### ISSUE TITLE
PlayerGRIS en mode autonome avec une fonction lecture à 16 canaux + 2 subs

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#109]
En discutant ici avec mes «associés» ou stagiaires, et en décrivant l'un des deux principes qui prévalaient à l'élaboration du ServerGRIS, à savoir une certaine forme de standardisation dans la présentation en concert des œuvres multiphoniques (possibilité de changer le dôme sans modifier la spatialisation), il m'est venu une idée que je trouve pas mal excitante. Imposer une configuration inaltérable VBAP à 16 canaux pour la diffusion.
Je pense par exemple à deux usages:
- faire circuler les œuvres domesques;
- établissement d'un concours de spatialisation pour dôme.

1. Circulation
Supposons que tu es dans ton lab avec 20 hp plus 2 subs (c'est l'équipement du studio de University of Florida où j'étais le week-end dernier).
Et que tu veilles faire circuler ta musique et permettre à des gens de l'écouter chez eux avec le ServerGRIS.
On pourrait imposer une configuration par défaut inaltérable à 16 canaux (plus 2 subs).
Ainsi d'un côté, le compositeur enregistre sa pièce sous ce format.
Et l'auditeur de son côté, l'écoute également sous ce format en écoute binaurale.

L'idée que j'ai eue, c'est la suivante: permettre l'utilisation du ServerGRIS en mode autonome.
Autrement dit, ajouter une fonction qui permette d'ajouter directement un fichier audio dans un lecteur audio multipiste.
Soit pour le concert, soit pour l'écoute binaurale.
Un DAW ne serait plus nécessaire dans cette équation.

Par exemple, Empreintes DIGITALes, qui bénéficie déjà d'une offre d'abonnement en streaming de son catalogue en stéréo, pourrait ajouter une fonction pour les musiques multipistes et on pourrait ainsi les faire circuler.
Les gens en écoutent un bout, aiment cela et achètent le fichier multipiste.
Même chose pour les appels d'œuvres pour les festivals.

2. Concours
L'idée d'un concours d'œuvres multipistes me trotte dans la tête depuis longtemps.
Mais comment accommoder tous les formats possibles?
En imposant un standard.
16 hp + 2 subs.
Ainsi les participants, quel que soit leur format de base, le réduisent (ou l'augmentent) en 16 pistes (plus deux subs) et envoient leurs musiques sous ce format.
À l'autre bout, le jury place le fichier 18 canaux dans le server et le joue sur les 18 hp d'Hexa.
Ou en font une écoute binaurale chez eux pour une présélection par exemple.

**Comment by led78** [comment]
Excellente idée! Je suis content qu'on le propose (format standard). Vivement un concours, il en faut plus et on a les installations pour le faire. Ces idées s'inscrivent tous dans une stratégie de démocratisation de la musique spatiale. C'est la prochaine étape si on veut que les outils du GRIS fassent leur chemin et qu'il y ait un approfondissement de la composition spécifique à ce médium de diffusion.
C'est en effet pas mal excitant comme idée.

**Comment by Xon77** [comment]
L'utilisation du ServerGRIS en mode autonome, qui permettrait de lire et échanger facilement de la musique spatialisée, est une très bonne idée.

Concernant le concours, il existe aussi un concours de mixage spatial en France, qui s'appelle : mixage fou
[](http://www.mixagefou.com)
Une banque de sons et des outils sont fournis et le concours consiste à réaliser à partir de ces éléments une création sonore originale spatialisée de 80 secondes. Comme leur outils propose différents standards, ce concours propose plusieurs catégories de spatialisation : STEREO, BINAURAL, 5.1, AURO 3D 9.1, AMBISONIC.

**Comment by Xon77** [comment]
http://www.mixagefou.com

**Comment by led78** [comment]
Suite à mon expérience à Hambourg et après avoir discuté avec Daniel Courville, je réalise l'importance d'être le plus autonome possible lors des présentations. En ce sens, un mode de lecture autonome dans le ServerGRIS serait le bienvenue. Toutefois, tous les dômes ne sont pas identiques et présentes parfois des différences considérables quant à la position des hautparleurs. C'était le cas à Hambourg notamment. C'est pourquoi je crois qu'un mode de lecture autonome doit absolument impliquer l'ajout de paramètres permettant la calibration de dernière minute, dans le lieu de diffusion, lors d'un soundcheck par exemple. Ainsi, le mode de lecture devrait permettre le contrôle du niveau de sortie pour chaque canal ou groupe de canal (une couronne d'hautparleur par exemple) ainsi que des EQ pour adapter les fréquences de coupures des hautparleurs et des subs, selon l'équipement sur place.

Par exemple, à Hambourg, leur dôme était en forme de balle fusil: trois couronnes rapprochées, puis une beaucoup plus élevée avec une «voix de Dieu» tout en haut. En écoutant et en m'informant, j'ai réalisé que le système n'était pas calibré pour compenser l'amplitude en fonction de la distance. Avec les coordonnées des hautparleurs, les plus récents décodeurs ambisoniques font la compensation ce qui n'est pas le cas du VBAP -- il faut le faire à la mitaine. Je ne sais pas s'il y aurait moyen, avec l'ajout d'un modèle de spatialisation asymétrique, d'intégrer des corrections à l'aide de délais courts et l'amplitude de sortie à une spatialisation VBAP.

Aussi, toujours à Hambourg, une des couronnes de hautparleurs comprenait deux HP plus bas et plus près du centre que les autres due à des contraintes d'espace. J'ai donc du appliquer une correction au niveau de sortie à l'oreille. Toutefois, puisque j'avais les coordonnées exactes, cela aurait pu être fait d'avance et plus précisément si le spatialisateur pouvait prendre en compte ces variations pour les canaux de sortie.

**Comment by Kurville** [comment]
Mon p'tit grain de sel: dans la suite de plug-in Ambisonic de I'IEM (Graz, Autriche), il y a depuis la version 1.4 un plug-in qui s'appelle DistanceCompensator. Ce plug-in n'est pas spécifiquement Ambisonic dans la mesure les entrées et sorties sont des signaux de haut-parleurs (jusqu'à 64 HPs). L'usager inscrit les données de distance des HPs et le plug-in calcule automatiquement les compensations de délais et de gain. L'usager peut choisir d'utiliser les deux compensations ou l'une ou l'autre seulement. https://plugins.iem.at

![capture d ecran le 2018-06-29 a 16 40 04](https://user-images.githubusercontent.com/29205070/42113995-650de892-7bbb-11e8-8417-5ce6e4631b51.png)

**Comment by belangeo** [comment]
Plus je réfléchi à ceci, plus je considère que la place de ce "player" autonome n'est pas dans le SpatGris (le logiciel parce que sa place est clairement dans les outils de la suite "SpatGris"!). Surtout si on veut ajouter les ajustements par piste que propose David (gain, eq, delai). On devrait selon moi envisager une nouvelle application, beaucoup plus simple que SpatGris, qui ne ferait que la lecture de pièces spatialisées (multipistes ou binaurales) avec paramètres de contrôle en sortie. Qu'en dites-vous?

**Comment by Normandeau** [comment]
Bien d'accord avec cela.

**Comment by Normandeau** [comment]
V3.1.12
Le PlayerGRIS s'est développé considérablement ces derniers temps. Avec un principe de fonctionnement pas mal plus élaboré, basé notamment sur la lecture de la position des hp originaux afin de reconstituer l’emplacement des sources enregistrées dans n'importe quel dispositif d'écoute. Cela va permettre une grande flexibilité dans l'usage des musiques multipistes et dans leur diffusion.
Cet outil, proche d'une première finalisation avait été imaginé en février 2018! Bravo à tous ceux qui ont mis la main à la roue dans l'intervalle!
