### ISSUE TITLE
Radius à 1 pour les sorties directes en VBAP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#128]
Une des conséquences de l'ajustement du Radius à 1 pour tous les hp en mode VBAP, c'est que les sorties directes se retrouvent sur le cercle des hp, ou plus précisément sur la surface du dôme. Dans la mesure où les sorties directes ont deux fonctions, soit d'alimenter les subs, et/ou  d'alimenter des hp périphériques, sur le plan graphique, on perd quelque chose ici.
Puisque les sorties directes ne sont pas prises en charge dans le VBAP, on pourrait retrouver la fonction Radius pour les sorties directes. 
On pourrait l'appeler autrement peut-être, pour ne pas créer de confusion: Distance?

**Comment by led78** [comment]
Distance me semble un bon terme.

**Comment by belangeo** [comment]
Ok.

**Comment by belangeo** [comment]
C'est fait, "Radius" pour le mode LBAP et "Distance" pour les modes VBAP. Dans le cas de la distance, seulement les HPs faisant partie de l'algorithme de spatialisation sont normalisés à 1.0.

**Comment by Xon77** [comment]
Il est désormais possible d’ajuster la distance des sorties directes en VBAP. Et le mot « Radius » a été changé en « Distance » pour le mode VBAP. Donc, cet issue pourrait être fermé.

Mais pourquoi conserver Radius pour le mode LBAP ? Il est de toute façon incontrôlable. 
Pourquoi ne pas avoir à la place de Radius un "vrai" paramètre de distance aussi en LBAP ? 

Il est vrai que concernant la configuration spatiale en LBAP (forme carré…), on pourrait préférer l’assignation sous forme cartésienne X,  Y et Z , alors que pour la configuration de dômes, la forme polaire avec Azimuth Elevation et Distance paraît plus appropriée.
