### ISSUE TITLE
CUBE et Son sur tous les hp d'un niveau en LBAP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#129]
V 2.00
J'ai fabriqué mon premier cube!!! Enfin presque. Ce n'est vraiment pas intuitif. Il nous faudrait une fonction comme celle qui nous permet en VBAP de créer automatiquement un cercle. Ici, ce serait un carré ou un rectangle. Mon cube a 16 hp, huit en bas et huit en haut.
Mon premier réflexe a été d'étendre certains hp d'un cercle vers les coins éloignés. Erreur. Le SpatGRIS ne se rend pas dans l'espace où le rayon est supérieur à 1. Donc si le hp d'un carré a un rayon supérieur à 1, il est inaccessible. Le carré doit donc être fabriqué à l'intérieur du cercle. À noter.
Ensuite, après voir fait ce cube, je déplace le son dans l'espace ainsi créé et je me rends compte que dès que le son atteint un groupe de hp, tous les hp de ce palier sont excités. Je n'ai pas écouté car je suis dans un chambre d’hôtel avec les hp de mon ordi. Mais je mesure et il ne semble y avoir qu'une différence maximale de 18 dB environ entre le hp le plus fort et le hp le plus faible. Entre les deux paliers, les 16 hp fonctionnent en même temps. Pas certain que ça soit très efficace pour la localisation...
Comme je sais que aimez le cinéma, j'ai tourné une vidéo. Elle est ici:
https://www.dropbox.com/home/GRIS/Crash%20Report%20ServerGRIS?preview=ServerGRIS+Dome+vs+Small+Cube.mov

PS Cela a été fait dans Reaper. Comme on peut le voir le Radius s'écrit pour chaque source. Cela est rapporté une issue de SpatGRIS 1.02.

**Comment by belangeo** [comment]
+1 pour la génération automatique de carrés ou de rectangle!

Pour ce qui est de la répartition du signal entre les HPs, le fonctionnement des algos 3D (le DBAP fait la même chose) est que tous les HPs participent dans la position d'une source. Dans le cas du LBAP, si le son est sur le niveau d'élévation d'un cercle (ou d'un carré), les autres niveaux sont éteints. Dès que l'élévation de la source se trouve entre deux niveaux, une pondération est effectuée et les HPs des deux niveaux participent à positionner la source dans l'espace. Ça fait beaucoup plus de HPs qu'avec le VBAP. 

Présentement, comme les "span" ne sont pas encore implémentés (je vais y travailler aujourd'hui), les niveaux d'intensité des HPs sont générer pour éliminer les "trous" entre les HPs lorsque la source se déplace. Je veux me servir des "span" pour élatgir ou rétrécir le coulement du son dans les HPs autour de la position de la source. Je vous revient sous peu à ce sujet.

**Comment by belangeo** [comment]
Les "span" sont ajoutés au LBAP, ce qui offre beaucoup plus de contrôle sur la répartition du signal dans l'espace. On paufinera au besoin après expérience en situation réelle.
