### ISSUE TITLE
Sorties directes non comprises dans le mixage STEREO

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#130]
Selon moi c'est un problème car souvent les sorties directes correspondent aux fréquences graves (subs). Cela signifie que le mixage stéréo obtenu avec ServerGRIS sera toujours faible en grave. Je pense que les sorties directes devraient faire partie du mixage stéréo. Si quelqu'un ne veut pas de celles-ci, il y a toujours la possibilité de les muter.

**Comment by belangeo** [comment]
100% d'accord!

**Comment by Normandeau** [comment]
Réglé.
