### ISSUE TITLE
Dans le couple SpatGRIS/ServerGRIS, il n'y a pas d'entrées physiques possibles?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#131]
Bonjour,
J'ai reçu ce message la semaine dernière d'un utilisateur de ServerGRIS:
«I have a simple question for you, I’m working with live saxophone improvisation and spatial sound composition using spatgris plugin in reaper and 32 outs FireWire setup.    I use my interface inputs to process live playing, but when I’m running Servergris for a 3D dome setup my inputs are no longer available to me.. or are they (from Jack)?  
Can ServerGris take a live input from my interface?»

Mon premier réflexe a été de lui dire de se faire un Aggregate Device dans Audio/MIDI Setup. Mais Jack ne peut pas faire partie d'un Aggregate Device! En effet, comme on le voit ici, il n'est pas dans la liste des interfaces audio du Mac, alors que ServerGRIS est actif et Reaper également:
![capture d ecran 2018-09-10 a 17 33 18](https://user-images.githubusercontent.com/8959779/45325731-bb8d1880-b51f-11e8-8de3-046d4e0f0733.jpg)

J'ai fait une tentative infructueuse avec QJackCtl. Mais est-ce qu'on a envie de revenir à cela? On voit QJackCtl dans ServerGRIS, mais on ne peut pas le rendre actif. Quelqu'un a-t-il une proposition? Peut-on offrir, en même temps, deux entrées dans ServerGRIS: un DAW et une interface?

Alors à moins que je ne me trompe, on a ici un sacré problème: il est actuellement impossible de brancher une source audio physique dans notre dispositif!!! C'est une lacune assez importante...

**Comment by belangeo** [comment]
En effet, jack ne voit que les composantes software qui se connectent sur le pilote JackRouter. Il est probablement possible, à l'interne, de connecter system:capture_1, system:capture_2, etc. aux entrées du ServerGris. Peut-être quelque chose dans les préférences comme ceci (pour connecter les entrées physiques 3 et 4 aux entrées du Server 18 et 19):

Capture 1 :    None
Capture 2 :    None
Capture 3 :    18
Capture 4 :    19 
...
...

**Comment by Xon77** [comment]
Pour moi, un possible hack aurait été de passer par QJackCtl, mais pas en le rendant actif dans le ServerGris, mais en faisant directement les connexions sur le bouton connect de la fenêtre de QJackCtl, du system (Capture 1...) vers les inputs de Reaper. 

Cependant, j'ai essayé et le son en cours d'enregistrement dans Reaper n'est pas transmis dans le server... Il faut que le son enregistré soit déjà sur la piste pour être envoyé vers le serveur et spatialisé.

L'enregistrement du son dans Reaper doit apparemment venir après l'envoi du son des pistes de Reaper vers le server.

**Comment by Normandeau** [comment]
Vient de faire une série de tests. En fait tous les séquenceurs permettent d'avoir une interface différente en entrée et en sortie. Il est donc possible de mettre l'interface en entrée et JackRouter en sortie. Il faut cependant s'assurer de diminuer la taille du buffer dans le ServerGRIS et de mettre la même valeur dans le séquenceur. Tests réalisés avec une valeur de 128. Ça pompe pas mal de CPU, mais ça fonctionne.
Testé avec Reaper (même si c'est une fonction «Legacy» ça fonctionne très bien), Live et Logic.
Curieusement, même si DP permet la double association, mais dès qu'on choisit l'interface et Jack, la connexion avec ServerGRIS est perdue.
Au sujet de la note précédente, il faut choisir le bon mode de monitoring input (il y en a deux: haut-parleur bleu ou vert. Il faut choisir le bleu) dans Reaper pour que que ça fonctionne:

![capture d ecran 2018-10-02 a 09 42 48](https://user-images.githubusercontent.com/8959779/46353414-1fd85f00-c62a-11e8-9a58-296c76ef30e3.jpg)


![capture d ecran 2018-10-02 a 09 59 33](https://user-images.githubusercontent.com/8959779/46353345-edc6fd00-c629-11e8-844a-e0bca32b9d05.jpg)

**Comment by Normandeau** [comment]
Fermé pour le moment. On pourra revérifier tout cela lorsqu'on aura une version de ControlGRIS.
