### ISSUE TITLE
Spatialisation du LBAP

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/SpatGRIS#132]
En testant la spatialisation du LBAP (hormis le contrôle des trajectoires), je m'aperçois d'un phénomène étrange : 

Un son central (en bas ou en haut) (avec elevation span à 0) paraît devant / frontal.
(Plus d’énergie dans les paires avant 1 et 2, comme on peut le constater ci-dessous - ne considérer que le point rouge au centre et non celui sur le côté)

<img width="1279" alt="capture d ecran 2018-09-17 a 18 07 45" src="https://user-images.githubusercontent.com/1010040/45704913-248b1680-bb46-11e8-9fbc-ebdbdec57f6c.png">

On ressent l’élévation avec le radius, mais le son paraît toujours devant, si le son 1 est en haut au centre.

<img width="920" alt="capture d ecran 2018-09-17 a 18 05 17" src="https://user-images.githubusercontent.com/1010040/45704951-3e2c5e00-bb46-11e8-9bdd-798917399bd1.png">

**Comment by Normandeau** [comment]
C'est parce que tu utilises Reaper qui ne supporte pas les pistes monophoniques. Pour spatialiser correctement un fichier mono, il faut panner complètement la piste à gauche ou à droite pour éviter que le son n'entre dans le ServerGRIS par les entrées 1 et 2. Cela résout le problème.
On n'a pas ce problème avec DP ou Logic dans lesquels on peut mettre des pistes mono.
