### ISSUE TITLE
Save et Save as: seulement quand on change quelque chose

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#133]
J'aimerais qu'on résolve la situation des Save et Save as dans le ServerGRIS. En fait c'est un problème depuis le début. ServerGRIS n'arrête pas de nous demander si on veut sauvegarder les documents quand on ferme soit la fenêtre d'édition des haut-parleurs ou le serveur lui-même, même si on vient juste de les sauvegarder ou de ne rien changer. Lorsqu'on ferme le serveur en fin de session, ce n'est d'ailleurs pas un Save qu'il nous demande mais plutôt un Save as, car il ouvre une fenêtre qui nous permet de changer son nom.
Je suggère:
- qu'un Save ou un Save as effectué à partir du menu File corresponde à ce qu'on trouve sur tous les logiciels, à savoir que le document est sauvé, pas besoin de le sauver à nouveau.
- qu'une configuration de Speaker Setup **si elle n'est que consultée** en ouvrant la fenêtre Show Speaker Setup Edition Window (d'ailleurs ce nom pourrait être raccourci en Speaker Setup Edition) ne mène plus à la question de savoir si on veut sauvegarder.
La confusion actuelle mène plus ou moins toujours à la question: est-ce que j'ai vraiment changé quelque chose?
Et tant qu'à y être, puisqu'on a les trois petits points rouge, jaune et vert, pourquoi ne pas être conforme avec les autres applications Mac: quand un changement est apporté dans la configuration, un point noir est placé au centre du point rouge, nous avertissant que le document a été modifié et qu'on devrait le sauver.
![point rouge](https://user-images.githubusercontent.com/8959779/46350235-3d092f80-c622-11e8-9aec-0981d96452cc.jpg)

**Comment by belangeo** [comment]
> Et tant qu'à y être, puisqu'on a les trois petits points rouge, jaune et vert, pourquoi ne pas être conforme avec les autres applications Mac: quand un changement est apporté dans la configuration, un point noir est placé au centre du point rouge, nous avertissant que le document a été modifié et qu'on devrait le sauver.

Juce n'offre pas d'accès vers le point rouge (qui est spécifique à la plateforme MacOS). Si c'est vraiment souhaité, je peux toujours ajouter des "*" autour du nom du fichier dans la barre de titre s'il est modifié, seulement, dans le cas du projet, c'est pas pire chiant puisqu'il faut attraper toutes les manipulations de l'interface indépendamment. C'est pas comme s'il y avait un seul document de modifié!

**Comment by Normandeau** [comment]
Ok on laisse tomber le point rouge. Mais si on peut corriger les multiples Save, ce serait bien.

**Comment by belangeo** [comment]
C'est fait!

**Comment by Normandeau** [comment]
Version 2.01
Speaker Setup
Ce que je constate actuellement, c'est que si je dis NO après avoir effectué des changements, les changements s'appliquent quand même au setup actuel. Le setup lui-même n'est pas sauvegardé sur le disque dur, mais les changements demeurent dans le document ouvert. Ma compréhension du NO veut que non seulement le document sur le disque ne soit pas sauvegardé, mais qu'en plus les changements apportés, que je ne veux pas sauvegarder, soient tout simplement annulés après le NO, comme un UNDO en fait. Possible?
Sinon, après chaque essai de changement, si je veux revenir au setup originel, je suis obligé de rappeler le document sur le disque dur.

Server document
Même après avoir sauvegardé un projet Server, lorsque je ferme le ServerGRIS (immédiatement après, donc sans avoir rien modifié), j'ai toujours cette fenêtre qui s'ouvre:
![capture d ecran 2018-11-03 a 11 27 39](https://user-images.githubusercontent.com/8959779/47954025-a64ecc00-df5b-11e8-9ff7-1bd336ad46fd.jpg)

**Comment by belangeo** [comment]
> Speaker Setup
Ce que je constate actuellement, c'est que si je dis NO après avoir effectué des changements, les changements s'appliquent quand même au setup actuel. Le setup lui-même n'est pas sauvegardé sur le disque dur, mais les changements demeurent dans le document ouvert. Ma compréhension du NO veut que non seulement le document sur le disque ne soit pas sauvegardé, mais qu'en plus les changements apportés, que je ne veux pas sauvegarder, soient tout simplement annulés après le NO, comme un UNDO en fait. Possible?

Yep. Je peux faire un backup du setup courant à l'ouverture de la fenêtre et le rétablir sur le NO.

> Server document
Même après avoir sauvegardé un projet Server, lorsque je ferme le ServerGRIS (immédiatement après, donc sans avoir rien modifié), j'ai toujours cette fenêtre qui s'ouvre:

Changement effectué après la version 2.0.1!

**Comment by Normandeau** [comment]
Version 202
«Yep. Je peux faire un backup du setup courant à l'ouverture de la fenêtre et le rétablir sur le NO.»
À faire.

**Comment by Normandeau** [comment]
V203
Sauvegarde de SpeakerSetup et de Server Document
Réglé.
