### ISSUE TITLE
Open documentation ne marche plus sous OSX

### ISSUE THREAD

**Issue by belangeo** [GRIS-UdeM/SpatGRIS#134]

**Comment by Xon77** [comment]
Pour moi, cela fonctionne sous OSX (version 2.01). La documentation s'ouvre bien.

**Comment by Normandeau** [comment]
Je viens de trouver la raison. J'ai gardé les deux versions de ServerGRIS: 1.04 pour travailler et 2.01 pour tester. J'ai renommé cette dernière version ServerGRIS Beta et c'est à cause du changement de nom que ça ne marche plus. Si je renomme la 2.01 ServerGRIS et que la version 1.04 devient ServerGRIS Stable, c'est la même chose avec cette dernière, le manuel ne s'ouvre pas.
Donc il ne faut pas changer le nom de l'application, ou se passer du manuel dans une des deux versions.

**Comment by Normandeau** [comment]
Étrange, mais pas un problème pour l’utilisateur, puisque celui-ci n'aura qu'une version valide du ServerGRIS en même temps.
Il faut juste le savoir pour nous, qui testons des versions bêta.
