### ISSUE TITLE
Text box X, Y et Z ne fonctionne plus dans la page Speaker Setup

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#135]
V. 2.01
Je révise le scénario de David pour la vidéo sur YouTube, et je me rends compte qu'on ne peut plus entrer les données X, Y et Z dans la page Speaker Setup. Seules les entrées Azimuth, Zenith et Distance sont disponibles. Cela que l'on choisisse VBAP ou LBAP comme algorithme. Alors que cela fonctionne dans la version 1.04.
Une raison à cela?

**Comment by belangeo** [comment]
Je ne me souviens plus où ça a été discuté mais on était d'accord pour garder les valeurs X-Y-Z seulement comme témoins dans la fenêtre d'édition des speakers.
Si je me souviens bien, la boucle de conversions automatisées (azi-ele-rad -> X-Y-Z -> azi-ele-rad -> ...) créait beaucoup plus de problèmes qu'elle n'en réglait!

**Comment by Normandeau** [comment]
D'accord, mais ta réponse soulève encore une fois la question fondamentale. Là où je parlais des paramètres Azimuth, Zenith et Distance, tu me réponds en parlant de azimuth-elevation-radius! C'est pourtant la première dénomination qui est affichée dans le Server! Cette question, à la fois terminologique et conceptuelle, est vraiment au cœur de notre développement. Si on fait une goofe, ça va être difficile à rattraper.
Je vais tenter de faire un inventaire de la manière utilisée par les autres.

**Comment by NicolaGiannini** [comment]
Bonjour,
J'avais analysé la question terminologique et j'avais  trouvé les informations suivants dans les documentations en ligne.

Fb360 audio360 spatialiser plug-in: azimuth, elevation distance

Spat Revolution :  azimuth, elevation distance (et xyz)
ircam panoramix : azimuth, elevation distance
MNTN : dans le manuel ils parlent de azimuth, elevation dans leur type de visualisation 2D.

IEM Plugin Suite azimuth, elevation roll (je crois à la place de distance)
Spatial Audio Designer = xyz

**Comment by belangeo** [comment]
Azimuth - Elevation - Distance me plaît bien! Il faudrait décider assez vite, j'ai déjà pas mal de « radius » dans le code du SpatGris 2.0 ! Je vais renommer les variables pour que le code reflète bien la réalité.

**Comment by Normandeau** [comment]
Ok, dans ce cas-là, il faudrait unifier les paramètres de réglages entre ControlGRIS et ServerGRIS.
Actuellement le premier utilise effectivement Azimuth-Distance-Elevation.
Mais le second utilise Azimuth-Zenith-Radius.
