### ISSUE TITLE
Affichage ServerGRIS d'un écran à l'autre, spécialement en mode 4k

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#137]
J'essaie de faire une capture d'écran pour la vidéo tutoriel du ServerGRIS, mais je me bute au fait que le ServerGRIS plante systématiquement 1 ou 2 secondes après avoir activé le Show 2D View. Je vais devoir sauter par dessus cette option en attendant que le problème soit réglé. Sinon, je peux toujours utiliser une ancienne version du ServerGRIS, car je crois que ce problème n'existait pas auparavant.

**Comment by Normandeau** [comment]
Il va falloir documenter cela plus précisément car je n'ai vraiment pas de problème. J'ai même fait une présentation complète au colloquium avec les deux fenêtres ouvertes sans aucun problème.

**Comment by led78** [comment]
Il semble que cela se produise que sur mon Mac Pro et non mon Macbook. Je vais essayer de voir pourquoi.

**Comment by led78** [comment]
AJOUT - Le plantage systématique survient seulement lorsque mon logiciel de division de l'écran est actif. Cela a pour cause de redimensionner automatiquement les fenêtres ouvertes et la fenêtre 2D View n'aime pas cela j'ai l'impression.

**Comment by Normandeau** [comment]
Dans le même ordre d'idée (peut-être), j'avais remarqué que lorsque l'on possède deux écrans, qu'on met ServerGRIS sur le second écran, qu'on ferme ce dernier et ensuite l'écran, et qu'on rouvre ServerGRIS, il n'apparaît pas! Enfin, presque pas. Il est complètement tassé dans la coin droit inférieur et si le bureau est un peu encombré (j'ai fait un peu de ménage ici), on ne le voit pas:

![servergris 2e ecran](https://user-images.githubusercontent.com/8959779/48678344-f7f87880-eb4f-11e8-867e-5dc60830651d.jpg)

**Comment by Normandeau** [comment]
Version 202, passage de deux écrans 4k à un écran Retina (2880X1800) avec un second écran de 1680X1050.
Dans cette nouvelle version, on n'a même pas droit à un petit bout de fenêtre, rien n'apparaît dans aucun des deux écrans. Même en essayant d'ouvrir un autre document, celui-ci n'apparaît pas aux écrans. La seule manière de faire apparaître la fenêtre est de débrancher le second écran de l'ordinateur. La fenêtre du server apparaît alors et reste sur l'écran principal, même après avoir réactivé le second moniteur.

**Comment by Normandeau** [comment]
V203
Même situation.

**Comment by Normandeau** [comment]
V205
Cas encore plus intéressant. Je passe du travail à la maison où j'ai deux écrans 4k que j'utilise en mode plus ou moins Retina (3360X1890, soit un peu moins que 4K, sans l'écran du Mac cependant, qui reste fermé). ServerGRIS est affiché sur l'écran de droite: je peux mettre mon speaker setup et 96 inputs. Pas mal non? Puis j'arrive à fac, et j'ouvre Server GRIS sur l'écran de mon Mac Retina, résolution maximale. Rien. ServerGRIS est bien affiché dans la barre des menus, mais aucune fenêtre n'est visible, même pas un petit bout dans le coin inférieur droit.
Je réduis donc la résolution à la valeur moyenne et je vois ceci:
![capture d ecran 2019-02-10 a 10 38 56](https://user-images.githubusercontent.com/8959779/52535815-ee327b80-2d20-11e9-88e0-ad882b885793.jpg)

Pas très pratique, parce que je n'ai pas accès à la barre de menus de ServerGRIS, donc je ne peux rien faire: ni déplacer ni changer de dimension. Pas d'autres choix que de diminuer la résolution de l'écran au minimum, pour finalement avoir accès à la fenêtre complète du Server et la déplacer où je veux.

**Comment by Normandeau** [comment]
Faut vraiment régler le problème de l'affichage avec ServerGRIS. Ça se présente chaque fois que je change de configuration. Irritant.

**Comment by Normandeau** [comment]
V208
Cela semble réglé. Comme cela a commencé en novembre 2018, on va prendre une pause!
