### ISSUE TITLE
Elevation en mode LBAP: toujours un dôme

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#139]
En mode LBAP, l'élévation est toujours contrainte par la forme d'un dôme. Lorsqu'on utilise le mode LBAP dans ControlGRIS, on peut effectivement placer une source dans les coins du carré en bas, mais lorsqu'on élève la source, celle-ci se rapproche toujours du faîte du dôme, au centre. On ne peut pas placer ni un hp, ni une source dans un coin supérieur.

**Comment by belangeo** [comment]
C'est réglé!

**Comment by Normandeau** [comment]
Bonne nouvelle. On a hâte de tâter cela!

**Comment by belangeo** [comment]
Aussi réglé pour la position des HPs.
