### ISSUE TITLE
Graphique des hp: étrange en LBAP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#142]
V202
Remarquez l'orientation des hp, indiquée par la petite barre grise, lorsqu'on est en mode LBAP dans ce cube de 24 hp. Ceux du bas sont orientés vers le centre, mais ceux du haut (Elevation: maximale: 90) sont orientés vers le bas:
![orientation des hp](https://user-images.githubusercontent.com/8959779/50521603-7839c400-0a94-11e9-88ae-e8fe3faf68ad.jpg)

C'est comme si tous les hp du haut étaient des douches verticales, alors que ceux du bas sont dirigés directement vers le public.

Cela est probablement un vestige du dôme, car on le voit ici, avec une élévation de 45, l'inclinaison se profile peu à peu à la manière des hp du dôme:
![capture d ecran 2018-12-28 a 11 37 41](https://user-images.githubusercontent.com/8959779/50521768-3a896b00-0a95-11e9-886e-bc88563bd101.jpg)

À corriger.

**Comment by belangeo** [comment]
Corrigé.
