### ISSUE TITLE
Abandon de l'idée d'avoir des hp en double

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#143]
V202
Je reprends ici une question de l'issue no 50:
«L'avertissement des numéros de sorties utilisés est en place. Une question cependant: qu'est-ce qui se passe si on ignore l'avertissement? Je me retrouve avec deux hp qui ont la même sortie. Peut-être que c'est une caractéristique utile: lorsqu'on on joue sur un plus petit acousmonium, on peut réattribuer certains hp aux mêmes sorties. Je pense surtout au mode LBAP bien évidemment. Mais je me demande si ce n'est pas là une source potentielle d'erreur.»
**Réponse c'en est une!!!**

Quelques exemples de bogues ou de comportements que cela occasionne:

1. Message à l'ouverture du ServerGRIS, lorsqu'un utilisateur n'a pas réglé le problème des doubles sorties:
![duplicated output numbers](https://user-images.githubusercontent.com/8959779/50539862-81d73080-0b55-11e9-9d9f-ee1e6e42eef1.jpg)
• Agaçant.

Problèmes de compatibilité avec des Speakers Setups réalisés avec la version 1.04.

2. Des hp fantômes sont créés.
Remarquez bien 25 et 26. Ils sont répétés à deux reprises mais ne correspondent à rien dans le dôme de hp.  Ce sont des copies fantômes dont on ne peut changer rien. Les trois hp correspondant à 25 par exemple adoptent toujours les mêmes réglages et si on essaie d'en effacer un, on fait crasher ServerGRIS.

![hp fantomes 202](https://user-images.githubusercontent.com/8959779/50539886-d2e72480-0b55-11e9-96ac-f645946a658d.jpg)

Vérification faite du Speaker Setup d'origine, ouvert par ServerGRIS 1.04 avec lequel il a été créé.
On peut voir qu'il y a effectivement un doublon dans les IDs 25 et 26. Cependant dans le setup originel, ils étaient tous associés à des sorties différentes, alors qu'avec la version 202, les ID 25 et 26 fantômes ont été ramenés aux valeurs des hp qui n'étaient pas des sorties directes.
Donc première question: comment cela se fait-il? Comment peut-on avoir des IDs identiques?

![hp fantomes 104](https://user-images.githubusercontent.com/8959779/50539910-4426d780-0b56-11e9-8aa0-fe879610d2bc.jpg)

3. Entrées et sorties vides
Avez-vous déjà vu un affichage de la sorte? Alors qu'il y a un dôme de 32 hp et 32 imputs dans le système.

![inputs-outputs vides](https://user-images.githubusercontent.com/8959779/50539949-d929d080-0b56-11e9-89b8-376ecca2abfb.jpg)

4. Des trous dans les sorties
Avez-vous déjà vu un affichage de la sorte? Avec un trou dans la liste des sorties?

![coupure dans les sorties](https://user-images.githubusercontent.com/8959779/50539968-1726f480-0b57-11e9-9d48-2870b4317f98.jpg)

**Donc on abandonne l'idée d'avoir des sorties en double et on revient à la formule originale qui prévient l'utilisateur lorsqu'il essaie d'utiliser un numéro de sortie qu'il a déjà utilisée.** 
Encore une fois, il faut revenir à l'essentiel: est-il possible de satisfaire un besoin autrement qu'en le mettant dans le ServerGRIS? Ici, l'utilisateur n'a qu'à placer des numéros de sortie fictif au moment de la construction du dôme. Il mettra ensuite les bonnes valeurs, ce qui lui évitera d'avoir un message d'erreur.

**Comment by led78** [comment]
Je n'ai pas fais ces tests, mais je peux dire que je n'ai jamais vu des affichages de la sorte auparavant. Il me semble que l'idée était non pas d'avoir une duplication des speaker ID, mais de pouvoir assigner certains hautparleurs à la fois comme sorties directes et comme faisant partie de l'environnement spatialisé.
Par exemple, lorsque je cherche un son dans ma banque de son et que je veux pouvoir l'éditer avant de l'ajouter à ma session de travail, mais que le ServerGRIS m'empêche de pouvoir l'écouter en dehors d'un client connecté. Je créer alors des faux hautparleurs (nouvel ID) connectés à des outputs qui n'existent pas dans l'environnement d'hautparleur. Grâce au TotalMix de la RME, je peux néanmoins récupérer ces sorties pour les réassigner aux hautparleurs 1-2 de l'environnement réel, afin d'entendre ce qui joue dans l'éditeur. C'est une façon de contourner le ServerGRIS pour entendre ce qui ne fait pas partie du projet spatialisé, dans une logique multiclient.

Puisque ce n'est pas tout le monde qui utilise une interface RME avec TotalMix et que ce n'est pas très intuitif, je me questionnais sur la meilleure façon de permettre une écoute directe sans ajouter des faux hautparleurs virtuels et TotalMix. Il y a peut-être une meilleure façon de permettre cela.

**Comment by belangeo** [comment]
J'ai repris la logique initiale qui interdit d'utiliser un numéro de sortie déjà utilisé mais ne l'applique pas aux sorties directes. Il est donc possible d'utiliser une sortie à la fois dans le calcul du dôme et en sortie directe.

**Comment by Normandeau** [comment]
Excellent.

**Comment by Normandeau** [comment]
V203
Réglé.
