### ISSUE TITLE
Ajout du symbol ° (degrés) dans la fenêtre "speakers set up edition"

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#144]
Dans la fenêtre "speakers set up edition" je crois il pourrait aider de avoir le symbol ° à côté des chiffres indiquantes Azimuth et Elevation en considérant qu'ils sont degrés. Cela pourrait aussi aider afin de savoir c'est quoi le range des valeurs qu'on peut indiquer. On pourrait assi ajouter les valeurs du range.

**Comment by belangeo** [comment]
Je ne suis pas convaincu... D'une part, ce symbole ne fait pas parti des symboles ASCII, ce qui risque d'occasionner des problèmes d'affichage dans diverses circonstances (sous Windows nottament et sur des systèmes où la langue par défaut gère mal ce type de symbole). D'autre part, si quelqu'un en est rendu à construire un setup de HPs, je pense qu'on peut assumer qu'il va vite figurer que c'est des degrés, ou qu'il ira lire le manuel!
