### ISSUE TITLE
"Click and scrolling" et "Control Click" dans la fenêtre "speakers set up edition"

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#145]
Je donnerai la possibilité de changer les valeurs des chiffres aussi en faisant click et scrolling de haut en bas sur la chiffre même, et de voir les déplacements des haut-parleurs en temps réel. Cela est en relation avec le issue 48 "HP draguable dans la vue 3D"

https://github.com/GRIS-UdeM/ServerGRIS/issues/48

**Comment by NicolaGiannini** [comment]
Je donnerai la possibilité aussi de sélectionner plusieurs valeurs avec “Control click”,  et de les pouvoir modifier toutes ensembles.  Je voudrais par exemple sélectionner e modifier les “Elevation” d’un ring simultanément.

**Comment by belangeo** [comment]
C'est fait pour le click+scroll. La sélection multiple est un sujet plus complexe, implique plus de choses, c'est à réfléchir...

**Comment by belangeo** [comment]
La sélection multiple fonctionne dans la fenêtre d'édition des HPs. En sélection multiple, modifier une valeur sur une ligne modifie la valeur de cette colonne pour tous les éléments de la sélection. Avec le click+drag, si la touche Alt est enfoncée, plutôt que d'assigner la même valeur à chaque élément dans la colonne, la différence est ajoutée indépendamment à chaque élément (valeur relative).

**Comment by Normandeau** [comment]
V 2.03
Added multiple selection in the speaker edit window (part of issue GRIS-UdeM/SpatGRIS#145).
Le problème avec cette fonction c'est que si tu sélectionnes plusieurs hp en cliquant sur des variables ajustables (et elles le sont pratiquement toutes), alors tous les hp sont ajusté automatiquement à cette valeur (comme ici, où ma souris était placé sur la valeur X)!!!
Et comme on n'a pas d'Undo, la seule solution est de fermer sans sauver et  de recommencer.
N'y aurait-il pas moyen, au moyen de la sélection de plusieurs hp de bloquer les modifications de valeurs?

![capture d ecran 2019-02-05 a 09 53 16](https://user-images.githubusercontent.com/8959779/52281320-e7c09000-292b-11e9-84b4-6497c3fa6177.jpg)

**Comment by belangeo** [comment]
C'est réglé!

**Comment by Normandeau** [comment]
V211
Mis dans le manuel
