### ISSUE TITLE
La création d'une configuration de haut-parleurs non-concentriques est assez pénible sans les coordonnées cartésiennes.

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#148]
Dans la Speaker Setup Edition Window, il faudrait vraiment pouvoir créer plus rapidement des configurations de haut-parleurs non-concentriques en permettant la modification des coordonnées cartésiennes (x, y et z), car pour le moment c'est assez long et pénible à faire seulement à partir des coordonnées sphériques (azimuth, élévation et distance).
On pourrait aussi ajouter des boutons « Add array » (rangée de hp) et « Add Layer » (couche de hp), similaire au « Add ring », et permettre de copier des haut-parleurs (sauf leur ID et leur # output) et même des rangées et des couches entières, où l'on aurait simplement qu'à changer la valeur d'élévation pour créer plusieurs couches identiques.

Il y a surement d'autres possibilités d'améliorer la Speaker Setup Edition Window, mais je crois que ces améliorations sont assez essentielles si on veut pouvoir utiliser le ServerGRIS aussi facilement en LBAP qu'en VBAP.

**Comment by belangeo** [comment]
Un setup en LBAP peut être modifié avec X-Y-Z (incluant le drag+drop et la sélection multiple). C'est valeurs sont toujours inactives en VBAP puisque ça ne fait pas sens!

**Comment by led78** [comment]
Pourtant, j'ai beau essayer de double cliquer sur les valeurs X-Y-Z en mode LBAP et ça ne fonctionne pas, contrairement au paramètres Azimuth, Élévation et Distance. On parle bien de la V.2.0.2 ?

**Comment by belangeo** [comment]
Non, on parle des changements que j'ai faits aujourd'hui!

**Comment by Normandeau** [comment]
V203
Il est maintenant possible de modifier les valeurs X-Y-Z en LBAP. Excellent. Mais lorsqu'on est en VBAP, elle sont presque toutes bloquées, mais tout à fait. En fait, on ne peut pas les modifier en double-cliquant dans le Text Box pour entrer une valeur numérique, mais on peut en changer la valeur en «scrollant» la valeur, mais seulement celle de Z . Et en fait la seule valeur qui entre à ce moment-là c'est 0.9999, équivalent à une élévation de 90. Pourquoi Z est-il toujours actif en VBAP?

**Comment by belangeo** [comment]
Oups... Z ne devrait pas être actif en VBAP! Je vais corrigé ça!

**Comment by belangeo** [comment]
C'est réglé.
