### ISSUE TITLE
LBAP: Sorties stéréo seulement dans Reaper

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#150]
V.2.0.2

On l'avait mentionné lors de notre dernière rencontre, mais je ne trouve pas d'issue qui en parle directement:

Lorsque je positionne une source à un endroit précis de l'environnement de haut-parleurs, le niveau du signal envoyé aux HP (View - Show Speaker Level = ON) n'est pas cohérent avec le rayonnement attendu. Du moins, cela dépend de l'algorithme de spatialisation employé. Ici, je m'attendrais à un algorithme DBAP, ce qui n'est pas le cas apparemment.

Ici, on peut voir que la source se situe dans le coins supérieur droit de l'espace de diffusion. La rangée supérieur de hp semble bien distribuer le signal, tandis que la rangée du bas ne devrait transmettre aucun signal, ce qui n'est pas le cas:
![diffusion_lbap_1](https://user-images.githubusercontent.com/13606544/51281418-573c0300-19b0-11e9-8857-3c2f762798ba.jpeg)

La rangée inférieur semble donc toujours active, où que se situe la source sonore virtuelle.

En plus de cela, l'axe vertical de HP central qui semble également plus actif, par rapport aux autres. Mais, tout de même pas autant que ceux de la rangée du bas. Pour une même position de la source que l'exemple précédent, le HP de la rangée du centre, situé au 0° azimuth, reçoit du signal avant les HP situés plus proche de la source:
![diffusion_lbap_2](https://user-images.githubusercontent.com/13606544/51281419-57d49980-19b0-11e9-848c-cbf7173a1c7a.jpeg)

**Comment by belangeo** [comment]
Tu m'envoies le speaker setup s'il te plait!

**Comment by led78** [comment]
Voilà! 
[FrontWall_speaker_setup.xml.zip](https://github.com/GRIS-UdeM/ServerGRIS/files/2770066/FrontWall_speaker_setup.xml.zip)

**Comment by led78** [comment]
Bon! J'ai fini mon set-up d'environnement de diffusion asymétrique. Pour vous éviter le trouble, le voici:
[Asymetric_speaker_setup.xml.zip](https://github.com/GRIS-UdeM/ServerGRIS/files/2771042/Asymetric_speaker_setup.xml.zip)

Il semble que le problème ne soit que sur le plan frontal, comme le démontre cette capture:
![diffusion_lbap_3](https://user-images.githubusercontent.com/13606544/51356706-a144e780-1a89-11e9-94e4-379c28dbce75.jpeg)

**Comment by belangeo** [comment]
Sur les images, on ne voit pas la source 2 (azimuth = 0, élévation = 0 probablement). Ce ne serait pas elle, par hasard qui alimenterait les HPs du bas? Je viens de tester avec ton setup FrontWall et une seule source et  j'obtiens bien le résultat attendu.

**Comment by led78** [comment]
Ah! Je n'y avait pas pensé, mais maintenant que tu le mentionnes, je comprends pourquoi:

C'est la faute à Reaper! (Il faudra d'ailleurs ajouter une note là-dessus, peut-être dans le manuel)

En effet, Reaper offre un maximum de 64, au lieu de 128 comme les autres DAW (Logic et DP) car il force l'utilisation de deux canaux par piste, même en situation mono -- le signal est alors identique sur les deux canaux. Il n'y a donc jamais qu'un seul canal par piste dans Reaper, ce qui fait que si on n'indique qu'une seule source dans le ControlGRIS d'une piste Reaper, ce dernier envoi quand même deux canaux avec le signal dupliqué. Cela fait que nous avons quand même un deuxième signal, invisible puisque non spatialisé.

J'ai vérifié si cela se produisait aussi dans Logic et oui, c'est la même chose, lorsque ma piste est stéréo, mais pas lorsqu'elle est mono. Autrement dit, si j'envoi une piste stéréo de Logic au ServerGRIS, mais que j'indique dans le ControlGRIS de cette piste qu'il n'y a qu'une seule source spatialisée, la même chose se produit que dans Reaper. Mais, si je change la sortie de cette piste pour qu'elle soit mono, alors là la deuxième source invisible ne transmet plus de signal et tout redevient normal.

C'est pourquoi je dis que c'est de la faute à Reaper, puisque ce dernier ne permet pas d'envoyer qu'un seul canal par piste, mais toujours deux. Donc, pour les utilisateurs de Reaper qui voudraient spatialiser une source mono sans avoir ce problème de duplication de source (invisible et non spatialisée), il faudrait toujours indiquer qu'il y a 2 sources dans le ControlGRIS correspondant, et ensuite superposer ces deux sources l'une sur l'autre, puis activer tous les boutons link pour qu'ils ne deviennent qu'un seul objet spatial.

Est-ce acceptable d'ajouter une note de ce genre dans le manuel? Commentaires?

**Comment by Normandeau** [comment]
Une solution beaucoup plus simple pour Reaper, qu'on a déjà validé: placer le Pan complètement à gauche ou à droite. Ainsi pour les sorties 1 et 2, la première piste sera à gauche et la seconde piste sera à droite, assignées touyes les deux aux sorties 1 et 2 (puisqu'il n'est pas possible d'avoir une sortie mono dans Reaper). Et on utilise deux ControlGRIS, un pour chaque piste en mode 1X1 avec les valeurs 1 et 2 respectivement.

**Comment by led78** [comment]
Encore mieux!

**Comment by Normandeau** [comment]
V211
Mis dans la manuel.
