### ISSUE TITLE
Problématique liée au changement du mode de spatialisation pendant la création d'un Speaker Setup.

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#151]
Alors que je venais de terminer un gros Speaker setup asymétrique dans la Speaker Setup Edition Window (SSEW) et que je vérifiais l'assignation des haut-parleurs, un à un, à l'aide de la flèche (pavé directionnel), j'ai cliqué dans la fenêtre principale par accident, puis appuyé à nouveau sur la flèche. Cela a donc modifier le mode de spatialisation plutôt que de passer au haut-parleur suivant dans la SSEW. Ce faisant, puisque je n'avais pas encore sauvegardé ma configuration (je n'avais pas encore fermé la fenêtre SSEW), le changement de mode m'a fait perdre tout le travail effectué. En effet, si on passe du LBAP au VBAP, le ServerGRIS modifie dynamiquement la position des HP pour que ceux-ci respect les règles du VBAP. Quoiqu'il en soit, puisque je n'avais pas encore sauvegardé ma configuration, elle est revenue automatiquement à ce qu'elle était (incluant dans SSEW) lors de l'ouverture du ServerGRIS.

Cette situation est problématique... Serait-il possible que la SSEW garde temporairement en mémoire la travail en cours, tant que la fenêtre n'est pas fermée, ou qu'une véritable sauvegarde soit effectuée? Je me questionne sur la meilleure façon de remédier à cette situation.

**Comment by belangeo** [comment]
Je pourrais interdire le changement de mode lorsque la fenêtre d'édition est ouverte...

**Comment by led78** [comment]
Oui, mais il faudrait alors ajouter une fenêtre qui demande à l'utilisateur le type d'environnement de haut-parleurs qu'il compte créer (dôme ou pas) au moment où celui-ci ouvre la SSEW. Sinon, l'utilisateur risque de ne pas faire le lien s'il n'a pas d'abord modifier le mode de spatialisation avant d'ouvrir la SSEW.

**Comment by belangeo** [comment]
C'est réglé. Le serveur affiche un message si on essaie de changer de mode alors que la configuration de HPs a changée.

**Comment by Normandeau** [comment]
V203
Réglé.
