### ISSUE TITLE
Icône abîmée depuis la version  202

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#153]
Robert:
V202
L'icône est toujours abîmée sur le Finder, mais correcte dans le Dock (me semble que ça devrait un signe de qqchose...)
V202
Les documents sur le Mac peuvent être représentés sous 4 formes: d'icônes, de liste, de colonnes ou de Cover Flow.
L'icône du ServerGRIS est abîmée seulement dans les Liste ou les Colonnes. Elle s'affiche correctement en mode Icône et Cover Flow.
L'icône abimée du ServerGRIS ne se manifeste que lorsqu'une la petite taille des icônes est sélectionnée.
Olivier:
Pour l'icône, il faut probablement juste refaire le .icns avec une version pour la plus petite taille...
Robert:
Comment fait-on cela?
Mais qu'est-ce qui a changé entre la version 201 et 202 pour que cette icône n'apparaisse plus correctement?
J'ai essayer de transférer les trois icônes identiques (Icon.icns, ServerGRIS_icon_doc.png et ServerGRIS_icon_small) présentes dans les Resources de ServerGRIS, mais cela n'a rien changé dans les versions 203 et 205 (la version sans mention de version est la 203):

![capture d ecran 2019-02-07 a 17 41 22](https://user-images.githubusercontent.com/8959779/52447732-a2ed5280-2aff-11e9-8c87-72be982ea476.jpg)

**Comment by NicolaGiannini** [comment]
En ce qui concerne l’icône abîmée, j’avais noté que  cela se produit si on désinstalle Servergris simplement en le jetant dans la corbeille. Si on suive les indications que Robert avait donné, pour le désinstaller, puis l'icône retourne correcte.

Robert: 
J'ai jeté respectivement:
Preferences:
~/Library/Preferences/com.UdeM.GRIS.ServerGRIS.plist
Cache:
~/Library/Caches/com.UdeM.GRIS.ServerGRIS
Support Library
~/Application Support/GRIS/ServerGRIS.xml

voir issue 140 https://github.com/GRIS-UdeM/ServerGRIS/issues/140

**Comment by Normandeau** [comment]
V203, MacOS 10.13.6
Ça ne marche pas pour moi. Je viens de tout virer et de réinstaller la version 2.0.3 et l'icône est toujours abîmée.
Notre page culturelle du jour: «Le troisième sens du mot icône est apparu avec la micro-informatique. Le mot désigne alors un « symbole graphique affiché à l'écran et associé à un objet (ou à une fonction) auquel il permet d'accéder lorsqu'il est sélectionné par un dispositif de pointage ». La majorité des dictionnaires s'entendent pour écrire dans ce sens une icône, bien que quelques-uns permettent en plus le genre masculin ou la graphie sans accent.» — Druide
Corrections apportées à mes messages précédents...

**Comment by NicolaGiannini** [comment]
Si je démarre l’ordinateur en safe mode, (je crois qu'en français c'est "mode sans échec" https://support.apple.com/fr-fr/HT201262 )
pas d’icône abîmée

J'étais en train de valider les étapes de la désinstallation 
Preferences:
~/Library/Preferences/com.UdeM.GRIS.ServerGRIS.plist
Cache:
~/Library/Caches/com.UdeM.GRIS.ServerGRIS
Support Library
~/Application Support/GRIS/ServerGRIS.xml

à la fin de ce processus je démarrais l'ordinateur et à la réinstallation je n'avais pas d'icône abîmée. 
Une fois j'ai testé de le faire sans démarrer l'ordinateur, et cela a produit l'icône abîmée. 

À ce point le seul moyen que j'ai trouvé de ne pas avoir l'icône abîmée est de démarrer en safe mode.  
Après on peut démarrer en modalité normale, et de mon côte ça marche.

**Comment by Normandeau** [comment]
Bravo, ça fonctionne ici aussi.
Ça n'explique rien, mais au moins ça règle le problème
Je mets cela dans le manuel.

**Comment by Normandeau** [comment]
V205 OS 10.3..6
Cette solution ne fonctionne pas sur mon Mac. Mais j'ai besoin d'une précision Nicola. Dans mon cas, même si je démarre en Safe Mode, l'icône est toujours abimée. Même si avant de redémarrer j'ai jeté toutes les préférences. Il y a quelque chose qui n'est pas clair dans ta description. Est-ce que tu jettes ServerGRIS et toutes les préférences? Puis tu réinstalles, en ensuite tu redémarres en Safe Mode?
Ou est-ce que tu installes une nouvelle version en Safe Mode. J,ai essayé cela aussi, mais on ne peut pas ouvrir ServerGRIS en Safe Mode.
Avec 205, j'ai essayé toutes les combinaisons possibles et rien à faire, l'icône est toujours abimée.
À suivre.

**Comment by NicolaGiannini** [comment]
V205 OS 10.3.6
Situation de départ, ServerGris installé et icône pas abîmée.
Je jette ServerGris.
Je réinstalle ServerGris 2.05, sans démarrer et sans jeter les préférences.
L'icône devient abîmée
Je démarre en Safe Mode : pas d’icône abîmée 
Je démarre en modalité normale : pas d’icône abîmée

Robert : Est-ce que tu jettes ServerGRIS et toutes les préférences? Puis tu réinstalles, en ensuite tu redémarres en Safe Mode?

Nicola : Oui, et jeter les préférences n'est pas nécessaire de mon côté. C'est après que j'ai redémarré en Safe Mode que je n'ai pas de  d’icône abîmée, même si avant je n'avais pas jeté les préférences.

**Comment by NicolaGiannini** [comment]
J'ai fait aussi ce test:

Situation de départ, ServerGris installé et icône pas abîmée.
Je jette ServerGris.
Je démarre en Safe Mode
Je réinstalle ServerGris 2.05 (sans jeter les préférences)
L'icône devient abîmée, même si je suis en Safe Mode.
Je démarre une autre fois en Safe Mode : pas d’icône abîmée. Je ne peux pas moi aussi ouvrir ServerGris en Safe Mode.
Je démarre en modalité normale : pas d’icône abîmée, et je peux ouvrir ServerGris.

**Comment by Normandeau** [comment]
Merci Nicola. 
J'ai débranché mon Mac des deux écrans 4K externes. Redémarré en Safe Mode. Remarqué que dans ce mode, les deux résolutions les plus fines de l'écran Retina ne sont pas disponibles. Problème résolu... Retour au mode normal, par de problème.
Trèze bizarre...

**Comment by belangeo** [comment]
C'est réglé. Juce produit un icône de mauvaise qualité. Au moment de faire un release, je le remplace par un de haute résolution que je viens de créer.

**Comment by Normandeau** [comment]
V206
Réglé. Youpie.
