### ISSUE TITLE
Plantage de Show OSC Log Window. Autant d'activité OSC à l'arrêt: normal? 

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#154]
V203
J'ai une (grosse) session DP ouverte (92 canaux SpatGRIS) et j'ouvre la fenêtre Show OSC Log Window. Même en mode Pause (pour DP), il y a vraiment beaucoup d'activité OSC. Normal?

[OSC Activity203.mov.zip](https://github.com/GRIS-UdeM/ServerGRIS/files/2847903/OSC.Activity203.mov.zip)

De plus, quand je ferme la fenêtre Show OSC Log Window, ServerGRIS plante à tous les coups.

**Comment by Normandeau** [comment]
ServerGRIS plante seulement quand Show OSC Log Window est en activité et qu'on ferme la fenêtre. Si on appuie sur Stop avant de fermer, ça va.

![capture d ecran 2019-02-09 a 09 51 30](https://user-images.githubusercontent.com/8959779/52522264-ddb2d000-2c50-11e9-879f-f415a496996a.jpg)

**Comment by NicolaGiannini** [comment]
V205
Logic
Session avec 20 canaux SpatGris
J’ai exactement le même comportement de la Show OSC Log Window :
- beaucoup d'activité OSC, Même en mode Pause (Logic)
- ServerGRIS plante seulement quand Show OSC Log Window est en activité et qu'on ferme la fenêtre. Si on appuie sur Stop avant de fermer, ça va.

**Comment by belangeo** [comment]
Il y a beaucoup d'activité dans la fenêtre parce que même lorsque le séquenceur est en pause, le SpatGris envoit toujours les coordonnés des sources. C'est que vous avez d'ailleurs demandé pour le ControlGris! Le crash est réglé.

**Comment by Normandeau** [comment]
V206 DP10
Même situation de crash pour moi:
J'ai une (grosse) session DP10 ouverte (86 canaux SpatGRIS), qui ne joue pas, et j'ouvre la fenêtre Show OSC Log Window. Quand je ferme (CLOSE) la fenêtre Show OSC Log Window, ServerGRIS plante à tous les coups.
Si on appuie sur STOP avant de fermer, ça va.

Bon peut-être que ce n'est pas grave, et qu'on n'offrira même pas cette option dans une version officielle. Et je peux le mettre dans le manuel. À confirmer.

**Comment by belangeo** [comment]
Ok, ma session de test sous MacOS était probablement trop modeste (pourtant sous linux avec 64 canaux, ça ne crashait pas)... C'est juste une question de s'assurer que le buffer de messages OSC est vide avant de fermer la fenêtre. J'attend qu'on décide si la fonctionnalité reste avant de réparer.

**Comment by NicolaGiannini** [comment]
V206 Logic X
Même situation de crash pour moi
Session avec 39 canaux de SpatGris, buffer 1024, 82 pistes de input. Logic en pause, si je ferme la fenêtre Show OSC Log Window, ServerGRIS se plante.
