### ISSUE TITLE
Interdire le zoom négatif (au-delà de 0) de la caméra

### ISSUE THREAD

**Issue by belangeo** [GRIS-UdeM/SpatGRIS#155]
J'ai remarqué récemment que la vue 3D du serveur présentait parfois les chiffres à l'envers et que le contrôle de la vue (caméra) se trouvaient inversé. J'ai réalisé que cela était du à un zoom de la caméra allant au-delà de la position 0 dans l'environnement virtuel. Cela fait en sorte que tout le dispositif se trouve visuellement inversé et peut être sauvegardé comme tel --avec une valeur négative pour la distance de la caméra (CamDistance= -1 dans le fichier XML).

Je suggère de bloquer le zoom à 0 pour interdire tout vue de la caméra en négatif.

**Comment by Normandeau** [comment]
V208
Réglé
