### ISSUE TITLE
Distance non prise en compte en mode LBAP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#156]
Lorsqu'on place les sources le plus loin possible dans le ControlGRIS (soit dans les coins), la notion d'éloignement du groupe des hp n'est pas prise en compte actuellement. Il n'y a ni atténuation du signal, ni filtrage des aiguës. Il serait souhaitable que cela soit pris en charge d'une manière ou de l'autre dans ServerGRIS. Par exemple, en reprenant cette fonction que nous avions dans le SpatGRIS en mode audio. Sinon, la notion d'éloignement n'est pas valide.
Ensuite, la position des sources dans ControlGRIS se limite à l'espace délimité, soit la représentation symbolique du lointain déterminé par le carré externe, alors que dans le ServerGRIS, le lointain est très... loin! Souvent au-delà des limites du visible, selon le réglage de zoom de celui-ci. Une meilleure cohérente serait souhaitable.

![Capture d’écran, le 2019-08-13 à 07 55 56](https://user-images.githubusercontent.com/8959779/62939694-d86d4400-bd9f-11e9-9384-7013a70ec0d3.jpg)

**Comment by NicolaGiannini** [comment]
Je suis d’accord et je confirme que il n’y a pas de notion d'éloignement du
groupe des hp.



Il giorno mar 13 ago 2019 alle ore 07:57 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V208
Très bien la notion d'éloignement est maintenant intégrée dans ServerGRIS en mode CUBE.
Maintenant il va nous falloir établir une relation graphique claire entre ControlGRIS et ServerGRIS.
Dans l'exemple illustré, afin de profiter de la notion d'éloignement, j'ai fabriqué un dispositif de 10 hp dont les distances maximales sont de 0.3 ou 0.5. Voici comment cela est représenté dans le ServerGRIS, vu du dessus. J'ai laissé volontairement un hp à une distance de 1, afin de valider mon point plus loin:
![CUBE à 0 5](https://user-images.githubusercontent.com/8959779/73216992-14654d00-4125-11ea-9a82-9a395c638e1f.jpg)

J'ajoute un ControlGRIS avec 8 sources à 0.5 de rayon:
![ControlGRIS à 0 5](https://user-images.githubusercontent.com/8959779/73217258-9786a300-4125-11ea-84ea-e5f95c2e9f6c.jpg)

Voici à quoi ça ressemble dans le ServerGRIS:
![ControlGRIS + ServerGRIS à 0 5](https://user-images.githubusercontent.com/8959779/73217386-cf8de600-4125-11ea-908d-bc91120bc5b8.jpg)

Donc c'est un peu n'importe quoi. Il faut unifier les échelles graphiques avec les échelles physiques. D'ailleurs ça pose la question des limites physiques. Actuellement, la distance dans le Speaker Setup n'est pas limité. À partir de 7 par exemple, avec un zoom out maximal le hp n'est plus représenté dans le graphique. Et en fait, selon différentes configurations de zoom, à partir de 3, le hp disparaît de l'affichage.
Je propose donc qu'on limite la représentation graphique du ServerGRIS avec trois carrés (il y en a 5 actuellement), un premier à 0.5, un second à 1 et le troisième à 2. Et qu'on fasse la même chose dans ControlGRIS.
Actuellement dans ControlGRIS, la valeur maximale est 1, ce qui correspond à un rayon de 2 dans le ServerGRIS. Cela devrait être unifié:
![ControlGRIS à 1 - ServerGRIS à 2](https://user-images.githubusercontent.com/8959779/73218729-8a1ee800-4128-11ea-97ca-15da01f46025.jpg)

La distance maximale pourrait alors être limité à 2. Cela pourrait représenter un hp qui serait installé de manière excentrique à la salle de concert, dans un corridor par exemple.
Qu'en dites-vous? Est-ce que j'oublie quelque chose?

**Comment by Normandeau** [comment]
V208
Très bien la notion d'éloignement est maintenant intégrée dans ServerGRIS en mode CUBE.
Question: comment l'audio est-il géré? Autrement dit, à partir de quelle valeur dans le CUBE, l'atténuation en amplitude et en filtrage commence-t-elle à s'exercer? Il semble que l'atténuation commence à 1 dans le ServerGRIS, correct? Or dans le ControlGRIS, cela correspond à un rayon de 0.6:

![ControlGRIS 0 6 - ServerGRIS 1 0](https://user-images.githubusercontent.com/8959779/73220020-7628b580-412b-11ea-9680-3ed656d76ffb.jpg)

Autant sur le plan graphique (voir l'issue no 173 ) que sur le plan audio, il faut unifier les deux outils.

**Comment by Normandeau** [comment]
Il faudra être très clair ici que le placement d'un hp avec une distance de 1 correspond à la frontière de l'atténuation. Ce ne sont pas les hp qui détermine cette frontière, mais bien le plan. À mettre dans le manuel.

**Comment by NicolaGiannini** [comment]
Donc si je comprends bien, si je place un haut-parleur à une distance de 1,5,  l'atténuation commence déjà à une distance de 1 (à cause de la limite du plan) ? C'est ce que nous voulons ?

**Comment by belangeo** [comment]
On a pas tellement le choix... L'attenuation est fonction de la distance de la source dans un plan délimité, et non fonction de la position d'un haut-parleur.

**Comment by NicolaGiannini** [comment]
Je me demande alors s'il n'est pas plus approprié de donner la possibilité de mettre les haut-parleurs uniquement sur la limite du plan. Car si je comprends bien, le comportement d'un haut-parleur est indépendant de la distance réelle du centre où il est positionné.

**Comment by Normandeau** [comment]
C'est exactement cela qu'on a suggéré. Actuellement il n'y a pas de limite au paramètre distance. Au point où tu ne vois même pas le hp dans la représentation graphique. Donc on va limiter le paramètre distance. Et l'atténuation va commencer à 1. Et les hp seront nécessairement dans le plan, puisqu'il sera limité à 2.5. Il faudra être clair sur le fait que le hp, placé à 1, est à la limite du facteur d'atténuation. Bien entendu, si ce facteur est utilisé dans les préférences, ce qui n'est pas obligatoire.
Oups!!! Vérification faite, l'atténuation est obligatoire dans la version 2.0.8, à -12 dB minimum. Peut-on ajouter 0 dB, juste au cas où?

**Comment by belangeo** [comment]
Bien sûr! Je vais ajouter 0dB.

**Comment by Normandeau** [comment]
SpatGRIS209
Mais on a tout de même un problème: quoique étant en mode CUBE, on est toujours avec un facteur d'atténuation qui relève du cercle. Si j'éloigne la source avec un angle de 0˚ vers le bord extérieur, l'atténuation commence à 0.62 (premier cercle blanc de ControlGRIS, deuxième de SpatGRIS).
Mais si j'éloigne la source avec un angle de 45˚, l'atténuation commence bien à une distance de 0.62, alors que, autant sur le plan graphique, que sur le plan acoustique, par rapport à la géométrie de l'espace, on s'attendrait plutôt à ce que ça soit à 0.87:

0˚, 0,62: aucune atténuation
![0˚, 0,62](https://user-images.githubusercontent.com/8959779/74109557-6e690800-4b52-11ea-9f60-8ffeb12ef984.jpg)

45˚, 0,62: aucune atténuation
![45˚, 0,62](https://user-images.githubusercontent.com/8959779/74109563-7de85100-4b52-11ea-937b-e6505fa220d2.jpg)

45˚, 0,87: atténuation notable
![45˚, 0,87](https://user-images.githubusercontent.com/8959779/74109566-88a2e600-4b52-11ea-98dc-3c676e9f07f0.jpg)

**Comment by belangeo** [comment]
Ouin... La distance, c'est la longueur du rayon par rapport au centre (pythagore), c'est certain que les coins du carré sont plus loin que les côtés en ligne droite... Ça serait un peu tordu de commencer l'atténuation à des distances différentes selon l'angle d'azimuth (et un peu plus coûteux en CPU dû à la condition et l'ajustement de distance pour chaque source).

**Comment by Normandeau** [comment]
Oui, je présentais la situation un peu naïvement en fait. Je me doutais bien de ta réponse! Laissons cela comme ça pour le moment. Et si jamais la ligue internationale des utilisateurs nous envoie un mémo pour qu'on tienne une conférence sur le sujet, on avisera!

**Comment by Normandeau** [comment]
V211
Mis dans le manuel
