### ISSUE TITLE
Inputs vs Available pour les séquenceurs à 128 inputs

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#157]
Le ServerGRIS ajoute systématiquement les 128 Inputs dès qu'on l'active ou le désactive (On/Off) pour les séquenceurs qui affichent automatiquement la valeur d'inputs Available par défaut à 128. Il faut ensuite réécrire le nombre réel affiché dans Inputs pour travailler. Cette dernière devrait avoir priorité pour un projet donné.

À l'ouverture d'une session:
![Capture d’écran, le 2019-08-13 à 09 03 07](https://user-images.githubusercontent.com/8959779/62943789-45d1a280-bda9-11e9-8915-2725bf324c71.jpg)

Après activation de ServerGRIS:
![Capture d’écran, le 2019-08-13 à 09 03 20](https://user-images.githubusercontent.com/8959779/62943820-52ee9180-bda9-11e9-94c8-9e85b3af137c.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme le comportement et je suis d'accord que il serait plus utile
que la valeur du projet soit prioritaire.



Il giorno mar 13 ago 2019 alle ore 09:05 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V207 avec ControlGRIS 101
Ceci est devenu un bogue majeur qu'Iil faut corriger **rapidement** si on veut travailler en mode LBAP. 128 inputs c'est trop en LBAP et ça bloque tout.

**Comment by Normandeau** [comment]
SpatGRIS 209
Je viens d'effectuer une comparaison entre l'ouverture d'un projet de 94 pistes réalisée dans DP10 avec ServerGRIS 208 d'une part et SpatGRIS 209 d'autre part. Au départ, un projet ServerGRIS de 38 entrées avait été ouvert, d'où ce nombre dans le tableau.
Voici ce que cela donne.

En gros, on peut avoir qu'avec la version 208, on avait 4 étapes à franchir pour avoir de l'audio sur toutes les entrées.
Avec SpatGRIS 209, on doit ajouter deux étapes supplémentaires pour obtenir le même résultat.

![Inputs vs Available pour les séquenceurs à 128 inputs](https://user-images.githubusercontent.com/8959779/73794373-4ce4d680-4776-11ea-986a-cc30a99030fc.jpg)

Il faudrait refaire les mêmes mesures avec Reaper et Logic pour fin de comparaison. Je n'ai pas de gros projets dans ces DAW, aussi cela va me prendre un certain temps avant d'y parvenir.
À suivre.

**Comment by NicolaGiannini** [comment]
J'ai une situation similaire à celle de Robert

![2_08_2_09](https://user-images.githubusercontent.com/35705913/73802154-b969d080-478a-11ea-8187-1049a86d0dbf.jpeg)

**Comment by NicolaGiannini** [comment]
J'ai une situation similaire à celle de Robert.

![2_08_2_09](https://user-images.githubusercontent.com/35705913/73802279-2bdab080-478b-11ea-9b86-85057c257ed0.jpeg)

(J'ai envoyé un nouveau message parce que j'avais téléversé une image incorrecte.)

**Comment by belangeo** [comment]
Selon ce que je vois, ça fait exactement ce que vous aviez demandé, non?

**Comment by Normandeau** [comment]
(voir ma réponse détaillée sur GRIS-Dev)
Sinon, je continue la description par item ici.
J'ouvre SpatGRIS avec un projet de 18 inputs.
J'ouvre une séquence Reaper avec 18 canaux.
End se place automatiquement à 32.
Je mets SpatGRIS à On et je me retrouve avec 32 canaux et Inputs est également ajusté à 32 canaux.
Je remets 18 dans le text box Inputs, et dans End ce qui réajuste les inputs à 18.
On peut commencer à travailler.
J'en conclus donc qu'il vaut mieux ouvrir plus de canaux que moins au départ.
Car on peut réduire les valeurs de Inputs et de End sans perdre l'audio.

Je teste avec une situation légèrement différente:
J'ouvre SpatGRIS avec un projet de 18 inputs.
J'ouvre une séquence Reaper avec 44 canaux.
End se place automatiquement à 32 (il manque donc 12 canaux).
J'ouvre mon projet à 44 canaux: Inputs se met à 44 mais End reste à 32 mais j'oublie (volontairement...) de le corriger.
Je mets SpatGRIS à On et je me retrouve avec 32 canaux. Inputs est correctement ajusté à 44 canaux.
Je joue la séquence et j'ai de l'audio dans les 32 premiers canaux seulement (valeur correspondant à End).
Je remets 44 dans End, mais cela n'ajoute pas l'audio dans les canaux manquants.
Je mets SpatGRIS à Off et à On.
J'ai de l'audio partout.
Cela confirme qu'il vaut mieux ouvrir SpatGRIS avec plus de canaux que moins.
Donc 64 serait une meilleure valeur par défaut que 32.

Confirmation
J'ouvre SpatGRIS avec un projet de 64 inputs.
J'ouvre une séquence Reaper avec 44 canaux.
End se place automatiquement à 32 (il manque donc 12 canaux, même si Inputs est à 64).
Je mets End à 64.
Je mets SpatGRIS à On
J'ai de l'audio partout et je peux ajouter des pistes dans la séquence qu'à 64 sans avoir à redémarrer SpatGRIS.

**Comment by Normandeau** [comment]
J'ai bonifié mon dernier commentaire d'hier (les mises à jour n'étant pas postées, vous pouvez le lire directement dans Github).
En fait la formule est:
— Si End est > Inputs, la valeur de celui-ci est automatiquement ajusté par l'activation du SpatGRIS (On ou Off)
— Si End est < Inputs, c'est cette dernière valeur qui prévaut.
Il s'agit donc du même comportement que nous avions dans ServerGRIS 208, sauf que dans SpatGRIS209 on a 32 comme valeur par défaut alors que dans ServerGRIS208 on avait 128.
Je reviens avec ma suggestion de mettre la valeur par défaut à 64.
Et d'enlever Available.
Et je ferai une mention très explicite dans le manuel.

**Comment by Normandeau** [comment]
Petite correction:
Il s'agit donc du même comportement que nous avions dans ServerGRIS 208, sauf que dans SpatGRIS209 on a 32 comme valeur par défaut alors que dans ServerGRIS208 on avait 128.

**Comment by belangeo** [comment]
Bien d'accord que Available est plus ou moins utile... Sous MacOS, c'est pratiquement toujours 128 (la valeur des entrées/sorties virtuelles qu'on impose à JackRouter à l'installation. 64 me semble aussi un bon compromis.

**Comment by belangeo** [comment]
Ok. Je crois que ça fait le tour!

1) Nombre de canaux actifs par défaut = 64.
2) Changer le start ou le end reconnecte automatiquement le client.
3) Available retiré de la boîte de clients.

**Comment by Normandeau** [comment]
Yep!

**Comment by Normandeau** [comment]
SpatGRIS210
Réglé.
J'utilise des documents qui ont fait leurs preuves après avoir jeté le dossier GRIS dans Application Support.
Séquence DP 38 canaux, DOME 10.2, Projet 38 canaux. On et ça marche.
Olivier écrit: «Changer le start ou le end reconnecte automatiquement le client.»
Cela m’intrigue, alors évidement j'essaie de faire planter cela! Mais ça marche: 
- End à 8: seuls les 8ers canaux fonctionnent
- End à 16: plus les suivants
- End à 24: plus les suivants
- End à 32: plus les suivants
- End à 38: tous.
On peut même faire 9-16 par exemple!!!
Bravo!!!
