### ISSUE TITLE
CPU affichage incohérent entre VBAP et LBAP selon le mode de fabrication du Speaker Setup

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#158]
En fait Nicola a mis le doigt sur une anomalie de ServerGRIS, mais pas exactement celle qui est décrite.
Notamment parce que le ServerGRIS testé était sans session, autrement dit sans séquenceur connecté, donc sans entrées réelles.
Aussi, le Speaker Setup n'est pas décrit adéquatement: sous quelle version et dans quel mode il a été fabriqué.

Je décris la situation que j'ai reproduite:
- Session DP de 92 canaux OSC avec 46 SpatGRIS stéréo automatisés (c'est le maximum que SpatGRIS peut gérer, pour une raison inconnue).
- Dispositif de 32 hp (B187) fabriqué en VBAP à l'origine.
• La valeur de CPU est parfaitement stable entre 0.001 et 1.000: autour de 43%
Ce qui est étonnant en fait, puisqu'on s'attend à une augmentation du CPU en fonction de la valeur de l'interpolation, mais ici elle reste stable, quelque soit la valeur d'interpolation utilisée.
• Par contre si on place la valeur de l'interpolation à 0.000, là ça grimpe à 55%.
Alors qu'effectivement on s'attend à avoir une valeur moindre (c'est la situation décrite par Nicola).

Si j'utilise le même dispositif de hp, mais que je transfère de VBAP en LBAP dans ServerGRIS, avec la même session DP toujours constitué des 48 SpatGRIS, voici ce que ça donne:
• De 0.001 à 1.000, le CPU est surchargé à 112% environ
C'est trop, la valeur en CPU clip en rouge régulièrement.
• À 0.000, le CPU tombe à 65% environ et la session roule correctement.
Comportement normal: sans interpolation, LBAP est capable de gérer le projet.

*****
Afin de compléter ces résultats, j'ai changé le dispositif de hp avec un modèle cylindrique de 32 hp fabriqué originellement en LBAP dans la version 2.05 de ServerGRIS (et non pas transposé de VBAP en LBAP). Cela donne, avec la même session DP en mode LBAP:
• Interpolation à 0.000: CPU à 35% (en comparaison de 65% avec le setup précédent)
• Interpolation de 0.001 à 1.000: CPU stable autour de 60% et la session roule correctement!
Ce résultat est tout de même étonnant, puisque le CPU reste stable, quelque soit la valeur de l'interpolation.

Transposition de LBAP en VBAP du même dispositif:
• Interpolation de 0.000 à 1.000: CPU stable à 35% et la session roule correctement! Pas de différence à 0.000

******
Conclusion:
Il semble y avoir une relation entre la consommation de CPU et la version de SpatGRIS avec laquelle le Speaker Setup a été fabriqué. Lorsque le LBAP a été implémenté dans ce dernier, on a eu toutes sortes d'incompatibilité au début entre les setups VBAP et LBAP, qui se sont stabilisées avec la version 2.05. Mais il semble que les Speaker Setup fabriqués avant cela et utilisés dans la version 2.07 influencent directement la consommation de CPU selon qu'ils ont été fait en mode VBAP ou LBAP et utilisés selon l'un ou l'autre de deux modes.

Pour continuer les tests, il est donc primordial de bien noter quelle version du ServerGRIS a été utilisée pour fabriquer le speaker setup. C'est hyper important, parce que cela signifie qu'il semble toujours y avoir incompatibilité entre les anciens setups et les nouveaux, du moins quant à la consommation de CPU.

Peut-être qu'Olivier peut nous expliquer cela.

*****
Le 14 août 2019 à 18:24, Nicola Giannini <nicolagiannini00@gmail.com> a écrit :

Le comportement relationnel entre CPU et Interpolation en mode VBAP est opposé à celui du mode LBAP.
En VBAP si l’interpolation est à 0, la valeur de la cpu est plus élevée, que lorsque l’interpolation est supérieure à 0. En LBAP si l’interpolation est à 0, le valeur de la cpu est plus basse que lorsque l’interpolation est supérieure à 0.
Voir la vidéo

https://www.dropbox.com/s/yiewqlmjujiyytj/interpolation.mov?dl=0

**Comment by NicolaGiannini** [comment]
Je confirme que même dans Logic la limite est de 92 canaux en input, (dans
mon cas 42 instances de SpatGris)

Ma situation 1 :
ServerGris 2.07
Session Logic avec 48 canaux
Dispositif de 126 HP (2 directs).
En VBAP si l'interpolation est supérieure à 0.000 la CPU est stable à 37%, si
l'interpolation est = 0.000 ça grimpe jusqu'à 52%

En LBAP si l'interpolation est est supérieure à 0.000 la CPU grimpe jusqu'à
112%, si l'interpolation est = 0.000 la CPU est stable à 47%

J'ai installé la version 2.05

Session Logic avec 92 canaux

*Tests avec ServerGris 2.05*
*Dispositif de 32 HP crée en LBAP en 2.05*

En LBAP avec interpolation à 0, cpu = 25%. Avec interpolation supérieure à 0
= 39% (stable)
En VBAP avec interpolation à 0, cpu = 28%. Avec interpolation supérieure à 0
= 23% (stable)


*Dispositif de 32 hp (B187) fabriqué en VBAP à l'origine *

En LBAP avec interpolation à 0, cpu = 45%. Avec interpolation supérieure à 0
= grimpe jusqu'à 111%

En VBAP avec interpolation à 0, cpu = 47%. Avec interpolation supérieure à 0
= 33% (stable)

*Tests avec ServerGris 2.07* (plus ou moins les mêmes résultats qu'avec la
2.05)a

Dispositif de 32 HP crée en LBAP en 2.05

En LBAP avec interpolation à 0, cpu = 24%. Avec interpolation supérieure à 0
= 38% (stable)
En VBAP avec interpolation à 0, cpu = 27%. Avec interpolation supérieure à 0
= 22% (stable)

Dispositif de 32 hp (B187) fabriqué en VBAP à l'origine

En LBAP avec interpolation à 0, cpu = 42%. Avec interpolation supérieure à 0
= grimpe jusqu'à 112%

En VBAP avec interpolation à 0, cpu = 46%. Avec interpolation supérieure à 0
= 32% (stable)

**Comment by belangeo** [comment]
En ce qui concerne l'interpolation, à 0, une simple interpolation linéaire est utilisée et au dessus de 0, c'est une filtre passe-bas IIR du premier ordre (même système en VBAP et en LBAP). Je viens de revérifier et clairement, sur ma machine, j'ai une économie nette de CPU avec l'interpolation linéaire (autant en VBAP qu'en LBAP). Il y a peut-être quelque chose d'autre qui interfère dans votre setup que je n'ai pas ici...

Une pensée à propos du modèle cylindrique évoqué par Robert... En LBAP, il y a deux interpolations dans le calcul de la position (rien à voir ici avec l'interpolation plus haut, qui ne fait que lisser les changements de valeur). La première lit la position dans la matrice horizontale et la seconde interpole entre les matrices superposées (verticalement). Il faudrait faire des tests à savoir si une des deux demande plus de CPU que l'autre (beaucoup de HPs au même niveau et très peu de niveau versus peu de HPs au même niveau + beaucoup de niveaux).

Il y aurait peut-être place pour de l'optimisation du LBAP ici...

**Comment by Normandeau** [comment]
V208
J'ai refait les tests décrits dans ma première communication du 15 août et les résultats sont les mêmes avec le V208.
J'ai ajouté un test avec les Span Azimuth et Elevation et leurs valeurs ne modifient pas substantiellement la charge en CPU (une seule piste stéréo cependant avec ControlGRIS 1.04). Cela reste à valider avec des tests plus costauds.

**Comment by NicolaGiannini** [comment]
j’ai fait aussi les mêmes test de août, avec les mêmes résultats. Le fait d’avoir ouvert la session de logic ouvert (mais non en play) ne change pas grand chose.
Avec seulement ServerGRIS ouvert
Speaker setup de 126 hp
48 inputs
LBAP
Interpolation à 0 = 46% de cpu
Interpolation à 0.001 = 99 % de cpu

VBAP

Interpolation à 0 = 52% de cpu
Interpolation à 0.001 = 39 % de cpu

Donc l’interpolation, dan mon cas, a un comportement inverse entre LBAP et VBAP.

Même chose avec la session de logic ouverte. 

En ce qui concerne le span Azimut et Elevation, j’ai fait de test avec SpatGRIS, 
Speaker setup de 126 hp
42 inputs mais seulement 1 piste stéréo (qui joue en solo du sequencer)

Interpolation à 0 

azimut span 0 = 49% de cpu
azimut span moitié  = 43% de cpu
azimut span max  = 41% de cpu

L’elevation Span ne change rien dans mon cas.

Mais je ne suis pas sûr que il soit le test que t'as demandé Olivier!

**Comment by belangeo** [comment]
Quelques petits détails ici.

> La valeur de CPU est parfaitement stable entre 0.001 et 1.000: autour de 43%
Ce qui est étonnant en fait, puisqu'on s'attend à une augmentation du CPU en fonction de la valeur de l'interpolation, mais ici elle reste stable, quelque soit la valeur d'interpolation utilisée.

Pour une interpolation plus grande que 0, on ne s'attend pas à une augmentation du CPU en fonction de la valeur de l'interpolation, les calculs sont toujours les même, seul le coefficient du filtre change. C'est un filtre passe-bas IIR de premier ordre : `y = x + (y - x) * coef`

> À 0.000, le CPU tombe à 65% environ et la session roule correctement.
Comportement normal: sans interpolation, LBAP est capable de gérer le projet.

Pas tout à fait vrai... À 0, il y a interpolation, seulement c'est une simple interpolation linéaire (plutôt que le filtre passe-bas décrit plus haut) : `y = y + diff` 

Maintenant, dans le cas du filtre passe-bas IIR, il faut aussi tenir compte de la dénormalisation (la gestion catastrophique des processeurs Intel des nombres trop petits pour être représentés en float 32-bit, de l'ordre de 1e-12). L'interpolation avec le filtre passe-bas vérifie si la valeur est trop petite (donc n'est plus significative) et si c'est le cas, la remplace par 0 et bypass le filtre. Tous les algos récursifs doivent gérer la dénormalisation d'une façon ou d'une autre...

Je viens de refaire les différents tests sur le macpro et le seul cas de figure qui détonne est celui où une session ServerGris n'a pas encore reçu de données OSC, donc pas de position à interpoler, donc le filtre est systématiquement bypassé. Ce n'est jamais le cas pour l'interpolation linéaire. Ce qui fait qu'une session « vierge » semble prendre plus de CPU avec l'interpolation à 0 mais dès qu'elle reçoit des données, ça change. Le filtre est plus costaud que l'interpolation linéaire. 

La différence est plus marquée en LBAP puisqu'il y a plus de HPs de stimulés par chacune des sources (contrairement à 3 pour le VBAP). Il y a donc beaucoup plus d'interpolation à effectuer et la différence entre les deux algos se fait plus sentir.

Bref, je ne crois pas qu'il y ait quoi que ce soit à faire pour cet issue, si ce n'est de, peut-être, préciser dans le manuel que l'interpolation à 0 ne veut pas dire « pas d'interpolation » mais bien un algorithme plus simple.

**Comment by Normandeau** [comment]
Ok, merci Olivier de cette description détaillée. Qui nous éclaire, pauvres néophites en matière de dénormalisation!
;-)

**Comment by Normandeau** [comment]
V211
Mis dans le manuel
