### ISSUE TITLE
En mode binaural, les sorties 1 et 2 sont maintenant déséquilibrées vers le canal gauche. 

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#160]
ServerGris V 2.07

En mode binaural, les sorties 1 et 2 sont déséquilibrées vers le canal droit. 

Testé avec : 
Logic 10.4.6
Reaper 5 983
SpatGris 1.0.1
ControlGris 1.00b4

1) J'active un canal avec une sinusoïde ou un bruit mono blanc, avec une instance de SpatGris ou Controlgris. 
2) Je place le son au centre
3) En mode stéréo, le son est réparti également sur les deux canaux.
4) En mode binaural, le son est déséquilibré vers le canal droit.

(Également testé avec un canal stéréo, avec le même contenu à gauche et à droite).

Voir la vidéo

https://www.dropbox.com/s/k8efr6gfh3c2g59/binaural.mov?dl=0

**Comment by catrochemusic** [comment]
Thanks, yes, I found the same imbalance in binaural and was worried it was reaper, and would be the same in vbap once I plugged into the speaker dome. So I now now it’ll be ok. :) 


Sent from Yahoo Mail for iPhone

**Comment by belangeo** [comment]
C'est réglé.

**Comment by Normandeau** [comment]
V208
Il semble que ce ne soit pas tout à fait réglé. Avec un sinus à 1000Hz mono -20dBFS), le canal gauche est plus fort de 0,9 dB (mesuré avec Digicheck sur une carte RME). En prenant le même signal mais avec une amplitude de 0dBFS, on constate le même écart de 0,9 dB.
Ce n'est pas un grand écart, mais ça s'entend. En stéréo, c'est parfaitement égal.

![Capture d’écran, le 2020-01-24 à 20 21 44](https://user-images.githubusercontent.com/8959779/73114304-47220200-3ee7-11ea-970f-c03c34239b38.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme le même comportement.



Il giorno ven 24 gen 2020 alle ore 20:31 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
La mesure faites avec une sinusoide n'est pas vraiment valide parce que le HRTF implique un filtrage différent pour chaque canal. Par exemple, si on change la fréquence de la sinusoide pour 2800Hz, c'est le canal droit qui est légèrement plus fort, à 425Hz, les deux canaux sont identiques. Avec une sinusoide, les filtres HRTF sont simplement des courbes de volume complexes en fonction de la fréquence...

**Comment by Normandeau** [comment]
Olivier, Ce qui est merveilleux avec toi, c'est qu'on on en apprend tous les jours. 
Je confirme qu'avec un bruit rose, ça marche impec.
Merci de cette information, que je vais mettre aussi dans le manuel (pour les nerds...).

**Comment by Normandeau** [comment]
V211
Mis dans la manuel
