### ISSUE TITLE
Instant Crash avec appareils Bluetooth

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#161]
ServerGris 2.07 MacOs 10.13.6
C'est probablement un bug de peu d'intérêt, mais si je choisis Apple Airpods comme carte de son, j'obtiens un crash instantané quand j'essaie d'ouvrir ServerGris. Je joins le rapport Apple.

**Comment by Normandeau** [comment]
MacOS 10.14.6
Si je travaille en mode simulation avec ServerGRIS connecté sur les hp du Mac et DP ouvert et quelqu'un me fait un appel Facetime, cela crashe ServerGRIS et par conséquent DP.
Bon vous me direz qu'on ne devrait pas faire du Facetime en même temps que du beta testing, que ce n'est pas sérieux!
Mais en même temps ça me rappelle la joyeuse époque de ProTools où on ne pouvait pas utiliser deux apps audio en même temps...

**Comment by belangeo** [comment]
Haha, tant que tu ne fais pas du facetime en concert! Si c'est jack qui ne gère pas correctement certains protocoles de Apple, il n'y a pas grand chose à faire à part que de filtrer ces clients pour que le ServerGris les ignore tout simplement. Je vais demander à ma blonde de me faire un facetime pour troubleshooter!

**Comment by Normandeau** [comment]
V208
Même chose avec des écouteurs Sony WH-1000XM3 connecté en Bluetooth. Même chose avec un hp JBL Charge 3. Donc en bref, tous les appareils Bluetooth sont incompatibles avec ServerGRIS (ou Jack). Dommage pour ceux (et les colocs et les voisins!) qui veulent travailler dans leur chambre ou leurs chambres d'hôtel...

**Comment by belangeo** [comment]
J'ai réussi à reproduire ce crash avec un haut-parleur bluetooth. Le problème survient quand jack n'arrive pas à changer le sampling rate de l'appareil utilisé. J'ai mis en place une gestion un peu plus serrée des erreurs potentielles et un message d'avertissement s'affiche quand une erreur survient. Je ne sais pas si c'est systématique mais maintenant, ça ne crash plus sur ma machine, le message s'affiche et le serveur utilise ensuite la sortie built-in. 

Ce serait intéressant que vous tentiez à nouveau les différents cas de figure avec la prochaine version pour voir comment ça se comporte.

**Comment by Normandeau** [comment]
SpatGRIS209
Même situation avec écouteurs Sony et haut-parleurs JBL. Mais... ça fonctionne si, dans les Préférences Son, on met deux appareils différents en entrée et en sortie. En effet, les appareils Bluetooth que j'utilise n'ont pas d'entrées. Pourtant on peut les choisir en entrée,ce qui n'a pas de sens. Je viens même de faire cracher mon Mac avec ce choix. Dans tous les cas, ça empêche d'ouvrir SpatGRIS (même si tout est à 48kHz).
Mais en assignant l'entrée de Préférences Son à autre chose qu'un appareil Bluetooth et seulement la sortie à celui-ci, cela fonctionne.

**Comment by Normandeau** [comment]
À mettre aussi dans le manuel: si on ferme l'appareil Bluetooth pendant que SpatGRIS est encore en action, cela le fait crasher immédiatement, et par conséquent toute la chaîne audio...

**Comment by NicolaGiannini** [comment]
v211
J'ai essayé en mettant SpatGRIS2 à 44.100 mais il crash quand même.
 Il faudrait donc l'indiquer dans le manuel.

**Comment by Normandeau** [comment]
V211
Mis dans la manuel
