### ISSUE TITLE
LBAP vs VBAP: le VBAP gagne toujours; Zoom

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#162]
V2.07
D'un côté du ServerGRIS il y a le speaker setup, de l'autre les entrées-sorties et les réglages. Ma séquence de travail est à peu près toujours la même: 
1. Ouverture d'un speaker setup
2. Ouverture d'un document Server

Lorsqu'on ouvre un speaker setup LBAP et ensuite un projet qui a été sauvegardé avec le VBAP comme algorithm, ServerGRIS remet toujours le speaker setup en VBAP. En ce moment je prépare des tests pour le Cube de 124 hp de Virginia Tech qui est en LBAP. Or celui-ci prend déjà entre 2 et 4 minutes à charger. Ensuite j'ouvre un ancien projet sauvé en VBAP et je dois attendre un autre 2 à 4 minutes. Puis je dois remettre le tout en LBAP, et attendre un autre 2 à 4 minutes!
N'y aurait-il pas moyen que la partie projet du ServerGRIS soit informée par la nature du Speaker Setup ouvert et puisse s’ouvrir automatiquement avec le bon algorithme?

**Comment by NicolaGiannini** [comment]
Je suis d'accord, je détacherais le projet de l'algorithme de
spatialisation.
Nicola Giannini



Il giorno mar 8 ott 2019 alle ore 13:04 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by belangeo** [comment]
En effet, le mode de spatialisation est déjà spécifié dans le speaker setup, je ne vois pas de raison d'avoir cette info (sans même connaître la config de HPs) dans le fichier de projet...

**Comment by Normandeau** [comment]
V208
DOME et CUBE sont maintenant indépendant du projet. Excellent.
Mais il y a encore une variable, le zoom de la le fenêtre 3D, qui est modifiée lorsqu'on ouvre différents projets. Cela signifie que le zoom est sauvegardé avec le projet. Est-ce que c'est cela qu'on veut? Selon moi, non. Le zoom fait partie de la fenêtre Speaker Setup. Lorsque je commence une session de travail avec un setup spécifique de hp, et que j'enchaîne les projets, je ne vois pas de raisons pour faire varier le zoom du dispositif de haut-parleurs.

**Comment by NicolaGiannini** [comment]
Je suis d’accord que le zoom est plus lié au Speaker Setup que au projet, mais je me demandais comment on pourrais sauvegarder le Speaker Setup sans entrer dedans la Speaker Setup Edition Window. On pourrait peut être ajouter un “save speaker setup” aussi dans view? (et peut être aussi déplacer le “load speaker set up” en “view” ?)

**Comment by Normandeau** [comment]
Mais pourquoi vouloir le sauvegarder ailleurs que dans la fenêtre Speaker Setup Edition?
Il n'y a que là que tu peux le modifier.
N'est-ce pas logique de le sauvegarder là, et de travailler ensuite ton projet la conscience tranquille ?
Normalement, lorsque tu ouvres un Speaker Setup, c'est pour un événement particulier.
Tu ne l'édites pas toutes les dix minutes, comme cela peut parfois arriver avec un projet, non?

**Comment by NicolaGiannini** [comment]
Peut être que je n’ai pas bien compris la question!
Une fois que l'editing est terminé, je n'ouvre plus cette fenêtre, tandis que 
parfois je change l'angle de vue et le zoom de la fenêtre 3D pendant une session. C'est pourquoi j'ai pensé qu'il était plus pratique de ne pas avoir à entrer dans la fenêtre d'édition pour enregistrer le zoom. Mais probablement il y a quelque chose que je n'ai pas bien compris.

**Comment by Normandeau** [comment]
Je vois, tu parles du zoom. C'est intéressant parce que ça pose la question d'un autre angle. Actuellement, le zoom de la fenêtre 3D est effectivement sauvegardé avec le projet. Mais le speaker setup lui-même est indépendant du projet. Lorsqu'on ouvre ServerGRIS, on ouvre le dernier projet et le dernier Speaker Setup qu'on a utilisé. Je soulevais le point que pendant une même session de travail, pour un speaker setup donné (par exemple le B-187), pour chaque projet différent qu'on ouvre, vient un zoom différent du **même** speaker setup. C'est juste cela que je voulais enlever. Ton point soulève le fait que ce n'est peut-être pas simple que cela. En effet, tous les attributs du menu View sont sauvegardés avec le projet, y compris le zoom bien que ce dernier n'ait pas de menu à proprement parler. Comme tu le dis, si tu changes quoi ce soit à la vue 3D (zoom, position, angle, etc.) et que tu ne sauves pas ton projet à la fin, tu auras perdu ce point de vue lorsque tu rouvriras ton projet.
Bon finalement sauvegarder le zoom avec le projet n'est peut-être pas une si mauvaise idée!
Quant à déplacer le “load speaker set up”, cela n'a pas de sens, puisqu'il s'agit bien d'ouvrir un fichier, donc il va bien dans File.
