### ISSUE TITLE
Changer VBAP pour Dome et LBAP pour Cube

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#163]
Rebaptiser les algorithmes
Changer VBAP pour Dome et LBAP pour Cube

**Comment by NicolaGiannini** [comment]
Je me demande si *CUBE* est le bon terme pour désigner le LBAP.
Avec LBAP, nous pouvons aussi construire des configurations de type
Acousmonium, ou des configurations qui ne sont pas nécessairement
immersives, comme un mur frontal d'haut-parleurs. Peut-être que "FREE"
pourrait être quelque chose de plus représentatif ?



Il giorno mar 8 ott 2019 alle ore 19:49 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by led78** [comment]
C'est aussi ce que je me dis.
En théorie, cet algo permet aussi de placer des hp à l'intérieur de l'espace. C'est donc plus 3D que CUBE. J'aime faire la distinction entre dome et 3D.

Envoyé de mon iPhone

Le 12 oct. 2019 à 14:53, NicolaGiannini <notifications@github.com<mailto:notifications@github.com>> a écrit :

Je me demande si *CUBE* est le bon terme pour désigner le LBAP.
Avec LBAP, nous pouvons aussi construire des configurations de type
Acousmonium, ou des configurations qui ne sont pas nécessairement
immersives, comme un mur frontal d'haut-parleurs. Peut-être que "FREE"
pourrait être quelque chose de plus représentatif ?
Nicola Giannini
+1 514 550 3856
nicolagiannini.com<http://nicolagiannini.com> <http://www.nicolagiannini.com/>


Il giorno mar 8 ott 2019 alle ore 19:49 Robert Normandeau <
notifications@github.com<mailto:notifications@github.com>> ha scritto:

**Comment by Normandeau** [comment]
V208
Modifié. On expliquera clairement le concept de CUBE dans le manuel.
