### ISSUE TITLE
Interleaved ne fonctionne qu'épisodiquement

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#164]
V207
La fonction qui permet de faire l'enregistrement d'un fichier interfolié n'a fonctionné qu'une seule fois pour moi aujourd'hui, soit la première d'une série d'enregistrements. Tous les autres qui ont suivis sont restés en fichiers mono multiples.

**Comment by NicolaGiannini** [comment]
J'ai eu parfois le même problème sporadiquement, je n'avais pas posté le
bug car je ne pouvais pas recréer la situation avec certitude.
Nicola Giannini



Il giorno dom 13 ott 2019 alle ore 13:12 Robert Normandeau <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V208
On n'arrive pas à reproduire cela de manière systématique. Depuis que je l'ai posté (il y a trois mois), cela n'est jamais arrivé. Je ferme donc cette issue. En espérant que ça ne se produise pas trop souvent. Ou qu'on arrive à la diagnostiquer correctement.
