### ISSUE TITLE
Niveaux mesurés en dB en mode CUBE: un réglage serait bienvenu

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#165]
V207
Virginia Tech
Les 124 hp fonctionnent bien. Je constate immédiatement deux choses avec un bruit rose:
- le son est toujours globalement plus fort sur les côtés qu'au centre, où il y a une baisse importante de l'intensité. Mon téléphone dit: -10dB (Décibel X Pro).
- l'interpolation atténue un peu ce phénomène, mais on est loin de la loi de panoramisation

**Comment by belangeo** [comment]
J'ai ajouté une compensation pour la dispersion d'énergie lorsqu'on se déplace vers le centre. Le ratio de compensation devra être validé en situation réelle.

**Comment by Normandeau** [comment]
Olivier,
En discutant hier, on se demandait s'il n'y aurait pas lieu de placer la valeur de compensation disponible pour l'utilisateur. Je doute en effet qu'on trouve une valeur universelle qui satisfasse toutes les conditions réelles des salles de concert (acoustique, dimensions, etc.) et des diverses installations (symétriques, asymétriques, en hauteur, etc.).
Et je n'en ferais pas une préférences, mais plutôt un réglage qui serait visible en mode CUBE (peut-être grisé en mode DOME ou tout simplement absent). Une fois cette valeur ajustée, elle serait sauvegardée avec quoi? Le speaker setup? Je pense que oui, car c'est relatif à l'installation physique, et non pas aux projets. Alors, est-ce qu'on pourrait la faire apparaitre du côté de la fenêtre 3D? Genre en haut à droite?

**Comment by belangeo** [comment]
Je viens de corriger la compensation que j'avais mise en place pour la version 2.0.8, elle ne marchait pas...
J'aimerais qu'on essaie d'abord de trouver un facteur de compensation qui fonctionne bien de façon générale. Si on y arrive pas, je l’inclurai dans l'interface. C'est très creux dans l'algorithme et j'aimerais, si possible, éviter de promener une variable à travers les dix couches qui sépare l'interface du fin fond du LBAP!

**Comment by Normandeau** [comment]
Ok, donc on attend la prochaine version et on va se pencher là-dessus. Nos possibilités de tests sont limités en CUBE à la fac, mais on inventera des situations plausibles.

**Comment by NicolaGiannini** [comment]
v2.10
J'ai fait quelques tests dans l’hexa, je trouve que ça marche bien :
Attenuation à -12 dB et à 125 Hz

**Comment by Normandeau** [comment]
Fait une double série de mesures avec un programme musical stable dans le dôme de Bordeaux, deux fois plus large et un peu plus haut qu'Hexa.
1. Mesure technique en db LU (Norme ITU 1770) avec DigiCheck
Limite des hp: -10dB
Centre: 0dB
Lointain: non mesurable (échelle minimale à -50)
2. Mesure acoustique avec mon iPhone et dBMeter Pro (échelle dBC)
Limite des hp: 64dB
Centre 72 dB
Lointain (réglages -36dB, 125 Hz): 43dB
3. À l'oreille: ça marche bien, on a une sensation de rapprochement progressif jusqu'au centre.
Il faudra valider cela dans le 187, à cause des dimensions plus importantes de ce studio.

**Comment by Normandeau** [comment]
V217
Studio Icosa 20.4 calibré.
- Premier niveau (octophonie): centre 76dB, petit carré: 70dB (-6dB)
- Niveau intermédiaire (6 + 4 hp sur deux niveaux), centre 78dB, petit carré 70dB (-8dB)
- Plafond (2 hp): centre 80dB, petit carré 70dB (-10dB)
- Le centre est très nettement favorisé en ce moment. Un réglage utilisateur serait bienvenu.
