### ISSUE TITLE
Fenêtre 2D disparaît en arrière-plan quand on change d'application

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#166]
Quand on passe de la fenêtre de ServerGRIS à celle du séquenceur, la fenêtre 2D disparaît en arrière-plan, ce qui est normal. Mais lorsqu'on revient sur ServerGRIS, elle ne revient pas au premier plan avec la fenêtre principale du ServerGRIS. Cela n'est pas normal.
À corriger.

**Comment by belangeo** [comment]
Seule solution possible à ce problème avec Juce (pourtant le problème revient régulièrement sur le forum de Juce depuis 2015) est de garder la fenêtre 2D toujours en avant-plan de l'application (comme pour la fenêtre d'édition du speaker setup). Vous me direz si c'est mieux ou pire!

**Comment by belangeo** [comment]
Problème avec ma première solution: la fenêtre 2D était cachée lorsque l'application front n'était pas le ServerGris. Pas commode pour envoyer des valeurs d'une autre application et voir l'action dans la fenêtre 2D.

Seul irritant avec ma seconde solution: les deux fenêtres (ServerGris et fenêtre 2D) apparaissent dans la liste des fenêtres disponibles quand on fait Alt-Tab. Beaucoup moins dérangeant...

**Comment by Normandeau** [comment]
V208
Ça fonctionne bien.
