### ISSUE TITLE
ServerGris ne rappelle pas une speaker setup particulière, lors du passage du mode stéréo au mode VBAP/LBAP, après un redémarrage de ServerGris

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#167]
ServerGris 2.07
ServerGris ne rappelle pas un speaker setup particulier, lors du passage du mode stéréo au mode VBAP/LBAP, après un redémarrage de ServerGris.

J'ouvre ServerGris.
J'ouvre un speaker setup VBAP ou LBAP particulière.
Je passe en mode stéréo.
Je retourne en mode VBAP ou LBAP et je retrouve mon speaker setup particulier (correct).
Je retourne en mode Stéréo, je sauvegarde le projet et je ferme ServerGris.

Je rouvre ServerGris qui charge le speaker setup stéréo (correct).
Je passe en mode VBAP ou LBAP, et ServerGris ne charge pas le speaker setup particulier que j'avais auparavant, mais il charge le "default speaker set up".

**Comment by Normandeau** [comment]
V208
Réglé
