### ISSUE TITLE
Un speaker setup qui contient des doublons de la valeur de LayoutIndex pose des problèmes de visualisation et d'édition

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#168]
ServerGris 2.07
Si la même valeur LayoutIndex est attribuée à plusieurs haut-parleurs, l'affichage et l'édition d'un speaker setup est problématique. 

J'ai pu constater ce comportement en ouvrant un ancien speaker setup, qui contient des doublons des valeurs de LayoutIndex dans le fichier xml. Je comprends que ServerGris ne crée pas des configurations avec des doublons de LayoutIndex, je ne sais pas si cela peut être utile en cas d'ouverture de configurations anciennes. Ou, peut être c'est juste pour un cas que ce speaker setup contient des doublons. Je décris ce comportement.

Dans cette speaker setup https://www.dropbox.com/s/l0axb7n7polt34e/GRISpeaker%20Dome54Subs2Virginia001-124%20avec%20doublons.xml.zip?dl=0 , probablement créé avec une version précédente de ServerGris, la même valeur LayoutIndex est attribuée à certains haut-parleurs. 
Si j'ouvre la fenêtre d'édition, un ring disparaît et les valeurs affichées dans la fenêtre ne sont pas les mêmes que celles du fichier xml.

Vous pouvez faire un test avec LayoutIndex="55", dans le fichier xml il correspond à 4 speakers avec un azimut et une élévation différents, dans la fenêtre d'édition il correspond à 4 speakers qu'ils ont les valeurs d'azimut et d'élévation identiques.

En assignant à chaque speaker une valeur de LayoutIndex différente par l'édition du fichier xml, le problème dans la version 2.07 n'existe pas :
https://www.dropbox.com/s/jmu2dteeo1j1dgq/GRISpeaker%20Dome54Subs2Virginia001-124%20sans%20doublons.xml.zip?dl=0

Cela ne se produit pas du tout avec la version 1.04 de ServerGris, je peux ouvrir le xml avec les doublons et il n'y a pas des problèmes d'affichage ou édition. Probablement ce speaker setup a été faite avec cette version.

**Comment by Normandeau** [comment]
V208
Semble réglé. Le fichier décrit ci-haut s'ouvre correctement avec des ID différents pour chaque hp. Dans le fichier d'origine, où les ID s'arrêtaient à 56, il y avait 22 doublons (45-56, 49-56, 55-56) qui sont apparus dans le fichiers corrigé par 208 avec des ID supplémentaires (57-78). Les doublons ont été éliminés.
Question: est-ce que la numérotation des ID est importante? Dans le fichier corrigé on a des ID qui vont de 1 à 18, puis de 41 à 78. Est-ce que le saut de 19 à 41 est potentiellement problématique? Je suppose que non.
À valider.

**Comment by belangeo** [comment]
Non, rien de potentiellement problématique!
