### ISSUE TITLE
Correspondances des valeurs cartésiennes et sphériques différentes entre le format VBAP et LBAP dans le speaker setup

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#169]
Les valeurs cartésiennes (XYZ) sont cohérentes entre les deux algorithmes. Par exemple si je construis un speaker setup en VBAP, et je veux le recréer en LBAP, je dois utiliser les mêmes cordonnées cartésiennes. Car sinon, si j’utilise les cordonnées sphériques, le speaker setup sera different.  

En LBAP il y a une correspondance directe entre elevation et Z, tandis qu'en VBAP l'elevation modifie les trois axes x, y et z. L'elevation en VBAB couvre une trajectoire sphérique sur la surface du dôme, tandis que l'elevation en LBAP couvre une trajectoire linéaire verticale. De même, la valeur distance a deux comportements différents dans les deux algorithmes. 

On sait que ces comportements sont dus à la différence entre les algorithmes, mais on pense que il faudrait soit changer les noms de distance et d'elevation en LBAP, ou, si possible, que les paramètres distance et elevation se comportent de la même manière dans les deux algorithmes. La même solution peut alors être appliquée aux sorties directes des setup en mode VBAP qui sont actuellement caractérisées par le même comportement d'un haut-parleur en mode LBAP en ce qui concerne les coordonnées. 

Ceci a aussi un impact sur le speaker setup quand on change l'algorithme. À ce moment il faudrait alors garder les cordonnées cartésiennes, puisque elles sont cohérentes dans les deux format. 

Nicola et Christophe

**Comment by belangeo** [comment]
La conversion de VBAP à LBAP utilise maintenant les coordonnées X-Y-Z, ce qui maintient la forme globale du setup. 

> si possible, que les paramètres distance et elevation se comportent de la même manière dans les deux algorithmes.

Impossible, c'est l'essence même des algos qu'il faudrait changer...

Quant à changer les noms de distance et d'élévation en LBAP, j'ai des réserves... Je suis plus en mode « finaliser la version 2 » que « tout chambouler le code » et comme la clarté du code dépend directement de la relation entre les noms de variables et les noms de paramètres, ce serait un changement à haut risque.

**Comment by Normandeau** [comment]
V208
Je suis d'accord avec Olivier: deux algorithmes impliquent deux concepts différents de distance et d'élévation. L'utilisateur doit être au courant de cela. Et la situation dans laquelle un utilisateur passe d'un setup de concert de format dôme à un setup identique de format CUBE est très hautement improbable. Chaque setup impliquant le choix d'un algorithme déterminé.
Cependant, j'ai tout de même une observation à faire.
Quand Olivier dit: «La conversion de VBAP à LBAP utilise maintenant les coordonnées X-Y-Z, ce qui maintient la forme globale du setup.», je ne suis pas certain de bien comprendre. En effet, avec un setup CUBE24, fabriqué avec 205:
![CUBE24 Show CUBE](https://user-images.githubusercontent.com/8959779/73122640-22fd0a00-3f55-11ea-90d4-52f5a75336c5.jpg)

 lorsque je passe de la représentation CUBE à DOME, cela me donne un dôme:
![CUBE24 Show DOME](https://user-images.githubusercontent.com/8959779/73122645-3019f900-3f55-11ea-8a56-1693d8b841f3.jpg)

Et si j'examine les coordonnées des haut-parleurs dans la fenêtre d'édition, j'observe des changements de données, autant en XYZ qu'en Azimuth-Elevation-Distance. CUBE24 édité en mode CUBE:
![CUBE24 Edit CUBE](https://user-images.githubusercontent.com/8959779/73122677-8850fb00-3f55-11ea-9d7b-cb7f0a2dee6f.jpg)

CUBE24 édité en mode DOME:
![CUBE24 Edit DOME](https://user-images.githubusercontent.com/8959779/73122682-97d04400-3f55-11ea-97a6-4c262ba7dc03.jpg)

**Comment by Normandeau** [comment]
Autre exemple plus «troublant» peut-être. À Nice, à cause de problème majeur de triangulation dans l’algorithme DOME, j'ai refait leur setup de 26 hp en mode CUBE. Il adopte cependant la forme d'un dôme:
![MICA CUBE26 Show CUBE](https://user-images.githubusercontent.com/8959779/73122790-c4d12680-3f56-11ea-8e65-be92365b703a.jpg)

On obtient une forme approximativement identique dans sa représentation en format DOME (Il faudrait sans doute raffiner les coordonnées du CUBE pour s'approcher du DOME. Mais ce n'est pas le point ici, voir plus bas):
![MICA CUBE26 Show DOME](https://user-images.githubusercontent.com/8959779/73122795-d61a3300-3f56-11ea-9a8b-0ec8290af97e.jpg)

Quand on ouvre la fenêtre d'édition du CUBE on trouve ceci:
![MICA CUBE26 Edit CUBE](https://user-images.githubusercontent.com/8959779/73122864-930c8f80-3f57-11ea-9046-044800131821.jpg)

Et quand ouvre le même speaker setup on mode DOME, voici ce qu'on observe:
![MICA CUBE26 Edit DOME](https://user-images.githubusercontent.com/8959779/73122885-c5b68800-3f57-11ea-8eb0-39467719abf3.jpg)

D'où ma question: qu'est-ce que cela veut dire exctement: «La conversion de VBAP à LBAP utilise maintenant les coordonnées X-Y-Z, ce qui maintient la forme globale du setup.»?

**Comment by belangeo** [comment]
C'est seulement lorsque l'on passe du VBAP au LBAP que le ServerGris utilise les coordonnées XYZ du setup pour éviter l'éclatement du setup (dans les versions précédentes, un dôme en VBAP devenait un genre de cube avec les HPs du haut poussés vers l'extérieur). Cela ne s'applique pas au passage de LBAP à VBAP puisqu'en VBAP, on a pas le choix de ramener la distance à 1...

**Comment by NicolaGiannini** [comment]
Il faudrait peut-être ajouter les éléments suivants au manuel :

Elevation et la Distance n'ont pas le même comportement dans les
algorithmes DOME et CUBE (on pourrait également ajouter une explication
graphique).

Un speaker set up conserve son apparence et ses coordonnées XYZ lors du
passage de l'algorithme DOME à l'algorithme CUBE, mais pas dans le cas
inverse.



Il giorno sab 25 gen 2020 alle ore 10:06 Olivier Bélanger <
notifications@github.com> ha scritto:

**Comment by Normandeau** [comment]
V211
Mis dans le manuel.
