### ISSUE TITLE
Speaker Setup - En mode LBAP, la limite de Z est de 1 pour les valeurs positives alors qu'elle est "- infinie" pour les valeurs négatives.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#170]
ServerGRIS 2.07
Speaker Setup - En mode LBAP, la limite de Z est de 1 pour les valeurs positives alors qu'elle est "- infinie" pour les valeurs négatives.

Je pense que cela est dû, en partie, au lien entre Z et Elevation, et au fait que les limites de Elevation sont de +90 et -90. 

Lorsque je définis les positions des haut-parleurs, si je saisis une valeur de -5 pour Z, en élévation une valeur de -450 est affichée, et si je sauvegarde le speaker setup, ces valeurs sont sauvegardées. Par contre, si je touche ensuite la valeur de -450 en Elevation avec la souris, elle passe à -90.

Quant aux valeurs positives, si j'introduis une valeur supérieure à 1 dans Z, cela ne s'affiche pas correctement, quelques exemples :
2 devient 0
4 devient -2
5 devient -3
8 devient -6
etc.

Quant aux X et Y, je peux insérer les valeurs que je veux et elles sont affichées correctement, positives et négatives, et supérieures à 1.

**Comment by belangeo** [comment]
Corrigé!

**Comment by Normandeau** [comment]
V208
Réglé
