### ISSUE TITLE
Calibration du Gain vs Outputs et documents par défaut.

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#171]
V208
«Changed master gain unit to dB instead of linear amplitude.»
Très bien d'avoir une échelle en dB. Comme je suis en pleine réflexion sur la question de la calibration, ma question ne vous surprendra pas: quelle sorte de dB? Et quelle est la relation entre cela et les niveaux de sorties?
Vérification: si je mets un signal à 1000 Hz de 0dBFS (Full Scale) en entrée, il sort maintenant au niveau nominal de 0dBFS lorsque le Gain est ajusté à 0dB. Cela signifie qu'on a maintenant **une valeur de gain maximale de +18dB**, puisque le Gain permet cela. C'est donc une amélioration... dangereuse, lorsqu'on ouvre des anciens projets où le gain était ajusté au maximum (j'ai toujours travaillé avec le gain au maximum, qui était à 0dBFS jusqu'à aujourd'hui)!
**À mettre dans le manuel!**
Cela me fait penser que si on fournit un speaker setup par défaut avec ServerGRIS, on ne fournit pas de document par défaut. Qu'est-ce qui se passe lorsqu'on ouvre ServerGRIS pour la première fois? Je ne le sais plus, mais ça serait bien de fournir un projet de base. Je m'en occupe.
Je vais aussi m'occuper de récolter des speaker setups de différentes institutions, afin de les inclure dans nos templates.

**Comment by belangeo** [comment]
C'est pas obligé de mettre 18 dB de head room, c'est un réflexe quand je configure un potentiomètre en dB. Facile à changer!

> Qu'est-ce qui se passe lorsqu'on ouvre ServerGRIS pour la première fois?

0 dB (1 en linéaire).

**Comment by Normandeau** [comment]
Bonjour,

La plupart des séquenceurs audio sur Mac (DP, Logic et Live) offrent +6dB au-dessus du 0 nominal.
Seul Reaper offre +12dB.

Comme ServerGRIS est un mixeur inversé, c'est-à-dire qu'il répartit l'énergie en la divisant vers plusieurs sorties., j'irais vers +12dB.
18dB m'apparaît exagéré.

Qu'en dites-vous?

Profitons-en pour discuter calibration et VU-mètres.

Si on modifie le Gain en permettant +12dB par exemple, il faudrait que cela se reflète dans nos VU-mètres de sortie.
Actuellement, avec un niveau d'entrée à 0dBFS avec un sinus à 1000Hz, le VU-mètre de ServerGRIS indique quelque chose comme -3dB.
Et en assignant le signal à une sortie directe, avec un Gain à 0dB, on a la même chose en sortie, soit -3dB affiché (ce qui entre, sort exactement pareil).
C'est-à-dire que si on se fie aux autres instruments de mesure, c'est une valeur RMS qui est affichée, correct?
(Le signal RMS est de -3dB pour un sinus (±) par rapport à la valeur Peak. Or c'est cette dernière qu'on retrouve sur tous les séquenceurs).

Donc si on permet +12dB de Gain, il nous faudrait une échelle avec une référence à 0dB et une valeur supplémentaire à +12 pour correspondre à la réalité (comme dans les séquenceurs, où le 0 n'est pas à la limite supérieure des potentiomètres).
Parce qu'actuellement, si je pousse le signal à +12 (et non pas à +18, car c'est vraiment trop), je fais écrêter tous les systèmes qui suivent ServerGRIS (cartes de son, appareils de mesure, etc.).

**Comment by belangeo** [comment]
> Donc si on permet +12dB de Gain, il nous faudrait une échelle avec une référence à 0dB et une valeur supplémentaire à +12 pour correspondre à la réalité (comme dans les séquenceurs, où le 0 n'est pas à la limite supérieure des potentiomètres).

Certain de ça? Il me semble que d'utiliser toute la longueur du potentiomètre pour afficher les valeurs utiles (jusqu'à 0dB) et une indication qu'on a clippé est plus pratique que de sacrifier des pixels pour des volumes qui ne seront pratiquement jamais atteints.

**Comment by Normandeau** [comment]
Olivier, Tu as un point. On peut l'essayer comme cela et à l'usage on verra ce que ça signifie. Je me mets tout de même une note afin d'informer les utilisateurs de la version 1, que le 0dB a changé de place dans le Gain.

**Comment by NicolaGiannini** [comment]
Je pense que la principale utilité des Vu Meters est de s'assurer qu'on ne dépasse pas 0. Probablement on a pas besoin d'afficher des valeurs supérieures à zéro.

Dans mon cas, je suis habitué avec Logic, qui permet aux faders d'aller jusqu'à + 6, mais le VU meter va jusqu'à zéro au maximum. Au-dessus du VU meter apparaît la valeur en chiffres indiquant de combien le zéro a été dépassé.

![Logic-Master](https://user-images.githubusercontent.com/35705913/74055270-b13dab00-49ad-11ea-9703-92a367e802f4.jpeg)

En Ableton le Vu Meter va jusqu'à + 6

![Live-master](https://user-images.githubusercontent.com/35705913/74055289-b7338c00-49ad-11ea-831d-e53bee69dc99.jpeg)


Reaper propose les deux modes, selon que la valeur indiquée est pour RMS ou PEAK (je crois).

![Reaper-Master](https://user-images.githubusercontent.com/35705913/74055298-bc90d680-49ad-11ea-96cb-3ea9fa43fb5a.jpeg)

Twisted Wave va  jusqu'à zéro.

![Twisted-Wave-Master](https://user-images.githubusercontent.com/35705913/74055308-c1ee2100-49ad-11ea-9bbd-77e605f3a1cd.jpeg)

Je pense qu'il suffit que le Vu Meter aille jusqu'à zéro.

 S'il est alors possible de faire ce que nous disions, c'est-à-dire un fichier d'analyse de l'enregistrement, indiquant quand le zéro a finalement été dépassé, je dirais que nous avons toutes les informations nécessaires (et dans tous les cas, cette analyse peut également être effectuée avec un autre logiciel).

**Comment by Normandeau** [comment]
SpatGRIS209
Crête mètres au lieu de VU-mètres.
Gain avec un headroom de +12dB
Excellent.

**Comment by Normandeau** [comment]
V211
Mis dans la manuel.
