### ISSUE TITLE
Mettre ServerGRIS à On remet toujours le nombre d'inputs à 128

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#172]
Le problème se pose quand on active ServerGRIS (On/Off) qui, même si on a réduit à 18 le nombre qui figure à End, finit toujours par mettre 128 Inputs après avoir été activé (pour les logiciels statiques, qui ont 128 canaux de connexion avec Jack par défaut. Seul DP est dynamique dans ses attributions.

Olivier:
«Ça c'est un bug!»

Ah, ENFIN!!!
Je pense qu'on est tellement habitué à cela, qu'on a fini par croire que c'était normal.

**Comment by NicolaGiannini** [comment]
Je confirme, même chose avec Logic. Lorsqu'on active ServerGRIS, le nombre des inputs revient toujours à 128.

**Comment by Normandeau** [comment]
SpatGRIS210
Mettre SpatGRIS210 à On remet toujours le nombre d'inputs à la valeur de End (soit 64 la nouvelle valeur par défaut). Si on change la valeur de End, c'est maintenant celle-là qui prévaut.
À expliquer clairement dans le manuel.

**Comment by belangeo** [comment]
Seulement si Inputs est plus petit que End, n'est-ce pas?

**Comment by Normandeau** [comment]
Exact. À préciser également.

**Comment by NicolaGiannini** [comment]
La valeur END n'est pas sauvegardée avec le projet, donc si je travaille sur un projet qui utilise plus de 64 sorties, chaque fois que je redémarre SpatGRIS, je dois changer la valeur END, car elle est automatiquement remise à 64 (sinon les sorties avec une valeur de output supérieur à 64 ne fonctionnent pas).

**Comment by Normandeau** [comment]
Dans DP, l'allocution dynamique que l'on voyait à End jusqu'à ce jour est maintenant disparue.
• J'avais un projet ouvert avec 8 sorties DP.
• Je ferme ce projet et j'en ouvre un autre de 94 sorties
• Inputs est ajusté à 94 mais End reste à 8, même si je mets SpatGRIS à Off ou à On.
• Il faut que je remette End à 94 manuellement.
Heureusement, le End est dynamique, pas besoin de repasser à Off/On, donc les nouvelles pistes ajoutées sont automatiquement activées.
• Je sauvegarde le projet
• Je ramène Inputs et End à 16
• Je rouvre le projet, Inputs est remis à 94 mais End reste à 16.
• Je remets End à 94.
• J'ouvre un autre projet plus petit à 18 entrées: Inputs est mis à 18 mais End reste à 94 et il n'y a pas d'audio
• Tête de linotte, je ne pense à rien et je fais Off/On, alors je me retrouve avec du son mais avec 94 Inputs.
• Il aurait fallu que je ramène End à 18 avant de faire Off/On bien évidemment.
Cela ne fait que confirmer que la valeur de End n'est pas sauvegardée avec le projet, quelle qu'en soit la valeur.
C'est dommage, parce que ça fonctionnait si bien «dans l'bon vieux temps»!

**Comment by Normandeau** [comment]
Question: est-ce un bogue? Une fatalité? Une amélioration potentielle?

**Comment by NicolaGiannini** [comment]
v211
La valeur END n'est pas sauvegardée avec le projet, donc si je travaille sur un projet qui utilise plus de 64 sorties, chaque fois que je redémarre SpatGRIS, je dois changer la valeur END, car elle est automatiquement remise à 64 (sinon les sorties avec une valeur de output supérieur à 64 ne fonctionnent pas).

Si on peut pas sauvegarder une valeur END majeure de 64, il faudrait l'indiquer dans le manuel.

**Comment by belangeo** [comment]
Dans la mesure où les clients ne font pas partie de la sauvegarde d'un projet (ils apparaissent/disparraisent au fur et à mesure des ouvertures/fermetures de logiciel), je ne vois pas comment on pourrait sauvegarder la valeur de END!

**Comment by NicolaGiannini** [comment]
Je comprends! Donc il faut indiquer dans le manuel que si le nombre des inputs utilisés est majeur de 64, il faut se rappeler d'ajuster la valeur END à main. Au moins avec Logic.

**Comment by Normandeau** [comment]
V211
Mis dans le manuel
