### ISSUE TITLE
Représentation graphique ControlGRIS/ServerGRIS

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#173]
V208
Très bien la notion d'éloignement est maintenant intégrée dans ServerGRIS en mode CUBE.
Maintenant il va nous falloir établir une relation graphique claire entre ControlGRIS et ServerGRIS.
Dans l'exemple illustré, afin de profiter de la notion d'éloignement, j'ai fabriqué un dispositif de 10 hp dont les distances maximales sont de 0.3 ou 0.5. Voici comment cela est représenté dans le ServerGRIS, vu du dessus. J'ai laissé volontairement un hp à une distance de 1, afin de valider mon point plus loin:
![CUBE à 0 5](https://user-images.githubusercontent.com/8959779/73219501-47f6a600-412a-11ea-8097-30567d1492aa.jpg)

J'ajoute un ControlGRIS avec 8 sources à 0.5 de rayon:
![ControlGRIS à 0 5](https://user-images.githubusercontent.com/8959779/73219511-5349d180-412a-11ea-8852-61d91942d337.jpg)

Voici à quoi ça ressemble dans le ServerGRIS:
![ControlGRIS + ServerGRIS à 0 5](https://user-images.githubusercontent.com/8959779/73219526-5f359380-412a-11ea-8e50-440860962ce8.jpg)

Donc c'est un peu n'importe quoi. Il faut unifier les échelles graphiques avec les échelles physiques. D'ailleurs ça pose la question des limites physiques. Actuellement, la distance dans le Speaker Setup n'est pas limité. À partir de 7 par exemple, avec un zoom out maximal le hp n'est plus représenté dans le graphique. Et en fait, selon différentes configurations de zoom, à partir de 3, le hp disparaît de l'affichage.
Je propose donc qu'on limite la représentation graphique du ServerGRIS avec trois carrés (il y en a 5 actuellement), un premier à 0.5, un second à 1 et le troisième à 2. Et qu'on fasse la même chose dans ControlGRIS.
Actuellement dans ControlGRIS, la valeur maximale est 1, ce qui correspond à un rayon de 2 dans le ServerGRIS. Cela devrait être unifié:
![ControlGRIS à 1 - ServerGRIS à 2](https://user-images.githubusercontent.com/8959779/73219548-71173680-412a-11ea-8b4c-b78a69368fe6.jpg)

La distance maximale pourrait alors être limité à 2. Cela pourrait représenter un hp qui serait installé de manière excentrique à la salle de concert, dans un corridor par exemple.
Qu'en dites-vous? Est-ce que j'oublie quelque chose?

**Comment by Normandeau** [comment]
Je viens d'ouvrir la fenêtre 2D à ce sujet. Elle correspond déjà à nos besoins!!! C'est à dire qu'elle reflète fidèlement l'information graphique reçue de ControlGRIS et le facteur d'atténuation qui commence bien ici au 3e carré (ou au 2e carré accentué).
Donc ce qu'il faut c'est ajuster la représentation graphique de la fenêtre 3D afin de la rendre conforme aux deux autres représentations:

![ControlGRIS 0 6, 2D et 3D](https://user-images.githubusercontent.com/8959779/73270031-ee36c000-41ab-11ea-8106-a46275445821.jpg)

**Comment by belangeo** [comment]
Ok, la vue 3D est calibrée de la même façon que les vues 2D. Il restera à ajouter le carrée central dans le ControlGris pour qu'elles soient identiques. Dans le speaker setup, j'ai clippé la distance à 2.5, parce que la distance est plus grande dans les coins du carrée que vis-à-vis les axes. Je vais ajuster l'affichage de la distance dans le ControlGris pour que les deux représentations soient conséquentes.

**Comment by NicolaGiannini** [comment]
En ce qui concerne la limite de distance : 2 pourrait être un bon chiffre, également pour rester cohérent et compatible avec les Speaker Setup et les projets que nous avons jusqu'à présent. 
(toutes les configurations de haut-parleurs que nous avons en VBAP ont évidemment une distance de 1 par rapport au centre).

Mais je pensais à l'installation de Claude Champagne pendant Ultrasons. Si nous voulions faire Speaker Setup qui inclut tous les haut-parleurs que nous utilisons, peut-être pour inclure ceux du fond de la salle (côté opposé de la scène), une valeur de 2 n'est pas suffisante. Peut-être que 3 pourrait donner plus de liberté ? Qu'en pensez-vous ?

**Comment by Normandeau** [comment]
Il faut comprendre qu'on est dans la représentation symbolique et non pas géographique, physique ou réelle. C'est le choix qu'on a fait depuis le début en 2008. Par exemple, on n'entre pas les dimensions réelles de la salle de concert dans nos logiciels. C'est comme le plan du métro. Les distances ne sont pas les bonnes, mais une station après l'autre tu arrives au but.
Si on a besoin de placer un hp très loin, on fait le cercle de hp plus petit. L'utilisateur doit comprendre que l'espace représenté est relatif et abstrait. C'est comme cela que SpatGRIS fonctionne avec les trois zones d'intensité. Bien sût il faudra valider, mais je pense que si on veut faire partir un son au lointain, avec les réglages actuels, ça devrait fonctionner assez bien.

**Comment by Normandeau** [comment]
SpatGRIS209
Bonne correspondance entre les trois affichages: ControlGRIS en LBAP, fenêtres 2D et 3D dans SpatGRIS209.
