### ISSUE TITLE
Changement de nom: SpatGRIS V2

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#174]
Bonjour,
À la suite de la discussion de l'automne dernier et compte tenu d'une plus grande facilité à prononcer et retenir le nom, je propose que la prochaine version du ServerGRIS, soit rebaptisé SpatGRIS v2.0.9 (pour être conséquent avec le développement, puisque nous en sommes actuellement à la version 2.0.8)
Il sera «commercialisé» comme un kit, nommé SpatGRIS 2, comprenant ControlGRIS (un plugiciel) et SpatGRIS v2 (un logiciel de spatialisation). Et avec ce kit, il sera possible de faire de la 2D (issu de SpatGRIS 1) ou de la 3D (issu de ServerGRIS 1). SpatGRIS 2 est tout simplement la fusion des versions 1 de nos outils précédents.
Le kit comprendra aussi des templates plus nombreux et mieux identifiés, notamment pour les dômes. Il est plus difficile de faire la même chose pour les acousmoniums car leurs configurations changent constamment. Je ne connais qu'un seul acousmonium permanent, c'est à Weimar, en Allemagne. Mais on pourra proposer VTech et d'autres types de CUBE (des cylindres, des murs, des galeries, etc.).

Olivier a écrit le 24 octobre:
«Par contre, il faudra peut-être créer un nouveau projet sur github (ou le garder sous le nom ServerGRIS) si on ne peut modifier le nom du projet (je dois vérifier)»
Github est notre référence à nous, aucune objection à ce que le site de développement reste sous le nom de ServerGRIS dans mon cas.

**Comment by belangeo** [comment]
Un petit détail... Est-ce qu'on veut que le nom du logiciel (visible à l'utilisateur) soit «SpatGRIS2» ou «SpatGRIS» tout court?

**Comment by Normandeau** [comment]
Olivier,

Je constate que les logiciels affichent ou pas leur numéro de version dans leur nom.
D'un côté on a ainsi Digital Performer, Reaper, iTunes, Twisted Waves, SoundGrain.
Et de l'autre, on a Logic X, Ableton Live 10, Cecilia5, AudioSculpt 3.4.5.

Je pense qu'on devrait continuer comme on faisait avec ServerGRIS.
On aurait dans la fenêtre About:
SpatGRIS

Et quand on l'ouvre, dans la barre en haut de la fenêtre, on aurait le nom SpatGRIS avec le numéro de version.

Donc la notion de SpatGRIS 2 serait de l'ordre de notre «stratégie commerciale et dans le manuel.

**Comment by belangeo** [comment]
Ok, donc, le nom de l'application est SpatGRIS.app .

**Comment by Normandeau** [comment]
Yep!
