### ISSUE TITLE
Le Gain n'affecte que les VU mètres de sortie mais pas... l'audio!!!

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#175]
SpatGRIS 2.0.9
Le Gain n'affecte que les VU mètres de sortie et l'activité des hp mais pas... l'audio!!!

On voit ici que malgré un gain de -60dB, l'audio sort bien de la carte son, mais ne passe ni par les hp de la fenêtre 3D, ni par les Vu-mètres:

![Gain à -60dB](https://user-images.githubusercontent.com/8959779/73765772-05912280-4743-11ea-8db5-c38ee10b7e4e.jpg)

Avec un Gain de 0dB  l'audio sort bien de la carte son, et passe par les hp de la fenêtre 3D, et par les Vu-mètres, mais le niveau audio n'est pas affecté:

![Gain à 0 dB](https://user-images.githubusercontent.com/8959779/73766006-67518c80-4743-11ea-9cc4-beb179e8c8b9.jpg)

**Comment by Normandeau** [comment]
J'ajoute que le niveau de sortie est très nettement plus fort qu'avant, les sorties écrêtent très rapidement.

**Comment by belangeo** [comment]
> Le Gain n'affecte que les VU mètres de sortie et l'activité des hp mais pas... l'audio!!!

Wow, si je ne m'abuse, ça date des toutes premières versions du ServerGris! C'est réglé.

> J'ajoute que le niveau de sortie est très nettement plus fort qu'avant, les sorties écrêtent très rapidement.

Il n'y a rien qui a changé dans cette région du code depuis belle lurette il me semble...

**Comment by Normandeau** [comment]
Vérification faite, le gain fonctionne normalement avec la 2.0.8!
Avec SpatGRIS 2.0.9, puisque le contrôle de gain n'affecte pas les sorties audio, peut-être qu'on est tout de suite à +12. Parce que de mon côté, je n'ai presque jamais vu les vu-mètre écrêter autant, voire presque jamais. Alors que là, avec les mêmes projets, ça écrête sévère!

**Comment by Normandeau** [comment]
SpatGRIS2.0.9.
SpatGRIS écrête, mais pas la carte de son:

![Capture d’écran, le 2020-02-04 à 13 24 59](https://user-images.githubusercontent.com/8959779/73774681-6aa04480-4752-11ea-96ed-15c7607630d7.jpg)


Même passage, ServerGRIS 2.0.8, niveau correct partout:

![Capture d’écran, le 2020-02-04 à 13 28 26](https://user-images.githubusercontent.com/8959779/73774646-56f4de00-4752-11ea-92a5-eecbb6e3aaf0.jpg)

**Comment by belangeo** [comment]
Sans le contrôle de gain, c'est fixe à 0dB. En effet, en passant de la représentation RMS à peak, j'ai enlevé la multiplication par le master gain. Ce qui n'est pas ue mauvaise chose au final puisqu'elle n'était pas faite là où elle devrait être! C'est réparé.

Pour la question des vu-mètres qui écrêtent, ce ne serait pas par hasard le fait qu'ils affichent maintenant la valeur peak? Si le master gain était ajusté à la baisse dans le projet, ça a aussi une influence puisque tu es à 0dB présentement...

**Comment by belangeo** [comment]
Aussi, avec le changement de nom et tout, il vaut mieux jeter le dossier GRIS qui est dans Aplication Support, juste pour être certain qu'il n'y a pas de conflit de configuration.

Avec les dernières sources (le gain réparé), si j'envoie un signal à -3dB (de pyo) dans l'input 1, avec sa position pile sur le premier HP, le vu-mètre de sortie du SpatGris me donne bien -3dB.

**Comment by Normandeau** [comment]
SpatGRIS 210
Réglé.
