### ISSUE TITLE
Sources en mode DOME dans un setup CUBE

### ISSUE THREAD

**Issue by belangeo** [GRIS-UdeM/SpatGRIS#176]
Un mode CUBE/DOME dans lequel on peut sélectionner d'être en DOME par source dans un CUBE global.

**Comment by Normandeau** [comment]
Excitant!

**Comment by NicolaGiannini** [comment]
Ce serait vraiment super !
Il m'arrive souvent d'utiliser des trajectoires réalisées dans SpatGRIS (l'ancien plugin de contrôle) dans des speaker setup CUBE (ayant pour objectif d'utiliser la spatialisation créée dans un projet DOME/VBAP dans un contexte CUBE/LBAP).

Les trajectoires réalisées avec SpatGRIS (l'ancien plugin de contrôle) donnent lieu au même mouvement dans les modes CUBE et DOME, alors que les trajectoires réalisées avec ControlGRIS en mode VBAP, ont un comportement différent dans les modes CUBE et DOME. 

Voir les deux vidéos :
SpatGRIS (plugin de contrôle) https://www.dropbox.com/s/r1frxxtikxn4lw7/SpatGRIS.mov?dl=0
ControlGRIS https://www.dropbox.com/s/6s0cp8au87fixwt/Controlgris.mov?dl=0 

Avec SpatGRIS, il était possible de transporter, grosso modo, un travail effectué en mode DOME/VBAP vers un contexte CUBE. Il serait pratique de pouvoir le faire aussi avec ControlGRIS.

**Comment by SamuelBeland** [comment]
v3.0.0

Pas parfait.

https://user-images.githubusercontent.com/39448259/128942440-2ac26ccf-017a-4e36-b667-c4001c35f9b1.mp4

**Comment by Normandeau** [comment]
Oui on peut s'attendre à cela dans un mode hybride. Mais il faut se demander ce que cela signifie sur le plan de la perception cependant.
La question la plus importante selon moi est plutôt celle des spans. Est-ce qu'il serait possible de faire cohabiter les deux sortes de spans dans un mode CUBE? Autrement dit de garder les spans de type DOME de ControlGRIS en passant au mode CUBE dans SpatGRIS3. pour le moment, c'est l'algorithme de SpatGRIS qui a prévalence.

**Comment by Normandeau** [comment]
311
En fait c'est plutôt l'inverse qu'on aujourd'hui, un DOME à l'intérieur duquel on peut entrer et sortir en mode CUBE. C'est déjà mieux que les deux algorithmes complètement indépendants.
