### ISSUE TITLE
Le terme LBAP est toujours affiché dans le message d'alerte qui apparaît lorsque on tente de visualiser les triplets en mode CUBE.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#177]
SpatGRIS 2.1.0
C'est un détail. Le terme LBAP est toujours affiché dans le message d'alerte qui apparaît lorsque on tente de visualiser les triplets en mode CUBE.

On pourrait peut-être mettre :  Triplets are not effective with the CUBE mode.

**Comment by Normandeau** [comment]
V211
Bon message
![Can't draw triplets](https://user-images.githubusercontent.com/8959779/77833353-104cb000-7113-11ea-9952-5e0a13fd658b.jpg)
