### ISSUE TITLE
Le message d'alerte sur les sorties directes (mismatch) apparaît seulement si les sorties sont totalement absentes du setup de hp

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#178]
Le message d'alerte sur les sorties directes mismatch) apparaît si on passe au mode stéréo ou binaural. Dans ces cas probablement il n'est pas necessaire.

**Comment by Normandeau** [comment]
Issue #130 
Le sorties directes sont pourtant prises en charge depuis le règlement de cette issue sur l'ajout des sorties directes dans la sortie stéréo.

**Comment by Normandeau** [comment]
V210
Aujourd'hui le message de Mismatch n'apparaît jamais quand je passe d'un projet à l'autre. La raison de cela difficile à identifier, car hier je l'avais à chaque changement.

**Comment by NicolaGiannini** [comment]
V210
Bonjour Robert,
en fait je crois que cela c’est lié au fait que :

maintenant le message d'alerte est affiché si on ouvre un speaker setup qui a des direct outs différentes de celles présentes dans le projet, mais il n'apparaît pas si on ouvre un projet avec des direct outs qui ne sont pas présentes dans le speaker setup. J'ai fait un issue, https://github.com/GRIS-UdeM/ServerGRIS/issues/182

**Comment by Normandeau** [comment]
Merci Nicola, bien identifié. Alors il faut **changer** le message de Mismatch!
En effet, quelle est la situation du compositeur?
1. Il travaille dans un studio donné avec un Speaker Setup particulier qui contient des sorties directes particulières.
2. Il ouvre différents projets qui ont peut-être été réalisés dans d'autres studios avec d'autres Speakers Setup qui contiennent d'autres sorties directes (par exemple quand il passe de son studio personnel au studio institutionnel).
3. Il reçoit un message l'avertissant que le projet qu'il ouvre ne contient pas les sorties directes du dispositif sur lequel il travaille EN ce moment.
Mais pas l'inverse! S'il ouvre un autre speaker setup qui n'est pas celui dans lequel il travaille EN ce moment, ça le regarde, tout le monde a droit à l'erreur, non?
On ne peut faire ouvrir une fenêtre de mismatch chaque fois qu'un utilisateur se trompe...

**Comment by Normandeau** [comment]
Pour résumer.
Le message actuel s'affiche lorsqu'on ouvre un Speaker Setup dont les Direct Outs ne correspondent pas au projet ouvert:

![Mismatch Speaker Setup](https://user-images.githubusercontent.com/8959779/75557198-e3d44400-5a3f-11ea-8a53-8de4319b87e0.jpg)

En fait le message est correct, mais il ne s'ouvre pas de la bonne manière. Le message devrait s'ouvrir lorsqu'on ouvre un projet dont les Direct Outs ne sont pas les bonnes par rapport au Speaker Setup sur lequel on travaille. En effet, on ne va pas changer les sorties directes du dispositif parce que le projet n'est pas associé à celles qu'il faut!

Peut-être que le message pourrait être plus explicite:
Some of the direct out channels of this project don't exist in the current speaker setup.

Hence the confusion!
Plus clair?

**Comment by belangeo** [comment]
Yep!

**Comment by Normandeau** [comment]
V211
Le message apparaît correctement et il est bien formulé. Excellent.

**Comment by Normandeau** [comment]
J'ai écrit un peu vite. Le message de Mismatch est toujours problématique, mais d'une autre manière. À moins que je n'ai mal compris la proposition.
Voici le message:

![Direct Out Mismatch](https://user-images.githubusercontent.com/8959779/77832800-fdd07780-710e-11ea-9701-a7474e1552dd.jpg)

Stricto sensu, le message est exact, mais nous donne-t-il la bonne information?
Si les numéros des sorties directes d'un projet qu'on ouvre sont compris dans le setup de hp en général, on ne reçoit pas le message. On reçoit le message uniquement si les numéros des sorties directes d'un projet qu'on ouvre ne font pas partie DU TOUT du setup de hp ouvert.
J'ai fabriqué un projet avec des sorties directes 17-18. Je le sauvegarde et j'ouvre un autre projet. J'ouvre un setup de hp comme le dôme 32-MOTU (sorties 1 à 34, sorties directes 33-34). Je rouvre le projet 17-18: je n'ai pas le message car les sorties 17-18 font partie du setup de hp.
Je refais le même exercice avec le dôme 32-UFX (sorties 31 à 60, sorties directes 5-6). En rouvrant le projet 17-18, là j'obtiens le message, parce que 17-18 ne font pas partie DU TOUT du setup de hp.
Si l'intention était d'avertir l'utilisateur que les sorties directes n'étaient pas DU TOUT disponibles, alors le message est correct. Mais ce n'est pas ce qui a été noté ici: on dit bien, plus haut, que le mismatch devait décrire une situation où les sorties directes d'un projet seraient DIFFÉRENTES de celles du setup de hp. Pas ABSENTES du setup de hp. Vous voyez la différence? Actuellement, il ne s'agit donc pas d'un mismatch, mais d'un Direct Out Missing.
Dans l'exemple 1 où mon projet 17-18 s'ouvre sans avertissement, je peux penser que mes sorties directes sont OK puisque je n'ai pas de message. Mais elles sont erronées, puisque les sorties directes de ce setup de hp sont à 33-34.

Donc de deux choses l'une: ou on revient à un message de mismatch exact: si les sorties directes d'un projet qu'on ouvre ne correspondent pas à celles du setup de hp, on reçoit le message.
Ou: on laisse faire ce genre de message et on fait confiance aux utilisateurs. Parce que la situation actuelle est source de confusion.
Qu'en dites-vous?

**Comment by NicolaGiannini** [comment]
Si c’est possible j’afficherais un message de mismatch exact, sinon on peut l’indiquer dans le manuel.

**Comment by belangeo** [comment]
En effet, ce l'on veut, c'est comparer non pas avec tous les outputPatch mais seulement ceux qui sont des sorties directes, right?

**Comment by Normandeau** [comment]
C'est comme cela que javais compris l'idée du message en tout cas. Si c'est possible.

**Comment by Normandeau** [comment]
V212
Réglé

**Comment by Normandeau** [comment]
V212
Cette issue n'est pas résolue finalement. En fait, il semble que le message apparaît la première fois qu'on ouvre un document avec des sorties directes qui ne sont pas présentes dans le Speaker Setup actif. Si on fait le changement afin d'attribuer les bonnes sorties directes, mais qu'on ne sauve pas ce changement, la fois suivante qu'on ouvre le même document, alors que les sorties directes sont encore mal attribuées, le message d'erreur n'apparait pas..

**Comment by NicolaGiannini** [comment]
Je confirme. 

Le message d'erreur n'apparait pas même si on ouvre un document avec des sorties directes qui ne sont pas présentes dans le Speaker Setup actif, on ne fait pas des changements, et on redémarre SpatGRIS2, alors que les sorties directes sont encore mal attribuées.

**Comment by Normandeau** [comment]
V215
On mettra une note dans le manuel de sauver ses sorties directes, parce qu'en général, le message assume bien sa fonction....

**Comment by Normandeau** [comment]
V219
Les message de mismatch est actuellement erroné, car les sorties directes sont carrément éliminées maintenant. Voir issue #242

**Comment by Normandeau** [comment]
V2110
Résumons cette longue saga.
1. Situation 1: Sorties directes > speaker setup
Si on ouvre un projet avec des sorties directes (22-30 par exemple) dont les numéros n'existent pas du tout dans le speaker setup (dont le plus grand numéro est 12), on reçoit le message de Mismatch: OK.

2. Situation 2: Sorties directes incluses dans speaker setup
Si on ouvre un projet avec des sorties directes (11-12 par exemple) dont les numéros existent dans le speaker setup (1 à 30, sorties directes 6, 14, 22, 30), on ne reçoit pas le message de Mismatch bien que ce soit la réalité: Erreur.
C'est la même situation à l'inverse. Si un projet est ouvert avec des sorties directes sur 11-12 par exemple, et qu'on ouvre un speaker setup qui comprend ces numéros mais qui ne sont pas des sorties directes, on n'a pas de message. Erreur.

3. Situation 3: Sorties directes inexistantes dans speaker setup
Si on ouvre un projet avec des sorties directes (11-12 par exemple) dont les numéros n'existent pas du tout dans le speaker setup (5-6 et 31-61), on reçoit le message de Mismatch: OK.

En conclusion, ce n'est pas fiable et ça fait depuis février 2020 qu'on essaie de résoudre cela. Je propose deux options:
1. On fait apparaître ce message si et seulement si les sorties directes ne sont pas **exactes** entre le setup et le projet, peu importe que ce soit l'un ou l'autre qui, à l'ouverture, ne soit pas compatible avec celui déjà ouvert. Autrement dit quand le son ne sortira pas au bon endroit.
2. On oublie cela et on laisse à l'utilisateur la responsabilité de faire ses branchements comme il faut.

**Comment by Normandeau** [comment]
Étant donné la nouvelle configuration des sorties directes qui existent à la fois en mode exclusif et en attribution des entrées, on va faire disparaître le message de Mismatch. En effet les situations où cela peut se produire sont trop nombreuses pour que ce message, qui n'a jamais été juste, puisse l'être éventuellement...
Mais je lance un concours! Pour des questions de clarté dans le manuel, il nous faudrait distinguer les sorties directes exclusives et celles du setup de hp. Vos suggestions sont bienvenues (par courriel... ou GRIS Dev)
