### ISSUE TITLE
Des valeurs non consécutives de OUTPUT peuvent créer, lors de l'enregistrement, des pistes qui ne font pas partie du Speaker Setup

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#179]
SpatGRIS 2.1.0
Certaines valeurs de OUTPUT pour les sorties directes peuvent créer, lors de l'enregistrement, des pistes qui ne font pas partie de Speaker Setup.

J'ouvre SpatGRIS

1) Je crée une configuration de haut-parleurs avec un ring de 8 haut-parleurs en mode DOME, avec des valeurs de OUPUT allant de 1 à 8.

2) J'ajoute une sortie directe avec la valeur OUTPUT à 9. 
Lorsque je configure l'enregistrement, 9 fichiers mono sont correctement créés.

3) Je modifie l'OUPUT de la sortie directe de 9 à 20. 
Je configure l'enregistrement, des pistes supplémentaires sont créées qui ne sont pas dans le speaker setup : les pistes de 10 à 16 et ensuite les pistes 18 et 19.

**Comment by NicolaGiannini** [comment]
Petit update, 
les sorties directs ne sont pas impliquées. 
J’ai le même comportement en faisant une quadriphonie en utilisant les output 1, 2, 7, 8. Au moment de l’enregistrement, SpatGRIS crée également les pistes 5 et 6, qui, après l'enregistrement, seront vides.

**Comment by Normandeau** [comment]
Belle trouvaille. Confirmation.
Speaker Setup Quad+Sub avec les sorties réelles de Bordeaux (16, 18, 21, 23, 1):

![FauxNo Outputs](https://user-images.githubusercontent.com/8959779/75437111-fe31f300-5955-11ea-871f-04b0337b6022.jpg)

Recording, 16 fichiers mono:

![FauxNo Recording](https://user-images.githubusercontent.com/8959779/75437136-0722c480-5956-11ea-8df4-9e3509562e08.jpg)

Analyse audio et fichiers vides:

![FauxNo Audio](https://user-images.githubusercontent.com/8959779/75437435-7993a480-5956-11ea-93a2-6163e5bff258.jpg)

**Comment by Normandeau** [comment]
Infirmation
Si on utilise le setup du B187, avec Subs (5-6) et 32 hp (31 à 62), aucun problème.

Confirmation.
Si je charcute ce setup en enlevant au hasard certains hp et que je n'en garde que 22 (sur 34):

![FauxNo B187 charcuté](https://user-images.githubusercontent.com/8959779/75438332-0a1eb480-5958-11ea-8fbd-06f3c5103479.jpg)

Recording enregistre 25 fichiers (on voit que le sub 5 est toujours là, ainsi que les nos 57 et 60:

![FauxNo 25 sur 34](https://user-images.githubusercontent.com/8959779/75438386-23bffc00-5958-11ea-940c-b2b7606f1afe.jpg)

**Comment by Normandeau** [comment]
Infirmation
Si on utilise le setup de Bordeaux, avec Subs (1-2) et 19 hp (5 à 23), aucun problème.

Confirmation
Si je charcute ce dispositif en gardant que 13 des 21 hp, Recording en produit 17.

**Comment by Normandeau** [comment]
V211
Refait tous les tests décrits ci-haut. Tout fonctionne impec.
Attends confirmation de Nicola avant de fermer.

**Comment by NicolaGiannini** [comment]
Parfait! C'est réglé!
