### ISSUE TITLE
En mode stéréo, même avec une valeur d'interpolation maximale, la rotation d'un son grave crée des clics

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#180]
SpatGRIS 2.1.0

En mode stéréo, même avec une valeur d'interpolation maximale, la rotation d'un son grave crée des clics. 
Cela se produit surtout lorsque le son, pendant sa rotation, passe de 90 ou 270 degrés par rapport à l'azimut.

**Comment by Normandeau** [comment]
Je ne peux pas vérifier cela ici, car les sorties 1-2 sont affectées aux subs (donc je ne peux écouter la distorsion). Cela nous ramène à l'issue #101 
À quelle sorties sont affectées les sorties du mode Stéréo? Actuellement c'est 1-2. Ce serait excellent que ça soit définissable. Comme le faisait remarquer David, dans le 187, les deux hp frontaux sont 11-12. Ici à Bordeaux c'est 23-15.
Relire l'issue 101.

**Comment by Normandeau** [comment]
V217
Ceci est une vieille issue (plus d'un an). Toujours valide? Moi j'arrive  à la reproduire, mais seulement pour des rotations rapides, genre 1Hz.
Son grave, 50Hz, ça tourne, pas de distorsion en DOME, mais bruits de modulation en STEREO si l'interpolation est inférieure à 1.000. À cette dernière valeur, pas de problème, même en faisant tourner à 0,25Hz!

**Comment by NicolaGiannini** [comment]
Je confirme ce que Robert dit. Avec une interpolation de 1.000, il n'y a pas de bruits de modulation en ce qui concerne les rotations vites des sons graves. 

Il s'agit probablement de situations assez rares (rotations rapides de sons graves).

Une solution pourrait-elle être de permettre l'interpolation pour certaines pistes seulement ? Mais probablement trop compliqué pour un cas aussi rare ! Dans mon cas, je résous le problème en éliminant la rotation de la source grave dans les versions stéréo.

**Comment by Normandeau** [comment]
V218
Cas très rare. Si jamais le problème nous est signalé, on y reviendra.
