### ISSUE TITLE
Atténuation en hauteur en mode CUBE

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#181]
SpatGRIS210
En faisant des tests dans le dôme de Bordeaux, je me suis rendu compte que la limite supérieure du haut du CUBE n'affecte pas l'amplitude et le filtre, comme sur les axes x et y. Autrement dit, avec z, on ne peut pas faire disparaitre un son au lointain au-dessus de nos têtes. Que faisons-nous des voix célestes alors?
À corriger.

**Comment by NicolaGiannini** [comment]
Je suis d'accord. Je suppose que la contrainte est le lien entre le Z en mode CUBE et l'élévation (max 90 degrés) + distance en mode DOME.

**Comment by NicolaGiannini** [comment]
V214
Si l'on considère le mode CUBE et les trois axes XYZ représentés dans SpatGRIS, il est possible, grâce à ControlGRIS, de positionner les sources au-delà des limites en ce qui concerne X et Y mais pas en ce qui concerne Z.

Pour être sûr de bien comprendre : l'idée était de permettre de déplacer la source pour ce qui concerne Z comme il est possible de le faire aussi pour X et Y ?

Voir la vidéo : 


https://user-images.githubusercontent.com/35705913/102554874-a5be1480-4093-11eb-88a9-231bc98c3d9c.mov

**Comment by Normandeau** [comment]
Exact. Actuellement on a deux références dans SpatGRIS2: le petit carré et le grand carré. Le petit carré est celui à partir duquel l'atténuation (-12dB à -72dB)  et le filtre d'éloignement (filtre passe-bas de 125 à 16k) commence à agir. Le grand carré représente la valeur maximum d'atténuation.
La situation actuelle, c'est que ces deux références n'existe pas pour l'axe vertical. Or c'est très précisément cela qu'on aimerait voir ajouter. Afin de pouvoir éloigner un son dans l'espace vertical. Comme on met des anges et des oiseaux dans nos musiques, il faut qu'ils puissent disparaître dans le ciel, n'est-ce pas?

**Comment by led78** [comment]
Suite à quelques tests avec les Audiodices de la SAT, je remarque une grande disparité entre l'interpolation horizontale et verticale, si elle existe. Idéalement, il faudrait avoir deux boutons d'interpolation en mode CUBE; un pour le plan vertical et un pour le plan horizontal.

Le cas du Audiodice est particulier et implique beaucoup de choses, car il contient 12 haut-parleurs très rapprochés en comparaison à un disposition de salle composé essentiellement de haut-parleurs assez éloignés en circonférence. L'interpolation d'un tel haut-parleur multi-directionnel devrait avoir sa propre interpolation indépendante de l'ensemble d'un dispositif de salle. Mais c'est un autre sujet.

Il permet toutefois de mettre en évidence la grande disparité entre l'interpolation verticale (quasi nulle) et horizontale (trop diffuse). En effet, [dans ce vidéo](https://share.icloud.com/photos/0aftOj5nxNwezJLdZR3yPjDqw), on voit que le mouvement haut-bas d'une source active les haut-parleurs soit de la couche supérieure ou inférieure, sans transition; inversement, les mouvement gauche-droite et avant-arrière son à peine perceptibles, et ce, avec une interpolation minimale.

Une autre incohérence est la différence entre la position verticale (Z) d'une source et son étendue (span) verticale.
Par exemple, si on une position N à la valeur Z permet à la source d'activer un haut-parleur situé à cette position, ce n'est pas le cas de l'étendu; une source dont la valeur Z est 0, mais dont l'étendue atteint et même dépasse la valeur N n'activera pas le haut-parleur à cette position. [La présente vidéo manifeste cela, en plus de la disparition d'interpolation verticale et horizontale](https://share.icloud.com/photos/08f41b-OF_11hJbO9B5Lje2qQ).
Aussi, du moment où la source passe à la couche supérieure, elle n'est plus du tout diffusée par les haut-parleurs les plus rapprochés, mais uniquement par le seul haut-parleur dont la hauteur (Z) n'est pas 0. Il faut ajouter deux fois plus d'étendu vertical que leur position verticale relative pour que les haut-parleurs du sol soient activés (1m45).

**Comment by led78** [comment]
Moi et Louis-Olivier Desmarais venons de tester un dispositif en cube disposé sur deux étages en mezzanine (8 + 8), à la Chapelle Historique du Bon-Pasteur, et le constat est le même : il n'y a pas d'interpolation verticale. Également, on a remarqué que la valeur d'interpolation ne s'appliquait pas toujours immédiatement - on utilise un MacBook M1. Je n'ai pas testé davantage, mais en réduisant la valeur d'interpolation de SpatGRIS de 1 à 0, le son d'une source très localisée éclaboussait autant sur les autres. Puis, en élevant légèrement la source en hauteur (Z), le haut-parleur le plus près de la source n'émettait plus du tout, tandis que les autres oui. Éventuellement, je ne se sais pas pourquoi, l'interpolation s'est remise à 0 et le son ne sortait que par le haut-parleur le plus près.

**Comment by Normandeau** [comment]
V 3.1.13
«Set vertical limit of cartesian vector to lbap extended radius»
On ne peut pas tester cette nouvelle fonctionnalité avec ControlGRIS 1.3.4, puisque l'axe vertical y est limité à 1.0. On attend donc la prochaine version, qui devrait être 1.3.5 pour tests, et 1.4 pour publication.
Tests avec Max pour le moment?

**Comment by NicolaGiannini** [comment]
Avec Max For Live ça semble fonctionner. J'ai essayé sans et avec attenuation settings.

https://user-images.githubusercontent.com/35705913/189497494-a96039a5-37a3-4bc8-b1a3-8da4ab8df09c.mov

**Comment by Normandeau** [comment]
Ah, enfin _La part des anges_!
