### ISSUE TITLE
Le Message d'alerte de Mismatch n'apparaît pas si on ouvre un projet avec des direct outs qui ne sont pas présentes dans le speaker setup

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#182]
Bonjour à tous,
maintenant le message d'alerte est affiché si on ouvre un speaker setup qui a des direct outs différentes de celles présentes dans le projet. Je pense que il pourrait être pratique aussi le contraire : soit afficher un message d'alerte si on ouvre un projet avec des sorties directes qui ne sont pas présentes dans le speaker setup.
Merci,
Nicola

**Comment by Normandeau** [comment]
Voir mon dernier commentaire dans l'Issue #178 
En fait c'est exactement cela qu'il faut qu'il fasse et pas l'inverse.
Je ferme celle-ci et garde l'autre pour éviter les doublons.
