### ISSUE TITLE
Une fois l'enregistrement terminé, appuyer sur la bouton “Record" fait planter SpatGRIS2 .

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#184]
SpatGRIS211

J’ouvre SpatGRIS2
J'appuie sur le bouton “Init Recording”
Je choisis un nom pour le fichier
J'appuie sur le bouton “Record"
J'appuie sur le bouton “Stop”
J’appuie sur le bouton “Record”
SpatGRIS 2 va en Crash.

**Comment by Normandeau** [comment]
Faut vraiment être un peu tordu pour faire cela!
;-)
Mais je confirme...

**Comment by NicolaGiannini** [comment]
Ahah oui! Totalement d'accord avec toi Robert. Clairement c'est passé par erreur !

Je ne pense pas que ce soit pas du tout important, peut-être même pas à mettre dans le manuel ? Mais je vous laisse décider !

**Comment by belangeo** [comment]
Pas à mettre dans le manuel, c'est un bug (pas très grave mais bug quand même). Il faudrait simplement que le bouton Record soit grisé tant qu'il n'y a pas eu de "Init Recording".

**Comment by Normandeau** [comment]
V212
Le bouton Record n'est plus disponible (grisé) après l'enregistrement. Il faut à nouveau appuyer sur Init recording. Réglé.
