### ISSUE TITLE
Reset pour les crêtes?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#186]
V211
Merci pour l'ajout des crêtes dans les Inputs/Outputs. C'est très utile comme information. Maintenant, le seul moyen de les enlever, est de cliquer dessus individuellement. Sur des gros projets, ça fait beaucoup de clics. Même en changeant de projet, les crêtes du projet précédent restent en place. Je sais qu'on est dans les derniers miles, mais je pose tout de même la question: est-il possible de mettre en place un Reset général des crêtes? Genre: avec un shortcut?

**Comment by belangeo** [comment]
Est-ce que le raccourci Alt-M sert à quelque chose sous MacOS?

**Comment by Normandeau** [comment]
Je viens de tester. Et de regarder la liste des raccourcis clavier dans les préférences. Il n'y pratiquement pas de raccourcis avec Alt (opt) sur le Mac. C'est dans doute le syndrome PC! En tout cas pas de Alt-M à priori.

**Comment by belangeo** [comment]
Excellent! Je l'ai utilisé pour faire le reset des crêtes.

**Comment by Normandeau** [comment]
Parfait, je viens d'ajouter cela dans le manuel. Mais ça va modifier un des menus alors? J'attends de savoir où et une nouvelle version pour faire une copie d'écran.

**Comment by Normandeau** [comment]
V212
Fonction intégrée et décrite dans le manuel.
