### ISSUE TITLE
Jack n'est plus maintenu sous Catalina

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#187]
MacOS 10.15.5
J'ai installé cet OS sur un volume séparé sur mon ordi afin de tester.
Contrairement ce qui est écrit dans SpatGRIS2, celui-ci n'est pas compatible sous Catalina. Les plugiciels doivent être autorisés sous 10.15 et avant que ce soit fait, on reçoit un message comme quoi ils sont incompatibles. Mais une fois l'autorisation effectuée, ControlGRIS fonctionne normalement. 
Donc nos outils fonctionnent sous ce MacOS, mais JackRouter est bloqué par le système. 
SpatGRIS2 s'ouvre normalement, et Jack a l'air de fonctionner aussi (difficile à dire sans audio, mais on ne reçoit pas de message d'erreur). Malheureusement, JackRouter n'est plus «vu» par les séquenceurs. Donc l'audio ne fonctionne plus.
Et nous venons d'apprendre que JackOSX n'est plus maintenu par le GRAME, ni par personne (en fait, depuis plusieurs années). À l'occasion de ces recherches, il semble que même Jack sous Linux soit problématique et que son maintien est très fragile.
C'est donc la fin de l'histoire de nos outils sous cette forme pour les prochains MacOS.
Il nous faut trouver un remplaçant à Jack. J'explore BlackHole pour le moment. À suivre.

**Comment by sletz** [comment]
@Normandeau sur OSX une solution serait de ne plus passer par JackRouter, mais d'utiliser l'API JACK directement dans vos applications.

**Comment by NicolaGiannini** [comment]
Bonjour à tous,
Je vous écris de Catalina. Je confirme que les séquenceurs ne voient pas JackRouter comme carte de son. 

La communication OSC entre SpatGRIS2 et ControlGRIS fonctionne bien, les sources se déplacent  graphiquement dans la visualisation 3D de SpatGRIS2.

**Comment by sletz** [comment]
Je vois dans le source que le code du driver JACK est déjà écrit:  driver https://github.com/GRIS-UdeM/ServerGRIS/tree/master/Source, donc c'est peut être "juste" une affaire d'activer/compiler ce code sur OSX pour accéder à JACK directement sans avoir besoin de JackRouter.

**Comment by belangeo** [comment]
Le problème n'est pas du côté du ServerGRIS, c'est un serveur jack tout ce qu'il y a de plus fonctionnel (en fait, c'est le code côté serveur, quasi inchangé, qui est dans les sources de jack). Le problème, c'est que pratiquement aucune application audio sous MacOS n'offre le support jack, d'où la nécessité d'utiliser JackRouter... Je serais bien curieux de compiler pyo avec le flag --use-jack sur une machine Catalina, ma main au feu que ça fonctionne sans problème!

Cockos offre déjà le support jack dans la version native linux de Reaper... Peut-être qu'ils accepteraient de l'offrir aussi pour MacOS!

**Comment by sletz** [comment]
C'est peut être le moment de pousser tous les projets "open" à effectivement utiliser l'API JACK de manière native.  Au dela du fait qu'à ma connaissance plus personne ne travaille sur JACK et OSX de manière spécifique, la question demeure: avec un système OSX de plus en plus fermé, je n'ai jamais pu savoir si le modèle de passerelle CoreAudio <==> JACK faite par JackRouter était simplement encore possible techniquement.

**Comment by belangeo** [comment]
> C'est peut être le moment de pousser tous les projets "open" à effectivement utiliser l'API JACK de manière native.

Malheureusement, des séquenceurs "open", il n'y en a pas des tonnes... À part Reaper, je ne vois pas qui oserait. Ça n'arrivera jamais dans le cas de Logic et DP.

> avec un système OSX de plus en plus fermé, je n'ai jamais pu savoir si le modèle de passerelle CoreAudio <==> JACK faite par JackRouter était simplement encore possible techniquement.

Que de mauvaises décisions d'Apple depuis quelques années... Je ne pensais pas dire ça un jour, mais je crois qu'il commence à être temps d'envisager de donner sa chance à Windows!

**Comment by ghost** [comment]
Je me permets ce commentaire. J'ai été "évangéliste" Apple dans les années 90, puis devenu usager Gnu/Linux en 98 (pour passer de Max à PureData). J'ai travaillé avec des artistes médiatiques (depuis 89). Ce qui manque, c'est de donner une chance à Linux et au libre pour de l'art numérique, incluant la musique; ce faisant, ça aidera Windows et Apple. Mais si Apple et Microsoft bloquent le chemin, ce sera dommage pour tous. Si Reaper "ose", les autres peuvent suivre, c'est juste une question de marché, et ce sont les usagers qui décident.

**Comment by SamuelBeland** [comment]
> Malheureusement, des séquenceurs "open", il n'y en a pas des tonnes... À part Reaper, je ne vois pas qui oserait. Ça n'arrivera jamais dans le cas de Logic et DP.

Effectivement, ça nous embarrerait dans un ou deux DAW si nous comptons sur une intégration JACK à même l'hôte.

> Que de mauvaises décisions d'Apple depuis quelques années... Je ne pensais pas dire ça un jour, mais je crois qu'il commence à être temps d'envisager de donner sa chance à Windows!

Nous ne sommes pas seuls: il semble y avoir une véritable exode des projets open source sous MacOS depuis les dernières années. Le pire, c'est que cela semble faire l'affaire d'Apple...

Mis à part mon éditorial politique, il y a un détail technique qui me chicote. Peut-être @belangeo pourras-tu m'éclairer là-dessus.

Ma compréhension actuelle est la suivante: JackRouter est assez unique en terme d'interface virtuelle, puisque JACK évalue l'ensemble d'un block audio dans un même callback (celui de l'interface de sortie auquel le serveur JACK est rattaché). Le calcul d'un block peut donc se faire dans un seul call, depuis l'interface jusqu'au DAW, en passant par SpatGRIS2, ce qui permet de n'ajouter aucune latence additionnelle.

Les autres solutions (SoundFlower, BlackHole), utilisent leur propre clock. Aurons-nous donc à gérer deux callbacks indépendants? Mis à part les problèmes évidents qui peuvent émerger de la coopération entre deux interfaces dont les horloges ne sont pas synchronisées, je ne sais pas si c'est possible à faire sans introduire de latence additionnelle.

Je sais que BlackHole a comme objectif de pouvoir être dirigé directement vers une interface et de synchroniser sa clock, mais ce n'est malheureusement pas encore possible.

**Comment by sletz** [comment]
**puisque JACK évalue l'ensemble d'un block audio dans un même callback** c'est effectivement le cas. Le serveur évalue le graphe de toutes les applications de manière synchrone,  dans un même callback, avec parallélisation dynamique. Voir : https://www.semanticscholar.org/paper/Jack-audio-Server-for-Multi-Processor-Machines-Letz-Fober/db54aa3e5061bda6523ee3244f9d5c3fd0cd91d9, https://hal.archives-ouvertes.fr/hal-02158993, https://hal.archives-ouvertes.fr/hal-02158922
A ma connaissance, on a pas fait mieux depuis...

**Comment by SamuelBeland** [comment]
Merci pour les liens @sletz, ça m'éclaire beaucoup.

> A ma connaissance, on a pas fait mieux depuis...

Effectivement... Si l'on n'arrive pas sauver JackRouter ou bien à l'émuler, il ne nous resterait que des solutions asynchrones.

Comme je le disais précédemment, l'auteur de BlackHole vise à implémenter prochainement une synchronisation des callbacks sur l'interface de sortie. Ça pourrait devenir notre porte de sortie sur MacOS.

Si nous devons toutefois aller vers une approche asynchrone, à quelle genre de latence additionnelle pourrait-on s'attendre ? J'imagine que nous aurons, au minimum, à doubler le buffer (probablement un peu plus). 

Et, est-ce simplement raisonnable de s'attendre à un stream audio stable dans ce genre de configuration ?

**Comment by sletz** [comment]
Si toutes les callback audio sont cadencées par la même clock, on peut espérer un système qui fonctionne, avec une latence fixe (1 buffer? 2 buffers ? à voir). Une release binaire vient d'apparaitre la 1° depuis la reprise de la maintenance the JACK par  Filipe Coelho à ma connaissance : https://github.com/jackaudio/jackaudio.github.com/releases/tag/v1.9.14, sans JackRouter donc, mais avec les outils pour developer si j'ai bien compris. Mais pas de description précise de quel fichier est installé ou...

**Comment by Normandeau** [comment]
SpatGRIS2 V214 avec BlackHole 0.2.7 avec Catalina 10.15.7.
Six mois plus tard, on est en présence d'un système qui semble bien fonctionner. Merci à Samuel et Devin pour cela. Il y aura sans doute des surprises, mais au moins on peut commencer à tester en situation réelle. Voilà qui termine bien l'année 2020.

**Comment by belangeo** [comment]
Nice job Samuel and Devin! Joyeuses fêtes tout le monde!

**Comment by NicolaGiannini** [comment]
C'est une excellente nouvelle ! Merci Samuel et Devin! Et bonnes fêtes à tout le monde !

**Comment by sletz** [comment]
Cet été j'avais réfléchi à une solution technique pour remettre en route la solution JackRouter, voir: https://github.com/jackaudio/jack-router/blob/main/macOS/docs/JackRouter-AudioServerPlugin.md
en particulier en discutant avec Kyle Neideck qui développe un projet similaire: https://github.com/kyleneideck/BackgroundMusic.
C'est donc peut être possible, mais techniquement compliqué, et je nai pas pu valider les hypothèses, et donc à part trouver un développeur très compétent sur ces aspects bas-niveau, la solution avec BlackHole est la plus raisonnable. Bonnes fêtes à tout le monde !

**Comment by Normandeau** [comment]
Bonjour Stéphane,

Merci du suivi.
Pour le moment, l'exercice de notre côté a eu du bon, car il a permis d'extraire Jack de SpatGRIS2, et de laisser la liberté aux utilisateurs de choisir leurs dispositifs d'entrée et de sortie de celui-ci.
Nous fournirrons Blackhole car son développeur, Devin Roth, fait maintenant partie du GRIS, et il a développé une version notorisée à 128 canaux pour nous.
Testé hier pour la première fois, tout roule.
Ça finit bien l'année.
Reste à faire du développement maintenant!

Joyeuses fêtes.
