### ISSUE TITLE
Deux problèmes graphiques

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#189]
V212
Lorsqu'on a un nombre élevé d'entrées (comme ici: 108), on ne peut voir que la moitié de la dernière, à droite de la fenêtre. Cela ne se passe que lorsque la flèche de défilement horizontale est présente:

![Input de droite à moitié visible](https://user-images.githubusercontent.com/8959779/87229897-0f662400-c37a-11ea-8c9e-51f43e90702a.jpg)

Deuxième problème, le nom du speaker setup est mal placé dans la fenêtre et il est trop gros, et sa couleur n'est pas la bonne. Il est écrit en blanc sur fond gris, or il arrive parfois que cela se confonde avec des couleurs pastels choisies pour certaines entrées (comme ici, pour des réverbs). Je propose de le mettre en noir et à la verticale sur le côté gauche.

![Nom du speaker setup à modifier](https://user-images.githubusercontent.com/8959779/87230019-d4b0bb80-c37a-11ea-9282-7ebcf037931e.jpg)

**Comment by NicolaGiannini** [comment]
Bonjour Robert,
j’ai essayé avec 108, ou aussi 256 entrées, et j’arrive toujours à voir la dernière entrée entièrement. La flèche de défilement est presente. Peut-être ce problème est-il lié à une résolution particulière ?
Voir la vidéo : https://www.dropbox.com/s/6xfa4ey9a5zniyj/derni%C3%A8re.mov?dl=0

En ce qui concerne le nom du speaker setup, c'est une très bonne idée! Je n'ai qu'un seul doute sur le noir, même les numéros des hp sont en noir. Mais de toute façon, ils occupent toujours une position centrale dans la fenêtre.

**Comment by Normandeau** [comment]
Précision au sujet de la dernière entrée partiellement cachée. En fait, c'est le curseur de défilement vertical qui prend la moitié de la place de la dernière entrée lorsqu'il apparaît. Si l'espace vertical de SpatGRIS2 est complet, le curseur n'apparaît pas et alors on voit la dernière entrée au complet. Il manque un espace vide à droite des entrées pour laisser de la place au curseur vertical.
Pour ce qui est du noir, peut-être que ce n'est pas une bonne idée. On peut toujours tester en blanc.

**Comment by Normandeau** [comment]
V219
Réglé.
