### ISSUE TITLE
Comparaison de CPU entre Jack et Blackhole

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#192]
V213
Première session avec Blackhole.
Joué trois pièces de suite (15', 16' et 10') sans aucun problème de synchronisation.
C'est vraiment bien de ne pas avoir à se préoccuper du nombre de pistes. On passe d'une session à l'autre, et ça joue. 
Pas besoin d'activer et de désactiver Jack entre les sessions.
Pas besoin d'ouvrir les logiciels dans l'ordre non plus.
J'ai fait des tests de CPU, voir le pdf joint.

Pour votre info.
[CPU Comparaison.pdf](https://github.com/GRIS-UdeM/ServerGRIS/files/5556444/CPU.Comparaison.pdf)

**Comment by SamuelBeland** [comment]
C'est vraiment intéressant comme tableau de comparaison! Je ne m'attendais honnêtement pas à d'aussi grandes différences avec autant d'alternance entre les augmentations et les diminutions de performance.

Est-ce que les trois pièces utilisent le mode VBAP?

**Comment by Normandeau** [comment]
Oui, essentiellement le mode VBAP pour le moment.

**Comment by NicolaGiannini** [comment]
Bonjour Robert,
Je voudrais essayer de répéter les tests indiqués dans le PDF. 
"Somme globale selon Menu Meter" se réfère à ce logiciel ? https://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/

As-tu fait les tests pendant que la session était en play ?
Merci !
Nicola

**Comment by Normandeau** [comment]
As-tu fait les tests pendant que la session était en play ?

Bien évidemment, car sinon, il y aurait peu de CPU en usage!

**Comment by NicolaGiannini** [comment]
Voici ma comparaison. 

Pour "Somme globale selon Menu Meter" j'ai utilisé l'affichage "the sum of all cores" dans MenuMeters.
[ComparaisonCpu.pdf](https://github.com/GRIS-UdeM/ServerGRIS/files/5593494/ComparaisonCpu.pdf)

**Comment by devinroth** [comment]
I think we can reduce the CPU usage even further with some of the synchronization improvements I’ve been working on with BlackHole.

It would also be interesting to see a breakdown of where the CPU is higher or lower by monitoring the CPU% by process.

Devin

**Comment by SamuelBeland** [comment]
> I think we can reduce the CPU usage even further with some of the synchronization improvements I’ve been working on with BlackHole.

Is there a specific commit that we should try or is it ok to go directly for [v0.3.0](https://github.com/ExistentialAudio/BlackHole/tree/v0.3.0) ?

**Comment by devinroth** [comment]
V0.3.0 is the one. Although this hasn’t been released yet. So be on the lookout for bugs.

Devin

**Comment by Normandeau** [comment]
Nouveau tableau de comparaison, cette fois-ci avec les 34 haut-parleurs du B187. Sous tous les aspects, il est clair ici que le CPU et SpatGRIS2 sont plus sollicités (et même DP parfois...) dans la version Blackhole que dans la version Jack sur un dispositif plus important. J'ai aussi ajouté la comparaison avec le même logiciel mais dans les deux dispositifs. Comme on peut s'y attendre ici, le 187 est plus exigeant que Icosa. Donc on peut dire qu'avec Blackhole et SpatGRIS213, on ne fait pas de gain de productivité, mais on a une version qui fonctionne sous Catalina.
Est-ce surprenant?
[CPU Comparaison Robert.pdf](https://github.com/GRIS-UdeM/ServerGRIS/files/5604647/CPU.Comparaison.Robert.pdf)

**Comment by devinroth** [comment]
How are you testing the Jack version?

It’s good we have it working on Catalina. We can improve it from here.

**Comment by SamuelBeland** [comment]
It's quite interesting to look at the difference between `SpatGRIS2 selon Moniteur` and `SpatGRIS 2 selon lui`. JUCE only reports the amount of CPU time used by the audio callback functions, while the monitor reports everything done by SpatGRIS (audio, OpenGL, business logic, etc.). There seems to be a steady +70% of CPU time spend on _something else_ than audio processing - which really shouldn't be the case. I'm going to look into this.

I also believe there is still some room for optimization in the code's audio processing routines.

But first, let's try the same thing with BlackHole 0.3

*I have to say I'm a bit confused by all those values ranging from 100% to 300% in the monitor. Are they just adding cores together?
