### ISSUE TITLE
Icône abimée

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#193]
V213
Un ancien problème vient de ressurgir. Voir issue #153 
Voici la solution d'Olivier: «C'est réglé. Juce produit un icône de mauvaise qualité. Au moment de faire un release, je le remplace par un de haute résolution que je viens de créer.»
L'icône a l'air de ceci, mais juste sur le bureau. Pas dans le dock, ni dans la fenêtre d'info:
![Capture d’écran, le 2020-11-18 à 10 35 58](https://user-images.githubusercontent.com/8959779/99552119-a4150a00-298a-11eb-827e-8e9243308449.jpg)

**Comment by belangeo** [comment]
Allo,

Peut-être une taille manquante dans ServerGRIS_icon_doc.icns
<https://github.com/GRIS-UdeM/ServerGRIS/blob/master/Resources/ServerGRIS_icon_doc.icns>
 ...

Olivier

**Comment by NicolaGiannini** [comment]
V214, il semble réglé.

**Comment by Normandeau** [comment]
En effet, réglé.
