### ISSUE TITLE
Pas de fonctionnement sous Catalina 10.15.7

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#196]
V213
- Premier commentaire: je pense que les nouvelles versions devraient être nommées SpatGRIS3. La mise au rancart de Jack, après toutes ces années, et la possibilité d'utiliser Blackhole est un changement majeur. Afin d'éviter toute confusion, je privilégierais l'appellation SpatGRIS3.
- Deuxième constat: ça fonctionne sous Catalina. Après avoir passé près de trois heures à tout configurer sous ce dernier MacOS (10.15.7), une session test DP 10.13 avec SpatGRIS2 213 et GRIS Blackhole 128ch, cela se comporte normalement en OSC et en audio.
- Le Speaker Setup Edition crashe aussi.
- Je n'ai pas fait de tests intensifs, car tous les plugiciels ne sont pas installés sous Catalina. La clé iLok ne peut pas être partagée entre deux MacOS. Donc à suivre.

**Comment by SamuelBeland** [comment]
* Comme JUCE ne permet malheureusement pas l'utilisation de numéros de version alphas ou betas (du style "3.a.1"), je vais est-ce que ça va à l'équipe si je continue d'incrémenter le numéro de version actuel (2.1.3) jusqu'au release de 3.0 ?

**Comment by Normandeau** [comment]
Oui pas de soucis.
Je pensais surtout à la version officielle.

**Comment by Normandeau** [comment]
V214 sous MacOS 10.15.7
Malheureusement la nouvelle version de Blackhole (0.2.7) livrée avec SpatGRIS 2.1.4. ne fonctionne plus sous Catalina. J'ai eu ces deux messages. J'ai essayé de la remplacer par la première version 128 ch que Samuel avait fait, et c'est la même chose. Entre la dernière fois et aujourd'hui, j'ai fait une mise à jour de sécurité. car 10.15. 7 est la dernière version de Catalina.
Après l'installation, j'ai essayé la commande dans le Terminal (courriel du 7 juin):
Copy BlackHole.driver and paste in Library/Audio/Plug-Ins/HAL/
Restart CoreAudio with Terminal command: sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod

J'obtiens ceci (un par tentative):
service spawned with pid: 809
service spawned with pid: 1307
service spawned with pid: 1777
Puis ennsuite les messages du Finder.

C'est dommage car j'ai passé la journée à configurer Catalina afin de passer entièrement dessus et de tester en profondeur, au jour le jour, notre dispositif. Back to square one...
Nos autres plugiciels, SpatGRIS1 par exemple, ne fonctionnent pas non plus.

![Blackhole Développeur non-identifié](https://user-images.githubusercontent.com/8959779/102941650-3f653780-4481-11eb-91e5-fee50d147800.png)

![Blackhole Impossible d'ouvrir](https://user-images.githubusercontent.com/8959779/102941673-4c822680-4481-11eb-877b-2d9e205edd41.png)

**Comment by devinroth** [comment]
This is a notarization/code signing issue. What settings do you have in System Preferences->Security and Privacy->General? This is a screenshot of my settings.

<img width="780" alt="Screen Shot 2020-12-22 at 10 56 34 PM" src="https://user-images.githubusercontent.com/13010961/102968578-f5904780-44a8-11eb-8ce6-c3e6476f1350.png">

You can change them to "Anywhere" by running `sudo spctl --master-disable` in Terminal.

@SamuelBeland is the BlackHole128ch installer notarized? If not I can do it so this isn't an issue in the future.

**Comment by devinroth** [comment]
Does this work? It's the 16ch version. If so I will build and notarize a 128ch version for you.
[BlackHole16ch.v0.2.7.pkg.zip](https://github.com/GRIS-UdeM/ServerGRIS/files/5733769/BlackHole16ch.v0.2.7.pkg.zip)

**Comment by SamuelBeland** [comment]
@devinroth BlackHole 128ch was not notarized. I haven't tested it yet but as you suggested, the notarized version should work just fine.

**Comment by Normandeau** [comment]
BlackHole16ch
Thanks Devin, Yes it works. Waiting for a 128 ch version.
After the Terminal operation.
But SpatGRIS2 is not working anymore.
See below.

![Capture d’écran, le 2020-12-23 à 11 52 39](https://user-images.githubusercontent.com/8959779/103020346-3bcfc000-4516-11eb-9782-b2031ed404cd.png)

**Comment by Normandeau** [comment]
No audio anymore in SpatGRIS 213 and 214 under Catalina 10.5.7
After solving the BlackHole problem with a new 16ch version, there is no audio anymore in SpatGRIS. The OSC is fine though.
Everything works fine under Mojave 10.14.6 (128 channels)

**Comment by devinroth** [comment]
@Normandeau check microphone permissions. System Preferences->Security and Privacy->Privacy->Microphone. If SpatGRIS is not listed audio won't work.

**Comment by Normandeau** [comment]
Thanks again Devin. Success.
So many things to remember! The instructions to make Catalina working will be longer than the manual itself!
Waiting fotr the 126 channel versionnow, to start to compose under Catalina! What a step, 16 months after the launch of that MacOS (already being replaced by Big Sur...).

**Comment by devinroth** [comment]
Working on it now. 

FYI I now have the new Mac mini with the M1 chip. I'm happy to run tests on that too.

**Comment by devinroth** [comment]
Here you go. Happy testing. 

[BlackHole128ch.v0.2.7.pkg.zip](https://github.com/GRIS-UdeM/ServerGRIS/files/5736710/BlackHole128ch.v0.2.7.pkg.zip)

**Comment by Normandeau** [comment]
This is my best Christmas gift!!! First time I can run a project with 116 audio channels, all spatialized with ControlGRSI and SpatGRIS2 under Catalina! WoW!
Thanks and Happy holidays!

**Comment by Normandeau** [comment]
Samuel,
Peux-tu remplacer la version actuelle de BlackHole, celle qui est disponible avec SpatGRIS 2 214, avec celle-ci? Merci.

**Comment by Normandeau** [comment]
Yup! Next step, isn't it?
And I don't remember: any plan to put BlackHole on Windows?
SpatGRIS2 is ready (we think...)

**Comment by devinroth** [comment]
Yes Windows. I will start work on it in the new year.

Devin

**Comment by delmenhorst** [comment]
Hai,
I try do run it on Catalina 10.15.7. I installed Blackhole 128ch but
In my case he is still looking for jack and crashes.


```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
  Referenced from: /Volumes/VOLUME/*/SpatGRIS.app/Contents/MacOS/SpatGRIS
  Reason: image not found
```

**Comment by delmenhorst** [comment]
Now It runs. I had to install SpatGRIS 2.1.2 to get the Jack Framework.

**Comment by Normandeau** [comment]
Please download the latest version 2.1.5. The link to Jack Libraries has been removed.
