### ISSUE TITLE
Proposition : indiquer quand la CPU dépasse le 100%

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#198]
V213
Ce n'est pas du tout une priorité, et je sais qu'on a bien d'autres priorités. Mais je lance l'idée d'ajouter une indication graphique lorsque la CPU dépasse le 100%. Cette indication pourrait être similaire à celle du dépassement du zéro dans les vu-meters.

**Comment by Normandeau** [comment]
V216
Il faudra voir comment la nouvelle version se comporte dans la vraie vie, mais l'augmentation de performance dans cette version rend peut-être caduque cette information?

**Comment by Normandeau** [comment]
Par contre, si c'est comme au hockey et que tout le monde s'attend à ce que tu donnes ton 110%, peut-être un signal clair, comme la case qui s'illumine en rouge lorsque la valeur maximale est atteinte, comme avec Jack, serait une bonne idée.

**Comment by SamuelBeland** [comment]
Je pense que c'est encore une bonne idée de donner une indication claire lorsque ça arrive. Peut-être même encore plus maintenant que la fluctuation du CPU a augmentée.

**Comment by Normandeau** [comment]
V219
Testé ma plus grosse session: 116 canaux audio, 58 EQ3, 56 ControlGRIS avec automation, 4 AltiVerb, 4 GRMTools, 12 Elixir, tout cela avec de l'automation. Résultat des cours: SpatGRIS: 17%.
Bon j'avoue la même session sur le CUBE de Virginia Tech (126 hp) ne tient pas la route. Mais je m'y attendais, pas besoin de flag pour cela! Est-ce vous avez déjà tâté le 100%?

**Comment by MelanieFrisoli** [comment]
Oui plusieurs fois en mode binaural. Pas en mode dôme ni cube par contre!

**Comment by NicolaGiannini** [comment]
Je n'ai toujours pas atteint 100%.

**Comment by SamuelBeland** [comment]
Je pense que dans tous les cas, c'est une vraiment bonne idée d'avoir un signal clair lorsque le CPU atteint 100%.

**Comment by Normandeau** [comment]
V2110
Quelqu'un a réussi à obtenir 100%

**Comment by NicolaGiannini** [comment]
Pas moi !

**Comment by SamuelBeland** [comment]
Voici à quoi ça ressemble quand on dépasse 100% : 

https://user-images.githubusercontent.com/39448259/122468916-51d0b180-cf8a-11eb-9901-d21f948ebe48.mp4

**Comment by Normandeau** [comment]
Très joli!
En espérant que cela n'arrive pas trop souvent!

**Comment by MelanieFrisoli** [comment]
V2112
J'ai réussi à avoir 100% momentanément mais je n'ai pas réussi à le reproduire. La case CPU était entourée de rouge. Discret mais efficace. On le voit tout de suite.

**Comment by Normandeau** [comment]
V2113
Mis dans le manuel
