### ISSUE TITLE
En mode Binaural, les sources ne sont pas reproduites après une certaine valeur d'élévation.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#199]
V213
Testé avec Logic et Live.

En mode Binaural, les sources ne sont pas reproduites après une certaine valeur d'élévation.

Si avec ControlGRIS j’augmente l’élévation des sources, une fois que les sources ont dépassé une certaine valeur (autour de 45 dans ControlGRIS en mode DOME et autour de 0,45 en mode CUBE), les sources ne sont pas reproduites au niveau sonore. 

Voir la vidéo (sans audio). 
https://www.dropbox.com/s/al77vlhq267a8ri/Binaural-Elevation213.mov?dl=0
On peut voir que les sources sont affichées (Source Activity est actif) mais que les VU-Meters des Outputs s'arrêtent lorsque les sources dépassent une certaine valeur d'élévation.

**Comment by NicolaGiannini** [comment]
V214
Il semble réglé.

**Comment by Normandeau** [comment]
En effet, c'est réglé.
