### ISSUE TITLE
Passer de mode Binaural et Stereo à Cube donne lieu à un positionnement non correct des haut-parleurs

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#200]
V213
Passer de mode Binaural et Stereo à Cube donne lieu à un positionnement non correct des haut-parleurs.
Voir la vidéo : 

https://www.dropbox.com/s/4gimvgy8jkm17gi/CubeBin.mov?dl=0

Si je me ne trompe pas, il s’agit du même type de positionnement qu’on obtenait lorsqu’on passait de DOME at CUBE dans d’anciennes versions de ServerGRIS, voir https://github.com/GRIS-UdeM/ServerGRIS/issues/169#issuecomment-578413738

**Comment by NicolaGiannini** [comment]
V214
Il semble réglé.

**Comment by Normandeau** [comment]
En effet, réglé
