### ISSUE TITLE
Le mode Binaural ne prend pas en compte la distance

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#202]
V214
Ce n’est pas exactement un bug, mais je signale que le mode Binaural ne prend pas en compte la distance. Alors si on travaille en mode Cube et on passe en mode Binaural, les sources restent sur la surface du dôme. J’imagine que cela est dû au fait que le mode Binaural est basé sur l’algorithme Vbap.
Peut-être, on pourrait le mentionner dans une version prochaine du manuel. 
(J'ai indiqué la version actuelle de SpatGRIS, mais cela se produit aussi avec la 212.)

**Comment by Normandeau** [comment]
Le mode binaural reste à être raffiné. Effectivement, actuellement c'est une version VBAP qui est ramené à deux sources en mode binaural. Il faudrait éventuellement avoir un mode binaural authentique pour le CUBE.
