### ISSUE TITLE
Les coordonnées des deux outils ne sont pas cohérentes en mode CUBE

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#203]
ControlGRIS 118 et SpatGRIS2 216. Mode CUBE. MacOS 10.15.7 (Catalina)
Les coordonnées des deux outils ne sont pas cohérentes.
Dispositif représenté ci: une source mono sur un CUBE.

1) X et Y sont inversés
X correspond à l'axe gauche-droite dans ControlGRIS et va de -1 (gauche) à +1 (droite).
X correspond à l'axe avant-arrière dans SpatGRIS2 et va de -2 (avant) à + 2 (arrière).
Y correspond à l'axe avant-arrière dans ControlGRIS et va de + 1 (avant) à -1 (arrière).
Y correspond à l'axe gauche-droite dans SpatGRIS2 et va de -2 (gauche) à +2 (droite).
On comprend mieux quand on voit la position de la source  sur l'image 2D. On voit que la source se positionne au bon endroit mais avec un système de coordonnées X-Y inversé:

![XYZ en mode CUBE en 2D](https://user-images.githubusercontent.com/8959779/106064880-77871800-60c8-11eb-8716-b89ae1a2748d.jpg)

2) Limite du petit carré
Source 1 et Hp 15 positionnés à peu près au même endroit:
- ControlGRIS Source 1: Coordonnées X, Y, Z obtenues: -0.61, 0.0, 0.33
- HP 15: Coordonnées X, Y, Z obtenues: 0, -1, 0.5

![XYZ en mode CUBE](https://user-images.githubusercontent.com/8959779/106063415-237b3400-60c6-11eb-9d83-2b8dba6a0529.jpg)

3) Grand carré
Si on place maintenant X à -1.0 dans ControlGRIS, on arrive à la limite du grand carré dans SpatGRIS2, mais si on place le Y du HP 15 au maximum, soit -2, il se place à l'extérieur du grand carré et il est inatteignable par la source. On comprend mieux quand on regarde d'en haut:

![XYZ en mode CUBE maximum](https://user-images.githubusercontent.com/8959779/106065401-42c79080-60c9-11eb-8013-c5d8c782c7ef.jpg)

4) Z erroné sauf à 1
Z n'est pas cohérent entre ControlGRIS et SpatGRIS2. Si on place le HP 15 à 0.5 pour Z, il se situe dans le carré du milieu de la grille du CUBE. Si on place à 0.5 le Z de la source, elle est dans la partie supérieure du 4e carré de la grille:

![Z erroné](https://user-images.githubusercontent.com/8959779/106065993-14968080-60ca-11eb-8930-823196e599c5.jpg)

Par contre, quand on ajuste les deux à la valeur maximale de 1, la source et le HP se positionne au top du CUBE:

![Z ok à 1](https://user-images.githubusercontent.com/8959779/106066290-92f32280-60ca-11eb-99fa-399964541366.jpg)

Je crois qu'il y a de la place à l'amélioration.

**Comment by Normandeau** [comment]
Les coordonnées des deux outils ne sont pas cohérentes en mode CUBE.
J'ai refait les images et les textes de cette situation. Il me semble que c'est plus clair maintenant.

**Comment by NicolaGiannini** [comment]
J'ai testé les quatre points que Robert a soulignés et je les confirme.

**Comment by Normandeau** [comment]
V217

1) X et Y inversés: Ok
2) Correspondance des valeurs de l'axe Z entre ControlGRIS et SpatGRIS2: Ok

3) Coordonnées de X et Y
• Petit carré:
- ControlGRIS: Coin supérieur droit: 0.6, - 0.6: Y devrait être positif. 
- SpatGRIS 2: Coin supérieur droit: 1.0, 1.0: Ok

• Grand carré: 
- ControlGRIS: Coin supérieur droit: 1.0, -1.0: Y devrait être positif. 
- SpatGRIS 2: Coin supérieur droit: 1.66, 1.66: Il existe toujours une échelle maximale qui va jusqu'à 2, position inatteignable par ControlGRIS.

Petit carré et grand carré correspondent sur le plan graphique du plugiciel et du logiciel.

**Comment by Normandeau** [comment]
V218
3) Coordonnées de X et Y
• Petit carré:
- ControlGRIS: Coin supérieur droit: 0.6, - 0.6: Y devrait être **positif**. 
- SpatGRIS 2: Coin supérieur droit: 1.0, 1.0: Ok

• Grand carré: 
- ControlGRIS: Coin supérieur droit: 1.0, -1.0: Y devrait être **positif**. 
- SpatGRIS 2: Coin supérieur droit: 1.0, 1.0: on peut plus mettre de valeurs supérieures à 1, ce qui correspond au petit carré.

**Comment by Normandeau** [comment]
V219
Coordonnées de X et Y
Il y a deux carrés dans ControlGRIS et trois carrés dans SpatGRIS. Le troisième carré représentant le lointain dans ce dernier. Il faudrait déjà unifier cela.

Carré no 3 dans SpatGRIS (frontière ultime)
Dans SpatGRIS, on ne peut pas mettre de haut-parleur à cet endroit. Pour quoi ce changement? Avant on pouvait mettre 2.0 comme valeur.
Dans ControlGRIS cependant, ces valeurs sont 1.0 (carré no 2):
- ControlGRIS: Coin supérieur droit: 1.0, - 1,0: Y devrait être positif.

![Capture d’écran, le 2021-05-23 à 17 33 46](https://user-images.githubusercontent.com/8959779/119277372-38d41b00-bbed-11eb-8aed-b87bb3fd40a4.jpg)


Carré no 2 dans SpatGRIS
Dans SpatGRIS, la valeur la plus élevée qu'on peut mettre est 1.00. Cela correspond à la frontière à partir de laquelle le son est atténué et filtré (carré no 2).
- SpatGRIS 2: Coin supérieur droit: 1.0, 1.0: Ok

Dans ControlGRIS cependant, ces valeurs sont 0.6 (carré no 1):
 - ControlGRIS: Coin supérieur droit: 0.6, - 0.6: Y devrait être positif.

![X, Y, Lointain](https://user-images.githubusercontent.com/8959779/119277061-7c2d8a00-bbeb-11eb-8c61-92e706702123.jpg)

Carré no 1 dans SpatGRIS
 - SpatGRIS 2: Coin supérieur droit: 0.5, 0.5: Ok

Ce carré n'existe pas dans ControlGRIS, les coordonnées équivalentes sont:
 - ControlGRIS: Coin supérieur droit: 0.3, - 0.3: Y devrait être positif.

![Capture d’écran, le 2021-05-23 à 17 28 23](https://user-images.githubusercontent.com/8959779/119277376-44bfdd00-bbed-11eb-9bdd-51efb74f39a2.jpg)

**Comment by Normandeau** [comment]
CUBE
Après avoir écrit dans #253 que la valeur maximale qu'on peut entrer dans le paramètre Distance est 1.73, je me rends compte que cela correspond également dans X et Y à 1.73 (si on est à 90˚ ou 180˚), alors que la valeur la plus grande qu'on peut entrer directement dans ces text box est de 1.00!
Cette valeur de 1,73 correspond en fait au plus grand rayon disponible dans CUBE, soit celui du grand cercle.
Question: pourquoi n'est-il pas possible d'entrer directement cette valeur dans les text box de X et de Y?

![Distance maximale à 1 73](https://user-images.githubusercontent.com/8959779/119537520-1e6a8080-bd58-11eb-9b5c-8ff8d3f21fc6.jpg)

**Comment by Normandeau** [comment]
V2112
Les corrections ont été effectuées. Les valeurs maximales qu'on peut entrer directement dans X et Y sont 1.67. Cela correspond à une distance de 2.56. Pour le CUBE, il est vraiment préférable d'entre X, Y et Z. Jouer avec Azimuth et Distance est vraiment gossant... À régler éventuellement. Dans DOME c'est beaucoup plus facile.

**Comment by MelanieFrisoli** [comment]
V2112 - Je confirme

**Comment by Normandeau** [comment]
V2113
Mis une explication et une suggestion dans le manuel
