### ISSUE TITLE
Plus de flexibilité dans la représentation graphique des outputs

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#204]
V215
Actuellement, l'ordre de représentation graphique des VU-mètres des Outputs est fait de gauche à droite en suivant l’ordre des ID. Et on ne peut pas changer cela. Or ça mène à des situations parfois contradictoires par rapport au dispositif des hp eux-mêmes. On pourrait s'attendre par exemple à une disposition gauche-droite correspondant à celle des hp. Or ce n'est pas le cas.
Dans l'exemple ci-dessous, je reprends le dispositif de mon studio Icosa. Les huit premiers hp (ID 1 à 8), correspondant à une octophonie, partent à droite et suivent le sens des aiguilles d'une montre (les nos de hp sont un peu étranges dû à une configuration de branchement correspondant à quatre dispositif 5.1. Mais cela a pas d'importance ici).
On se retrouve donc avec ces 8 hp à gauche des Outputs, alors qu'en fait ils sont distribués également à droite et à gauche par rapport à ligne du centre:

![Capture d’écran, le 2021-01-05 à 19 32 51](https://user-images.githubusercontent.com/8959779/103714853-110d4f00-4f8d-11eb-8a9a-756091b31f3e.jpg)

Ce qui serait bien c'est de pouvoir les déplacer dans la fenêtre Speaker Setup Edition pour que leur VU mètres correspondent à la disposition des hp.
D'ailleurs question corollaire: ça sert à quoi d'avoir des ID? Sauf à nous dire que c'est dans cet ordre-là que les hp ont été créés, ils ne nous donnent aucune information particulière non? Est-ce obligatoire sur le plan informatique?

**Comment by SamuelBeland** [comment]
Les ID ne servent effectivement pas à grand chose pour l'utilisateur.

Je suis d'accord que ça serait bien de pouvoir ordonner soi-même les HP. J'imagine que si c'est possible de déplacer les HP dans le speaker setup (soit avec un mouse drag ou avec des boutons "move up / down"), on ferait mieux de désactiver les features de tri dans cette fenêtre pour empêcher de perdre son ordre custom ?

Aussi, serait-il envisageable d'ordonner systématiquement les HP par leur # d'output ?

**Comment by NicolaGiannini** [comment]
Je pense aussi qu'il serait utile de pouvoir déplacer les HP dans la fenêtre Speaker Setup Edition. 
(Opinion personnelle : je préfère le drag and drop.) 
Les hp pourraient être placés par leur # d'output de façon automatique, lors notamment de l'ajout d'un HP.

Samuel : 

> on ferait mieux de désactiver les features de tri dans cette fenêtre.


Tu te réfères à la visualisation de la triangulation en mode DOME ?

**Comment by Normandeau** [comment]
V217
Le fait de pouvoir déplacer les hp dans la fenêtre d'édition des Speaker Setup est vraiment bien. Il faudra bien spécifier dans le manuel que cela n'apparaît qu'après avoir Computer la chose.

**Comment by Normandeau** [comment]
M2113
En fait, cela se fait automatiquement maintenant. Détaillé dans le manuel.
