### ISSUE TITLE
Interpolation: vraiment nécessaire?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#205]
V215
On se posait la question de savoir si le facteur d"interpolation était encore vraiment nécessaire. Personnellement, ça fait au moins 6 mois qu'il est à 0 sur tous mes projets. Pourriez-vous tester cela de manière soutenue afin de vérifier s"il y a encore des situations où c'est nécessaire?
Si ce n'est pas le cas, on pourrait soit le retirer, ou mettre un interrupteur On/Off afin de sauver du CPU.

**Comment by belangeo** [comment]
Quand le facteur d'interpolation est à 0, l'interpolation est linéaire sur la durée d'un buffer size, au dessus de 0, un filtre passe-bas de premier ordre est appliqué (plus coûteux). N'oubliez pas de tester les « edge cases » avant de retirer le filtre passe-bas (ex.: 
sons graves - mouvements rapides) !

**Comment by NicolaGiannini** [comment]
V215
Personnellement je n'ai jamais utilisé l'interpolation dans des situations réelles (concerts ou travail en studio), mais maintenant je viens de tester de « edge cases » avec mon casque. 
J'ai testé en mode Binaural STEREO, DOME et CUBE (pour ces derniers j'ai testé le passage entre hp1 et hp2, soit gauche et droite). 

Dans le cas d'une rotation très rapide d'une sinusoïde grave avec une interpolation nulle, des clics peuvent être entendus en mode STEREO. Je n'arrive pas à générer des clics dans les autres modes. En augmentant la valeur de l'interpolation, ces clics peuvent disparaitre.

Si on diminue le Buffer Size de SpatGRIS2, il est possible d'entendre les clics également dans les autres modes. Je pense que c'est un comportement normal. En augmentant l'interpolation, c'est possible d'éliminer ces clics introduits par la diminution du Buffer Size.

Il y a certains sons, très chargés sur les graves, qui peuvent donner toujours des clics lors de rotations très vites (voir l’issue https://github.com/GRIS-UdeM/ServerGRIS/issues/180). Personnellement j'ai toujours réglé ça en changeant le mouvement et en supprimant un peu de graves dans les versions stéréo.

Mon point de vue : je n'utiliserais pas l'interpolation avec les mode DOME et CUBE. Si j'aurais disponible une interpolation, je l'utiliserais pour voir si elle pourrait régler des éventuelles problèmes de clics en mode STEREO.

**Comment by belangeo** [comment]
Juste pour être certain que tout le monde est sur la même longueur d'onde, vous utilisez toujours une interpolation! 

- À 0, c'est une interpolation linéaire:

`y = last_x + step`

`step` étant `(x - last_x) / buffer_size`

Notez que le facteur d'interpolation n'est justement pas utilisé (il est à 0 anyway!). C'est ce qu'il y a de moins cher, mais ça lisse quand même les trajectoires... Sans interpolation, c'est inutilisable!

- Plus grand que 0, la valeur est rééchelonnée entre 0.9 et 0.999 (quelque chose comme ça, de mémoire) et ça devient le coefficient  (`c`) d'un filtre passe bas:

`y = x + (last_x - x) * c`

Dans tous les cas, l'interpolation est essentielle!

À peluche!

**Comment by NicolaGiannini** [comment]
Olivier,
Merci beaucoup pour cette explication ! Cela m’aide vraiment beaucoup à comprendre !

Alors par rapport à ce que j’ai dit dans mon commentaire précédent, je pense que je pourrais dire ce qui suit. Je n'utiliserais pas une interpolation avec une valeur supérieure à zéro pour les modes DOME et CUBE. Je pourrais utiliser une interpolation  avec une valeur supérieure à zéro pour le mode STEREO.

**Comment by Normandeau** [comment]
Merci Olivier de ces précisions.
Fin de la discussion.
