### ISSUE TITLE
Buffer size: le même partout?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#206]
V215
Depuis la disparition de Jack de l'équation, Buffer Size et Fe sont maintenant indépendants. On peut supposer que les compositeurs seront assez attentif pour régler la Fe de manière conséquente, mais pour le buffer size c'est moins clair. Actuellement, on peut ajuster SpatGRIS2 et le DAW de manière indépendante. 
1. Est-ce que cela a des conséquences? 
2. Comment BlackHole réagit-il?
3. Est-ce que cela a un effet sur la synchronisation à long terme?
 
Il serait important de tester cela rapidement.

**Comment by devinroth** [comment]
The buffer size of BlackHole can be set from the DAW or SpatGRIS2. In theory these can be completely independent and different applications can use different sizes. But I haven’t done any specific tests to confirm.

Devin

**Comment by NicolaGiannini** [comment]
V215 et Logic 10.5.1
J'ai testé longuement (plus d'une heure) les combinaisons les plus étranges.
Un exemple :
Daw à 44,100 (Fe) et 1024 (Buffer size) VS SpatGRIS2 à 48,000 (Fe) et 32 (Buffer Size), et l'envers. Je n'ai eu aucun problème. Pas de distorsion et même pas de désynchronisation.

Avec des valeurs basses de Buffer Size pour SpatGRIS2 (par exemple 32), j'entends des clics sur les sons graves, mais je pense que c'est normal.

**Comment by Normandeau** [comment]
Ce que tu décrit ici est incompréhensible pour moi. Ce que je connais de la théorie de l'échantillonnage me dit qu'on ne peut pas opérer un même système audio-numérique sur deux fréquences d’échantillonnage en même temps. Il y a forcément une partie du système qui transpose. Live fait cela. Quel DAW utilises-tu? Peux-tu tester plus avant avec du matériel audio tonique, comme une chanson par exemple. Avec des hauteurs très précises. Et écouter s'il y a transposition (c'est environ un demi-ton entre 44 et 48). Ou alors essayer avec des Fe encore plus différentes comme 44 et 96 par exemple? (essayer d"éviter le rapport d'octave comme 44-88).

**Comment by NicolaGiannini** [comment]
J'ai fait d'autres tests en ce qui concerne la Fe.

Dans mon cas, la fréquence d'échantillonnage est la même dans le DAW et dans SpatGRIS2, même si parfois la fréquence affichée par SpatGRIS2 n'est pas la réelle. Changer la Fe dans Logic 10.5.1 et dans Live 10.1.30 fait changer automatiquement la Fe également dans SpatGRIS2, mais ce changement n’est pas affiché. Si la carte de son choisie comme output dans SpatGRIS2 ne supporte pas la Fe qu’on a mis dans le DAW, on n’aura pas du son et les deux Fe seront différentes.

Je donne un exemple.

J’ouvre SpatGRIS2 et je mets comme input device Blackhole et comme output device une carte de son Apogee qui supporte une Fe jusqu’à 96kHz. 
Dans SpatGRIS2 je mets comme Fe 88,200Hz. Je redémarre SpatGRIS2.
J’ouvre l’application Configuration Audio et Midi pour vérifier les Fe : Blackhole et la carte du son utilisée par SpatGRIS2 sont à 88,200 Hz. Cpu usage : 68%

J’ouvre Logic, la carte de son choisie est Blackhole, je crée un nouveau projet qui par default est à 44,100 Hz. Blackhole et la carte du son utilisée par SpatGRIS2 se mettent automatiquement à 44,100 (vérifié par l’application Configuration Audio et Midi). CPU usage de SpatGRIS2 affiche 31 %. La Fe affichée ne change pas, elle reste à 88,200 Hz. 

Dans Logic je change la Fe à 96 kHz. Blackhole et la carte du son utilisée par SpatGRIS2 se mettent automatiquement à 96 kHz. CPU usage de SpatGRIS2 affiche 72%. La Fe affichée ne change pas, elle reste 88,200 Hz. 

Dans Logic je change la Fe à 176,400 kHz. Blackhole passe effectivement à 176,400 Hz,  mais la carte du son utilisée par SpatGRIS2 reste à 96 kHz (elle ne supporte pas une Fe à 176,400 kHz). On a pas du son et le CPU usage passe à zéro.

Pour résumer, Blackhole (donc le DAW) et la carte du son utilisée par SpatGRIS2 sont toujours à la même Fe, si la Fe choisie dans le DAW est supportée dans la carte du son utilisée par SpatGRIS2. Si la Fe choisie dans le DAW n'est pas supportée dans la carte du son utilisée par SpatGRIS2 on aura 2 Fe différentes et on aura pas de son.

Dans Reaper j'ai un comportement un peu différent. C'est SpatGRIS2 qui change la Fe dans le DAW. Mais j'admets que je ne suis pas trop pratique de Reaper. Pour le reste, le comportement est le même.

**Comment by Normandeau** [comment]
V216
Il semble bien que les buffer size peuvent être différents d'une appli à l'autre.

**Comment by NicolaGiannini** [comment]
V216
Je confirme que il semble qu'on peut choisir des buffer size différents d'une appli à l'autre.
