### ISSUE TITLE
"Jack Settings" est affiché dans les Proprieties/Pereferences

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#207]
V215
Un détail : "Jack Settings" est affiché dans les Proprieties.
![Capture d’écran, le 2021-01-16 à 17 26 59 copy](https://user-images.githubusercontent.com/35705913/104827857-b26b8f00-5830-11eb-9257-4e2b01001909.png)

Peut-être, il faudrait simplement enlever l'expression "Jack Settings".

**Comment by Normandeau** [comment]
V216
Réglé.
