### ISSUE TITLE
Certaines configuration de hp anciennes DOME plante SpatGRIS lorsqu'il est en CUBE

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#208]
V215
Je viens d'ouvrir un dôme de hp fait pour la salle Claude Champagne il y a pourtant moins d'un an (10 avril 2020). SpatGRIS2 était en mode CUBE au moment de l'ouverture et il a planté. Je ne sais pas si d'autres ont constaté cela? Dans mon cas c'est vraiment rare. Pour l’instant je me mets une note pour le manuel.

**Comment by SamuelBeland** [comment]
Est-ce qu'il t'a été possible d'ouvrir le speaker setup par la suite, ou est-ce que ça plante à tout coup ?

**Comment by SamuelBeland** [comment]
Est-possible aussi d'obtenir une copy du fichier xml ?

**Comment by Normandeau** [comment]
Je viens de tester une vingtaine de configurations anciennes, y compris celle qui avait fait planter. Aucun problème. Donc c'était probablement un coupe de malchance. Si ça se reproduit, je documenterai davantage.
