### ISSUE TITLE
Dans un speaker setup, plus la valeur des output est élevée, plus la consommation de CPU est grande

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#209]
V215
Je ne sais pas si l'on peut considérer un issue, mais dans un speaker setup plus la valeur des output est élevée, plus la consommation de CPU est grande, cela affecte aussi l'influence de la valeur de l'interpolation sur la consommation de CPU. Je me ne réfère pas au nombre de sorties, mais à la valeur du chiffre des sorties. 

Si, par exemple, on crée un setup de 16HP et que les haut-parleurs sont assignés aux sorties 1 à 16 la consommation du CPU (avec 60 input), dans mon cas, est d'environ 9% en mode DOME et CUBE, et cela avec la valeur d'interpolation à 0. Avec une valeur d'interpolation supérieure à 0 en mode DOME j'obtiens une consommation du CPU de 12% et mode CUBE de 17%.

Si on crée un setup de 16HP  et que les haut-parleurs sont assignés aux sorties de 1 à 8 et de 120 à 127 la consommation du CPU, dans mon cas, est d'environ 55% en mode DOME et CUBE avec l'interpolation à 0. 
Avec une valeur d'interpolation supérieure à 0 en mode DOME j'obtiens une consommation du CPU de 34% et mode CUBE de 40%.
Je joins les deux setup.
[16HP.zip](https://github.com/GRIS-UdeM/ServerGRIS/files/5832101/16HP.zip)

En résumant : plus la valeur des output est élevée, plus la consommation de CPU est grande si l'interpolation est à zéro. Et si on définit une valeur d'interpolation supérieure à zéro, à partir de ces cas, la consommation du CPU diminue.

J'ai fait des tests avec d'autres setup et j'ai les mêmes résultats. 

Le comportement lié à l'interpolation m'a rappelé cette discussion https://github.com/GRIS-UdeM/ServerGRIS/issues/158

**Comment by Normandeau** [comment]
Wow!! Qu'est-ce que c'est que cela?
Je confirme. Sur un dispositif de 20.4 hp, la distribution des numéros de sorties sur 32 valeurs occupe 15% de CPU. Si je fais passer al moitié du dispositif sur des valeurs non continues à partir de 96 par exemple, le CPU passe à 35%!!!
Pour des chiffres! Est-ce que la valeur des sorties non utilisées est prise en compte dans la charge de CPU!
Quel bogue!

**Comment by Normandeau** [comment]
Bravo Nicola.
Et quand je dis à 35% c'est parce que l'interpolation était à 0.1. Lorsque je la mets à 0.0 ça passe à 50% avec un petit projet de 54 entrées. Avec mon projet actuel de 116 canaux, ça passe carrément à 100%. Mais selon Moniteur d'activité on serait plutôt à 125%!
Quand la séquence joue, SpatGRIS2 continue d'afficher 100% (est-ce qu'il peut afficher plus? Apparemment non, il reste collé à 100%) mais Moniteur d'activité indique plutôt 160%.
Si je remets mon speaker setup d'Icosa, même nombre de hp et 116 entrées, ça retombe à 35%. (75% selon Moniteur d’activité). Quand la séquence joue, le CPU Usage de SpatGRIS descend à 30% (!!!), mais Moniteur d'activité montre plutôt 110%.

**Comment by Normandeau** [comment]
Comparaison de l'usage du CPU en fonction des numéros de sortie du speaker setup. J'ai ajouté une comparaison entre une valeur d'interpolation à 0.000 et une valeur à 0.100. 
On se rend compte:
-  Qu'il vaut mieux utiliser la valeur 0.100 plutôt que 0.000 (les valeurs au-dessus 0.100 n'affectent pas tellement le CPU);
- Qu'il vaut mieux utiliser des numéros de sortie consécutifs qui commencent à 1 (mais que faire alors quand on a une UFX+ dont on utilise les sorties MADI qui commencent à 31, comme au B187?).
 
On peut constater qu'avec la version 212-Jack-Mojave, il y a peu de différence entre les deux dispositifs de hp.
Alors qu'avec la version 215-Catalina-BlackHole et une session DP, le CPU passe presque du simple au double.
On peut remarquer aussi que ça dépend où on mesure. Moniteur d'activités affiche une moindre grande différence que le SpatGRIS lui-même en fonction des deux valeurs d'interpolation.
Finalement on constate que la version BlackHole consomme un peu moins de CPU que la version Jack (ce qui n'était pas le cas de la version 2.1.3).

![CPU USage en fonction des nos de sorties](https://user-images.githubusercontent.com/8959779/105084724-c39ce180-5a64-11eb-8754-1a08088ae8e1.jpg)

**Comment by SamuelBeland** [comment]
Le problème : au lieu de créer le nombre de sorties dont il a de besoin, SpatGRIS 2.1.5 créé un nombre d'outputs égal à la sortie la plus élevée !

Je vais voir si ce bug existe aussi dans 2.1.2 et investiguer comment le régler dans 2.1.5.

Merci @NicolaGiannini pour la trouvaille, c'est quelque chose qui aurait pu nous échapper pendant longtemps...

**Comment by NicolaGiannini** [comment]
J’ai essayé de reproduire les tests de Robert. 
J’ai utilisé 2 speaker setup. 
Set up1 = Nos de 1 à 16
Set up2 = NOS de  112 à 127
J’ai utilisé les versions 212 et 215, les 2 sous 10.14.

![Capture d’écran, le 2021-01-19 à 20 51 04](https://user-images.githubusercontent.com/35705913/105116120-1cd23880-5a98-11eb-8a2e-a92ae31c40f8.jpg)

Je pense d’avoir obtenu des résultats un peu différents de ceux de Robert. Dans mon cas, il ne semble pas avoir trop de différence entre V212 et V215 en ce qui concerne la relation entre CPU usage et numéros des sorties. Dans les deux cas, utiliser des numéros plus élevés donne lieu à une augmentation d’usage de CPU. 
Dans mon cas, lors du setup 1 (Nos de 1 à 16) et avec la session DAW ouverte, le passage de 0 à 0,1 en ce qui concerne l’interpolation donne lieu toujours à une petite augmentation de l’usage de CPU, tandis que dans le cas de Robert c’est le contraire.

J’ajoute une chose
Si dans une sortie on indique un chiffre supérieur à 128 on obtient un crash de SpatGRIS2 V215. Cela ne se produit pas dans V212.

Samuel dit : 

> Le problème : au lieu de créer le nombre de sorties dont il a de besoin, SpatGRIS 2.1.5 créé un nombre d'outputs égal à la sortie la plus élevée !

> 

Cela ressemblait à quelque chose comme ça. Et cela m'a rappelé cet issue : https://github.com/GRIS-UdeM/ServerGRIS/issues/179 je ne sais pas s'il y a quelque relation entre les deux situations.

**Comment by Normandeau** [comment]
On voit que dans un setup invraisemblable, le setup no 2 de Nicola avec des sorties 112 à 127, on des différences extrêmes d'usage de CPU.
Donc ce bogue existe depuis un certain temps apparemment. depuis le début?

**Comment by SamuelBeland** [comment]
Petites clarifications au sujet du CPU usage :

Le moniteur d'activité de MacOS donne une vue d'ensemble de l'utilisation du CPU pour notre processus (SpatGRIS). Ce dernier peut afficher un nombre supérieur à 100% puisqu’il additionne les pourcentages d'utilisation de chaque cœur disponible sur votre machine. Ça serait donc une bonne idée de joindre le nombre de cœurs de votre CPU à ces données. Ce % inclut tout le travail effectué par SpatGRIS : la logique interne, le processing audio, les messages OSC, l'affichage 2D, l'affichage 3D (qui à lui seul semble occuper un cœur à environ 70% sur ma machine), etc.

Le pourcentage affiché par SaptGRIS décrit __uniquement le poids du processing audio__. Le processing audio est toujours _single-threaded_, c'est-à-dire qu'il ne peut s'exécuter que sur un seul cœur. Comme ce fil d'exécution a la plus grande priorité, tous les autres qui partagent ce même cœur (qu'ils soient associés à SpatGRIS ou à un autre processus) seront retardés ou réduits de façon à ce que le processing audio ait toujours accès aux ressources dont il a besoin.

Donc en gros, le % affiché dans le moniteur d'activité est important, mais pas primordial. Ça donne une bonne vue d'ensemble du poids général de SpatGRIS sur un CPU, mais ça inclut plusieurs choses qui vont se contracter ou se dilater en fonction des ressources disponibles. 

Le % affiché dans SpatGRIS, même s’il donne moins d'information, est absolument primordial. S’il atteint 100%, cela veut dire que le processing audio n'a plus de marge de manoeuvre et qu'on entendra des clics.

**Comment by Normandeau** [comment]
Excellent, merci de ces précisions. On se fie donc à l'information que SpatGRIS nous offre, comme on le faisait autrefois avec le % affiché pour Jack. 
Parlant de 100%, j'ai trouvé une situation où ça se produit maintenant, ce qui n'était pas le cas avec ServerGRIS. À Virginia Tech, ils ont 124.2 hp. Mais la première fois que j'y suis allé en 2017, je n'avais accès qu'à 64 canaux. J'ai donc sélectionné 56 hp pour faire une sorte de dôme (le mode CUBE n'existait pas encore). Les numéros correspondant aux véritables numéros de hp sont donc répartis sur les 124 numéros disponibles (d'où le rapport avec la rubrique du jour...).
Je suis retourné sur Mojave afin de comparer nos trois outils: ServerGRIS207, SpatGRIS212 (les deux sur Jack) et SpatGRIS215 (sur BlackHole). J'ai rejoué la pièce que j'avais jouée à Virginia Tech en 2019 cette fois-là sur 124.2 hp en mode CUBE et j'ai comparé les deux dispositifs de hp. Voici le tableau des résultats. Tout cela s'est fait sur le mode CUBE.
On peut voir que la seule possibilité de jouer la pièce sur 124.2 hp a été avec le premier spatialisateur. Cela n'est plus possible avec les versions récentes. Aussi, la valeur d'interpolation de 0.100 fait overloader tous les systèmes, à une exception près, 215 avec 54.2 hp.
Par contre on peut aussi constater qu'avec un nombre moins élevé de hp, la dernière version (215) est beaucoup plus performante. Et 124.2 hp, ce n'est pas si fréquent...

![CPU USage trois spatialisateurs](https://user-images.githubusercontent.com/8959779/105244470-9886c080-5b3e-11eb-9d98-a9d747b3df40.jpg)

**Comment by devinroth** [comment]
This is really interesting.

What’s the difference between v207 and 212?

Devin

**Comment by Normandeau** [comment]
Devin,

You can follow the ServerGRIS/SpatGRIS saga on this great channel:
https://github.com/GRIS-UdeM/ServerGRIS/releases

ServerGRIS was the first name of the spatializer.
At version 2, we changed it for SpatGRIS2 but the GitHub account stayed the same.

I used 207 in my 2019 residency at Virginia Tech.
The first time in 2017 I used a beta version (probably 004, 005 or 006).

212 was the last Jack version and the official release of the SpatGRIS2.

**Comment by SamuelBeland** [comment]
La version 2.1.6 (disponible depuis moins de 2 minutes) ne règle pas encore ce bug, mais je serais quand même très intéressé à savoir comment elle performe dans les mêmes tests.

**Comment by Normandeau** [comment]
V216
Ajout de la version 216 en comparaison de trois versions précédentes. Augmentation impressionnante de la performance! Où on peut jouer la session sur les 126 hp de Virginia Tech avec l'interpolation à 0.

![CPU Usage quatre spatialisateurs](https://user-images.githubusercontent.com/8959779/105612978-88b0eb80-5d8d-11eb-83a8-637206b6de8b.jpg)

**Comment by Normandeau** [comment]
V216
Comparaison de CPU Usage entre 215 et 216. Le gain de performance est spectaculaire!
Je ne crois pas que le fait de ne pas avoir de numéros de sorties consécutifs soit encore un problème. En tout cas dans une situation réelle comme celle la UFX+ dont les numéros MADI commencent à 31, ce n'est pas problématique. Et dans la réalité, c'est probablement la situation la plus «extrême» que l'on puisse rencontrer.
J'attire tout de même l'attention sur le fait que l'interpolation à 0.100 diminuait le CPU dans 215 alors qu'elle l'augmente sous 216.
(Veuillez noter que le nombre de pistes n'est pas le même entre le tableau précédent, 66, et celui-ci, 116).

![CPU Usage en fonction des nos de sorties](https://user-images.githubusercontent.com/8959779/105613156-da0daa80-5d8e-11eb-8484-fa802f562126.jpg)

**Comment by NicolaGiannini** [comment]
V216
J’ai essayé de répéter les tests de Robert en ce qui concerne la comparaison entre les 4 spatialisateurs. J’ai aussi ajouté la version DOME des deux setups.
Je pense que les résultats sont cohérents avec ceux de Robert. Et wow quelle super Augmentation de performance !

Je vous reviens aussi avec l'autre comparaison en fonction des numéros des sorties. 

![Schermata 2021-01-26 alle 14 54 23](https://user-images.githubusercontent.com/35705913/105897653-72519c80-5fe6-11eb-9771-2440c4097d4d.jpg)

**Comment by NicolaGiannini** [comment]
J’ai essayé de répéter les tests de Robert en ce qui concerne l’usage de la CPU en fonction des numéros des sorties.
Aussi dans ce cas, je pense que les résultats sont cohérents avec ceux de Robert.

À noter la différence de performance entre les deux versions  en ce qui concerne le Setup 2, le setup plus irréaliste (NOS de  112 à 127). Notamment on passe de 125% à 50% en ce qui concerne la mesure de CPU affichée par le Moniteur d'activité lors de l’interpolation à 0. 

Robert : 

> Je ne crois pas que le fait de ne pas avoir de numéros de sorties consécutifs soit encore un problème. 

Je suis totalement d'accord. 

![Schermata 2021-01-27 alle 19 39 59](https://user-images.githubusercontent.com/35705913/106073199-95a84480-60d7-11eb-8fa8-95042425ddc5.jpg)
