### ISSUE TITLE
Fréquence d'échantillonnage: qui est le boss?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#210]
J'ai séparé cette discussion du Buffer size parce que ce sont deux choses très différentes.
Nicolas:
J'ai testé longuement (plus d'une heure) les combinaisons les plus étranges. Un exemple : Daw à 44,100 (Fe) et 1024 (Buffer size) VS SpatGRIS2 à 48,000 (Fe) et 32 (Buffer Size), et l'envers. Je n'ai eu aucun problème. Pas de distorsion et même pas de désynchronisation.
Avec des valeurs basses de Buffer Size pour SpatGRIS2 (par exemple 32), j'entends des clics sur les sons graves, mais je pense que c'est normal.

**Comment by Normandeau** [comment]
Robert:
 Ce que tu décrit ici est incompréhensible pour moi. Ce que je connais de la théorie de l'échantillonnage me dit qu'on ne peut pas opérer un même système audio-numérique sur deux fréquences d’échantillonnage en même temps. Il y a forcément une partie du système qui transpose. Live fait cela. Quel DAW utilises-tu? Peux-tu tester plus avant avec du matériel audio tonique, comme une chanson par exemple. Avec des hauteurs très précises. Et écouter s'il y a transposition (c'est environ un demi-ton entre 44 et 48). Ou alors essayer avec des Fe encore plus différentes comme 44 et 96 par exemple? (essayer d"éviter le rapport d'octave comme 44-88).

**Comment by Normandeau** [comment]
J'ai fait d'autres tests en ce qui concerne la Fe.
Dans mon cas, la fréquence d'échantillonnage est la même dans le DAW et dans SpatGRIS2, même si parfois la fréquence affichée par SpatGRIS2 n'est pas la réelle. Changer la Fe dans Logic 10.5.1 et dans Live 10.1.30 fait changer automatiquement la Fe également dans SpatGRIS2, mais ce changement n’est pas affiché. Si la carte de son choisie comme output dans SpatGRIS2 ne supporte pas la Fe qu’on a mis dans le DAW, on n’aura pas du son et les deux Fe seront différentes.
Je donne un exemple.
J’ouvre SpatGRIS2 et je mets comme input device Blackhole et comme output device une carte de son Apogee qui supporte une Fe jusqu’à 96kHz. Dans SpatGRIS2 je mets comme Fe 88,200Hz. Je redémarre SpatGRIS2. J’ouvre l’application Configuration Audio et Midi pour vérifier les Fe : Blackhole et la carte du son utilisée par SpatGRIS2 sont à 88,200 Hz. Cpu usage : 68%
J’ouvre Logic, la carte de son choisie est Blackhole, je crée un nouveau projet qui par default est à 44,100 Hz. Blackhole et la carte du son utilisée par SpatGRIS2 se mettent automatiquement à 44,100 (vérifié par l’application Configuration Audio et Midi). CPU usage de SpatGRIS2 affiche 31 %. La Fe affichée ne change pas, elle reste à 88,200 Hz.
Dans Logic je change la Fe à 96 kHz. Blackhole et la carte du son utilisée par SpatGRIS2 se mettent automatiquement à 96 kHz. CPU usage de SpatGRIS2 affiche 72%. La Fe affichée ne change pas, elle reste 88,200 Hz.
Dans Logic je change la Fe à 176,400 kHz. Blackhole passe effectivement à 176,400 Hz, mais la carte du son utilisée par SpatGRIS2 reste à 96 kHz (elle ne supporte pas une Fe à 176,400 kHz). On a pas du son et le CPU usage passe à zéro.
Pour résumer, Blackhole (donc le DAW) et la carte du son utilisée par SpatGRIS2 sont toujours à la même Fe, si la Fe choisie dans le DAW est supportée dans la carte du son utilisée par SpatGRIS2. Si la Fe choisie dans le DAW n'est pas supportée dans la carte du son utilisée par SpatGRIS2 on aura 2 Fe différentes et on aura pas de son.
Dans Reaper j'ai un comportement un peu différent. C'est SpatGRIS2 qui change la Fe dans le DAW. Mais j'admets que je ne suis pas trop pratique de Reaper. Pour le reste, le comportement est le même.

**Comment by Normandeau** [comment]
La grande question c'est: qui a le contrôle sur la Fréquence d'échantillonnage?
Quand on avait Jack, c'était simple: c'était Jack. Et tout le monde s'ajustait automatiquement. Nicola et moi avons travaillé sur un tableau avec DP, Logic, Live et Reaper.
Ce qui ressort de nos tests, c'est qu'avec DP, Logic et Live, c'est le DAW qui détermine la Fe. Toute la chaîne audionumérique s'ajuste automatiquement à celle-ci. SpatGRIS2 aussi, même s'il n'affiche pas la bonne valeur. Le son est toujours lu à la bonne Fe par ce dernier.
Reaper est un cas à part. Difficile à comprendre en réalité. Il semble qu'il transpose tout le temps. En fonction de la fréquence «forcée» choisie dans les préférences du projet.

![Fréquences d'échantilonnage](https://user-images.githubusercontent.com/8959779/105534042-ea545580-5cba-11eb-8da2-7fb4dc67bc6f.jpg)

Deux questions fondamentales se posent pour SpatGRIS2:
1) Pourquoi SpatGRIS2 ne s'inscrit-il pas de manière très flexible dans la chaîne audionumérique en s'ajustant et en affichant la bonne Fe? Pourquoi doit-on le redémarrer pour changer sa Fe alors que dans les faits, il la change naturellement sur demande? Pour moi la chaîne audio est ainsi faite: DAW -> BlackHole -> SpatGRIS2 -> Interface. Donc tout ce qui est après le DAW devrait s'ajuster automatiquement comme le font déjà BlackHole et l'interface. SpatGRIS2 le fait aussi, mais on ne le sait pas. Sauf à l'oreille!

2) Pourquoi les choix de Fe dans SpatGRIS2 sont-ils limités à 44, 48, 88 et 96? Alors que de toute évidence il fonctionne aussi à 176 et 192?

Et une autre question fondamentale se pose pour moi: comme la Fe est-elle communiquée à tous dans la chaîne audionumérique? Est-ce Core Audio qui joue ce rôle? On voit bien que quand on ouvre un DAW (sauf Reaper), toutes les composantes prennent la même valeur de Fe. Pourrait-on alors faire en sorte que SpatGRIS adopte la même Fe et l'affiche automatiquement?

**Comment by Normandeau** [comment]
PS Un des indices qui nous indiquent que SpatGRIS2 fonctionne bien à 176 et 192 c'est le CPU, qui passe très rapidement à des valeurs très élevées à ces très hautes fréquences d'échantillonnage. En fait à ces valeurs, le nombre d'entrées et de hp est très limité.

**Comment by NicolaGiannini** [comment]
Je suis d’accord avec tous les points indiqués par Robert. Il serait pratique que SpatGRIS2 puisse s'adapter automatiquement aux Fe indiquées dans le DAW.

J’ai fait des tests supplémentaires pour chercher de comprendre la relation entre DAW, SpatGRIS2 e Core Audio. 
En résumant, de ce que je comprends :

- Logic est toujours le master de la Fe.
- Live, ça dépende de la séquence temporelle des actions. La Fe peut être imposé par Live même, par SpatGRIS2 et également par l’application Configuration Audio et MIDI.
- Reaper est toujours le slave, mais il y a une exception.  Si on utilise l’audio de système (Sortie = BlakHole ; Entrée = la carte de son choisie dans SpatGRIS2) comme carte de son de Reaper, on peut obtenir le même comportement de Live. 

Voici les comportements décrits plus en détail.

3 prémisses : 

- Pour avoir du son, il faut que toute la chaine audio soit à la même Fe.
- La Fe de la chaine audio doit être supportée par la carte qu’on a choisie comme sortie de SpatGRIS2.
- Pour vérifier les Fe j’utilise l’application Configuration Audio et MIDI. Les donnes que je regarde sont :

1. Fe de BlackHole (qui est la sortie de la DAW et l’entrée de SpatGRIS2)
2. Fe de la carte du son choisie en sortie de SpatGRIS2

**Logic > est toujours le Master**
La Fe reste toujours celle sélectionnée même si j’essaie de la changer de SpatGRIS2 avec redémarrage de SpatGRIS2. La Fe reste la même également si je cherche à la changer à partir de l’application Configuration Audio et MIDI.

**Live > ça dépende de la séquence temporelle des actions.** 
Si j’indique une Fe dans Live, cette Fe devient la Fe de toute la chaine audio. Si ensuite j’indique une autre Fe dans SpatGRIS2 (avec redémarrage de SpatGRIS2), cette Fe devient la Fe de toute la chaine audio. Il y a une autre possibilité : si j’indique une Fe dans l’application Configuration Audio et MIDI, cette nouvelle Fe devient la Fe de toute la chaine audio.

**Reaper > SpatGRIS2 est toujours le master, cela dit il y a une exception**

Dans Reaper, si on sélectionne BlackHole comme carte de son, la Fe de la chaine audio est toujours imposée par SpatGRIS2. Cependant on peut obtenir le même comportement de Live si on fait ce qui suit.
Dans les Préférences Système, il faut mettre comme son:

- Sortie = BlackHole 
- Entrée = la carte de son choisie dans SpatGRIS2 comme sortie

Il faut sélectionner dans Reaper comme carte de son Default System Devices.
À partir de maintenant le comportement est identique à celui de Live. 

Par contre, je me demande si c’est une bonne idée dans Reaper le fait de choisir comme carte de son les « Default System Devices » composée par 2 cartes de son différentes. Dans les options de Reaper c'est découragé le fait d’utiliser de différents dispositifs en sortie et en entrée. Cependant il pourrait être considéré peut-être comme un dispositif agrégé, mais j’admets que je ne suis pas pratique de Reaper.

Une dernière note. Il y a un aspect positif à sélectionner Blackhole et la carte de son de sortie comme audio de système. Par exemple en sélectionnant l’audio du système dans Logic, de cette façon j’ai accès seulement aux Fe utiles, soit celles supportées par la carte de son en sortie de SpatGRIS2.

**Comment by NicolaGiannini** [comment]
Je vous propose des réflexions générales suivantes celles  de Robert.

Pourrait-on retirer tout contrôle sur le Fe de SpatGRIS2 et tout gérer à partir de la DAW ? Actuellement, comment le SpatGRIS2 agit-il sur Fe ? Vu ce qui se passe dans Reaper, je pense que SpatGRIS2 gère quand même le Fe. 

Imaginons que l'on élimine ce contrôle. Si la carte son en sortie de SpatGRIS2 ne se règle pas automatiquement sur la même Fe de la DAW, on pourrait utiliser l'application Configuration Audio et Midi pour indiquer la bonne Fe ?

**Comment by Normandeau** [comment]
V116
Il semble bien que sauf pour Reaper (qui reste à comprendre), tout le monde s'accorde sur la même Fe. Je vais tout de même mettre une note dans le manuel.

**Comment by NicolaGiannini** [comment]
V216
Dans mon cas, tout le monde s'accorde sur la même Fe en ce qui concerne Logic et Live.
Dans Logic on ne peut pas changer la Fe à partir de SpatGRIS2, Logic est toujours le boss.
Dans Live on peut changer la Fe à partir de la DAW et de SpatGRIS.

Dans Live et Logic, si on indique une Fe non supporté par la carte de son en sortie de SpatGRIS2, les DAWs et SpatGRIS2 ne se mettent pas à la même Fe. C’est un comportement normal,  cela dit je ne sais pas s’il faudrait l'indiquer dans le manuel. 

Dans Reaper on peut indiquer la Fe seulement à partir de SpatGRIS2. Si on change la Fe à partir de Reaper (soit des préférences du projet ou générales) la Fe ne change pas. Si on change la Fe à partir de SpatGRIS2, tout le monde s'accorde sur la même Fe.

**Comment by Normandeau** [comment]
V2.1.13
Mis dans le manuel
