### ISSUE TITLE
Preferences-Properties? Ou Settings?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#212]
Pour la version 3 officielle.
Dans le menu File on ouvre des Preferences:

![Properties-Preferences](https://user-images.githubusercontent.com/8959779/105614951-c8ca9b00-5d9a-11eb-8fd3-bb3f8bef5870.jpg)

Mais c'est une fenêtre Properties qui s'ouvre.
Peut-être que ce n'est ni l'un ni l'autre, mais plutôt des Settings (c'est le nom que les réglages portent tous)?

![Properties](https://user-images.githubusercontent.com/8959779/105614978-00394780-5d9b-11eb-80d4-84de4a62ffab.jpg)

**Comment by NicolaGiannini** [comment]
"Settings" semble le plus approprié.

**Comment by MelanieFrisoli** [comment]
D'accord aussi pour Settings.

**Comment by NicolaGiannini** [comment]
V217
“Settings” est affiché dans le menu file et dans la fenêtre des réglages.
