### ISSUE TITLE
Incompatibilité des versions 216 et 218 à cause des préférences

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#215]
V3
Afin d'indiquer correctement les noms et les endroits où se situent les préférences de SpatGRIS3, notamment s'il faut désinstaller, il faudrait uniformiser:

• Preferences:
~/Library/Preferences/com.UdeM.GRIS.SpatGRIS3.plist
Celle-ci est ok et porte déjà le nom de la version 3

• Support Library
~/Application Support/GRIS/SpatGRIS2.xml
Changer la version 2 pour la version 3

Disparue?
Celle-ci ne se retrouve plus avec la version 3:

• Cache:
~/Library/Caches/com.UdeM.GRIS.SpatGRIS2
Exact?

**Comment by NicolaGiannini** [comment]
Après avoir éliminé tous les fichiers dans la Library et après avoir installé SpatGRIS2 v216, j’obtiens les fichiers suivants :

Support Library : 
~/Application Support/GRIS/SpatGRIS2.xml

Preferences:
~/Library/Preferences/com.UdeM.GRIS.SpatGRIS3.plist

Je ne trouve aucun fichier dans le cache.

**Comment by NicolaGiannini** [comment]
V217
Dans ~/Library/Preferences/com.UdeM.GRIS.SpatGRIS3.plist
Le fichier est com.UdeM.GRIS.SpatGRIS3

Dans ~/Application Support/GRIS/SpatGRIS.xml
Le fichier est SpatGRIS.xml

**Comment by Normandeau** [comment]
Pour la version 217, Samuel a écrit: All user settings files should now be properly labeled as "SpatGRIS3"».
Donc ce n'est pas encore le cas.

**Comment by Normandeau** [comment]
V218, version du 5 mars,
Afin de vérifier l'installation ce cette nouvelle version, j'ai voulu jeter les préférences de la version installée hier avec laquelle j'ai travaillé toute la journée. Voici ce que j'ai trouvé:

~/Application Support/GRIS/SpatGRIS.xml

~/Library/Preferences/
Ce fichier: com.UdeM.GRIS.SpatGRIS3 est inexistant!

Où sont donc stockées les préférences maintenant?

**Comment by NicolaGiannini** [comment]
Je confirme ce que Robert a dit.

**Comment by Normandeau** [comment]
V219
Ni l'un, ni l'autre ne sont créés. Les Settings ne sont pas sauvegardés, particulièrement les CUBE Distance Settings.

Dans ~/Library/Preferences/com.UdeM.GRIS.SpatGRIS3.plist
Le fichier était com.UdeM.GRIS.SpatGRIS3

Dans ~/Application Support/GRIS/SpatGRIS.xml
Le fichier était SpatGRIS.xml

**Comment by SamuelBeland** [comment]
Les settings sont sauvegardés dans v2.1.9.

Les paramètres d'atténuation CUBE font maintenant partie des paramètres de projet et non plus des paramètres utilisateurs. L'utilisateur sera averti en fermant SpatGRIS que le projet a été modifié.

Je vais vérifier le *path* de sauvegarde pour cette version des paramètres utilisateur...

**Comment by Normandeau** [comment]
Ok, alors si «les paramètres d'atténuation CUBE font maintenant partie des paramètres de projet», comme nous en avions convenu, il faut les mettre dans le projet, pas dans les Settings. Car si je les ajuste dans ceux-ci et que je fait Save, je m'attends à ce qu'ils soient sauvés, non? Surtout qu'avant ça fonctionnait comme cela. Il faut que la relation de ces paramètres avec le projet soit claire, donc visible dans le projet. Car dans le projet, aussitôt qu'on bouge quelque chose, il nous demande à la fin de le sauver, ce qui est bien évidemment. Mais parfois c'est juste pour expérimenter, alors on ne sauve nécessairement à tous les coups.
Sinon, aujourd'hui, un document nommé SpatGRIS (et non pas SpatGRIS2 ou SpatGRIS3, comme déjà discuté) a bien été créé dans ~Library/Application Support/GRIS

**Comment by SamuelBeland** [comment]
Je suis bien d'accord avec toi. Je vais ajouter les settings d'atténuation directement dans l'interface de projet lorsque l'on est en mode CUBE.

**Comment by Normandeau** [comment]
V2110
Réglé. À mettre dans le manuel.

**Comment by Normandeau** [comment]
V2113
Mis dans le manuel
