### ISSUE TITLE
Si à l'ouverture, la carte de son qui a été sélectionnée lors de la précédente utilisation n'est pas connectée, SpatGRIS2 plante

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#216]
V216
Dans mon cas, si à l'ouverture, la carte de son qui a été sélectionnée lors de la précédente utilisation (une Apogee dans mon cas) n'est pas connectée, SpatGRIS2 plante.

Je sélectionne une carte de son en sortie.
Je ferme SpatGRIS2.
Je déconnecte cette carte.
J’ouvre SpatGRIS2.
SpatGRIS2 plante.

Si je déconnecte la carte de son pendant que SpatGRIS2 est ouvert, SpatGRIS2 passe automatiquement à une autre carte de son disponible. 

Après ce crash, si je reconnecte la carte et ouvre SpatGRI2, SpatGRIS2 s'ouvre régulièrement.

Probablement, il faudrait vérifier si cela se passe aussi avec d’autres cartes de son.

**Comment by Normandeau** [comment]
Exact. J'ai eu la même chose hier en passant de ma RME Babyface Pro à ma Madiface USB même si c'est le même pilote. Peux-tu vérifier si, après avoir déconnecté ton interface, tu jettes les préférences de Spatgris2, ça plante quand même? Chez moi ça règle le problème. On en a discuté hier avec Samuel. Ce sera corrigé à la prochaine version.

**Comment by NicolaGiannini** [comment]
J’ai réglé le problème en jetant ça :
• Support Library
~/Application Support/GRIS/SpatGRIS2.xml
Changer la version 2 pour la version 3

Jeter ça n’avait pas réglé le problème :
 • Preferences:
~/Library/Preferences/com.UdeM.GRIS.SpatGRIS3.plist

**Comment by Normandeau** [comment]
Je ne comprends pas, parce que dans mon ordi (Catalina), c'est toujours le document SpatGRIS2 qui est généré dans Application Support:
~/Application Support/GRIS/SpatGRIS2.xml
Le seul fichier de préférences qui mentionne la version 3 est précisément celui qui est dans les préférences d'utilisateur:
~/Library/Preferences/com.UdeM.GRIS.SpatGRIS3.plist
Je parle de cela dans l'issue #215

**Comment by MelanieFrisoli** [comment]
J'ai eu le même problème en passant du B-188 au Gris du 5ème étage.
Ai jeté également ceci:
• Support Library
~/Application Support/GRIS/SpatGRIS2.xml
et le problème était réglé.

**Comment by NicolaGiannini** [comment]
V217
Ça semble réglé.

**Comment by Normandeau** [comment]
Effectivement.

**Comment by Normandeau** [comment]
Cependant les Preferences sont réinitialisées de telle sorte que l'interface choisie en sortie est également celle qui est choisie en entrée. Je vais mettre une note dans le manuel

**Comment by Normandeau** [comment]
Nicola a ajouté (21-06-01):

Dans certaines conditions, le changement de carte son et l'augmentation du buffer size peuvent faire planter SpatGRIS. Cela dans mon cas, ça se produit si à l'ouverture de SpatGRIS, la carte de son qui a été sélectionnée lors de la précédente utilisation n'est pas connectée, voir issue #216

Comme Robert indique dans cet issue "les Preferences sont réinitialisées de telle sorte que l'interface choisie en sortie est également celle qui est choisie en entrée" en plus le buffer size est mis automatiquement à 512.

Dans cette situation si je change la carte de son, soit en input ou en ouput, et qu'après j'augmente le Buffer Size, soit à 1024 ou à 2048, j'ai toujours un crash.
Cela ne se produit pas si je change de carte de son et que je baisse le Buffer Size.

https://user-images.githubusercontent.com/35705913/120362702-5aae5b80-c2d9-11eb-8c31-d3e7b0133509.mov

**Comment by Normandeau** [comment]
J'ai mis ton commentaire ici, car nous avions déjà une issue à ce sujet.
Je remarque dans ton film que tu laisses la sortie à Built-In Output. Qu'en est-il si tu passes d'une interface externe à une autre? Se pourrait-il que ce soit un bogue avec la sortie stéréo du Mac qui ne supporte certaines valeurs de Buffer Size?

**Comment by NicolaGiannini** [comment]
Robert,
J’ai essayé aussi en mettant en input Blackhole et en output la Fireface du B187 et j’ai le même problème. 


https://user-images.githubusercontent.com/35705913/120378639-ad454300-c2ec-11eb-87b5-d81716706696.mov



Cela dit, si à l'ouverture de SpatGRIS la carte de son qui a été sélectionnée lors de la précédente utilisation n'est pas connectée, SpatGRIS sélectionne automatiquement comme carte de son le Built-In Output et Input. Peut-être que cela se produit à cause du passage de la carte interne à une autre carte ?

**Comment by NicolaGiannini** [comment]
V210

Nicola

> Dans certaines conditions, le changement de carte son et l'augmentation du buffer size peuvent faire planter SpatGRIS. Cela dans mon cas, ça se produit si à l'ouverture de SpatGRIS, la carte de son qui a été sélectionnée lors de la précédente utilisation n'est pas connectée, voir issue #216. Dans cette situation si je change la carte de son, soit en input ou en ouput, et qu'après j'augmente le Buffer Size, soit à 1024 ou à 2048, j'ai toujours un crash.

Cela semble réglé en V210

**Comment by Normandeau** [comment]
En fait, après discussion avec Samuel, il semble que si les entrées-sorties sauvegardées ne sont pas trouvées par SpatGRIS à son ouverture, il va chercher les préférences son du système. Donc si on met Blackhole en entrée dans les Préférence son, c'est cette option qui sera choisie en entrée. En sortie, c'est un petit peu au petit bonheur la chance, mais mon expérience c'est qu'en passant d'un studio l'autre, les cartes son les plus couramment utilisées sont rappelées. Mais pas toujours!

**Comment by Normandeau** [comment]
V2112
Input et Output sauvés dans les Settings sont automatiquement rappelés. Si l'un ou l'autre est absent — une nouvelle carte de son dans un autre studio par exemple — SpatGRIS va chercher celle qui est sélectionnée dans les Préférences du système.
