### ISSUE TITLE
L'enregistrement ne fonctionne plus correctement depuis 216

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#218]
V216
J'ai fait un enregistrement stéréo 24 bits/48kHz de 15 minutes en format Single Interleaved, et voici ce que j'obtiens:
- deux fichiers séparés
- vides
- Même vides on ne peut pas les ouvrir.

![Capture d’écran, le 2021-02-11 à 11 23 07](https://user-images.githubusercontent.com/8959779/107665565-91ddfb80-6c5b-11eb-891d-ea1fa7b0dc9d.jpg)

Avec Multiple Mono Files, en mode DOME, pas de problème.

J'ai fait un second essai après avoir tout quitté. Et tout a fonctionné à nouveau. Est-ce un problème avec les Preferences qui ne se mettent pas jour à moins de redémarrer SpatGRIS2 (comme dans le bon vieux temps)? Je les avais changées de Multiple Mono Files à Single Interleaved et fait Save, mais sans redémarrer SpatGRIS2.
Toujours est-il que la première fois que j'avais essayé d'enregistrer la version stéréo, la fenêtre annonçant que SpatGRSIS2 génère le fichier interfolié n'était pas apparu, avec sa confirmation:

![Capture d’écran, le 2021-02-11 à 11 39 20](https://user-images.githubusercontent.com/8959779/107668144-57299280-6c5e-11eb-9722-ccee87660f4e.jpg)

Pourriez-vous tester cela davantage?

**Comment by Normandeau** [comment]
Cela a très certainement à voir avec les Preferences et le fait de redémarrer SpatGRIS2, sinon, elles ne sont pas prises en charge. Je viens de changer de Single Interleaved à Multiple Mono en mode DOME, et il a généré un fichier interfolié. Qui lui, a bien fonctionné.
Alors indication dans le manuel, ou correction de la situation?

**Comment by Normandeau** [comment]
J'ai été un peu vite en affaire: le fichier interfolié a bien fonctionné... jusqu'à 7 minutes pour une musique qui dure 15:20 minutes. L'enregistrement a continué jusqu'à 13:48 seulement (?!?), mais le document est silencieux après 7 minutes.

![Capture d’écran, le 2021-02-11 à 12 09 52](https://user-images.githubusercontent.com/8959779/107671799-3c591d00-6c62-11eb-8844-c248eb0f97b4.jpg)

**Comment by NicolaGiannini** [comment]
J'ai fait quelques tests. Dans mon cas, l'enregistrement en mode STEREO ne fonctionne pas si j'ai d'abord enregistré en mode DOME ou CUBE. Si j'enregistre en mode STEREO après avoir enregistré en mode DOME ou CUBE, deux fichiers vides sont toujours générés. Il y a toujours deux fichiers, que "Single Intervealed" ou "Multiple Mono Files" soit sélectionné dans les paramètres. Si je fais un enregistrement en mode BINAURAL, l'enregistrement stéréo recommence à fonctionner.

Cela se produit même si après les enregistrements en mode DOME, CUBE et BINAURAL je redémarre SpatGRIS2. Le fonctionnement (ou pas) de l'enregistrement en mode STEREO dépend toujours du dernier mode d'enregistrement.

**Comment by Normandeau** [comment]
V216
Résumé: Impossible de faire du Stereo Interleaved après DOME ou CUBE.
Il faut choisir ces dernières préférences, quitter SpatRIS2 et ensuite c'est possible.
Donc la fonction existe toujours, mais elle n'est disponible que dans certaines conditions très particulières.

De Dome à Stereo, sans quitter SpatGRIS2
Preferences jetées avant l'ouverture de SpatGRIS 2, à cause de #216 
Petit projet: 18 entrées
Petit seul de hp: 12 hp.

Enregistrement Stereo, Interleaved
• Ok
Enregistrement Stereo, Multiple Mono Files
• Non, reste en Interleaved
Passe à Dome, Multiple Mono Files
• Ok
Reste en Dome, Interleaved
• Ok
Passe en stereo, Interleaved
• Ok
Reste en stereo, Multiple Mono Files
• Ok

Moyen projet: 56 entrées
Moyen setup de hp: 24 hp.

De Dome à Stereo, sans quitter SpatGRIS2

Enregistrement Stereo, Interleaved
• Non: Multiple Mono, fichiers vides
Enregistrement Stereo, Multiple mono
• Non: Multiple Mono, fichiers vide

Après redémarrage de SpatGRIS2

Enregistrement Stereo, Interleaved
• Ok
Enregistrement Dome, Interleaved
• Ok
Enregistrement Dome, Multiple mono
• Ok
Passe en stereo, Interleaved
• Multiple Mono, fichiers vides
Passe en Binaural, Interleaved
• Ok
Passe en stereo, Interleaved
• Ok
Passe en Cube, Interleaved
• Ok
Passe en stereo, Interleaved
• Non: Multiple Mono, fichiers vides

Quitté SpatGRIS2 pour rendre effective les Preferences, crash, puis crash de DP, car la communication audio est rompue.
Redémarrage de SpatGRIS en mode stereo, Interleaved
• Ok

Stereo, Interleaved
• Pièce de 15'20, Ok.

**Comment by Normandeau** [comment]
Confirmation du problème d'enregistrement d'un fichier interfolié de longue durée:
Musique originale: 15'20
Durée du fichier enregistré: 13'48
Partie enregistrée: 6'54

![Fichier interfolié, ](https://user-images.githubusercontent.com/8959779/108241889-4e333800-711a-11eb-821b-61ca9f66865a.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme le problème d'enregistrement d'un fichier interfolié de longue durée.

Musique originale: 16'20
Durée du fichier enregistré: 16'20
Partie enregistrée: 13'48


Je me demande si cela a un rapport avec la taille maximale des fichiers Aiff. 
"The practical file size limit is 2 GB in many player applications due to their interpretation of the file size header. This also applies to 24-bit and 32-bit files where those bit depths are valid.	"

https://manual.audacityteam.org/man/export_formats_supported_by_audacity.html

Mais peut-être que cette limitation ne s'applique pas aux fichiers interleaved ?

Dans mon cas, le problème semble ne se poser que si le fichier est aiff. Avec wav, j'ai tout enregistré.

Enregistrement stéréo
Dans mon cas, si je jette les préférences avant ouvrir SpatGRIS2 et comme première chose je cherche d’enregistrer en stéréo, j'obtiens toujours deux fichiers vides distincts. Cela se produit même si j'essaie d’enregistrer en stéréo interleaved.

**Comment by NicolaGiannini** [comment]
V217
**En général :** 
- L'enregistrement stéréo Interleaved et Multiple mono fonctionne.
- Le problème d'enregistrement d'un fichier interfolié de longue durée reste.

J'ai remarqué de nouveaux comportements par rapport à V216.

- Le timer ne fonctionne plus, il reste bloqué à zéro.
- La fenêtre annonçant que SpatGRSIS2 génère le fichier interfolié n'apparaît pas, même si les fichiers interfoliés sont créés.
- Dans les autres modes d'enregistrement, le nombre des fichiers créés dépend de la valeur du dernier speaker qui fait partie du setup.

Je m'explique. Une configuration qui contient le HP 62 contiendra 62 fichiers (mono ou interfolié) même si le nombre réel de haut-parleurs contenus dans la configuration est de 34. 

**Le problème d'enregistrement d'un fichier interfolié de longue durée reste : voici 2 tests.**

Test enregistrement fichier interfolié à 62 canaux aiff 24 bit 48 kHz

Musique originale: 16'20
Durée du fichier enregistré: 8'00
Partie enregistrée: 4'00
Fichier de 4,29 GB

Test enregistrement fichier interfolié à 18 canaux aiff 24 bit 48 kHz

Musique originale: 16'20
Durée du fichier enregistré: 16'20
Partie enregistrée: 13'48
Fichier de 2,57 GB

Moins il y a de canaux et plus le fichier est petit, alors plus longues sont les parties effectivement enregistrées par SpatGRIS2.
Il me semble qu'il pourrait y avoir donc un lien avec la taille maximale du fichier AIFF.


**Enregistrement binaural**

L'enregistrement interfolié fonctionne, mais crée un fichier qui contient 16 canaux. Les deux premiers avec audio, les 14 autres vides. Je pense que le chiffre 16 dépend des 16 output de la configuration VBAP qui génère le binaural.

Si on enregistre en mode Multiple mono, l'enregistrement crée 16 fichiers. Les deux premiers avec audio, les 14 autres vides.

**Comment by NicolaGiannini** [comment]
BlackHole 0.2.8. et V217
Je confirme les comportements décrits dans mon précédent message.

**Comment by Normandeau** [comment]
V217, BlackHole 0.2.8
1-Première tentative d'enregistrement Stereo Interleaved: fichier stereo vide.
Deuxième tentative: Ok
2- Multi interfolié
Limitations de AIFF et Wav: 4GB
On devrait offrir CAF (Core Audio Format) et Wav64 comme format d'enregistrement pour dépasser cette limite.
Je confirme tout ce qui dit Nicola. 
3- Glitches
Voir issue #223

**Comment by NicolaGiannini** [comment]
Je précise qu’aussi dans mon cas la première tentative d'enregistrement Stereo Interleaved après l'installation de V217 était un fichier stereo vide.

**Comment by Normandeau** [comment]
V217 BlackHole 0.2.7
Retour à la version précédente de BlackHole. 
Session 56 pistes (jamais plus de 20 pistes en même temps), Speaker Setup 36 hp.
1- En mode DOME et Interleaved: ça glitch pas mal. Honnêtement, c'était peut-être le cas avant. Je n'enregistre jamais de gros fichiers comme ceux-là en mode Interleaved car il n'y a (presque) rien à faire avec après (sans compter la limite de grosseur de fichier). J'utilise toujours Multiple mono, et avec TwistedWave, je les regroupe ensuite, souvent en octos.
2- Je fais un test en mode DOME et Multiple mono, c'est pire, ca glitche et l'audio est interrompu régulièrement.
Ça fait deux mois que je travaille à mon prochain CD et que je fais au moins un mixdown (DOME ou STEREO) dans SpatGRIS par semaine. Je n'ai jamais eu le moindre problème audio, ni aucun glitch d'aucune sorte. Et c'est vraiment l’enregistrement qui est en cause ici, car l'écoute de la session seule ne pose aucune problème.
Problème majeur ici.

**Comment by Normandeau** [comment]
V217
Un autre problème vient de réapparaître dans l'enregistrement Multiple Mono. Les numéros des pistes comment à 0 et non pas à 1. Il faut évidemment corriger cela.

**Comment by Normandeau** [comment]
V217, BlackHole 0.2.8
Je fais en autre test en mode DOME et Multiple mono,  j'obtiens 36 fichiers vides numérotés de 000 à 035...

**Comment by Normandeau** [comment]
Samuel a écrit:
«La version 2.1.7 est problématique puisque les écritures sur disque sont effectués à même le thread audio (ouch). J'avais mal lu la documentation de JUCE et je croyais que les écritures étaient asynchrones par défaut, mais ce n'est visiblement pas le cas. Le processing audio se retrouve donc à attendre (parfois très longtemps) après le disque dur, et ça coupe coupe coupe.
Il y a une chose importante à clarifier : y a-t-il eu des glitchs audio à un autre moment qu'à l'enregistrement ?»
J'ai déplacé ton commentaire ici car il concerne plutôt l'enregistrement. Il y a deux issues en ce moment par rapport à la distorsion. Celle de Mélanie #223 qui semble toucher à Live uniquement et celle-ci- qui a trait à l'enregistrement en général. Du côté de 223, on investigue différentes causes possibles, du côté matériel notamment.
V217, BlackHole 0.2.8, DP10.13, Live 10.
Pour répondre à la question, aucun problème de glitch ou de coupure audio de mon côté, tant et aussi longtemps que je ne touche pas à l'enregistrement.

**Comment by NicolaGiannini** [comment]
V217, BlackHole 0.2.8, Logic 10.5.1

Je confirme ce que Robert dit aussi pour Logic 10.5.1 : aucun problème de glitch ou de coupure audio de mon côté, tant et aussi longtemps que je ne touche pas à l'enregistrement.

**Comment by Normandeau** [comment]
V218
**Dome et Stereo, AIFF**
Interleaved ou Multiple mono semblent bien fonctionner, au moins sur des enregistrements très courts.
**Binaural**
Très problématique en Interleaved: il enregistre les 16 haut-parleurs, plutôt que juste la sortie binaurale. En fait, il n'y a du signal que dans deux des 16 pistes, les 14 autres sont vides.
En Multiple Mono, tout est ok.
**Dome et Cube, Wave**
Interleaved: ça crashe à tous les coups, aussitôt que j'appuie sur Record.
**Stereo, Wave**
Interleaved: Ok
**Binaural, Wave**
Très problématique en Interleaved: il enregistre les 16 haut-parleurs, plutôt que juste la sortie binaurale. En fait, il y a bien du signal dans les pistes 1 et 2, mais aussi de la distorsion numérique maximale dans le canal droit de la piste 9 et dans les deux canaux de la piste 16:
![Capture d’écran, le 2021-03-05 à 13 19 00](https://user-images.githubusercontent.com/8959779/110157006-ac684800-7db5-11eb-95e6-f35bb5971686.jpg)

**Comment by NicolaGiannini** [comment]
V218
Dans mon cas j’obtiens des comportements similaires à ceux observés par Robert. Dans mon cas, il ne semble pas y avoir de différence entre Wave et Aiff.

**STEREO**, Wave, Aiff, Multiple Mono et interleaved : OK

**Binaural**, Aiff et Wave
Multiple mono: OK
Interleaved : il enregistre les 16 haut-parleurs, plutôt que juste la sortie binaurale. En fait, il y a bien du signal dans les pistes 1 et 2, mais aussi de la distorsion numérique maximale dans presque toutes les autres pistes.
![Schermata 2021-03-05 alle 13 33 55](https://user-images.githubusercontent.com/35705913/110159671-03235100-7db9-11eb-9b15-cba59cf86bb4.jpg)

**Dome et Cube**, Aiff et Wave

Interleaved: ça crashe à tous les coups, aussitôt que j'appuie sur Record.
Multiple mono : OK

**Comment by Normandeau** [comment]
J'ai reçu à quelque reprise ce message d'erreur en enregistrant un fichier stéréo (multiple mono) en mode STEREO. Je n'avais jamais vu ce message auparavant. C'est étonnant, parce qu'en fait, il est erroné. Il me dit qu'il va effacer le fichier que je vient de lui demander d'enregistrer! Il n'y avait aucun fichier qui portait ce nom sur le disque avant que je lance Recording. Puisque je suis en mode Multiple Mono, c'est comme s'il enregistrait le fichier .001 et qu'il devait ensuite l'effacer pour enregistrer le fichier .002?
PS Ce n'est pas systématique, mais ce message est apparu à quelque reprises pendant une session de travail.

![Error message quand on enregistre](https://user-images.githubusercontent.com/8959779/112195776-b45f1f00-8be0-11eb-8878-7e14aa3ba5dc.jpg)

**Comment by Normandeau** [comment]
V219
- Premier commentaire: on ne peut plus enregistrer en aiff. Seulement en wav, soit la valeur par défaut.
- Second commentaire, on ne peut plus enregistrer les sorties directes en STEREO et en BINAURAL (voir issue #242 ).
- Troisième commentaire: enregistré de courtes séquences en multi, interleved ou mono, et en stereo: aucun problème détecté.
- Quatrième commentaire: enregistré avec succès un pièce de 16'20 en mode interleaved en wav. Fichier de 3,4 Gb. Je ne peux pas comparer en aiff pour le moment.
- On attend la version aiff et éventuellement CAF et Wave64.

**Comment by NicolaGiannini** [comment]
J'ai vu qu’on peut enregistrer en aiff si on ajoute l'extension .aiff au nom du fichier dans la fenêtre Start Recording ou dans la fenêtre Save as. Cela dit, peut-être que c'est plus pratique d'avoir un menu pour ce choix ?

Je confirme tout le reste.

**Comment by Normandeau** [comment]
J'avais essayé aif! Dans la très grande majorité des milliers de fichier audio que j'ai sur mon Mac, c'est .aif qui est utilisée comme extension de fichier. Oui un menu serait plus pratique.

**Comment by SamuelBeland** [comment]
Je note l'ajout du menu.

Par curiosité, je me demande dans quel scénario quelqu'un voudrait avoir des sorties directes dans un setup STEREO ou BINAURAL?

**Comment by Normandeau** [comment]
Réponse simple: **TOUS les scénarios** où des sorties directes sont utilisées.
Les sorties directes sont utilisées pour répondre à deux fonctions:
1) haut-parleur unique à qui on envoie un signal dédié: typiquement les subs, mais aussi des hp solos dans un dôme par exemple. Ou sur des dispositifs originaux comme celui qu'expérimente en ce moment Nicola à Sporobole. Très utile dans une galerie d'art par exemple.
2) un haut-parleur faisant partie du dôme à qui on envoie un signal unique en plus de la spatialisation (nouvelle fonction, grâce à toi). Le hp reçoit donc une somme d'un ou plusieurs signaux.
En tout état de cause, la panoramisation gauche-droite doit être prise en charge, en STEREO et en BINAURAL, pour les sorties directes comme pour les autres hp. On a vu déjà que ceci est un problème majeur, voir issue #242

**Comment by NicolaGiannini** [comment]
Je suis d'accord avec Robert.
Dans l'idéal, surtout dans le mode BINAURAL, il pourrait être pratique que la position de sorties directes soit prise en charge comme cela se passe pour les sorties qui font partie de la spatialisation.

**Comment by Normandeau** [comment]
De plus la fenêtre qui s'ouvre lors de l’enregistrement est trop petite. Idéalement elle devrait s'ajuster au chemin ouvert. Sinon, il faut soit pouvoir l'agrandir ou la designer plus grande. Pour le moment on ne peut même pas circuler dedans afin d'aller mettre la bonne extension de fichier.

![Start Recording trop petite](https://user-images.githubusercontent.com/8959779/119576248-5ee0f300-bd86-11eb-81e0-0483ad7eb0f8.jpg)

**Comment by Normandeau** [comment]
V2110
Speaker Setup du B187, avec sorties directes 5-6 et ensuite 31-61.
SpatGRIS en mode Stereo, Recording AIFF et Interleaved.
Ça crashe à tous les coups. Après discussions avec Samuel, on s'attendait un peu.

**Comment by NicolaGiannini** [comment]
Je confirme. 
Dans le cas du B187, si on met comme sorties directes 1-2 ça fonctionne.

**Comment by Normandeau** [comment]
V2111
Testé un enregistrement AIFF Interleaved de 15'27 sur 24 canaux (Icosa). Le fichier fait 3.21Gb et le son s'arrête au bout de 10' environ. Ce problème, déjà décrit, persiste donc:

![Capture d’écran, le 2021-06-20 à 16 36 10](https://user-images.githubusercontent.com/8959779/122687676-a328ad00-d1e5-11eb-93b2-11911d8963cc.jpg)

Testé ensuite un enregistrement WAV Interleaved de 10'24 sur 34 canaux (B187). Le fichier fait 3.1Gb. Tout est là.

Pourtant la limite est de 4Gb pour les deux formats. Pourquoi le son s'arrête=t=il après 10 minutes en AIFF?

**Comment by Normandeau** [comment]
Suite des tests d'enregistrement.
Malgré ce qui est généralement écrit, il semble que le format AIFF soit limité à 2Gb:
«The practical file size limit is 2 GB in many player applications due to their interpretation of the file size header. This also applies to 24-bit and 32-bit files where those bit depths are valid» 
https://manual.audacityteam.org/man/export_formats_supported_by_audacity.html 

J'ai testé avec le dispositif suivant:
- DP 56 24 sorties dans Blackhole, durée du fichier 15'27 (le même qu'hier)
- Twistedwave avec Blackhole en entrée, 24 Inputs
- Enregistrement d'un fichier 24 pistes interfolié (2448).
 
Résultats: 
- WAV: pas de problème, grosseur du fichier: 3,19Gb
- AIFF: TW me dit qu'il ne peut pas enregistrer le fichier au format AIFF car il est trop gros!
- CAF: pas de problème, grosseur du fichier: 3,19Gb

Il faudra donc ajouter le format CAF et mettre une note dans le manuel au sujet de AIFF.

**Comment by Normandeau** [comment]
V2112
Il y a tellement de choses dans cette issue qui ont été résolues, que je la ferme. Et j'en ouvre une autre qui ne concerne que la taille du fichier AIFF, qui semble être un bogue.
