### ISSUE TITLE
Menu File, Load speaker setup dans Ressources et menus Templates

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#220]
V216
Lorsqu'on ouvre SpatGRIS2 pour la première fois, il nous est proposé:
- un default_speaker_setup
- un default_preset

Ces deux documents ne sont ensuite plus accessibles par défaut, à moins de les avoir soigneusement conservé quelque part où on s'en souvienne.
Mon expérience, c'est que les utilisateurs ne se rendent pas compte, au moment de l'installation, qu'il y a un dossier avec SpatGRIS2 qui se nomme Templates. Et ils ne l’installent pas. Ce serait bien que le futur installeur s'occupe de cela, et installe un dossier GRIS_Templates dans le dossier Document de l'utilisateur. C'est ce que font la plupart des logiciels audio.

**Comment by Normandeau** [comment]
V219
Quand ou ouvre Load Speaker Setup pour la première fois, on ouvre le dossier Ressources de SpatGRIS. Pas  certain que c'est une bonne idée de laisser les utilisateurs fouiller là-dedans...

**Comment by Normandeau** [comment]
V2111
On ouvre toujours le dossier Ressources de SpatGRIS quand on ouvre Load Speaker Setup ou Load Preset pour la première fois. On ne devrait pas indiquer ce chemin à l'utilisateur.
Quant au default_speaker_setup, on devrait tout simplement le fournir dans les templates, en le bloquant, pour qu'il ne puisse pas être altéré.

**Comment by NicolaGiannini** [comment]
V2111
Je confirme.

**Comment by Normandeau** [comment]
V2112
Pas de changement ici.

**Comment by Normandeau** [comment]
V2113
Bravo pour l'ajout du menu Template. Mais quand on fait Load Speaker Setup, on ouvre toujours le dossiers Ressources de l'application, la première fois tout au moins. Par la suite, il se souvient du dernier dossier qu'on a ouvert (des fois oui, des fois non en fait...). Mais je pense que c'est justement la première fois que c'est critique. Est-ce qu'on ne pourrait pas mettre une valeur par défaut, genre:
~/Documents

Même commentaire pour Open Project. Sauf qu'il n'y a pas de template ici. Je pense qu'il faudrait en fournir. Je mets un homme là-dessus...

![Dossier ressources](https://user-images.githubusercontent.com/8959779/124330613-cd6e5900-db5b-11eb-8f12-cf2d63387434.jpg)

**Comment by SamuelBeland** [comment]
Ha zut, j'ai fais la correction pour les save mais pas pour les load!

Aussi, je crois que l'on pourrait donner des meilleurs noms aux templates. "GRISpeaker Dome..." n'est plus vraiment nécessaire maintenant que l'on est dans la section speaker setup->templates->dome->...

**Comment by Normandeau** [comment]
Bien d'accord pour raccourcir les noms des speaker setups. D'ailleurs, le fait que le mode de ceux-ci soit automatiquement détecté par SpatGRIS permettrait à la limite de ne plus utiliser Dome ou Cube dans leurs noms. Mais je n'irais pas jusque là! Donc je vais préparer un nouveau dossier Templates. Si vous avez des dispositifs à ajouter à ceux existants, envoyez-les moi.

**Comment by Normandeau** [comment]
Suggestion au sujet du menu Templates. Actuellement, le menu File est divisé en trois sections: Project, Speaker et Settings (c'est très clair):

![File Menu](https://user-images.githubusercontent.com/8959779/124362880-dd427780-dc05-11eb-842d-cd1a5bea7b7e.jpg)

Samuel vient d'ajouter un menu Templates dans Speaker, subdivisé ensuite entre dome et cube. Peut-être mettre des majuscules: Dome et Cube.
Ensuite, ajouter aussi un menu Templates dans Project. J'en ai fabriqué vraiment beaucoup, avec toutes les couleurs qu'il faut. Ça peut vraiment rendre service, surtout qu'il semble que la gestion des couleurs est toujours problématique dans Juce.

**Comment by Normandeau** [comment]
Question:
Y a-t-il une raison pour laquelle on **Open** Project et on **Load** Speaker Setup?
Pourquoi pas **Open** partout?

**Comment by Normandeau** [comment]
Le Save As à partir des setups du menu Templates ne fonctionne pas. Le nom du setup qu'on veut sauver devrait apparaître ici:

![Capture d’écran, le 2021-07-03 à 15 32 21](https://user-images.githubusercontent.com/8959779/124365113-f05c4400-dc13-11eb-8be7-38ebadecce23.jpg)

**Comment by Normandeau** [comment]
Pourquoi les setups dans le Templates sont dans n'importe quel ordre? L'ordre alphabétique pourrait être un meilleur choix, non?

![Capture d’écran, le 2021-07-03 à 15 42 27](https://user-images.githubusercontent.com/8959779/124365362-77f68280-dc15-11eb-85fa-0b9339407ae2.jpg)

**Comment by Normandeau** [comment]
V2113
Pas de raccourcis claviers pour les nouveaux menus: Save Speaker et Save Speaker As... On a déjà utilisé les standards Mac pour les projets (Cmd-S et Cmd-Maj-S). Je propose:
• Save Speaker Setup: Cmd-E (E pour Edition)
• Save Speaker Setup As: Cmd-Maj-E

**Comment by MelanieFrisoli** [comment]
Bonne idée ! 
je seconde.

**Comment by MelanieFrisoli** [comment]
V2114
Les noms de templates sont dans bien dans l'ordre alphanumérique.
Est-ce que c'est normal que certains templates s'appellent juste "96" ou "128" ? C'est un peu sec, non ? ;)

![Screen Shot 2021-07-15 at 5 24 08 PM](https://user-images.githubusercontent.com/74631914/125859676-beb55fff-ad24-4ab2-9ac5-4a9be078863a.JPG)

**Comment by MelanieFrisoli** [comment]
V2114
Les raccourcis pour "Save Speaker Setup" et "Save Speaker Setup As..." apparaissent bien.
Par contre quand je fais Cmd + E ou Cmd + Shift + E sur un template, le résultat est le même (ouverture d'une fenêtre comme "Save as" pour choisir l'emplacement). 
Deux-trois questions : 
Est-ce qu'on peut permettre à l'utilisateur de modifier les templates ? Ou est-ce vraiment trop "dangereux" ?
Est-ce que si on ne permet pas la modification des templates on pourrait griser "Save Speaker Setup" pour montrer plus clairement qu'ils sont protégés en écriture ? 

sinon tout fonctionne bien sur un Speaker Setup chargé à partir de la commande "Open Speaker Setup"

**Comment by MelanieFrisoli** [comment]
V2114
Effectivement, quand on clique sur "Open Speaker Setup" on n'est pas amené dans le dossier "Ressources".
Chez moi, SpatGRIS m'emmène dans mon dossier "Documents".

**Comment by Normandeau** [comment]
• C'est pour cela que tu n'as pas Save avec un Template: ils ne sont pas modifiables. À moins de les renommer ailleurs. Donc Save et Save As conduisent à la même action.
• Les Templates fournis ici ne sont pas les bons. Je les ai tous refaits — ils ont tous changé de noms et le mot SpatGRIS n'en fait plus partie, juste DOME ou CUBE et pour les projets, PROJECTS — mais Samuel était parti en vacances. On mettra tout cela ensemble avec le manuel lorsqu'il sera corrigé.
• Open Speaker (au lieu de Load) et Save As sont maintenant conformes.
• Les Templates sont en ordre
• Save Speaker Setup et Save Speaker Setup As ont des raccourcis clavier
• Dome et Cube ont des majuscules
• Open n'ouvre plus le dossier Ressources de SpatGRIS
Beaucoup de choses réglées ici. Va falloir que je refasse toutes mes saisies d'écran maintenant!

**Comment by MelanieFrisoli** [comment]
Idée alors pour une version future : Permettre à l'utilisateur de créer ses propres templates qui apparaisseraient dans ledit menu ? (plus rapide à ouvrir)
On pourrait ajouter un nouveau choix "Save Speaker Setup as Template"  (avec Cmd + T) :)
