### ISSUE TITLE
Bogue de connexion audio après redémarrage de SpatGRIS2

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#222]
V216
Comme on l'a décrit dans l'issue #218, les Preferences de SpatGRIS ne sont pas toutes prises en charge après les avoir sauvegardées. Il faut donc parfois redémarrer SpatGRIS2 après avoir changées certaines d'entre elles (la Fe notamment). Or après le redémarrage, la connexion audio avec le séquenceur est perdue, du moins avec DP. Autrement dit, si on laisse DP ouvert au moment où on ferme et redémarre SpatGRIS2, DP perd la connexion avec BlackHole. Même si DP offre la reconnexion, cela n'est pas possible et il demeure silencieux. Il faut alors tout quitter et tout repartir.
Il faudrait vérifier cela avec les autres séquenceurs: Logic, Live et Reaper.
En résumé, en date d'aujourd'hui et en fonction des multiples bogues mis au jour récemment, de deux choses l'une:
- ou les bogues sont réglés;
- ou on remet le fenêtre d’avertissement qui dit qu'il faut redémarrer les logiciels après un changement dans les préférences.
 
Ce serait dommage, car l'aspect dynamique des changements étaient bienvenus dans la chaîne de connexion.

**Comment by Normandeau** [comment]
Je signale ceci en passant. SpatGRIS2 est maintenant dynamique avec la Fe. Si elle est réglée à 48kHz et qu'on ouvre un projet à 44,1kHz, il s'ajuste automatiquement. Mais cette valeur n'est pas conservée comme une préférence, comme c'est le cas dans les séquenceurs. Ces derniers se souviennent toujours de la dernières Fe utilisée. Pas SpatGRIS2. Si on referme le tout, la prochaine fois qu'on va l'ouvrir (en fonction de cet exemple) il va se mettre à 48kHz. Cela signifie qu'après l'avoir ouvert, il faut ouvrir les Preferences, remettre la Fe à 44,1kHz, Save et fermer SpatGRIS2 et le rouvrir.
C'est un peu trompeur et cela peut mener à des erreurs de manipulation de la part des utilisateurs.

**Comment by devinroth** [comment]
This might be BlackHole related. It sounds like similar to a bug I fixed in BlackHole 0.2.8. Try this and see if it fixes the issue.

https://www.dropbox.com/s/yh703sti9iofxg8/BlackHole128ch.v0.2.8.pkg?dl=0


Devin Roth

**Comment by Normandeau** [comment]
Thanks Devin, But isn't this version is the one we currently use? Or did you change anything in it? It has the number: 0.2.8.

**Comment by devinroth** [comment]
I thought you were using 0.2.7.

Devin Roth

**Comment by MelanieFrisoli** [comment]
Hello,
J'ai fait quelques tests dans Live 10:

* En effet maintenant SpatGris est maître au niveau de la Fe. Si je la change dans SpatGris elle est automatiquement changée dans les préférences de Live.
* Par contre, après avoir réglé la Fe dans SpatGris à 44,1KHz, je l'ai fermé et rouvert. Là, il s'est ouvert à 48kHz mais ne communique effectivement plus avec Live (la Fe de Live, qui est resté ouvert pendant ce temps, est toujours à 44,1KHz et il n'y a plus de son). Aussi SpatGris n'a pas non plus gardé en mémoire les entrées et sorties audio.
* J'ai donc fermé et ouvert Live à nouveau. L'audio se rend bien dans SpatGris mais ma Fe dans Live est restée sur son dernier réglage de Fe, soit 44,1KHz (alors que SpatGris est à 48KHz)
*

**Comment by NicolaGiannini** [comment]
V216 et V217 macOS 10.14.6
Logic 10.5.1 
Dans Logic je n’ai pas ce problème parce que Logic est toujours le master. Si j’ai Logic et SpatGRIS2 ouverts et que je change la Fe de SpatGRIS2, la Fe reste celle indiquée par Logic. 
Si je ferme et je rouvre SpatGRIS2 je ne perds pas la connexion audio avec BlackHole, même si  j’ai essayé de changer la Fe (mais je ne peux la pas changer à partir de SpatGRIS2 parce que Logic est toujours le master).

V217 et Reaper

Dans Reaper c’est SpatGRIS2 qui est toujours le master. Si je change la Fe à partir de Reaper, la Fe reste celle indiquée par SpatGRIS2. Si je change la Fe à partir de SpatGRIS2, la Fe change dans les deux. La connexion audio entre Reaper et SpatGRIS via BlackHole semble toujours être active, même si je redémarre SpatGRIS2 en changeant la Fe.

Version 217 testée avec BlackHole 0.2.8

**Comment by Normandeau** [comment]
V217, BlackHole 0.2.7
DP et SpatGRIS
SpatGRIS et DP ouvert à 44,1kHz. Je ferme SpatGRIS et je le rouvre.  Après le redémarrage, la connexion audio avec le séquenceur est perdue, du moins avec DP. Autrement dit, si on laisse DP ouvert au moment où on ferme et redémarre SpatGRIS2, DP perd la connexion avec BlackHole. Même si DP offre la reconnexion, cela n'est pas possible et il demeure silencieux. Il faut alors tout quitter et tout redémarrer. Dans le cas de cet exemple, au moment de quitter SpatGRIS a crashé.
En fait je ne sais pas si c'est un problème majeur. En situation réelle de travail, on ne change pas à tout bout de champ la Fe et on ne fait pas exprès de fermer et d'ouvrir SpatGRIS pensant qu'un séquenceur reste ouvert. On voit qu'on a des situations différences selon ces derniers. Ici avec la version 217, la préférence de Fe est gardée, et c'était le bogue initialement décrit.

**Comment by NicolaGiannini** [comment]
Robert : 

> Dans le cas de cet exemple, au moment de quitter SpatGRIS a crashé.

J'ai remarqué des crash lors de la fermeture de SpatGRIS2. Il me semble que ces crash sont liés à des changements dans les "Settings", notamment de Fe et de Buffer Size, mais dans mon cas je ne suis pas encore arrivé à trouver une séquence d'actions que donne lieu toujours à un crash. 
Cela se produit dans V216 et V217.

**Comment by Normandeau** [comment]
Je vais ajouter une note dans la manuel: «Don't play with your food».

**Comment by Normandeau** [comment]
V2112
Réglé. SpatGRIS se reconnecte dès son ouverture.
