### ISSUE TITLE
Glitchs et coupures audio

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#223]
V216
En travaillant, je me rends compte que j'ai des coupures intermittentes pendant le lecture. Le son saute, souvent quand je suis en train de faire des tâches assez basiques comme ajuster une EQ ou ouvrir un plugin. 
Est-ce que ça vous arrive parfois aussi? 
Mon CPU ne monte que jusqu'à 25% dans Live pourtant. La F.e. et la Buffer Size sont les mêmes dans SPATGRIS et dans Live (48KHz et 512 Samples).

**Comment by SamuelBeland** [comment]
Il n'y a normalement aucun glitch audio.

- Est-ce que c'est quelque chose qui t'arrivait occasionnellement dans Live sans utiliser ControlGRIS ou SpatGRIS ?
- Est-ce que ça arrive aussi lorsque tu n'est pas en train d'éditer un plugin ?
- Les coupures sont-elles des clics très courts ou carrément une seconde de silence ?

**Comment by Normandeau** [comment]
On a regardé cela de plus près hier. Ce sont carrément des coupures audio. Pas certain que c'est relié à nos outils, mais c'est surprenant dans Live. Le projet comportait environ 60 pistes, avec quelques automations. Pas de quoi dévisser ControlGRIS. Et les deux logiciels fonctionnaient en bas de 20%.
Je sais que c'est probablement tune pratique d'un autre âge (le mien), mais je travaille toujours mes projets sur un disque dur externe, jamais sur le disque de mon Mac. Cela vient de l'époque où les ordis n’étaient pas assez puissant pour assumer l'OS et le flux audio. Avec ProTools HD par exemple, on n'avait pas le choix de travailler avec un disque externe certifié pour sa vitesse. Alors Mélanie va tester son projet sur un disque externe pour voir si ça fait une différence.

**Comment by MelanieFrisoli** [comment]
En effet, comme dit Robert, ce sont des coupures audio, très courtes et successives qui semblent arriver de manière aléatoire. Je poursuis des tests très vite (notamment avec le disque dur externe) et vous tiendrai informés! 
Aussi, je passe à Live 11 la semaine prochaine et je ferai à nouveau des tests. 
À très vite!

**Comment by NicolaGiannini** [comment]
Salut Mélanie !
Cela se produit-il lors de la lecture des automations de ControlGRIS ? 
Le monitoring de l'activité du disque dur dans Ableton indique-t-elle quelque chose ?

**Comment by MelanieFrisoli** [comment]
Allo Nicola,

En fait ça a l'air d'être assez aléatoire, on a fait des tests avec Robert. Et pas d'overload pour le disque dur et mon CPU tourne autour de 20%. Je refais des tests aujourd'hui et demain.

**Comment by NicolaGiannini** [comment]
Je viens de remarquer quelques coupures audio. Ce sont des cas très rares. Cela m'est arrivé pendant l'enregistrement d'un fichier interfolié à 62 canaux à partir d’une session de Logic à 92 pistes de 16 minutes.
SpatGRIS2 affiche une consommation de CPU de 10%, le moniteur d’activité affiche 122%.

La même pièce entendue sans l’enregistrement en arrière-plan apparemment ne présente pas de coupures audio, mais je vais tester davantage.

Testé avec BlackHole 0.2.8.

**Comment by Normandeau** [comment]
V217, BlackHole 0.2.8
Glitches
J'ai beaucoup de glitches au moment de l'enregistrement.

Je fais un autre test en mode DOME et Multiple mono, c'est pareil, ca glitche et l'audio est interrompu régulièrement. Et en plus, j'obtiens 36 fichiers vides numérotés de 000 à 035...

**Comment by Normandeau** [comment]
Retour à V216 BlackHole 0.2.8
Séance d'enregistrement type afin de passer de la version multiphonique originale à une version stéréo «potable»:
Étape 1
DP 56 pistes Session de 15'20 -> SpatGRIS DOME 36hp -> Multiple Mono AIFF
Étape 2
DP 36 pistes -> SpatGRIS STEREO -> Multiple Mono AIFF
Aucun problème de glitch, ni de coupures audio.

**Comment by MelanieFrisoli** [comment]
BlackHole 0.2.8 / SpatGRIS V217
Test chez moi en mode binaural. 
Peu de coupures audio dans ma session Live habituel en travaillant sur le disque dur interne.
Plus de coupure du tout en travaillant sur le disque dur externe.
À confirmer en studio car je n'aurai pas la même interface audio (le problème de coupures audio pourrait venir de là aussi) et que je ne travaillerai pas en binaural.
Dans le moniteur d'activités, Live montait parfois à 110% du CPU.

**Comment by MelanieFrisoli** [comment]
De retour au studio Hexa où j'ai mes petites habitudes et surtout où j'avais fait l'expérience de pas mal de coupures audio.
En travaillant sur un disque dur externe, au bout de 3h de travail, je n'ai eu aucune coupure ! Merci Robert!
(J'utilise en ce moment SpatGRIS 2.1.6 et la dernière version de BlackHole)

**Comment by MelanieFrisoli** [comment]
Nouvelle journée, mes settings sont les mêmes et beaucoup de coupure en travaillant sur ma session (sur un disque dur externe).

**Comment by Normandeau** [comment]
Donc avec BlackHole 0.2.8 et SpatGRIS216?
Idéalement, il faudrait tester différentes combinaisons:
- Avec BlackHole 0.2.7 et SpatGRIS216.
- Avec BlackHole 0.2.7 et SpatGRIS217
- Avec BlackHole 0.2.8 et SpatGRIS217?
(J'ai mis l'ordre des changements avec un seul changement à la fois)

Je sais, c'est du boulot, mais c'est seulement comme cela qu'on peut savoir si c'est l'un ou l'autre des logiciels, ou la combinaison des deux.
Ou ta machine... ou Live... ou la combinaison des deux!
Personnellement j'ai dû réinitialiser mon disque dur interne en janvier...
Pas le fun, mais ça va mieux depuis.
Combien de d'espace disque disponible sur ton disque interne? Au moins 10%?
Est-ce que tu mets ton ordi à off de temps en temps?
Toutes les combinaisons ci-haut-mentionnées ne génèrent aucun problème sur ma machine avec DP 10.13.
Le seul problème que je rencontre est pendant l'enregistrement.

**Comment by MelanieFrisoli** [comment]
Allo Robert,

Oui je vais tester le différentes combinaisons :) (en ce moment c'est bien BlackHole 0.2.8 et SpatGRIS216)
Est-ce qu'il est possible cependant que la version de Blackhole ait effacé la précédente?)

En attendant, oui mon disque interne a plus de 10% disponible. En fait je m'assure pour qu'il ait toujours au moins 30% pour fonctionner correctement.
J'éteins mon ordi quasiment toutes les nuits.
Live est à 30% de CPU. 
Je fais le suivi dès que j'ai fait les autres essais. 
À tout à l'heure!

**Comment by Normandeau** [comment]
Oui une nouvelle installation de BlackHole efface la précédente, car elles ont le même nom.
Fait un test rapide avec Live 10.1.30, BlackHole 0.2.8 et SpatGRIS 217.
4 pistes stéréo, avec ControGRIS, trajectoires automatisées dans tous les sens.
Aucun problème audio, ni en enregistrement des trajectoires, ni dans leur reproduction.

![Capture d’écran, le 2021-02-25 à 12 16 27](https://user-images.githubusercontent.com/8959779/109190884-94644900-7763-11eb-8fb5-7fa9d5a4cc69.jpg)

**Comment by MelanieFrisoli** [comment]
Oui, je vais essayer ça (mais pour l'instant je suis au Colloquium :)

**Comment by SamuelBeland** [comment]
La version 2.1.7 est problématique puisque les écritures sur disque sont effectués à même le thread audio (ouch). J'avais mal lu la documentation de JUCE et je croyais que les écritures étaient asynchrones par défaut, mais ce n'est visiblement pas le cas. Le processing audio se retrouve donc à attendre (parfois très longtemps) après le disque dur, et ça coupe coupe coupe.

Il y a une chose importante à clarifier : y a-t-il eu des glitchs audio à un autre moment qu'à l'enregistrement ?

**Comment by MelanieFrisoli** [comment]
Quelques nouvelles de mes petites coupures audio? ;)​
hier dans le studio hexa:
- Interface audio branchée directement dans l'ordi​ (et plus dans le hub USB)
- Driver à jour (Total Mix v.1.64)
- Flash update faite (Firmware v40 / Driver v3.19)​​

Et... toujours des coupures.​

Par contre ça n'a absolument rien à voir avec le SpatGRIS (ce qui paraissait assez évident mais c'est maintenant confirmé), j'ai ouvert une session assez grosse d'une production que je fais pour une chanteuse et j'ai des coupures aussi. 
Par contre, chez moi avec le même projet je n'ai aucune coupure, j'en conclus donc qu'il y a sûrement quelque chose dans l'hexa qui ne fonctionne pas avec mon set up...

À suivre...

**Comment by Normandeau** [comment]
Bonne nouvelle pour SpatGRIS, moins bonne pour toi!
Premier commentaire: le driver à jour de la RME UFX (celle d'Hexa) est le 320 (et non pas le 319). Est-ce que ça peut faire une différence, à suivre. Le firmware ne semble pas le bon non plus. La dernière mise à jour date du 22 février et elle installe les versions suivantes: Update to version, Fireface UFX: USB 360, DSP 163, FW 344, Class Compliant 28. Je passerai au studio faire les mises à jour avant ta prochaine période.
Dernier test pour toi: tester avec juste ton ordi, sans écran externe. Les écrans Dell du Studio ne sont pas nécessairement compatible Mac ou avec tous les Mac. Je sais c'est étrange, mais j'ai cette marque d'écran à la maison et au studio et ils ne sont pas tout compatibles. En se mettant en veille par exemple, ils m'ont abimé deux disques durs, dont un Time Machine.
En tout état de cause comme cette issue semble relié à ta machine et non pas à nos outils, je la ferme.

**Comment by NicolaGiannini** [comment]
Allô Mélanie,
une autre chose que tu pourrais vérifier est si tu as des coupures lorsque ton ordi est branché à l’électricité ou pas. Je viens de parler avec Christophe, et on avait eu des problèmes similaires dans l'Hexa. On avait réglé cela en branchant l’ordi à l’électricité. Tu pourrais essayer si dans ton cas, cela change quelque chose.

**Comment by Normandeau** [comment]
Déjà testé. Merci.
