### ISSUE TITLE
SpatGRIS2 ne rappelle pas le dernier speaker setup DOME ou CUBE si on ferme le logiciel en mode STEREO ou Binaural.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#225]
V217
SpatGRIS2 ne rappelle pas le dernier speaker setup DOME ou CUBE si on ferme le logiciel en mode STEREO ou Binaural.

J'ouvre un speaker setup DOME. 
Je passe au mode STEREO ou BINAURAL.
Je ferme SpatGRIS2.
J'ouvre SpatGRIS2.
Je passe au mode DOME.
Ce pop-up est affiché : Cannot find file, the current setup will be kept.

Il faut donc rouvrir le speaker setup DOME  à partir de la fenêtre “File”.

Je ne sais pas si le comportement peut avoir un lien avec le issue https://github.com/GRIS-UdeM/ServerGRIS/issues/220

![Error](https://user-images.githubusercontent.com/35705913/108608994-c0b14b80-7398-11eb-9cdc-5132978d7345.jpg)

**Comment by Normandeau** [comment]
En fait, c'est même pire: on reste bloqué en mode STEREO ou BINAURAL. Pour l'utilisateur moyen, c'est comme la fin de sa session! Et quand on utilise la fonction Load Speaker Setup, on ouvre le contenu de SpatGRIS2 et on tombe sur les Ressources de l’application où est situé le default_speaker_setup. Je ne crois pas que ce soit une bonne idée!!!

**Comment by Normandeau** [comment]
V118
Ça semble réglé. Je laisse Nicola confirmer.

**Comment by NicolaGiannini** [comment]
Ça semble réglé pour moi aussi.
