### ISSUE TITLE
Incohérence du haut-parleur affiché selon l'endroit où il est sélectionné

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#226]
V217
Ce n'est pas du tout un bug, mais maintenant pour mettre en évidence un haut-parleur sélectionné dans la fenêtre 3D, la fenêtre "Speaker Setup Edition" doit être active.

Si je travaille dans la fenêtre "Speaker Setup Edition" et que j'ai sélectionné un HP dans la fenêtre, le bon HP est mis en évidence dans la fenêtre "Speaker Setup Edition" et dans la fenêtre 3D.

Si je sélectionne un HP dans la fenêtre 3D, pour que le bon haut-parleur soit mis en évidence aussi dans la fenêtre "Speaker Setup Edition", je dois activer la fenêtre "Speaker Setup Edition" en la touchant.
C'est vraiment un détail, mais il pourrait être pratique d'avoir la mise à jour visuelle automatique.

Voir la vidéo : 

https://user-images.githubusercontent.com/35705913/108610021-408ee400-73a0-11eb-96c2-7f9de53715fb.mov

**Comment by Normandeau** [comment]
Sélection des hp, infos supplémentaires.
Il y a trois endroits où on peut sélectionner les hp, mais il y en a un seul qui soit toujours synchronisé avec les deux autres:
- Speaker Setup Edition: ici quand on sélectionne un hp, c'est le bon qui est sélectionné partout.
- Fenêtre 3D: quand on sélectionne ici,  c'est correct dans Outputs, mais comme l'a mentionné Nicola, il faut activer Speaker Setup Edition par la barre des menus pour que le changement s'opère là.
- Outputs: ici ça semble purement aléatoire. Voici ce que ça donne après avoir sélectionné le output no 20, c'est le 9 qui a été sélectionné dans les deux autres fenêtres. Impossible de prévoir le résultat!

![Capture d’écran, le 2021-02-22 à 17 01 23](https://user-images.githubusercontent.com/8959779/108775926-b37a9500-752f-11eb-831e-a066d4867d0b.jpg)

**Comment by Normandeau** [comment]
V218
Clicking on a speaker [output patch] in the main window now selects the right speaker in the speaker setup window
Aucun changement.
Par contre, quand on sélectionne un hp par son numéro dans les Outputs, là ça fonctionne partout.
Question: est-ce qu'on a vraiment besoin d'avoir trois points de sélection à synchroniser? 
En fait, même si ça fonctionne actuellement par les Outputs, moi je ne me sers jamais de cela. Quand j'ai besoin de sélectionner un hp et de voir mon choix s'afficher, c'est soit dans la fenêtre 3D ou dans la fenêtre Speakers Setup Edition réciproquement.

**Comment by SamuelBeland** [comment]
Oups, j'ai oublié de tester ce fix dans MacOS !

Je pense que l'important était effectivement de régler les sélections aléatoires dans la fenêtre principale, mais est-ce que ça peut être un problème sérieux de ne pas voir les sélections se mettre à jour lorsqu'on construit un speaker setup ?

**Comment by Normandeau** [comment]
Oui c'est un problème. Regarde ceci. Je sélectionne le hp 21 (d'ailleurs est-ce qu'on peut avoir une meilleure résolution graphique des chiffres ici?) dans la fenêtre 3D et sans trop prêter attention, je pense qu'il est automatiquement sélectionné dans la fenêtre des données, alors je me met à éditer le hp sélectionné. Et quel est le hp que j'édite en réalité? Le hp 27! Frustrant:

![Capture d’écran, le 2021-03-05 à 11 16 14](https://user-images.githubusercontent.com/8959779/110142727-78d0f200-7da4-11eb-963b-eea84c00be5c.jpg)

**Comment by NicolaGiannini** [comment]
Je pense aussi qu'il est important d'avoir une réprocité entre la fenêtre de données et la fenêtre 3D.

**Comment by Normandeau** [comment]
V219
Problème réglé. C'est cohérent partout.
