### ISSUE TITLE
Touches de raccourci pour les Settings 

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#227]
Allo! 
Une simple question pratique:
Dans la plupart des logiciels, l'accès aux Préférences se fait par le raccourci Cmd + , (ou Ctrl + , sur Pc).
J'ai pas mal ce réflexe quand je veux accéder aux settings dans SpatGris. 
Y-a t'il une raison particulière au fait que ce soit Cmd + ; dans SpatGris?

**Comment by Normandeau** [comment]
Pas vraiment de raison en fait. Je n'avais jamais remarqué qu'il y avait une combinaison standard. On pourrait s'adapter à cela.

**Comment by Normandeau** [comment]
V218
Changement effectué.
