### ISSUE TITLE
Fenêtre Speaker Set Up : la modification d'une valeur par drag peut entraîner la modification de la même valeur pour les HP situés au-dessus et au-dessous dans la liste. 

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#229]
V217
Fenêtre Speaker Set Up : la modification d'une valeur par drag peut entraîner la modification de la même valeur pour les HP situés au-dessus et au-dessous dans la liste. 

Je crois que cela se produit parce que changer une valeur par glissement permet également de déplacer la position des HP dans la liste.

Voir la vidéo :

https://user-images.githubusercontent.com/35705913/108909880-200a9800-75f3-11eb-82b8-28bb7cc5e2a6.mov

Dans l'exemple je modifie X pour le HP 60, mais dès que je bouge la souris vers le bas le HP 60 est également déplacé vers le bas. Dès que le HP 60 est déplacé vers le bas la valeur qui est modifiée est celle du HP 58, soit celle du HP qui était en bas du HP 60.

**Comment by Normandeau** [comment]
Je confirme tout cela. Avec en plus des plantages à répétition lorsqu'on fait certaines modifications de coordonnées.

**Comment by Normandeau** [comment]
V218
Pas de changement en mode DOME: regarder le comportement du hp no 6 dont la position change:

https://user-images.githubusercontent.com/8959779/110034311-4bcf0180-7d08-11eb-9b6b-265f3f6b6856.mov

En fait, je pense que l'idée de mettre une colonne supplémentaire à la gauche complètement, avec une icône claire destinée exclusivement aux déplacements serait une meilleure solution. Car avoir en même temps la possibilité de changer une valeur et/ou de déplacer un hp par la même case c'est un peu casse-gueule. Parce que même si la confusion existe moins en mode CUBE, il n'en demeure pas moins qu'on peut, par la même sélection, soit changer le numéro de sortie, soit déplacer le hp alors que ce sont deux opérations qui n'ont rien à voir.

**Comment by Normandeau** [comment]
V219
Une bonne addition, la poignée de déplacement. Ça donne de drôle de choses sur le plan visuel cependant, qui ne se reflète pas dans l'audio, mais pourtant ce sont bien les VU-mètres de sortie qui sont déclenchés:


https://user-images.githubusercontent.com/8959779/119194731-83b92b80-ba51-11eb-89aa-0ef4f6315624.mov

**Comment by Normandeau** [comment]
V2110
Poignée de déplacement ok.
Problème de flash dans les VU-mètres réglé.
