### ISSUE TITLE
La fonction “Reference Pink Noise” fait (parfois) planter parfois SpatGRIS2

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#230]
V217
La fonction “Reference Pink Noise” fait planter parfois SpatGRIS2.
Dans mon cas, si j’ouvre la fenêtre “Speaker Setup Edition” et que j’active la fonction “Reference Pink Noise” et je bouge le knob du volume, SpatGRIS2 se plante. 
Cela se ne passe pas toujours à la première fois que j’active cette fonction. Mais au cas où cela ne se produit pas la première fois, si je ferme et rouvre la fenêtre Speaker Setup Edition”  et  je réactive la fonction, SpatGRIS2 plante.

Testé avec le speaker Setup du B187 et le default_speaker_setup. Testé avec différentes configurations de cartes de son.

**Comment by Normandeau** [comment]
Another can of worms...
Je n'arrive pas à reproduire cela chez moi. Par contre ça me permet de mettre à jour deux autres bogues.
1-Lorsque j'utilise le Reference Pink Noise dans la fenêtre Speaker Setup Edition, et que je referme celle-ci, SpatGRIS2 ne plante pas mais il me demande toujours si je veux sauvegarder le Speaker Setup. Or je n'ai fait aucun changement dans le speaker setup. Cette fenêtre ne devrait pas s'ouvrir:

![Capture d’écran, le 2021-02-27 à 11 21 37](https://user-images.githubusercontent.com/8959779/109393311-e2598800-78ee-11eb-81b7-fa4eb26a54f5.jpg)

**Comment by Normandeau** [comment]
2-Autre situation. J'ai ouvert SpatGRIS2 chez moi, sans configurer les Settings. Jutilise une RME Babyface Pro. Lorsque j'ai testé avec le Reference Pink Noise, j'avais du son dans toutes les sorties de SpatGRIS2, comme il se doit, mais j'avais aussi du son  dans les entrées 5-6! Peu importe le document, peu importe le SpeakerSetup, il y avait du son dans les entrées 5-6:

![Capture d’écran, le 2021-02-27 à 11 24 40](https://user-images.githubusercontent.com/8959779/109393401-69a6fb80-78ef-11eb-81de-402a74d4ce2a.jpg)

Vérification faite dans les Settings, ma carte son était sélectionnées en entrée et en sortie comme dans les Preferences système:
![Capture d’écran, le 2021-02-27 à 11 25 01](https://user-images.githubusercontent.com/8959779/109393516-3749ce00-78f0-11eb-9e89-efd9c555fa4e.jpg)

Or les interfaces RME sont dotées d'une fonction nommée LoopBack qui permet, comme BlackHole, de brancher deux logiciels audio ensemble en utilisant l'interface audio comme intermédiaire. Je me sers de cette fonction pour rediriger le signal de sortie vers un autre logiciel RME, DigiCheck, qui me permet de faire l'analyse du signal:

![Capture d’écran, le 2021-02-27 à 11 50 30](https://user-images.githubusercontent.com/8959779/109393854-08345c00-78f2-11eb-810f-56707014c32f.jpg)

Mais c'est la première fois que je remarque que SpatGRIS2 récupère ce signal. Mais c'est peut-être aussi la première fois que la RME est sélectionnées en entrée. Est-ce un problème? Actuellement non, car j'ai ouvert seulement SpatGRIS2, sans DAW. Donc il ne reçoit aucune commande OSC, et parconséquent il n'envoie aucun signal audio des entrées vers les sorties. Théoriquement cela devrait conduire à un feedback numérique... Ai-je envie de tester? N'écoutant que mon courage, j'y vais! En fait, non, parce que la matrice de TotalMix, si elle est bien comprise par l'utilisateur, évite cela. Mais peut-être qu'une note dans le manuel serait une bonne idée pour prévenir l’utilisation de la même interface en entrée et en sortie...

**Comment by Normandeau** [comment]
Et tant qu'à être dans le sujet, la valeur de référence de sortie en dB de Reference Pink Noise n'est pas la bonne. La valeur maximale affichée est de -3dB, alors qu'en fait elle est au-dessus du 0 numérique: toutes les sorties écrêtes. Valeur lue sur les entrées et les sorties de SpatGRIS2 ainsi que dans Digicheck (-4dB semble correspondre au 0 nominal):

![Reference Pink Noise erronée](https://user-images.githubusercontent.com/8959779/109394620-ed63e680-78f5-11eb-97e5-818930357094.jpg)

**Comment by Normandeau** [comment]
Bingo, j'ai réussi à le faire planter finalement. Il semble que ça soit seulement lorsqu'on bouge le réglage très rapidement ou brusquement qu'il plante SpatGRIS2. Lorsqu'on fait des ajustements fins, qu'on l'ouvre et le ferme, qu'on ferme la fenêtre et qu'on la rouvre, tout est sous contrôle. Mais pas toujours. J'ai aussi remarqué que ça dépend de l'endroit où on pose le pointeur de la souris: dans le cercle jaune ça va, en dehors du cercle, où on peut aussi modifier la valeur, ça plante presque systématiquement. Et cela n'a pas à voir avec le son, ça plante simplement en mode graphique, sans le bruit. Que voulez-vous, c'est un tendre...
À corriger.

![Reference Level](https://user-images.githubusercontent.com/8959779/109395126-c22ec680-78f8-11eb-9a94-e7b4f748d71a.jpg)

**Comment by Normandeau** [comment]
V218
- Le Pink Noise ne fait plus planter. 
- La valeur de référence à 0db est la bonne.
- Le fait de l'utiliser (on/Off) ou de changer la valeur, ne génère plus de demande de sauvegarder le setup
