### ISSUE TITLE
Fenêtre 2D avec une partie de la valeur des angles: pas nécessaire

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#232]
V218
0, 9, 18 et 27, mode DOME ou mode CUBE (comme ici):

![Capture d’écran, le 2021-03-04 à 15 51 55](https://user-images.githubusercontent.com/8959779/110028780-b03a9280-7d01-11eb-9d6a-c5e478935355.jpg)

**Comment by SamuelBeland** [comment]
Incroyable ! J'avais ce problème uniquement sous Windows et en voulant le régler je l'ai recréé, mais seulement sous MacOS.

On règle le bug où on enlève les angles ?

**Comment by Normandeau** [comment]
C'est quoi le bogue exactement? Je parlais simplement d'enlever l'affiche numérique partiel des angles qui ne sont pas nécessaires ici.

**Comment by Normandeau** [comment]
V219
On enlève les angles, qui sont toujours là.

**Comment by Normandeau** [comment]
V2111
Réglé, les angles sont partis.
