### ISSUE TITLE
Messages d'erreur dans Speakers Setup Edition

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#233]
SpatGris v2.1.8

Dans la fenêtre Speakers Setup Edition, on peut régler la valeur du HighPass en maintenant et glissant notre souris sur la valeur, alors que ce n'est pas possible pour Gain et Distance (pour les régler on n'a pas d'autres choix que de double-cliquer et d'entrer la valeur manuellement) mais ça redevient possible pour l'élévation et l'azimuth. 
Je ne sais pas si c'est voulu mais c'est peut-être étrange que, dans une même fenêtre, les réglages de paramètres ne se fassent pas de la même façon.

**Comment by SamuelBeland** [comment]
Effectivement, il devrait être possible de régler le gain de la même façon que le highpass. Par contre, la distance peut être réglée avec la souris, mais seulement en mode CUBE. C'est vrai que ça serait bien d'avoir un indicateur visuel (couleur de background différente?) pour les valeurs non-modifiables.

**Comment by Normandeau** [comment]
V218
En fait, on a ici affaire à deux types de réglages: la position des hp (X, Y, Z etc), et des contrôles de niveau de sortie (Gain et HighPass).
Ces derniers sont assez critiques si on fait une erreur alors que pour les premiers on voit immédiatement leurs effets, à cause de la position des hp qui changent. Les contrôles de sorties sont là essentiellement en situation de concert si l'utilisateur veut (et peut...) calibrer sommairement le dispositif en ajustant le niveau et le filtrage de chaque hp. On ne se sert de cela que très rarement en fait.
Je propose donc qu'on garde des text box fixe pour les contrôles de sorties (Gain et HighPass). Donc qu'on revienne à cela pour HighPass.
À faire quand on aura le temps, y'a pas le feu...

**Comment by MelanieFrisoli** [comment]
En discutant avec Robert aujourd'hui, on s'est dit que ce serait bien si l'utilisateur pouvait avoir le choix pour entrer la valeur:
à la fois écrire (text box) si il a envie ou pouvoir "click & drag" (en fait exactement comment se comporte le "Highpass").

**Comment by Normandeau** [comment]
En fait, il n'y a qu'une seule valeur qui ne se comporte pas comme les autres et c'est Gain (dB). C'est le seul paramètre qu'on ne peut entrer qu'avec une Text box. C'est pourtant un paramètre qui devrait pouvoir être changé en temps réel si je puis dire, puisqu'il sert à calibrer un dispositif.

**Comment by NicolaGiannini** [comment]
Je suis d’accord en ce qui concerne le gain.
J’ajoute, comme Samuel le suggère, que ça serait bien d'avoir un indicateur visuel pour les valeurs non-modifiables en mode DOME. Donc : X Y Z et distance. Il pourrait être une couleur de background différente, ou même le texte du chiffre en gris clair (pas exactement le gris du background).

**Comment by Normandeau** [comment]
V219
Toutes les valeurs sont maintenant ajustables en continu avec la souris:
- Mode CUBE: toutes les valeurs
- Mode DOME: X, Y, Z et Distance ne sont pas disponibles, par définition. À mettre dans le manuel
«C'est vrai que ça serait bien d'avoir un indicateur visuel (couleur de background différente?) pour les valeurs non-modifiables.»
On mettra le background éventuellement plus tard ;-)

**Comment by MelanieFrisoli** [comment]
V219 
Léger détail mais qui pourrait frustrer les utilisateurs :
En mode Cube pour les valeurs X, Y, Z, il faut des mouvements très grands de souris et il est impossible d'atteindre la valeur maximum en une fois. Il faut s'y reprendre à plusieurs fois et puis parfois il redescend (surtout le Z). en fait j'atteins le haut de mon écran avec ma souris et là les valeurs redescendent. (Un peu la même chose m'arrive avec Distance en fait)

Aussi pour le Z, parfois il est écrit 0.00 et parfois -0.00.

**Comment by Normandeau** [comment]
Je seconde. La navigation dans cette fenêtre est pénible. Même la possibilité de placer les hp dans un certain ordre est une épreuve qui peut durer longtemps. Lorsqu'on déplace hp à une bonne position, certains autres se déplacent aussi. C'est comme un puzzle. Ce n'était pas le cas avant.

**Comment by Normandeau** [comment]
V2110
Mode CUBE
Les ajustements de paramètres sont bien contrôlables maintenant. Je remarque notamment qu'en mode CUBE,  en x, y et z, la valeur maximale est 1.00. Autant avec la souris qu'avec le Text Box, on ne peut pas tricher. Excellent.
Par contre Distance est toujours disponible en mode CUBE et la valeur maximale qu'on peut entrer est 1.73 (la racine carrée de quelque chose apparemment..), ce qui modifie les valeurs maximales de x et y pour 1.22 lorsque z est à 0.00. Ensuite si je mets z à 1.00, Distance passe à 2.00, ce qui place le hp dans le coin du CUBE. C'est un joli ballet. Sur le plan graphique c'est cohérent. J'aimerais cependant comprendre les maths qui sont derrière. Car je pense qu'il va falloir expliquer cela dans le manuel.

Voir:

https://user-images.githubusercontent.com/8959779/121097330-d3be1f00-c7c1-11eb-8b8c-f374c6e23133.mov

**Comment by SamuelBeland** [comment]
> J'aimerais cependant comprendre les maths qui sont derrière.

La distance entre l'origine [0, 0, 0] et le point le plus éloigné [1, 1, 1] est égale à √3, qui s'approxime à ≈1.73

**Comment by MelanieFrisoli** [comment]
En mode Cube il y a des petites choses : 


- Quand je règle un speaker à la souris, si je veux modifier légèrement cette valeur, dès que je clique pour glisser la souris, la valeur revient automatiquement sur une autre valeur, souvent aléatoire. C'est peut-être plus clair en vidéo (voir plus bas).
- Si je règle un premier hp (les valeurs X, Y et Z) et que je clique sur "Add Speaker", il donne au nouveau speaker les mêmes valeurs que le précédent. Est-ce qu'il ne serait pas mieux qu'il crée toujours des nouveaux speakers avec des valeurs par défaut ?
- Quand un nouveau speaker est créé, le numéro 2 apparaît avant le numéro 1. Est-ce que ce serait plus logique si il pouvait se mettre en dessous ?
- Quand on supprime des speakers pour en remettre d'autres, les outputs continuent d'avancer. Mettons que j'ai 5 speakers : 1, 2, 3, 4, 5. Je supprime 1 et 3. Si je crée un nouveau speaker, il aura le numéro d'output 6. Est-ce que ça fait du sens ?


https://user-images.githubusercontent.com/74631914/123178683-b5a91d80-d455-11eb-8501-957d4bd2218b.mp4

**Comment by MelanieFrisoli** [comment]
V2.1.12
Test en mode Dôme maintenant : 
* Quand je crée un speaker, la valeur de X est presque impossible à régler tant que je n'ai pas touché Azimuth ou tant que je n'ai pas beaucoup insisté : 


https://user-images.githubusercontent.com/74631914/123178012-60b8d780-d454-11eb-812b-8e69c6b6d4ac.mp4


* Pareil qu'en mode Cube pour la création du nouveau speaker avec les réglages du précédent. 
* Même chose avec le glissement de la souris qui nous fait partir d'une autre valeur aléatoire (sur tous les paramètres : Azimuth, Elevation, X, Y, Z, Gain et HiPass)
* Même chose aussi sur l'ordre des output (on va du plus haut au plus bas) 
* Par contre, contrairement au mode Cube, quand je crée plusieurs speakers à la suite sans modifier les réglages - en me disant par exemple, tiens je vais créer mes 5 speakers puis j'ajusterai leurs réglages, j'ai ce message d'erreur (au bout du 3ème speaker). Je me demandais juste si c'était normal) 

![Screen Shot 2021-06-23 at 6 51 54 PM](https://user-images.githubusercontent.com/74631914/123178144-978eed80-d454-11eb-87bf-b4869595b33b.JPG)

* Dernière chose pour la Distance : peut-être que ce serait bien que ce paramètre soit grisé quand on est en mode Dôme ?

**Comment by NicolaGiannini** [comment]
MODE CUBE

Mélanie 

> Quand je règle un speaker à la souris, si je veux modifier légèrement cette valeur, dès que je clique pour glisser la souris, la valeur revient automatiquement sur une autre valeur, souvent aléatoire. C'est peut-être plus clair en vidéo (voir plus bas).

Je confirme cela. Dans mon cas, il semble que si j'augmente la valeur avec la souris et que je clique à nouveau sur cette valeur, celle-ci diminue un peu. En revanche, si je diminue la valeur avec la souris et que je clique à nouveau sur cette valeur, celle-ci augmente un peu.

Mélanie

> Si je règle un premier hp (les valeurs X, Y et Z) et que je clique sur "Add Speaker", il donne au nouveau speaker les mêmes valeurs que le précédent. Est-ce qu'il ne serait pas mieux qu'il crée toujours de nouveaux speakers avec des valeurs par défaut ?

Il est vrai que si on veut créer une séquence de HP ayant des valeurs similaires, on utiliserait probablement la fonction Add Ring. Cela dit, dans le cas où on ne veut pas ajouter un Ring précis, mais on veut ajouter des haut-parleurs avec certaines valeurs en commun, alors il pourrait être pratique d'avoir le nouveau haut-parleur avec les mêmes valeurs que celui qu’on vient modifier. Je suppose que cela dépend vraiment du contexte.

Mélanie

> Quand un nouveau speaker est créé, le numéro 2 apparaît avant le numéro 1. Est-ce que ce serait plus logique si il pouvait se mettre en dessous ?

Je suis d'accord

Mélanie

> Quand on supprime des speakers pour en remettre d'autres, les outputs continuent d'avancer. Mettons que j'ai 5 speakers : 1, 2, 3, 4, 5. Je supprime 1 et 3. Si je crée un nouveau speaker, il aura le numéro d'output 6. Est-ce que ça fait du sens ?

Je me suis moi-même posé la même question, et j'ai parfois pensé qu'il serait plus pratique que les numéros de sortie soient automatiquement attribués au plus petit numéro disponible à chaque fois. Peut-être que la raison pour laquelle le nombre de sorties continue d'avancer est que dans le cas où on veut  ajouter un ring de 8 HP, il est plus pratique pour la numérotation du ring commence à la valeur la plus élevée ? Ceci étant, le nombre de HP du ring pourrait être plus élevé que le nombre disponible de HP qu'on a supprimés ?


MODE DOME

Mélanie

> Quand je crée un speaker, la valeur de X est presque impossible à régler tant que je n'ai pas touché Azimuth ou tant que je n'ai pas beaucoup insisté :

Je pense que la modification des paramètres XYZ en mode DOME est problématique, car les XYZ sont conditionnés par l'azimut, l'élévation et la distance. On peut voir dans la vidéo que lorsque je modifie X et Y, le haut-parleur se déplace sur l'axe d'azimut. Lorsque je modifie Z, le haut-parleur se déplace sur l'axe d'élévation. De plus, il est problématique d’insérer une valeur précise avec le clavier. Cette valeur revient automatiquement sur une autre valeur.


https://user-images.githubusercontent.com/35705913/123314304-6cf67080-d4f8-11eb-890c-d7d8e26ca021.mov



Mélanie

Dernière chose pour la Distance : peut-être que ce serait bien que ce paramètre soit grisé quand on est en mode Dôme ?

Je suis d'accord. Et je confirme tout le reste.

Mélanie

> Par contre, contrairement au mode Cube, quand je crée plusieurs speakers à la suite sans modifier les réglages - en me disant par exemple, tiens je vais créer mes 5 speakers puis j'ajusterai leurs réglages, j'ai ce message d'erreur (au bout du 3ème speaker). Je me demandais juste si c'était normal)

Je ne suis pas arrivé à reproduire ce message d'erreur. 

![Schermata 2021-06-24 alle 14 18 02](https://user-images.githubusercontent.com/35705913/123314346-7aabf600-d4f8-11eb-9372-a804bfedacf2.jpg)

**Comment by NicolaGiannini** [comment]
V2113
Les nouveaux haut-parleurs sont maintenant ajoutés sous la ligne sélectionnée. 

Mode CUBE,
On peut modifier les valeurs pour XYZ Azimuth Elevation et Distance. Maintenant si on modifie une valeur et qu’après on clique avec la souris, la valeur reste correcte. 

Mode DOME
Maintenant quand on indique une valeur précise, cette valeur est respectée. Quand on glisse sur XYZ, le déplacement des HP est (correctement je dirais) lié aux contraintes de l'algorithme DOME.

**Comment by Normandeau** [comment]
Mélanie: «Quand je crée plusieurs speakers à la suite sans modifier les réglages, j'ai ce message d'erreur (au bout du 3ème speaker). Je me demandais juste si c'était normal.»
Nicola: «Je ne suis pas arrivé à reproduire ce message d'erreur.»

De mon côté j'obtiens les deux messages d'erreur seulement en soustrayant des hp d'un dôme existant:
- le message de 170˚ quand cela se présente;
- le message de 3 hp quand cela se présente.

Par contre, en partant de 0 et en ajoutant des hp manuellement, les messages n'apparaissent jamais, même si, comme l'a illustré Nicola, les nouveaux hp ont tous les mêmes coordonnées.

**Comment by NicolaGiannini** [comment]
Je confirme ce que Robert dit. 
J'ajoute une chose. Je ne sais pas si ça peut être utile. 
Pour curiosité j'ai construit un dispositif avec 18 HP tous au même endroit en partant de 0 en mode DOME. J'ai enregistré le dispositif. En mode DOME l'audio n'est pas envoyé aux Speakers, par contre en mode CUBE l'audio est envoyé aux sorties.

**Comment by NicolaGiannini** [comment]
J’ajoute une autre chose. En construisant cette configuration à 18 haut-parleurs au même endroit en mode DOME, en la sauvegardant et en la rouvrant, je n'obtiens aucun message d'erreur.

Cependant, si je redémarre SpatGRIS, j'obtiens le message d'erreur de 170° à la réouverture.

**Comment by Normandeau** [comment]
V2.1.14
Message d'erreur apparaît en soustrayant. Puis message de spatialisation réapparaît en partant de 0 au 3e hp.
Message d'erreur aussi après avoir fermé et rouvert SpatGRIS.
Pour moi, c'est ok. Il y a assez d'information ici et dans le manuel. Et puis si l'utilisateur qui n'a pas de son avec 2 hp ne peut pas comprendre, qu'y pouvons-nous?!? Vous me direz ce que vous en pensez.

**Comment by NicolaGiannini** [comment]
C'est ok pour moi aussi !
