### ISSUE TITLE
Speaker Setup Edition - ranger les HP par leur numéro de sortie, sélectionner un HP et ensuite appuyer sur "Add Speaker" peut faire planter SpatGRIS2

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#234]
Speaker Setup Edition - ranger les HP par leur numéro de sortie, sélectionner un HP et ensuite appuyer sur "Add Speaker" peut faire planter SpatGRIS2

Si j’ouvre la fenêtre Speaker Setup Edition, je range les HP par leur numéro de sortie, je sélectionne un HP et ensuite j’appuie sur "Add Speaker”, SpatGRIS2 se plante. 
Voir la vidéo :

https://user-images.githubusercontent.com/35705913/110847314-c81e9300-827a-11eb-9f78-985d747c60de.mov

J’ai testé avec plusieurs Speaker Setup. Dans mon cas, le crash se produit toujours sauf que dans deux cas :
1) Si après avoir rangé les HP je sélectionne le dernier HP dans la liste.
2) Avec le speaker setup du B187 : 
[GRISpeaker Dome32Sub2UdeMUFX+.xml.zip](https://github.com/GRIS-UdeM/ServerGRIS/files/6125662/GRISpeaker.Dome32Sub2UdeMUFX%2B.xml.zip)
Cependant, si j’enlève les sorties directes de ce setup et que j’enregistre un nouveau setup, avec la même séquence, SpatGRIS2 se plante.

**Comment by Normandeau** [comment]
V218
Beau travail de recherche Nicola.
Peut-être rattaché à l'issue #229

**Comment by Normandeau** [comment]
V219
Semble réglé. Je laisse Nicola confirmer.

**Comment by NicolaGiannini** [comment]
V219
Ça semble réglé aussi dans mon cas.

**Comment by MelanieFrisoli** [comment]
V219
Ça semble réglé chez moi aussi.
