### ISSUE TITLE
Speaker Setup Edition - Le numéro de sortie d'un haut-parleur ajouté peut être le même que celui d'une sortie déjà assignée dans le Speaker Setup. 

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#235]
On a noté cela avec Mélanie vendredi passé en studio. 

Lors de l'ajout d'un HP, SpatGRIS peut attribuer un numéro de sortie en fonction du nombre total des HP présents, sans tenir compte des sorties déjà attribuées. Cela se produit si le HP est ajouté sans avoir préalablement sélectionné d'autres HP dans la fenêtre.
Cela peut entraîner l'ajout d'un HP dont le numéro de sortie est déjà attribué dans le setup.
Si, par contre, avant d'ajouter un haut-parleur, je sélectionne un haut-parleur, SpatGRIS prend en compte les sorties assignées.

Exemple 

Setup du B187
Sorties directes : 5 et 6 
Sorties du setup : du 31 à 62
Total HP : 34

Si j'ouvre la fenêtre Speaker Setup Edition et que j'ajoute un HP par la fonctionne "Add Speaker", la sortie du nouveau HP est 35. L'HP 35 est déjà présent. 

Si je sélectionne dans la liste un HP avant d'en ajouter un autre, la sortie du HP ajouté devient 63. L'HP 63 n'est pas présent dans le Setup, la dernière sortie assignée était 62.

Voir la vidéo :

https://user-images.githubusercontent.com/35705913/110851047-8a236e00-827e-11eb-843f-6f2a10fdf8de.mov

**Comment by Normandeau** [comment]
V218
Peut-être rattaché à l'issue #229

**Comment by Normandeau** [comment]
V219
Semble réglé avec le setup du B187 UFX+. À tester avec différentes configuration.

**Comment by Normandeau** [comment]
Testé avec Icosa, ça fonctionne. Je ferme pour le moment.
