### ISSUE TITLE
Le fait d'avoir deux haut-parleurs assignés à la même sortie peut entraîner l'accès au fichier default_speaker_setup ou la perte des entrées et sorties du projet. 

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#236]
Dans certaines conditions, il est possible d’assigner deux HP à la même sortie, voir issue https://github.com/GRIS-UdeM/ServerGRIS/issues/235
Si je cherche, d’enregistrer un setup avec deux haut-parleurs assignés à la même sortie, SpatGRIS m’avertit et il  me demande si je veux continuer. 
Si je réponds non, le fichier default_speaker_setup est automatiquement chargé.  Je peux donc entrer dans le dossier "Contents" du logiciel.

Voir la vidéo : 

https://user-images.githubusercontent.com/35705913/110853055-251d4780-8281-11eb-8406-c9e181b51634.mov

Si je réponds oui, je peux enregistrer le Setup, mais  quand je vais le rouvrir les sorties et les entrées du projet ne sont pas affichées. Si je supprime le doublon de sortie, les entrées et les sorties réapparaissent. 
Voir la vidéo : 
https://www.dropbox.com/s/dpd4wn4m6vvxqgf/yes.mov?dl=0

**Comment by Normandeau** [comment]
V218
Peut-être rattaché à l'issue #229

**Comment by Normandeau** [comment]
V219
Semble réglé, puisqu'il n'est plus possible d'avoir deux haut-parleurs assignés à la même sortie. À valider.

**Comment by SamuelBeland** [comment]
Je réalise que je n'ai pas prévu le chargement d'un speaker setup classique (< 2.1.9) où deux speakers seraient assignés à la même sortie. Je ne l'ai pas testé, mais logiquement SpatGRIS devrait complètement ignorer l'un des deux speakers.

Devrait-on accommoder ce cas particulier?

**Comment by Normandeau** [comment]
J'ai fabriqué un setup de 16 hp, plus 8 sorties directes, plus 2 sorties directes dans la version 218. Les 8 premières sorties directes ont les numéros 1 à 8, en commun avec les huit premiers hp du dôme: 

![16-8-2](https://user-images.githubusercontent.com/8959779/119268797-88e9b800-bbc2-11eb-82a4-fe6ef703c488.jpg)

Je rouvre ce setup dans 219, et il semble exploser, les 8 premiers VU-mètres en feu:

![8 premiers VUs en feu](https://user-images.githubusercontent.com/8959779/119268807-91da8980-bbc2-11eb-84b5-e09cf5076489.jpg)

Puis j'ouvre Speaker Setup Edition, et je vois que les 8 premiers hp du dôme sont disparus et que seules les 8 sorties directes qui partageaient les mêmes numéros sont conservées. Dès que je réordonne l’ordre des hp, le signal dans les VU-mètres disparait.

![8-2-8](https://user-images.githubusercontent.com/8959779/119268856-d0704400-bbc2-11eb-85ed-949aecae7367.jpg)

Je n'ai plus alors qu'à décocher les sorties directes 1 à 8 pour que la conversion soit complète. J en sais pas combien de personnes utilisent les sorties directes de cette manière. À mettre dans le manuel ou trouver une autre façon de faire la conversion? Dans le cas de Cathal Roche, le fichier a fait crasher V219. Pourquoi?
