### ISSUE TITLE
La fonction Add Speaker ne fonctionne plus en mode DOME

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#237]
SpatGRIS ne demande pas d’enregistrer le SpeakerSetup si on supprime un HP. Cependant, le haut-parleur est supprimé de la fenêtre 3D et des sorties.

Voir la vidéo :

https://user-images.githubusercontent.com/35705913/110855913-fb661f80-8284-11eb-8c57-5911e7cc5a73.mov

Le fichier XML n’est pas modifié.

**Comment by Normandeau** [comment]
V218
Peut-être rattaché à l'issue #229

**Comment by Normandeau** [comment]
V219
Ancien titre de cette issue, augmenté: SpatGRIS ne demande pas d’enregistrer le SpeakerSetup si on supprime **ou ajoute** un HP. Je viens de mettre «ou ajoute». En fait c'est plus compliqué que cela.

1. Setup de départ: dôme de 10 hp (octo plus 2 en haut)
2. J'ouvre la fenêtre Speaker Setup Edition, je sélectionne le hp 10 et je fais Add speaker. Le nouveau HP 11 s'ajoute au-dessus du no 10: je me serais attendu, puisqu'il s'ajoute, qu'il soit positionné après le 10, surtout qu'il porte le no 11. Si on ne choisit pas de hp, le no 11 s'joute à la fin de la liste. Enfin, celui-ci n'apparaît pas dans la fenêtre 3D:

![Add Speaker n'apparaît pas](https://user-images.githubusercontent.com/8959779/119185954-7007c800-ba45-11eb-85f9-56e05c77d8ee.jpg)

Il faut fermer la fenêtre Speaker Setup Edition pour que le nouveau hp apparaisse... au centre du dôme, donc inaccessible. La valeur par défaut de Distance du nouveau hp est 0.00 et elle est non-éditable! D'ailleurs aucun des paramètres n'est pris en charge. Je nouveau hp reste résolument au centre.

![Add Speaker apparait au centre du dôme](https://user-images.githubusercontent.com/8959779/119186251-d260c880-ba45-11eb-9405-b8a26baf4bc8.jpg)

Si je lance de l'audio à partir du séquenceur, le son se rend aux hp, mais dès que je bouge un ControlGRIS, le son s'arrête:

![Son bloqué après un mouvement de ControlGRIS](https://user-images.githubusercontent.com/8959779/119186442-1e137200-ba46-11eb-8cba-2b80fd117de9.jpg)

La seule façon de retrouver du son est de rouvrir Speaker Setup Edition, d'enlever le nouveau hp, de fermer la fenêtre, de lancer le séquenceur (il n'y a toujours pas de son à cette étape) et finalement de bouger ControlGRIS.

Conclusion: 
1) La fonction Add Speaker ne fonctionne plus en mode DOME.
2) La fonction COMPUTE ne joue plus aucun rôle.
Le problème ne se pose pas en mode CUBE, car on peut éditer X, Y, Z ou Azimuth, Elevation, Distance à volonté.

**Comment by SamuelBeland** [comment]
SpatGRIS demandera de sauvegarder le speaker setup si il est fermé, si l'utilisateur essaie de charger un speaker setup ou si le mode de spatialisation est changé.

**Comment by Normandeau** [comment]
Merci de cette précision. Donc est-ce que cela confirme que la fonction Compute de Speaker Setup Edition n'est plus utilisée?

**Comment by SamuelBeland** [comment]
Elle est automatiquement appelée à lorsque la fenêtre est fermée.

Il faudrait aussi que ce soit le cas lorsqu'un speaker est ajouté. Et bien évidemment, il faudrait que la position du nouveau speaker soit légale...

**Comment by Normandeau** [comment]
Dans le cas où le speaker setup a été modifié, que l'on ne l'a pas sauvegardé et qu'on ouvre un autre speaker setup, la demande de sauvegarde apparaît deux fois:
1) une première fois lorsqu'on appuie sur Load Speaker Setup
2) une seconde fois, après voir choisi un nouveau speaker setup.
Peut-être qu'une seule fois suffit.

**Comment by Normandeau** [comment]
Donc Compute pourrait être encore utile si on veut tester un speaker setup avec la fenêtre ouverte, exact? Je viens de tester en mode CUBE et cela semble être le cas. Pour le moment on ne peut pas tester en mode DOME.

**Comment by Normandeau** [comment]
«SpatGRIS demandera de sauvegarder le speaker setup si il est fermé, si l'utilisateur essaie de charger un speaker setup ou si le mode de spatialisation est changé.»
En fait, la seule manière de sauver un Speaker Setup est de fermer SpatGRIS. Il n'y a plus aucune fonction de Save ou de Save As. C'est très embêtant. Par exemple, j'ouvre les Speakers Setup existants afin de les convertir au nouveau format pour que nos Templates soient à jour. Pour chaque Speaker Setup, il faut que je ferme SpatGRIS! Et que je le rouvre pour le suivant. Il serait préférable de revenir à la formule précédente: un changement dans la fenêtre Speaker Setup Edition et dès qu'on ferme celle-ci, il nous demande de faire la sauvegarde. Ou un menu Save As dans cette fenêtre.

**Comment by SamuelBeland** [comment]
> Dans le cas où le speaker setup a été modifié, que l'on ne l'a pas sauvegardé et qu'on ouvre un autre speaker setup, la demande de sauvegarde apparaît deux fois:
> 
> 1. une première fois lorsqu'on appuie sur Load Speaker Setup
> 2. une seconde fois, après voir choisi un nouveau speaker setup.
>    Peut-être qu'une seule fois suffit.

Oui, une fois c'est assez!

> Donc Compute pourrait être encore utile si on veut tester un speaker setup avec la fenêtre ouverte, exact? Je viens de tester en mode CUBE et cela semble être le cas. Pour le moment on ne peut pas tester en mode DOME.

Exactement. La mise en place de VBAP est trop intensive pour être calculée au fur et à mesure. Ça serait possible de le faire en background, mais je pense que nous avons d'autres priorités pour l'instant.

> En fait, la seule manière de sauver un Speaker Setup est de fermer SpatGRIS. Il n'y a plus aucune fonction de Save ou de Save As. C'est très embêtant. Par exemple, j'ouvre les Speakers Setup existants afin de les convertir au nouveau format pour que nos Templates soient à jour. Pour chaque Speaker Setup, il faut que je ferme SpatGRIS! Et que je le rouvre pour le suivant. Il serait préférable de revenir à la formule précédente: un changement dans la fenêtre Speaker Setup Edition et dès qu'on ferme celle-ci, il nous demande de faire la sauvegarde. Ou un menu Save As dans cette fenêtre.

Je crois que d'exiger la sauvegarde des speaker setup à la fermeture de la fenêtre a le potentiel d'embêter les utilisateurs. Cela étant dit, les commandes "save speaker setup" et "save speaker setup as" sont définitivement manquantes.

J'appuie aussi l'idée d'ajouter des boutons correspondants directement dans la fenêtre d'édition de speaker setup.

**Comment by Normandeau** [comment]
On avait aussi discuter de la possibilité, en plus du Save et de Save As, d'ajouter le menu New dans cette fenêtre. Afin de pouvoir construire un speaker sur une base vierge.

**Comment by Normandeau** [comment]
Une question: pourquoi, lorsqu'on crée un nouveau speaker setup à partir de rien (de rien, vraiment?), les numéros ne démarrent pas automatiquement à 1?
C'est ce qu'on constate si on laisse Offset angle à 0.0: l'ordre de disposition des hp commence à 45˚ et défile ensuite à l'inverse des aiguilles d'une montre, avec les numéros 9-15 puis 8 pour le CUBE, et 5-11 puis 4 pour le DOME (c'est comme cela dans mon exemple, mais je n'ai aucune idée pourquoi) ?!?
Question corollaire: Où est le 0? Les Hp 10 et 6 sont ici respectivement à 0˚mais ils sont 2e dans l'ordre de création. 0˚ qui correspond à l'axe des X et qui est droit devant nous, ça me semble une bonne convention, c'est celle de ControGRIS en tout cas.
Deuxième question corollaire; pourquoi le premier hp de la nouvelle série ne se place-t-il pas automatiquement sur le 0˚ lorsqu'on choisit 0.00 comme valeur d'offset?
Troisième question corollaire: pourquoi l'inverse du mouvement horaire?

Création d'une octo en mode CUBE:

![CUBE Nouveau](https://user-images.githubusercontent.com/8959779/119379015-ee09e000-bc8c-11eb-8ceb-1b6a33d99046.jpg)

Création d'une octo en mode DOME:

![DOME nouveau](https://user-images.githubusercontent.com/8959779/119379117-1265bc80-bc8d-11eb-8ce8-7a37b53886c7.jpg)

**Comment by NicolaGiannini** [comment]
Je suis d'accord avec l'idée d'ajouter les commandes  "save speaker setup", "save speaker setup as" et "new".

Je me demande également s'il ne serait pas pratique que SpatGRIS demande si on veut sauvegarder les modifications lorsqu'on ferme la fenêtre d'édition.

Je suis d'accord avec les questions de Robert. 

Note 1 : de ce que je comprends, lors qu'on veut créer un speaker setup de rien et qu'on efface tous les HP, les numéros de nouveaux commencent à partir du chiffre suivant le dernier HP qu'on a effacé. Si le dernier HP qu'on a effacé était le 8, les nombres démarrent du 9. 

Note 2 : pour le moment, un autre moyen de sauvegarder un Speaker Setup est de faire des changements dans le Setup, fermer la fenêtre et ouvrir un autre Setup ou changer d'algorithme. À ce moment SpatGRIS demande si on veut enregistrer les changements.

**Comment by Normandeau** [comment]
V2110
Mode DOME
Situations avec Add Speaker et Add Ring à partir d'une page blanche. La seule manière de créer un speaker setup vierge est d'en ouvrir un existant et d'en effacer tous les hp.
Si on ajoute un Ring de 8, on reçoit cette information, qui n'est pas exact, puisqu'on veut précisément créer des hp!

![Capture d’écran, le 2021-06-08 à 12 08 14](https://user-images.githubusercontent.com/8959779/121220769-ecc2e080-c852-11eb-96d0-c4d37dfe086a.jpg)

Alors on fait NO et deux choses produisent:
- soit SpatGRIS crashe et à la réouverture il a perdu ses Settings. Plus précisément il perd le Input Device;
- soit le Ring de hp est bien créé.

• Coordonnées:
- le 0˚ est bien l'axe des X;
- les angles sont bien clockwise;
- les numéros de output dans mon exemple commencent parfois à 2, ou 3 ou 4 mais jamais à 1?
- ces numéros sont counterclockwise: pourquoi pas clockwise?

• Add speaker en mode DOME place bien le hp sur le dôme à distance de 1.00. Réglé.
- Adding a new speaker will copy the selected speaker's position: OK
- Adding a new speaker will correctly select it: OK
- Adding a new speaker will display it properly in the 3D view: OK.

![Capture d’écran, le 2021-06-08 à 12 25 43](https://user-images.githubusercontent.com/8959779/121222593-acfcf880-c854-11eb-8cfd-449b7927bf48.jpg)

Tests à poursuivre.

**Comment by Normandeau** [comment]
Mode DOME
Une situation un peu étrange. Si on vide complètement un speaker setup, on reçoit bien sûr l'avertissement qu'on n'a pas assez de hp, et si on ferme la fenêtre après avoir appuyé sur NO, on se retrouve avec une fenêtre 3D vide, mais avec les outputs du Speaker Setup ouvert à l'origine:
![Capture d’écran, le 2021-06-08 à 12 38 20](https://user-images.githubusercontent.com/8959779/121227158-46c6a480-c859-11eb-8061-da4f5bcb0d02.jpg)

Je pense que la fenêtre d'avertissement devrait être plus contraignante. Quel est le nombre minimal pour avoir un setup qui fonctionne? Considérons que le dome minimal est constitué de 4 hp: 3 à la base et un 1 au sommet. Le fenêtre d'avertissement pourrait alors se lire comme suit:
«The minimal dome setup needs 4 speakers on two levels.»

![Capture d’écran, le 2021-06-08 à 12 56 35](https://user-images.githubusercontent.com/8959779/121227045-2a2a6c80-c859-11eb-933d-a089e57d1a65.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme tout ce que dit Robert.

Robert :

> les numéros de output dans mon exemple commencent parfois à 2, ou 3 ou 4 mais jamais à 1?


Je pense que les numéros de nouveaux HP commencent à partir du chiffre suivant le dernier HP qu'on a effacé. Si le dernier HP qu'on a effacé était le 8, les nombres démarrent du 9. Si le dernier HP qu'on a effacé était le 1, les nombres démarrent du 2.

**Comment by Normandeau** [comment]
La demande de sauvegarde apparaît toujours deux fois

**Comment by Normandeau** [comment]
V2111
Il y a de nouveaux messages d'alerte dans Speaker Edition Window.
Deux d'entre eux sont erronés, comme on peut le voir ici:

Création d'un setup de 4 hp, à 90˚ d'azimuth entre eux: fausse alerte d'azimuth maximale de 170˚:

![Disabled Spatialisation 170˚](https://user-images.githubusercontent.com/8959779/122301465-b62e3b00-cece-11eb-93f9-62f77966e17d.jpg)

Création d'un setup de 4 hp: fausse alerte d'au moins 3 hp:

![Disabled Spatialisation 3 speakers](https://user-images.githubusercontent.com/8959779/122301546-cf36ec00-cece-11eb-81b9-09a7e2cb569d.jpg)

**Comment by Normandeau** [comment]
La demande de sauvegarde n'apparaît plus deux fois.

**Comment by NicolaGiannini** [comment]
V2111
Je confirme les messages d'alerte erronés.

**Comment by Normandeau** [comment]
Les numéros des hp qu'on créés avec Add Ring sont counterclockwise: pourquoi pas clockwise? Je ne dis pas que c'est fondamental, mais s'il s'agit d'être cohérent...
Puisque: «The offset angle is now clockwise instead of counterclockwise»:

![HP counterclockwise](https://user-images.githubusercontent.com/8959779/122816753-20ffbd80-d2a5-11eb-87ad-9933acff6b6c.jpg)

**Comment by NicolaGiannini** [comment]
V2112
Les messages d’erreur semblent être réglés. 
Les numéros des hp qu'on créés avec Add Ring semblent être encore counterclockwise.
