### ISSUE TITLE
Lors de l’utilisation de la fonction “Reference Pink Noise” le fait de supprimer des HP peut causer une sorte de distorsion numérique 

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#238]
V218
J’imagine qu’on ne peut pas le considérer un bug, mais probablement on pourrait l’indiquer dans le manuel. 
Si on efface des HP pendant qu’on utilise la fonction “Reference Pink Noise”  de la distorsion numérique est générée. Le son peut sembler une onde carrée.  Plus de HP on efface et plus on entend cette distorsion.  

Dans le cas du B187, chaque fois que je supprime un haut-parleur, l'un des haut-parleurs passe du bruit rose à cette distorsion numérique. Il ne me semble pas qu'il y ait une correspondance exacte, c'est-à-dire que si je supprime le numéro 31, ce n'est pas forcément le 31 qui commence à diffuser la distorsion. Dans le B187 si j’efface tous les HP, tous les HP vont diffuser cette distorsion.
Testé dans le A569 aussi. Dans le cas du A569, si je supprime tous les HP (8), 4 vont diffuser cette distorsion.

On pourrait probablement ajouter une note dans le manuel indiquant que les haut-parleurs ne doivent pas être supprimés lors de l’utilisation de la fonction  “Reference Pink Noise”

**Comment by Normandeau** [comment]
Je veux bien mettre une note dans le manuel mais en même temps, et malgré le fait que j'apprécie ta découverte, on ne peut pas prévoir toutes les conneries faites par les utilisateurs!
;-)

**Comment by NicolaGiannini** [comment]
Ahah :) Je suis totalement d'accord !
Il s'agit d'une utilisation totalement non orthodoxe et insensée !
