### ISSUE TITLE
Lors de l’utilisation de la fonction “Reference Pink Noise" SpatGRIS envoie plus de signaux audio que les canaux du speaker setup.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#239]
V218
J'imagine que ce n'est pas trop important, mais lors de l’utilisation de la fonction “Reference Pink Noise SpatGRIS envoie plus de signaux audio à la carte de son que les canaux du speaker setup.

Studio A569. Le speaker setup comporte les HP de 1 à 8 pour l'octo et les HP 13 et 14 pour les sub. Dans ce cas je suis en train d'envoyer de l'audio à tous les HP grâce au span de ControlGRIS.
Capture d'écran de Totalmix de la carte de son

![Schermata 2021-03-13 alle 14 37 06](https://user-images.githubusercontent.com/35705913/111042722-bff65d00-840c-11eb-9813-75fe4fa7565d.jpg)

On remarque qu'il y a du signal dans les sorties de 1 à 8 et dans les 2 AES, qui sont les canaux associés aux sub. Cela est cohérent avec le setup que j'utilise.

--------------

Dans ce cas j'utilise la fonction “Reference Pink Noise".
On remarque que le signal est envoyé également vers les canaux 9,10,11,12 qui ne font pas partie du speaker set up.

![Schermata 2021-03-13 alle 14 37 44](https://user-images.githubusercontent.com/35705913/111042760-ee743800-840c-11eb-868b-e15045de8900.jpg)

Testé également dans le B187.

De ce que je comprends, la fonction “Reference Pink Noise" envoie le signal à toutes les sorties compris entre la première et la dernière sortie du setup, même si certaines sorties ne font pas partie de la configuration. Ça semble similaire à un vieux bug lié à l'enregistrement.

**Comment by Normandeau** [comment]
Je confirme cela. Dans Icosa, j'utilise les sorties 33-34 et le Pink Noise sort partout jusqu'à 34 alors que je n'ai que 24 hp réellement utilisés.

**Comment by Normandeau** [comment]
V219
Réglé, autant en mode DOME qu'en CUBE.
