### ISSUE TITLE
Mode CUBE inutilisable avec des hp non consécutfs

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#241]
V218
Le mode CUBE ne fonctionne pas toujours comme prévu.
Piste octophonique, mouvement bas-haut et vice-versa.

Studio Icosa, 20.4 (Speaker Setup construit de neuf),
Certains haut-parleurs sont ignorés lorsque le signal est à leur hauteur et réapparaissent alors que le signal est rendu ailleurs. Remarquez 10 et 27 au premier niveau, puis 27 et ensuite 28:
(vue du côté de l'axe des X)
Une piste d'explication et de solution j'espère: les numéros des hp dans Icosa ne sont pas consécutifs (pour des raisons de logique de branchement dans le studio)

https://user-images.githubusercontent.com/8959779/111530751-111e8d80-873a-11eb-821d-001ea02e1ddb.mov

J'ai une situation semblable dans le dôme du B-187 dont les hp du zénith (53-54) correspondent à des numéros plus petits que ceux de la couronne inférieure. On voit qu'il n'y a aucune activité dans le 54 alors qu'il y a une source placée directement à l'intérieur de celui-ci:

![CUBE B187 54 off](https://user-images.githubusercontent.com/8959779/111531951-8ccd0a00-873b-11eb-8b93-535eea3f6e32.jpg)

**Comment by Normandeau** [comment]
Sur un dispositif complexe de 54 hp avec des numéros consécutifs, tout se passe comme prévu:

https://user-images.githubusercontent.com/8959779/111532482-167cd780-873c-11eb-8c5f-113fbdc79914.mov

Tous les CUBE testés avec des numéros consécutfis sont corrects.

**Comment by Normandeau** [comment]
Même situation avec Icosa, avec une source octophonique très serrée (en fait le diamètre du cercle octophonique ne change rien) en haut du CUBE. Les hp qui fonctionnent: 
- 26: premier niveau
- 27: deuxième niveau
- 28: troisième niveau
- 29: quatrième niveau
- 5: quatrième niveau
- Ça n'a aucune sens sur le plan spatial! Sauf que ce sont les hp numérotés 26 à 29, donc consécutifs!

![Octo très serrée en haut](https://user-images.githubusercontent.com/8959779/111533590-542e3000-873d-11eb-9834-eb70128ff041.jpg)

**Comment by Normandeau** [comment]
Confirmation.
J'ai fabriqué un CUBE de 32 hp avec des nos consécutifs. Tout se comporte normalement:

https://user-images.githubusercontent.com/8959779/111536349-868d5c80-8740-11eb-866f-a4983edb1e4b.mov

Le même dispositif dans lequel j'ai changé les numéros de sortie de façon arbitraire. La spatialisation n'a plus de sens. Regardez le no 43 au départ par exemple, et le 27 ensuite (parmi d'autres):

https://user-images.githubusercontent.com/8959779/111536488-ade42980-8740-11eb-95e8-541530934393.mov

**Comment by SamuelBeland** [comment]
Je crois que de réordonner les speakers en ordre croissant d'output patch devrait rendre les setups utilisables en attendant que je fix ce problème...

https://user-images.githubusercontent.com/39448259/111721395-2d075980-8836-11eb-9dbb-215af91a6427.mp4

**Comment by NicolaGiannini** [comment]
Je confirme le comportement décrit par Robert, avec des HP non consécutifs le mode CUBE ne fonctionne pas comme prévu.

Je confirme également le comportement décrit par Samuel, si on réordonne les speakers en ordre croissant la spatialisation en mode CUBE fonctionne correctement.

**Comment by Normandeau** [comment]
J'ai fait un test supplémentaire sous Mojave (10.14) avec SpatGRIS 2.12 (la version officielle) avec Jack. Le même Speaker Setup et la même session DP 10.13. Aucun problème de cet ordre. Peu importe comment les hp sont placés ou comment les numéros de sortie sont distribués, la spatialisation se comporte normalement sur des séries de groupes de hp à la même hauteur. Cela veut dire que le problème a été introduit récemment, peut-être avec les versions BlackHole. 
Sous Mojave toujours, j'ai comparé avec la version 218, et on retrouve le comportement problématique décrit dans cette issue.

**Comment by Normandeau** [comment]
V219
Ce problème semble réglé. En tout cas dans Icosa et le B187, avec des setups de CUBE constitués de numéros non-consécutifs, la répartition spatiale se passe correctement.
