### ISSUE TITLE
Niveaux de sorties différents entre STEREO et en BINAURAL

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#242]
V218
En STEREO et en BINAURAL, toutes les sorties directes sont acheminées exclusivement vers le canal droit. Aucun signal n'est envoyé au canal gauche en provenance des sorties directes. Qu'on soit en DOME ou en CUBE à l'origine ne change rien.

**Comment by Normandeau** [comment]
En essayant de voir quand ce problème a commencé, je suis remonté en arrière. Pas bien loin.
V216: même problème.
V214: impossible de l'ouvrir sous Catalina, elle crashe immédiatement.

**Comment by Normandeau** [comment]
Sous Mojave
ServerGRIS207, SpatGRIS209, SpatGRIS218
Le problème est pas mal plus compliqué qu'il n'y paraissait. Ce que j'avais décrit, c'était encore une fois avec mon dôme Icosa, qui possède un ordre de sorties un peu bizarre (pour des raisons de câblage). J'ai voulu savoir quand ce problème avait commencé. Je suis remonté à ServerGRIS207 (Jack) sous Mojave. Tout était beau.
Mais dès SpatGRIS2 V209, le problème arrive. En fait. le problème est multiple:
1) si les sorties directes ont des numéros qui se situent à l'intérieur des valeurs du dôme, c'est le bordel. Ça sort à droite, à gauche, c'est inversé ou toutes du même bord. Dans le cas d'Icosa, il y a 32 sorties sur l'interface et les sorties directes sont 6, 14, 22 et 30. Elles sortent toutes à droite.
2) si les sorties directes ont des numéros supérieurs au dôme, c'est aussi le bordel, mais différent. Je n'ai pas testé tous les cas de figure mais en voici quelques-uns. Dans le dispositif, les hp sont respectivement placés à gauche et à droite du dôme. Les G et D mentionnés correspondent aux canaux  du BINAURAL ou du STEREO. Le dôme est Icosa. Selon l'ordre de succession, elles sortent à gauche ou à droite, au petit bonheur la chance. Pas de logique genre gauche-impaire, droite-paire par exemple:
- 35 31 44 39
    G  G   D   G
- 30 33 32 31
   D   G   D   D
- 30 31 32 33
   D   G    D   G

3) J'ai une autre série avec un plus petit dôme de 10hp (sorties 1 à 10) avec au départ les sorties sur 11-12.  STEREO: G-D, normal.
- 31 15
  G   G
- 14 15
   D  G
- 13 12
   G  D
- 13 57
   G  G
- 57 13
   G  G

En fait, lorsqu'on passe par STEREO ou BINAURAL, le positionnement des sorties directes dans l'espace gauche-droite devrait être pris en charge. Je crois qu'on a pris cela pour acquis mais ce n'est pas le cas. Quelle est la logique de distribution des sorties dans le mixage à deux canaux?

**Comment by NicolaGiannini** [comment]
J'ai fait des tests. Dans mon cas, les sorties directes numérotées paires semblent être envoyées à droite, et les sorties numérotées impaires à gauche.
Je continue à tester.

**Comment by Normandeau** [comment]
V219
Quand on passe en mode STEREO ou BINAURAL, et qu'on a des sorties directes dans notre projet, on reçoit ce message:

![Dropped Direct Out](https://user-images.githubusercontent.com/8959779/119273403-d4a75c00-bbd8-11eb-95a7-6b2633f3a64b.jpg)

Donc si ces sorties directes étaient destinées aux subs, on n'a plus de grave ni en stéréo, ni en binaural. Pire, quand on revient en DOME, les sorties directes ne sont plus activées.
Je pense que le remède est pire que le problème soulevé ici.
À corriger impérativement.

**Comment by NicolaGiannini** [comment]
V219
Je confirme ce que dit Robert.

**Comment by Normandeau** [comment]
V2110
Les sorties directes sur les hp spatialisés et celles sur les sorties exclusives se répartissent maintenant correctement dans l'image gauche droite du mode STEREO. Par exemple, une sortie directe placée à 270˚ sortira complètement à gauche alors qu'une sortie directe placée à 45˚ sortira plus fort à droite qu'à gauche (environ 10dB de différence). Cela quelque soit le numéro du hp (impaire-pair).
Par contre en mode BINAURAL, tout est beaucoup plus centré. En reprenant l'exemple précédent, avec une sortie directe placée à 270˚, le son sort principalement à gauche mais aussi à droite (à environ -20dB). Remarquez que ce n'est pas propre à la sortie directe, on a le même comportement avec un son spatialisé par ControlGRIS.
Est-ce une question d'algorithme?

**Comment by catrochemusic** [comment]
V2.1.10A small matter but I noticed a change that is perhaps unintended in this version.. in Catalina the 3D view window flashes continuously red when adjusting it’s scale.


Sent from Yahoo Mail for iPhone


On Monday, June 14, 2021, 4:23 p.m., Robert Normandeau ***@***.***> wrote:




V2110
Les sorties directes sur les hp spatialisés et celles sur les sorties exclusives se répartissent maintenant correctement dans l'image gauche droite du mode STEREO. Par exemple, une sortie directe placée à 270˚ sortira complètement à gauche alors qu'une sortie directe placée à 45˚ sortira plus fort à droite qu'à gauche (environ 10dB de différence). Cela quelque soit le numéro du hp (impaire-pair).
Par contre en mode BINAURAL, tout est beaucoup plus centré. En reprenant l'exemple précédent, avec une sortie directe placée à 270˚, le son sort principalement à gauche mais aussi à droite (à environ -20dB). Remarquez que ce n'est pas propre à la sortie directe, on a le même comportement avec un son spatialisé par ControlGRIS.
Est-ce une question d'algorithme?

**Comment by NicolaGiannini** [comment]
Robert : 

> Par contre en mode BINAURAL, tout est beaucoup plus centré.

J'ai noté exactement la même chose.

**Comment by Normandeau** [comment]
V2112
Mode CUBE ou DOME
La différence de niveau gauche-droite la plus grande qu'on peut obtenir en BINAURAL est de -12dB entre des hp situés aux extrémités du dispositif de hp (CUBE montré ici), que ce soit en spatialisation (représentée ici) ou en sortie directe:

![BINAURAL Cube](https://user-images.githubusercontent.com/8959779/123435732-e4311080-d59b-11eb-88cd-c8ee9407d48e.jpg)

Comparaison avec Stereo:

![STEREO Cube](https://user-images.githubusercontent.com/8959779/123435781-f27f2c80-d59b-11eb-8371-95200728df47.jpg)

Question: normal?

**Comment by Normandeau** [comment]
V311
Les problèmes de déséquilibre gauche-droit de cette issue sont résolus. Le Binaural pose encore pas mal de problèmes. À suivre dans d'autres issues.
