### ISSUE TITLE
Il n'y a plus de zoom dans la vue 3D

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#244]
V219
The 3D camera zoom is smoother.
On ne peut plus zoomer avec la roulette de la souris dans l'espace 3D. Cette fonction est vraiment indispensable, spécialement dans de gros setups où on ne voit plus rien en détail. Il faut pouvoir agrandir l'image.
La vue 3D s'ajuste à la grosseur de la fenêtre, mais ça, on avait déjà cela avant. Je parle ici d'un zoom indépendant, qu'on vient de perdre.

**Comment by SamuelBeland** [comment]
Ça ne semble toucher que la version MacOS. Je m'y met.

**Comment by Normandeau** [comment]
V2110
Réglé. Youpie!!!
