### ISSUE TITLE
Show Source Activity ne fonctionne plus dans la fenêtre 2D

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#245]
V219
Dès que la séquence démarre les sources sont montrées dans SpatGRIS et ne disparaissent plus, même avec Reset Input Position.

**Comment by SamuelBeland** [comment]
Reset input position fonctionne de mon côté (Catalina & Windows 10).

Show source activity ne fonctionne pas par contre.

**Comment by Normandeau** [comment]
Une précision: Reset Input Position fonctionne effectivement après que la séquence ait été fermée. Je voulais dire, pour forcer à faire disparaître l'affichage des sources dans cette situation particulière, ce qui n'est pas possible de toute manière.

**Comment by MelanieFrisoli** [comment]
Pareil chez moi, Show source activity ne fonctionne pas (High Sierra)

**Comment by NicolaGiannini** [comment]
Je confirme que les sources sont toujours affichées dès qu’on démarre la séquence. Show source activity ne semble pas fonctionner.

**Comment by Normandeau** [comment]
V2110
Réglé.

**Comment by Normandeau** [comment]
C'est réglé dans la fenêtre 3D mais pas dans la fenêtre 2D.

![Capture d’écran, le 2021-06-10 à 18 22 09](https://user-images.githubusercontent.com/8959779/121604578-cfd80a00-ca18-11eb-909f-bd7f07212846.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme.

**Comment by Normandeau** [comment]
V2111
Réglé.
