### ISSUE TITLE
Elevation à 90 fait disparaître le hp de la vue 3D

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#246]
V219
À certaines occasions, le haut-parleur qui a le numéro le plus élevé et/ou qui est au sommet, n'apparaît pas dans la fenêtre 3D. Ici le hp no 16 dans le speaker setup par défaut. Pour le faire réapparaître, il faut éditer celui-ci dans la fenêtre Speaker Setup Edition.

![default speaker setup hp16 invisible](https://user-images.githubusercontent.com/8959779/119240272-8b91d200-bb1c-11eb-96f3-d727dc076d52.jpg)

**Comment by Normandeau** [comment]
Un autre exemple, le fameux dôme minimum à 4 haut-parleurs! C'est grâce à lui qu'on fera de la conversion auprès des néophytes! Et là, il manque le hp no 4! En fait, dans celui-ci, si l'élévation est à 90, l'image du hp disparaît. Si je mets 89.9 elle réapparaît. 
Après plusieurs tests, il appert que c'est uniquement l'élévation à 90 qui fait disparaître le hp. Testé avec plusieurs configurations anciennes et nouvelles.
Ce problème n'existe pas dans la version 216.

![Dôme à 4 hp](https://user-images.githubusercontent.com/8959779/119241469-89337600-bb24-11eb-9884-aa1d959d70fc.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme.

**Comment by Normandeau** [comment]
V2110
Le haut-parleur qui est à 90˚ en élévation disparaît de la fenêtre 3D en mode CUBE.
Réglé en mode DOME.

**Comment by Normandeau** [comment]
J'ai été un peu vite. Pas réglé même en mode DOME.

**Comment by NicolaGiannini** [comment]
Je confirme, le haut-parleur qui est à 90˚ en élévation disparaît de la fenêtre 3D en mode CUBE et DOME.

**Comment by Normandeau** [comment]
V2111
Réglé, en DOME et en CUBE
