### ISSUE TITLE
CUBE converting to DOME

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#247]
Il y a beaucoup de messages comme celui-ci qui apparaissent à l’ouverture de dômes classiques, y compris le speaker setup par défaut! Ce sont des Speaker Setup auxquels il manque une ligne de code dans le fichier xml: SpatMode="0". Mais même en l'ajoutant, ça ne change rien. Il faudra juste convertir tous ces fichiers et mettre un mot dans le manuel. Le message d'erreur cependant est erroné. Ce sont de dômes que j'essaie d'ouvrir, pas des CUBE. Quant j'essaie d'ouvrir des CUBE en mode DOME, il passe tout simplement en mode CUBE. Confusion potentielle. Donc ce message est utile quand on a un CUBE ouvert qu'on veut passer en mode DOME. Mais quand on ouvre un speaker setup ancien, il faudrait un autre message.

![CUBE to DOME](https://user-images.githubusercontent.com/8959779/119240207-35bd2a00-bb1c-11eb-857d-8cf547a72d02.jpg)

**Comment by SamuelBeland** [comment]
Ce qui est étrange, c'est que plusieurs setups DOME fournis avec SpatGRIS n'ont pas réellement une structure de dôme.

Pour v2.1.9, SpatGRIS assume un layout DOME lorsque le paramètre "SpatMode" est manquant dans un setup classique. Le mieux dans ce cas-ci serait surement de vérifier si la structure ressemble à un dôme, et ensuite de déduire l'algorithme à utiliser en conséquence. Il va nous falloir corriger les setups erronés.

**Comment by Normandeau** [comment]
Aucun problème pour faire la conversion. J'attends le Save As!

**Comment by Normandeau** [comment]
V2110
Je vérifie les Speaker Setup que nous fournissons dans le dossier Template afin de les convertir au nouveau format.
1. Conversion d'un HP direct out en HP spatial
Pont de départ: GRISpeaker Dome4Subs1: 4 hp au sol et un sub. 
Comme les setups 2D ne fonctionnent plus, je convertis le sub qui est en direct out à une distance de 1.4 pour faire le 5e hp placé en haut qui permettra de faire la triangulation.
Résultat: ce hp reste fixé à une distance de 1.4 et comme on est en mode DOME:
- on ne peut éditer Distance;
- on ne peut éditer Z.
- Donc c'est bloqué comme cela.

![4hp avec le 5e à 1 4](https://user-images.githubusercontent.com/8959779/121234870-2fd88000-c862-11eb-9ef3-61d072de029d.jpg)

Je le ferme et le sauve comme tel.
Je me dis qu'en le rouvrant, SpatGRIS va soit le convertir en DOME (Distance = 1) ou l'ouvrir en CUBE comme mentionné:
«Legacy speaker setups are now read as CUBE if the structure isn't dome-like»

Rien de cela. Le setup s'ouvre normalement avec un hp du DOME à 1.4. La seule possibilité c'est de le faire passer en CUBE, de placer la distance à 1.00 et de le sauver comme tel.

**Comment by NicolaGiannini** [comment]
Je confirme ce que Robert dit. 
Une autre possibilité pour ramener la distance à 1 est de rouvrir le Setup, passer en mode CUBE et ensuite repasser en mode DOME. Dans mon cas la distance est automatiquement mise à 1.

**Comment by SamuelBeland** [comment]
v2.1.10

> Je le ferme et le sauve comme tel.
> Je me dis qu'en le rouvrant, SpatGRIS va soit le convertir en DOME (Distance = 1) ou l'ouvrir en CUBE comme mentionné:
«Legacy speaker setups are now read as CUBE if the structure isn't dome-like»

À partir du moment où un speaker setup est enregistré par SpatGRIS 2.1.9 ou plus, ce n'est plus un setup "legacy". SpatGRIS assume que les positions des speakers sont valides... Le problème est dans la conversion d'un speaker non-spatialisé à un speaker spatialisé : la position devrait être ramenée sur le dôme à ce moment.

> Comme les setups 2D ne fonctionnent plus [...]

Normalement, les setups 2D devraient être fonctionnels depuis 2.1.10, plus besoin du 5e speaker.

**Comment by Normandeau** [comment]
On fera toutes les conversions du dossier Template avant de publier.
