### ISSUE TITLE
Problème de conversion des anciens speaker setup avec des sorties directes communes avec le dome

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#248]
Samuel:
Je réalise que je n'ai pas prévu le chargement d'un speaker setup classique (< 2.1.9) où deux speakers seraient assignés à la même sortie. Je ne l'ai pas testé, mais logiquement SpatGRIS devrait complètement ignorer l'un des deux speakers.
Devrait-on accommoder ce cas particulier?

**Comment by Normandeau** [comment]
J'ai fabriqué un setup de 16 hp, plus 8 sorties directes, plus 2 sorties directes dans la version 218. Les 8 premières sorties directes ont les numéros 1 à 8, en commun avec les huit premiers hp du dôme. Les deux autres sont destinées aux Subs et portent des numéros uniques.:
![16-8-2](https://user-images.githubusercontent.com/8959779/119269108-03ff9e00-bbc4-11eb-8d20-a4a27544c52b.jpg)

Je rouvre ce setup dans 219, et il semble exploser, les 8 premiers VU-mètres en feu:
![8 premiers VUs en feu](https://user-images.githubusercontent.com/8959779/119269111-09f57f00-bbc4-11eb-9143-94b7c137c7ce.jpg)

Puis j'ouvre Speaker Setup Edition, et je vois que les 8 premiers hp du dôme sont disparus et que seules les 8 sorties directes qui partageaient les mêmes numéros sont conservées. Dès que je réordonne l’ordre des hp, le signal dans les VU-mètres disparait.
![8-2-8](https://user-images.githubusercontent.com/8959779/119269116-0f52c980-bbc4-11eb-9a28-08d6cd739b17.jpg)

Je n'ai plus alors qu'à décocher les sorties directes 1 à 8 pour que la conversion soit complète. Je ne sais pas combien de personnes utilisent les sorties directes de cette manière. À mettre dans le manuel ou trouver une autre façon de faire la conversion? Dans le cas de Cathal Roche, le fichier a fait crasher V219. Pourquoi?

**Comment by Normandeau** [comment]
Je viens de faire un test supplémentaire afin de voir si le comportement était le même avec des sorties directes loin dans l'ordre des numéros. J'ai pris le setup du B187 (5-6 puis 31-62) auquel j'ai ajouté 12 sorties directes (no 35 à 46) dans 218. Remarquez que ces 12 hp ne correspondent pas à ceux déjà existants sur le plan géographique:

![32Input12DO2Subs](https://user-images.githubusercontent.com/8959779/119272446-e89c8f00-bbd3-11eb-950c-2ad61e960117.jpg)

Lorsque j'ouvre ce setup dans 219, j'ai les 12 hp en feu, mais après avoir édité le setup c'est réglé:

![32InputsSubs2](https://user-images.githubusercontent.com/8959779/119272454-efc39d00-bbd3-11eb-8cea-854fa32e00f7.jpg)


Ce que je trouve embêtant dans cette conversion, c'est que ce sont les hp du dôme qui sont sacrifiés au profit des hp des sorties directes (par exemple 35-41 ici). Il me semblerait plus logique de conserver les hp du dôme et de sacrifier les sorties directes.

**Comment by SamuelBeland** [comment]
Oui, effectivement, ça serait bien si les HP du dôme serait priorisés dans la conversion.

**Comment by SamuelBeland** [comment]
En fait, je réalise que je n'ai même pas besoin de sacrifier des HP: je vais simplement assigner des nouveaux output patch aux speakers dupliqués.

**Comment by NicolaGiannini** [comment]
Je ne sais pas si cela peut aider. 
Voici une configuration réalisée avec la version 212. La configuration comporte 16 HP de 1 à 16 qui font partie de la spatialisation. Les mêmes HP sont doublées pour être utilisées également comme sorties directes. En outre, il y a un haut-parleur (numéro 60) pour la triangulation (https://github.com/GRIS-UdeM/ServerGRIS/issues/255).

Si j'essaie d'ouvrir cette configuration avec la version 219, SpatGRIS se plante. 
[SpeakerSetup-Sporobole.xml.zip](https://github.com/GRIS-UdeM/ServerGRIS/files/6534911/SpeakerSetup-Sporobole.xml.zip)

**Comment by Normandeau** [comment]
Ou bel exemple de plantage majeur, comme le setup de Cathal Roche, Probablement dû à la même cause: un certain nombre de sorties de dôme avec les même numéros que ceux des sorties directes, mais surtout **aux mêmes coordonnées**. Pour vérifier cela, j'ai fabriqué, avec 218, un dôme de 16hp avec 16 hp sorties directes à des endroits différents:
![Capture d’écran, le 2021-05-24 à 17 30 11](https://user-images.githubusercontent.com/8959779/119410251-8cf70200-bcb6-11eb-8573-4dd42af37060.jpg)

Mais je ne suis pas capable de l'ouvrir avec 219. J'ai un nouveau message d'erreur (décidément):
![Capture d’écran, le 2021-05-24 à 17 35 35](https://user-images.githubusercontent.com/8959779/119410267-92ece300-bcb6-11eb-8b34-bdddd8ab2e13.jpg)

**Comment by NicolaGiannini** [comment]
C'est la même erreur que je viens d'avoir en essayant de reconstruire le set up de 16 que j'ai vous envoyé avec la version 219. J'avais accidentellement mis toutes les sorties de 1 à 16 comme sorties directes, et donc SpatGRIS affichait ce message d'erreur. L'unique sortie non directe était la 60 (Hp en haut pour la triangulation).

Se pourrait-il que donc dans le cas d'un Setup créé avec une version antérieure à la 219, les sorties directes, qui font aussi partie de la spatialisation, ne soient considérées que comme des sorties directes par la version 219 ?

**Comment by Normandeau** [comment]
Je viens de faire plusieurs tests. Il semble que ce soit le nombre de sorties directes qui soit en cause. Si celui-ci est égal ou plus grand que le nombre de sorties dôme, soit SpatGRIS plante, soit il nous dit qu'il n'y a pas assez de hp. Si on a moins de sorties directes que de sorties dôme, il fait la conversion. Ton dispositif à Sporobole est étrange, Nicola. Toutes tes sorties directes sont au même endroit, en plein centre. Normal?
Je viens de modifier ton setup en ajoutant 3 hp. Je l'ouvre dans 219, ça donne ceci:

![Capture d’écran, le 2021-05-24 à 18 06 35](https://user-images.githubusercontent.com/8959779/119413152-11e41a80-bcbb-11eb-81c0-2ea9f87d50b3.jpg)

Comme se sont les sorties directes qui sont conservées, cela donne comme résultat que tous les hp sont empilés au même endroit:

![Capture d’écran, le 2021-05-24 à 18 09 56](https://user-images.githubusercontent.com/8959779/119413315-625b7800-bcbb-11eb-970b-2b0f15456d61.jpg)

**Comment by NicolaGiannini** [comment]
Robert : Ton dispositif à Sporobole est étrange, Nicola. Toutes tes sorties directes sont au même endroit, en plein centre. Normal?

Réponse : Oui, les sorties directes sont toutes au même endroit au centre. Quand je les ai ajoutées, je ne les ai pas placées à la même place des sorties non directes. Cela parce que la spatialisation est calculée à partir des sorties non directes, c'est juste ? Alors j'ai laissé les sorties directes où elles étaient placées par défaut.

**Comment by Normandeau** [comment]
V2110
Testé avec le setup de Nicola à Sporobole que j'ai modifié pour distinguer les sorties directes. Numéros utilisés: 1 à 16 pour le demi-cercle, 17 pour le top du dôme et 1 à 16 pour les sorties directes. Importation avec succès: les sorties directes sont renumérotées 18 à 33 et conservent leur statut de sorties directes.
Attendre confirmation de Nicola avant de fermer.

![Capture d’écran, le 2021-06-08 à 15 05 12](https://user-images.githubusercontent.com/8959779/121242811-fb1cf680-c86a-11eb-8a24-cd289f020cb5.jpg)

**Comment by NicolaGiannini** [comment]
J’ai ouvert le setup https://github.com/GRIS-UdeM/ServerGRIS/files/6534911/SpeakerSetup-Sporobole.xml.zip et j’ai eu un comportement compatible avec celui de Robert. Donc je dirais que la conversion fonctionne bien. 

J’ajoute une réflexion. 
Depuis (V219) que Samuel a introduit la possibilité de rendre toutes les sorties des sorties directes, dans le cas du setup de Sporobole,  j’avais simplement enlevé toutes les sorties directes de la 1 à la 16. Après j’avais assigné les inputs de SpatGRIS de 1 à 16 aux sorties de 1 à 16. De cette façon de mon DAW je peux gérer ces 16 sorties à la fois comme des sorties directes et à la fois comme sorties de spatialisation. 

![sporobole](https://user-images.githubusercontent.com/35705913/121252896-8a7bd700-c876-11eb-8388-9df8f405ad53.jpg)


Ma question est la suivante. Dans le cas d’un ancien Setup où il y a des sorties directes qui ont le même numéro d’une sortie qui fait partie de la spatialisation, il pourrait être pratique de simplement éliminer cette sortie directe dans la conversion ? Ou peut-être il y a quelque chose qui m’échappe ? Qu’en pensez-vous ?

**Comment by Normandeau** [comment]
Le choix que Samuel a fait est de ne rien éliminer (voir plus haut). Rappelez-vous qu'au début, c'était les hp de la spatialisation qui était éliminés. Samuel a plutôt proposé d'assigner des sorties différentes pour les sorties directes. Je pense que c'est un bon choix. Cela laisse libre l'utilisateur de faire ce qu'il veut avec la nouvelle manière d'assigner les sorties directes. Ou de garder l'ancienne manière.
