### ISSUE TITLE
Binaural & span(s) 

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#249]
V219
Dans un premier temps, super bravo Samuel pour l'optimisation du CPU avec le mode Binaural. Avec la version précédente de SpatGRIS je ne pouvais quasiment pas travailler dans ce mode-là tant mon "cpu usage" était haut (il était beaucoup vers les 100% en fait). Et aujourd'hui j'ai ouvert un "gros" projet sur lequel je travaille (gros étant relatif car je fais attention en mode binaural) et je ne dépasse que rarement les 50%! 

Cela étant, petite requête pour le mode binaural, les spans d'azimuth et d'élévation n'apparaissent sur le SpatGRIS (c'était déjà le cas sur la version précédente 2.18).
Il est vrai que le span d'Azimuth ne change pas grand chose sur le son mais le span d'élévation modifie beaucoup, à la fois le timbre (genre de saturation) et l'amplitude du son. 
D'ailleurs, j'en profite pour demander si c'est normal :)

**Comment by Normandeau** [comment]
Je ne sais pas si c'est normal, mais c'est le choix qu'Olivier avait fait à l'époque. Les Spans sont ignorés en STEREO et en BINAURAL. Pour sauver du CPU? Certainement.

**Comment by MelanieFrisoli** [comment]
Ok je comprends.
Et en fait, je viens d'ouvrir un projet à 72 pistes et le CPU en binaural oscille entre 99 et 100%. Augmenter la taille de la mémoire-tampon aide un peu

**Comment by Normandeau** [comment]
«The BINAURAL mode seems to have suffered a pretty significant performance regression.»
Je viens de comparer SpatGRIS218 et 219 en mode Binaural avec la même session: 47% contre 65%. Donc oui, résultat préliminaire, baisse de rendement ici.

**Comment by belangeo** [comment]
> Je ne sais pas si c'est normal, mais c'est le choix qu'Olivier avait fait à l'époque. Les Spans sont ignorés en STEREO et en BINAURAL. Pour sauver du CPU? Certainement.

Je ne crois pas que les spans impliquent un gros overhead de CPU en Binaural (c'est le HRTF qui est coûteux et non le VBAP). Si je me souviens bien, c'était pour éviter des problèmes de phases dû au fait de sommer le même signal passé dans plusieurs filtres subtilement différents... Ça me semblait une boîte de pandore! Qui sait, peut-être que ça vaudrait le coup d'essayer. En même temps, la localisation n'est déjà pas terrible avec un HRTF générique, ajouter les spans ne fera que rendre la localisation encore plus flou... Mon deux cents!

Pour la stereo, ça ne devrait pa être trop compliqué de considérer la valeur de span en azimuth!

**Comment by SamuelBeland** [comment]
Depuis v.2.1.9, VBAP est appliqué *as is* en BINAURAL avant le transfert HRTF.

Ça veut dire que les spans sont maintenant utilisables en BINAURAL, même si ils ne sont pas affichés pour l'instant.

Par contre, le 2¢ d'Olivier fait beaucoup de sens. Est-ce que c'est souhaitable de permettre les spans en BINAURAL?

> Si je me souviens bien, c'était pour éviter des problèmes de phases dû au fait de sommer le même signal passé dans plusieurs filtres subtilement différents... 

En même temps, le VBAP duplique déjà le signal. Le problème de phase est donc possiblement déjà présent. Considérant tout cela, je pense que ça peut être préférable de laisser le span en BINAURAL, même si la qualité n'est pas encore là où on voudrait qu'elle le soit. C'est pas mal le seul moyen d'avoir rapidement un transfert stéréo.

**Comment by Normandeau** [comment]
À tester avec la nouvelle version en binaural. Il y a surtout le mode STEREO pour transférer en stéréo. Actuellement cependant ce qui me semble plus urgent c'est de réintégrer les sorties directes dans le BINAURAL et le STEREO, voir issue #242

**Comment by Normandeau** [comment]
V2113
Mis dans le manuel
