### ISSUE TITLE
Nombre de sources à 128 maximum

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#250]
Vraiment pas une urgence ni un bug, juste une remarque. 
Je viens de voir que je peux dire à SpatGRIS de me mettre 216 sources (nombre choisi au hasard), est-ce que la limite n'est pas de 128 avec BlackHole? Si oui, peut-être mettre un message d'erreur ou simplement mettre 128 par défaut si l'utilisateur dépasse cette limite?

**Comment by Normandeau** [comment]
La limite actuelle avec BlackHole est de 128. Mais SpatGRIS peut en prendre jusqu'à 256. La limite de BlackHole est conventionnelle, on a décidé que cela était suffisant. On peut aussi décider d'ouvrir davantage... plus tard!

**Comment by devinroth** [comment]
You could compile BlackHole for 256. The only limitation is the speed of a single CPU core.

**Comment by Normandeau** [comment]
Thanks Devin. At this very moment, I think we'll keep it at 128. we have so much other things to worry about...
All the best.

**Comment by Normandeau** [comment]
Bloquer les valeurs maximales à 128. Pour le moment.

**Comment by Normandeau** [comment]
V2110
Limite de 128 sources.
