### ISSUE TITLE
Petites fautes d'orthographe

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#251]
Quand je passe du mode Dôme au mode binaural, j'ai ce message qui me prévient que les pistes direct ont été supprimées et il y a une petite faute : ça devrait être "were" au lieu de "where" non? 
![Screen Shot 2021-05-23 at 7 27 28 PM](https://user-images.githubusercontent.com/74631914/119280002-2d88eb80-bbfd-11eb-8e0c-5647c93167fc.JPG)

**Comment by MelanieFrisoli** [comment]
J'ai remarqué aussi un autre truc dans les typos : 
![Screen Shot 2021-05-24 at 8 20 48 AM](https://user-images.githubusercontent.com/74631914/119348955-868f6880-bc6b-11eb-9b9a-e1a0a0820121.JPG)
"to save" est répété 2 fois

**Comment by MelanieFrisoli** [comment]
Pareil pour "Unsaved Project" 
![Screen Shot 2021-05-24 at 8 57 32 AM](https://user-images.githubusercontent.com/74631914/119351140-264df600-bc6e-11eb-8458-4a97b36182fd.JPG)

**Comment by Normandeau** [comment]
V2110
Corrigées
