### ISSUE TITLE
inputs / outputs

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#252]
J'aime vraiment la nouvelle barre en haut qui te donne des indications sur le projet (f.e, sr, cpu et i/o) mais les inputs restent sur 128 et les outputs sur 8. Est-ce que ces nombres pourraient s'adapter en fonction des entrées et sorties réellement présentes dans notre projet ? 
![Screen Shot 2021-05-24 at 8 08 34 AM](https://user-images.githubusercontent.com/74631914/119345742-4fb75380-bc67-11eb-834e-150e02f1f2b1.JPG)

**Comment by SamuelBeland** [comment]
Ce n'est probablement pas clair, mais les deux dernières colones correspondent aux nombre d'entrées/sorties physiques disponibles sur l'interface audio.

Peut-être devrait-on y mettre le nombre d'entrées/sorties actives? Est-ce que nous devrions informer l'utilisateur/trice lorsque l'interface audio n'a pas assez de ports physiques pour un projet ou un speaker setup?

**Comment by MelanieFrisoli** [comment]
Ok je comprends.
Cependant, comme les autres indicateurs nous montrent des paramètres ajustés pour le projet, je crois que naturellement on aurait tendance à penser que ces chiffres s'ajustent aussi en fonction du projet en cours. 
(Même si j'imaginais bien que si ça ne bougeait pas, ça correspondait aux entrées/sorties disponibles et non celles en cours)

**Comment by Normandeau** [comment]
Inputs et Outputs sont aussi des paramètres ajustés pour le projet. C'est contraint par les interfaces, d'accord, mais 48000Hz et 512 samples, c'est contraint par l'industrie. Pas tellement de liberté de choix là-dedans...
