### ISSUE TITLE
Distance à 1.4 et plus dans Speaker Setup Edition

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#253]
V218
J'ai remarqué un comportement bizarre en refaisant de zéro une configuration de haut-parleurs en mode Dôme. 
En créant un "ring" de 8 speakers, je suis capable de mettre la distance jusqu'à 1.4. 
![Screen Shot 2021-05-24 at 8 18 51 AM](https://user-images.githubusercontent.com/74631914/119346836-b6893c80-bc68-11eb-93aa-fbf2ceae512b.JPG)
Je clique sur "add ring" et aucun hp n'apparaît.
Ensuite je clique simplement dans n'importe quelle boîte à chiffres (# speakers, elev, distance ou angle - sans en changer le nombre, juste un clic et les speakers apparaissent dans SpatGRIS donc le même effet que de cliquer sur "Compute" - ce qui est plutôt bien en fait. Tu n'as pas besoin de cliquer sur "compute" à chaque fois que tu fais un ring)
Et effectivement un ring est bien créé, plus loin que si je faisais un ring à 1.0. 
Mais ils sont en dehors du dernier cercle et il manque le 8ème à l'affichage (celui du bas) :
![Screen Shot 2021-05-24 at 8 24 37 AM](https://user-images.githubusercontent.com/74631914/119347428-82fae200-bc69-11eb-9edd-12baa3735908.JPG)
Question : Est-ce qu'en mode Dôme on peut jouer avec la distance et "sortir" finalement les hp du dôme? 
Aussi, après avoir ajouté les ring, je ne peux plus changer la distance (issue déjà reporté il me semble)

En mode Cube par contre, il ne manque pas le 8ème speaker à l'affichage et les 8 hp à 1.4 de distance sont situés entre les deux derniers cercles. Ici, 3 rings (tous à 8hp, 22° et pas d'élévation mais à des distances respectives de 0.5, 1.0 et 1.4 : 
![Screen Shot 2021-05-24 at 8 32 44 AM](https://user-images.githubusercontent.com/74631914/119348361-c30e9480-bc6a-11eb-939f-578e2b4df653.JPG)

**Comment by Normandeau** [comment]
Le paramètre distance en mode DOME ne devrait pas pouvoir être ajustable. Un oubli surement. De plus le fait de pouvoir mettre des hp à 1.4 dans un dôme est aussi une erreur. Doublé avec le fait qu'en ajoutant un hp avec Add Speaker, celui-ci se met au centre du dôme et n'est plus ajustable par la suite, voir #237, on a une fonction d'édition un peu chaotique!

**Comment by Normandeau** [comment]
On peut même mettre des hp avec une distance de 5! À nous le cosmos!

![Distance à 5](https://user-images.githubusercontent.com/8959779/119374598-c3695880-bc87-11eb-9e9b-bbfc959410de.jpg)

**Comment by Normandeau** [comment]
En fait il ne semble pas y avoir aucune limite quand à la valeur qu'on peut mettre dans Distance quand on utilise la fonction Add Ring (DOME ou CUBE). Même à 50 ça fonctionne. Évidement il n'y a pas d'audio qui passe par ces hp.
En mode CUBE, quand on rouvre la fenêtre d'édition, et qu'on clique dans le textbox de la distance, une valeur s'y affiche automatiquement: 1.73. Quelque soit la valeur entrée > 1,73 c'est cette valeur maximale qui est maintenant possible.
En mode DOME, ces valeurs excentriques sont automatiquement ramenées à 1.00.

**Comment by MelanieFrisoli** [comment]
C'est drôle, chez moi, quand j'utilise "Add Ring", que ce soit en mode Dôme ou en mode Cube, dès que je tape une valeur supérieure à 1.4 dans "Distance" en tapant les chiffres et en appuyant sur "Entrée", il la ramène automatiquement à 1.4.
Par contre, quand je rentre une valeur et que, au lieu d'appuyer sur "Entrée" je me place sur une autre case (# de speakers, Elevation ou Offset), il garde cette valeur.

D'ailleurs c'est la même chose pour les autres boîtes à chiffres présentes ici. J'ai même essayé d'ajouter 480 speakers (mais là SpatGRIS a planté)
Mais voici mon chef d'oeuvre (je ne fais pas de capture d'écran de la fenêtre des speakers car aucun n'apparaît... évidemment)
![Screen Shot 2021-05-25 at 7 36 09 PM](https://user-images.githubusercontent.com/74631914/119581484-a2405f00-bd90-11eb-8ba0-e403518a49e3.JPG)

**Comment by MelanieFrisoli** [comment]
Aussi, il n'est pas possible d'écrire deux chiffres après la virgule.
Par exemple, je voulais une distance à 0.25, en appuyant sur "Entrée" il ramène le nombre à 0.2. 
(Mais pas si je ne presse pas "Entrée" et me déplace dans une autre boîte à chiffres)

**Comment by NicolaGiannini** [comment]
Je confirme tout cela.

**Comment by Normandeau** [comment]
V2110
Les distances maximales sont maintenant contenues dans les valeurs limites: 1.00 pour le dôme et 1.7 pour le Cube quand on fait Add Ring. Même chose pour Add Speaker. Cela a l'air réglé.
