### ISSUE TITLE
Offset Angle utilise 90˚ comme valeur de référence

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#254]
V219
Le calcul d'Offset angle dans Speaker Edition Window part de 90˚ (axe des X), plutôt qu'au 0˚(axe des Y):

![Offset Angle à 90](https://user-images.githubusercontent.com/8959779/119532617-093f2300-bd53-11eb-91e6-843139fa7dcb.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme.

**Comment by MelanieFrisoli** [comment]
V2110
Ça fonctionne chez moi. Avec un offset de 0°, il est bien à 0 sur l'axe des X

**Comment by Normandeau** [comment]
Réglé.
