### ISSUE TITLE
Les DOMES en 2D ne fonctionnent plus.

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#255]
V219
Autant les anciens «dômes» 2D comme octophonique, hexa ou quad, fabriqués avec les anciennes versions, que les nouveaux fabriqués avec 219. Quand un «dôme» ne peut pas afficher de triplets, soit il ne fonctionne pas du tout, soit il ne permet l'utilisation que de deux hp seulement avec une puissance qui dépasse le 0dB numérique:

![Dôme 2D](https://user-images.githubusercontent.com/8959779/119387924-9fae0e80-bc97-11eb-832f-ec61207db969.jpg)

Question: est-ce définitif? Pourquoi ce changement? On dit pourtant depuis de l'utilisation du VBAP, autant par le Zirkonium que par le ServerGRIS, que celui-ci supporte très bien les dispositifs 2D?

**Comment by Normandeau** [comment]
V2110
Cela semble réglé. Testé avec 4, 7 et 8 hp en 2D.

**Comment by NicolaGiannini** [comment]
Cela semble réglé dans mon cas aussi. Testé avec 3, 4 et 16 hp en 2D.
