### ISSUE TITLE
Il n'est plus possible de sélectionner plusieurs HP en même temps dans la fenêtre Speakers Setup Edition

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#256]
V219

Dans mon cas, il n'est plus possible de sélectionner plusieurs HP en même temps dans la fenêtre Speakers Setup Edition, notamment pour effacer tous les hp d’un setup. 
Cela était possible jusqu’à la version 218.

**Comment by Normandeau** [comment]
En fait c'est possible mais il faut d'abord sélectionner un hp en bas de la liste, puis en sélectionner un autre avec la commande Maj. Des fois ça marche, des fois non... Mais ça ne permet pas de les effacer tous en même temps cependant.

**Comment by MelanieFrisoli** [comment]
De mon côté parfois ça fonctionne dans les deux sens (vers le haut et vers le bas) mais il faut que je clique deux fois tout en maintenant Shift et il y a aussi un côté un peu aléatoire concernant la piste de départ.
Et chez moi aussi je ne peux pas les effacer en même temps

**Comment by NicolaGiannini** [comment]
J’ai fait d’autres tests. 

Si je sélectionne de haut en bas, en faisant  Shift+click sur le dernier HP, les HP dans la fenêtre 3D et les vu-mètres des sorties sont sélectionnés. Si je fais clic une autre fois, les HP dans la fenêtre 3D et les vu-mètres des sorties sont de-sélectionnés.


Si je sélectionne de bas en haut, en faisant  Shift+click sur le premier HP, les HP dans la fenêtre 3D et les vu-mètres des sorties sont sélectionnés. Si je fais clic une autre fois, les HP sont sélectionnés aussi dans la fenêtre speaker setup edtiion. 

Je n’arrive jamais à effacer tous les hp ensemble.

**Comment by NicolaGiannini** [comment]
V2110
Je n’arrive pas à sélectionner plusieurs HP en même temps. J'ai essayé avec les méthodes qui marchaient en V219, mais dans mon cas, ça ne marche pas.

**Comment by MelanieFrisoli** [comment]
Même chose sur V2.1.12

**Comment by Normandeau** [comment]
B319
À revoir éventuellement.
