### ISSUE TITLE
Show Sphere ne fonctionne pas dans le mode Dome

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#257]
V219, La sphère rouge n'apparaît pas dans les modes Dôme, binaural et stéréo quand on active "Show Sphere/Cube".
En revanche, le carré rouge lui apparaît bien en mode Cube quand on active "Show Sphere/Cube".

V218, tout apparaît correctement. J'active "Show Sphere/Cube" et je peux changer de mode j'ai toujours la sphère ou le cube qui apparaît.

**Comment by Normandeau** [comment]
V2110
Show Sphere toujours absent.

**Comment by NicolaGiannini** [comment]
Je confirme.

**Comment by MelanieFrisoli** [comment]
Confirmé aussi.

**Comment by Normandeau** [comment]
V2111
Réglé, la sphère est bien là.
