### ISSUE TITLE
BINAURAL fonctionne de manière incohérente par rapport aux sorties directes

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#258]
V219
Dispositif DOME de 36 entrées sur un dôme de 32 hp plus 4 subs (numéros consécutifs).
Dans le dispositif de hp j'ai 4 sorties directes dédiées: 33 à 36 (subs).
Je mets en plus trois entrées au hasard en sorties directes: 4, 12, 24.

![DOME 36 x 36 ](https://user-images.githubusercontent.com/8959779/119694454-3820cc00-be1b-11eb-9402-581c73f234f8.jpg)

Puis je passe en BINAURAL, où je reçois ce message:

![Capture d’écran, le 2021-05-26 à 12 10 07](https://user-images.githubusercontent.com/8959779/119694574-54bd0400-be1b-11eb-9727-d594dc0ccd40.jpg)

Et voici le résultat. La sortie directe 24 et les quatre de 33 à 36 ont sautées. Mais pas 4 et 12! Et elles fonctionnent, mais exclusivement sur la sortie directe. Elles ne sont pas envoyés dans le binaural (sortie 1 et 2)! 

![DOME 36 x 36 Passage au BINAURAL](https://user-images.githubusercontent.com/8959779/119695019-c5642080-be1b-11eb-81b3-e176f8f65e57.jpg)

Et les ControlGRIS 4 et 12 n'ont plus aucun effet. Autrement dit la sortie directe placé sur un canal de spatialisation prend la place de ce canal.

![Capture d’écran, le 2021-05-26 à 12 20 09](https://user-images.githubusercontent.com/8959779/119696244-fdb82e80-be1c-11eb-961e-21536a7267db.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme ce que Robert dit.
J’ai fait des tests et je pense que quand on passe de Dome à Binaural, les sorties directes ne sont maintenues que si elles sont comprises entre 1 et 16 (nombre de canaux du binaural).
D’ailleurs si on revient au mode Dome, les assignations de sorties directes supérieures à 16 ne sont pas rappelées. 

Robert, quand tu dis :

> Et les ControlGRIS 4 et 12 n'ont plus aucun effet. Autrement dit la sortie directe placée sur un canal de spatialisation prend la place de ce canal.

Tu veux dire que tu as placé dans le DAW un ControlGRIS sur la piste envoyée vers un input de SpatGRIS qui est envoyée vers une sortie directe ?

**Comment by Normandeau** [comment]
Excellente remarque au sujet des 16 canaux du BINAURAL. J'étais en train d'explorer cela justement.
Et excellente question aussi au sujet des ControlGRIS. C'est que j'ai utilisé une session DP avec des numéros enregistrés (de ma jolie voix...) afin d'identifier les sources correctement. Et sur toutes les pistes il y a des ControlGRIS. Ceux-ci sont bien sûr annulés par la fonction de sortie directe.
C'est intéressant le fait que les sorties directes correspondant au 16 numéros du dispositif BINAURAL ne soient pas retirés dans ce mode. Par exemple, dans le dôme du 187, comme les subs sont sur 5 et 6, on pourrait imaginer, puisque les sorties n'ont pas sauté et qu'on entend toujours le son, que cela va être enregistré. Alors que ça ne l'est pas évidemment, puisque BINAURAL n'enregistre que 1 et 2.
Source de confusion potentielle complexe.

**Comment by NicolaGiannini** [comment]
v2110
Avec la fonction Stereo Reduction, soit binaural et stereo, la position des HP semble être respectée et elle n’est plus liée au numéro pair ou impair de la sortie. C’est super utile ! 
Je continue à tester.

**Comment by Normandeau** [comment]
Je confirme. Grosse amélioration.
