### ISSUE TITLE
Dans la fenêtre Speaker Setup Edition, en mode CUBE Distance et Elevation se comportent différemment qu'auparavant

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#259]
V219
Je ne sais pas si cela était prévu, mais j'ai remarqué que dans la fenêtre Speaker Setup Edition, en mode CUBE Distance et Elevation se comportent différemment qu'auparavant.

V219

https://user-images.githubusercontent.com/35705913/119709358-1e878080-be2b-11eb-8780-0269796c653a.mov

V218

https://user-images.githubusercontent.com/35705913/119709433-33fcaa80-be2b-11eb-8560-f48c717d0886.mov

Dans V219 en mode CUBE, l'élévation a le même comportement que lorsque nous sommes en mode DOME. Dans V219 en mode CUBE, la distance est maintenant prise en compte à partir du centre du setup (x=0, y=0, z=0).

**Comment by Normandeau** [comment]
Si tu utilises X, Y et Z en mode CUBE, tu vas obtenir le comportement attendu. Au fond la question est de savoir si on doit bloquer Azimuth, Elevation et Distance en mode CUBE. Comme X, Y, Z et Distance le sont en mode DOME?

**Comment by Normandeau** [comment]
V2110
«In CUBE mode, azimuth and elevation angles cannot be directly edited anymore»
On peut toujours éditer Azimuth et Elevation en mode CUBE.

**Comment by MelanieFrisoli** [comment]
Je confirme.

**Comment by NicolaGiannini** [comment]
Je confirme moi aussi. Par contre je me demande si ce n’est pas utile de pouvoir éditer Azimuth Distance et Elevation, au cas où nous aurions besoin de reconstruire une configuration de haut-parleur en mode CUBE pour laquelle nous n'avons que les coordonnées sphériques.

**Comment by Normandeau** [comment]
V2111
Every position parameter in the speaker edition window (x-y-z & azimuth-elevation-distance) can now be freely edited in any mode 
Tes souhaits sont exaucés, Nicola!

**Comment by NicolaGiannini** [comment]
Yes ! :)
