### ISSUE TITLE
Est-ce que les sorties directes dans Speaker Setup Edition sont encore pertinentes?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#260]
V219
Puisque nous avons la possibilité de mettre n'importe quelle entrée sur une sortie directe, est-ce toujours pertinent d'avoir l'option Direct Out lorsqu'on fabrique un speaker setup?
Je viens de répondre à cette question en enlevant l'option Direct Out de mes 4 subs. Lorsque je rouvre ce dispositif, il m'annonce qu'il va le convertir en DOME, alors que je viens à peine de le sauver! Mais c'est parce qu'il veut mettre mes subs à distance de 1.00, comme dans tout dôme qui se respecte. Donc l'option Direct Out est utile afin de nous permettre de placer librement un hp n'importe où dans l'espace du DOME. À mettre dans le manuel.

**Comment by SamuelBeland** [comment]
L'option *Direct Out* pour un speaker sert à l'exclure de la spatialisation.

**Comment by Normandeau** [comment]
V2113
Mis dans le manuel
