### ISSUE TITLE
Save Settings et carte audio In/Out

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#261]
Samuel dit: Je ne suis pas designer graphique.
À ce sujet, on a remarqué que le nouvel emplacement des infos de SpatGRIS, en haut des Inputs est constitué de cinq cases distinctives par leur couleur. Instinctivement on a envie de cliquer dedans pour les modifier, ce qui n'est pas possible. On pense qu'en utilisant une seule couleur pour l'ensemble, ce serait moins le cas.
Cela étant dit c'est peut-être aussi une question d'habitude.

**Comment by MelanieFrisoli** [comment]
Je confirme, mon premier réflexe a été de cliquer dessus pour ajuster ma f.e. Je pense que c'est bien de se fier à ses premières intentions et premiers réflexes. Si c'était de la même couleur ou en ajoutant la mention "infos", alors notre souris ne serait pas attirée par ça.

**Comment by NicolaGiannini** [comment]
Je suis d'accord avec vous. Moi aussi j'avais essayé de cliquer dessus pour changer les paramètres.

**Comment by MelanieFrisoli** [comment]
V2.1.10
On peut en effet maintenant cliquer sur la section des infos pour afficher les préférences. C'est super pour la f.e et la buffer size mais je ne sais pas si c'est utile que les préférences s'ouvrent quand on clique sur le nombre d'inputs et d'outputs, sachant qu'on ne peut pas les changer. 

Aussi, je ne sais pas si c'est possible mais un menu déroulant par paramètre serait encore mieux que l'ouverture des préférences. 

À propos, je ne sais pas si c'est normal mais en travaillant sur un second écran, le menu préférences s'ouvre toujours sur mon écran de laptop. Ce qui n'est pas le cas des autres logiciels que j'utilise. Le menu s'affiche sur l'écran que j'utilise.

**Comment by NicolaGiannini** [comment]
Je confirme tout ce que dit Mélanie.
Je me demande moi aussi : 

> si c'est utile que les préférences s'ouvrent quand on clique sur le nombre d'inputs et d'outputs.

Une question de termes : dans la partie "Controls" on appelle les inputs "Sources" tandis que dans la partie en haut on indique "Inputs". En fait les inputs en haut indiquent le chiffre maximal d'inputs mis à disposition par la carte de son. Probablement il pourrait être bien d'utiliser toujours le mot "input" ?

**Comment by Normandeau** [comment]
V2110
N'oubliez pas de mettre le no de version quand vous faites une issue, ou quand vous ajoutez en premier un commentaire d'une nouvelle version.

Ensuite. Au contraire de vous, je trouve bien qu'en cliquant sur les paramètres, la fenêtre Settings s'ouvre. Quand on passe d'un studio à l'autre, c'est très pratique d'avoir accès à Inputs/Outputs, ce qui correspond aux entrées matérielles et logicielles. Dans mon cas, les Inputs ne sont jamais sauvegardées (BlackHole) quand je passe d'un studio à l'autre. SpatGRIS remet toujours le micro par défaut. Pourtant c'est l'interface audio, donc les Outputs, qui change... et qui est conservé! J'en déduis que SpatGRIS ne garde pas les préférences d'Inputs/Outputs, mais qu'il choisit celles qui sont définies par CoreAudio dans les Préférences Système. Vérification faite: effectivement le micro était choisi comme entrée. À corriger? Bonne question. Si SpatGRIS est capable d'interpréter correctement les interfaces de CoreAudio, cela pourrait se régler automatiquement. En sortie en tout cas, mon Mac s'adapte à chaque carte de son déjà utilisée.

Finalement, relativement à la distinction Inputs/Sources, elle est importante: Les Inputs c'est la carte de son, en général Blackhole en ce qui nous concerne. Les sources, c'est le nombre de canaux audio du projet venant du DAW. Distinct du nombre des inputs, évidemment.

**Comment by belangeo** [comment]
> À propos, je ne sais pas si c'est normal mais en travaillant sur un second écran, le menu préférences s'ouvre toujours sur mon écran de laptop. Ce qui n'est pas le cas des autres logiciels que j'utilise. Le menu s'affiche sur l'écran que j'utilise.

Haha, ça c'est une issue de Juce qui a pratiquement toujours été là, faut croire qu'ils ne veulent pas la corriger! Vous pouvez toujours calculer l'offset entre la position absolue du clic de la souris et la position du popup, puis déplacer le popup programatiquement... Ou vous fixez les sources de Juce!

**Comment by MelanieFrisoli** [comment]
> SpatGRIS ne garde pas les préférences d'Inputs/Outputs, mais qu'il choisit celles qui sont définies par CoreAudio dans les Préférences Système. 

Exact ! J'ai fermé SpatGRIS, changé mes paramètres dans les Préférences Système et SpatGRIS les a automatiquement pris à sa réouverture.
J'ai essayé de changer les Préférences Systèmes quand SpatGRIS est ouvert, mais là (ouf) il garde ses réglages. 

J'ai l'impression que ce serait peut-être mieux que SpatGRIS soit capable de conserver nos derniers réglages 
(Si je prends l'exemple de Live, il se rouvre toujours sur mon dernier setting - sauf si la carte son est débranché, là il choisit l'avant-dernier que j'ai utilisé)

**Comment by NicolaGiannini** [comment]
Dans mon cas SpatGRIS prend automatiquement les paramètres du système, quand l’on l’ouvre et que la carte de son qui était sélectionnée lors de la dernière utilisation n’est pas présente. Par contre, si la carte de son est toujours connectée et que je change les cartes en CoreAudio, cela n’affecte pas SpatGRIS.

**Comment by SamuelBeland** [comment]
v2.1.11

Je n'arrive pas à reproduire le bug.
SpatGRIS prend toujours ses derniers réglages d'entrées/sorties à l'ouverture.

Peut-être que ça a été accidentellement réglé dans v2.1.11 ?

**Comment by Normandeau** [comment]
La question de la fenêtre des Settings qui apparaît dans le même écran que SpatGRIS semble réglé, pour moi en tout cas. On verra pour les autres.
Quant aux Settings, lorsqu'on ouvre SpatGRIS la première fois, donc sans que ses préférences n'aient été écrites, il prend automatiquement les valeurs des préférences système. Après les avoir changées et avoir quitté SpatGRIS, ses préférences sont écrites. Notez qu'elles portent maintenant le no de version de SpatGRIS.
Si on change de studio, donc de dispositif, si SpatGRIS ne retrouve pas la carte audio de ses préférences (donc essentiellement celle qui est affecté à la sortie, puisqu'en entrée, c'est plutôt systématiquement Blackhole), il choisit automatiquement les réglages en entrée et en sortie du système.
À confirmer.

**Comment by Normandeau** [comment]
Question: pourquoi le Save de Settings est-il un leurre? Un Save devrait être un Save, non?

**Comment by MelanieFrisoli** [comment]
v2.1.11
Je confirme, la fenêtre des settings s'ouvre bien sur le même écran que SpatGRIS. Maintenant c'est juste la fenêtre d'ouverture (celle qui ne reste pas longtemps) qui s'ouvre sur mon laptop et pas sur l'écran supérieur.

Quant aux changements de dispositifs, J'ai donc réglé "blackhole" en entrée et mon interface en sortie. Je ferme SpatGRIS, je débranche ma carte son. Je rouvre SpatGRIS et en entrée j'ai mon micro de laptop et en sortie les haut-parleurs de mon laptop. Est-ce qu'il ne devrait pas garder Blackhole en entrée tout de même ? 

Pour le Save : Est-ce que la bonne nomenclature ne serait pas "Apply" ?

**Comment by NicolaGiannini** [comment]
V2111

Je confirme que la fenêtre des Settings apparaît dans le même écran que SpatGRIS.

Je confirme également que si SpatGRIS ne retrouve pas la carte audio de ses préférences, il choisit automatiquement les réglages en entrée et en sortie du système. Dans mon cas, pour que Blackhole soit retenue comme carte d'entrée audio, elle doit être sélectionnée comme carte d'entrée audio dans les préférences du système, au cas où je déconnecterais l'autre carte externe.

J'ajoute une note par rapport à un comportement que je pense lié à l'écriture des préférences et au nombre des signaux audio envoyés de SpatGRIS à la carte de son externe lorsqu'on choisit une carte de son externe au premier démarrage ou quand SpatGRIS ne retrouve pas la carte audio de ses préférences. Dans ces cas, il semble que SpatGRIS puisse modifier la carte son, mais pas le nombre de canaux audio disponibles.

Exemple testé dans le studio Hexa.

Au premier démarrage de SpatGRIS ou si SpatGRIS ne retrouve pas la carte audio de ses préférences, comme on sait, il choisit automatiquement les réglages en entrée et en sortie du système. 
Si après cela :

- je ferme SpatGRIS
- je branche la carte du son externe
- je redémarre SpatGRIS
- je sélectionne la carte de son externe, alors SpatGRIS envoie correctement l'audio à la carte externe, mais par contre seulement aux canaux 1 et 2.

![Schermata 2021-06-17 alle 13 39 56](https://user-images.githubusercontent.com/35705913/122448575-e3ccc000-cf72-11eb-9651-688aeefafeda.jpg)


Pour que SpatGRIS envoie l'audio à tous les canaux de la configuration, je dois redémarrer le programme.

Il semble que SpatGRIS puisse modifier la carte son, mais pas le nombre de canaux audio disponibles (la carte sélectionnée dans les préférences du système a deux canaux).

**Comment by SamuelBeland** [comment]
@Normandeau :
> Question: pourquoi le Save de Settings est-il un leurre? Un Save devrait être un Save, non?

Le bouton est un leurre en ce moment puisque la plupart des settings utilisateurs doivent être enregistrés automatiquement de toute façon à la fermeture (position de la fenêtre, speaker setup actif, etc). C'est tellement plus simple de faire ainsi!

Mais évidement, on ne peut pas laisser un bouton qui ne fait pas ce qu'il pretend faire.

Ça serait assez simple de faire en sorte que les paramètres de la fenêtre settings ne soient enregistrés que si et seulement si l'utilisateur appuie sur "save". Par contre, je me questionne à savoir si c'est vraiment un comportement utile? Existe-t-il un scénario où c'est souhaitable de __ne pas__ enregistrer automatiquement tous les settings utilisateurs à la fermeture (incluant les settings audio et le port OSC)?

C'est pourquoi je propose de garder le comportement actuel de sauvegarde automatique mais de changer le bouton "save" par "close" ou "ok".

@MelanieFrisoli :
> Pour le Save : Est-ce que la bonne nomenclature ne serait pas "Apply" ?

"Apply" serait excellent aussi, mais il faudrait que les settings ne soient pas appliqués au fur et à mesure comme c'est le cas actuellement.

> Quant aux changements de dispositifs, J'ai donc réglé "blackhole" en entrée et mon interface en sortie. Je ferme SpatGRIS, je débranche ma carte son. Je rouvre SpatGRIS et en entrée j'ai mon micro de laptop et en sortie les haut-parleurs de mon laptop. Est-ce qu'il ne devrait pas garder Blackhole en entrée tout de même ?

Ha, je comprend mieux le problème maintenant!

@NicolaGiannini 
> Au premier démarrage de SpatGRIS ou si SpatGRIS ne retrouve pas la carte audio de ses préférences, comme on sait, il choisit automatiquement les réglages en entrée et en sortie du système.
> Si après cela :
> - je ferme SpatGRIS
> - je branche la carte du son externe
> - je redémarre SpatGRIS
> - je sélectionne la carte de son externe, alors SpatGRIS envoie correctement l'audio à la carte externe, mais par contre seulement aux canaux 1 et 2.

Bonne trouvaille! C'est quelque chose qui m'avait échappé.

**Comment by SamuelBeland** [comment]
Il y a réellement 3 problèmes discutés dans ce billet:

1. Si l'interface de sortie n'est plus disponible, toute la config audio est remplacée par la configuration système.
2. Le bouton "save" dans la fenêtre settings est un leurre.
3. Changer d'interface de sortie ne met pas à jour nombre de sorties disponibles

**Comment by SamuelBeland** [comment]
Au sujet de "Le bouton save dans la fenêtre settings est un leurre", je réalise que la stratégie "Apply" ne peut pas fonctionner : nous avons besoin de charger les interfaces audio au fur et à mesure qu'elles sont sélectionnées pour n'afficher que les taux d'échantiollonages et les _buffer sizes_ partagés par les deux interfaces.

J'y vais pour "Close"?

**Comment by MelanieFrisoli** [comment]
Parfait pour "Close"

**Comment by MelanieFrisoli** [comment]
V2.1.11
Ce matin, je pars de chez moi donc je débranche mon interface audio. Je rouvre SpatGRIS en arrivant à la faculté, sans interface branchée. Et là, il m'a gardé Blackhole en entrée alors que dans mes préférences système c'est bien le built-in input qui est sélectionné

![Screen Shot 2021-06-18 at 10 10 11 AM](https://user-images.githubusercontent.com/74631914/122574592-cdc80980-d01d-11eb-995b-7bbb6c705102.JPG)

Je dois préciser qu'un truc étrange s'est passé avant ça. Chez moi ce matin, j'ai ouvert SpatGRIS v2.1.8. Il a planté et au moment où il me prévient et me demande si je veux ignore/report ou reopen SpatGRIS2.1.8, mon ordinateur a ouvert SpatGRIS2.1.11 sans que je ne lui demande rien. Je dois avoir un fantôme dans mon laptop qui me fait des blagues.

**Comment by Normandeau** [comment]
V2112
Close au lieu de Save et carte de son inexistante remplacée par les préférences son. Tout semble OK. À confirmer à l'usage.

**Comment by NicolaGiannini** [comment]
V2112

> Close au lieu de Save et carte de son inexistante remplacée par les préférences son.

Je confirme.



> Il semble que SpatGRIS puisse modifier la carte son, mais pas le nombre de canaux audio disponibles (la carte sélectionnée dans les préférences du système a deux canaux).

V2112, ça semble réglé.

**Comment by MelanieFrisoli** [comment]
V2112 

SpatGRIS conserve bien BlackHole en entrée même si je débranche mon interface audio, super ! 
(**exemple :** SpatGRIS est chez moi sur les réglages habituels - BlackHole et interface Saffire - je ferme SpatGRIS et débranche l'interface audio - je rouvre SpatGRIS et c'est toujours BlackHole en entrée et Built-in en sortie (la même que dans mes Préférences Système))

**Autre test par la suite :** si je ferme à nouveau SpatGRIS et que je change mes préférences système (juste la sortie) et que je rouvre SpatGRIS, il a gardé "built-in output".

Donc si je comprends bien, il va prendre la sortie des préférences système quand il ne trouve plus l'interface audio qu'on lui avait donné et n'en changera plus tant que celle qui est sélectionnée est disponible (ce qui est pas mal en fait. À inscrire dans le manuel ?) 

![Outputs](https://user-images.githubusercontent.com/74631914/123552556-b2a77900-d744-11eb-9e59-065741f0235a.JPG)


Et très bonne nouvelle, si je redémarre mon ordi, il garde bien mes derniers settings.

**Comment by MelanieFrisoli** [comment]
V2112
Je me permets une petite remarque : Si je rebranche mon interface audio quand SpatGRIS est ouvert, on dirait qu'il n'arrive pas à faire la mise à jour des cartes son disponibles. Je dois alors le fermer et le rouvrir pour sélectionner mon interface.

**Comment by Normandeau** [comment]
V2113
Chez moi, avec une MADIFace, pas de soucis. Dès que celle-ci est rebranchée, même à chaud, SpatGRIS la reconnait. Donc cas particulier d'interface ou de pilote. Il y en a tellement...
