### ISSUE TITLE
Une fois qu’un input est assigné à une sortie directe, il n’est plus possible de l’assigner au mode spatialisation.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#262]
Une fois qu’un input est assigné à une sortie directe, il n’est plus possible de l’assigner au mode spatialisation. Il faut toujours choisir une sortie directe. Peut-être que l’on pourrait donner la possibilité de ne pas choisir de sortie directe et de réaffecter l’input au mode de spatialisation.

![Schermata 2021-05-31 alle 15 40 56](https://user-images.githubusercontent.com/35705913/120235025-2bd7ad00-c227-11eb-8ed2-198dae38be2c.jpg)

**Comment by Normandeau** [comment]
J'apporte ici une nuance. Si le dispositif de hp ne comporte pas de sorties directes, c'est exactement la situation décrite par Nicola. Par contre, si le dispositif inclue des sorties directes, il est alors possible de désactiver l'envoi vers les sorties directes grâce à la petite barre de séparation, ici entre les sorties directes (11-12) et les sorties spatialisées (01-10):

![Capture d’écran, le 2021-06-01 à 13 42 52](https://user-images.githubusercontent.com/8959779/120368385-ffcc3280-c2df-11eb-8ec2-ab220097f38f.jpg)

**Comment by Normandeau** [comment]
V2110
Réglé.
