### ISSUE TITLE
Feu d'artifice rouge en redimensionnant les fenêtres

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#265]
V2110
Le problème de comportement des VU mètres dans Speaker Setup Edition est réglé.
Mais il a laissé la place à un autre genre de feu d'artifice:
- quand on modifie les dimensions de la fenêtre générale de SpatGRIS
- quand on modifie les dimensions de la fenêtre 3D.
Voir la vidéo (beau rouge cependant...:

https://user-images.githubusercontent.com/8959779/121095235-f0f0ee80-c7bd-11eb-829f-d60aa14e2625.mov

**Comment by NicolaGiannini** [comment]
Je confirme.

**Comment by MelanieFrisoli** [comment]
Confirmé aussi mais ce n'est pas rouge chez moi, c'est noir (beaucoup plus triste) - MacOS High Sierra -

https://user-images.githubusercontent.com/74631914/121369913-41756280-c90a-11eb-8156-9b3f514976b2.mp4

**Comment by Normandeau** [comment]
Cathal a écrit:
V2.1.10A small matter but I noticed a change that is perhaps unintended in this version.. in Catalina the 3D view window flashes continuously red when adjusting it’s scale.

**Comment by Normandeau** [comment]
V2111
Réglé.
