### ISSUE TITLE
Reset Input Position ne fonctionne plus

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#266]
V2110
Même après que la séquence ait été fermée dans DP. Et même après avoir fermer DP! À valider dans les autres séquenceurs.

**Comment by NicolaGiannini** [comment]
Je confirme la même chose avec Logic et Reaper. Je pense aussi avec Live (10), mais je laisse confirmer à Mélanie.

**Comment by MelanieFrisoli** [comment]
Je vous confirme dès que possible. Là mon ordi est en surchauffe. Dès que j'ai SpatGRis2.1.10 + Live 11, il marche vraiment au ralenti. Ça m'inquiète! Je vous reviens dès qu'il va mieux...

**Comment by Normandeau** [comment]
J'assigne ControlGRIS à trois numéros différents respectivement: 1, 9 et 17.
Les trois s'inscrivent dans la fenêtre 3D.
J'utilise la fonction Reset Input Position entre chacune des opérations suivantes:
- Je désactive l'OSC
- J'enlève ControlGRIS de la session
- Je ferme la session
- Je ferme DP.

Voici ce qui reste:

![Capture d’écran, le 2021-06-08 à 18 28 46](https://user-images.githubusercontent.com/8959779/121265991-c0758700-c887-11eb-9c9f-6e8555a94015.jpg)

**Comment by MelanieFrisoli** [comment]
Je confirme dans Live 10 et 11.
Aussi testé lors des étapes suivantes :

- après avoir enlevé ControlGRIS de la session
- après avoir fermé Live

**Comment by Normandeau** [comment]
V2111
Reset Input Position semble corrigé.

**Comment by NicolaGiannini** [comment]
V2111
Il semble réglé dans mon cas aussi.
