### ISSUE TITLE
Stereo Reduction - Si les sorties choisies en stéréo n'existent pas dans le Speaker Setup, SpatGRIS3 ne peut pas enregistrer

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#267]
v2110

Stereo Reduction - s'il n'y a pas de sorties 1 et 2 dans le Speaker Setup, SpatGRIS utilise les deux premières sorties ayant le numéro le plus bas comme sortie stéréo.
Notamment vous pouvez tester avec le setup du B187. Dans ce Setup les sorties ayant le numéro le plus sont la 5 et la 6. Lorsqu’on active la réduction stéréo, le signal est envoyé à ces deux sorties. 
Si par contre les sorties 1 et 2 sont présentes dans le Setup, lorsqu’on active la réduction stéréo, le signal est envoyé à ces 2 sorties.

**Comment by MelanieFrisoli** [comment]
V2110
Je confirme

**Comment by Normandeau** [comment]
On avait imaginé, depuis un certain temps déjà, de laisser le choix des sorties à l'utilisateur pour les modes STEREO et BINAURAL. L'exemple de Nicolas est bon, car 5 et 6 dans le B187, ce sont les subs!

**Comment by Normandeau** [comment]
Speaker Setup du B187, avec sorties directes 5-6 et 31-61.
SpatGRIS en mode Stereo, Recording AIFF et Interleaved.
Ça crashe à tous les coups.

**Comment by Normandeau** [comment]
V2111
Une précision. Stereo Reduction - s'il n'y a pas de sorties 1 et 2 dans le Speaker Setup, SpatGRIS utilise les deux premières sorties ayant le numéro le plus bas comme sortie stéréo. Mais cela fait crasher SpatGRIS en mode Recording. De plus, si le speaker setup comporte des sorties directes qui ne sont pas 1 et 2, quelles soient utilisées ou non (par exemple 5-6), cela fait planter SpatGRIS en Recording.

**Comment by Normandeau** [comment]
Autres précisions, avec le setup du B187 (pas de sorties 1-2).
Ça crashe la première fois qu'on essaie d'enregistrer, mais pas nécessairement à tous les coups. Après, voici ce que ça donne:
DOME
1. STEREO
1.1. WAV ou AIFF et Mono: deux fichiers séparés vides
1.2. WAV ou AIFF et INTERLEAVED: un fichier stéréo vide

2. BINAURAL
2.1. WAV ou AIFF et Mono: deux fichiers séparés vides
2.2. WAV ou AIFF et INTERLEAVED: un fichier stéréo vide

Testé seulement sur de très courts enregistrements.

**Comment by NicolaGiannini** [comment]
V2112
Maintenant c’est possible de choisir les sorties pour la réduction stéréo. Et même s’il n’y a pas de sorties 1 et 2 dans le speaker setup (exemple le B187) on peut choisir d’autres sorties et l’enregistrement stereo fonctionne. 

Je partage deux réflexions. 

1 Il faudrait probablement ajouter “Stereo Reduction Ch”, ou quelque chose d’autre, pour indiquer que Left et Right font référence aux canaux de la réduction. Ou la section Left et Right pourrait simplement être plus alignée avec “Stereo Reduction”?

2 Il est vraiment utile que nous puissions maintenant décider des canaux pour la réduction ! Dans le cas d'une configuration de haut-parleurs qui ne comprend pas les sorties 1 et 2, maintenant pour pouvoir écouter la réduction en utilisant la carte interne de l’ordi, il faut créer les sorties 1 et 2 et les mettre en sortie directe. Je pense que c'est la seule façon d’envoyer la réduction à la carte interne. Nous pourrions peut-être mentionner cela dans le manuel ?

**Comment by Normandeau** [comment]
Oui pour le manuel.

**Comment by Normandeau** [comment]
V2113
L'absence de sorties 1-2 dans le Speaker Setup ne fait plus crasher SpatGRIS. Mais cela peut être encore une situation embêtante, dont je me suis rendu compte en discutant avec un utilisateur.
Mettons un exemple, le dispositif du B187, qui ne comporte pas de sorties 1-2:
En passant du studio à la maison, je me mets en STEREO ou en BINAURAL, mais je ne peux pas car le setup n'a pas de sorties 1-2 et je reçois le message d'erreur!
Naïvement, je me suis dit, je vais mettre la sortie de SpatGRIS sur les hp du Mac. Mais ça ne change rien, c'est le speaker setup qui est le boss ici! Une suggestion?

![Capture d’écran, le 2021-07-08 à 16 36 58](https://user-images.githubusercontent.com/8959779/124988263-c4720180-e00b-11eb-8938-a7e0d2b554bf.jpg)

**Comment by NicolaGiannini** [comment]
Robert,
Si je comprends bien, la solution consiste à créer les sorties directes 1 et 2 dans le Speaker Setup, puis à affecter ces sorties à la réduction.

**Comment by Normandeau** [comment]
Exact. Ce n'est pas très élégant, mais il y a probablement peu de dispositif sans sorties 1 et 2, alors ça n'affectera pas grand-monde. Je l'ai mis dans le manuel.

**Comment by MelanieFrisoli** [comment]
V2114
Quand je charge le Speaker Setup du B-187 et que j'essaie de passer en stéréo ou en binaural pour travailler à la maison, j'ai un message d'erreur comme ceci : 

![Screen Shot 2021-07-15 at 5 35 31 PM](https://user-images.githubusercontent.com/74631914/125861083-7e3eb151-c6d4-48a2-a587-bb937f401ff0.JPG)

Je ne sais pas si le libellé est approprié. Est-ce qu'on ne pourrait pas dire simplement à l'utilisateur "please choose available outputs for stereo reduction" ou un message directement sur le logiciel genre en rouge qui dirait "No outputs have been selected for stereo reduction", simplement pour rappeler à l'utilisateur de faire cette étape ?

**Comment by Normandeau** [comment]
Même speaker setup (heureusement qu'on l'a celui-là!).
En effet ce nouveau message d'erreur... est erroné! Il y a un en effet un output patch disponible, n'importe quel hp du dispositif est disponible. L'absence de sorties 1-2 dans un setup pose problème selon moi. À cause de la possibilité de vouloir passer sur ces sorties pour l'écoute à la maison sur les hp de l'ordi. Certes il existe la solution de créer deux hp supplémentaire avec sorties 1-2. Mais une fonction automatique qui permettrait à SpatGRIS de reconnaitre la carte son du Mac serait pas si mal. Ce qui n'est pas le cas actuellement. En changeant ma RME pour les hp du Mac, cela ne change rien dans SpatGRIS sur le plan de sorties stéréo. Curieux non? Une raison à cela? Le speaker setup a préséance sur le hardware?

**Comment by MelanieFrisoli** [comment]
Complètement d'accord avec toi.
Même si c'est un setup rare, on va avoir beaucoup d'étudiants qui vont y faire face en travaillant dans le B-187 et en rentrant chez eux pour continuer à travailler. Modifier le Speaker Setup à chaque fois qu'on change d'endroit peut s'avérer frustrant.

**Comment by NicolaGiannini** [comment]
Je suis d'accord qu'un setup qui n'a pas les sorties 1 et 2 peut être problématique lord d'une réduction stéréo.

Je me demandais s'il serait possible pour SpatGRIS de créer automatiquement les sorties (directes) 1 et 2 en arrière-plan dans le cas d'une configuration qui ne possède pas ces sorties, une fois que la réduction stéréo est activée.
SpatGRIS pourrait alors indiquer les sorties 1 et 2 comme étant le routage stéréo par défaut et les créer en arrière-plan si elles n'existent pas. Le routage stéréo serait toujours éditable.

**Comment by Normandeau** [comment]
V2115
Réduction stéréo: a dream came true! Vraiment excellent. Testé avec toutes les combinaisons de paires de ma carte son, Ça fonctionne. Test suppl. avec les vôtres?
Et si on passe de la carte son aux hp du Mac, ça fonctionne aussi! (ne pas oublier de choisir les hp du Mac pour le Son dans les Préférences...). Corrections à faire dans le manuel.

**Comment by MelanieFrisoli** [comment]
Je confirme, cette nouvelle option est géniale ! 
J'ai alterné entre différentes configurations et SpatGRIS3 s'adapte instantanément aux sorties du nouveau setup. C'est vraiment parfait et ce sera tellement plus simple pour les utilisateurs. Bravo !

**Comment by Normandeau** [comment]
Quand j'écrivais «a dream came true»! Je viens de retrouver l'issue où j'ai posté ce souhait la première fois avec David #101 
V014 16 janvier 2018!!!

**Comment by NicolaGiannini** [comment]
Ça fonctionne très bien !
C’est vraiment très très pratique, bravo !

**Comment by NicolaGiannini** [comment]
V2115
Bonjour,
la réduction stéréo fonctionne bien en écoute, mais dans mon cas l'enregistrement de la réduction n'est pas possible s'il n'y a pas de sorties 1 et 2 dans le Speaker Setup.
J'obtiens ce message : 

![Schermata 2021-08-02 alle 13 16 41](https://user-images.githubusercontent.com/35705913/127901543-fef6f6fa-262e-4da6-9554-34c1c9281388.jpg)

Si j'ajoute les deux sorties directes, 1 et 2 l'enregistrement est possible (notamment si j'ajoute les sorties directes 1 et 2 au Setup du B187)

Si dans le Speaker Setup il y a déjà les sorties 1 et 2, l'enregistrement est possible (notamment si on utilise le Setup du Hexa).

**Comment by Normandeau** [comment]
V2116
Confirmé, Même si on change l'interface pour les haut-parleurs du Mac, et c'était cela l'idée au départ, l'écoute fonctionne bien mais l'enregistrement est impossible avec un setup qui n'a pas de sorties 1-2.

**Comment by NicolaGiannini** [comment]
V300
J'ai le même comportement. Même si on change l'interface pour les haut-parleurs du Mac, l'écoute fonctionne bien mais l'enregistrement est impossible avec un setup qui n'a pas de sorties 1-2.

**Comment by Normandeau** [comment]
V301
L'enregistrement fonctionne effectivement maintenant en stéréo, même avec un setup sans sorties 1-2 (comme celui du B187). Malheureusement tous les enregistrements stéréo sont automatiquement faits en 44,1kHz, quelque soit les réglages de l'ensemble du système, tous réglés à 48Khz par exemple. Testé en .wav et .aiff, en multiple mono et en interleaved.

**Comment by Normandeau** [comment]
Tests supplémentaires. Tous les enregistrements sont en 44,1 kHz, même les multiphoniques. À valider par tous.

**Comment by SamuelBeland** [comment]
v3.0.1

Ici tout fonctionne correctement.

Testé sur Windows 10, Ubuntu 18 et MacOS Catalina.

**Comment by Normandeau** [comment]
Après avoir redémarré l'ordi, tout est OK. ;-)( Bézarre!

**Comment by Normandeau** [comment]
Résolu finalement?

**Comment by NicolaGiannini** [comment]
V301
Dans mon cas, il semble reglé. L'enregistrement stéréo maintenant fonctionne avec un setup qui n'a pas de sorties 1-2. Testé avec le setup du B187, mono files et interleaved, WAV et AIFF.

**Comment by Normandeau** [comment]
Résolu.
