### ISSUE TITLE
Affichage des triplets: seulement en mode DOME

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#268]
V2.1.10
Si je ferme et rouvre SpatGRIS dans le même studio (B-187 en ce moment), il n'est plus en mode dôme mais en mode cube automatiquement. Ce qui donne ceci : 
Est-ce normal ? 
![Screen Shot 2021-06-10 at 11 19 17 AM](https://user-images.githubusercontent.com/74631914/121551821-f75db100-c9dd-11eb-8b89-8966d3c919cb.JPG)

**Comment by SamuelBeland** [comment]
C'est "normal" : comme ce speaker setup a été enregistré avant v2.1.9, le mode (CUBE ou DOME) est déduit selon la position des speakers.

Il y a quelques setups comme le tien qui ont des positions étranges : même si ils sont en mode DOME, les speakers ne sont pas réellement placés sur un dôme. Par exemple, le speaker branché sur le patch 55 :
![Untitled](https://user-images.githubusercontent.com/39448259/121739397-8a274a00-cac9-11eb-9260-7d6fa2a5432a.png)

SpatGRIS assume donc un mode CUBE. Après avoir enregistré le speaker setup avec v.2.1.10, ça devrait arrêter.

**Comment by Normandeau** [comment]
Vérifié?

**Comment by MelanieFrisoli** [comment]
Oui je viens de vérifier chez moi. Avec le template "Dome32Subs2 UdeMUFX+" SpatGRIS s'ouvre par défaut en mode Cube. 
J'ai fait le tour des templates du dossier "Dôme" et voici le résultat :

- "GRISpeaker Dome4Subs1" -> Ok
- "GRISpeaker Dome5Subs1" -> Ok
- "GRISpeaker Dome7Subs1" -> Ok
- "GRISpeaker Dome8 6+2Subs2" -> Ok
- "GRISpeaker Dome10Subs2" -> Mode CUBE
- "GRISpeaker Dome16Subs2 MicaDome" -> Ok
- "GRISpeaker Dome16Subs2 UdeM" -> Ok
- "GRISpeaker Dome19Subs2 SCRIME" -> Ok
- "GRISpeaker Dome20Sub4 GRIS" -> Ok
- "GRISpeaker Dome20Subs2 Gainesville" -> Ok
- "GRISpeaker Dome23Subs2 ZKM Minidome" -> Ok
- "GRISpeaker Dome24Subs2 MicaDome" -> Ok
- "GRISpeaker Dome24Subs2 NOTAM" -> Ok
- "GRISpeaker Dome31Subs1 Satosphere" -> Mode CUBE
- "GRISpeaker Dome32Subs2 UdeMUFX+" -> Mode CUBE
- "GRISpeaker Dome36Subs3 CEMIcircles" -> Ok
- "GRISpeaker Dome43Subs4 ZKM Kubus" -> Ok
- "GRISpeaker Dome44 Sphere" -> Ok
- "GRISpeaker Dome64" -> Mode CUBE
- "GRISpeaker Dome80" -> Mode CUBE
- "GRISpeaker Dome96" -> Mode CUBE
- "GRISpeaker Dome128" -> Message d'erreur suivant : 

![Screen Shot 2021-06-14 at 2 45 44 PM](https://user-images.githubusercontent.com/74631914/121943153-4a59a000-cd1f-11eb-8163-ff5af979a54e.JPG)

**Comment by MelanieFrisoli** [comment]
Tant que j'y étais, j'ai testé les templates du dossier "Cube" et tout va bien.

**Comment by NicolaGiannini** [comment]
Je confirme tout ce que Mélanie dit.

En fait  notamment dans ”GRISpeaker Dome10Subs2" -> Mode CUBE les HP 9 et 10 ont un DISTANCE de 0.60.

**Comment by MelanieFrisoli** [comment]
V2.1.10
Les speaker setup qui s'ouvrent en mode Cube alors qu'ils proviennent du dossier de template "Dome" présentent également un problème d'affichage avec "Show Speakers Triplets" mais j'imagine que c'est lié. 
Ce problème n'est cependant pas présent dans la v2.1.8 (puisque ces templates s'ouvraient directement en Dôme j'imagine)

Voici deux exemples : 
- Le template "GRISpeaker Dome32Subs2 UdeMUFX+", juste une barre blanche apparaît entre les deux subs 

![Screen Shot 2021-06-15 at 2 02 09 PM](https://user-images.githubusercontent.com/74631914/122102231-38413580-cde3-11eb-8ddd-58b495cf72e4.JPG)

Le même setup dans v2.1.8 (en mode Dôme) : 

![Screen Shot 2021-06-15 at 2 02 42 PM](https://user-images.githubusercontent.com/74631914/122102289-468f5180-cde3-11eb-987d-6b581ad5c5b9.JPG)

- Le template "GRISpeaker Dome96" : 
Plusieurs lignes d'un seul côté du Dôme (en mode Cube toujours) 

![Screen Shot 2021-06-15 at 2 05 34 PM](https://user-images.githubusercontent.com/74631914/122102365-57d85e00-cde3-11eb-98f2-530bc5413c18.JPG)

Cependant, quand je passe en mode Dôme, les triangles se sont remis en place. Aussi, si je repasse en mode Cube, ils restent sur l'image et à l'identique alors que dans le menu l'option "Show Speakers Triplet" est grisée et donc inutilisable.

*** Je crois que je viens de comprendre quelque chose : Si "Show Speakers Triplet" est activé dans le menu et que je charge un speaker setup (un de ceux qui s'ouvrent en Cube), j'ai des images bizarres (mais ça se remet en place quand je clique sur Dome) ***

Quelques photos des belles figures créées : 

![Screen Shot 2021-06-15 at 2 17 13 PM](https://user-images.githubusercontent.com/74631914/122103588-c964dc00-cde4-11eb-823a-d0ff98b6cf13.JPG)

![Screen Shot 2021-06-15 at 2 17 59 PM](https://user-images.githubusercontent.com/74631914/122103606-cf5abd00-cde4-11eb-9d24-b0b45786b65f.JPG)

![Screen Shot 2021-06-15 at 2 18 21 PM](https://user-images.githubusercontent.com/74631914/122103628-d4b80780-cde4-11eb-9567-d20d96dead9e.JPG)

![Screen Shot 2021-06-15 at 2 18 43 PM](https://user-images.githubusercontent.com/74631914/122103668-df729c80-cde4-11eb-9ded-a50002f3428e.JPG)

![Screen Shot 2021-06-15 at 2 19 21 PM](https://user-images.githubusercontent.com/74631914/122103689-e5687d80-cde4-11eb-92fd-e033be41cc91.JPG)

**Comment by Normandeau** [comment]
Excellent! Garde-les, on va faire une expo! Ou encore on va faire croire aux clients qu'il s'agit de trajectoires complexes réalisées grâce à SpatGRIS!

**Comment by MelanieFrisoli** [comment]
V2.1.11

Quelques tests sur le chargement de différents speaker setups du dossier "Dome" téléchargé avec la version 2.1.11: 
Ceux qui s'ouvraient en mode "Cube" s'ouvre toujours en mode Cube.

**Comment by MelanieFrisoli** [comment]
V2.1.11

Le problème avec "Show Speaker Triplets" semble réglé.
Quand je passe en mode Cube, il n'y a plus aucune ligne blanche. 
Par contre, lorsque je repasse en mode Dome (et je n'ai pas déselectionné "Show Speaker Triplets" entre temps) il n'y a plus la triangulation, il faut que je retourne dans le menu cliquer.

**Comment by MelanieFrisoli** [comment]
V2.1.11

Le message d'erreur pour "GRISpeaker Dome128" a changé : 
Plus classe ;) 

![Screen Shot 2021-06-17 at 7 30 07 AM](https://user-images.githubusercontent.com/74631914/122389895-6a67aa00-cf3f-11eb-8493-644253a740b9.JPG)

**Comment by SamuelBeland** [comment]
v2.1.11

Le problème de triplets existe encore en mode VBAP + BINAURAL.

**Comment by MelanieFrisoli** [comment]
v2.1.11
Je viens de me rendre lors du chargement d'un speaker setup ("GRISpeaker Dome20Sub4 GRIS.xml") que "Show Speaker Triplets" était grisé quand je le chargeais et que j'étais en mode "Stereo" ou "Binaural", même quand je me remets sur "None" après. Ça n'a pas l'air de le faire sur tous les chargements de speaker setup cependant.

Alors que quand je le charge en étant en Stereo Reduction "None", Show Speaker Triplets apparaît bien dans le menu et je peux switcher en mode binaural et stéréo et les triplets restent apparentes.


*** À essayer de manière plus systématisée pour comprendre le phénomène qui se produit ici ***

![Screen Shot 2021-06-18 at 7 26 22 AM](https://user-images.githubusercontent.com/74631914/122554222-b6c9ed00-d006-11eb-8acc-7e9bf64c8a3c.JPG)

**Comment by Normandeau** [comment]
Question: est-ce pertinent de montrer les Triplets lorsqu'on est en Stereo ou en Binaural? Je pense qu'on pourrait tout simplement désactiver le graphisme dès qu'on passe dans un de ces deux modes.
Actuellement, leur présence dépend de l'ordre dans lequel on choisit de les afficher:
1. DOME
Show Triplets: OK
Passe en Stereo et/ou en Binaural: ça continue de s'afficher
2. DOME
Pas de Triplets
Passe en Stereo: Show Triplets est grisé, donc inactif: OK
Passe en Binaural: galerie de dessins bizarres comme l'a illustré Mélanie: bogue
Retour à None: les dessins restent affichés. Il faut désactiver et réactiver Show Triplets pour les avoir comme il faut. Trop de manipulation et source de confusion ici.
3. CUBE
Les triplets sont automatiquement désactivés.

Je vais changer le nom de l'issue.
En attendant:
«Par contre, lorsque je repasse en mode Dome (et je n'ai pas désélectionné "Show Speaker Triplets" entre temps) il n'y a plus la triangulation, il faut que je retourne dans le menu cliquer.»
Normal, parce que quand on passe en mode Cube, les triplets sont automatiquement désactivés.

**Comment by Normandeau** [comment]
V2112
Réglé.
