### ISSUE TITLE
Impossible d'ouvrir SpatGRIS

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#270]
V2110
Mélanie:
​Juste un petit mot pour vous dire que je rencontre des problèmes intéressants avec la nouvelle version de SpatGRIS.
​Hier j'ai eu des gros ralentissements sur mon ordinateur avec juste SpatGRIS et Live11 ouverts (iOS High Sierra).
​Ce matin, je rallume mon laptop et j'essaie d'ouvrir SpatGRIS en vain. J'ai constamment ce message d'erreur :
​
![Screen Shot 2021-06-09 at 9 13 52 AM](https://user-images.githubusercontent.com/8959779/121564908-edda4600-c9e9-11eb-8a98-70425f284c3f.JPG)

​J'ai aussi eu ce message d'erreur une fois (je crois à la 3ème tentative d'ouverture du logiciel) :

![Screen Shot 2021-06-09 at 9 13 41 AM](https://user-images.githubusercontent.com/8959779/121564958-fcc0f880-c9e9-11eb-80e1-eb0d44af2a02.JPG)

​

**Comment by Normandeau** [comment]
Même problème pour moi aujourd'hui sous Catalina (sauf le second message).
Dans 
~/Application Support/GRIS
Il y a deux documents:
- SpatGRIS2.xml
- SpatGRIS3.xml
J'avais pourtant vidé ce dossier avant d'installer la version 2.1.10. Je jette les deux documents. SpatGRIS s'ouvre à nouveau.
Ces documents correspondent en fait aux derniers réglages, si je comprends bien lisant le fichier .xml:
- LAST_SPEAKER_SETUP
- LAST_PROJECT
- LAST_RECORDING_DIRECTORY
Ainsi que:
- AUDIO_SETTINGS
Or quand on sauve ceux-ci, le document ne s'écrit pas tout de suite, mais seulement quand on quitte SpatGRIS. Normal?
La synthaxe des deux documents est différentes, alors il se peut qu'il y ait un conflit ici qui provoque le crash. Il faudrait aviser les usages de vider le dossier GRIS avant d'installer la nouvelle version.
Mais je reviens sur ce que dit Mélanie: hier j'ai également travaillé avec la nouvelle version sans problème!

**Comment by SamuelBeland** [comment]
J'avoue que le bouton "save" est un petit peu un mensonge en ce moment... Les paramètres d'application sont sauvegardés automatiquement à la fermeture (et uniquement à la fermeture) de SpatGRIS.

On pourrait soit : garder le modèle actuel et remplacer le mot "save" par "close". Ça rend implicite le fait que tout est sauvegardé automatiquement, OU BIEN faire en sorte que les paramètres affichés dans la fenêtre _settings_ soient uniquement enregistrés lorsque l'utilisateur appuie sur "save" et que tous les autres soient enregistrés à la fermeture.

Sinon, c'est vraiment étrange sinon cette histoire de crash à l'ouverture.

Par hasard, est-ce que @MelanieFrisoli ou @Normandeau auriez encore dans votre corbeille les fichiers qui étaient sous `~/Application Support/GRIS` ? J'aimerais y jeter un coup d'oeil.

**Comment by Normandeau** [comment]
En complément d'information, dans Application Support:
- SpatGRIS 216 génère SpatGRIS2
- SpatGRIS 218 génère SpatGRIS
- SpatGRIS 2110 génère SpatGRIS3
- J'ai mis les mêmes paramètres dans les trois versions.
Toutes les versions s'ouvrent en alternance sans problème.
- Puis j'ai mis des paramètres différents dans les trois versions.
Toutes les versions s'ouvrent en alternance sans problème.
;-(
PS Non, je n'ai pas gardé les documents jetés après le crash...

**Comment by MelanieFrisoli** [comment]
​Les voici :

[Report-SpatGRIS.pdf](https://github.com/GRIS-UdeM/ServerGRIS/files/6649042/Report-SpatGRIS.pdf)

**Comment by MelanieFrisoli** [comment]
V2.1.11.

Aucun problème à l'ouverture pour cette nouvelle version.
J'ai ouvert des versions antérieures, rouvert la V2.1.11 et aucun bug. 
Je n'ai pas eu à effacer des fichiers dans "Application Support" non plus.
