### ISSUE TITLE
Format des fichiers Speaker et Preset 2110 non compatibles avec les versions antérieures

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#272]
V2110
Les nouveaux formats de fichiers de Speaker Setup et de Preset ne sont pas  compatibles avec les anciennes versions de SpatGRIS. Testé avec v216 et v218.

Message d'erreur Speaker Setup:
![Capture d’écran, le 2021-06-15 à 14 57 39](https://user-images.githubusercontent.com/8959779/122108861-b81ece00-cdea-11eb-96cc-0af19fed779c.jpg)

Message d'erreur Preset:
![Capture d’écran, le 2021-06-15 à 14 59 11](https://user-images.githubusercontent.com/8959779/122108923-c79e1700-cdea-11eb-83f3-5cc3a770bc74.jpg)

Peut-être qu'un message plus précis serait approprié. Genre: Your file is outdated. Ou: Your file is not compatible with this version.
Parce que Corrupted n'est pas tout à fait exact et un peu paniquant, non?
À mettre dans le manuel assurément.

**Comment by SamuelBeland** [comment]
On ne peut malheureusement pas faire grand chose pour les versions antérieures de SpatGRIS.

Par contre, on peut s'arranger pour que ça n'arrive plus dans le futur.

Je vais attacher le numéro de version de SpatGRIS aux fichiers de speaker setup et de projets afin de pouvoir détecter ce type de problème et afficher un message plus approprié.

**Comment by SamuelBeland** [comment]
v2.1.11

Si je change le numéro de version dans mon speaker setup pour "2.1.12" et que j'efface un paramètre obligatoire :

<img width="310" alt="SpatGRIS_GS15R4WzbH" src="https://user-images.githubusercontent.com/39448259/122488069-b439aa00-cfaa-11eb-8582-0adbd0e50c8d.png">

**Comment by Normandeau** [comment]
Beaucoup mieux! Et plus standard. Je ne sais pas si c'est nécessaire, mais la plupart des logiciels audio qui génèrent des fichiers incompatibles avec les versions antérieures nous préviennent au moment de la sauvegarde. Genre: The document you are about to save  is not compatible with the previous version of SpatGRIS. Voici le message de DP en ce moment. On peut se passer de la partie Save as cependant:

![Capture d’écran, le 2021-06-21 à 10 04 22](https://user-images.githubusercontent.com/8959779/122775413-1a0e8600-d278-11eb-819f-2cc266b25b59.jpg)

**Comment by MelanieFrisoli** [comment]
Décidément, DP est un logiciel très classe. :) 
Sur Ableton, ça dépend des versions antérieures.
Par exemple, en essayant d'ouvrir un projet fait avec Live 11 : 
- Dans Live 10 : 

![Screen Shot 2021-06-27 at 10 29 03 AM](https://user-images.githubusercontent.com/74631914/123548426-c1853000-d732-11eb-8d19-e0d1659ceb2d.JPG)

- Dans Live 9 : 

![Screen Shot 2021-06-27 at 10 29 52 AM](https://user-images.githubusercontent.com/74631914/123548436-cb0e9800-d732-11eb-896d-00b4103d1a56.JPG)

et bien je trouve que le message de Live 9 est plus agréable à lire en tant qu'utilisatrice. (donc bien d'accord avec vous!)

**Comment by Normandeau** [comment]
V2113
Mis dans le manuel.
