### ISSUE TITLE
V2.1.11 Changement d'affichage du speaker setup en mode binaural et stéréo 

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#273]
Dans v.2.1.8, quand je passe en mode binaural et stéréo, l'affichage des haut-parleurs se modifie en fonction : 

![Screen Shot 2021-06-18 at 7 41 49 AM](https://user-images.githubusercontent.com/74631914/122555871-d7934200-d008-11eb-9f68-0b4f68011332.JPG)
![Screen Shot 2021-06-18 at 7 41 58 AM](https://user-images.githubusercontent.com/74631914/122555873-d7934200-d008-11eb-97df-19045a883ddd.JPG)

Nous avons alors un rappel visuel clair de ce qu'il se passe. 

v2.1.11
Quand je passe en mode binaural ou stéréo, l'affichage de mon speaker setup reste en place tel que je l'ai chargé. 
Je me demandais si c'était quelque chose de voulu.

![Screen Shot 2021-06-18 at 7 45 01 AM](https://user-images.githubusercontent.com/74631914/122556100-1b864700-d009-11eb-8111-ac3606c7644d.JPG)

**Comment by Normandeau** [comment]
Oui c'est voulu. Mais la prochaine étape est de nous laisser choisir sur quels haut-parleurs on veut mixer en Stereo ou en Binaural. Actuellement, si tu actives Show Speaker Level, tu verras que le mixage se fait sur 1-2 s'ils ont présents, ou sur les hp qui ont les plus petits numéros. Voir #267

**Comment by Normandeau** [comment]
V2112
Choix des haut-parleurs pour la réduction stéréo: c'est fait.
