### ISSUE TITLE
Coordonnées maximales en mode CUBE limitées au petit cube

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#274]
V2111
Les coordonnées maximales qu'on peut entrer en mode CUBE pour X, Y et Z sont maintenant de 1.00. Pour un angle de 45˚ (un coin), cela correspond à une distance maximale de 1.73. Comme cette distance est calculée à partir du centre au sol, cela signifie que la position la plus éloignée dans le CUBE est au coin supérieur, un peu plus loin que le cercle d'atténuation:

![Valeur maximale à 1 00](https://user-images.githubusercontent.com/8959779/122595163-0bd12780-d036-11eb-8886-82835b6243ba.jpg)

Il n'est donc plus possible de placer un hp aux extrémités du dispositif, ni même en dehors du petit carré au sol, même pour une sortie directe (ce qui pourra avoir une incidence lors du mixage à 2 canaux).
Pourtant si on ouvre un setup fabriqué avec une version antérieure, les hp sont bien positionnés loin du carré central. Notez bien les positions des deux sorties directes 6 et 14:

![Sorties directes lointains](https://user-images.githubusercontent.com/8959779/122595187-168bbc80-d036-11eb-8961-a6088eea4bb2.jpg)

Mais aussitôt qu'on veut ajuster ces valeurs lointaines, celles-ci sont automatiquement ramenées à 1.00 et on ne peut plus les modifier au-delà de cette valeur:

![Valeurs corrigées](https://user-images.githubusercontent.com/8959779/122595206-1c819d80-d036-11eb-9317-ab84b1d86394.jpg)

Actuellement les coordonnées limites sont celles du petit cube, celui est affiché avec Show Sphere/Cube

![Valeurs maximales limitées au petit cube](https://user-images.githubusercontent.com/8959779/122595392-62d6fc80-d036-11eb-8d58-cb1e5ed02441.jpg)

Ceci est un bogue majeur, car c'est exactement ce qu'on veut faire avec le mode CUBE: être capable de placer des hp n'importe dans l'espace délimité par le grand cube.

**Comment by NicolaGiannini** [comment]
Je confirme.

**Comment by NicolaGiannini** [comment]
V2112
On peut maintenant placer les HP aux coins du carré plus grand. La plus grande valeur que on peut insérer pour X et Y est 1.67.

**Comment by MelanieFrisoli** [comment]
V2112 - je confirme ce que Nicola dit pour les valeurs maximales de X et Y.

En mode Cube je remarque quelques mini trucs néanmoins : 
* Quand je règle un speaker à la souris, si je veux modifier légèrement cette valeur, dès que je clique pour glisser la souris, la valeur revient automatiquement sur une autre valeur, souvent aléatoire. C'est peut-être plus clair en vidéo (voir plus bas). 
* Si je règle un premier hp (les valeurs X, Y et Z) et que je clique sur "Add Speaker", il donne au nouveau speaker les mêmes valeurs que le précédent. Est-ce qu'il ne serait pas mieux qu'il crée toujours des nouveaux speakers avec des valeurs par défaut ? 
* Quand un nouveau speaker est créé, le numéro 2 apparaît avant le numéro 1. Est-ce que ce serait plus logique si il pouvait se mettre en dessous ? 
* Quand on supprime des speakers pour en remettre d'autres, les outputs continuent d'avancer. Mettons que j'ai 5 speakers : 1, 2, 3, 4, 5. Je supprime 1 et 3. Si je crée un nouveau speaker, il aura le numéro d'output 6. Est-ce que ça fait du sens ? 


https://user-images.githubusercontent.com/74631914/123177497-619d3980-d453-11eb-9246-5eba947265b8.mp4


Je copie/colle ces dernières remarques dans l'issue appropriée #233

**Comment by Normandeau** [comment]
Je seconde Mélanie pour son commentaire: «Quand je règle un speaker à la souris, si je veux modifier légèrement cette valeur, dès que je clique pour glisser la souris, la valeur revient automatiquement sur une autre valeur, souvent aléatoire.»
Et c'est particulièrement vrai en mode CUBE. Il faut se lever de bonne heure pour parvenir à entrer les valeurs qu'on veut!  Les text box de Juce... Mais ça finit par fonctionner. Je fais un vidéo demain, promis.

**Comment by NicolaGiannini** [comment]
J'ai répondu sur CUBE et DOME dans l'issue https://github.com/GRIS-UdeM/ServerGRIS/issues/233

**Comment by Normandeau** [comment]
Le problème décrit dans cette issue est réglé. Je réfère à #233 pour le reste.
