### ISSUE TITLE
Dans le cadre d’une session un peu chargée de Ableton Live 10, appuyer sur le bouton Save dans la fenêtre Unsaved project peut faire bloquer SpatGRIS

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#275]
V2111
J'ai une session un peu chargée de Ableton live 10: 85 pistes, 12 sends, 24 ControlGRIS.
Si je change quelque chose dans le projet de SpatGRIS et que je le ferme, le logiciel demande si je vais enregistrer les changements non enregistrés. Si j'appuie sur Save, SpatGRIS se bloque, et le curseur de la souris devient la roue qui tourne. Dans cette situation je dois terminer SpatGRIS avec cmd+opt+esc.
Cela se passe aussi pendant que Live n'est pas en lecture. 

Cpu usage dans SpatGRIS= 5%
Cpu monitor dans Live= 2%
SpatGRIS dans moniteur= 21%
Live dans moniteur= 28%
MenuMeters average of all cores= 12%

Cela se passe seulement avec cette session de live plus chargée. Avec d'autres sessions plus légères il n'y a pas de souci. 

Cela se passe aussi avec la version 2110
Cela ne se passe pas avec la version 219

**Comment by SamuelBeland** [comment]
Est-ce que le projet est sauvegardé après avoir _forced quit_?

> Cela se passe seulement avec cette session de live plus chargée. Avec d'autres sessions plus légères il n'y a pas de souci.

Est-ce que ça veut dire que le même speaker setup et projet ne vont pas planter si Live n'est pas ouvert?

**Comment by NicolaGiannini** [comment]
> Est-ce que le projet est sauvegardé après avoir forced quit?

Non, le projet n'est pas sauvegardé après avoir forced quit.

> Est-ce que ça veut dire que le même speaker setup et projet ne vont pas planter si Live n'est pas ouvert?

Exactement. Si Live n'est pas ouvert, ou aussi avec des sessions plus légères de Live, c'est tout correct.

**Comment by Normandeau** [comment]
V2112
Je ne suis pas certain de comprendre cette issue. Nicola: Est-ce que tu essaies de fermer SpatGRIS pendant que ta session Live est en train de jouer? Parce que tu dis: «Cela se passe aussi pendant que Live n'est pas en lecture.» Comme si le crashe se passait pendant que Live joue.
Sinon, je n'arrive pas à reproduire cela avec DP et une session de104 canaux. En fait cela ne m'est jamais arrivé, quelque soit la taille du projet DP.

**Comment by NicolaGiannini** [comment]
Robert,
Cela se produit lorsque Live n’est pas en lecture ou lorsque Live est en lecture. Je joins ici une vidéo où le projet de Live est simplement ouvert. Je modifie un paramètre dans le projet de SpatGRIS, j'essaie de fermer le logiciel, il me demande de sauvegarder, je clique sur Save, et là le programme se bloque. Ce n'est pas exactement un Crash, le curseur devient la roue colorée qui tourne. 
Petite note, dans la capture vidéo la roue qui tourne n'est pas affichée, mais je vous assure qu'à 00,10 le curseur devient une roue. 

https://user-images.githubusercontent.com/35705913/123445187-a5a05380-d5a5-11eb-9de0-c53b58ead878.mov

Je l'ai essayé avec une session chargée de Logic et je n'ai eu aucun problème. Il se pourrait que ce soit vraiment lié à ma session particulière de Live.

**Comment by Normandeau** [comment]
Ce que je ne comprend pas c'est pourquoi tu essaies de fermer le logiciel alors que la session Live est encore ouverte? As-tu essayé juste de sauver le projet de SpatGRIS avec la commande Save Project ou Save Project as? As-tu la même réaction?

**Comment by NicolaGiannini** [comment]
> Ce que je ne comprend pas c'est pourquoi tu essaies de fermer le logiciel alors que la session Live est encore ouverte?

Bonne question !
Je faisais probablement des tests comparatifs entre différentes versions de SpatGRIS2. Ce cas ne représente probablement pas un cas d'utilisation réel.

> As-tu essayé juste de sauver le projet de SpatGRIS avec la commande Save Project ou Save Project as? As-tu la même réaction?

Avec Save Project ou Save Project as je n'ai pas ce problème.

Par contre j'ai exactement le même problème si je fais des modifications au Speaker Setup et j’essaye d'en ouvrir un autre. Quand SpatGRIS2 me demande si je veux enregistrer les modifications, si j'appuie sur Save, SpatGRIS2 se bloque, et le curseur de la souris devient la roue qui tourne.

**Comment by MelanieFrisoli** [comment]
V2112
Je viens de faire quatre fois l'essai. Deux fois en mode Dome, ajoutant 2 speakers à un setup, puis en ajoutant un ring, puis deux fois en mode "Cube" avec le même principe. 
Je clique sur "Compute" et sors de la fenêtre Speaker Setup Edition. Je charge un autre speaker setup, je clique sur Save et aucun problème chez moi, c'est sauvegardé et le nouveau setup est chargé.

**Comment by NicolaGiannini** [comment]
Je signale dans cet issue un autre comportement qui peut provoquer le blocage de SpatGRIS. Si on essaye de changer de Speaker Setup sans arrêter la session DAW, dans le cas d'une session très lourde, SpatGRIS peut se bloquer. Je suppose que c'est normal, je ne sais même pas si cela doit être mentionné dans le manuel.

**Comment by Normandeau** [comment]
V2113
De mon côté, je travaille avec des sessions vraiment lourdes depuis pas mal de temps, et je n'ai jamais eu aucun blocage. Mais:
- Je n'essaie pas de changer le Speaker setup quand je travaille sur un projet!
- Je n'essaie pas de fermer SpatGRIS pendant que la session joue!

Question 1: quand tu dis: «Si je change quelque chose dans le projet de SpatGRIS et que je le ferme», qu'est-ce que tu changes exactement?
Question 2: pourquoi fermer SpatGRIS à ce moment-là?
Ce que cette issue illustre en fait, c'est du moins mon avis, c'est qu'on peut faire planter à peu près n'importe quel logiciel en effectuant des tâches «absurdes». C'est bien de tester les limites, mais après un certain temps, on peut se demander si cela se reproduit dans la réalité. Sinon, on peut passer à autre chose. Comme personne n'est arrivé à reproduire cela, je dois supposer que c'est une fatalité de ton projet!

**Comment by NicolaGiannini** [comment]
Robert,

> Question 1: quand tu dis: «Si je change quelque chose dans le projet de SpatGRIS et que je le ferme», qu'est-ce que tu changes exactement?

je change notamment le gain ou l’interpolation, simplement pour que le projet soit modifié.
J’avais 

> Question 2: pourquoi fermer SpatGRIS à ce moment-là?


Je changeais de version de SpatGRIS pour faire des tests, mais je suis d’accord avec toi qu’il ne s'agit pas d'un cas d'utilisation réelle.
De plus, il se peut que ce soit lié à cette session spécifique de Live 10. C'est le seul projet avec lequel cela m'arrive.
