### ISSUE TITLE
Problème majeur de niveau en mode CUBE

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#276]
V2111
Dispositif: 1 seule source de bruit rose mono à -6dB située au centre d'un CUBE de 8 hp: 4 hp en bas, 4 hp en haut.
Attenuation: 0dB; Filtre: 16kHz; Gain Smoothing: 0

Lorsque le signal est au plancher, on a -6dB sur les 4 hp du bas:
![4 hp du bas](https://user-images.githubusercontent.com/8959779/122830523-71cbe200-d2b6-11eb-8e2a-09c00b1aa751.jpg)

Lorsqu'on monte le signal en haut du CUBE, on obtient -18dB, donc 12 dB d'atténutation:

![4 hp du haut](https://user-images.githubusercontent.com/8959779/122830688-b2c3f680-d2b6-11eb-8a46-77e3b3fe07df.jpg)

C'est déjà un bogue majeur.

Mais il y en a un autre, il n'y a plus d'interpolation entre les niveaux. Il suffit de placer Z à 0.03 dans ControlGRIS pour que tout le son passe en haut, pratiquement sans transition:

![Z à 0 03](https://user-images.githubusercontent.com/8959779/122830928-151cf700-d2b7-11eb-8e1d-cfaba37c2439.jpg)

Autrement dit, le fondu enchaîné entre le bas et le haut se fait sur 3 centièmes de position Z!!! Gain smoothing à 1.00 ne change rien.
Ça veut dire qu'on pourrait pas jouer _Octophony_ de Stockhausen, dont c'est précisément le dispositif.

**Comment by Normandeau** [comment]
Comparaison avec la version 216.
L'équilibre entre les hp du bas et ceux du haut est obtenu à Z=0.50 comme on s'y attend:

![V216 Z à 0 50](https://user-images.githubusercontent.com/8959779/122832525-76de6080-d2b9-11eb-9897-e039fac15e79.jpg)

**Comment by Normandeau** [comment]
Vérification faite avec un autre CUBE, de 24 hp celui-là, 12 hp en bas, 12 hp en haut. Les 12hp du bas ont exactement les mêmes coordonnées que ceux du bas, sauf le Z évidemment qui est à 1.00 partout en haut.

Niveaux obtenu à Z=0.00 (bas): déséquilibre entre les hp:

![CUBE 24 HP du bas](https://user-images.githubusercontent.com/8959779/122832684-b7d67500-d2b9-11eb-9bda-52034449e3e6.jpg)

Niveaux obtenu à Z=1.00 (haut): seulement 4 hp sur 12 fonctionnent:

![CUBE 24 HP du haut](https://user-images.githubusercontent.com/8959779/122832762-d5a3da00-d2b9-11eb-880c-2234049b41ba.jpg)

Ce problème n'existe pas non plus dans la version 216, où tous les hp fonctionnent et où les niveaux sont égaux.

**Comment by Normandeau** [comment]
Autre setup: un cylindre de 32 hp à 4 niveaux: 12, 8, 8, 2

Z= 0.00:

![Cylindre 32 HP du bas](https://user-images.githubusercontent.com/8959779/122834256-43510580-d2bc-11eb-9ec8-1152ad5d4592.jpg)

Z= 0.01: il n'y a aucune transition, on passe des 12hp du bas aux 2 du haut en un centième de position. Tous les hp des niveaux 2 et 3 sont ignorés:

![Cylindre 32 HP du haut](https://user-images.githubusercontent.com/8959779/122834356-6ed3f000-d2bc-11eb-861d-46cbbc7b479d.jpg)

Vérification faite cette fois-ci avec 218. Aucun problème.

**Comment by NicolaGiannini** [comment]
Je confirme. J’ai fait des tests avec la version 2.111 2.19 et 2.18.
Dans mon cas apparemment le problème apparaît depuis la version 2.19.

**Comment by Normandeau** [comment]
Source mono seulement ou toutes les sources au centre.
Apparemment, le problème ne se pose que lorsqu'on utilise une source mono. 
En stéréo ou en octo, le comportement est normal mais seulement **si les sources ne sont pas superposées au centre**.
Si on prend les sources 1 et 2 et qu'on les superpose au centre, a le même comportement qu'avec une source mono. Même chose avec un fichier octo.
À valider.

**Comment by NicolaGiannini** [comment]
V2112
Dans mon cas ça semble réglé.

**Comment by Normandeau** [comment]
Confirmé. Bravo Samuel, temps de résolution record pour un bogue majeur!!!
