### ISSUE TITLE
HP ajoutés en counterclockwise

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#279]
V2112
Les numéros des hp qu'on créés avec Add Ring sont counterclockwise: pourquoi pas clockwise? Je ne dis pas que c'est fondamental, mais s'il s'agit d'être cohérent...
Puisque: «The offset angle is now clockwise instead of counterclockwise»:

![HP counterclockwise](https://user-images.githubusercontent.com/8959779/123166673-acaf5080-d443-11eb-93ce-4bcf0dce8262.jpg)

**Comment by MelanieFrisoli** [comment]
Oui, c'est sûr ce serait plus cohérent. Je seconde.

**Comment by NicolaGiannini** [comment]
V2113
Les numéros des hp qu'on ajoute avec Add Ring sont clockwise maintenant.
