### ISSUE TITLE
Erreur de compilation sous Linux

### ISSUE THREAD

**Issue by ghost** [GRIS-UdeM/SpatGRIS#281]
(je pourrais chercher, mais peut-être que le problème est trivial à résoudre pour les développeurs principaux);
sur la branche dev:

ServerGRIS/Builds/LinuxMakefile$ make CONFIG=Release CXX=clang++-10

../../Source/jackClientGRIS.cpp:634:22: error: no viable conversion from 'std::unique_ptr<FileInputStream>' to 'juce::FileInputStream *'
    FileInputStream *stream = file.createInputStream();

**Comment by SamuelBeland** [comment]
Cette erreur arrive lorsque la branche `main` est compilée avec JUCE 6. Assurez-vous de bien être sur la branche `dev` et qu'elle soit à jour (je viens tout juste d'y régler d'autres problèmes de compilation avec [`ef0903`](https://github.com/GRIS-UdeM/ServerGRIS/commit/ef0903e2bbec6291cc1dcba802ad6ebe4d49bd2c)).

Vous pouvez aussi utiliser [JUCE 5.4.7](https://github.com/juce-framework/JUCE/releases/tag/5.4.7) pour compiler la branche `main`.

**Comment by ghost** [comment]
En effet, j'étais sur la branche main (alors que je croyais être sur la branche dev). J'utilise bien JUCE version 6, spécifiquement 6.0.5 GPL. Il y a un nouveau problème:

../../Source/StaticVector.hpp:22:10: fatal error: narrow.hpp: Aucun fichier ou dossier de ce type
   22 | #include "narrow.hpp"

**Comment by SamuelBeland** [comment]
Vous n'avez probablement pas réexécuté `git pull` depuis que le commit a été poussé il y a tout juste 1 heure.

Vous devrez probablement aussi regénérer le makefile produit par le _Projucer_ avant de pouvoir compiler.

**Comment by ghost** [comment]
Encore une fois c'était mon erreur, et j'ai maintenant SpatGRIS qui roule sous Linux. Mais il n'y a qu'une interface ALSA qui est disponible. Comme il semble que JUCE puisse supporter Jack, est-ce que le choix de ALSA seulement est intentionnel?

**Comment by SamuelBeland** [comment]
Jack était bel et bien désactivé dans la configuration!

Après avoir activé Jack, SpatGRIS plantait systématiquement puisque Jack bloquait l'interface par défaut (ALSA) et SpatGRIS ne savait plus quoi faire. 

SpatGRIS devrait maintenant tenir le coup, même si aucune interface audio n'est disponible. Réglé sur la branche `dev` ([1fcd30](https://github.com/GRIS-UdeM/ServerGRIS/commit/1fcd305b57ec973d9af633f4b28e7a3464332255)).

Merci pour l'_issue_ @marclava. Dis-moi si ça fini par fonctionner!

J'ai aussi remarqué que le serveur Jack devait absolument avoir déjà été lancé avant l'ouverture de SpatGRIS. Ça devrait surement être mentionné dans le manuel @Normandeau.

**Comment by ghost** [comment]
En fait j'allais proposer un patch qui fait la même chose. Ça fonctionne maintenant avec ALSA ou Jack, et dans ce cas il faut avoir démarré Jack avant toute chose, comme avec tous les logiciels qui utilisent Jack. Avoir le support ALSA et Jack dans SpatGRIS devrait pouvoir couvrir les cas d'usage habituels sous Linux; certains n'aiment pas utiliser Jack, personnellement je l'utilise à temps plein avec un pont PulseAudio. Je suppose qu'en ayant ainsi activé Jack dans les paramètres audio du projet JUCE ça devrait aussi rajouter Jack comme option de config audio sous OSX (et peut-être même sous Windows).

**Comment by ghost** [comment]
J'ai aussi pu compilé ControlGRIS sous Linux, et je me demandais si le support Jack devrait y être rajouté, mais probablement pas parce c'est un plugin VST...

**Comment by SamuelBeland** [comment]
Ce n'est pas nécessaire : les plugins n'ont généralement pas directement accès aux interfaces audio (sauf en standalone). De plus, ControlGRIS n'interragit pas avec l'audio pour l'instant.
