### ISSUE TITLE
Lorsqu'un Speaker Setup est sauvegardé, le nom du fichier n'est pas mis à jour dans la fenêtre 3D

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#282]
V2112
Si je modifie un Speaker Setup et que je l'enregistre avec un nouveau nom, ce nouveau nom n'est pas affiché dans la fenêtre 3D en haut à gauche. 
Il reste toujours affiché le nom du Speaker Setup qu'on vient de modifier.

**Comment by Normandeau** [comment]
Excellente remarque. Le nouveau speaker setup pourtant existe bel et bien, il a bien été sauvegardé (Save As), c'est pourtant lui qu'on voie dans la fenêtre 3D, mais sans son nom. On peut s'en rendre compte en l'ouvrant: le speaker setup est le même que celui qu'on vient de remplacer mais avec le bon nom.
Alors que pour le projet, la commande Save As remplace le nom du setup qui vient d'être modifié.

**Comment by Normandeau** [comment]
Trouvé tout à fait par hasard: lorsqu'on clique sur un des haut-parleurs du setup modifié qui n'affiche pas le bon nom, le bon nom s'affiche correctement!
Donc c'est juste un problème de rafraichissement d'écran apparemment.

**Comment by NicolaGiannini** [comment]
Je confirme!

**Comment by MelanieFrisoli** [comment]
Je confirme aussi !

**Comment by MelanieFrisoli** [comment]
V2114 
Ça fonctionne très bien chez moi maintenant. Le nouveau nom apparaît instantanément.

**Comment by Normandeau** [comment]
Réglé
