### ISSUE TITLE
Message d'erreur "Disabled Spatialization" en assignant des speakers en sortie directe

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#283]
V2112
Avec un speaker setup octophonique très simple agrémenté de deux subs, j'ai coché la case "Sortie Directe" pour les speakers 1, 2, 3 et 4. J'ai alors eu ce message d'erreur qui peut faire du sens car effectivement il y a des speakers qui ont un écart de plus de 170° entre eux. En tout cas, j'ai cliqué sur "Ok" et tout a fonctionné comme si de rien n'était (le mode Dome est restée sélectionné). 
Simple question :)

![Disabled Spatialization](https://user-images.githubusercontent.com/74631914/123562346-43e61200-d77c-11eb-9697-bdec78506ae4.JPG)

**Comment by SamuelBeland** [comment]
Le message d'erreur averti que la spatialisation est désactivée. Il est encore possible d'utiliser SpatGRIS et de modifier le setup, mais il n'y a plus d'audio.

Le comportement me semble sensé. Est-ce qu'il y aurait une meilleure approche?

**Comment by MelanieFrisoli** [comment]
Je ne sais pas pour une meilleure approche mais  je sais que j'ai toujours de l'audio et que la spatialisation a l'air de fonctionner (mais en "sautant" des speakers j'ai l'impression).

Ici, les sorties 1, 2, 3 et 4 sont directes. ControlGRIS envoie de l'OSC - normal - et en binaural j'entends les sources spatialisées tourner mais plus trop vers l'avant, comme si c'était devenu un demi-cercle vers l'arrière (ce qui est assez cool en fait! Tu peux faire des setups super particuliers. Là je joue des drones sur 1/2 et 3/4 ça me donne une belle stéréo et j'ai des sources qui bougent vers l'arrière. C'est pas mal!)

![SortiesDirectes](https://user-images.githubusercontent.com/74631914/123626195-8e987600-d7de-11eb-9d10-4a26c37bdf59.JPG)

Enfin voilà c'était pas pour relancer un débat mais juste pour te prévenir que l'audio passe et que les mouvements continuent de fonctionner sur les hp qui ne sont pas en sortie directe.

**Comment by SamuelBeland** [comment]
Je comprend mieux maintenant!

STEREO et BINAURAL ne seront jamais désactivées. BINAURAL utilise un speaker setup spécial en cachette et STEREO n'en utilise même pas! La seule chose dans le speaker setup utilisateur qui affecte les réductions stéréos, c'est la position des speakers où sont envoyées des sources en sorties directes.

Tu as probablement eu le message d'erreur en mode DOME (sans réduction stéréo), où l'audio avait été désactivée.

**Comment by MelanieFrisoli** [comment]
D'accord, je comprends mieux aussi!
Je viens de refaire un test et oui, je n'ai pas le message d'erreur quand je suis en binaural ou en stéréo.
Si j'ai fait ces manipulations en mode Dome ou Cube, j'ai le message et également si après les manipulations faites en mode binaural ou stéréo, je repasse en dome ou en cube.
Merci pour les précisions!

**Comment by NicolaGiannini** [comment]
J'ai essayé de recréer la situation décrite par Mélanie. Et je confirme que si la fenêtre d'erreur s'affiche en mode DOME, une fois les 4 sorties directes activées, l'audio ne fonctionne pas. En revanche, l'audio fonctionne si on active la réduction BINAURAL ou STEREO.

**Comment by Normandeau** [comment]
Je confirme aussi. 
Précisions dans les termes: comme l'as suggéré Nicola, nous avons deux nouveaux termes pour les sorties directes:
- sorties directes indépendantes: ce sont celles qui sont prévues par le Speaker Setup et qui ont été utilisées ici;
- sorties directes spatialisées: ce sont celles qui sont déterminées par l'assignation d'une sortie directe via les Inputs.

Donc tout est conforme ici au fonctionnement normal de SpatGRIS. Le chapitre sur les sorties directes va être fantastique à écrire sur le plan de la clarté...

**Comment by Normandeau** [comment]
V2113
Mis dans le manuel
