### ISSUE TITLE
Bruit sur les changements effectués dans SpatGRIS (mode binaural et stéréo)

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#284]
V2112
Quand je suis en mode binaural et que je change des paramètres dans SpatGRIS j'ai un buzz assez fort mais relativement court qui apparaît.
Quand je suis en mode stéréo ce sont juste des petits clics. 
Est-ce que c'est juste chez moi ? Ou ça vous arrive aussi ? 
Je suis sur un système stéréo chez moi mais je n'ai pas l'impression que ça arrive sur un système dome ou cube dans réduction stéréo ou binaurale.

Petit exemple en vidéo : 

https://user-images.githubusercontent.com/74631914/123562664-1601cd00-d77e-11eb-87d4-e36a195887a7.mp4

**Comment by Normandeau** [comment]
Je confirme ce que dit Mélanie. Dans mon cas, c'est vraiment en Binaural que ça buzze. En Stereo, chez moi, ce sont plutôt des coupures brèves de l'audio. Disons que je ne trouve pas cela surprenant, ni un ni l'autre en fait. Le fait d'introduire des changements dans une chaîne audio et que ça génère des bruits n'est pas vraiment surprenant, sauf peut-être pour les utilisateurs de Live! En principe, on n'opère pas ces changements pendant qu'on travaille.

**Comment by NicolaGiannini** [comment]
Je confirme moi aussi le buzz dans le cas de la réduction binaurale et la coupure audio dans le cas de la réduction stéréo.

**Comment by NicolaGiannini** [comment]
V2113
Maintenant dans mon cas, je note une brève coupure audio dans le cas de la réduction binaurale et stéréo, mais pas de buzz.

**Comment by Normandeau** [comment]
V2113
Bruit de transition encore présent, mais moindre. À confirmer.

**Comment by MelanieFrisoli** [comment]
V2113
En effet, c'est moindre maintenant. Soit un silence soit une sorte de clic audio. Ce qui paraît plus normal.
Vraiment mieux que d'avoir un buzz.

**Comment by Normandeau** [comment]
Donc tout le monde est content! Youpie, une  issue de plus en moins.
