### ISSUE TITLE
Menu About SpatGRIS, sans image

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#285]
V2113
«Fixed missing splash screen and about window icon on Windows.»
Si on le remet à l'un, doit-on l'enlever à l'autre?

![About](https://user-images.githubusercontent.com/8959779/124332082-9e0d1b80-db5e-11eb-816d-a013d692fbf4.jpg)

**Comment by MelanieFrisoli** [comment]
V2114
L'image est là ! 
![Screen Shot 2021-07-15 at 4 59 24 PM](https://user-images.githubusercontent.com/74631914/125856857-89ded5b6-c76d-442e-8245-92555f77f826.JPG)

**Comment by Normandeau** [comment]
Trèze joli!
