### ISSUE TITLE
Disable spatialization

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#286]
V2113
Nouveau message, qui apparaît lorsqu'on enlève un hp qui était assigné à une sortie stéréo:

![Disable spatialization](https://user-images.githubusercontent.com/8959779/124335200-900fc880-db67-11eb-995a-772f1d95efb4.jpg)

1) Je ne suis pas certain que libellé du message est correct: en effet cela concerne la réduction stéréo, pas la spatialisation!
2) En fait, j'ai reçu ce message dans Speaker Setup Edition alors que j'enlevais des hp. Mon setup de base avait 12 hp de 1 à 12 et mes sorties stéréo était assignées à 1-9 et Stereo était activé. Lorsque j'ai enlevé le 9, j'ai reçu ce message alors que j'avais toujours 8 hp dans le setup! C'est troublant, car c'est inexact.

Disable channel peut-être?

**Comment by NicolaGiannini** [comment]
Je suis d’accord.
Dans le cas décrit par Robert, le message pourrait être aussi :

“Stereo Channel Disabled. Please select valid stereo channels.”

Si on passe d’un dispositif où les sorties de la réduction sont présentes à un dispositif où elles ne le sont pas, par exemple de Hexa à B187, en considérant comme sorties stéréo par exemple 1 et 2, le message pourrait être : “Please select valid stereo channels.”

**Comment by MelanieFrisoli** [comment]
Tout à fait d'accord 👍🏼

**Comment by Normandeau** [comment]
V2.1.14
Nouveau message, plus approprié:

![Capture d’écran, le 2021-07-15 à 18 49 54](https://user-images.githubusercontent.com/8959779/125867572-2eeaa99c-b9bb-4d1d-9b0f-ffacea67e21c.jpg)
