### ISSUE TITLE
Longer load times. Vraiment?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#287]
V2113
Samuel écrit: «Spatialization algorithms are initialized more often than they should be, leading to artificially longer load times for large DOME setups.»
Je ne vois vraiment pas de quoi tu parles. Je viens de passer en revue tous les plus gros speaker setups que j'ai, dont certains prenaient jusqu'à 3-4 minutes pour ouvrir avec la version officielle, et aujourd'hui c'est littéralement instantané. Est-ce que quelqu'un d'autre a déjà expérimenté cela récemment?

**Comment by NicolaGiannini** [comment]
Dans mon cas également, toutes les configurations s'ouvrent à peu près instantanément.

**Comment by MelanieFrisoli** [comment]
Je confirme, même les plus grosses configurations s'ouvrent instantanément.

**Comment by Normandeau** [comment]
Donc pas vraiment de problème ici.
