### ISSUE TITLE
Résolution du Zoom Out maximum?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#288]
V2113
La résolution maximum du Zoom Out de la fenêtre 3D correspond au grand cube. Cela peut poser problème sur des écrans de dimensions normales, car en ouvrant des grands cubes, selon les dimensions normales de SpatGRIS, on ne voit pas les hp les plus proches de nous:

![Zoom out maximum](https://user-images.githubusercontent.com/8959779/124363674-af136680-dc0a-11eb-9e18-ced16a2f9da2.jpg)

Il faut agrandir la fenêtre 3D au max pour tout voir. Cela se fait au détriment de la sections Sources-Speakers:

![Zoom out maximum](https://user-images.githubusercontent.com/8959779/124363735-fef22d80-dc0a-11eb-9ea9-b73b1c81ae10.jpg)

Est-ce possible d'améliorer cela?

**Comment by MelanieFrisoli** [comment]
Je confirme, ce serait vraiment pratique de pouvoir dézoomer encore un peu plus.

**Comment by MelanieFrisoli** [comment]
V2114
On peut maintenant "zoom-out" très loin en mode Cube : 

![Screen Shot 2021-07-15 at 4 58 34 PM](https://user-images.githubusercontent.com/74631914/125856730-84a2e52e-82ef-45e5-a75d-7678c5725599.JPG)

Ce qui permet d'avoir une belle vue d'ensemble.

**Comment by Normandeau** [comment]
Excellent.
