### ISSUE TITLE
Menu Settings disparaît à l'arrière plan

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#289]
V2113
J'ouvre la fenêtre Settings avec "Cmd + ," et si je clique ailleurs, la fenêtre vient se placer en arrière-plan. 
Je n'avais pas vu que j'avais fait ça et j'ai fait, en vain, plusieurs fois le raccourci pour l'ouvrir et j'ai mis un moment avant de me rendre compte qu'elle était passée derrière.
Pourrait-il y avoir un moyen qu'elle repasse au premier plan quand on clique sur "Settings" ou quand on fait le raccourci ? 
Autre option, qu'elle ne passe jamais en arrière-plan tant qu'on n'a pas cliqué sur "Close" ?

**Comment by Normandeau** [comment]
Oui, compte tenu du fait que c'est une fenêtre qu'on n'ouvre que de temps en temps pour faire des réglages et qu'on passe ensuite à autre chose, il n'y aucune raison qu'elle ne reste pas au premier-plan dès qu'elle est ouverte.

**Comment by MelanieFrisoli** [comment]
Sur plusieurs logiciels (par exemple Pro Tools), il est même impossible de toucher à d'autres fonctions quand cette fenêtre est ouverte. Il attend alors qu'on clique sur "Apply" ou "Ok" pour donner accès au logiciel.
Dans Live par contre, la fenêtre des préférences peut être relégué à l'arrière-plan mais est rappelée dès qu'on clique sur "Préférences" ou qu'on fait le raccourci. 
Plusieurs options sont donc possibles :)

**Comment by NicolaGiannini** [comment]
Je suis d’accord ! il serait plus pratique d’avoir cette fenêtre toujours au premier plan.

**Comment by MelanieFrisoli** [comment]
V2114
La fenêtre "Settings" reste bien au premier plan et on ne peut pas atteindre le logiciel tant que nous n'avons pas cliqué sur "Close". Super !

**Comment by Normandeau** [comment]
Yeah!
