### ISSUE TITLE
Le clic droit sur la couleur d'une source ne fonctionne plus

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#290]
V2113
Le clic droit, qui nous permettait de mettre les deux canaux d'un fichier stéréo de la même couleur, ne fonctionne plus. Déjà qu'on n'est pas gâté avec ce genre de fonctions pour le moment, faut pas nous enlever celles qui fonctionnent!

**Comment by MelanieFrisoli** [comment]
Tout à fait d'accord. Je confirme.
J'ajoute une question : Lorsque les couleurs choisis sont trop claires on ne voit plus le numéro de la source. Existerait-il un moyen pour soit choisir la couleur de l'écriture, soit automatiquement la mettre noir pour des couleurs claires ?

**Comment by MelanieFrisoli** [comment]
V2114
Cela fonctionne chez moi sur cette nouvelle version.

**Comment by Normandeau** [comment]
Chez moi, avec une souris Logitech (MX Master 3), ça ne fonctionne plus du tout. Je ne suis même plus capable d'ouvrir le panneau de couleurs avec le clic droit. Je viens de tester avec 2.1.6, et ça fonctionne.

**Comment by MelanieFrisoli** [comment]
V2114
En effet, chez moi ça n'ouvre pas le panneau de couleur avec un clic droit.
Par contre ça donne la même couleur que celui sur lequel je clique droit à celui à sa gauche (ce qui est une forme de "Duplicate" et qui peut être pratique)

Testé également avec 2.1.8 et ça fonctionnait (clic droit qui ouvre le panneau de couleurs et colorent les deux sources successives)

**Comment by Normandeau** [comment]
Ah je vois. Donc clic sur un hp, choix de couleurs, fermeture du panneau de couleur, et clic droit sur celui qu'on vient de changer ce qui modifie celui qui est immédiatement à sa droite. Est-ce mieux? Une question d'habitude? Vous me dites.

**Comment by MelanieFrisoli** [comment]
En effet, je trouve ça assez rapide et pratique comme ça.
Et ça permet de pouvoir en faire 4 ou 6 de suite si on le souhaite.

**Comment by Normandeau** [comment]
Oh, en effet, Vendu!!!

**Comment by NicolaGiannini** [comment]
C'est pratique !

**Comment by SamuelBeland** [comment]
Oups! J'avais mal compris le comportement désiré... mais tant mieux si ça fait l'affaire!

**Comment by Normandeau** [comment]
Bravo. À mettre dans le manuel.

**Comment by Normandeau** [comment]
Mis dans le manuel
