### ISSUE TITLE
MacOS 10.12 à 11.4

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#292]
V2113
• MacOS from 10.12 Sierra™ to 11.4 Big Sur™
Déjà mis dans le manuel.

Il faudra modifier l'information dans l'installeur.
Actuellement elle se lit comme suit:
System requirements: macOS 10.11 to 10.15.7

Bonne nouvelle!

**Comment by MelanieFrisoli** [comment]
Excellente nouvelle, bravo !
  
​
  
​Mélanie

**Comment by Normandeau** [comment]
V2115
Pas encore modifié dans l'installer: System requirements: macOS 10.11 to 10.15.7

**Comment by Normandeau** [comment]
V2116
Correctement annoncé!
