### ISSUE TITLE
Show Numbers & Show Speakers

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#293]
V2113
Si "Show Speakers" n'est pas coché, on ne peut pas faire apparaître les numéros des speakers. C'est tout à fait logique. Cependant, il serait peut-être préférable que "Show Numbers" apparaissent grisé dans le menu quand "Show Speakers" n'est pas coché pour éviter les confusions. Certains utilisateurs pourraient penser que cela ne fonctionne pas.

**Comment by Normandeau** [comment]
En fait, tu touches un point que je n'avais pas encore osé soulevé... Selon moi, le Show Numbers devrait être distinct pour les Speakers et pour les Sources. Quand on travaille régulièrement avec un dispositif, on n'a plus besoin des numéros des hp. Mais les numéros des sources sont toujours utiles. Comme les deux apparaissent ensemble, sur de gros projets, ça devient inutilisable parce qu'illisible:

![Capture d’écran, le 2021-07-09 à 16 55 16](https://user-images.githubusercontent.com/8959779/125135134-82fa5880-e0d6-11eb-8b00-e50a5801e3e2.jpg)

Dans la fenêtre 2D, comme on n'a que les sources et que les numéros sont placés au centre des boules de couleurs, c'est beaucoup plus pratique et informatif:

![Capture d’écran, le 2021-07-09 à 16 56 44](https://user-images.githubusercontent.com/8959779/125135236-a8876200-e0d6-11eb-88f6-4bf0ad5d8326.jpg)

Donc oui, amélioration éventuelle...

**Comment by MelanieFrisoli** [comment]
Oui ça pourrait être intéressant d'avoir deux choix dans le menu pour séparer les choses. Un "Show Hp Numbers" et un "Show Sources Numbers". 
(Et qu'on ne puisse pas cliquer sur "Show Hp Numbers" quand les hp ne sont pas apparents).

Sur ta première image, c'est vrai qu'on ne voit plus grand chose mais, si tu enlèves "Show Speakers", ce qui est chouette c'est que les numéros des sources restent en place. Ça peut être une solution pour des projets chargés. Surtout quand on connaît bien notre speaker setup, on n'a pas forcément besoin de voir les hp. Pour ma part, je n'affiche quasiment jamais les speakers :) (mais je travaille juste sur les deux dômes de la faculté).

**Comment by NicolaGiannini** [comment]
Je trouve également qu'il peut être pratique d'avoir la possibilité de voir les numéros des HP et des sources séparément.

**Comment by Normandeau** [comment]
311
Réglé
