### ISSUE TITLE
Des templates "Dôme" s'ouvrent en mode Cube

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#294]
V2113
J'ai toujours ce problème (je ne trouve plus l'issue correspondante).
Plusieurs speakers setup du dossier "Dome" dans "Templates" s'ouvrent en mode Cube.
C'est le cas de : 
- GRISpeaker Dome128
- GRISpeaker Dome31Subs1 Satosphere
- GRISpeaker Dome96
- GRISpeaker Dome80
- GRISpeaker Dome64
- GRISpeaker Dome32Subs2 UdeMUFX+
- GRISpeaker Dome10Subs2

ce n'est qu'une manipulation supplémentaire (Cliquer sur Dôme quand on se rend compte que Cube a été choisi) mais je pense que ça éviterait de la confusion chez l'utilisateur.

**Comment by Normandeau** [comment]
J'ai refait tout le dossier des Templates. 
D'une part, si les DOMES s'ouvrent en CUBES, c'est parce qu'ils ne sont pas des dômes! Stricto sensu, la distance doit être égale à 1.00 partout avec 2.1.13. Vérification faite avec quelques-uns mentionnés ici, c'est bien le cas. Il faut alors les ouvrir en CUBE et les convertir ensuite en DOME. C'est ce que j'ai fait.
Ensuite, le format xml des speaker setup ayant été modifié, il fallait tout convertir afin de s'assurer que ça ouvre bien dans le bon le format.
Même chose pour les Projects.
Sinon, la doc a été mise à jour dans le manuel afin de bien expliquer la chose.

**Comment by MelanieFrisoli** [comment]
Excellent. Merci Robert !
