### ISSUE TITLE
Output des nouveaux speakers créés

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#295]
v2113
Quand je prends un speaker setup comme celui du B-187 où les sorties vont de 31 à 62 avec les subs en 5 et 6 et que je veux créer une paire de speakers pour, par exemple, avoir mes sorties stéréo, les nouveaux speakers créés ont automatiquement 63 et au-dessus comme numéros d'output.
Est-ce que ce ne serait pas mieux pour l'utilisateur que les outputs commencent au début ? 
Il me semble que cela ferait plus de sens si les nouvelles sorties créées commençaient à 1. 
(Cela étant j'imagine que c'est speaker setup un peu particulier qu'on ne retrouve pas souvent)

**Comment by Normandeau** [comment]
Peut-être que ce serait mieux... éventuellement. Pour l'instant j'ajoute une note dans le manuel:
**NOTE:  If you want to send the sound to the speakers of your computer, which correspond, by definition, to number 1 and 2 and if your speaker setup doesn’t include no 1 and 2, you won’t be able to set the stereo routing properly. To solve this, you must add independent direct outputs no 1 and 2 in your speaker setup.**
