### ISSUE TITLE
Comportement de la fenêtre 2D

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#296]
V2113
Quand j'ouvre la fenêtre 2D, elle se place au-dessus de SpatGRIS. Quand je clique sur SpatGRIS, elle se place en arrière et si je porte l'attention de l'ordinateur sur un autre logiciel et que je reviens sur SpatGRIS, elle se replace automatiquement devant. 
Est-ce que c'est son "bon" comportement ou devrait-elle toujours être gardée en avant de SpatGRIS ?

**Comment by Normandeau** [comment]
Je n'ai pas vraiment d'opinion là-dessus. En fait, je la place systématiquement à côté pour éviter d'avoir à dealer avec ça!

**Comment by Normandeau** [comment]
En fait je vois cela plutôt comme un bon comportement finalement. Cela signifie que si on passe à autre chose après avoir mis la fenêtre 2D en arrière-plan, le fait de revenir à SpatGRIS nous remémore que celle-ci est ouverte. Combien de fenêtres se trouvent ainsi perdues en arrière-plan dans la plupart des logiciels qu'on utilise? Et elles pleurent ainsi dans l'infini inconsolable du trouveur...
