### ISSUE TITLE
Lorsqu’on utilise des entrées en direct dans le DAW, le fait de spécifier des Buffer Size différents pour le DAW et SpatGRIS peut entraîner une distorsion numérique.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#298]
V2114
Lorsqu’on utilise des entrées en direct dans le DAW, le fait de spécifier des Buffer Size différents pour le DAW et SpatGRIS peut entraîner une distorsion numérique.
Cela se produit surtout si les valeurs sont très éloignées les unes des autres. 
Peut-être cela pourrait-il être indiqué dans le manuel. 
Testé dans Live 10 et SpatGRIS V2114, mais je me rappelle la même chose avec la version Jack et Logic.

**Comment by Normandeau** [comment]
Je pense que c'est un phénomène normal. Je le mets dans le manuel.

**Comment by Normandeau** [comment]
Mis dans le manuel
