### ISSUE TITLE
Deux-trois détails dans le GUI

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#299]
v21114
Rien d'urgent ni de prioritaire mais quelques détails que j'ai pu remarquer à l'utilisation : 

- La fenêtre "About SpatGRIS" s'ouvre sur mon écran principal lorsque SpatGRIS est sur mon écran secondaire
- Dans "output gain" on peut sélectionner "db" et ça fait un peu bizarre. Est-ce qu'on pourrait ne rendre que les chiffres sélectionnables ? 

![Screen Shot 2021-07-19 at 4 37 55 PM](https://user-images.githubusercontent.com/74631914/126224758-5821225e-432c-4fad-8091-d502c9ed4699.JPG)

![Screen Shot 2021-07-19 at 4 38 23 PM](https://user-images.githubusercontent.com/74631914/126224776-5565cd86-8f4e-4043-be94-63e097110900.JPG)

- Une fois qu'un speaker est sélectionné dans l'interface du setup, on dirait qu'on ne peut plus n'avoir aucun speaker de sélectionné (donc on reste toujours avec un speaker orange). Visuellement ça me gêne un peu. Je n'ai pas été capable d'enlever ça à moins de recharger mon speaker setup 

![Screen Shot 2021-07-19 at 4 45 02 PM](https://user-images.githubusercontent.com/74631914/126225019-59caae43-1371-4f22-afe6-d9e041890a5e.JPG)

**Comment by Normandeau** [comment]
• Combien de fois on fait About dans un logiciel?
• «Dans "output gain" on peut sélectionner db.» Ça n'a pas l'air de trop perturber l'information qu'on entre. J'ai même essayer avec dB, puis avec SpatGRIS. Peu importe le texte qu'on entre, ça devient 0.00 db
• «Je n'ai pas été capable d'enlever ça».
Faut lire le manuel ou l'index du manuel! ;-) Trop bien fait!!!
5.6.5. Show Numbers
Clicking on a speaker or its number selects it; Right-clicking deselects it.

**Comment by MelanieFrisoli** [comment]
- pas très souvent c'est vrai
- en effet ça ne perturbe pas l'information, ça me perturbe moi ;)
- Oh la la merci ! Pourtant j'ai lu le manuel plusieurs fois ! 

En tout cas, ce sont vraiment des détails sans trop d'importance, c'est sûr !

**Comment by Normandeau** [comment]
Oh la, la. On ne veut surtout pas que tu sois perturbée, on a trop besoin de toi. Alors on fera le changement, mais peut-être pas tout de suite...
;-)
