### ISSUE TITLE
Les numéros OSC et BlackHole doivent correspondent sinon il n'y a pas de son

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#300]
V2114
En testant quelque chose dans BigSur avec la version 2114 (en attendant la version 2115...), j'ai ouvert une session Reaper où il y avait une erreur dans les attributions de numéros OSC, par rapport aux numéros de sorties BlackHole. Il est écrit partout dans le manuel qu'il vaut mieux faire en sorte que les numéros concordent, juste pour être cohérent dans le travail. Mais cela n'avait jamais été décrit comme une contrainte absolue!

La situation: session Reaper avec deux pistes octophoniques (audio 1-8 et 9-16) et une piste stéréo (audio 17-18). SpatGRIS possédant 20 sources (les 2 de plus pour les subs).
Sur la 2e octophonie, ControGRIS était ajusté à 17-24. Résultat: aucun son!!! Les numéros OSC 17-24 sont au-delà des numéros BlackHole 9-16. Pour être absolument précis, il peut y avoir du son, si auparavant, les sources correspondantes ont été activées correctement. Mais:
-  il n'y a pas de spatialisation
- dès qu'on utilise la fonction Reset Input Position, le son s'arrête.

• Si je ramène les no OSC à 15-22, je vois les sources 15-16 et j'ai alors du son sur ces deux seules entrées qui fonctionnent (il y a du son qui entre sur les autres sources mais elles ne vont nulle part):

![Capture d’écran, le 2021-07-23 à 18 47 57](https://user-images.githubusercontent.com/8959779/126848290-8c27d543-9eff-4c23-9f2f-bf2d9e27650b.jpg)
• Si je ramène les no OSC à 11-18, je vois les sources 11-16 et j'ai alors du son sur ces six seules entrées qui fonctionnent:

![Capture d’écran, le 2021-07-23 à 18 49 41](https://user-images.githubusercontent.com/8959779/126848409-5c749c6d-60df-4b9b-8f25-b9353ed0431a.jpg)

Je viens de tester avec la version 2.1.6 et c'est le même comportement. Sauf que si on fait Reset Input Position, ça n'arrête pas le son. Il n'est plus spatialisable, il est fixe mais il continue de fonctionner avec les dernières positions enregistrées.

Conclusion: est-ce que j'ai la berlue? Car je n'avais jamais réalisé cela. Et je ne dois pas être le.a seul.e, car on vient de passer deux semaines à corriger le manuel et c’est écrit partout comme un «conseil» de faire coïncider les numéros OSC et audio. Mais ce n'est décrit nulle part comme étant une contrainte! En fait je pense que c'est plutôt logique comme comportement.
Qu'en dites-vous?
Ça implique des corrections dans le manuel cependant... ;-(

**Comment by NicolaGiannini** [comment]
Je confirme que les numéros OSC et Blackhole doivent correspondent sinon il n'y a pas de son.

Certains cas que j'ai testés :

Si j'active une instance de ControlGRIS et les numéros OSC et Blackhole ne correspondent pas, je n'ai pas du son.

Si les numéros correspondent, j'ai du son.

Si à partir d'une situation où les numéros correspondent (et donc j'ai du son) je change les numéros parce qu'ils ne correspondent plus, j'obtiens toujours du son, mais la spatialisation ne fonctionne plus. De que j’appuie sur Reset Input Position, je n'ai plus du son.

Oui probablement on doit faire des corrections dans le manuel :)

**Comment by Normandeau** [comment]
V2115
Corrections effectuées dans le manuel et le Quick Start Guide.
