### ISSUE TITLE
SpatGRIS1 fait planter systématiquement SpatGRIS 2.1.9 et plus à la fermeture du plugiciel

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#301]
V2115
V1.02 MacOS 10.15.7 DP 11.00
Une vieille chose! La dernière version de SpatGRIS1 (le plugiciel) datant de 2018. Je voulais vérifier si ça fonctionnait encore pour un client qui l'utilise toujours. Ça fonctionne, en mode OSC Spatialisation. Mais dès qu'on ferme la fenêtre du plugiciel (SpatGRIS1 donc), SpatGRIS3 quitte automatiquement. On ne peut rien faire avec cela mais c'est dommage! J'aime bien les vieilles choses qui ont du vécu! Et il n'a que trois ans! Obsolescence planifiée? Pour faire encore plus d'argent?
SpatGRIS2 V216
Par contre, SpatGRIS1 ne fait pas planter SpatGRIS2.1.6...
Quelque chose à investiguer ici?

**Comment by NicolaGiannini** [comment]
SpatGRIS3 V2115
SpatGRIS1 1.02
MacOS 10.14.6, Logic 10.5.1
Je confirme que la fermeture de SpatGRIS1 fait planter SpatGRIS3.

Dans mon cas SpatGRIS1 ne fait pas planter SpatGRIS3,  version 2.1.8.

**Comment by Normandeau** [comment]
V2116
Cette version aussi se fait fermer par SaptGRIS1. Ce n'est peut-être pas grand chose, mais c'est aussi peut-être un signe de faiblesse dans SpatGRIS depuis la version 2.1.9. Ça vient certainement de l'OSC, car SpatGRIS1, en mode Audio (PanSpan) n'a pas cet effet-là. À suivre. Je l'ai mis dans les Known Issues du manuel pour le moment.

**Comment by Normandeau** [comment]
Retrouvé cette note dans le Read Me de SpatGRIS102, la dernière instance du plugiciel:
«SpatGRIS 1.02 is the last update that send an OSC code to the Server when an instance of the plugin is removed from the DAW.»
Cause du problème?

**Comment by Normandeau** [comment]
V301
La nouvelle version plante aussi à la fermeture de la fenêtre de SpatGRIS1.

**Comment by Normandeau** [comment]
V302
Réglé
