### ISSUE TITLE
Colorize Sources et Reset Sources Position: corrections orthographiques

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#302]
V2116
On a oublié cela. Pas d'urgence. Ça peut attendre la prochaine version.
Changer Inputs de Colorize Inputs  et Input de Reset Input Position pour le terme Sources:

![Colorize Sources](https://user-images.githubusercontent.com/8959779/127704184-062ebe10-78e4-4eac-bab0-85ec7c797177.jpg)

**Comment by NicolaGiannini** [comment]
V3.00
"Reset Input Position" est devenu "Reset Sources Position".
Il faudrait toujours changer "Colorize Inputs" pour "Colorize Sources".

**Comment by Normandeau** [comment]
V301
Réglé.
