### ISSUE TITLE
La fenêtre d'enregistrement ne devrait pas passer en arrière-plan

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#303]
V2115
Lorsqu'on clique sur Record, cela fait apparaître la fenêtre des paramètres d'enregistrement. Mais si on clique ensuite sur SpatGRIS3, celle-là passe en arrière-plan. Ce qui peut mener à une situation assez confuse, car tant qu'on n'a pas cliqué sur Record dans cette fenêtre, elle attend quelque chose. Par exemple si on appuie alors de nouveau sur le bouton Record et il ne se passe rien. Cette fenêtre devrait rester au premier plan tant qu'on n'a pas appuyé sur Record (le carré rose).

**Comment by NicolaGiannini** [comment]
Je seconde.

**Comment by MelanieFrisoli** [comment]
Je confirme. C'est un peu comme ce qu'il se passait avec la fenêtre des Préférences.

**Comment by Normandeau** [comment]
V301
Réglé.
