### ISSUE TITLE
Fermer la fenêtre de Monitoring OSC fait planter SpatGRIS

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#306]
SpatGRIS v3.0.1
J'ai ouvert le monitoring OSC et en voulant fermer la fenêtre, SpatGRIS a planté.
J'ai retenté la manipulation plusieurs fois et ça a systématiquement fait crasher SpatGRIS.

**Comment by MelanieFrisoli** [comment]
https://user-images.githubusercontent.com/74631914/132555743-7f1d39b2-8498-4d44-b116-cb70a82ab44d.mp4

**Comment by NicolaGiannini** [comment]
Je confirme.

**Comment by Normandeau** [comment]
V302
Réglé
