### ISSUE TITLE
Police trop grosse dans le fenêtre 2D

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#307]
V301
Certains numéros de sources à 2 chiffres et tous les numéros à 3 chiffres ne s'affichent pas correctement dans la fenêtre 2D. Il faudrait utiliser un grosseur de police plus petite. Regardez le cercle mauve: 20 manque. Et dans le cercle bleu pâle au centre qui commence à 25: 26, 28, 29 et 30 manquent:

![Capture d’écran, le 2021-09-12 à 13 33 54](https://user-images.githubusercontent.com/8959779/132997364-484ad343-f0e1-4f84-8fa3-2ea077358dbb.jpg)

**Comment by Normandeau** [comment]
Et c'est très variable pour les numéros à 2 chiffres. Ici les numéros commencent à 49:
![Capture d’écran, le 2021-09-12 à 14 40 48](https://user-images.githubusercontent.com/8959779/132999106-f8ca0469-6f0e-43d1-8e08-aa41152de6ca.jpg)

**Comment by MelanieFrisoli** [comment]
V301
Je confirme, chez moi aussi de nombreux nombres à 2 chiffres n'en montrent qu'un.
Dans la capture d'écran ci-dessous, seuls les points verts contiennent un seul chiffre (Sources de 1 à 9). Tous les jaunes, oranges, bleus devraient avoir deux chiffres et ce n'est largement pas le cas.
![Screen Shot 2021-09-12 at 5 12 07 PM](https://user-images.githubusercontent.com/74631914/133003021-3f957b7f-ff0c-40cd-a8b3-637d7d01c364.jpg)

**Comment by NicolaGiannini** [comment]
V301
Je confirme.

**Comment by Normandeau** [comment]
V302
Réglé
