### ISSUE TITLE
Bug visuel bizarre

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#311]
V3.0.2
Je travaillais sur Live et Max et bien sûr SpatGris pour ma spatialisation (chez moi en binaural).
Au bout d'un moment , j'ai ces images bizarres à la place de mon patch Max (SpatGRIS est alors sur mon deuxième écran) cf. images ci-dessous.
Impossible de voir mon patch s'afficher. Seul le redémarrage de l'ordinateur a pu me faire retrouver un état normal dans Max.
(Je me permets de poster ceci car il y avait peut-être des suspicions de problèmes de graphisme dans SpatGRIS - par exemple avec ma performance à Ultrasons)
Sur Mojave en ce moment. 

![Screen Shot 2021-09-28 at 10 01 57 AM](https://user-images.githubusercontent.com/74631914/135146896-09f595bb-ed34-4953-aa9b-4f5db591e2a7.jpg)
![Screen Shot 2021-09-28 at 10 02 34 AM](https://user-images.githubusercontent.com/74631914/135146900-da671688-3c60-4a9d-a6e0-b3070075920a.jpg)

**Comment by Normandeau** [comment]
Je mettrais cela sur le compte du HDMI!

**Comment by Normandeau** [comment]
Peux-tu valider avec un autre protocole vidéo, comme Mini Display?

**Comment by MelanieFrisoli** [comment]
Je n'ai pas réussi à reproduire le bug, en HDMI. Malheureusement (ou heureusement!)
(et je ne connais pas cet autre protocole vidéo)

**Comment by Normandeau** [comment]
Et sur le compte de Max ;-)

**Comment by Normandeau** [comment]
311
Quelque chose de nouveau à ce sujet? Ou on ferme.

**Comment by MelanieFrisoli** [comment]
311
Je n'ai pas revu ce bug depuis un moment, pourtant j'ai retravaillé dans les exactes mêmes conditions.
