### ISSUE TITLE
SpatGRIS plante quand j'essaie d'ouvrir un speaker setup que je viens de sauvegarder

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#312]
V3.0.2
J'ai créé un setup pour un concert samedi avec SpatGRIS v3.0.2 et en voulant le rouvrir, SpatGRIS plante systématiquement. Impossible de le rappeler donc et je me retrouve à le refaire à chaque fois.
La petite roue tourne et je ne peux que forcer à quitter. 
Avez-vous déjà eu ce problème ?

**Comment by SamuelBeland** [comment]
Je peux avoir une copie du setup?

**Comment by MelanieFrisoli** [comment]
Oui bien sûr le voici:
https://we.tl/t-UjLkTt8ia7

(essayé de l'ouvrir avec SpatGRIS3 et même chose)

**Comment by MelanieFrisoli** [comment]
V3.02. 
Aussi je suis en train de refaire mon setup et premier paramètre que je touche (X sur une sortie directe) et SpatGRIS plante. 
(Ce n'est pas la première fois que ça me fait ça - j'ai déjà dû recommencer un setup presque fini parce que SpatGRIS avait planté au moment anodin où je touchais un paramètre)

**Comment by NicolaGiannini** [comment]
V302
Bonjour tout le monde !

Dans mon cas, j'arrive à ouvrir, modifier et enregistrer ton Setup de Mélanie. Je n'arrive pas à faire planter SpatGRIS, pour le moment.

**Comment by MelanieFrisoli** [comment]
J'ai éteint et rallumé l'ordinateur et j'ai réussi à le rouvrir également. 
On dirait qu'au bout d'un moment, mon ordinateur sature avec SpatGRIS et n'est plus capable d'en prendre plus. 
Et là c'est plantage sur plantage, pour un oui ou pour un non. 
Je ne comprends pas vraiment pourquoi mais je sais que ça fait plusieurs fois que ça m'arrive.

**Comment by Normandeau** [comment]
Situation non reproductible sur d'autres machines apparemment.
