### ISSUE TITLE
Sphere et Cube ne sont plus possibles

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#313]
V302
Les valeurs négatives de Z (Elevation) pour construire une vraie sphère ou un vrai Cube ne sont plus possibles. Si on entre ces valeurs, c'est 0 qui est automatiquement mis en place.

Signalé par un utilisateur, et validé par moi:

I'm a studio technician at Leeds Beckett University, in the UK.  I'm trying to set up the new SpatGRIS3 in our new ambisonic sphere, but there is an issue with the lower speakers.  Our system is a 4-8-4 sphere, so I started with your 2-6-8-6-2 sphere preset, and deleted a few channels .  This gives me a rough approximation of what I need, however, whenever I try and adjust the angles of the lower ring, the elavation of the speaker jumps to zero and I can't seem to enter the negative elavations I need.  Is this a bug, or am I doing something wrong?

**Comment by Normandeau** [comment]
Comparaison de trois sphères:

V216 (ancien format XML)
Valeurs négatives affichées et modifiables, sans problème:

![Sphere 216](https://user-images.githubusercontent.com/8959779/135494583-9e6101b0-8968-4353-9a8c-97d9a89b6c23.jpg)

V219 (nouveau format XML)
Valeurs négatives affichées mais ramenées à 0 ou plus (valeurs positives) dès qu'on essaie de les modifier, comme on le voit pour les hp 2 et 3 (au-dessus de celui qui est sélectionnée en jaune):

![Sphere 219](https://user-images.githubusercontent.com/8959779/135494792-f1f7a1ab-3f91-46f0-bdec-70f7ce75d449.jpg)

V302
Aucune valeur négative affichée et valeurs positives seulement dès qu'on essaie de les modifier. Ici c'est différent. Toutes les valeurs de Z sont sont affichées à 0 ou plus (valeurs positives), sans que les positions réelles des hp en soient affectées (voir hp 14 dans la figure, avec un Z = 0 mais situé en bas de la sphère). Ce n'est que lorsqu'on essaie de changer une valeur que le hp se déplace automatiquement dans la partie positive des valeurs de l'élévation:

![Sphere 302](https://user-images.githubusercontent.com/8959779/135494856-9d0c7a6a-d0ea-464b-8ddb-83069b91fbb0.jpg)

**Comment by Normandeau** [comment]
delmenhorst
Evelation range just from 0 - 90 degrees. Its not possible to go under 0 or above 90 like in some template. ( DOME44 (2-6-8-12-8-6-2) Sphere for example)

**Comment by Normandeau** [comment]
V315
Est-ce que le problème des valeurs négatives de Z peut-être résolu facilement? Depuis la version 2.1.9. (modification du format XML des speaker setup, on ne peut plus fabriquer de sphère ni de cube complets. Depuis la version 3.0 toutes les valeurs de Z plus grandes que 90, ou avec des valeurs négatives sont ramenées à 90 dès qu'on les touche. 
Aucune explication ne nous a jamais été fournie pour expliquer cela.
Remarquez d'ailleurs que ControlGRIS ne va pas non plus en dessous du plancher...
Je prépare une pièce pour le dispositif du SARC à Belfast qui possède 8 haut-parleurs sous le plancher (une rareté j'en conviens). Et pour l'instant je ne peux pas designer le dispositif que j'aimerais bien ajouter dans nos templates.
La question de fond est: pourquoi afficher une sphère ou un cube complet dans SpatGRIS3 si on ne peut plus rien faire avec? Alors qu'avant on pouvait au moins mettre les hp en bas, à défaut de leur parvenir de l'automation à partir de ControlGRIS (d'autres sources OSC pouvaient sans doute y parvenir).

Voici le SARC:

https://user-images.githubusercontent.com/8959779/156424465-ecc4718f-709e-4508-b9c1-1e6466a6a457.mp4

**Comment by Normandeau** [comment]
Sphere
En plus on a mis dans nos Templates la sphère complète à 44 canaux et il n'y en que 28 qui fonctionnent... Tous ceux situés en dessous de l'horizon sont muets! Est-ce qu'avec Max ou une autre source OSC directement branchée sur SpatGRSI3 on serait capable d'activer les haut-parleurs sous le plancher de la sphère? Ou la fonction est-elle toutmsimplement disparue?
Si la fonction est disparue, il faudra enlever la sphère de nos templates...

**Comment by MelanieFrisoli** [comment]
Testé depuis Max, en coordonnées polaires et cartésiennes. Effectivement, avec des valeurs négatives respectivement pour l'élévation et pour Z (dans le template "Dome44()Sphere"), rien ne descend en-dessous du plancher. Notre source reste à 0.

**Comment by Normandeau** [comment]
V3.1.10
On peut à nouveau positionner les hp en bas de l'horizon. Reste à tester pour l'audio avec Max par exemple. Avec ControlGRIS on ne peut pas descendre dans les valeurs négatives de Z. Il faudra songer à cela... éventuellement.

**Comment by MelanieFrisoli** [comment]
V3.1.10
Tests avec Max pour les valeurs négatives de Z. 
Comme le montre la vidéo ci-dessous, seul le mode Cube (et le mode Hybride quand la source possède le mode Cube sélectionné) accepte d'afficher des sources en-dessous du "sol". En mode dôme, même avec des valeurs négatives de Z, les sources sont "bloquées" au niveau du sol. 

https://user-images.githubusercontent.com/74631914/166439709-7e909205-4345-401a-8b08-bc286383b281.mp4


Note : autre remarque ici, que vous pouvez constater au début de la vidéo, quand la valeur de Z est maximale (1) en mode Dôme, la source n'atteint pas le sommet du dispositif. Or, ce serait censé être le cas : 

<img width="687" alt="Screen Shot 2022-05-03 at 6 41 39 AM" src="https://user-images.githubusercontent.com/74631914/166439851-db44b9b1-d054-4d3c-a593-6081fd5ee54b.png">

**Comment by NicolaGiannini** [comment]
Je confirme qu’en MODE cube on peut placer des sources en bas et l’audio semble fonctionner, voici la vidéo :


https://user-images.githubusercontent.com/35705913/166483267-b1de8d23-01a0-47bc-aaf9-46391952e052.mov



En mode Dôme, je confirme qu’il ne semble pas possible de positionner les sources en bas. J’ai essayé avec des patch de MAX en “Polar” et Degrés. 

En "Polar" j’ai augmenté le range de l’élévation, celui dans la vidéo va de -1.5708 à 1.5708 (dans la patch MAX qui est sur Github le range va de 0 à 1.5708 pour l’élévation). 
Dans les valeurs négatives, la source reste au sol. 


https://user-images.githubusercontent.com/35705913/166483353-dc607a71-18e6-495e-b7ab-b00bc21a8ac9.mov



J’ai aussi augmenté le range dans la patch de MAX en degrés. Dans la patch qui est sur Github l’élévation va de 0 à 90. J’ai alors créé un contrôle qui va de 0 à 360. Dans la speaker Setup Window pour placer les HP en bas, le range va de 360 à 270.
En utilisant le range de 360 à 270 avec MAX, la source reste au sol. 

https://udemontreal-my.sharepoint.com/:v:/g/personal/nicola_giannini_umontreal_ca/EYtnoqnTbHZFvJYgDYSWzaYB47YELo8Ts5WpOXK8boZcWA?e=8X7BgS

Je confirme aussi que si on envoie de MAX des coordonnées cartésiennes avec SpatGRIS en mode Dôme, quand la valeur de Z est maximale (1), la source n'atteint pas le sommet du dispositif. Cela dit, je pense que ça dépend aussi du fait que si j'envoie de MAX des coordonnées cartésiennes avec SpatGRIS en mode Dôme, aussi X et Y influencent la position en hauteur de la source.


https://user-images.githubusercontent.com/35705913/166483785-a9e1dd71-cbfa-43d0-a49c-1e8d3f7c66db.mov



Par contre, j’ai noté aussi qu’avec ControlGRIS, si on l’utilise en mode CUBE et si on met la X à 1, la source atteint le sommet du dispositif avec SpatGRIS en mode Dôme. Cela dit, j’ai aussi noté que ControlGRIS envoie des coordonnées polaires en radians (même si ControlGRIS est en mode CUBE), au moins de ce que je comprends du “Show OSC Monitor”.

**Comment by Normandeau** [comment]
Donc:
- on des hp qui se positionnent en bas, en Dome ou en Cube
- mais on ne peut déplacer une source en valeurs négatives en mode Dome, seulement en mode Cube
- en coordonnées cartésiennes en mode Dôme, quand la valeur de Z est maximale (1), la source n'atteint pas le sommet du dispositif.

De plus, relativement au positionnement des hp en mode Dome, lorsqu'on change la valeur de Z pour des données négatives, la valeur de X est affectée et tend rapidement vers 0 (ici le hp no 18):

Z à -0.00 (X : -0.38):
![Z à -0 00 Dome](https://user-images.githubusercontent.com/8959779/166490685-72a2e786-3422-4217-b4ac-2b7b3c2354a0.jpg)

Z à -0.20 X: -0.33)
![Z à -0 20 Dome](https://user-images.githubusercontent.com/8959779/166490867-62c624bf-3233-44f5-88f5-1011849c3a60.jpg)

Z à -0.40 (X: 0.00)
![Z à -0 40 Dome](https://user-images.githubusercontent.com/8959779/166491049-b875ad21-fb88-4b4a-88f6-585ec5966156.jpg)

Cette situation ne se produit pas en mode Cube, car Z est vraiment vertical.

**Comment by NicolaGiannini** [comment]
Je pense que, en général, avec SpatGRIS en mode DOME, si on utilise les coordonnées cartésiennes XYZ pour déplacer les sources et/ou les HP on peut avoir des comportements inattendus, cela parce qu’en mode DOME les sources et les HP doivent se trouver sur la surface du dôme, tandis que les valeurs XYZ permettent de placer les sources et les HP partout, y inclus des positions impossibles pour le mode DOME. 

Je pense que cela pourrait être en relation avec ça : https://github.com/GRIS-UdeM/ControlGris/issues/179#issuecomment-1058088120

**Comment by Normandeau** [comment]
Voici le comportement inattendu!
Comparaison entre le comportement d'un hp en mode Dome selon qu'on le déplace en Elevation ou en Z.
En Elevation, on a un comportement «normal», ou attendu (première partie du vidéo).
Alors qu'en Z, le paramètre X est ramené rapidement à 0, puis en s'approchant du sommet, le paramètre Y est également ramené à 0, où il restera ensuite. Le paramètre X, après avoir atteint le sommet, varie de 0 à +1.00 à 0, lorsque Z varie de +1.00 à 0 à -1.00:
 

https://user-images.githubusercontent.com/8959779/166500836-e37b4064-345c-43f8-a8a2-8ee9f79b9dd0.mov

**Comment by OKGougou** [comment]
En effet, Azimuth et Elevation rendent le positionnement des speakers plus intuitif en mode Dome (coordonnées polaires), alors que X, Y et Z facilitent l'utilisation en mode Cube (coordonnées cartésiennes). Ça me paraît assez logique ainsi. 
D'ailleurs, en mode Cube, l'Elevation se comporte («anormalement») comme X, Y et Z en mode Dome.

**Comment by MelanieFrisoli** [comment]
Et je me permets d'ajouter qu'en mode Dôme, le positionnement des sources est aussi plus intuitif lorsque l'on utilise des valeurs d'azimuth et d'élévation. En tout cas, c'est ce que je fais avec mes périphériques Max et cela fonctionne très bien :)

**Comment by Normandeau** [comment]
Donc (prise 2):
- On ne peut pas déplacer une source en valeurs négatives en mode Dome, seulement en mode Cube
- En coordonnées cartésiennes en mode Dôme, quand la valeur de Z est maximale (1), la source n'atteint pas le sommet du dispositif.
- Et l'audio a l'air de fonctionner (du moins les hp s'illuminent...)

C'est bien cela?

**Comment by MelanieFrisoli** [comment]
Je confirme, c'est exactement cela.

**Comment by NicolaGiannini** [comment]
Je confirme moi aussi.

**Comment by Normandeau** [comment]
V3.1.12
- Les hp peuvent être positionnés en dessous de l'horizon en mode Dome ou Cube. Dans le manuel, il faudra spécifier que leur positionnement est préférable en coordonnées polaires (Azimuth-Elevation) en mode Dome et en coordonnées cartésiennes (X, Y, Z) en mode Cube.
- Reste à tester le comportement sonore en Dome et en Cube. À suivre.

**Comment by Normandeau** [comment]
Le comportement sonore semble correct, à l’œil tout au moins. Car il est impossible de vérifier le tout à l'oreille, n'ayant pas de sphère sous la main. D'autres questions sont soulevées cependant ( #355 ), mais on peut fermer celle-ci pour le moment.
