### ISSUE TITLE
Proposition d'une implémentation combinée du VBAP et du DVBP

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#317]
Je réfléchis depuis très longtemps à une manière plus simple d'effectuer des trajectoires au sol dans un projet pour dôme.
Actuellement, ma stratégie a été d'utiliser deux instance différentes de ControlGRIS et d'utiliser des envois (BUS) pour faire passer un signal audio d'un côté à l'autre du dôme, sans passer par le haut. C'est le défaut du VBAP où le centre devient obligatoirement le haut de l'espace de diffusion.

On peut néanmoins utiliser le VBAP pour faire un rendu octophonique, ce qui équivaut au DVBP (Directionnal, Vector-Based Passing), où les vecteurs sont alors calculés entre les haut-parleurs du sol - puisqu'il n'y en a pas au centre (haut), mais qu'ils respectent tout de même la règle de distance constante.

Serait-il possible d'ajouter un mode automatisable de type (Horizontal - Vertical) au mode Dome de ControlGRIS? En mode horizontal, ce mode indiquerait à SpatGRIS d'ignorer les haut-parleurs ayant un degré d'élévation supérieur à 0 pour ces sources en particulier. En mode vertical, le mode Dome fonctionnerait normalement. En pouvant automatiser ce paramètre pour certaines sources, cela permettrait de facilement faire passer un même son, tantôt au dessus, tantôt à travers l'espace de diffusion. Dans l'interface, cette fonction pourrait occuper la place de l'élévation en mode Cube, actuellement vacante en mode Dôme.

Qu'en pensez-vous?

L'autre option - ma préférée toujours - serait de permettre d'assigner un mode de spatialisation différent (Dôme ou Cube) pour certains canaux en entrée dans SpatGRIS (à l'instar des sorties directes).

**Comment by Normandeau** [comment]
V310
Vos désirs sont exaucés. À vos tests maintenant!
Merci Samuel.
