### ISSUE TITLE
Communication OSC avec SpatGRIS

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#318]
Je suis en train de programmer des petits périphériques sur Max pour communiquer avec SpatGRIS et jusqu'à maintenant je m'étais beaucoup concentrée sur le mode Dôme. J'ai voulu me pencher sur le mode Cube et j'aimerais beaucoup pouvoir envoyer des données XYZ. Aucun problème avec le Y et le Z, par contre avec le X, je n'arrive pas à avoir des trajectoires droites. Je réussis seulement à faire des cercles. Est-ce qu'il y a un truc à savoir dans les données que j'envoie ? Dans le manuel, il est écrit que les valeurs doivent être entre 0 et 2pi, donc toujours un angle d'azimuth. 
Si quelqu'un a quelques lumières sur cette affaire, je suis preneuse !

**Comment by SamuelBeland** [comment]
Je crois qu'il est grand temp de réformer le format des messages OSC pour permettre aux usagers et aux usagères d'envoyer soit une coordonnée polaire (azi-ele-rad) ou cartésienne (x-y-z) à SpatGRIS. Je vais proposer quelque chose pour la prochaine version.

**Comment by MelanieFrisoli** [comment]
Ce serait génial ! 
Merci d'avance Samuel :)

**Comment by MelanieFrisoli** [comment]
Une petite suggestion aussi : 
Est-ce qu'il serait possible d'ajouter un message OSC pour SpatGRIS qui, en mode hybride seulement, permettrait de changer dynamique si notre source est en mode Dome ou Cube ? J'ai ce petit bouton sur mes périphériques Max et ce serait super pratique pour l'utilisateur de pouvoir "switcher" entre ces deux modes sans repasser à chaque fois sur SpatGRIS.

P.s: ne réforme pas tout sur l'OSC - juste l'azimuth ce sera parfait, le reste fonctionne super bien 👍🏼

**Comment by SamuelBeland** [comment]
Ajouté à 3.1.1

[Les détails sont ici.](https://github.com/GRIS-UdeM/SpatGRIS#alg-sets-a-sources-hybrid-spatialization-mode)
