### ISSUE TITLE
Question : est-ce que SpatGRIS(3) est compatible avec l'ancienne version du plugiciel qui avait le même nom (SpatGRIS1-legacy)?

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#319]
J'ai récemment ouvert mes projets de maîtrise pour les tester dans la Satosphère et qui sont spatialisés avec le plugin SpatGRIS de l'époque (Dome seulement). Le son passe entre le DAW (Logic Pro et DP) et SpatGRIS(3), mais n'en sort pas -- aucune spatialisation et les sources n'apparaissent pas dans l'affichage 3D ou 2D.

Ma déduction est que les numéros OSC ne correspondent plus. Est-ce le cas? Que faites-vous pour vos anciens projets?

J'ai gardé les anciennes version de ServerGRIS au cas, donc je ne suis pas inquiet pour faire un rendu. Mais tôt ou tard, je devrai remplacer mon ordinateur et JACK ne fonctionnera plus. Je m'inquiète donc pour la pérennité de ces compositions!

**Comment by Normandeau** [comment]
David,
Clarifions juste les termes pour commencer:
- SpatGRIS1, c'est le plugin.
- SpatGRIS3, c'est le logiciel de spatialisation.
Tous nos tests à ce jour démontre la compatibilité SpatGRIS1 avec SpatGRIS3. On a même réglé un bogue de communication entre les deux avec la version actuelle de SpatGRIS3 qui est la 3.0.2.
Je viens de vérifier:
MacOS Catalina 10.15.7
Logic 10.6.3
BlackHole 0.2.10
SpatGRIS1 1.0.2 
SpatGRIS3 303 (une version bêta)
Tout baigne.
Si je comprends bien tu utilises toujours Jack? Pourquoi ne pas le remplacer par BlackHole?
Je viens également de vérifier la version PanSpan (mode audio) de SpatGRIS1 dans un projet DP de 2018 et ça roule.

**Comment by led78** [comment]
Robert,
Je vais revérifier pour être certain. Moi je suis sur MacOS High Sierra 10.13.6
J'utilise la dernière version de SpatGRIS3 (3.0.2), mais j'ai gardé les dernières version du ServerGRIS (avec JACK) au cas, pour mes compos faites avec l'ancien plugin SpatGRIS1.
J'ai ouvert mes deux projets (Cathédrales : I et II), l'un sur Logic Pro et l'autre sur DP, avec SpatGRIS3. Le son se rend (input), mais ne sort pas (output); il n'y a aucune source de visible et SpatGRIS3 ne semble pas recevoir les coordonnées OSC de mes plugins SpatGRIS1. Dois-je modifier les adresses OSC?

Comme je disais, dans le cas ou ça ne fonctionne pas, je peux toujours utiliser une ancienne version de ServerGRIS pour faire un rendu, puisque je suis toujours sous High Sierra et que JACK peut encore fonctionner.

**Comment by NicolaGiannini** [comment]
Salut David!
Es-tu en train d’utiliser SpatGRIS legacy version 1.0.2 ? https://github.com/GRIS-UdeM/SpatGRIS-legacy/releases

Parce que j’avais ton même problème et j’avais réalisé que j’étais en train d’utiliser la 1.0.1.

Je viens de tester et dans mon cas SpatGRIS-1 legacy version 1.0.2 fonctionne avec SpatGRIS 3.1.0 (testé dans Logic).

Je ne suis pas sûr à 100 %, mais je pense qu'une chose a changé. Il est maintenant nécessaire que les sorties du DAW correspondent aux sources de SpatGRIS1 legacy. 
Exemple :
Si on utilise les sorties du DAW 3-4, il faut mettre comme 1st source dans SpatGRIS1-Legacy la sortie 3.

En espérant que cela aide !
À bientôt,
Nicola

**Comment by led78** [comment]
« Es-tu en train d’utiliser SpatGRIS legacy version 1.0.2 ? https://github.com/GRIS-UdeM/SpatGRIS-legacy/releases
Parce que j’avais ton même problème et j’avais réalisé que j’étais en train d’utiliser la 1.0.1.
Je viens de tester et dans mon cas SpatGRIS-1 legacy version 1.0.2 fonctionne avec SpatGRIS 3.1.0 (testé dans Logic). »

C'était exactement cela, merci Nicola! 
J'avais la version 1.0.1 du plugin. Suite à la mise à jour vers la version 1.0.2, tout semble maintenant fonctionner normalement!
