### ISSUE TITLE
Mode Hybride

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#321]
V310
Nous avons donc enfin un mode Hybride. Va falloir tester toutes les fonctions «normales» de SpatGRIS3  afin de déterminer si cette nouvelle fonction interagit avec d'autres paramètres du logiciel. Par exemple comment se comporte l'enregistrement?

Un premier test aujourd'hui, au sujet du CPU.
J'ai pris le projet de _Rail_, le plus gourmand de tous mes projets actuels:
- 116 canaux audio dont 112 avec ControlGRIS;
- composé en mode Dome.

Comparé le CPU Usage de ce même projet en:
- Dome: 23%
- Cube: 55%
- Hybride Dome (58 pistes)/Cube (56 pistes): 36%

Pour le mode Hybride j'ai changé les 56 canaux de ControlGRIS en mode Cube ainsi que dans SpatGRIS3. Je n'ai pas ajouté d'automation de l'axe Z (inexistant dans la pièce originelle).
Pour le reste, ça fonctionne du feu de Dieu! Impressionnant. Avoir su on aurait demandé avant! Quoique ça fait deux ans....

**Comment by NicolaGiannini** [comment]
Les résultats de mes tests semblent cohérents avec ceux de Robert.
J’ai pris le projet de For Hannah :
94 canaux audio dont 92 avec ControlGRIS;
composé en mode Dome

Comparé le CPU Usage de ce même projet en:
	•	Dome: 11%
	•	Cube: 18%
	•	Hybride Dome (44 pistes)/Cube (48 pistes): 15%
Vraiment super !
