### ISSUE TITLE
Sauvegarder et rouvrir un projet en mode Hybrid

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#322]
V310
J'ai fait quelques tests et tout semble fonctionner correctement en ce qui concerne la relation entre le Speaker Setup, le projet et le mode.

Le choix de l'algorithme dépend du Speaker Setup qu’on charge. Maintenant si on charge un speaker setup Hybrid, le mode passe automatiquement à Hybrid. 

Je me demandais cela : l'ouverture d'un projet créé en mode Hybride pourrait activer automatiquement le mode Hybride ?

Maintenant, si nous ouvrons un projet qui a été créé en mode hybride, à partir d’un setup non hybrid, les affectations DOME/CUBE pour les sources ne sont pas affichées. Le fonctionnement est correct, mais je me demandais s'il ne serait pas plus intuitif d'activer automatiquement le mode hybride dans cette situation. Mais cela irait probablement à l'encontre de la philosophie qui consiste à garder séparés les projets et les speaker setup. 
Qu'en pensez-vous ?

Le mode hybride est vraiment très intéressant !

**Comment by Normandeau** [comment]
DOME/CUBE/HYBRIDE
Le mode hybride est en fait un mode DOME sur le plan du speaker setup. Si le speaker setup a été créé en CUBE, il sera converti automatiquement en DOME (avec un avertissement), comme lorsqu'on passe de CUBE à DOME. Donc il n'y a pas à proprement parler de Speaker setup hybride. Seules les projets sont en mode hybride.
Actuellement, le mode hybride **lui-même** n'est pas sauvegardé nulle part. Par contre les affectations dome/cube le sont avec le projet:
![Capture d’écran, le 2021-11-26 à 11 46 41](https://user-images.githubusercontent.com/8959779/143611630-3b86e22b-08dd-4710-bf7f-0300d898e300.jpg)

Cependant, si entretemps on a activé DOME ou CUBE, et qu'on rouvre un projet fabriqué en hybride, celles-ci n'apparaîtront que lorsqu'on réactivera le mode Hybride.
Donc, oui ce serait une bonne idée qu'un projet fabriqué en mode Hybride, s'ouvre automatiquement dans ce mode.

**Comment by MelanieFrisoli** [comment]
Tout à fait d'accord ! 
Les premières fois, ça me faisait un peu drôle que mon projet sauvegardé en mode hybride réapparaisse en dôme quand je le chargeais.

**Comment by SamuelBeland** [comment]
Actuellement, le mode de spatialisation (dome, cube ou hybrid) est sauvegardé dans le _speaker setup_ alors que l'affectation individuelle des sources est placée dans le projet.

Cela faisait du sens avant de sauvegarder le mode de spatialisation dans le _speaker setup_ à cause de la différence évidente entre les deux. Avec le mode hybride, je me rend compte que cette différence n'est pas si importante et que le mode de spatialisation devrait réellement toujours être sauvegardé avec le projet et jamais avec le speaker setup.

Ou alors, est-ce que l'on devrait le sauvegarder dans les deux et simplement toujours essayer d'appliquer mode d'un fichier lorsque on l'ouvre?

**Comment by Normandeau** [comment]
Quelques précisions.
Il y a seulement deux modes de speaker setup: Dome ou Cube. L'un des deux est automatiquement affiché selon le choix de l'algorithme avec lequel il a été conçu. C'est une caractéristique de la configuration de hp et c'est là que c'est sauvegardé. Et c'est très clair comme cela.
Il n'y a pas de speaker setup hybride. On ne peut pas en concevoir ni en sauvegarder un (pour l'instant...). Le mode hybride est juste une fonction, pas un algorithme. Et cette fonction devrait pouvoir être conservé avec le projet, car c'est bien ce dernier qui est hybride. Pas le speaker setup. Il faudrait donc mémoriser le mode Hybrid du côté du projet, avec l'affectation des sources. Ce serait plus cohérent, car actuellement, rien ne signifie à l'ouverture d'un projet qu'il a été créée en mode hybride. Et si un Cube est ouvert au moment où on ouvre un projet Hybrid, on devrait avoir le même avertissement qu'on obtient en tentant de passer à un dome:

![Capture d’écran, le 2021-11-29 à 16 31 46](https://user-images.githubusercontent.com/8959779/143946082-8f921cd0-52f6-4831-a9cc-79002416c23d.jpg)

**Comment by SamuelBeland** [comment]
En fait, 3.1.1 sauvegarde littéralement "hybrid" dans les speakers setups hybrides.

![temp](https://user-images.githubusercontent.com/39448259/144749423-c9e54c0d-59bf-4d13-b2f1-b18adfb9ab20.png)

Je vais retirer le mode de spatialisation du speaker setup et l'intégrer au projet à la place.

**Comment by Normandeau** [comment]
V313
Cela n'est toujours pas fait. À suivre.

**Comment by MelanieFrisoli** [comment]
V313
Je confirme, la fonction hybride est toujours sauvegardée avec le speaker setup et je suis d'accord avec Robert, elle devrait pouvoir être sauvegardée avec le projet.

**Comment by Normandeau** [comment]
V313
Précisions au sujet du mode Hybride. Après avoir discuté le bout de gras avec Gaël jeudi, voici de quoi il retourne.
Il y a deux informations qui sont sauvegardées lorsqu'on utilise le mode Hybride.

1. SpeakerSetup Hybrid
Dans le Speaker Setup, il y a deux informations qui sont sauvegardées en tête de liste:
Version de SpatGRSI3 (ici 2.1.13) et MODE (ici Dome):
<SPEAKER_SETUP VERSION="2.1.13" SPAT_MODE="Dome">
C'est ici également que le mode Hybrid est sauvé:
<SPEAKER_SETUP VERSION="3.1.3" SPAT_MODE="Hybrid">
Donc si vous sauvegardez un speaker setup un mode Hybrid, il s'ouvrira correctement, avec le bon mode sélectionné:
![Capture d’écran, le 2022-02-06 à 16 54 52](https://user-images.githubusercontent.com/8959779/152702962-5404fbfe-52ad-40a1-8ed1-391951a3b01b.jpg)

2. Project Hybrid
En mode Hybrid, la gestion des sources par l'un des deux algorithmes,  Dome ou Cube, est sauvegardée dans le projet. Si vous ouvrez un projet Hybrid avec le mode Hybrid ouvert dans SpatGRIS3, cette page s'ouvrira correctement:
![Capture d’écran, le 2022-02-06 à 16 58 34](https://user-images.githubusercontent.com/8959779/152703074-d4b8d85b-e0ae-4821-ad1f-ef02068a22fa.jpg)

Actuellement cependant, si vous ouvrez un projet Hybrid avec l'algorithme  Dome ou Cube, cette page ne s'ouvrira pas, et rien ne dit à l'utilisateur que son projet est hybride. Ce qui peut éventuellement conduire à des méprises ou des erreurs.
On songe à un moyen de faire en sorte que l’utilisateur soit prévenu du caractère hybride de son projet s'il l'ouvre en Dome ou en Cube.
Note dans le manuel.

**Comment by MelanieFrisoli** [comment]
V313
Oui, pour le moment, cela pourrait juste être un message qui apparaît pour prévenir l'utilisateur quand il ou elle ouvre le projet. En attendant qu'il soit possible de le sauvegarder directement avec un projet ?

**Comment by MelanieFrisoli** [comment]
V318
J'ai pu ouvrir un projet ou un speaker setup et l'algorithme est bien sélectionné.

**Comment by Normandeau** [comment]
V318
La condition à remplir pour qu'un projet sauvé en mode Hybrid s'ouvre bien en mode Hybrid est qu'il ait été sauvé avec la version 3.1.8! Vive le futur! Autrement dit, les projets sauvés avant 3.1.8 en mode Hybrid, bien que conservant les bonnes informations, ne forcent pas l'ouverture de mode Hybrid.
Cela étant dit, une fois que SpatGRIS3 est en mode Hybrid, il le reste! En tout cas, aucun des Templates de projets fournis ne font retourner SpatGRIS en mode Dome ou Cube. Parfois, certains de mes projets personnels ramènent le Dome. Mais pas troujours.

**Comment by MelanieFrisoli** [comment]
@Normandeau 
Je viens de tester et je confirme !

**Comment by NicolaGiannini** [comment]
Je pense que cela dépend également de la version avec laquelle le projet a été enregistré. Si je suis en mode HYBRID et que j'ouvre un projet enregistré en mode DOME avec la version 317 (ou précédentes), SpatGRIS reste en HYBRID. Si j'ouvre un projet DOME enregistré avec la version 318, SpatGRIS passe en mode DOME. En fait, dans les fichiers XML, l'information pour les modes est présente depuis la version 318 pour les modes DOME et CUBE.

**Mode DOME, Version 318**

![318_dome](https://user-images.githubusercontent.com/35705913/160930187-08f7c965-ad20-46ff-bd03-febb257992f3.jpg)


**Mode DOME, version 317**

![317](https://user-images.githubusercontent.com/35705913/160930252-0f84e9c0-38d4-461d-b518-7080ee7f6f6f.jpg)

**Mode HYBRIDE, Version 318** 

![318-hybrid](https://user-images.githubusercontent.com/35705913/160930576-17c46acd-2309-4998-858d-e05df7edd7da.jpg)



En quelque sorte ,l’information est présente aussi dans les versions précédentes (j’imagine depuis que le mode Hybrid existe) mais l’information est indiquée pour chaque source et non pas pour le projet.

**Comment by Normandeau** [comment]
Belle observation. Donc tout cela sera conforme au fur et à mesure que les projets seront à nouveau sauvegardés sous 3.1.8. Comme on ne peut pas sortir 3.1.8 (voir #339), je vais sauvegarder à nouveau tous les Templates de hp avec cette version, afin que les utilisateurs futurs aient la bonne version sous la main avec quoi? 3.1.9? On espère.

**Comment by Normandeau** [comment]
V319
Tous les Templates de Projects et de Speaker Setups ont été sauvegardés en version 318. Le mode Hydrid est sauvegardé partout.
