### ISSUE TITLE
Clock issue under M1, Monterey, BlackHole and Live

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#323]
V311
Mélanie:
En effet, en travaillant avec la carte son interne de nouveau Mac sous Monterey, je devais changer régulièrement entre 44,1kHz et 48kHz en f.e. pour corriger les artefacts sonores importants qui étaient générés. Cela arrivait environ toutes les 8-10 minutes. 
Cela étant, j’ai une interface audio depuis deux jours et je n’ai pas ce problème pour le moment. Je n’ai pas encore travaillé énormément sur un projet avec SpatGRIS mais disons qu’en 20 minutes ce n’est pas arrivé.
Aussi, Robert, j’ai écouté tes conseils et j’ai mis toutes les interfaces possibles sur 48kHz dans Audio Midi Setup.

**Comment by Normandeau** [comment]
Un utilisateur:

«J’ai un problème avec la version 3 que j’ai désormais implantée avec Control Gris et Blackhole sur mon Apple M1.
J’ai une carte son usb 20 sorties Umc 1820 avec un Adat pour les sorties 13 à 20 sur une Focusrite Pro40 en Hardware, et ça fonctionne très bien sur mon ancien ordinateur, bien qu’il soit en limite de travail car j’ai huit entrées dans Spatgris qui gère lui-même 13 sorties en coupole.
Sur le M1, ça fonctionne très bien au début, et au bout de 15 minutes environ, il y a des coupures importantes du flux sonore, bien que mon moniteur d’activité soit largement dans le confort.
Mon système est Monterey sur cette machine, mais j’ai également eu des problèmes avec Big Sur.
J’utilise Ableton Live 10.4.2 qui n’est as la dernière version (Live 11), mais qui fonctionne bien sans SpatGris
Ma question est donc la suivante :
	- Avez-vous eu vent de problème entre Spatgris et Blackhole ? Ou entre Blackhole et Monterey ou encore entre le VST ControlGris et Spatgris sous Blackhole ? Ou autre chose (gestion problématique de l’USB par exemple... Je fais des tas d’essais dans tous les sens mais je n’arrive pas à trouver la solution et pourquoi le système devient bancal au bout d’un certain temps, et pas au début de la mise en route.

**Comment by Normandeau** [comment]
Devin:
I think I may know what’s happening. 
It could be an issue with the clock in BlackHole running on M1 hardware. It sounds similar in this regard since the bug shows up typically between 15-21 minutes. Newer versions fixed this. I’m working on an update to BlackHole that will work well with 124 channels. The current version has some performance issues with many channels. 

There’s also been reports of issues with Live in particular. There’s a good thread on that topic. Sounds like Live made some poor choices on their real-time audio thread. 
https://github.com/ExistentialAudio/BlackHole/issues/448
I have Monterey on my M1 and could test it out.

**Comment by Normandeau** [comment]
Mélanie (21-11-29)
OS Monterey 12.0
SpatGRIS v3.1.1.
64GB de RAM
10 cores 

Fréquence d’échantillonnage : 
- avec Live et carte son externe & interne : aucun problème de glitch ou de désynchronisation cette fois, en tout cas pas avec la fréquence d’échantillonnage. 
J’ai par contre eu quelques soucis en modifiant la buffer size (son extrêmement coupé - mais en “rythme”), je fais des tests plus poussés après dans le courriel.

- avec Logic Pro 
Testé dans mon interface + carte son interne et tout va bien. Pas de désynchronisation après 20 minutes.
Ce qui a vraiment changé pour moi, je pense, c’est d’ouvrir Audio Midi Setup et de tout mettre sur la même fréquence d’échantillonnage. 
En tout cas, depuis, mon problème de départ ne semble pas se reproduire…

Buffer size : 
Par contre, pas mal de bugs avec le changement de buffer size et c’est peut-être plus problématique, puisque c’est un réglage qu’on est plus amené à modifier au cours d’un projet.
Les logiciels, que ce soit Live ou Logic, n’échangent pas ces infos avec SpatGRIS et c’est en modifiant la buffer size dans l’un ou dans l’autre que des artefacts audio se produisent.

Dans Logic :
(deux boucles audio sans effets qui tournent sur deux mesures) 
Logic à 256/512/1024 et SpatGRIS à 128 ou inférieur = glitch, de quelques-uns à totalement glitchy  (CPU Usage SpatGRIS : entre 16 et 32%à 128 - monte à 80% en 64 échantillons)
Logic à 256/512/1024 et SpatGRIS à 256 ou 512 = pas de glitch (CPU Usage entre 8 et 20% pour les 2 buffer size)
 
Quand j’ai mis Logic et SpatGRIS tous les deux sur 64 échantillons de buffer size, l’audio s’est arrêté et j’ai eu ce message:
<img width="368" alt="Screen Shot 2021-11-29 at 7 45 43 AM" src="https://user-images.githubusercontent.com/8959779/143904062-190e5efb-b8f1-48a9-969f-4e8878760594.png">

Et si je relance la lecture, c’est complètement entrecoupé. Pourtant dans Activity Monitor, personne ne devient trop fou (capture d’écran ci-dessous). 
<img width="789" alt="Screen Shot 2021-11-29 at 7 48 26 AM" src="https://user-images.githubusercontent.com/8959779/143904183-0d583e6b-216c-4aea-98ad-26da1db1f76b.png">

Après avoir réglé les deux logiciels sur 64 échantillons, j’ai voulu repasser à 256 pour les deux. 
Je lance ensuite la lecture et là l’audio est carrément inécoutable, tellement ça glitch. 
Et je continue à avoir le premier message de Logic (“Sample Rate 36,647 recognized”) 
<img width="1120" alt="Screen Shot 2021-11-29 at 7 52 43 AM" src="https://user-images.githubusercontent.com/8959779/143904320-e35df9ad-6ad9-4351-8a93-31f63a47833a.png">

CPU Usage dans Activity Monitor avec les deux buffer size à 256 : 
<img width="784" alt="Screen Shot 2021-11-29 at 7 55 21 AM" src="https://user-images.githubusercontent.com/8959779/143904387-ae58ce69-7eae-4017-a3e6-7fb584a9c78a.png">

=> Logic et SpatGRIS ne semblent pas se remettre du passage à 64 échantillons pour les deux. 
Ces tests ont les mêmes résultats que je sois dans ma carte son interne ou externe.

**Dans Live**
(trois boucles audio avec 2-3 effets qui tournent sur deux mesures)
J’ai fermé Logic, ouvert Live et ai laissé SpatGRIS tel quel. Live est en 256 échantillons et le CPU s’excite beaucoup, le son est très glitchy. 
Je ferme et rouvre SpatGRIS. Je relance la lecture dans Live et là aucun son, pourtant dans les réglages tout est beau. 
Je referme les deux et tout fonctionne à nouveau. 

Mêmes tests que sur Logic ensuite. 
Avec la carte son interne : 
Les 2 sur 64 de buffer size, des glitchs (mais pas de message d’erreur de la part de Live). Je peux ensuite remonter les valeurs de buffer size indépendamment dans les deux logiciels et je n’ai pas de coupures audio comme avec Logic. 
Ce que je remarque, bien sûr, c’est que les glitchs apparaissent en général quand la buffer size de SpatGRIS est inférieure à celle du logiciel utilisé (surtout à 128 en fait, ce qui est curieux avec la  puissance de mon nouvel ordinateur).

Avec la carte son externe :
Je me branche ensuite sur mon interface audio externe et là j’ai beau remettre les deux logiciels sur 256 ou 512, tout est vraiment glitchy et entrecoupé.
Je dois relancer les deux logiciels pour qu’ils me redonnent un son normal.

**Comment by Normandeau** [comment]
MacIntel 8 cores, 32 Gb RAM
Interface RME MadiFace USB2
MacOS 11.6.1 (Big Sur)
SpatGRIS 3.1.1
BlackHole 0.28

Logic 10.7.1
Attention: Pour Big Sur et Monterey, il faut utiliser cette version (qui ne fonctionne pas sur les anciens OS).
Buffer Size 32 ou 64: Logic et SpatGRIS3: aucun problème (entendu un seul glitch à 32, au début)

DP 11.02
Buffer Size 32 ou 64: DP et SpatGRIS3: aucun problème
Buffer Size DP 64 et SpatGRIS 32: quelques glitchs légers 
Buffer Size DP 128 et SpatGRIS 32: aucun problème

Reaper 6.42
(Reaper n'a pas de Buffer Size par défaut. Il faut le forcer à en sélectionner un dans les Préférences)
Buffer Size 32 ou 64: Reaper et SpatGRIS3: aucun problème
Buffer Size Reaper 64 et SpatGRIS 32: aucun problème
Buffer Size Reaper 128 et SpatGRIS 32: aucun problème

**Comment by devinroth** [comment]
Try installing this beta version of BlackHole. I'm still testing before I release it but I believe it will fix most of the issues. 

[BlackHole128ch.v0.2.11beta.pkg.zip](https://github.com/GRIS-UdeM/SpatGRIS/files/7620286/BlackHole128ch.v0.2.11beta.pkg.zip)

**Comment by Normandeau** [comment]
BlackHole 0.2.11
DP 11.02

Played a stereo sequence of 15 min with a buffer size of 32: no problem.
Played a multiphonic sequence of 116 tracks with a buffer size of 512 for 12 minutes: no problem.

**Comment by Normandeau** [comment]
BlackHole 0.2.11
Live 10
Un utilisateur: «J’ai testé le nouveau Blackhole durant 2 h et ça a fonctionné. Pas de saccade. Donc pour l’instant et dans l’état actuel de mon matériel, c’est ok pour moi. Avec M1 et Monterey. Je ne l’ai pas testé sur Big Sur. Je peux le faire si u veux. Cette version beta corrige donc les problèmes existants sur les M1.
Grand ouf de soulagement.»
Autres commentaires utilisateurs de Live et de M1?

**Comment by MelanieFrisoli** [comment]
BlackHole 0.2.11
Live 11.0.12

En effet, pas de problème de synchronisation avec la fréquence d'échantillonnage. 
Played a stereo sequence of 15min with a buffer size of 256 : no problem

(I don't know why I can't go under 256 without having glitches, my new laptop is supposed to be a killer! With Live only I can go until 32 and there's no problem -  but with SpatGRIS, its CPU is becoming crazy - I'm at home, using the binaural mode, maybe that's why)

**Comment by devinroth** [comment]
I decided to bump the next release to BlackHole v0.3.0 due to some added support for a few more sample rates. 
I also leveraged Apple's Accelerate DSP library to improve the performance even more. 

Please give this version a test. If everything seems to work well it should be good to bundle with SpatGRIS. 

[BlackHole128ch.v0.3.0.pkg.zip](https://github.com/GRIS-UdeM/SpatGRIS/files/7666260/BlackHole128ch.v0.3.0.pkg.zip)

**Comment by Normandeau** [comment]
BlackHole V0.3.0
Est-ce qu'on peut tester svp.

**Comment by MelanieFrisoli** [comment]
BlackHole V0.3.0
SpatGRIS V311
Ça fonctionne très bien en mode binaural tant que je ne descends pas la buffer size en dessous de 128.
Avec une buffer size inférieure, SpatGRIS glitch quand il est en arrière-plan.
Dès que le focus revient sur lui, ça ne glitch plus.

**Comment by Normandeau** [comment]
Les tests ici sont au sujet de l'horloge (clock). Pas du buffer size #326 ni du gain #325.

**Comment by Normandeau** [comment]
MacIntel, MacOS 11.6.2
DP11, Séquence de 104 canaux, automations partout, 16'
Aucun problème d'horloge.

**Comment by NicolaGiannini** [comment]
MacIntel, MacOS 10.4.6
Logic 10.5.1
Séquence de 92 sources, automations partout, 11'
Aucun problème d'horloge.
Testé en mode Binaural.

Je ne sais pas si cela peut aider, mais j'ajoute une chose en ce qui concerne la relation entre buffer size et l'erreur de synchronisation entre Audio et Midi parfois affiché par Logic. 

Si nous diminuons beaucoup le buffer size dans Logic et SpatGRIS, Logic peut signaler ce type d'erreur. Notamment dans l'exemple ci-dessus "Séquence de 92 sources, automations partout, 11'", avec un buffer size de 32 j'obtiens cette erreur. 

![Schermata 2021-12-20 alle 15 52 54](https://user-images.githubusercontent.com/35705913/146833448-986cb709-5302-43bb-be71-9e033f78c84e.jpg)


Mais si je remonte le buffer size à 64 (dans Logic et SpatGRIS), dans mon cas l'erreur de synchronisation entre Audio et Midi disparait. 

Le support Apple indique plusieurs raisons possibles pour ce type d'erreurs https://support.apple.com/en-ca/HT204466 dont le buffer size. 

Dans mon cas, je peux obtenir le même comportement, en utilisant des buffer size très basses, même sans utiliser SpatGRIS et Blackhole, mais simplement en utilisant Logic et la carte de son interne de l'ordi.

**Comment by Normandeau** [comment]
Oui Logic affiche un message général sans distinction de la véritable source du probléme pour dire que le CPU est surchargé. Je pense qu'il faut tout simplement oublier l'idée qu'on peut faire du multicanal intense avec un petit buffer size... Donc ce problème semble actuellement réglé... dans la plupart des cas!

**Comment by devinroth** [comment]
I get this error all the time when I’m trying to test and push the limits of BlackHole. Basically BlackHole can’t work fast enough and runs behind. I could potentially change BlackHole to throw an error and skip an audio buffer if it can’t keep up. In this situation isn’t really that Logic is unable to keep up.

Devin

**Comment by Normandeau** [comment]
I just made a test with Logic and DP both with 128 channels at a buffer size of 64 directly on the sound card: no problem. With the same sequence of 128 channels, they just don't play through BlacklHole and SpatGRIS3. The question now is: isn't that normal with such small buffer size? What would be the consequence if BlackHole «skip an audio buffer size»?

**Comment by devinroth** [comment]
Completely normal.

Benefit of skipping a buffer is logic wouldn’t stop and send an error. Downside is you will get audio glitches.

No way to make it better if the CPU can’t keep up.

Devin

**Comment by Normandeau** [comment]
V313 et BlackHole 0.3.0
Le problème d'horloge semble réglé... en général!
