### ISSUE TITLE
Reset Meter Cliping ne fonctionne pas en Stereo Reduction (Binaural ou Stereo)

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#324]
SpatGRIS v3111

Reset Meter Cliping ne fonctionne pas, ni depuis le menu de SpatGRIS  ni à partir du raccourci Opt + M.
C'est le cas en mode Binaural en tout cas.
Je n'ai pas réussi à comparer avec le mode Stéréo car j'avais beau "crinquer" le signal, rien n'allait clipper, comme si il y avait un limiter sur les sortie : 
![Screen Shot 2021-12-01 at 5 24 45 PM](https://user-images.githubusercontent.com/74631914/144323949-00ab097a-a868-4ce0-9b6c-b6745d294f32.png)
s

**Comment by Normandeau** [comment]
V3111
Je confirme que la fonction Reset Meter Cliping ne fonctionne plus en Stereo Reduction, ni en Binaural, ni en Stereo pour les Speakers. Pas contre elle fonctionne toujours bien sur les Sources. Et tout fonctionne normalement en mode Dome ou Cube.
V303
Même comportement. Donc il est fort probable que cela ne fonctionne plus depuis la version 3.
V219
Ça fonctionne bien.

**Comment by NicolaGiannini** [comment]
V3111
Je confirme tout ce qui a été dit par Mélanie et Robert. 
Dans mon cas il semble possible de faire un Reset Meter Clipping manuel, soit en touchant avec la souris le canal devenu rouge. 

Je ne sais pas si cela peut aider, mais je pense que ce comportement a été introduit lors de la transition entre la version 2.1.14 (fonctionnement correct) et la 2.1.15 (Reset Meter Clipping ne fonctionne pas en Stereo Reduction).
Si on compare les 2 versions en ce qui concerne la fonction Stereo Reduction, on peut voir que dans 2.1.14 tous les speakers restent affichés si on active la réduction stéréo, tandis qu’à partir de 2.1.15 seulement les canaux L et R sont affichés. 
![Schermata 2021-12-08 alle 11 54 40](https://user-images.githubusercontent.com/35705913/145250503-1df32cce-cdb2-4953-bfba-5dadd1f0c28b.jpg)


(Dans l'image on voit à gauche la version 2.1.14 et à droite la version 2.1.15).

**Comment by Normandeau** [comment]
Une précision ici: le document de Nicolas affiche le mode Binaural et non pas Stereo. C'est effectivement à partir de la version 2.1.15 que seulement deux canaux L et R, assignable à n'importe quelle sortie de la carte son, que le mode Binaural s'est affiché à deux sorties seulement:
«In stereo reduction mode, speaker vumeters are now replaced with L & R channels and sound can be routed to any output patch made available by the physical audio interface»
Pour aussi loin que j'ai pu remonter sur ma machine, le mode Stereo a toujours affiché deux canaux seulement.
Cela étant dit c'est bien à partir de 2.1.15 que le raccourci de Reset Meter Clipping ne fonctionne plus (Opt-M) en mode Stereo reduction (Binaural et Stereo).

**Comment by Normandeau** [comment]
V312
Toujours pas réglé. 
Pour être bien clair ce n'est pas la fonction qui n'existe plus, mais simplement le raccourci clavier (Opt-M) et le menu lui-même (View -> Reset Meter Clipping) qui ne fonctionnent plus en mode Stereo reduction (Stereo ou Binaural). Comme le dit Nicola, il est toujours possible de faire disparaître les clips en touchant le canal devenu rouge avec la souris.

**Comment by Normandeau** [comment]
V313
Réglé
