### ISSUE TITLE
Buffer size en dessous de 128 problématique

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#326]
Mélanie:
BlackHole V0.3.0
SpatGRIS V311
Live11
Ça fonctionne très bien en mode binaural tant que je ne descends pas la buffer size en dessous de 128.
Avec une buffer size inférieure, SpatGRIS glitch quand il est en arrière-plan.
Dès que le focus revient sur lui, ça ne glitch plus.

**Comment by Normandeau** [comment]
MacIntel 8 cœurs, MacOS 11.6.2

DP11, deux types de séquences:
- Simple, un fichier stéréo:
BF32 et 64: impossible de jouer, DP me dit que je surcharge le processeur. Aucun audio ne se rend à SpatGRIS3.
BF128 et +: ça joue
- Complexes, Cube92 ou Dome104, les deux avec automations:
BF64:  impossible de jouer, DP me dit que je surcharge le processeur. Aucun audio ne se rend à SpatGRIS3.
BF128: glitches
BF256 et +: ça joue.

Logic10, deux types de séquences:
- Simple, un fichier stéréo:
BF32 et 64: impossible de jouer, Logic me dit que je surcharge le processeur. Aucun audio ne se rend à SpatGRIS3.
BF128 et +: ça joue
- Complexes, Dome128, sans automations:
BF64: impossible de jouer, Logic me dit que je surcharge le processeur. Aucun audio ne se rend à SpatGRIS3.
BF128: ça joue

Le fait de mettre SpatGRIS3 en avant-plan ou en arrière-plan ne change rien à ces résultats. Cet aspect semble relié exclusivement à Live.

**Comment by NicolaGiannini** [comment]
MacIntel 4 cores, 16 Gb RAM
Cartes audio : différentes RME utilisées en mode dispositif agrégé avec Blackhole64ch 0.2.10
MacOS 10.14.6
SpatGRIS 3.0.2

Live 10.1.42

Projet de 15 minutes avec 4 pistes de live bien chargées. Autour de 18 plugiciels par piste, dont ControlGRIS. Les 4 pistes sont des entrées microphoniques, avec du son en entrée en direct. Beaucoup d'automations.

Je suis conscient que cette configuration tient compte d'une ancienne version de SpatGRIS, mais je rapporte ces réflexions au cas où elles pourraient être utiles pour approfondir la relation entre SpatGRIS et Ableton Live.

J’utilisais la version de BlackHole 0.2.10 à 64ch en mode dispositif agrégé pour essayer de ne pas avoir des glitches dans le cadre de l’utilisation des entrées microphoniques dans Live. Avant de la création du dispositif agrégé j'avais de problème de glitch après un peu de temps d'utilisation (environ entre 10 minutes et 2 heures).

Dans mon cas, l'unique buffer size qui m'a permis de ne pas avoir des glitch a été 1024. Le même buffer size devait être utilisé dans SpatGRIS et dans Live. Avec des valeurs inférieures, j'ai toujours obtenu des glitch. 

J'ajoute deux choses.

1) Même projet, mais avec un buffer size de 128, le CPU load meter de Live affiche max 18%. Cela dit, les glitch disparaissent avec un buffer size de 1024.

2) En faisant le test de CPU usage Simulator dans les préférences de Live, avec une simulation d'utilisation à 80% de la CPU, 128 semblerait être la bonne valeur pour le buffer size, bien qu'en réalité les glitch disparaissent à 1024.

Je testerai bientôt le même projet à différentes buffer size avec les nouvelles versions de BlackHole et SpatGRIS.

**Comment by devinroth** [comment]
I’m fairly confident that it’s an issue with Live.

Does a similar setup with Logic Pro X cause glitches?

Devin Roth

**Comment by NicolaGiannini** [comment]
Hi Devin,
I started using Ableton Live on May 2021. Before I was using Logic Pro, and since we started using Blackhole with SpatGRIS I’ve never had glitches problems with Logic Pro. But I’ve never used Logic Pro with live inputs, SpatGRIS and Blackhole. I’ll test also this configuration.

**Comment by devinroth** [comment]
The reason I bring this up is a number of people noticed the same issue with Live + BlackHole but no issues with other daws.

Here’s the thread.

https://github.com/ExistentialAudio/BlackHole/issues/448

Devin Roth

**Comment by NicolaGiannini** [comment]
Hi Devin,
I read that thread and it seems similar to my situation. 
“audio drops and cracles each 3 - 5 minutes that disappear after about 5 seconds and come back again”.
In my case using 1024 as buffer size solved the issue. 
I know that another composer, Ana Dall’Ara-Majek, used Reaper + SpatGRIS + Blackhole + Live inputs, without having glitches problems. I mean "audio drops and cracles each 3 - 5 minutes that disappear after about 5 seconds and come back again".

**Comment by SamuelBeland** [comment]
What worries me here is that putting SpatGris' window in the background has any effect whatsoever.

Even if there's an issue with Live + BlackHole, we should not be able to trigger that bug by toggling the OS' focus on and off SpatGris.

We had a similar issue in Septembre, detailed in a email from Robert to me :

> Samuel,
> 
> On a eu un cas très particulier de problème avec SpatGRIS 3 la semaine dernière pendant les concerts Ultrasons.
> 
> Mélanie présentait une pièce en direct faite avec Ableton Live 11. [...]
> Essentiellement le son distorsionnait beaucoup, des glitchs numériques.
> 
> La solution?
> 
> Mettre la fenêtre de SpatGRIS au premier plan.
> Si celle-ci était en arrière-plan c'est-à-dire derrière Live, le son distorsionnait!
> [...]

**Comment by Normandeau** [comment]
On a deux problèmes spécifiques à Live: la taille du buffer size et le fait de mettre SpatGRIS3 en arrière plan. La première n'est pas surprenante, Live comme son nom l'indique privilégie les actions à courtes vues si je puis dire, ce qui ne correspond pas à notre cahier des charges. Ensuite l'histoire du second plan ne nous a pas été confirmé avec les nouveaux M1. Et cela ne se produit pas avec les autres DAWs. Donc pour l'instant je ne mettrais pas un homme là-dessus...

**Comment by devinroth** [comment]
I’ve experienced that bug a few times over the years. In every situation it was a result of blocking calls on the real-time audio thread.

Devin Roth

**Comment by MelanieFrisoli** [comment]
C'est confirmé avec le M1.
Comme je le disais dans un précédent post : 
"Avec une buffer size inférieure, SpatGRIS glitch quand il est en arrière-plan.
Dès que le focus revient sur lui, ça ne glitch plus."

**Comment by SamuelBeland** [comment]
> [...] it was a result of blocking calls on the real-time audio thread

Yeah, I'm also worried that something in the audio processing is leaking in another thread, but I really can't pin it down right now.

**Comment by belangeo** [comment]
UI updates on the active app seems to be prioritized by the system!

https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/PrioritizeWorkAtTheTaskLevel.html

Categorization of the app may help increase its priority...

Olivier

**Comment by SamuelBeland** [comment]
> UI updates on the active app seems to be prioritized by the system!

Yes, but somehow that _de-prioritization_ is leaking into the realtime audio thread, which should not happen at all.

I am expecting the UI to run much slower when the app is in background (and probably also the OSC responsiveness to decrease), but audio should not get impacted by this.

The only explanation I have right now, as Devin suggested, is that the audio callback makes a blocking call at some point (waiting for a lock, memory allocation, disk I/O, etc.). This would leak the _de-prioritization_ to the audio thread.

I just don't see where that could be happening!

**Comment by belangeo** [comment]
On Tue, Dec 21, 2021 at 7:28 PM Samuel Béland ***@***.***>
wrote:

> UI updates on the active app seems to be prioritized by the system!
>
> Yes, but somehow that *de-prioritization* in leaking into the realtime
> audio thread, which should not happen at all.
>
> I am expecting the UI to run much slower when the app is in background
> (and probably also the OSC responsiveness to decrease), but audio should
> not get impacted by this.
>
I agree! My guess was that if the active app (ie the DAW) takes too much
CPU resources, even the real time threads would be affected...

> The only explanation I have right now, as Devin suggested, is that the
> audio callback makes a blocking call at some point (waiting for a lock,
> memory allocation, disk I/O, etc.). This would leak the
> *de-prioritization* to the audio thread.
>
Yeah, for sure, the audio callback should never do that kind of thing!

> I just don't see where that could be happening!
>
 Hard to define a test case to debug this... :(

**Comment by devinroth** [comment]
I haven’t dug deep into the SpatGRIS source code but a mistake I often see is people using Objective-C in the real-time audio thread.

Devin Roth

**Comment by Normandeau** [comment]
Une issue sans issue apparemment ici.
