### ISSUE TITLE
Speaker Setup Edition

### ISSUE THREAD

**Issue by delmenhorst** [GRIS-UdeM/SpatGRIS#329]
Evelation range just from 0 - 90 degrees. Its not possible to go under 0 or above 90 like in some template. ( DOME44 (2-6-8-12-8-6-2) Sphere for example)

**Comment by Normandeau** [comment]
This issue was already created. No need to add a new one about the same topic. Issue #313 
Unfortunately, we are in process of training a new developer. This is issue has been assigned to a low priority.
