### ISSUE TITLE
À investiguer : SpatGRIS plante parfois lorsqu'on joue avec les Solo et Mute de sortie.

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#330]
Hier, je testais l'assignation des sorties vers les haut-parleurs avec le générateur de bruit rose, en faisant un SOLO sur chaque haut-parleur. Ce faisant, SpatGRIS a planté à quelques reprises - sur MacBook M1.

**Comment by NicolaGiannini** [comment]
V313, MacOs 10.14.6, Intel Core i7 (2,9 GHz, 4 core)

Je confirme. Aussi dans mon cas SpatGRIS plante  lorsqu'on joue avec les Solo et Mute en utilisant la fonction _Reference Pink Noise_.
Pour le moment je l'ai testé seulement en utilisant la carte de son interne du Mac. Je testerai davantage branché sur un dôme.

**Comment by MelanieFrisoli** [comment]
V313, MacOs 12.1, M1 Max, 10 cores.

Avec carte son interne et pink noise : 
Ça a buggé aussi mais seulement en mode Hybride en jouant avec les solos et les mutes.
J'ai pu modifier les solos et mute pendant un long moment avec les modes Dôme et Cube sans que cela n'arrive. En passant au mode Hybride, au bout de quelques clics, SpatGRIS a planté 

Avec interface externe et pink noise : 
J'ai cliqué une bonne centaine de fois sur les différents modes et SpatGRIS n'a pas planté.

**Comment by NicolaGiannini** [comment]
Dans mon cas, SpatGRIS plante dans les trois modes (CUBE, DOME ET HYBRIDE), mais je l'ai toujours testé seulement avec la carte interne.

**Comment by MelanieFrisoli** [comment]
V313 -ERRATUM - SpatGRIS plante effectivement dans les trois modes. 
(depuis l'Hexa, interface UFX+)

**Comment by NicolaGiannini** [comment]
V314 MacOs 10.14.6, Intel Core i7 (2,9 GHz, 4 core)
Dans mon cas, ça semble réglé.

**Comment by Normandeau** [comment]
Cela semble effectivement réglé.
Bravo Gaël. Ton premier release et un bogue de réglé!

**Comment by MelanieFrisoli** [comment]
V314, MacOS 12.1, M1, etc.
Réglé de mon côté également !

**Comment by Normandeau** [comment]
V314
Réglé
