### ISSUE TITLE
Mini-erreur de triangulation - Template Dome32(12-10-8-2)Sub2 UdeM UFX+

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#331]
V313
Dans le template Dome32(12-10-8-2)Sub2 UdeM UFX+, il y a une triangulation en trop.
Je ne sais pas dans quelle mesure cela affecte le rendu, mais c'est un template qu'on utilise beaucoup, à la fac en tout cas.
C'est le seul template (en dôme) dans lequel j'ai constaté cela (entre les speakers 60 et 36)

<img width="592" alt="Screen Shot 2022-02-03 at 2 21 42 PM" src="https://user-images.githubusercontent.com/74631914/152414034-35999170-38bb-4688-af12-78761548918d.png">

**Comment by Normandeau** [comment]
Peux-tu remplacer cette image avec une image avec les nos de hp.  Parce que là on n'est pas capable de valider.
