### ISSUE TITLE
Le Highpass du Speaker Setup semble excessivement gourmand en CPU

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#333]
V1313
Il semble que la fonction Highpass du Speaker Setup n'est pas utilisable, au moins à 96kHz. Testé avec un Cube de 62.2 hp, les trois quarts environ des Highpass étaient ajustés (par erreur) à 60 ce qui menait à une surcharge du CPU.
À tester avec plusieurs valeurs et plusieurs configurations de hp.
Quelle est la limite?
Tester les gains également dans la même fenêtre.

**Comment by belangeo** [comment]
Ma main au feu que c'est un problème de dénormalisation. Tous les systèmes récursifs en floating-point y sont sujet. Quand le signal cesse d'entrer dans le filtre, celui-ci consume les derniers échantillons et les réinjecte dans le filtre avec perte de gain, jusqu'au moment où les valeurs tombent sous le seuil de résolution du système (selon que les échantillons sont calculés en 32 ou 64 bits). À partir de ce moment, le CPU est surchargé très rapidement. La solution est d'ajouter un bruit à faible amplitude en entrée du filtre (trop faible pour avoir un impact sur le signal mais assez fort pour éviter la dénormalisation). Pour référence, voici le bruit de l'objet Denorm de pyo (la valeur à la fin des lignes est le gain du bruit blanc pour 32 et 64 bits):

```
#ifndef USE_DOUBLE
#define DENORM_RAND  ((MYFLT) ((pyorand()/((MYFLT)(PYO_RAND_MAX)*0.5+1) - 1.0) * (MYFLT)(1.0e-24)))
#else
#define DENORM_RAND  ((MYFLT) ((pyorand()/((MYFLT)(PYO_RAND_MAX)*0.5+1) - 1.0) * (MYFLT)(1.0e-60)))
#endif
```
La surcharge n'est pas présente à l'ouverture du projet parce que les filtres n'ont encore rien reçu, donc ils calculent des zéros.

Le problème pourrait se présenter en cours de performance si un canal a un filtre actif et qu'il cesse de recevoir du signal. Après un certain temps, il va se mettre à consommer du CPU en fou...

p.s.: Pas mal certain que les highpass sont utilisables, même pour des gros setups, très peu coûteux comme filtre!

**Comment by MelanieFrisoli** [comment]
V313
Tests des filtres High-Pass à 96KHz - 512 - Projet à 83 sources - en binaural
OS 12.1 / Macbook M1 Max / 64GB RAM / 10 coeurs

- **Avec le template Dome 96.4 :** j'ai modifié la valeurs d'une quarantaine de filtres et le CPU n'a pas bougé (environ 13%). Par contre, SpatGRIS a planté peu après ces modifications. 
![Screen Shot 2022-02-07 at 7 59 14 AM (2)](https://user-images.githubusercontent.com/74631914/152827721-950e44e5-1992-4fb5-9434-56f3a0909d0d.png)

Je l'ai rouvert et ai rechargé le template, ai changé 4 filtres et la roulette s'est mise à tourner, j'ai dû le forcer à quitter.
Je l'ai rouvert à nouveau et ai fait le test avec une fe de 48KHz. J'ai pu modifié quasiment tous les filtres (avec des valeurs aléatoires comprises entre 50 et 100). Aucun problème et le CPU se trouvait autour de 10%. 
J'ai rechangé le fe pour 96et aucun problème, le CPU a juste un peu augmenté (autour de 25%)

- **Avec le template Dome_default_speaker_setup**, tous les filtres à + de 50, à 96KHz, aucun problème (CPU autour de 22%)
- Même test avec **le template Dome16.2 Udem_Hexa**, tous les filtres à plus de 50, aucun problème (CPU autour de 25%)
- Même test avec **le template Dome32.2_UdeM UFX+**, aucun problème (CPU autour de 23%)
- Même test avec **le template Cube54.2 Cube Virginia**, tous les filtres à plus de 50, aucun problème ((CPU autour de 25%)
- Même test avec **le template SATOSPHÈRE**, aucun problème ((CPU autour de 24%)
- Même test avec **le template Dome20.4 UdeM Icosa**, SpatGRIS plante après trois changements de valeurs de filtre. Mêmes étapes que tantôt, j'ai rouvert SpatGRIS, rechargé le template mais je suis passée à 48KHz, et j'ai pu modifier les filtres à ma guise (toujours des valeurs entre 50 et 100). Puis je suis repassée à 96KHz et ça a fonctionné sans problème ((CPU autour de 30%)

**Plusieurs questions :** 
Est-ce qu'il faudrait tester tous les templates présents dans SpatGRIS ? 
Est-ce seulement la "faute" des templates ? 
(Je viens juste de rechanger les valeurs de tous les filtres sur le template UdeM Icosa (2h après les premiers tests plus haut) et SpatGRIS n'a pas planté comme tantôt... Et le CPU n'a pas beaucoup bougé non plus. Les seules choses qui changent c'est que je travaille sur un autre projet et que je ne suis plus en binaural (CPU autour de 11%)).


**Courts TESTS avec le gain :**
- Sur Template Dome96.4 = augmenté le gain (+6) de quarante pistes, aucun plantage, aucune hausse de CPU (toujours à 96KHz)
- Sur Template Dome16.2 Udem Hexa, même test et même résultat.

**Comment by Normandeau** [comment]
Comme l'a souligné Olivier, la solution semble être déjà trouvée. Donc pas besoin de pousser davantage les tests avec le filtre en tout cas. On a déjà eu ce genre de problème dans le passé et la solution semble assez simple à appliquer. Gaël pourra l'intégrer dans le prochain release.

Mais j'ai plusieurs questions au sujet des informations manquantes:
1. Est-ce que tu as fait tourner des séquences à chaque fois? Car comme je le décrivais et comme l'explique Olivier, c'est seulement après qu'une séquence ait joué que le problème se pose.
2. Pourquoi avoir testé en binaural et en Dome? C'est plutôt en mode Cube qu'on veut valider pour le CIRMMT. Je ne sais pas si les filtres sont opérationnels en mode binaural. En fait, j'en doute fort.
3. Icosa est un Dome. Le problème semble se poser surtout sur les Cube, qui sont davantage exigeants que les Dome.
4. À tester: Gain dur les Cube.

**Comment by NicolaGiannini** [comment]
V313
Je confirme que la fonction Highpass du Speaker Setup peut provoquer une surcharge de la CPU. 

Comme l'indique Olivier, le passage du signal audio influe sur ce comportement. Je ne sais pas si ça peut être utile, mais j'ai noté aussi des relations entre ce comportement le MODE et les trajectoires. 

Différentes combinaisons semblent provoquer différents comportements

Mode CUBE, speaker setup B187 version CUBE, tous les filtres Highpass à 60, 1 piste,  à 96kHz.
Si nous n'envoyons pas de signal audio depuis le DAW, la CPU est à 76%
Si nous envoyons du signal audio depuis le DAW, la CPU passe à 31%
Si on bouge l'élévation  à partir de ControlGRIS, la CPU passe à 11%
Voir la vidéo
https://udemontreal-my.sharepoint.com/:v:/g/personal/nicola_giannini_umontreal_ca/EXBJDq95i3tJmhRkJAVSW6sBb31Kr7Y0fs1OFyZ8gyQGxA?e=JAJKOk

Si on bouge Azimuth-Distance  à partir de ControlGRIS, la CPU reste à 33%, comme dans le cas du passage du signal audio, soit bouger Azimuth-Distance ne semble pas influencer la CPU.

https://udemontreal-my.sharepoint.com/:v:/g/personal/nicola_giannini_umontreal_ca/EX0MevGi7bpEn0PfRYr6oAcB__Hx50bDsRyxaD2rs-5Pjg?e=1alNnR

J'ajoute une chose.
Si j'ajoute 2 pistes, lors du passage du signal audio et de la lecture des trajectoires, la charge de CPU augmente (17%) par rapport à l'exemple avec seulement une piste (11%).
Voir la vidéo

https://udemontreal-my.sharepoint.com/:v:/g/personal/nicola_giannini_umontreal_ca/Eal6v4tR5KhIrNDDtAJ1APsB_bIz92UR-GWGkeRHuj8t4Q?e=vckGIG

Dans le mode DOME (toujours à 96kHz), on peut remarquer quelques différences :
Si nous n'envoyons pas de signal audio depuis le DAW, la CPU est à 74% (similaire au mode CUBE)
Si nous envoyons du signal audio depuis le DAW, la CPU passe à 62% (donc moins de différence par rapport au mode CUBE)
Si on bouge l'élévation la CPU passe à 49%
Si on bouge l'azimuth la CPU passe à 30%.

https://udemontreal-my.sharepoint.com/:v:/g/personal/nicola_giannini_umontreal_ca/EZZyXQZvX01AtecmLFOul8sBg7k67ue4eOZyHLkZIcSUHQ?e=loGPTc

Testé également avec le setup  MMR 62.2 hp, j'ai des comportements cohérents à ceux que je viens de décrire. 

Les gains, dans mon cas, ne semblent pas influencer la charge de CPU.

Si je passe à 48 kHz, je obtiens des comportements similaires mais avec des écarts de CPU réduits.

**Comment by MelanieFrisoli** [comment]
_`Est-ce que tu as fait tourner des séquences à chaque fois? Car comme je le décrivais et comme l'explique Olivier, c'est seulement après qu'une séquence ait joué que le problème se pose.`_

Oui, à chaque fois, la même séquence tournait. Mon projet contenait 83 sources. 

   ` Pourquoi avoir testé en binaural et en Dome? C'est plutôt en mode Cube qu'on veut valider pour le CIRMMT. Je ne sais pas si les filtres sont opérationnels en mode binaural. En fait, j'en doute fort.`

J'ai testé en binaural ce matin car j'étais chez moi - donc par réflexe - mais j'ai ensuite testé sur des configurations Cube et Dome. J'ai jugé que ce serait intéressant d'avoir un peu de chaque, au cas où nous aurions besoin d'être en 96KHz ailleurs.


Mis à part ça, on vient de passer du temps avec Nicola pour faire des tests sur nos deux ordinateurs avec le template Cube62.2 MMR et avec le template Cube setup B187, avec tous les filtres à 60. Nos deux CPU sur SpatGRIS se comportent complètement différemment. Pour ma part, je n'ai aucun problème de CPU sur ma machine (la puissance des nouveaux M1 peut-être?), et le CPU chute dès que le son arrête d'être lu.

**Comment by MelanieFrisoli** [comment]
Test GAIN 

V313
96KHz - 512 samples 
(OS 12.1 / Macbook M1 Max / 64GB RAM / 10 coeurs)

Template : Cube62.2 MMR 
Tous les gains sont à +6 / Session d'une quarantaine de piste.
Toujours la même boucle de 30 secondes dans le projet.

Avant le changement de gain, environ 44%, après le changement de gain : 44% aussi 
Donc, j'ai l'impression que sur mon ordinateur, le CPU se comporte normalement. 

En guise de comparaison : 
avec le même speaker setup et tous  les highpass à 60 : 47-48%
avec le même speaker setup, tous les highpass à 60 et tous les gains à + 6 : 47-48% également

**Comment by MelanieFrisoli** [comment]
V314
SpatGRIS à 96kHz / 512 samples
(OS 12.1 / Macbook M1 Max / 64GB RAM / 10 coeurs)

Cela semble être encore le cas. 
En faisant un test simple avec juste SpatGRIS  : 
Quand je charge le speaker setup du MMR (62.2) sans aucun filtre (ni gain) modifié, le CPU oscille entre 2 et 3%.
Quand je charge le même speaker setup où tous les filtres sont modifiés à 60, le CPU oscille entre 12 et 13%.
(J'ai testé aussi ce même speaker setup avec filtres + gains modifiés, le résultat est identique à celui avec juste les filtres modifiés)

En pièces jointes, les trois speaker setup dont il est question dans ce test : 

[Test-CPU-Filtres.zip](https://github.com/GRIS-UdeM/SpatGRIS/files/8069289/Test-CPU-Filtres.zip)

**Comment by Normandeau** [comment]
Ce problème n'a pas encore été abordé avec 314. Cela devrait être corrigé dans la prochaine version.

**Comment by belangeo** [comment]
Petit commentaire concernant le fix implémenté dans 84be4c5c .

DENORM_GAIN est une constante qui est directement ajouté au signal entrant dans le filtre, ce qui ajoute du DC au signal et risque de faire dévier son centre de gravité au-dessus du 0. Le highpass Linkwitz-Riley est un filtre récursif d'ordre 4 qui peut devenir très sensible si on introduit du DC. Même une valeur aussi petite, peut devenir considérable par accumulation.

Il est donc très important d'utiliser un signal "stable" (c'est à dire oscillant autour de 0), comme un bruit blanc (d'amplitude DENORM_GAIN), pour la  dénormalisation. Quelque chose comme:

```c++
auto const sample{ static_cast<double>(data[sampleIndex]) + whiteNoise * DENORM_GAIN};
```

**Comment by Normandeau** [comment]
V317, Mode CUBE
Le problème général décrit à l'apparition de ce problème semble être résolu... très partiellement. J'ai rouvert le même projet avec 116 sources et 64 sorties (CubeMMR, maintenant dans les Templates). J'ai mis toutes sortes de valeurs aléatoires dans les 62 filtres du Speaker Setup. Deux VU-mètres se sont allumés au maximum dans le rouge, mais pas d'un coup. Il faut attendre une ou plusieurs minutes avant de voir le phénomène apparaître. Même chose avant de le voir disparaître, ce qui prend généralement plus de temps. 
- Leurs valeurs étaient réglées à 1. 
- Pas besoin d'envoyer de l'audio pour que le phénomène se produise. Dès l’ouverture de SpatGRIS3, le feedback apparaît.

J'ai cherché le seuil. Le seuil se situe entre 0.1 et 1.0.
- Ni la valeur 0.0 ni la valeur 0.8 ne semble provoquer le phénomène!!!
- Autre phénomène: tous les VU mêtres accotés dans le rouge pendant un certain temps redescendent ensuite d'eux-mêmes à 0 sur une période de 5 à 10 minutes environ.  Sur une période d'attente de 15 minutes environ, les niveaux ne sont pas revenus. 

![Seuil entre 0 1 et 1 0](https://user-images.githubusercontent.com/8959779/157319496-76d23c73-7abb-4b78-a4aa-b0519dc5f791.jpg)

- Le feedback est une impulsion extrêmement grave. Regardez moi ce spectre, analysé par ma carte de son (ça pulse en fait, fermez vos hp... danger à l'horizon):

![Feedback](https://user-images.githubusercontent.com/8959779/157317678-d8f4d6d0-7509-4e3a-bbe4-25e601d195f6.jpg)

**Comment by Normandeau** [comment]
Contrairement à ce qui est écrit ici:
«-Fix: Speaker Highpass filters use 100% cpu in cube mode»
Il se passe exactement la même chose en mode DOME.

**Comment by Normandeau** [comment]
V317
Réglé
