### ISSUE TITLE
Une version compilée de SpatGRIS3 pour les nouvelles puces M1

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#334]
Ce serait super d'avoir une version compilée pour les nouvelles puces M1 à un moment donné. Pour l'instant rien n'indique dans SpatGRIS3 sous quel mode il fonctionne, contrairement à certains applications déjà fonctionnelle sous M1. En mode natif ou en mode Rosetta. Probablement Rosetta. Apple a annoncé deux ans de compatibilité Rosetta. Et les M1 date d'un an et demi déjà...

**Comment by Normandeau** [comment]
V317
À toi de jouer Mélanie! Mon Mac me dit qu'on a maintenant une version universelle, autant pour SpatGRIS3 que pour ControlGRIS.

**Comment by MelanieFrisoli** [comment]
V317 téléchargée à l'instant !

**Comment by MelanieFrisoli** [comment]
V317 & ControlGRIS 132
Une journée de travail dessus (sans Rosetta) et aucun bug pour le moment. 
Bonne nouvelle !

**Comment by Normandeau** [comment]
V318 et ControlGRIS 132
Donc c'est confirmé, ça fonctionne toujours avec M1?

**Comment by MelanieFrisoli** [comment]
V318 et ControlGRIS 132
Pas encore testé, j'ai dû reprendre Rosetta à cause d'autres plugins. 
Je teste ça cette semaine

**Comment by MelanieFrisoli** [comment]
V318 et ControleGRIS 132
Après trois jours de travail sans Rosetta, je confirme la stabilité de nos deux logiciels sur les puces M1 (en tout cas, les M1 Max!) 
Bravo !

**Comment by louisodesmarais** [comment]
Bonjour! 

Quel timing...

Simplement vous dire que j'expérimente moi aussi des bugs avec M1 (pas M1 MAX) et la version 3.1.7. 
Il y a des glitchs ponctuels et, d'un coup, je perds le volume. SpatGris aussi fige du même du coup. Je dois redémarrer ou débrancher la carte de son pour retrouver du son.

**Comment by Normandeau** [comment]
Louis-Olivier,
Il faut impérativement utiliser la version 3.1.8 de SpatGRIS3, qui vient avec la version 1.3.2 de ControlGRIS, les seules qui sont optimisées pour M1. Disponibles sur ce site. On devrait sortir la version 3.1.9 très bientôt, qui devrait une version officielle.

**Comment by louisodesmarais** [comment]
Ahhh voilà! Je me mets à jour et vous fait signe si jamais j'expérimente le même problème.

**Comment by Normandeau** [comment]
V319 et ControlGRIS 132
Cela devrait normalement être confirmé puisque la version précédente fonctionnait bien.
