### ISSUE TITLE
SpatGRIS refuse de loader d'anciens speaker setups sous M1 et Monterey

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#336]
V314 
(OS 12.1 / Macbook M1 Max / 64GB RAM / 10 coeurs)

SpatGRIS refuse apparemment de charger des speaker setup fait avec la V313. 
J'ai fait une dizaine d'essais, sur plusieurs templates différents (dont le "Cube36 SousMix" et "Cube62Subs2 MMR"), la petite roulette se met à tourner et l'application ne répond plus. 

Update 1 *** en éteignant et rallumant l'ordinateur, les speaker setups se chargent sans problème.

Update 2 *** pas si simple que ça en fait. Après être repassée sur un template natif et travaillé quinze minutes, je veux reloader l'ancien setup et SpatGRIS ne répond à nouveau plus. Avez-vous rencontré ce problème aussi ?
(j'ai le même problème avec la V313 en ce moment. Impossible de charger des setups fait avec cette version)

**Comment by MelanieFrisoli** [comment]
Update *** en éteignant et rallumant l'ordinateur, les speaker setups se chargent sans problème.

**Comment by MelanieFrisoli** [comment]
Update 2 *** pas si simple que ça en fait. Après être repassée sur un template, et travaillé quinze minutes, je veux reloader l'ancien setup et SpatGRIS ne répond plus à nouveau. Avez-vous rencontré ce problème aussi ?

**Comment by Normandeau** [comment]
Aucun problème de mon côté. J'ouvre sans problème des dômes, des cubes et des hybrides, dont les deux mentionnés (au moins une vingtaine). J'ouvre même sans problème les vieilles versions qui datent d'avant la version 3, des speaker setups qui datent de 2017 ou 2019.
Étrange.

**Comment by NicolaGiannini** [comment]
De mon côté, pas de problème jusqu’à maintenant. J'ai essayé d'ouvrir des templates et des Speaker Setup créés avec des anciennes versions de SpatGRIS. J'ai essayé également avec "Cube36 SousMix" et "Cube62Subs2 MMR".

**Comment by Normandeau** [comment]
Sous M1? Sous Monterey? Les deux?

**Comment by MelanieFrisoli** [comment]
M1 & MacOS Monterey 12.1

**Comment by Normandeau** [comment]
As-tu essayé de jeter toutes les préférences de SpatGRIS3, redémarrer l'ordi, rouvrir SpatGRIS3 et rouvrir les speaker setup en question?

**Comment by MelanieFrisoli** [comment]
Merci Robert, j'ai effacé les préférences de SpatGRIS3 et le problème ne s'est pas représenté.

**Comment by Normandeau** [comment]
Apparemment réglé.
