### ISSUE TITLE
Open Documentation (le manuel) ne s'ouvre pas

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#338]
V316
Le manuel ne s'ouvre pas dans la nouvelle version. Même après avoir jeté les préférences. À corriger car comme on le sait le manuel est si merveilleux!

**Comment by MelanieFrisoli** [comment]
V316
Je confirme

**Comment by Normandeau** [comment]
V317
Ici ça flye! Quand il y a un bogue, l'équipe d'urgence met en place et c'est réglé le lendemain!
