### ISSUE TITLE
Le highpass filter: la valeur 0 (filtre inactif)est difficile à ajuster; un changement de valeur génère une impulsion grave à 0 dB

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#339]
Mode CUBE
Le problème général décrit à l'apparition de ce problème semble être résolu... très partiellement. J'ai rouvert le même projet avec 116 sources et 64 sorties (CubeMMR, maintenant dans les Templates). J'ai mis toutes sortes de valeurs aléatoires dans les 62 filtres du Speaker Setup. Deux VU-mètres se sont allumés au maximum dans le rouge, mais pas d'un coup. Il faut attendre une ou plusieurs minutes avant de voir le phénomène apparaître. Même chose avant de le voir disparaître, ce qui prend généralement plus de temps.
- Leurs valeurs étaient réglées à 1.
- Pas besoin d'envoyer de l'audio pour que le phénomène se produise. Dès l’ouverture de SpatGRIS3, le feedback apparaît.

J'ai cherché le seuil. Le seuil se situe entre 0.1 et 1.0.
- Ni la valeur 0.0 (heureusement, il est à off...)  ni la valeur 0.8 ne semble provoquer le phénomène!!!
- Autre phénomène: tous les VU mêtres accotés dans le rouge pendant un certain temps redescendent ensuite d'eux-mêmes à 0 sur une période de 5 à 10 minutes environ. Sur une période d'attente de 15 minutes environ, les niveaux ne sont pas revenus.

![Seuil entre 0 1 et 1 0](https://user-images.githubusercontent.com/8959779/157695575-6f12de7c-3400-4c81-bb32-49e0e957cce4.jpg)

Le feedback est une impulsion extrêmement grave. Regardez moi ce spectre, analysé par ma carte de son (ça pulse en fait, fermez vos hp... danger à l'horizon):

![Feedback Impulsions](https://user-images.githubusercontent.com/8959779/157695629-e89fc78f-1bdc-4ab1-a001-dbbe36298f29.jpg)

Comme ce sont des valeurs inhabituelles en audio (qui a besoin d'un filtre à 5 Hz?, la solution serait de limiter le fréquence la plus basse.

**Comment by NicolaGiannini** [comment]
V317
Je confirme. Dans mon cas je peux reproduire le comportement aussi en mode DOME et HYBRID. Dans mon cas apparemment le bruit est déclenché par les valeurs suivantes : 
de 0,1 à 0,5 (inclus)
de 0,7 à 0,9 (inclus)
À 0,6 et à partir de 1, le bruit ne se génère pas.

**Comment by belangeo** [comment]
Pratiquement la seule utilisation d'un highpass avec une fréquence de coupure de 5hz et moins est pour éliminer le DC (ce qui n'est pas rien quand même!). Ce filtre est généralement très simple et stable (ordre 1). Assurément, le Linkwitz-Riley n'est pas conçu pour ça... Dans le contexte, il n'y a pas de raison, à mon avis, de permettre des fréquences de coupure en dessous de 20hz...

p.s.: La valeur 0.8, c'est probablement juste un coup de chance, qui a généré des coefficients de filtre qui n'explose pas!

**Comment by MelanieFrisoli** [comment]
V318
Je confirme que la valeur des filtres high pass commencent bien à 20Hz avec la nouvelle version. Cependant, quand j'ouvre un "vieux" templates de speaker setup (exemple : "Dome31(12-10-8-2)Sub2 UdeM UFX+"), les high pass apparaissent encore sur 0 et c'est seulement quand j'essaie de les modifier qu'ils viennent "s'aimanter" à 20Hz et ne descendent plus en dessous.

**Comment by MelanieFrisoli** [comment]
V318
Voici, en vidéo, le comportement des filtres :  

https://user-images.githubusercontent.com/74631914/160912429-0fa95a81-d462-4d32-9eb2-ffcab8cd188a.mp4

**Comment by MelanieFrisoli** [comment]
V318
Dans le manuel, il est écrit page 30 : 
"You can adjust the output Gain (dB) and put a
Highpass filter (0 is off, value in Hz, minimum
20 Hz) on each speaker to calibrate the setup"

Sauf qu'on ne peut plus le mettre sur 0 une fois qu'on l'a bougé. Il refuse de descendre en-dessous de 20Hz.
Peut-être qu'il faudrait changer les captures d'écran et p.30 et 31 et ajuster l'explication dans le manuel ?

**Comment by Normandeau** [comment]
En fait, si tu es un peu patiente, tu peux remettre le 0. Mais, ça gigue pas mal avant d'y arriver:

https://user-images.githubusercontent.com/8959779/160919580-b0639006-9813-4dd8-8f59-4f412768aa0c.mov

**Comment by MelanieFrisoli** [comment]
V318
Je ne sais pas si c'est "legit" de faire ça mais j'ai tenté de modifier les filtres (template en mode Cube "MMR") pendant la lecture de ma pièce pour des valeurs aléatoires. Au bout du 41ème haut-parleur modifié, SpatGRIS a planté. J'ai refait l'expérience et SpatGRIS a planté au bout du 17ème haut-parleur. 
Sans que ma pièce joue, j'ai pu modifier les highpass filters à loisir sans problème.
(Testé sur V317 aussi - même chose et plante encore plus vite même! => ce qui me confirme qu'on ne devrait pas faire ça)

Aussi, j'ai noté que si je change les filtres pendant la lecture, ça fait de drôles de bruits (sauf quand je copie/colle ou écris une valeur à la main-en tout cas moins). Peut-être qu'il faudrait l'inscrire dans notre manuel - de ne pas modifier les filtres pendant la lecture ?. Pour ma part, c'était un réflexe de vouloir entendre en direct l'effet du highpass sur les haut-parleurs. Pas une bonne idée donc 
(Testé sur V317, ça fait de drôle de bruits également)
 

https://user-images.githubusercontent.com/74631914/160920366-1d0b4bbb-3de0-456c-bca1-86d24e2ae261.mp4

**Comment by MelanieFrisoli** [comment]
V318
Tout cela pour en arriver à la conclusion qu'en mode CUBE ou hybride, avec des valeurs de filtre aléatoires ou avec chaque filtre dans le tapis, aucun problème sur les Vu-mètres, aucun n'est dans le rouge (et après quelques minutes de lecture)

**Comment by Normandeau** [comment]
Comme tu dis, ce n'est pas «legit»! L'idée ici est d'offrir la possibilité d'atténuer l'intensité et de filtrer le son lorsqu'on évalue le dispositif de haut-parleur à l'aide du générateur de bruit rose fourni, afin d'effectuer ces opérations avec une source stable et connue. Donc le 0 est possible, mais vraiment pas évident à placer. Il faudrait au moins qu'on puisse entrer cette valeur directement, à partir du clavier, ce qui n'est pas possible actuellement. Quand on tape 0, il met la valeur 20 à la place. Donc le minimum. Ce qui signifie que le filtre est actif (contrairement au 0, où il est inactif). Si quelqu'un par mégarde place tous ses filtres à 20, n'y a-t-il pas risque de surchauffe quelconque? En tout cas la fonction est probablement inutile la plupart du temps. Alors le «easy» 0 serait bienvenu.

**Comment by NicolaGiannini** [comment]
Pour avoir le zéro easy, je me demande si alors on pourrait mettre un bouton pour activer et désactiver le filtre. Avec le bouton à OFF le filtre serait à zéro.

De mon côté, si je change la valeur du filtre pendant que j’utilise la fonction “Reference Pink Noise”, dès que je touche le filtre avec la souris, le vu-mètre de l’HP en question devient rouge. Je ne sais pas si cela provoque réellement une distorsion sur le haut-parleur.

**Comment by Normandeau** [comment]
J'apporte une précision ici: le VU mètre de sortie peake dans le rouge TEMPORAIREMENT. Quant à savoir ce qui se passe dans les hp, pourquoi ne pas avoir écouté? Cela génère une impulsion très grave à 0dB numérique!!! Bogue majeur. On ne peut pas sortir la version 3.1.8.

**Comment by MelanieFrisoli** [comment]
V318
Testé en studio avec le bruit rose. 
Je confirme que ça fait de gros bruits anormaux (dont certains à très graves fréquences - possiblement dangereux pour les speakers) et que ça peake solide dans les VU-mètres - pareil que lorsque c'était ma pièce qui jouait en fait -

**Comment by Normandeau** [comment]
Ajout d'informations. Le problème apparaît historiquement:
- Version officielle 3.0.2: pas de problème avec cette version
- Version officielle actuelle 3.1.3: même problème qu'avec la version 3.1.8.

Donc c'est apparu entre les versions 3.0.2 et 3.1.3. Il n'y a eu que 4 versions entre les deux (3.0.3, 3.1.0, 3.1.1 et 3.1.2) et rien n'indique un changement ou un ajout dans la fenêtre Speaker Setup Edition dans ces versions. Par ailleurs, les modifications au filtre HighPass ont commencé avec la version 3.1.5.

**Comment by NicolaGiannini** [comment]
J’ai testé la version 3.0.2, et comme Robert le dit on n’a pas ce problème avec cette version. Mais dans la version 3.0.2, on ne pouvait pas entendre le changement de la valeur du filtre en temps réel. Dans 3.0.2 pour entendre le résultat du changement il faut appuyer sur “Compute”. Est-ce que la distorsion qu’on entend avec les versions suivantes est due à la modification du filtre en temps réel ?

À partir de la version 3.1.0, il n'est plus nécessaire d'appuyer sur "Compute" pour que le changement de filtre soit audible, on entend ce changement en temps réel, mais cela semble produire de la distorsion.

Peut-être que le fait de réintroduire la nécessité d'appuyer sur “Compute” résoudrait ce problème ?

J'ai cherché la version 3.0.3 pour la tester, mais je ne l'ai pas trouvée. Dans mon cas, de la version 3.0.2 on passe à la 3.1.0. J'ai aussi cherché ici https://github.com/GRIS-UdeM/SpatGRIS/releases et je ne l'ai pas trouvée.

**Comment by Normandeau** [comment]
Très bonne observation au sujet du temps réel. La version 3.0.3 était une version «privée» (il faut bien que j'ai quelques privilèges...), créée par Samuel pour régler un problème de VBAP au moment du concert à Akousma.

**Comment by Normandeau** [comment]
Reference Pink Noise
300
Le fait de «computer» le signal envoie également une impulsion numérique à 0dB, même avec cette première version 3.
302
Même constat.
310
Même constat avec la version  3.1.0 excepté que le signal est filtré ici en temps réel.

Donc c'est un bogue qui existe depuis le début de la version 3. Ça nous a échappé...

**Comment by Normandeau** [comment]
216
Le Highpass ne fonctionne pas
219
Même constat que 300

Donc plus ancien que 300.

**Comment by NicolaGiannini** [comment]
Je confirme, je ne m'en suis pas rendu compte quand j'ai fait les autres tests. 
Le fait de «computer» le signal envoie également une impulsion numérique à 0dB, aussi dans les versions précédentes. 

Dans mon cas, le filtre semble fonctionner aussi dans 216, toujours avec le même problème. Je viens de noter que dans 216 il y avait encore la différence entre ID du speaker et numéro de output. Par exemple dans le Speaker Setup de default le output 1 est sur l’ID 5. 
Je n’ai pas été capable de re-installer  certaines versions (notamment 215 et 214), mais le problème semble y être aussi dans la 212 que j'ai encore installée.

Un possible workaround pourrait être de rendre possible la modification et la computation du filtre seulement quand il n’y a pas du son, y inclus le Reference Pink Noise ?

**Comment by NicolaGiannini** [comment]
J'ai testé aussi la 1.0.1 (ServerGRIS!) et quand on compute il y a toujours l'impulsion, dans mon cas.

**Comment by Normandeau** [comment]
B319
Le problème semble enfin réglé. En fait les problèmes. 
- Impulsions graves;
- Difficulté d'ajuster la valeur entre 0 et 20 Hz.
À confirmer.

**Comment by NicolaGiannini** [comment]
V319
Tout semble être réglé. On a regardé cela avec Mélanie en studio. Je l'ai également testé pendant plus de 10 minutes : aucun problème.
