### ISSUE TITLE
Manuel : corriger la partie concernant le fonctionnement de SpatGRIS sous Windows 

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#340]
J'aimerais vous informer qu'il est tout-à-fait possible d'utiliser JACK avec plus de 16 canaux sous Windows. Je viens de faire fonctionner Reaper + SpatGRIS/ControlGRIS via Jack Router avec au moins 32 canaux en entrée et 32 en sortie. En théorie, il n'y a pas plus de limite qu'avec macOS ou Linux.

[Tel qu'indiquer ici (étape 2.), il faut simplement modifier le nombre de canaux maximal dans le document jackrouter avant de l'allumer.](https://music.tutsplus.com/articles/working-with-internal-audio-routing-jack-audio--audio-20601)

Il n'y a donc aucune restriction à utiliser SpatGRIS sous macOS, Linux ou Windows!

**Comment by led78** [comment]
Il faudrait toutefois détailler comment utiliser SpatGRIS avec JACK sous Windows dans le manuel.

**Comment by led78** [comment]
Voilà une excellente nouvelle pour les étuediants de ma formation en création sonore immersive à la SAT!

**Comment by Normandeau** [comment]
Notre politique au sujet du manuel est de décrire comment nos outils fonctionnent ainsi que ceux nous fournissons comme BlackHole. Il est explicitement écrit dans le manuel que les utilisateurs doivent connaître leurs propres outils.
Comme nous ne fournissions ni Windows, ni Jack, c'est aux utilisateurs à faire leur recherche. Merci pour le lien, nous venons de le mettre dans le manuel qui sera fourni avec la prochaine version de SpatGRIS3. En attendant BlackHole pour Windows...

**Comment by MelanieFrisoli** [comment]
Je sais que le sujet est clos et ce n'est pas pour l'ajouter au manuel mais juste pour vous dire que mon copain Thomas a fait des tests 128 in et 128 out avec Jack et SpatGRIS sur Windows et que ça fonctionne super bien !

**Comment by Normandeau** [comment]
On aime cela des copains comme ça!!! Déjà ajouté dans le manuel.
