### ISSUE TITLE
Attenuation Settings: Ajoût d'un interrupteur On/Off

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#342]
V317
Les réglages de Attenuation Settings ne sont pas sauvegardés dans le Projet. Tant et aussi longtemps qu'on laisse SpatGRIS3 ouvert, les mêmes réglages s'appliquent à tous les projets que l'on ouvre.
Cependant si on change ces réglages pour un projet ouvert, et qu'on veut ensuite ouvrir un autre projet, SpatGRIS3 nous demande si on veut sauvegarder les changements. Si on sauve le projet ouvert, qu'on change les réglages et qu'on le rouvre, ce sont les réglages en cours qui sont utilisés et non pas ceux qui sont supposément sauvegardés. Cette situation peut-être embêtante en situation de concert, car si un utilisateur utilise des réglages très marqués, la pièce suivante du concert peut en être fortement altérée. De fait c'est comme cela qu'on s'est aperçu de ce bogue la semaine dernière.

![Capture d’écran, le 2022-03-24 à 10 36 16](https://user-images.githubusercontent.com/8959779/159940278-e0d072ef-966d-4051-8c43-dfcca9fb4266.jpg)

Une note à ce sujet: les Attenuation Settings ont fait partie pendant un certain des Settings généraux (carte de son, Fe, Buffer, etc.). On avait décidé de les sortir de là car dans les faits ils appartiennent aux projets. Il semble qu'il y ait un lien qui se soit perdu dans le changement.

**Comment by NicolaGiannini** [comment]
Je confirme. J'ajoute une note. Dans le fichier XML du projet, l'information semble être présente. À la fin du code on peut voir cela :   
![Schermata 2022-03-24 alle 12 17 19](https://user-images.githubusercontent.com/35705913/159962004-b4270d9d-c500-4195-94c8-6ba5a04ee3f7.jpg)

**Comment by NicolaGiannini** [comment]
Désolé, j'ai essayé de copier le code, mais apparemment github ne l'affiche pas. J'ai donc ajouté une capture d'écran.
![Schermata 2022-03-24 alle 12 17 19](https://user-images.githubusercontent.com/35705913/159962334-5fc127ef-e503-416d-b25f-f69eb3b443d1.jpg)

**Comment by MelanieFrisoli** [comment]
V318
Cela semble réglé

**Comment by NicolaGiannini** [comment]
V318 cela semble réglé aussi dans mon cas.

**Comment by Normandeau** [comment]
Je confirme. Donc réglé.

**Comment by Normandeau** [comment]
V 3.1.13
J'ai un doute. Les Attenuation Settings font actuellement partie du projet. Comme cela a été décrit ici (par moi-même...). Mais en faisant les corrections des Speaker Setups pour la version 3.2, je me demande s'il ne serait pas plus pertinent de les associer plutôt au Speaker Setup?
C'est en effet dans celui-ci que les hp sont disposés et où, par conséquent, que les paramètres d’atténuation se font sentir. Cela me vient du fait que les Attenuation Settings sont toujours actifs. Donc si la fréquence de coupure est à 16000 Hz par exemple, dans un projet, elle se manifestera très peu. Si on change de projet, que celui-ci est réglé à 1000 Hz, alors les aigus seront fortement atténués. Alors qu'on est sur le même setup.
Deux questions donc:
- Attenuation Settings: Projects ou Speaker Setup?
- Attenuation Settings: ajout d'un interrupteur On/Off?

Peut-être qu'on peut les laisser dans le projet avec un interrupteur qui serait à Off par défaut?
Pas nécessaire de démarrer une discussion philisophique ici, écrivez-moi directement à ce sujet, me faisant part de vos réflexions.

**Comment by NicolaGiannini** [comment]
Robert : 

> Peut-être qu'on peut les laisser dans le projet avec un interrupteur qui serait à Off par défaut?

Je seconde cela !
Il peut arriver que le même Speaker Setup soit utilisé avec des paramètres d'atténuation différents. 
Un interrupteur qui serait à Off par défaut serait le bienvenu.

**Comment by MelanieFrisoli** [comment]
Pas de réponse philosophique, juste un point de vue depuis ma petite expérience d'utilisatrice : il m'est arrivé d'utiliser différents paramètres d'atténuation dans le même speaker setup. Cela dépendait des besoins de la pièce que je composais.

**Comment by Normandeau** [comment]
On va laisser les Attenuation Settings avec le projet. On va ajouter une interrupteur On/Off. De toute manière celui-ci était souhaitable car même à 16 000Hz je filtre était actif et éliminait les très hautes fréquences.

**Comment by Normandeau** [comment]
David a écrit:

V. 3.2.0 Global Sound Diffusion à 0 Cube62(30-12-20)Subs2 MMR
Une source qui sort des limites internes du cube est filtrée même si les Attenuation settings sont à 0dB. Si on change la fréquence de coupure du filtre à 16000 Hz, l'effet est moins présent puisque dans le très haut registre. Or, on s'attendrait à ne pas avoir d'atténuation du tout à 0dB. Comme on peut le voir dans cette vidéo, le problème se manifeste aussi en mode binaural.
J'ajoute que le problème survient également au haut du cube, lorsqu'on active le mode extended top dans ControlGRIS. La vidéo ci-haut montre que l'atténuation est forte lorsqu'on dépasse le « plafond », même à 0dB d'atténuation dans SpatGRIS.

**Comment by Normandeau** [comment]
V320. Mode CUBE
Mesures des niveaux de sortie avec Attenuation Settings réglés au minimum (0dB et 16k).
Plaidoyer pour un interrupteur ou pour une correction des réglages.

![Attenuations Settings 16k](https://user-images.githubusercontent.com/8959779/196223854-279a227e-10ea-449e-8492-555835b3c472.jpg)

Échelle de mesure: 1dB par case.
Outil de mesure: DigiCheck NG (lecture directe sur le processeur de la carte)
Bruit rose généré par Twisted Wave.

**Axe Y**

Mesure d'un bruit rose au centre (Y = 0): -1dB au haut de l'échelle:
![Y = 0 Centre](https://user-images.githubusercontent.com/8959779/196224026-e9673105-670d-414f-9593-b4f207caa7fb.jpg)

À la limite du cercle des hp (Y = 0.6): -1dB au haut de l'échelle:
![Y = 0 6 Cercle](https://user-images.githubusercontent.com/8959779/196224202-698505bd-8a30-4157-a771-be0aa0f22c15.jpg)

Au plus loin (Y = 1.0): jusqu'à -6dB au haut de l'échelle:
![Y = 1 0 Extérieur](https://user-images.githubusercontent.com/8959779/196224466-78bcd21d-ac91-4a0b-8511-2f40b8cf0fa2.jpg)

**Axe Z**

Au plancher (Z = 0.0): -1dB au haut de l'échelle:
![Z = 0 0 Floor](https://user-images.githubusercontent.com/8959779/196224644-b482635c-3629-470e-919b-3d72f699ba01.jpg)

Limite du cube (Z= 0.6): jusqu'à -4dB au haut de l'échelle:
![Z = 0 6 Cube](https://user-images.githubusercontent.com/8959779/196224791-4e6f1bdb-b293-4645-b098-3713dc59e881.jpg)

Top (Z = 1.0): -6dB au haut de l'échelle:
![Z = 1 0 Top](https://user-images.githubusercontent.com/8959779/196224937-4ff784d5-a1f5-4c9e-a271-83a324941710.jpg)

**Comment by Normandeau** [comment]
V321
Bouton On/Off pour les Attenuation Settings en place. Sauvegardé avec le projet. Bel ajout.

**Comment by MelanieFrisoli** [comment]
V321
Je suis d'accord, super bel ajout ! 
Peut-être un détail, mais quand "Attenuation Settings" est off, on ne voit presque plus le carré où cliquer pour le remettre à On. 
Chez un·e utilisateur·trice novice, si ce bouton est éteint, cela peut être troublant de constater que l'atténuation ne fonctionne pas, et ne pas savoir qu'on peut le rallumer. Qu'en pensez-vous ?

**Comment by NicolaGiannini** [comment]
J'ai copié le commentaire suivant dans l'issue dédié https://github.com/GRIS-UdeM/SpatGRIS/issues/377

> V321
> Moi aussi je suis d’accord, super bel ajout !
> 
> En effet comme Mélanie l'indique : "quand "Attenuation Settings" est off, on ne voit presque plus le carré où cliquer pour le remettre à On."
> 
> On pourrait rendre le carré gris quand il est sur off pour le rendre plus visible ?
> 
> J'ajoute une note. 
> Pas du tout urgent. Je me demande si pour rendre encore plus évident le changement d'état entre OFF et ON, il ne serait pas utile de griser les deux paramètres (db et Hz) lorsque l'atténuation est désactivée.

**Comment by DavidPiazza** [comment]
Question : quelle est l'utilité d'avoir une option 0 dB dans le menu d'atténuation, maintenant qu'un interrupteur existe pour activer ou désactiver l'atténuation? D'autant plus que, malgré cet ajout, reste qu'un facteur d'atténuation non-négligeable est _toujours_ appliqué alors que le paramètre est à 0 dB, comme je l'ai mentionné ici -> #374.

https://user-images.githubusercontent.com/50223477/204678762-6bfb27a5-b11f-4b78-8c3f-2d8b2c419f15.mov

**Comment by Normandeau** [comment]
L'atténuation en dB et le filtre en Hz sont indépendants. Donc le 0dB permet de conserver le niveau de sortie sans atténuation, alors que le filtre est toujours actif. Dans l'exemple ci-dessus, celui-ci est à 125 Hz donc forcément, le niveau de sortie baisse énormément lorsque le filtre est actif. Le problème dans les vidéos de l'issue 374 c'est que les réglages de SpatGRIS ne sont pas spécifiés.

**Comment by DavidPiazza** [comment]
> L'atténuation en dB et le filtre en Hz sont indépendants. Donc le 0dB permet de conserver le niveau de sortie sans atténuation, alors que le filtre est toujours actif. Dans l'exemple ci-dessus, celui-ci est à 125 Hz donc forcément, le niveau de sortie baisse énormément lorsque le filtre est actif. Le problème dans les vidéos de l'issue 374 c'est que les réglages de SpatGRIS ne sont pas spécifiés.

Ah, je comprends maintenant! Je croyais que la boîte de droite ne faisait que spécifier la fréquence de coupure du filtre et que la boîte de gauche déterminait la raideur de sa courbe d'atténuation par octave. Mon erreur!
