### ISSUE TITLE
Interpolation verticale / nombre de couches inconnu

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#343]
Led78
Suite à quelques tests avec les Audiodices de la SAT, je remarque une grande disparité entre l'interpolation horizontale et verticale, si elle existe. Idéalement, il faudrait avoir deux boutons d'interpolation en mode CUBE; un pour le plan vertical et un pour le plan horizontal.

Le cas du Audiodice est particulier et implique beaucoup de choses, car il contient 12 haut-parleurs très rapprochés en comparaison à un disposition de salle composé essentiellement de haut-parleurs assez éloignés en circonférence. L'interpolation d'un tel haut-parleur multi-directionnel devrait avoir sa propre interpolation indépendante de l'ensemble d'un dispositif de salle. Mais c'est un autre sujet.

Il permet toutefois de mettre en évidence la grande disparité entre l'interpolation verticale (quasi nulle) et horizontale (trop diffuse). En effet, [dans ce vidéo](https://share.icloud.com/photos/0aftOj5nxNwezJLdZR3yPjDqw), on voit que le mouvement haut-bas d'une source active les haut-parleurs soit de la couche supérieure ou inférieure, sans transition; inversement, les mouvement gauche-droite et avant-arrière son à peine perceptibles, et ce, avec une interpolation minimale.

Une autre incohérence est la différence entre la position verticale (Z) d'une source et son étendue (span) verticale.
Par exemple, si on une position N à la valeur Z permet à la source d'activer un haut-parleur situé à cette position, ce n'est pas le cas de l'étendu; une source dont la valeur Z est 0, mais dont l'étendue atteint et même dépasse la valeur N n'activera pas le haut-parleur à cette position. [La présente vidéo manifeste cela, en plus de la disparition d'interpolation verticale et horizontale](https://share.icloud.com/photos/08f41b-OF_11hJbO9B5Lje2qQ).
Aussi, du moment où la source passe à la couche supérieure, elle n'est plus du tout diffusée par les haut-parleurs les plus rapprochés, mais uniquement par le seul haut-parleur dont la hauteur (Z) n'est pas 0. Il faut ajouter deux fois plus d'étendu vertical que leur position verticale relative pour que les haut-parleurs du sol soient activés (1m45).

**Comment by Normandeau** [comment]
Led78
Moi et Louis-Olivier Desmarais venons de tester un dispositif en cube disposé sur deux étages en mezzanine (8 + 8), à la Chapelle Historique du Bon-Pasteur, et le constat est le même : il n'y a pas d'interpolation verticale. Également, on a remarqué que la valeur d'interpolation ne s'appliquait pas toujours immédiatement - on utilise un MacBook M1. Je n'ai pas testé davantage, mais en réduisant la valeur d'interpolation de SpatGRIS de 1 à 0, le son d'une source très localisée éclaboussait autant sur les autres. Puis, en élevant légèrement la source en hauteur (Z), le haut-parleur le plus près de la source n'émettait plus du tout, tandis que les autres oui. Éventuellement, je ne se sais pas pourquoi, l'interpolation s'est remise à 0 et le son ne sortait que par le haut-parleur le plus près.

**Comment by Normandeau** [comment]
On n'arrive pas à visualiser les vidéos. ICloud dit: «Les photos partagées ne sont pas disponibles.» De plus on n'arrive pas à reproduire cela. L'interpolation verticale fonctionne très bien chez nous.

**Comment by led78** [comment]
Oui, ça fait déjà quelques temps de cela. Ce n'est pas avec la dernière version en tout cas. Je vais essayer de repartager les vidéos sur GitHub dès que j'ai un peu de temps.

**Comment by led78** [comment]
Je viens de tester avec v.3.1.9 et ce problème semble toujours exister : avec ou sans interpolation générale, avec ou sans atténuation, les haut-parleurs situés sur une même couche verticale sont favorisés, même s'il sont horizontalement plus distants de la source spatialisée, ce qui créer une incohérence perceptive. [J'ai encore une fois capté des vidéos pour le démontrer, avec un audiodice situé à l'intérieur du dôme de la Satosphère (SAT)](https://drive.google.com/drive/folders/10dS9nC3O01rqKuTIB78nzWAdXzpwQ3_g?usp=sharing).

**Comment by led78** [comment]
Pour une source traversant le haut d'un dispositif hémisphérique, on s'attendrait à ce qu'elle soit inaudible au centre du dôme avant d'avoir pénétré à l'intérieur du dôme, ce qui n'est pas le cas actuellement d'après mes tests.

**Comment by led78** [comment]
On voit dans les exemples vidéo que, dès que la source est émise par les haut-parleurs situés au bas dôme, elle est également émise par les haut-parleurs du audiodice situés au même niveau vertical, quoique plus éloignés au centre de l'espace, et ce, malgré le fait que la source soient plus rapprochée des haut-parleurs situés plus haut, sur un autre niveau vertical.

**Comment by led78** [comment]
Avoir un contrôle indépendant des interpolations verticales et horizontales permettrait d'ajuster et d'adapter la redistribution des signaux en fonction du dispositif - distance relative des haut-parleurs sur les plans vertical et horizontal -, à l'instar des _spans_ de source dans ControlGRIS.

**Comment by led78** [comment]
Il semblerait que le problème vienne du fait que le Audiodice se trouve entre deux couches de hautparleurs du dôme, créant ainsi sa propre couche indépendante des autres. Pour l’instant, on ignore combien de couches (layers) sont réellement crées et on ne peut pas déterminer manuellement l’écart des valeurs de z se trouvant dans chaque couche précalculée. Mais il faudrait pouvoir calibrer cela d’une façon ou d’une autre pour que ça reste cohérent avec la perception.

**Comment by NicolaGiannini** [comment]
David dit :

> Je viens de tester avec v.3.1.9 et ce problème semble toujours exister : avec ou sans interpolation générale, avec ou sans atténuation, les haut-parleurs situés sur une même couche verticale sont favorisés, même s'ils sont horizontalement plus distants de la source spatialisée, ce qui créer une incohérence perceptive

V3.1.10 (mais je crois aussi versions précédentes)
En effet en mode CUBE la position verticale (Z) d'une source semble être prédominante par rapport à la position sur l'axe horizontal, en ce qui concerne le signal envoyé aux HP. 

Je pense que probablement on avait déjà discuté de cela avec Robert. 

Je crois qu'en mode CUBE, une couche est créée chaque fois qu'un HP est placé à une hauteur différente (Z).

Si une source est exactement à la même hauteur Z d'une couche de HP, seulement les HP de cette couche émettent du signal. Cela peut donc produire le comportement suivant : la source n'est pas diffusée par des haut-parleurs proches (plus proches que les haut-parleurs qui la diffusent effectivement) si ces haut-parleurs sont à une hauteur différente. La source peut donc être diffusée par des haut-parleurs qui sont plus loin de la source en termes absolus, si l'on considère les axes vertical et horizontal ensemble.

Vidéo 1 


https://user-images.githubusercontent.com/35705913/185666359-aea9c98d-d296-46db-b086-4f92e90cf21d.mov



Quand la source atteint Z=1, où les HP 17 et 18 sont placés, le HP 10 n'envoie pas du signal, même s’il est plus proche de la source. 

Vidéo 2 

https://user-images.githubusercontent.com/35705913/185666499-85bebab9-a251-482e-a7d9-36f20156370e.mp4




Quand la source atteint Z=0,4 où le HP 2 est placé, les autres HP, n'envoient pas du signal, même si parfois ils sont plus proches de la source. Vu que le HP 2 est l'unique à Z=0,4, c'est l'unique qui émet du signal à cette hauteur.

**Comment by Normandeau** [comment]
V 3.1.13
Je ferme cette issue puisque l'algorithme du cube est changé et qu'une nouvelle issue a été créée afin de décrire les nouveaux problèmes mis en cause par celui-ci #365
