### ISSUE TITLE
Dézoom impossible dans l'affichage seulement avec les Mac M1

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#344]
V3.1.10 & Mac M1
Lorsque l'on zoom sur la section d'affichage des haut-parleurs, il est impossible ensuite de dézoomer. 
Il semble que ce soit le cas depuis la version 3.1.6.

Le plus grave, en fait, c'est que même si je ferme et rouvre SpatGRIS, le problème persiste et je me retrouve avec un affichage très zoomé sans possibilité de le changer... 

Je suis donc bloquée ici : 

<img width="724" alt="Screen Shot 2022-05-10 at 11 11 48 AM" src="https://user-images.githubusercontent.com/74631914/167662133-113ed4d4-08fa-48d7-bffb-b14cf7e3e510.png">

**Comment by Normandeau** [comment]
Il semble que ce bogue soit exclusif au M1 (rapporté aussi par un utilisateur allemand). Sur mon Mac Intel, aucun problème de cette nature avec toutes les versions officielles 3 (3.0.0, 3.0.2, 3.1.1 et 3.1.9), ainsi qu'avec la dernière en date (3.1.10).

**Comment by Normandeau** [comment]
Voir #244 et #288

**Comment by MelanieFrisoli** [comment]
En rebootant l'ordinateur, le zoom fonctionnait normalement. 
Il se rebloque quand je zoome au maximum et se retrouve bloqué ensuite (et je dois éteindre à nouveau l'ordinateur pour espérer avoir une vue normale)

**Comment by NicolaGiannini** [comment]
Avec mon Mac Intel sur 10.14.6 aucun problème non plus.

**Comment by MelanieFrisoli** [comment]
V3.1.11
Le zoom est toujours bloqué dans cette nouvelle version, mais cette fois-ci, même en redémarrant une fois, ça reste bloqué. J'ai éteint et rallumé l'ordinateur et la vue est toujours bloquée. 
Ce qui est encore plus surprenant, c'est que je l'ai désinstallé et réinstallé deux fois et que ... la vue est toujours bloquée. 


UPDATE **** 
En vidant le cache et en supprimant les dossiers qui étaient dans "Application Support", j'ai réussi !

**Comment by MelanieFrisoli** [comment]
V3.1.12
Le souci avec le zoom a l'air de persister sur la nouvelle version.
Comme avec les précédentes versions, quitter SpatGRIS ou même rebooter l'ordinateur ne sert à rien.
Pour revenir à une vue "normale", j'ai dû supprimer le dossier qui était dans "Application Support", en plus du fichier "ca.umontreal.musique.gris.spatgris" qui se trouvait dans les Préférences (ce qui n'était pas le cas la fois dernière).

**Comment by MelanieFrisoli** [comment]
V3.1.13
Même problème avec le Zoom que précédemment et même solution pour revenir à une vue normale.

**Comment by Normandeau** [comment]
V321
Impossible à vérifier avec les Mac Intels. Sur le M1 du FCI, on n'a pas ce problème. Est-ce que ce bogue est toujours valide?

**Comment by OKGougou** [comment]
Robert,

Finalement, j'ai pu reproduire le bug, mais seulement en mode realease, pas
en mode debug. En essayant quelques trucs ça a fonctionné de mon côté.

Gaël

**Comment by Normandeau** [comment]
Gaël,

Excuse mon ignorance.
Ça veut dire quoi exactement, la différence entre les deux modes?

En essayant quelques trucs ça a fonctionné de mon côté.

Qu'est-ce qui a fonctionné: de reproduire le bogue?
Ou de faire fonctionner l'ordi correctement?

**Comment by MelanieFrisoli** [comment]
V321
Même problème pour ma part sur un M1. 
Fermer et rouvrir SpatGRIS ne change rien, il faut que je supprime le fichier dans "Application Support" pour que ça revienne à la normale.

**Comment by Normandeau** [comment]
Donc ce serait le fichier des préférences qui causerait le problème?

**Comment by MelanieFrisoli** [comment]
Ce fichier : 
<img width="978" alt="Screen Shot 2022-11-07 at 9 40 00 AM" src="https://user-images.githubusercontent.com/74631914/200337721-6c41159c-32bd-40e2-b95c-8287dd59af29.png">

**Comment by Normandeau** [comment]
V325
macOS 13.2.1 (Ventura)
MacBook M2
Pas de problème de zoom et de dézoom sur M2 avec macOS 13.2.1

**Comment by Normandeau** [comment]
Louis Dufort a écrit le 23-04-17:

Bonjour,
J'ai accidentellement activé un "zoom in" sur l'interface graphique 3D de l'emplacement des HP. Lorsque je quitte SpatGRIS ou que je change de template, rien n'y fait, je suis toujours très rapproché et ne peut voir l'ensemble des HP. Comment peut-on "zoomer out" ?

**Comment by MelanieFrisoli** [comment]
Bonjour ! 

J'expliquais plus haut qu'il fallait aller supprimer le fichier présent dans Library->Application Support->GRIS pour que ça revienne à la normale.

**Comment by Normandeau** [comment]
V3.3.0 avec Speaker View 0.0.0.1
Mac M2 macOS 13.6
Pas de problème de zoom avec le M2.
Gaël: il faudrait que tu valides cela avec le M1 du GRIS. C"est le seul qu'on a sous la main.

**Comment by OKGougou** [comment]
Oui, ça fonctionne avec le M1.
