### ISSUE TITLE
Un gros bouton MUTE ALL serait bienvenu

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#345]
Je travaille dans un studio muni de 28.4 haut-parleurs. Comme c'est souvent le cas, par exemple dans le B187, les studios ne sont pas équipés d'un MUTE général, en cas de génération de signaux audios indésirables (comme le problème décrit en #339).
Je suggère donc qu'on ajoute un MUTE ALL dans SpatGRIS3. Tu appuies dessus, et le son s'arrête partout. Cela m'est déjà arrivé, et la seule ressource d'urgence disponible est de fermer ControlGRIS3, mais faut y penser... Donc un bon gros bouton bien visible qui ne disparaît jamais de la fenêtre quelque soit le niveau de zoom utilisé.
Pour l'instant ça pose un problème, car on peut réduire la grosseur de la fenêtre à pratiquement rien. Il faudrait donc apporter une modification graphique pour faire en sorte qu'un moins le bouton MUTE reste toujours visible:
![Capture d’écran, le 2022-05-30 à 10 47 13](https://user-images.githubusercontent.com/8959779/170954730-fb8a00bf-8cc6-41d6-88e5-b31c886a4449.jpg)

On pourrait même être en mesure de l'asservir en MIDI à un vrai bouton extérieur ou touche de clavier ou que ce soit en MIDI à la portée de la main selon la nature du studio de l'utilisateur.

**Comment by NicolaGiannini** [comment]
Très bonne idée !
Je pensais à l'emplacement. Il pourrait être près de l'Output Gain ? Vu que ce contrôle gère tous les Speakers en même temps. 

Par exemple : 
![Mute2](https://user-images.githubusercontent.com/35705913/171026027-ff27a1bb-8ac1-4134-bcb7-af8f38a40b2e.jpg)

Comme fenêtre minimale, nous pourrions peut-être établir 1024x768 pixels ? Par exemple: 

![Schermata 2022-05-30 alle 11 39 20](https://user-images.githubusercontent.com/35705913/171026354-aa2d9d6c-56e3-4096-90e7-91b798a1d80b.jpg)

**Comment by MelanieFrisoli** [comment]
Super idée de nouveau bouton (et super idée pour l'emplacement aussi!).

**Comment by Normandeau** [comment]
V3.3.7
Le bouton MUTE vient d'être ajouté
