### ISSUE TITLE
Mode CUBE, si les haut-parleurs sont à distance de 2.01 et plus, une source n'est pas reproduite lorsqu'elle est très proche du centre.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#346]
V3110 (mais je crois aussi avec les versions antérieures, testé aussi avec v3.0.2)

Mode CUBE, si les haut-parleurs sont très éloignés du centre, à une distance supérieure à 2, la source n'est pas reproduite lorsqu'elle est très proche du centre. 
J’ai noté ce comportement en essayant le template Cube (2x4)Subs2 Big.

En déplaçant une source de l'extérieur vers le centre, le niveau augmente progressivement jusqu'à s'arrêter lorsque l'on arrive dans une zone proche du centre, valeur de 0.33 (en X ou en Y), ce qui correspond visuellement au petit carré de SpatGRIS3.

Vidéo https://www.dropbox.com/s/mitjiak4o47zu3x/Cube-Distance1.mov?dl=0

Lorsque la source est au centre de la configuration, pour le son se rende aux haut-parleurs, il est nécessaire que le haut-parleur soit positionné à une distance de 2 ou moins.

Vidéo https://www.dropbox.com/s/iooikq6ya8c3ycf/Cube-Distance2.mov?dl=0

**Comment by MelanieFrisoli** [comment]
V3110
Testé avec le même speaker setup et effectivement, l'acheminement vers les sorties coupent quand on s'approche trop du centre.

2 remarques : 

1) Cela fonctionne pourtant dans les modes stéréo et binaural sans coupure. 

2) Sans réduction stéréo, cela ne semble pas arriver uniquement sur une circonférence. J'ai testé avec des trajectoires en cercle. Certes, trop près du centre, nous n'avons plus de son du tout vers les sorties, mais à une distance "intermédiaire", SpatGRIS envoie du son vers les sorties de manière intermittente.

Dans la vidéo suivante, c'est illustré par la troisième taille de cercle.
Avec la quatrième taille, le son n'est juste plus acheminé vers les sorties. 


https://user-images.githubusercontent.com/74631914/171162655-1838e264-c9f4-4f89-a600-6e4baa1d0d7e.mp4

**Comment by Normandeau** [comment]
Je confirme le tout. J'ajoute un autre problème qu'on voit bien sur la vidéo de Mélanie mais qui n'est pas mentionné: le déplacement est discret, c'est-à-dire que le son passe directement d'un haut-parleur à l'autre sans fondu. Il faut dire que l'interpolation est ici réglée à 0.10.
J'ai repris le même setup où j'ai mis tous les hp à distance de 2.0. L'autre problème qui est illustré ici, c'est le saut brusque d'un groupe de haut-parleurs à l'autre lorsque le son passe par le centre et que l'interpolation est à 0.00. Lorsqu'on l'ajuste à 1.00, il y a un meilleur fondu mais cette valeur pourrait être plus grande.
Je pense qu'il faut d'abord corriger le problème du silence lorsque les hp sont trop loin et ensuite améliorer le paramètre d'interpolation en mode Cube (voir aussi #343).

Interpolation à 0.00, puis à 1.00 (autour de 0'18"):

https://user-images.githubusercontent.com/8959779/171637796-f6f6bd81-367d-4ed1-a8ab-74ad82f58aba.mov

**Comment by Normandeau** [comment]
V3.1.12
Cube8(2X4)Subs2 Big (attention le template est défectueux. Le hp 5 est en bas).
Interpolation: 0; Attenuation Settings: 0db; 16kHz
Wow! Grand progrès ici. J'ai repris les tests mentionnés plus haut. J'ai mis les 8 sorties en mono afin valider la perception de force égale lors du déplacement de la source sur les 8 hp. Comme dans la vidéo de Mélanie, j'ai fait tourner une source de bruit rose sur des cercles du plus petit au plus grand. La sensation de force sonore est parfaitement égale, de bas en haut et partout entre les deux.
Et grande nouvelle: je pense enfin avoir résolu l’énigme de la quadrature du cercle!!! ;-)
Sinon, autres tests à réaliser.

https://user-images.githubusercontent.com/8959779/181298411-1bb30ee0-2581-4927-a89e-1a78a7204545.mov

**Comment by NicolaGiannini** [comment]
V3.1.12
La question du silence au centre me semble avoir été réglée ! Les haut-parleurs reproduisent une source qui est au centre même lorsqu'ils sont positionnés dans les coins, et donc même à une distance de 2,01 et plus. Le comportement est celui attendu : lorsque la source est proche du centre, davantage de haut-parleurs participent à la diffusion du son, alors que quand la source est éloignée du centre, la diffusion du son est plus localisée.
