### ISSUE TITLE
Un Speaker Setup avec des numéros de HP non consécutifs fait planter SpatGRIS avec Show Player View

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#348]
V3.1.11

Dans mon cas, si je charge un Speaker Setup avec des numéros de HP non consécutifs et que j’active la fonction Show Player View, SpatGRIS se plante.

Par exemple, en chargeant le template Dome16(8-6-2)Subs 2 (numéros de HP consécutifs), je peux activer la fonction Show Player View sans problème. 

Si je charge le template Dome16(8-6-2)Subs2 UdeM Hexa (numéros de HP non consécutifs), l’activation de la fonction Show Player View fait planter SpatGRIS, dans mon cas.

Testé avec des Setup Dome et Cube.

J’ajoute une note.

Si je modifie un setup avec des numéros de HP consécutifs, en insérant des chiffres non consécutifs, je fais “Compute” et que j’active la fonction Show Player View, je n’ai pas de crash.
Si j’enregistre le setup, je redémarre SpatGRIS, j’ouvre le SpeakerSetup enregistré et que j’active  la fonction Show Player View, SpatGRIS plante. 

Exemple : 
Je charge le setup Dome16(8-6-2)Subs 2
Je change la sortie du dernier HP de 18 à 19.
J’obtiens donc un setup avec des numéros non consécutifs.
J’appuie sur Compute.
Je lance le player.
Aucun crash.

J’enregistre le Speaker Setup modifié avec des numéros non consécutifs.
Je redémarre SpatGRIS. 
Quand je redémarre SpatGRIS, je retrouve chargé le Setup que je viens d’enregistrer.
Je lance le player.
J’ai un crash.

**Comment by Normandeau** [comment]
Je confirme

**Comment by Normandeau** [comment]
J'ajoute: les numéros doivent non seulement être consécutifs mais ils doivent commencer à 1. J'ai pris un setup standard de 16 canaux, et j'ai mis les numéros 7 à 24 (au lieu de 1 à 16). Crash comme décrit par Nicola. À corriger.

**Comment by NicolaGiannini** [comment]
Je confirme. Cela me fait penser à une chose. Il semble donc que les numéros des Speakers doivent être identiques aux numéros des Sources pour qu'il n'y ait pas de crash.

**Comment by Normandeau** [comment]
Voir issue #241

**Comment by MelanieFrisoli** [comment]
Je confirme également.

**Comment by Normandeau** [comment]
V3.1.12
Les numéros de hp peuvent être:
- non-consécutifs
- commencer avec une valeur autre que 1
- indépendants des numéros des sources

Problème corrigé.
