### ISSUE TITLE
Effacer tout les hp d'un setup de hp Hybrid fait planter SpatGRIS sans avertissement

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#349]
V 3.1.9, 3.1.10, 3.1.11
Je prend le speaker setup sur lequel je travaille en ce moment, soit celui du Micadôme qui est Hybrid. Celui-ci possède 32 hp (8+8+8+4)Subs4 numérotés de 1 à 32. Cependant, je les ai disposés de manière non consécutive, de manière symétrique par rapport à l'axe central. Ça ressemble à ceci:
![Capture d’écran, le 2022-06-06 à 15 33 44](https://user-images.githubusercontent.com/8959779/172170893-3be03450-5c3a-402e-b41b-68cc99aaedad.jpg)

En partant de celui-ci, j'ai voulu créer un nouveau setup, donc j'ai effacé les hp existant un à un. Alors que je suis en train d'effacer le 3e avant-dernier hp, j'aurais dû recevoir le message d'avertissement que je n'ai plus assez de hp pour faire un dôme n'est-ce pas? Mais ce n'est pas le cas et au lieu de cela, je me rends au dernier et lorsque je l'efface, SpatGRIS plante (des fois il se plante au 2e ou 3e avant-dernier).

Si je fais la même procédure avec le speaker setup par défaut, aucun problème, le fenêtre d'avertissement arrive au bon moment, et même si j'efface tout, pas de problème. Même chose avec celui d'Hexa ou d'Icosa, pourtant non consécutifs. 

Bingo: J'ai deux versions d'Icosa: Dome et Hybrid. C'est exactement le même dispositif. La version Dome: pas de problème. La version Hybrid se plante. J'ai testé tous les templates Hybrid et ils se plantent tous.

**Comment by NicolaGiannini** [comment]
Je confirme.
J'ajoute une note. Dans mon cas, le crash se passe quand j'efface le dernier HP qui n'est pas une sortie directe.

Par exemple, si on considère le setup Dome10(8+2)Subs2 Hybrid, si je n'efface pas les sorties directes, le crash se passe quand j'essaie d'effacer le dernier HP qui n'est pas une sortie directe. Donc quand j'essaie d'effacer le premier des 3 derniers. 
Si par contre j'efface d'abord les sorties directes, le crash se passe quand j'essaie d'effacer le dernier speaker.

**Comment by MelanieFrisoli** [comment]
V310 / V317 / V3111
Je confirme, j'ai absolument les mêmes crash que ceux décrit par Robert et Nicola (même chose également avec les sorties directes et l'ordre avec lequel j'efface les hp).

V311, V317 & V3111 : 
Je ne sais pas si c'est utile, mais si nous sommes en mode Binaural ou Stéréo, SpatGRIS ne plante pas du tout. Nous pouvons effacer tous les hp (dans n'importe quel ordre) sans message d'avertissement, ni crash. 
Cependant, avec V310 (première version à avoir la configuration Hybride), même en mode binaural et stéréo, SpatGRIS plante lorsque l'on cherche à effacer tous les hp.

**Comment by Normandeau** [comment]
V3.1.12
Problème résolu en mode Hybrid, La fenêtre d’avertissement apparaît bien lors de l'effacement du 3e avant dernier hp. Et SpatGRIS ne se plante lors de l’effacement du dernier hp.
