### ISSUE TITLE
Si la fenêtre 3D montre le Speaker Setup vu du dessus lors de la fermeture de SpatGRIS, le Speaker Setup disparaît lors de la réouverture.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#352]
V3.1.11 (mais le comportement est présent depuis 2.1.9)
MacOs 10.14.6 - 2,9 GHz Intel Core i7 

Si la fenêtre 3D montre le Speaker Setup vu du dessus lors de la fermeture de SpatGRIS, le Speaker Setup disparaît lors de la réouverture.
 
Si on clique sur la fenêtre 3D et on essaie de changer l'angle de visualisation, le Speaker Setup réapparaît.
Voir la vidéo : 
https://udemontreal-my.sharepoint.com/:v:/g/personal/nicola_giannini_umontreal_ca/EerJypFgxYxJqJKoevc1d9ABO71HIkaKeAGL-XfDJonong?e=9uj5pF

(Dans la vidéo à la première fermeture, le Setup n'est pas parfaitement vu d'en haut, à la deuxième oui)

Par «vu du dessus», j'entends une position du Speaker Setup comme celle de Show 2D View. Une fois placé dans cette vue du dessus, le Setup peut être tourné (à gauche et à droite), et le phénomène se produit quand même. Si, par contre, le Speaker Setup est incliné (on fait monter, par exemple, la partie du bas vers le haut), et donc que la vue n'est pas exactement d'en haut, le phénomène ne se produit pas.

J'ai noté que ce comportement est apparu lors du passage de 2.1.8 à 2.1.9.

Si je comprends bien, jusqu'à 2.1.8 la position du Speaker Setup dans la fenêtre 3D était sauvegardée dans le projet. Par exemple, si on change simplement cette position et on ferme SpatGRIS 2.1.8, le logiciel demande si on veut sauvegarder le projet. Si on sauvegarde le projet avec le Speaker Setup en position frontale, à la réouverture, le Speaker Setup est affiché. À partir de 2.1.9, SpatGRIS rappelle la position du Speaker Setup dans la fenêtre 3D si on ferme et rouvre SpatGRIS et cela sans devoir sauvegarder le projet.

**Comment by Normandeau** [comment]
V2.1.9 à 3.1.11
Je confirme le tout. Très bonne observation!

**Comment by Normandeau** [comment]
B3.1.12
Problème d'affichage réglé.
