### ISSUE TITLE
SpatGRIS indique qu'un projet est modifié aussitôt qu'il est ouvert: question de version

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#353]
V3.1.12
SpatGRIS3 «pense» qu'un projet est modifié aussitôt qu'il est ouvert. Si on ne fait qu'ouvrir SpatGRIS3 avec le dernier projet utilisé par exemple et qu'on referme SpatGRIS3 sans avoir rien modifié, SpatGRIS3 nous avertit que le projet a été modifié et qu'il faut le sauvegarder. Même chose si j'ouvre un Template et qu'ensuite je ferme SpatGRIS3, il me dit que des modifications ont été apportées et il me demande si je veux les sauvegarder:
À corriger.
![Projet modifié](https://user-images.githubusercontent.com/8959779/182248709-4ee9a96e-2d72-408a-bc4d-20ce85f5ae0e.jpg)

**Comment by NicolaGiannini** [comment]
V3.1.12
MacOS 10.14.6 - CPU 2,9 GHz Intel Core i7
Je n'arrive pas à reproduire l'issue. J'ai essayé avec un projet sauvegardé et des templates. 
Voici une vidéo : 


https://user-images.githubusercontent.com/35705913/185662994-e508ec21-9a6d-4ae7-bf51-809b66a218c9.mp4

**Comment by NicolaGiannini** [comment]
Mise à jour.

Je suis arrivé à reproduire l’issue. Je pense que cela se produit si lors de la fermeture du logiciel, le projet et le Speaker Setup ne sont pas réglés sur le même mode.

Exemple :

- J’ouvre un speaker setup DOME
- J’ouvre un projet CUBE (template ou sauvegardé)
- Le speaker setup passe de DOME à CUBE (mais SpatGRIS ne m’avertit pas de cette transformation).
- J’essaie de fermer SpatGRIS.
- SpatGRIS m’avertit que le Speaker Setup n’est pas sauvegardé (parce qu’il est passé de DOME à CUBE).
- Si je ne sauvegarde pas le nouveau Speaker Setup, la situation décrite par Robert se produit. 
- Je pense que cela arrive car à la réouverture SpatGRIS rappelle le projet (sauvegardé ou template) en CUBE et le Speaker setup DOME. Le fait que le Speaker Setup soit en DOME produit un changement immédiat dans le projet qui devient lui-même DOME. Donc si je ferme encore SpatGRIS il me demande si je veux sauvegarder les modifications au projet.

L’issue se produit si lors de la fermeture du logiciel, le projet et le Speaker Setup ne sont pas réglés sur le même mode (DOME, CUBE ou HYBRID).
L’issue ne se produit pas si au moment de la fermeture du logiciel, le projet et le Speaker Setup sont réglés sur le même mode (DOME, CUBE ou HYBRID).

**Comment by Normandeau** [comment]
Bravo Nicola, belle trouvaille. C'est la même logique avec le Speaker Setup. Si j'ouvre un projet Cube avec un Dome ouvert, il me demande si je veux sauvegarder le speaker setup. Comme le mode est maintenant sauvegardé autant dans le projet que dans le speaker setup, SpatGRIS3 compare la cohérence entre les deux.
Il faut donc ajouter une note dans le manuel à cet effet.

**Comment by NicolaGiannini** [comment]
Très bonne idée la note. 
Je me demande aussi s'il pourrait aider que SpatGRIS prévienne lorsqu'un Setup change de mode. Cela se produit lorsque l'on passe de CUBE à DOME, mais pas dans l'autre sens.

![Schermata 2022-08-02 alle 15 36 23](https://user-images.githubusercontent.com/35705913/182459151-8f59fe9e-ff40-4569-924a-33b7577b5e84.jpg)

**Comment by Normandeau** [comment]
V321
Si on ouvre SpatGRIS et qu'on le referme immédiatement sans rien changer, celui-ci nous avertit que le Project a été modifié. Même avec les valeurs par défaut qui s'ouvrent. Il semble que ça ne soit valable qu'avec les projets, pas avec les Speaker Setups.
Agaçant...

**Comment by NicolaGiannini** [comment]
Je confirme que c'est très facile d'obtenir cela :

> Si on ouvre SpatGRIS et qu'on le referme immédiatement sans rien changer, celui-ci nous avertit que le Project a été modifié.

Par exemple : 

- Situation de départ = projet Default_Project18 mode DOME; Setup Dome_Default_Speaker_Setup
- J'ouvre le template de projet CUBE project96(12x8)
- SpatGRIS passe en mode CUBE et donc il transforme le setup Dome_Default_Speaker_Setup en CUBE.
- Je ferme SpatGRIS en répondant "Discard" à la demande si je veux enregistrer ce Setup.
- J'ouvre SpatGRIS : le setup Dome_Default_Speaker_Setup est en mode DOME parce que je ne l'avais pas sauvegardé. 
- Le project96(12x8), à l'origine en CUBE, est transformé en DOME par l'ouverture de ce setup DOME. Et en fait on ne voit pas les paramètres d'atténuations affichés. 
-  Je ferme SpatGRIS sans rien faire. SpatGRIS me demande si je veux sauvegarder le projet. 

Je pense que cela arrive parce que SpatGRIS reconnait que le fichier original du project96(12x8) était en CUBE, mais l'ouverture du setup DOME, transforme ce projet en mode DOME.

**Comment by Normandeau** [comment]
Sans rien faire de tout cela, il suffit d'ouvrir SpatGRIS et de le refermer, sans rien toucher, et SpatGRIS nous demande tout de même si on veut sauvegarder le projet.
Cela est nouveau.

**Comment by Normandeau** [comment]
En même temps que la disparition de l'issue #379 celle-ci est disparue aujourd'hui...
Mon ordi doit être hanté!

**Comment by Normandeau** [comment]
Et il est revenu aussi vite!!!

**Comment by Normandeau** [comment]
Je viens de comprendre.
Gaël a modifié tous les templates après que je les lui ai fait parvenir, pour intégrer le bouton des Attenuations Settings.

Donc quand je joue avec des templates, je n'ai pas la fenêtre d'avertissement qu'ils ont été modifiés.
Mais si j'ouvre mes projets personnels, il sont alors considérés comme modifiés, car le nouveau format est différent du précédent.
Donc même mes templates ne sont pas conformes...

Si vous ouvrez des Speaker Setups ou des Projects qui sont sur vos disques durs, ils ne sont plus conformes au nouveau format xml. Donc pour le devenir, il faut les sauvegarder à nouveau...
