### ISSUE TITLE
La modification d'un paramètre d'un HP dans la fenêtre Speaker Setup Edition fait en sorte que SpatGRIS plante

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#354]
V3.1.12
MacOS 10.14.6 - CPU 2,9 GHz Intel Core i7

La modification d'un paramètre d'un HP dans la fenêtre Speaker Setup Edition fait en sorte que SpatGRIS plante à la fermeture de cette fenêtre. Dans mon cas cela se produit avec tous les parametres qu'on peut éditer pour les HP (de Output à Delete).
Cela ne se produit pas avec l'HP 1.
Cela se produit avec tous les autres HP d'un Setup.
Cela se produit dans tous les modes.

Voir la vidéo :

https://user-images.githubusercontent.com/35705913/185660684-e277c373-60df-4a60-81d5-d46a87749c89.mp4

**Comment by Normandeau** [comment]
MacOS 12.5
Même commentaire sauf ceci: si on fait Compute avant de fermer le Speaker Setup Edition, SpatGRIS ne plante pas. Donc c'est comme si la fonction automatique de Compute qui s'active lorsqu'on ferme la fenêtre Speaker Setup Edition n'était plus fonctionnelle. Maintenant je fais mon «coming out»: je n'ai jamais aimé cette fonction automatique car c'est comme si on avait un pléonasme de sauvegarde: en fermant la fenêtre ou en faisant Compute. C'est contre le comportement normal d'à peu près tout dans un ordi: rien n'est sauvé automatiquement surtout quand on ferme une fenêtre! Ce serait même plutôt le contraire. Je suggère donc qu'on revienne à l'ancien comportement qui consistait à appuyer sur Compute pour que les changements prennent effet. Et si l'utilisateur oublie cela, il reçoit un message d'erreur qui lui recommande d'appuyer sur Compute, à défaut de quoi les changements seront perdus.
Qu'en dites-vous?

**Comment by NicolaGiannini** [comment]
Je suis très d'accord !
Je me demande s’il ne serait pas encore plus clair si à la place de "Compute" on met "Save" dans la Speaker Setup Edition Window.
Et dans ce cas, si on n’appuie pas sur "Save" le message pourrait être celui que présentement on reçoit lorsqu'on ferme SpatGRIS sans avoir sauvegardé le Setup :

![Schermata 2022-08-02 alle 15 26 36](https://user-images.githubusercontent.com/35705913/182458130-71d05eac-974b-45f9-9cb3-3b0d126650a4.jpg)

**Comment by OKGougou** [comment]
Que diriez-vous de remplacer le bouton Compute par un bouton Apply qui appliquerait les changements et fermerait la fenêtre, comme pour les Settings? 
Et quand on ferme la fenêtre avec le X après qu’il y ait eu changements, il y aurait cet avertissement :

![CloseEditSpeakersWindow](https://user-images.githubusercontent.com/75331877/184153433-aecda020-100f-4973-b086-bb3928a9e142.png)

Le bouton Yes applique les changements et ferme la fenêtre sans sauver le Speaker Setup.
Le bouton No annule les changements et ferme la fenêtre.
Le bouton Cancel renvoie à la fenêtre d'édition des Speakers.

La sauvegarde du Speaker Setup se fait toujours par le menu File.

**Comment by Normandeau** [comment]
Je ne suis pas certain de cela. Quand on fabrique un Speaker Setup, on ne veut pas nécessairement que la fenêtre se ferme dès qu'on a positionné certains hp. On veut rendre le dispositif actif, mais tout en gardant la fenêtre ouverte. C'était l'idée derrière la fonction Compute.
Par contre, la fenêtre que tu proposes serait bienvenue si l'utilisateur ferme la fenêtre sans avoir fait Compute.
Actuellement, lorsque la fenêtre se ferme, la fonction Compute s'exerce en arrière-plan sans que l'utilisateur ne s'en rende compte. Et il semble que ce soit cette fonction qui soit boguée en ce moment. Le Save et le Compute, qui font la même chose, le font par deux entrées différentes et c'est probablement là que le problème se pose.
Compute dit bien ce que ça fait. Si on change des paramètres, ils ne sont pas actifs automatiquement, il faut les activer. Cependant, pour être cohérent avec la fenêtre que tu proposes, on peut remplacer Compute par Save, mais tout en laissant la fenêtre ouverte.

**Comment by OKGougou** [comment]
Pour info, le bug qui se manifeste ici n’est pas directement en lien avec la fonction Compute, mais a plutôt à voir avec un changement qui m’a échappé dans la dernière mise à jour de JUCE.

Pour clarifier, dans ma proposition, je pensais rendre la fonction Compute automatique lors d’un changement de paramètre. Le bouton Compute aurait donc été superflu. Pour l’instant, Compute actualise le speaker setup, mais ne l’enregistre pas sur disque. De ce que je comprends, on préfère avoir un bouton Save qui fait ce que le bouton Compute fait en plus d’enregistrer le speaker setup sur disque. Et c’est lorsqu’on n’a pas appuyé sur Save avant la fermeture de la fenêtre, et qu’il y a eu modification, qu’on reçoit la fenêtre d’avertissement.

C’est bien cela?

**Comment by Normandeau** [comment]
Ce qu'on veut c'est que lorsque l'on crée ou modifie un Speaker Setup, c'est de le vérifier au fur et à mesure. Actuellement, on doit appuyer sur Compute chaque fois qu'on fait une modification afin de la rendre active. Rendre la fonction Compute automatique au fur et à mesure de la fabrication d'un setup me semble effectivement l'idéal.
Le bouton Save ferait alors ce qu'on attend de lui, i.e. de sauver le setup sur disque (toujours sans fermer la fenêtre). Si l'utilisateur l'oublie au moment de fermer la fenêtre d'édition, l’avertissement apparaît alors.
Fiou, on va y arriver. Merci pour l'amélioration!

**Comment by NicolaGiannini** [comment]
Je suis d’accord ! 

Robert :
> Rendre la fonction Compute automatique au fur et à mesure de la fabrication d'un setup me semble effectivement l'idéal.
> Le bouton Save ferait alors ce qu'on attend de lui, i.e. de sauver le setup sur disque (toujours sans fermer la fenêtre). Si l'utilisateur l'oublie au moment de fermer le setup, la fenêtre d’avertissement apparaît alors.

**Comment by MelanieFrisoli** [comment]
Je suis d'accord aussi pour rendre la fonction Compute automatique ! 
(Je me demandais ce qu'il se passait, SpatGRIS plantait souvent quand je jouais dans le speaker setup)

**Comment by Normandeau** [comment]
V3.1.13
Le problème semble réglé. Et on a bien une mise à jour qui se fait automatiquement quand on change une valeur (ancienne fonction Compute). Un bouton Save qui sauve le fichier. Et une fenêtre d'avertissement quand on oublie de sauvegarder.

**Comment by Normandeau** [comment]
Aucun plantage après plusieurs essais.

**Comment by NicolaGiannini** [comment]
Aucun plantage non plus dans mon cas. La fonction Save dans la Speaker Setup Window est très utile. Je me demande s'il serait utile d'avoir aussi un bouton "Save as" aussi. Actuellement si on modifie un Setup customisé, on peut seulement enregistrer le fichier courant et on ne peut pas créer un nouveau fichier. Par contre, si on modifie un template, on peut créer un nouveau fichier.

**Comment by MelanieFrisoli** [comment]
V3113

Aucun plantage aussi sur le M1.
Je seconde également ce que dit Nicola, un Save As serait pratique.
