### ISSUE TITLE
Speaker Setup Edition, il n'est pas possible d'ajouter un Ring avec des valeurs d'Elevation entre 360 et 270

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#355]
V 3.1.12
Il semble que le problème des valeurs négatives d'Elevation/Z soit maintenant résolu. Sauf qu'on ne peut pas ajouter de Ring avec des valeurs entre 270 et 360  car Speaker Setup Edition ne permet pas d'utiliser ces valeurs d'Elevation qui est le seul paramètre disponible en mode Add Speaker.
1. Ajustement automatique à 90 comme valeur maximale en mode Dome
Quand on entre une valeur entre 360 et 270 (270 étant le minimum en bas complètement de la sphère), elle est automatiquement ajustée à 90. On peut ensuite corriger ces valeurs manuellement, mais c'est plutôt fastidieux.
2. Ajustement automatique à 90 comme valeur maximale en mode Cube
Comme avec le mode Dome, quand on entre une valeur entre 360 et 270 (270 étant le minimum en bas complètement de la sphère), elle est automatiquement ajustée à 90. On ne peut cependant modifier cette valeur avec le paramètre Elevation, car la valeur minimale est 0 en ajustement manuel. Si on veut aller en dessous de l'horizon, il faut utiliser le paramètre Z en mode Cube. Quand on fait cela, l'Elevation s'ajuste automatiquement avec des valeurs entre 360 et 270, qu'on peut modifier tant qu'on ne dépasse le 0. Si on le fait, on est à nouveau bloqué à 0.

Il y a donc beaucoup d'incohérence ici quant au placement des hp en bas de l'horizon.
1. La première est le fait de devoir toujours positionner les hp avec le paramètre Elevation, même en mode Cube.
2. Ne devrait-on pas pourvoir le faire en mode X, Y, Z en mode Cube.
3. On devrait pouvoir mettre les valeurs en dessous de l'horizon quelque soit le mode et/ou le paramètre utilisé

**Comment by NicolaGiannini** [comment]
Je confirme et je suis d’accord avec Robert. 
Pour le mode DOME on devrait être en mesure d’insérer des valeurs entre 360 et 270 pour l’élévation. 

Toujours pour le mode DOME, je me demande si, en général, il est utile de donner la possibilité d'utiliser aussi XYZ puisque les haut-parleurs ne peuvent être placés que sur la surface du dôme. Cela signifie qu'il existe certaines combinaisons de XYZ qui ne sont pas possibles sur un dôme.

Quant au mode CUBE, je propose une réflexion.  En plus de la possibilité de construire un ring, il pourrait être utile d'avoir aussi la possibilité de construire un rectangle/carré ? On pourrait penser à une fonction permettant de créer un rectangle à la suite de l'indication d'un point en coordonnées XYZ (début du rectangle) et du nombre de haut-parleurs par côté. Cela dit, je me demande si c'est vraiment important et utile d'avoir une fonction de ce type.

**Comment by Normandeau** [comment]
Je suis d'accord avec la possibilité de permettre d'ajouter au moins un carré, plutôt que seulement un cercle en mode Cube. Ça fait longtemps que je me retiens à ce sujet!!! Mais puisque cela vient de quelqu'un d'autre, je seconde.
En fait on revient à la quadrature du cercle. Il est peut-être temps de régler le fait que la fenêtre Speaker Setup Edition est actuellement fonctionnelle uniquement en mode Dome.

**Comment by OKGougou** [comment]
Est-ce que je dois comprendre, en mode Dome, qu'il serait préférable de permettre la modification des paramètres d'azimut et d'élévation et d'empêcher la modification des coordonnées XYZ ? Et inversement pour le mode Cube (permettre la modification XYZ et empêcher azimut et élévation) ?

Et la possibilité d'ajouter un carré en mode Cube vient-elle remplacer l'ajout d'un cercle ? Ou préfère-t-on garder la possibilité d'ajouter un cerle ?

**Comment by Normandeau** [comment]
«Est-ce que je dois comprendre, en mode Dome, qu'il serait préférable de permettre la modification des paramètres d'azimut et d'élévation et de limiter la modification des coordonnées XYZ ? Et inversement pour le mode Cube (permettre la modification XYZ et limiter azimut et élévation) ?»

Exact

«Et la possibilité d'ajouter un carré en mode Cube vient-elle remplacer l'ajout d'un cercle ? Ou préfère-t-on garder la possibilité d'ajouter un cercle ?»

Cercle pour le Dome.
Carré pour le Cube

**Comment by Normandeau** [comment]
L'idée derrière cela est de faire disparaître l'omniprésence du dôme dans cette fenêtre d'édition. On voit bien que lorsque qu'on fabrique un cube, dans les faits c'est un dôme carré qu'on dessine! Déjà si on pouvait faire un carré de hp, au lieu d'un cercle (qu'on pourra ensuite modifier) ce serait bien. Et surtout, si on pouvait donner suite à l'issue GRIS-UdeM/SpeakerView#46, qui permettrait de draguer les hp directement dans la fenêtre 3D avec la souris, souhait formulé en août... 2017, ce serait encore mieux. La première version du Zirkonium, publié en 2007, permettait déjà de faire cela...

**Comment by OKGougou** [comment]
Et qu'en est-il pour le paramètre de la distance ? Pour l'instant, il est modifiable en mode Cube et pour un speaker en sortie directe en mode Dome. Il me semble qu'il ne devrait pas être modifiable en mode Cube, non ?

**Comment by Normandeau** [comment]
Exact.

**Comment by NicolaGiannini** [comment]
Je suis d'accord sur tout. Je vous propose une reflexion en ce qui concerne les coordonnes en mode CUBE.

Je me demande si ça pourrait être pratique en mode CUBE de garder la possibilité d'insérer/modifier azimuth/elevation/distance. Je pense par exemple à la possibilité de recevoir de telles coordonnées d'une salle de concert (bien sûr, si les coordonnées fournies sont azimut/élévation/distance, il est peut-être plus probable que le dispositif soit un dôme). En gros, toute combinaison d'azimuth/distance/elevation semble possible en mode CUBE.

Je dis cela aussi parce que maintenant, de ce que je comprends, les paramètres Elevation et Distance ont le même comportement en mode CUBE et en mode DOME, alors que dans le passé ces paramètres avaient des comportements différents dans les deux modes (https://github.com/GRIS-UdeM/SpatGRIS/issues/169). D'ailleurs, suite à ce changement, on pourrait peut-être enlever la phrase "Elevation and Distance do not have the same behaviour in the DOME and CUBE algorithms." dans le paragraphe "5.5.3. Converting from DOME to CUBE and vice versa" du manuel.

**Comment by MelanieFrisoli** [comment]
Je suis aussi d'accord avec tout.
(Et je trouve super les idées de pouvoir ajouter un carré au lieu d'un Ring en mode Cube, ainsi que celle de réserver X,Y, Z pour Cube et Élévation/Azimuth pour Dôme. Je rêve que ControlGRIS fonctionne également de cette façon, mais c'est un autre sujet)

Je pose juste ici une mini-suggestion qui pourrait peut-être simplifier les choses pour l'utilisateur·trice lors la création de speaker setup avec des speakers en-dessous du plancher. Ne serait-il pas plus compréhensible de pouvoir placer des haut-parleurs avec des valeurs d'élévation entre 0° et -90° ? (au lieu de 360° à 270° - je comprends bien l'idée trigonométrique derrière tout ça, mais comme on ne permet pas de valeurs entre 90° et 270°, je crois que, pour certain·e·s, cela pourrait être plus clair). Après tout, Z fonctionne de -1 à 1.

Et pour rejoindre Nicola, ce serait en effet pratique de garder la possibilité d'insérer/modifier azimuth/elevation/distance pour le mode CUBE, au cas où nous ferions un dispositif non-conventionnel qui mélangerait Dôme et coordonnées X,Y,Z.

Ou bien, pouvoir disposer du mode Hybrid pour créer ce genre de speaker setup particulier ! (pour l'instant, le mode Hybrid permet uniquement de placer les haut-parleurs sur le surface du dôme - je comprends que ce mode est destiné (pour l'instant?) au déplacement des sources uniquement).

**Comment by Normandeau** [comment]
V 3.1.13
Valeur possibles maintenant entre 270 et 360.
Ajout d'un carré à venir.

**Comment by Normandeau** [comment]
Speaker Setup Edition
Les valeurs d'édition en mode Dome sont bien Azimuth-Elevation. Et en mode Cube, X, Y, et Z. 
Les autres sont grisées.

**Comment by Normandeau** [comment]
Voir GRIS-UdeM/SpatGRIS#364 pour la suite
