### ISSUE TITLE
PlayerGRIS: Le fichier xml du Speaker Setup d'origine n'est pas sauvegardé au bon endroit

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#356]
V 3.1.12
PlayerGRIS: Le fichier xml du Speaker Setup d'origine n'est pas sauvegardé au bon endroit. Il est plutôt sauvegardé dans le dossier précédent celui des Audio Files alors qu'il devrait être dans le même dossier. Par exemple je crée un dossier nommé PlayerGRIS dans lequel il y a plusieurs dossiers nommés Test (1, 2, 3, 4, etc). Les fichiers audio sont bien sauvegardés dans les dossiers Test mais le Speaker Setup est sauvegardé dans le dossier PlayerGRIS. Or ils ont besoin d'être ensemble pour que le PlayerGRIS fonctionne bien. Sinon, on reçoit cet avertissement:

![Avertissement Speaker absent](https://user-images.githubusercontent.com/8959779/183293114-0c264335-e64b-432e-95ea-defe472bb887.jpg)

**Comment by NicolaGiannini** [comment]
Je confirme

**Comment by Normandeau** [comment]
V 3.1.13
Réglé
