### ISSUE TITLE
PlayerGRIS fonctionne plutôt bien

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#357]
V 3.1.12
J'ai fait une série de tests avec le PlayerGRIS. Tous (presque) réussis avec succès.
1. Dome à Dome
Dome32(4X8)Subs2 Twisted spiral à Dome16(8-6-2)Subs2
OK
2. Cube à Cube
Cube31(8-15-8)Subs1 SARC à Cube24(3X8)Subs2
OK
3. Dome à Cube
Dome(8-6-4-2)Subs4 Icosa à Cube24(3X8)Subs2
OK, sauf que les numéros des sources originelles sont remplacés par une série d'un ordre croissant qui commence par 1. Je fais une autre issue à ce sujet.
4. Cube à Dome
Cube31(8-15-8)Subs1 SARC à Dome(8-6-4-2)Subs4 Icosa
OK

Voici comment le Dome d'Icosa se présente dans le Cube24. Convaincant non?
![Dome(8-6-4-2)Subs4 Icosa à Cube24(3X8)Subs2](https://user-images.githubusercontent.com/8959779/183293328-d6aef16d-c2b8-4eb9-9913-70c216c41ece.jpg)

Et comment les 4 subs d'Icosa sont distribués dans les 2 subs de Cube 24. Une belle réussite!
![Répartition des suns Icosa](https://user-images.githubusercontent.com/8959779/183293369-c5fa0468-fbf6-4f3e-a408-36cdaf659c4c.jpg)

Enfin voici comment le Cube du SARC est reproduit dans le Dome Icosa.
![Cube31(8-15-8)Subs1 SARC à Dome(8-6-4-2)Subs4 Icosa](https://user-images.githubusercontent.com/8959779/183293458-7a855f95-ce5b-4aec-92cd-d7445d4546b2.jpg)

Il y aura sûrement plus de tests à faire, notamment au sujet des sorties directes autre que les subs.

**Comment by NicolaGiannini** [comment]
Je viens de faire des tests et ça fonctionne très bien ! Excellent !

Voici le setup de Sporobole dans l'hexa. Parfait !

![Schermata 2022-08-16 alle 12 41 22 PM](https://user-images.githubusercontent.com/35705913/184954426-0550a23b-a707-4fed-8b2d-2eadb7600be9.jpg)


J'ai fait des tests en ce qui concerne les sorties directes.

Dans le cas des sorties directes indépendantes, de ce que je comprends SpatGRIS place les sorties directes du setup original sur les sorties directes disponibles dans le setup utilisé par le player. Les affectations sont effectuées par ordre numérique croissant.
Notamment les sorties directes 18, 19, 20, 21 (original), seront mises en correspondance avec les hp d'Icosa comme ça :
18 (original) = 6 (Icosa)
19 (original) =14 (Icosa)
20 (original) = 22 (Icosa)
21 (original) = 30 (Icosa)

S'il y a moins de sorties directes dans le lecteur que dans la configuration originale, comme indiqué par Robert les sorties directes originales sont distribuées sur celles du lecteur. 

Je signale une chose.

SpatGRIS3 pour les assignations considère l’ordre numérique croissant et non la position des sorties directes originales.

Si, par exemple, toutes les sorties directes originales sont à droite, elles seront placées par le lecteur à droite et à gauche si la configuration utilisée par le lecteur a des sorties directes des deux côtés.
Voici un exemple :

![Schermata 2022-08-16 alle 2 42 09 PM](https://user-images.githubusercontent.com/35705913/184954981-28398ac5-9d50-4b5a-80ab-8beb13d5dd57.jpg)

La position des sorties directes originales est affichée avec la couleur rouge foncé.

Dans tous les cas, il est expliqué dans la fenêtre du lecteur que SpatGRIS tentera d'attribuer des sorties directes, mais que certains ajustements devront peut-être être effectués.

**Comment by Normandeau** [comment]
Oui je pense qu'il faut ajouter une fonction dans le Player qui permettent d'assigner les sorties directes manuellement. Car une sortie indépendante, destinée au sub et une sortie directe spatialisée ne correspondent pas à la même fonction musicale.

**Comment by NicolaGiannini** [comment]
Si je comprends bien, les **sorties directes spatialisées** (Spatialized direct outputs) permettent d'envoyer une source vers un HP qui fait partie de la spatialisation. En fait, c'est comme si nous placions une source aux coordonnées d'un HP via ControlGRIS. Lorsque le lecteur recrée la configuration d'origine dans le setup de lecture, il crée des sources à la position des HP, qui est donc aussi la position des sorties directes spatialisées. Dans ce cas, pensez-vous qu'il soit nécessaire de donner l'option d'une affectation manuelle ? 

De ce que je comprends, le lecteur assigne les **sorties directes indépendantes** (rouge foncé - Independent direct outputs) du setup original aux sorties directes disponibles dans le setup utilisé par le player. Le lecteur considère l’ordre numérique croissant et non la position des sorties directes originales pour ces assignations. Après ces assignations faites par le lecteur, on peut assigner ces sorties directes indépendantes à n'importe quel HP du setup utilisé par le lecteur, y compris les sorties directes, en modifiant le projet.

Je me demande s'il ne serait pas intéressant d'ajouter une option permettant de transformer ce qui était une sortie directe indépendante dans le setup original vers une source normale dans le lecteur.
L'utilisateur pourrait donc avoir trois choix en ce qui concerne les sorties directes indépendantes :

- Utiliser l'assignation proposée par le lecteur (c'est déjà le cas).
- Modifier cette assignation en envoyant le signal vers un autre HP du setup du lecteur (c'est déjà le cas)
- La sortie directe originale ne serait pas envoyée à un HP en particulier, mais elle serait traitée comme un HP original qui fait partie de la spatialisation. La sortie directe originale serait donc reproduite à sa position originale et par plusieurs HP selon le mode utilisé.

Qu'en pensez-vous ?

Cette option pourrait être utile lorsque dans la configuration d'origine certaines sorties directes indépendantes sont utilisées non pas pour des subs mais pour d'autres signaux, et que leur position est en quelque sorte significative. 

![Schermata 2022-08-16 alle 2 42 09 PM](https://user-images.githubusercontent.com/35705913/185428069-bc9c71c4-55e9-4121-ba93-b6728e4704c6.jpg)

Par exemple, dans ce cas, je pourrais vouloir transformer les sorties directes indépendantes en sources. Je pense également aux cas où il n'y a pas de sorties directes dans le setup du lecteur.
Cela dit, peut-être s'agit-il de cas très rares ?

Après avoir pensé à cela je me suis alors demandé si c'était possible de reproduire des sources positionnées en dehors des hp en mode DOME (vu qu'on peut positionner les sorties directes aussi en dehors du dôme). La réponse est oui. En fait, Robert montre dans ses exemples comment comment on peut recréer un setup CUBE qui a des hp qui sortent du setup DOME dans lequel il est recréé. 

J'ai fait moi aussi des tests visuels (que je vais valider en studio).
J'ai essayé de reproduire dans un setup dôme une source positionnée dans un coin extrême du setup Cube8(2x4)subs2 big. Et apparemment (visuellement), ça fonctionne. 

Source positionnée sur le hp 8 qui est en haut à gauche et à l'arrière du Cube8(2x4)subs2 big:
![Schermata 2022-08-18 alle 10 33 16 AM](https://user-images.githubusercontent.com/35705913/185428486-56e38586-06e7-4f8a-ad7e-1102a12830e7.jpg)

Même source reproduite par le setup DOME de l'Hexa:
![Schermata 2022-08-18 alle 10 38 12 AM](https://user-images.githubusercontent.com/35705913/185428558-92f72d31-c868-48e9-b863-f634b250e100.jpg)

Le player semble donc rendre possible la reproduction d'une source positionnée en dehors du DOME.

**Comment by Normandeau** [comment]
«La sortie directe _indépendante_ originale ne serait pas envoyée à un HP en particulier, mais elle serait traitée comme un HP original qui fait partie de la spatialisation. La sortie directe originale serait donc reproduite à sa position originale et par plusieurs HP selon le mode utilisé.»
Cette phrase est vraiment difficile à comprendre. 
Je pense que ça demande à couvrir trop large pour l'objectif du _Player_ qui est de permettre la circulation des œuvres. Si un dispositif original comporte beaucoup de sorties directes indépendantes, c'est peut-être à l'utilisateur de réorganiser son matériel afin de pouvoir le diffuser sur un autre dispositif. L'utilisateur récepteur pourra toujours ajouter des hp correspondants à celles-ci si nécessaire. 
Mais je ne crois pas que le _Player_ puisse répondre à toutes les situations imaginables. On ne sera jamais capable d'en sortir une version à peu près utilisable!
