### ISSUE TITLE
PlayerGRIS: les numéros des sources originelles sont remplacés par une série d'ordre croissant commençant par 1

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#358]
V 3.1.12
Lorsqu'on fait un enregistrement avec SpatGRIS3, les numéros originaux des sources sont reproduits dans le nom des fichiers enregistrés. Par exemple dans Icosa, constitué de 24 hp, les numéros sont échellonnés de 1 à 30 en omettant les deux derniers chiffres de chaque groupe de 8 (7-8, 15-16, 23-24 et 31-32). Les subs portent les numéros 6, 14, 22 et 30 (ce sont en fait 4 systèmes 5.1).
Lorsqu'on **lit un enregistrement** avec PlayerGRIS, donc réalisé avec l'option Export Speaker Setup, les numéros originaux des sources sont remplacés par une série ascendante commençant à 1. Dans ce cas particulier, elle s'arrête à 24.
Test confirmé avec le Speaker Setup du B187 (5-6, puis 31 à 62).

Série originelle Icosa:
![Série originelle Icosa](https://user-images.githubusercontent.com/8959779/183294459-45803a8d-5785-4aa1-810c-20e926d18a22.jpg)

Série reproduite par PlayerGRIS:
![Répartition des subs Icosa](https://user-images.githubusercontent.com/8959779/183294502-fab362b7-02df-4bd8-8f81-ba71758850d2.jpg)

Si on reproduit l'enregistrement réalisé sur Icosa sur le dispositif Icosa, on se retrouve donc devant des fichiers qui porte des numéros différents, rendant impossible toute  vérification ou toute détection d'erreurs (en noir les numéros originaux, en rouge les numéros de PlayerGRIS):
![Icosa vs PlayerGRIS](https://user-images.githubusercontent.com/8959779/183294669-b6f70ebf-32d9-4d8e-93f8-841a7ddd3d1c.jpg)

Dans des dispositifs complexes, cela peut amener pas mal de confusion. Je suggère donc de corriger cela, si possible.

**Comment by NicolaGiannini** [comment]
Je confirme et je suis d'accord avec Robert.

**Comment by Normandeau** [comment]
V 3.1.13
Les numéros d'origine sont bien conservés. Et les sources vides sont grisées et mutées. C'est très clair.
Réglé.
