### ISSUE TITLE
PlayerGRIS : le nom du projet ouvert par le Player devrait remplacer le projet courant

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#359]
V3.1.12
PlayerGRIS : lors du chargement du dossier avec les fichiers et le Speaker Setup, le projet ouvert est remplacé par celui créé par le player. Ce comportement est correct en ce qui concerne le player. 

Cela dit, je me demande si nous ne devrions pas informer  de ce changement (ou mettre une note dans le manuel). 

Lorsque le lecteur est fermé, le projet ouvert reste celui créé par le lecteur mais avec le nom du projet qui était ouvert avant le chargement du dossier du player.

Exemple
Projet sur lequel je travaille: 
![Schermata 2022-08-19 alle 2 00 32 PM](https://user-images.githubusercontent.com/35705913/185679844-bbddf54e-8ce5-435f-8187-c64cf65de63f.jpg)

Projet créé par le player, le nom reste le même:
![Schermata 2022-08-19 alle 2 01 08 PM](https://user-images.githubusercontent.com/35705913/185679823-7842d76f-ffee-41a7-a514-93d4f8e05597.jpg)

Il y a un autre fait. Si, avant de charger le dossier dans le player, on modifie le projet sur lequel on travaille, lorsque SpatGRIS crée le projet du player il ne demande pas si on veut enregistrer les changements au projet précédent.

**Comment by Normandeau** [comment]
1. Le nom du projet qui s'ouvre avec le Player devrait être celui qui s'affiche. Autrement dit, le nom du projet courant devrait être remplacé exactement comme lorsqu'on change de projet.
2. Cette amélioration devrait corriger la situation de la sauvegarde. Actuellement, SpatGRIS demande si on veut sauver les changements apportés, soit en le fermant, soit en ouvrant un autre projet. Il ne serait pas très prudent d'apporter des changements au projet avant d'ouvrir le Player...

**Comment by NicolaGiannini** [comment]
Je suis d'accord ! Comme nom du projet créé par PlayerGRIS, SpatGRIS pourrait utiliser automatiquement le nom du dossier qui est chargé dans le lecteur ?

**Comment by Normandeau** [comment]
V 3.1.13
Le nom du projet du Player remplace celui qui était ouvert. Si des modifications avaient été faites à celui-ci, il nous demande si on veut les sauvegarder, comme lorsqu'on change de projet. 
Réglé
