### ISSUE TITLE
PlayerGRIS : l'utilisation d'un fichier interfolié génère une erreur

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#360]
V3.1.12

Player : l'utilisation d'un fichier interfolié génère une erreur. Si on essaye de charger un dossier qui contient un enregistrement sauvegardé dans un fichier interfolié on reçoit ce message d'erreur. Probablement parce que le player voit un seul ficher. 

![Schermata 2022-08-19 alle 2 18 58 PM](https://user-images.githubusercontent.com/35705913/185683262-3d2cf5d7-9391-4ab0-9b61-445bb48ab878.jpg)

**Comment by Normandeau** [comment]
Comme on veut conserver les numéros d'identification des pistes, continus ou discontinus, et que cette information ne se retrouve pas dans un fichier interfolié, ce comportement est normal. Il faut juste le spécifier dans le manuel, dans le nouveau chapitre sur le Player.

**Comment by Normandeau** [comment]
V 3.1.13
C'est dans le manuel de 3.2
