### ISSUE TITLE
Messages à la première ouverture de SpatGRIS v3.1.12 sous M1

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#362]
V3.1.12.
Macbook Pro M1 - Os Monterey

Quand j'ouvre SpatGRIS pour la première fois après l'avoir téléchargé (ou qu'il plante sans avoir rien sauvegardé), j'ai ce premier message : 

<img width="1277" alt="Screen Shot 2022-08-30 at 3 58 02 PM" src="https://user-images.githubusercontent.com/74631914/187550330-048591d7-ce78-433f-ad4d-729d316ad1b9.png">

Je clique sur "ok" et j'obtiens ce deuxième message : 

<img width="1281" alt="Screen Shot 2022-08-30 at 3 58 08 PM" src="https://user-images.githubusercontent.com/74631914/187550405-6b09f6c7-c87b-4161-a0cc-b40c15ecc14a.png">

J'ai vérifié dans les "Contents" et j'y ai pourtant bien vu les fichiers que SpatGRIS recherche : 

<img width="1290" alt="Screen Shot 2022-08-30 at 5 23 25 PM" src="https://user-images.githubusercontent.com/74631914/187550513-b1c20c69-b7b1-4a75-9ec5-890eaefbfdff.png">

**Comment by Normandeau** [comment]
Bogue avec M1? Sur Intel, sous Monterey 12.5.1, je n'ai jamais eu ces messages.

**Comment by Normandeau** [comment]
On attend la sortie du nouveau Mac Mini M2. On pourra tester plus régulièrement ensuite.

**Comment by MelanieFrisoli** [comment]
V3113

Aucun message d'erreur à la première ouverture de cette nouvelle version de SpatGRIS avec mon MacBook Pro M1.

**Comment by Normandeau** [comment]
Réglé pour le moment.
