### ISSUE TITLE
Cube: Intensité incohérente sur le plan vertical au centre d'un cube vide

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#365]
V 3.1.13
Fichier mono, bruit blanc, niveau nominal
Position au centre, déplacement vertical

Cube20Icosa en mode Cube
En haut, seuls les deux hp du haut fonctionnent. Puis en descendant, les «étages» s'activent et à la fin, en bas complètement, tous les hp fonctionnent pratiquement à la même amplitude. On a donc perdu les couches (layers) avec MBAP, mais on a aussi perdu la localisation! Est-ce dû au fait que les hp se rapprochent de plus en plus du centre vers le haut?
On a donc toujours une référence au centre bas pour le calcul de l'intensité, n'est-ce pas un rappel du dôme... en mode Cube!

https://user-images.githubusercontent.com/8959779/189499170-20301f3d-5e07-4d58-9e84-903a00efd255.mov

Cube24Cylinder
On constate un meilleur étalement de l'intensité entre les trois couronnes de 8 hp. La postion Z des hp est ici à 0.0, 0.5 et 1.0 (légèrement modifié par rapport au Template). 

https://user-images.githubusercontent.com/8959779/189498522-e6cbd622-9e9d-4b73-87f2-e9ee0fc0e10d.mov

On constate des différences d'intensité selon la position verticale de la source: 
Source en haut (Z à 1.0):
• 1.0: -24dB; 0.5: -48dB; 0.0: 0dB
Source au milieu (Z à 0.50):
• 1.0: -30dB; 0.5: -24dB; 0.0: -42dB
Source en bas (Z à 0.0):
• 1.0: 0dB; 0.5: -36dB; 0.0: -18dB

Je me serais attendu à une valeur de -24dB à 0.0 lorsque la source est en bas. Histoire d'être cohérent, puisque le dispositif est un cylindre et que les hp sont équidistants. C'est la valeur qu'on lit lorsque la source est en haut ou au milieu.

**Comment by Normandeau** [comment]
V 3.1.13
Fichier mono, bruit blanc, niveau nominal
Position au centre, déplacement vertical

Cube62MMR
Trois couronnes de hp: 0.0, 0.60 et 0.95

https://user-images.githubusercontent.com/8959779/189499426-29b8f098-b113-4ce0-8429-13a30c509003.mov

On touche à peine à la couronne centrale. Je ralentis sciemment pour illustrer le phénomène. C'est seulement quand on rendu presque complètement en bas que les hp à 0.60 s'allument. Pas certain que sur le plan perceptif, dans le MMR, la localisation verticale soit très convaincante (mais peut-être que oui, car je ne peux me fier qu'à ce que je vois).

**Comment by Normandeau** [comment]
Fichier mono, bruit blanc, niveau nominal
Position au centre, déplacement vertical

Cube124Cube Virginia
Ne reculant devant rien, la direction vous offre le top, Virginia Tech 124 (l'image est vraiment large, ça ne rentre même pas dans mon écran 4k!)!

https://user-images.githubusercontent.com/8959779/189499750-e68d56cf-4bc3-4928-931b-baf140f8f5a6.mov

Je voulais vérifier si le fait d'avoir 4 niveaux, contrairement aux 3 du MMR, donnait une meilleure répartition du signal entre les différents étages. Mais on constate que celui-ci touche peu au 3e niveau et ne rejoint le 2e pratiquement qu'en même temps qu'au premier.

**Comment by NicolaGiannini** [comment]
Je confirme tout ce que Robert décrit.

Je pense que le nouvel algorithme calcule l'intensité selon la distance entre une source et les HP. Je pense qu'il s'agit d'une distance absolue calculée de la même manière que le paramètre Distance dans la Speaker Setup Edition. Dans la Speaker Setup Edition la distance est celle entre le centre et les HP.

Notamment si en mode CUBE on utilise un dôme parfait, quand la source est en bas et exactement au centre, tous les hp ont exactement le même niveau parce que tous les hp sont à la même distance du centre, où la source se trouve.

Vidéo de l'Hexa avec une source au centre à 1, 0,5 et 0 en Z :


https://user-images.githubusercontent.com/35705913/189502682-bb5b5586-bf59-4d4e-85f7-3b1201c8cfda.mov

Si nous prenons le cas du MMR, lorsque la source au centre est à élévation = 0,6, bien que la source soit exactement à la même hauteur que les haut-parleurs, la source est probablement encore plus proche, en termes absolus, des haut-parleurs au sommet.

![Schermata 2022-09-10 alle 17 17 23](https://user-images.githubusercontent.com/35705913/189502690-6669bac8-c7aa-46c0-aaf3-b902476f9035.jpg)

Lorsque la source au centre est à l'élévation 0, on remarque par exemple que le haut-parleur 52 qui est positionné dans la couronne la plus haute a une intensité plus élevée que le haut-parleur 41 qui est situé plus bas. Dans la Speaker Setup Edition du MMR, on voit que l'HP 52 est à une distance de 0,97 tandis que l'HP 41 est à une distance de 1,19.

![Schermata 2022-09-10 alle 17 19 06](https://user-images.githubusercontent.com/35705913/189502705-f7c6c6f6-6d0a-4f57-a7eb-eec668e55f4a.jpg)

**Comment by Normandeau** [comment]
Merci Nicola.
Cela nous ramène à l'issue #165 décrite en...2019!
Peut importe l'algorithme utilisé (DBAP, LBAP, MBAP), aucun d'entre eux n'est arrivé, à ce jour, à assurer d'un seul coup un comportement acceptable au centre dans un cube. Car cela dépend de deux facteurs principaux:
- emplacement des hp en fonction d'un niveau de référence: où est-il? Comment l'éloignement de celui-ci se comporte-t-il?
- dimensions réelles du lieu de diffusion: impossible à programmer puisque les valeurs dans SpatGRIS3 sont abstraites et virtuelles et non pas réelles.

On peut toujours essayer de modéliser le cube MMR, les réglages programmés ne seront plus valides au SARC ou à Virginia Tech, deux autres cubes réels. Il nous faut donc un réglage manuel d'atténuation/augmentation de l'intensité au centre du dispositif! Comme les hp sont la plupart du temps disposés sur les murs, donc loin du centre, il faut qu'on puisse ajuster le niveau manuellement afin de compenser cette distance, dictée par l'algorithme.
Deux réglages potentiels:
- intensité au centre en ± ndB.
- courbe d'atténuation/augmentation en ndB/distance par rapport aux HPs. Ce réglage permettra de conserver l'équilibre sur les murs de bas en haut.

On a hâte de tester cela...

**Comment by Normandeau** [comment]
Bonne discussion avec Gaël aujourd'hui à ce sujet. Une hypothèse de solution est en cours. À suivre dans votre journal préféré.

**Comment by DavidPiazza** [comment]
Voici les résultats de mes essais préliminaires avec le MBAP. J'ai effectué ces tests sur le speaker setup Cube124(64-20-20-20)Sub2 de Virginia Tech.

Pour une onde sinusoïdale à 440 Hz, à -6 dBFS en mono, placée au centre du cube, je montre successivement 4 déplacements verticaux : 

1. Azimuth span à 0%, Elevation span à 0%;
2. Azimuth span à 100%, Elevation span à 0%;
3. Azimuth span à 0%, Elevation span à 100%;
4. Azimuth span à 50%, Elevation span à 50%.

Les mêmes manipulations sont effectuées pour : 

- v3.1.13 (ancien algorithme);

https://user-images.githubusercontent.com/50223477/191624003-286a1262-00ee-4724-867f-9e9e651fb724.mp4

- v3.1.14 avec le Global Sound Diffusion à 0%;

https://user-images.githubusercontent.com/50223477/191624513-e27a7c92-dee8-468d-bd14-a8c8affdcb5e.mp4

- v3.1.14 avec le Global Sound Diffusion à 50%;

https://user-images.githubusercontent.com/50223477/191624570-60726619-a1dd-4a3d-8142-01e97c515bc0.mp4

- v3.1.14 avec le Global Sound Diffusion à 100%;

https://user-images.githubusercontent.com/50223477/191624618-9e94cfcc-534c-446e-8a5d-d2f25725d6c5.mp4

N'ayant moi-même jamais travaillé en mode cube, j'ai peu de référents pour déterminer l'efficacité sur le plan de la perception auditive du Global Sound Diffusion. Chose certaine, avec une valeur de 100%, l'ensemble des haut-parleurs s'activent et je présume qu'une valeur aussi élevée affecterait négativement la localisation. Des tests sur d'autres setups en mode cubes et avec des sources différentes restent à faire pour déterminer une sorte de « sweet spot ».

**Comment by Normandeau** [comment]
V 3.1.14
Lorsqu'on combine le Azimuth Span, même avec des valeurs petites, avec le nouvel algorithme MBAP, on réussit à obtenir une soucoupe sonore qui n'affecte que le groupe de hp sur le même niveau. Belle réussite.
Cependant comme on peut le voir dans la vidéo suivante, la sensibilité des niveaux de sortie des hp est beaucoup trop élevée par rapport aux modifications de X et de Y de ControlGRIS. Notez ici une variation importante des niveaux (± 4dB) pour une variation 0.01 de X ou de Y ou des deux combinés.

https://user-images.githubusercontent.com/8959779/191816156-4bd444eb-c699-4512-9023-c741c93f7a0a.mov

**Comment by NicolaGiannini** [comment]
Robert : 

> Cependant comme on peut le voir dans la vidéo suivante, la sensibilité des niveaux de sortie des hp est beaucoup trop élevée par rapport aux modifications de X et de Y de ControlGRIS. Notez ici une variation importante des niveaux (± 4dB) pour une variation 0.01 de X ou de Y ou des deux combinés.

Je confirme cela. 


Note : j'ai déplace le reste de ce commentaire dans le nouveau issue https://github.com/GRIS-UdeM/SpatGRIS/issues/369

**Comment by Normandeau** [comment]
V320
Même chose pour la nouvelle issue #373
