### ISSUE TITLE
Speaker Setup Edition: disparition des messages quand on efface tous les hp (mode Dôme & Cube): sur M1 seulement

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#366]
V3112 & 3113

Je remarque la disparition du message "Dome needs at least 3 speakers" lorsque l'on efface les derniers hp dans la fenêtre de Speaker Setup Edition. Est-ce que c'est quelque chose de voulu ? 

<img width="375" alt="Screen Shot 2022-09-12 at 8 16 42 AM" src="https://user-images.githubusercontent.com/74631914/189651590-8ba341c4-6258-470c-aece-1ec13d7ab5fa.png">

**Comment by Normandeau** [comment]
V 3.1.13, macOS 12.6 (mise à jour hier)
Je reçois tous les messages de mon côté:
- Dome min 3 speakers
- Cube min 2 speakers
-  y compris un que je ne n'avais pas vu avant:

![Dome 170 apart](https://user-images.githubusercontent.com/8959779/190006974-c4533414-91de-458c-a97a-9d63032749ce.jpg)

Autre problème M1?

**Comment by NicolaGiannini** [comment]
V31.13 macOS 12.6 
Moi aussi je reçois les messages : 

- Dome min 3 speakers
- Cube min 2 speakers. 

Je n'arrive pas à avoir le message posté par Robert, mais il me semble de l'avoir déjà vu.

**Comment by Normandeau** [comment]
Oui, je suis privilégié et j'ai des messages exclusifs et secrets!
C'est qu'il faut être doué pour faire planter SpatGRIS3! Tu prends Dome10(8+2)Subs2, tu enlèves les hp 9 et 10, puis les hp 7 et 8, et ensuite, le hp 5, et bingo! Parce les hps résultants sont plus éloignés de 170˚.

**Comment by Normandeau** [comment]
Avec l'image:

![Disable 170](https://user-images.githubusercontent.com/8959779/190237154-854a3edd-b1a7-4248-8fb2-a9088d37d52e.jpg)

**Comment by NicolaGiannini** [comment]
Merci ! J'ai obtenu le message.

**Comment by MelanieFrisoli** [comment]
MacBook Pro, puce M1 Max
MacOS Monterey

V3113
Aucun des trois messages n'apparaît sur mon M1 lorsque j'efface des speakers.

V3112
Aucun des trois messages n'apparaît sur mon M1 lorsque j'efface des speakers. 
La seule différence avec V3113 : avec le speaker setup Dome10(8+2)Subs2, lorsque j'efface les speakers 9, 10, puis 7 et 8 et enfin le 5, et que je ferme la fenêtre (sans cliquer sur "Compute"), SpatGRIS plante.

V3111
J'ai bien les trois messages qui apparaissent à l'effacement des hp.

**Comment by MelanieFrisoli** [comment]
V3114

Aucun des trois messages n'apparaît sur mon M1 lorsque j'efface des speakers.

**Comment by Normandeau** [comment]
V321
Impossible à vérifier avec les Mac Intels. Sur le M1 du FCI, on n'a pas ce problème. Est-ce que ce bogue est toujours valide?

**Comment by MelanieFrisoli** [comment]
V321
M1 

Problème apparemment réglé ! 
Les trois messages sont à nouveau présents quand on supprime les haut-parleurs dans le speakers setup edition.
