### ISSUE TITLE
Le potentiomètre Global Sound Diffusion n'est pas activé correctement lorsqu'on entre des valeurs chiffrées

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#368]
V3.1.14

Je signale que dans mon cas, le changement de valeur ne semble prendre effet que lorsque je cesse de cliquer sur la souris. 
Je le signale au cas où il ne s'agirait pas d'un comportement voulu.
Voir la vidéo :

https://user-images.githubusercontent.com/35705913/192332206-510c611f-02a8-449d-92a4-ccd061992057.mov

**Comment by DavidPiazza** [comment]
v3.1.14

Je seconde; dans mon cas aussi le paramètre ne se modifie que quand je relâche le bouton de la souris.

Le changement du paramètre cause une réévaluation de tous les niveaux de sortie, ce qui me mène à penser que le calcul de son interpolation se complexifierait (et pas nécessairement de manière linéaire) à mesure que le nombre de hp augmenterait dans un setup. Je présume que l'opération n'est pas impossible à réaliser en temps réel sur nos machines modernes, mais que l'implémentation d'un comportement continu du paramètre pourrait impliquer que l'on exclue potentiellement des processeurs plus âgés, d'où mon impression que cela représente le comportement désiré, pour l'instant.

**Comment by MelanieFrisoli** [comment]
V3114

Même chose ici.

**Comment by Normandeau** [comment]
V320
C'est voulu.

**Comment by NicolaGiannini** [comment]
V320 
J'ajoute un détail à ce sujet au cas où il serait utile de le mentionner dans le manuel : quand on indique la valeur en chiffres, une fois appuyé sur la touche "Enter", il faut cliquer sur le chiffre (ou sur le potentiomètre) pour que la modification soit prise en compte.

**Comment by Normandeau** [comment]
Je confirme. Wow bonne observation. La nouvelle valeur n'est pas prise en compte malgré une sorte de confirmation du logiciel après avoir entré Enter. Pour ajouter aux options décrites par Nicolas, on peut ajouter qu'on peut cliquer n'importe où sur la fenêtre pour la nouvelle valeur soit prise en compte.
Pour mieux saisir:

https://user-images.githubusercontent.com/8959779/196518296-3bb15207-67c3-4610-a5b4-4fa16eefdc05.mov

**Comment by Normandeau** [comment]
V321
Une nouvelle valeur de Global Sound Diffusion est belle et bien fonctionnelle dès que Enter est touché.
