### ISSUE TITLE
Coupure de son dans les modes Cube et Hybrid, en écoute binaurale

### ISSUE THREAD

**Issue by MelanieFrisoli** [GRIS-UdeM/SpatGRIS#370]
V3114

Lorsque je suis en binaural, avec ControlGRIS qui fait une trajectoire en spirale, j'expérimente des coupures de son en changeant du mode Dome pour le mode Hybrid. En voici une démonstration en vidéo : 

https://user-images.githubusercontent.com/74631914/193589525-d9ac771e-0e47-4aeb-a55b-71ec7be5ece4.mp4

**Comment by Normandeau** [comment]
Belle trouvaille Mélanie.
En fait ce phénomène se passe autant en mode Cube qu'en mode Hybrid. Et en mode Hybrid, peu importe que la source soit en mode Dome ou en mode Cube. Cela se passe également avec toutes les trajectoires, pas seulement la spirale.
Autrement dit, il s'agit ici d'un bogue majeur. Heureusement qu'il y en a qui travaille au casque.
Ce problème ne se pose qu'avec la version courante, 3.1.14. Aucun problème avec les versions 3.1.9 (officielle) et 3.1.13 (apparition du MBAP).

**Comment by NicolaGiannini** [comment]
Je confirme tout cela!

**Comment by Normandeau** [comment]
V320
Semble réglé autant en cube qu'en hybrid.
