### ISSUE TITLE
Cube : Facteur d'atténuation non-nul à 0dB

### ISSUE THREAD

**Issue by DavidPiazza** [GRIS-UdeM/SpatGRIS#374]
https://user-images.githubusercontent.com/50223477/196053750-bc9003ed-577d-4349-b602-77de152754c6.mov

V. 3.2.0
Global Sound Diffusion à 0
Cube62(30-12-20)Subs2 MMR

Une source qui sort des limites internes du cube est filtrée même si les Attenuation settings sont à 0dB. Si on change la fréquence de coupure du filtre à 16000 Hz, l'effet est moins présent puisque dans le très haut registre. Or, on s'attendrait à ne pas avoir d'atténuation du tout à 0dB. Comme on peut le voir dans cette vidéo, le problème se manifeste aussi en mode binaural.

**Comment by DavidPiazza** [comment]
https://user-images.githubusercontent.com/50223477/196054970-fe695ad9-3a8e-4772-9a44-a9c8b14f1edb.mov

J'ajoute que le problème survient également au haut du cube, lorsqu'on active le mode extended top dans ControlGRIS. La vidéo ci-haut montre que l'atténuation est forte lorsqu'on dépasse le « plafond », même à 0dB d'atténuation dans SpatGRIS.

**Comment by Normandeau** [comment]
Transféré dans l'issue #342, déjà en cours.
