### ISSUE TITLE
Mute et Solo sont sauvegardés dans Projects et Speaker Setup, mais pas considérés comme un changement

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#376]
V320
Un hasard fait que le template Cube24(8-6-4-2)Subs4 Icosa comporte actuellement une erreur. Lorsqu'on ouvre celui-ci, le hp no 5 a été sauvé en solo. Si j'enlève le solo, SpatGRIS ne me demande pas si je veux sauvegarder le changement. Et comme c'est un Template, il va toujours s'ouvrir de la même manière.
Il y a donc une erreur ici: à la fois les Solo et les Mute sont sauvegardés avec les Speaker Setups, mais quand on change leur valeur, aucun avertissement de nous informe que le changement n'a pas été sauvegardé.
Les Mutes et les Solos font donc bien partie d'un Speaker Setup, mais ils ne sont pas considérés comme des changements. Ils ne «triggent» pas la fonction Save de SpatGRIS. À corriger.

**Comment by Normandeau** [comment]
C'est la même situation avec les Projects

**Comment by NicolaGiannini** [comment]
Je confirme cela.

**Comment by Normandeau** [comment]
V321
Mute et Solo sont désormais sauvegardés respectivement dans les Projects ou les Speaker Setup.

**Comment by MelanieFrisoli** [comment]
V321 

Je confirme.
