### ISSUE TITLE
Bouton Attenuation Settings invisible lorsque à Off

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#377]
V321
Bouton On/Off Attenuation Settings

Mélanie:
Je suis d'accord, super bel ajout !
Peut-être un détail, mais quand "Attenuation Settings" est off, on ne voit presque plus le carré où cliquer pour le remettre à On.
Chez un·e utilisateur·trice novice, si ce bouton est éteint, cela peut être troublant de constater que l'atténuation ne fonctionne pas, et ne pas savoir qu'on peut le rallumer. Qu'en pensez-vous ?

Robert:
Effectivement, il ne reste aucune trace du bouton lorsqu'il est à Off. Donc on l'oublie. Je n'ai pas vu cela, car le bouton n'est apparu que dans la version officielle. Les images du manuel sont fabriquées artificiellement...
Comme quoi, il ne fait rien laisser passer!

On:

![Capture d’écran, le 2022-11-07 à 11 43 15](https://user-images.githubusercontent.com/8959779/200366091-7b90538d-b7d3-4771-80fe-bbf3481f2e5c.jpg)

Off: il faut vraiment avoir un œil de lynx pour apercevoir la trace du bouton!
Il faut colorer le bouton Off. Peut-être en gris pâle comme les boutons Dome, Cube et Hybride? Seul celui qui est en orange est actif.

![Capture d’écran, le 2022-11-07 à 11 43 28](https://user-images.githubusercontent.com/8959779/200366285-984fee24-5cab-4b46-9cf8-6e46156ab830.jpg)

**Comment by NicolaGiannini** [comment]
Je suis d'accord, on pourrait rendre le carré gris quand il est sur off pour le rendre plus visible.

J'ajoute une note.
Pas du tout urgent. Je me demande si pour rendre encore plus évident le changement d'état entre OFF et ON, il ne serait pas utile de griser les deux paramètres (db et Hz) lorsque l'atténuation est désactivée.

**Comment by DavidPiazza** [comment]
> Je me demande si pour rendre encore plus évident le changement d'état entre OFF et ON, il ne serait pas utile de griser les deux paramètres (db et Hz) lorsque l'atténuation est désactivée.

Je seconde cette suggestion. Ça faisait probablement partie de l'idée à Nicola, mais j'ajouterais  la précision que les paramètres ne devraient, en l'occurence, pas être modifiables lorsqu'ils sont grisés.

**Comment by MelanieFrisoli** [comment]
Une autre question concernant les Attenuation Settings. 
En dôme, sans réduction stéréo, ils n'apparaissent pas, ce qui est bien normal. 
Mais, ils apparaissent lorsque je passe (toujours en dôme) en réduction stéréo binaural ou stéréo, sans les réglages toutefois. Juste le on/off.
Est-ce normal ? 

https://user-images.githubusercontent.com/74631914/200830962-7f756186-5e9e-4502-9f35-80034ba7e870.mp4

**Comment by Normandeau** [comment]
Gaël:
«Une autre chose concernant l'atténuation. Je remarque qu'aucune atténuation n'est appliquée avec la réduction Stéréo. J'imagine que c'est voulu ? (En fait, je cherche un peu à quoi sert ce mode...)»

Le mode Stereo sert à travailler sur une paire de hp dans un studio maison ou à réduire une œuvre multiphonique en stéréo. Très utile. Mais le point que tu soulèves mérite d'être examiné de près.
Faisons le point:

**1. Mode Dome**
1.1. Stereo
Attenuation Settings apparaît avec le bouton On/Off qui semble actif.
En fait il ne l'est pas et **ces informations ne devraient pas apparaître**.
À corriger.
1.2. Binaural
Même commentaire.

**2. Mode Cube**
2.1. Stereo
Tous les réglages apparaissent mais ne sont pas actifs!
2.2. Binaural
Tous les réglages apparaissent et sont actifs.
D'après moi c'est ce comportement qui est correct.

Le pense que le mode Stereo devrait avoir le même comportement que le Binaural en mode Cube et Hybrid.
En effet, si on écoute son travail de spatialisation sur deux hp, on veut conserver les effets d'atténuation et de filtrage.
De plus, si on veut réduire une pièce multiphonique en stéréo, il faut que ces paramètres soient conservés.

J'ajoute que si un utilisateur n'en veut pas il n'a qu'à les fermer.

Qu'en pensez-vous?
Compliqué à corriger?

**Comment by OKGougou** [comment]
Contrairement au mode binaural qui utilise l'algorithme sélectionné dans SpatGris pour traiter le son,  la réduction stéréo vient «écraser» chaque source sur l'axe des X, entre -1 et 1 (entre les haut-parleurs gauche et droite).
Il n'y a pas de traitement de spatialisation et d'atténuation pour le moment. Ça me prendrait un peu de temps mettre ça au point.

Mais une atténuation est-elle vraiment souhaitable en mode stéréo ? Tout son atténué en Y et en Z sera réparti entre gauche et droite. Par exemple, si on a un son avec atténuation en X=0, Y=0 et Z=1.6, le mode stéréo positionnera en plein centre le son atténué.

**Comment by NicolaGiannini** [comment]
Je suis d’accord avec Robert.
En mode Dome les Attenuation Settings ne devraient pas apparaître lors des réductions Stereo et Binaural, en considérant qu'en mode DOME les Attenuation Settings ne sont pas disponibles.

En mode CUBE, pour moi aussi on devrait pouvoir utiliser les Attenuation Settings lors d'une réduction Stéréo.
Les attenuation settings peuvent avoir une fonction musicale, par exemple, ils peuvent être utilisés pour faire apparaître et disparaître des matériaux sonores. 

Ainsi, si une source disparaît ou est atténuée à un moment donné en mode CUBE multicanal, par exemple parce qu'elle est à Z=1.6, comme dans l'exemple de Gaël si je comprends bien, je pense qu'elle devrait également disparaître dans sa réduction stéréo.

**Comment by DavidPiazza** [comment]
Je crois aussi que les paramètres d'atténuation devraient être entendus lorsqu'on est en réduction stéréo. Cette dernière a l'avantage de ne pas appliquer la coloration spectrale reliée à la HRTF du mode binaural. Avoir à choisir entre une reproduction adéquate au niveau timbral ou bien au niveau musical (on entend ici, tel que l'a mentionné Nicola, la fonction musicale de l'atténuation des sources) cause une incongruité dans l'utilisation de SpatGRIS au casque/paire de haut-parleurs.

**Comment by NicolaGiannini** [comment]
V322

- Le bouton Attenuation Settings est visible lorsque à Off.
- Les deux paramètres (db et Hz) sont grisés lorsque l'atténuation est désactivée.
- En mode DOME, les Attenuation Settings n'apparaissent pas lors des réductions Stereo et Binaural.
- En mode CUBE, les Attenuation Settings apparaissent et sont actifs aussi lors de la réduction Stereo maintenant.

Tout semble réglé !

**Comment by Normandeau** [comment]
Testé avec du bruit rose à -3dB.
Je confirme tout cela. Et j'ajoute:
• Cela fonctionne comme prévu en mode Hybrid également.
• Cela fonctionne bien également en mode Extended Top et Extended Top and Bottom
• Un enregistrement stéréo et/ou binaural en mode Cube reflète bien les réglages d'Attenuation Settings.

Continuons à tester afin d'être bien certain cette fois-ci.

**Comment by Normandeau** [comment]
Donc tout va bien?
Tout est bien testé avec les Attenuation Settings?
On peut publier?

**Comment by DavidPiazza** [comment]
Tout va bien du côté de mes tests en ce sens.

**Comment by NicolaGiannini** [comment]
De mon côté tout semble beau. Je me demande si dans les templates on devrait les mettre à OFF par default. Dans tout cas, ce n'est pas une urgence.

**Comment by Normandeau** [comment]
Bonjour,

Vous n'êtes pas très bons ces jours-ci!!!!

Voir l'issue no 380 que j'ai trouvé en faisant un test de base...

Allez de retour au boulot...

Le 28 nov. 2022 à 17:51, David Piazza ***@***.******@***.***>> a écrit :


Tout va bien du côté de mes tests en ce sens.

Le 28 nov. 2022 à 19:32, NicolaGiannini ***@***.******@***.***>> a écrit :

De mon côté tout semble beau. Je me demande si dans les templates on devrait les mettre à OFF par default. Dans tout cas, ce n'est pas une urgence.





Cordialement,

•••••••••••••••••
Robert Normandeau
Professeur titulaire de composition électroacoustique
Directeur du GRIS
Faculté de musique

T 514-343-6111 poste 3486

Faculté de musique
200, ave. Vincent d'Indy
Bureau  A-879, Montréal, H2V 2T2

[cid:FA2B6DA7-5371-4FCD-B945-B8CC52684843]
