### ISSUE TITLE
En utilisant la fonction 'Show Speaker Level' sur M1 et M2, les haut-parleurs ne sont pas visibles, à moins qu'un signal audio ne leur soit envoyé

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#378]
Dans une vidéo envoyée par Mélanie (processeur M1) le 11 juin 2022, on peut voir qu'en utilisant la fonction 'Show Speaker Level', les haut-parleurs ne sont pas visibles, à moins qu'un signal audio ne leur soit envoyé. S'il n'y a pas d'audio, les haut-parleurs disparaissent. 

Voici la vidéo :

https://user-images.githubusercontent.com/35705913/200407354-64759f27-2ff4-487f-8254-ef558d2ba13c.mp4

Dans mon cas, cependant, les haut-parleurs sont toujours visibles (MacIntel), ils sont gris et deviennent blancs quand ils reçoivent de l’audio.
Aussi dans le manuel on lit :
• Show Speaker Level: Shows how much energy each speaker delivers. From grey (nothing) to white (maximum) 

Je pense alors qu'il s'agit d'un bug. Mais je vous laisse vérifier cela, et si cela est toujours présent dans la version 3.2.1.

La version affichée dans la vidéo de Mélanie est la 3.1.9

**Comment by Normandeau** [comment]
V321
Comme pour les autres bogues M1, est-ce toujours valide? Arrive-t-on à le reproduire sur notre Mac M1?

**Comment by MelanieFrisoli** [comment]
V321
J'ai le même comportement que Nicola. Soit les haut-parleurs sont inexistants soit ils sont blancs. Il n'existe plus d'intermédiaire qui rend compte de l'amplitude du signal qui les traversent.

**Comment by MelanieFrisoli** [comment]
V321 

Voici une vidéo dans laquelle un son continu effectue une rotation très simple sans aucune élévation. On remarque que les haut-parleurs du premier cercle apparaissent et disparaissent (comme décrit pas Nicola). 
On remarque aussi que les haut-parleurs du second cercle s'allument aussi les uns après les autres, alors qu'ils ne seraient pas censés, non ? Cependant ils sont moins "blancs" que ceux du premier cercle. 

Aussi, à la fin de la vidéo, je passe en mode Binaural puis Stéréo et les derniers haut-parleurs allumés restent, mais les mouvements ne sont plus suivis. Cela m'amène une nouvelle question à propos de "Show Speakers Level". En mode binaural, devrait-on pouvoir voir les niveaux des différents haut-parleurs ? Il me semble que j'aimerais ça, mais je ne suis pas sûre que ça fasse du sens. Qu'en pensez-vous ? 

https://user-images.githubusercontent.com/74631914/200555990-8bdf36bd-ce75-46ab-a69e-9479266ddb0b.mp4

**Comment by Normandeau** [comment]
V325
Confirmation du bogue visuel sur M2.

**Comment by Normandeau** [comment]
macOS 13.3.1 (mise à jour Ventura)
DP 11.22 (mise à jour DP)
Nouvelle manifestation de ce bogue.
Les haut-parleurs sont maintenant toujours affichés, que ce soit avec ou sans Show Speaker Level, mais leur niveau ne l'est plus!
Il existe cependant une petite différence entre les deux.
Les sorties directes sont en noir lorsque c'est désactivé, et en blanc lorsque c'est activé.
Cela est uniquement graphique car dans les deux cas, le niveau n'est pas montré.
Qu'est-ce qui changé?
Ce n'est pas de notre côté en tout cas...

Show Speaker Level désactivé:

![Show Speaker Level désactivé](https://user-images.githubusercontent.com/8959779/230942785-f6bbdf24-eff6-43b4-bc76-f61f59553bc0.jpg)

Show Speaker Level activé:

![Show Speaker Level Activé](https://user-images.githubusercontent.com/8959779/230942866-b89e97de-3644-479e-85e2-9b44653df49e.jpg)

**Comment by Normandeau** [comment]
V328
Toujours présent.

**Comment by Normandeau** [comment]
V3.3.0 avec Speaker View 0.0.0.1
Mac M2 macOS 13.6
Ce problème est enfin réglé, presqu'un an plus tard!
Bravo Gaël.
