### ISSUE TITLE
Conflit lors d'un changement de la Fe: plantage occasionnel mais fréquent de SpatGRIS

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#379]
V321
MacOS 12.6.1

Bogue majeur de conflit entre les Préférences Son du Mac et celles de SpatGRIS
En résumé, si les Préférences Son du Mac sont réglées en entrée sur le micro et en sortie sur les hp du Mac, SpatGRIS va finir par geler d'une manière ou d'une autre.
En fait la seule condition qui semble fonctionner à tous les coups, c'est lorsque la sortie du Mac est sur autre chose que les HP du Mac.
Je n'ai jamais vu cela récemment.

**À valider rapidement, car si c'est vérifié, il faudra sortir un correctif très rapidement.**

Situation 1
- Utilisation d'une interface différente dans un autre studio (Babyface Pro ici) et fermeture du Mac
- Ouverture du Mac réglé  en entrée sur micro et en sortie sur HP du Mac 
- Ouverture de SpatGRIS sur une interface différente (Madiface USB)
- SpatGRIS gèle et refuse de s'ouvrir.

Situation 2
- Jeté les Preferences de SpatGRIS
- Préférences Son du Mac en entrée sur micro et en sortie sur HP du Mac
- SpatGRIS gèle et refuse de s'ouvrir.

Situation 3
- Aucunes Preferences de SpatGRIS
- Préférences Son du Mac réglées sur Entrée micro et Sortie MadiFace
- SpatGRIS s'ouvre normalement avec le micro en Entrée et Madiface en sortie

Situation 4
- Aucunes Preferences de SpatGRIS
- Préférences Son du Mac réglées sur Entrée BlackHole et Sortie HP du Mac
- SpatGRIS s'ouvre normalement avec BlackHole en Entrée et HP du Mac en sortie

Situation 5
- Aucunes Preferences de SpatGRIS
- Préférences Son du Mac réglées sur Entrée micro du Mac et Sortie HP du Mac
- SpatGRIS s'ouvre normalement avec micro en entrée et la HP du Mac en sortie!!!!!!!
(C'est à n'y rien comprendre...)
- Mais si j'essaie de changer le Audio Input Device pour BlackHole, SpatGRIS gèle et après il ne s'ouvre plus.

Situation 6
- Aucunes Preferences de SpatGRIS
- Préférences Son du Mac réglées sur Entrée micro du Mac et Sortie MadiFace USB
- SpatGRIS s'ouvre normalement avec le micro en Entrée et Madiface en sortie
-  Change pour BlackHole en entrée
- Sauve les préférences

Situation 7
- Remet les préférences Son du Mac réglées sur micro et sortie HP du Mac
- SpatGRIS s'ouvre normalement avec BlackHole en Entrée et MadiFace en sortie selon ses Preferences
- Change SpatGRIS pour micro en entrée et HP du Mac en sortie
- Sauve les Préférences
- SpatGRIS s'ouvre normalement avec micro en entrée et la HP du Mac en sortie
- Mais si j'essaie de changer le Audio Input Device pour BlackHole, SpatGRIS gèle et après il ne s'ouvre plus.

**Comment by NicolaGiannini** [comment]
V321
MacOS 12.6.1

Je n’ai pas de cartes de son externes à disposition aujourd’hui alors je n’ai pas pu vraiment tester la plupart des situations décrites par Robert. Je vais le faire demain. 

J’ai testé la situation 2, mais je n’arrive pas à faire geler SpatGRIS.

J'ai aussi essayé de tester la situation 1 en créant des cartes virtuelles (par des aggregated devices), mais je n’arrive pas à faire geler SpatGRIS.

**Comment by Normandeau** [comment]
De retour chez moi, je n'arrive pas à reproduire non plus, pourtant avec David à la fac, on y est arrivé immédiatement sur son ordi!
Je note une chose cependant. Dans les directives pour désinstaller SpatGRIS, on donne les indications suivantes pour jeter deux fichiers:

Preferences:
~/Library/Preferences/ca.umontreal.musique.gris.spatgris.plist

Support Library
~/Application Support/GRIS/SpatGRISx.x.xml
(x.x.x: version number. Example: 3.2.1)

J'ai jeté ces deux fichiers après la découverte du bogue. Or je remarque que le premier n'est pas recréé dans le dossier Preferences. Ce fichier est-il inutile aujourd'hui? Quelles informations contenait-il? Y avait-il un conflit?

**Comment by Normandeau** [comment]
Le fichier Preferences est recréé seulement quand on ouvre ou sauvegarde des projets/speaker setups originaux, mais pas quand on ouvre des templates. Il contient le lien vers les dossiers où ces documents ont été ouverts/sauvegardés. À suivre.

**Comment by MelanieFrisoli** [comment]
V321
Je n'arrive pas non plus à reproduire ce bug.
J'ai testé toutes les situations et tout fonctionne normalement sur mon M1 sous Monterey, avec mon interface Scarlett.

**Comment by Normandeau** [comment]
De retour à la fac, tout fonctionne...
Un fichier corrompu? 
 Dans mes Preferences, j'avais deux fichiers (ce que j'ai pu vérifier dans mon Time Machine, au moins jusqu'en juin dernier):
ca.umontreal.musique.gris.spatgris.plist
ca.umontreal.musique.gris.spatgris.txt
Pourquoi le fichier txt? Fouille-moi!

En fait, ça fait plusieurs fois que cela m'arrive, mais je n'avais pas réussi à documenter le tout, contrairement à hier où le problème apparaissait systématiquement. Et comme David a eu le même problème devant moi et sur un autre ordi, j'étais certain du résultat.
On verra si ce problème nous est signalé.

**Comment by Normandeau** [comment]
De retour à la fac, le bogue réapparaît... tel que décrit initialement.

![SpatGRIS ne répond pas](https://user-images.githubusercontent.com/8959779/201194518-cb74f876-9161-48b2-9ccd-1f49e4f3f04f.jpg)

**Comment by Normandeau** [comment]
V322
Après un ménage en profondeur de mon Mac, cela semble réglé... pour le moment!

**Comment by Normandeau** [comment]
Bonjour, Je ne vais pas rouvrir cette issue #379, mais j'ai toujours le même problème: une très grande difficulté pour SpatGRIS de passer d'une Fe à l'autre. Ça plante à tous les coups.
Situation.
Travail personnel sur des projets DP à 48kHz, fermer l'ordi.
Rouvrir l'ordi, passage à la session DP du cours d'histoire à 44,1kHz.
Changement d'interface entre les deux types de session.
Plantage de DP ou de SpatGRIS ou des deux.
L'inverse est aussi vrai, passage de 48 à 44,1 kHz.
Pourriez-vous jeter un œil là-dessus encore, au cas où?

**Comment by Normandeau** [comment]
Ou tester les mêmes changements mais sans fermer l'ordi.
Ou juste en fermant la session.

**Comment by NicolaGiannini** [comment]
J’ai essayé de tester plusieurs situations et parfois SpatGRIS ne répond plus (roue qui tourne) en cas de changement d'interface.

Je n’ai aucune séquence d’étapes qui donne toujours le même résultat. Mais souvent, je peux faire en sorte que SpatGRIS ne réponde (roue qui tourne) pas en suivant les étapes suivantes :

SpatGRIS, Audio output Device : RME Hexa
SpatGRIS FE : 44,100Hz

Ableton Live 10,  Audio output Device : Carte de son Mac.
Ableton Live 10, FE : 48kHz

Je démarre la session dans Live.
Je modifie le Audio output Device dans Live et je mets la RME de l’Hexa.
Le passage de carte de son et donc de FE parfois fait en mesure que SpatGRIS ne répond plus.
Cela n’arrive pas toujours.

Sinon autre situation.

Hier je utilisais un aggregated device dans le B187 (RME B187+Blackhole 64ch). Hier soir, j’ai fermé SpatGRIS et j’ai mis l’ordi en veille.

Ce matin je branche l’ordi à la carte de son de l’hexa. J’essaie d’ouvrir SpatGRIS, il ne s’ouvre pas. Je force la fermeture, j’essaie d’ouvrier SpatGRIS, il ne s’ouvre pas.
Je débranche la carte de son de l’Hexa. SpatGRIS ne s’ouvre pas quand même.

En redémarrant l’ordi, tout est beau.

Sinon, en changeant de projet à différentes FE dans Logic, je n’ai pas eu des plantages.

**Comment by NicolaGiannini** [comment]
Il vient d’arriver une autre situation où SpatGRIS ne répond plus.

Situation de départ :
SpatGRIS, Audio output Device : Carte de son Mac.
SpatGRIS FE : 44,100Hz

Ableton Live 10, Audio output Device :  RME Hexa
Ableton Live 10, FE : 48kHz

Je ferme les 2.

Ordi en veille

J'ouvre SpatGRIS. Tout est beau.

J'ouvre Ableton. Tout est beau.

Dans SpatGRIS je mets comme carte de son la RME, SpatGRIS ne répond plus.
Je force la fermeture, j’essaie d’ouvrier SpatGRIS, il ne s’ouvre pas.
Cette fois en débranchant la carte de son de l'hexa, j'arrive à ouvrir SpatGRIS.

**Comment by Normandeau** [comment]
Cela confirme mes expériences. Il me semble que cela est nouveau, non? On avait discuté de cela lors de l'issue #210

**Comment by NicolaGiannini** [comment]
Oui exactement, on avait parlé de cela dans cette issue. Et en effet ce comportement semble nouveau.

**Comment by OKGougou** [comment]
On dirait que le problème survient lorsque la carte RME est utilisée, ou tente d'être utilisée mais est absente.

Est-ce que le problème survient avec d'autres pilotes audio (d'autres cartes de son) ?

**Comment by Normandeau** [comment]
Perso, je n'ai accès qu'à des RME... Pôvre de moi ;-(

**Comment by NicolaGiannini** [comment]
V324
J'ai essayé ce que j'avais décrit ici https://github.com/GRIS-UdeM/SpatGRIS/issues/379#issuecomment-1338069149 avec une carte de son Apogee, et je n'ai pas eu de crash pour le moment. Je referai les tests aussi avec les RME.

**Comment by Normandeau** [comment]
Testé avec toutes les configurations décrites au début de cette issue, aucun problème à date. Les différentes constituantes du dispositif — RME, DP et SpatGRIS — s'adaptent automatiquement à la bonne Fe dès que la session DP s'ouvre. Et on peut alterner 48 kHz et 44,1 kHz sans problème.

**Comment by Normandeau** [comment]
V327
Ouverture pour la première fois de la version 327 avec réglage à 48kHz.
Lancement de DP à 48kHz.
Ça roule.
Changement de projet DP à 44kHz, le pilote de la RME s'ajuste automatiquement à 44kHz.
SpatGRIS 327 reste muet.
Bon, on savait que ce problème reviendrait en rétropédalant à la version 7.02 de JUCE, mais ça demeure tout de même un irritant majeur. Surtout qu'il y a aucun avertissement pour l'usager qui ne comprend pas pourquoi l'application reste tout à coup silencieuse.
On va attendre que tout cela soit réglé avant de publier.

**Comment by Normandeau** [comment]
Ah oui, il y a signal d’avertissement: la roue de la mort... qui nous oblige à forcer SpatGRIS à quitter!

**Comment by Normandeau** [comment]
Il y a deux documents qui s'écrivent lorsqu'on utilise SpatGRIS
1. SpatGRIS3.2.7.xml déposé dans le dossier GRIS de Application Support (un document différent pour chaque version de PatGRIS). C'est ce document qui fait référence à la fréquence d'échantillonnage, aux interfaces d'entrée et de sortie, au Speaker Setup.. Il est écrit au moment où on quitte SpatGRIS.
2. ca.umontreal.musique.gris.spatgris.plist déposé dans le dossiers Preferences décrit les dossiers dans lesquels on pige les documents. Si on ne travaille qu'avec les Templates, ce document ne s'écrit pas. D'après Gaël, c'est Apple qui rédige ce document.

Lorsque SpatGRIS gèle à cause d'une changement dans le Fe, je pensais que le fait jeter l'on et/ou l'autre de ces documents permettait de régler le problème. Mais ce n'est pas le cas. C'est: des fois oui, des fois non!
- La seule chose qui est sûre, c'est que si je change de projet DAW avec une Fe différente (de 48 à 44). SpatGRIS gèle.
- Si je jette SpatGRIS3.2.7.xml, SpatGRIS ne s'ouvre pas (dans danse le Dock).
- Si je jette ca.umontreal.musique.gris.spatgris.plist, SpatGRIS ne s'ouvre pas (danse dans le Dock).
- Si je jette les deux, SpatGRIS ne s'ouvre pas (danse dans le Dock).
- Si je quitte DP, et que je rouvre la session 44k alors SpatGRIS s'ouvre mais à la mauvaise Fe (48) comme pour la RME d'ailleurs. Comme SpatGRIS met la RME en entrée et en sortie par défaut et DP étant assigné à BlackHole, rien ne permet à la RME de savoir qu'il y a un projet à 44.
- Je met BlackHole en entrée dans SpatGRIS mais sans changer la Fe, SpatGRIS reste à 48, et DP proteste! Ça ne joue pas, SpatGRIS est gelé.

Leçon: toujours ouvrir l'interface audio en premier ajuster la Fe manuellement en fonction du projet sur lequel on veut travailler. Ouvrir SpatGRIS ensuite et ajuster la Fe manuellement en fonction du projet sur lequel on veut travailler. Ouvrir le DAW ensuite. Avec de la chance ça devrait fonctionner...

**Comment by Normandeau** [comment]
V327

**Comment by Normandeau** [comment]
V327
J'essaie de toujours de trouver une combinaison **perdante** parfaite pour ce problème de Fe. **Ça plante, et ça gèle tout le temps, mais c'est vraiment imprévisible**.
NOTE: Par préférences, j'entends ici le document que SpatGRIS génère automatiquement à la fermeture de celui-ci et qui contient notamment les informations de Fe. Codocument est placé dans Application Support -> GRIS

Tests de changements de Fe
Vérification de la relation entre les périphériques utilisés par défaut par Préférences Son et ceux qui sont utilisés par notre chaîne audio DAW-Blackhole-SpatGRIS.
Vérification de la Fe utilisée par CoreAudio.
Vérification de la relation de SpatGRIS avec CoreAudio, est-ce que la Fe change automatiquement même si SpatGRIS est passif.
De tout cela il ressort que SpatGRIS est très instable, qu'il gèle régulièrement au changement de Fe, qu'il soit utilisé ou non, qu'on jette ou non les Préférences.
Si SpatGRIS est fermé sur une Fe (ex 44) et qu'on ouvre un fichier audio sur une autre Fe (par ex 48), SpatGRIS gèle automatiquement lorsqu'on le rouvre, même après jeté les préférences.

![Test Issue 379, Changement de Fe 1](https://user-images.githubusercontent.com/8959779/223448214-eeef3c74-2ab7-4389-ba66-514a6847795c.jpg)

En fait les situations où SpatGRIS gèle sont tellement nombreuses et imprévisibles qu'il est presque impossible de les décerner correctement.

![Test Issue 379, Changement de Fe 2](https://user-images.githubusercontent.com/8959779/223448927-10f91be2-1f85-4c83-a479-d938113a4615.jpg)

Combinaison Twisted Wave-SpatGRIS-RME

![Test Issue 379, Changement de Fe 3](https://user-images.githubusercontent.com/8959779/223449170-4199e239-a649-410a-9607-96c8a4a85613.jpg)

**Si quelqu'un arrive à trouver la combinaison perdante parfaite, je lui offre... une bière!!! À vos tests.**

V 326
Aucun de ces problèmes n'apparaît avec V326.
Je retourne provisoirement à 326... en essayant de ne pas jouer des fichiers audio trop longs!

**Comment by Normandeau** [comment]
Je ne sais pas si ça peut aider à trouver le problème, mais lorsque je fais un changement de Fe et que SpatGRIS n'aime vraiment pas cela, la fenêtre du CPU s'illumine en rouge, comme la valeur dépassait les 100% et reste ensuite allumée par la suite jusqu'au moment où on le force à quitter. Cela a été mon premier indice il y a plusieurs semaines maintenant. Mais il faut avoir l'œil rivé sur l'écran pour le voir passer...

![Cpu Usage](https://user-images.githubusercontent.com/8959779/223516244-8b44c07e-6d2f-4200-8600-5d5c084c7d6f.jpg)

**Comment by NicolaGiannini** [comment]
Robert,
Je n'arrive pas à lire les captures d'écran. Ah ma vue ! :-)
Pourrais-tu les poster en plus haute résolution ? Merci beaucoup !

**Comment by Normandeau** [comment]
On connait le problème. Il a été résolu avec JUCE 7.0.3. À nous d'en tirer profit.

**Comment by Normandeau** [comment]
V328
Testé avec les fréquences 44, 48, 88, 96, 176 et 192.
Aucun problème.

**Comment by NicolaGiannini** [comment]
Testé des passages entre 44 et 48 kHz (je n'ai pas de cartes externes aujourd'hui). Tout me semble beau.
