### ISSUE TITLE
Attenuation Settings: réglages inaccessibles sous certaines conditions en Cube (ou Hybrid)

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#380]
V322
Mode Cube (ou Hybrid)
- En ouvrant n'importe quel preset Cube, le bouton Attenuation est à On (valeur par défaut)
- En passant en mode Stereo ou Binaural
- En mettant le bouton des Attenation à Off
- En ouvrant n'importe quel preset Cube
- Le bouton Attenuation revient à On, ce qui est la valeur par défaut
**Mais:**
- Les réglages sont en grisé et inaccessibles.

![Capture d’écran, le 2022-11-29 à 10 33 59](https://user-images.githubusercontent.com/8959779/204573827-1a8073c1-aa61-45fd-88b9-5f0ead656d52.jpg)

**Comment by Normandeau** [comment]
Complément d'information
Les réglages sont en grisé, donc inaccessibles, comme mentionné précédemment.
Cependant ils sont bien en fonction. Voir un exemple ici où un projet a été sauvegardé avec les réglages à -36dB et le filtre à 2000 Hz. Ceux-ci sont bien en fonction comme on le voit dans l'analyse spectrale:

![Capture d’écran, le 2022-11-29 à 10 55 34](https://user-images.githubusercontent.com/8959779/204578434-a56f274c-bf2f-4314-8247-f48bd1fad673.jpg)

Pour récupérer les réglages, il suffit de passer à un mode différent: Non, Stereo ou binaural.

**Comment by Normandeau** [comment]
Autre complément, en mode Stereo ou Binaural.
Si on sauve un projet avec les Attenuations à Off, et qu'on passe ensuite à un projet avec ceux-ci à On, et qu'on revient au projet sauvegardé à Off, tout est conforme.
Autrement dit, lorsque c'est à Off, ça fonctionne.

**Comment by NicolaGiannini** [comment]
Je confirme tout cela.
J'ajoute que pour récupérer les réglages dans la première situation décrite par Robert https://github.com/GRIS-UdeM/SpatGRIS/issues/380#issue-1468278608 en plus de passer à un mode différent: Non, Stereo ou binaural, on peut aussi faire cela. Après avoir ouvert un preset de projet CUBE et qu'on se retrouve avec les réglages inaccessibles, pour récupérer les réglages, on peut aussi ouvrir n'importe quel preset Cube. Donc à la deuxième ouverture d'un projet CUBE ça fonctionne.

Je signale aussi que les réglages sont grisés et inaccessibles mais actifs aussi dans le cas suivant :

- En ouvrant n'importe quel preset Cube, le bouton Attenuation est à On (valeur par défaut)
- En mettant le bouton des Attenation à Off
- En ouvrant n'importe quel preset Cube (aussi le même)
- Les réglages sont grisés, inaccessibles mais actifs.


Je signale aussi qu'on peut avoir la situation inverse, c'est-à-dire le bouton Attenuation Settings à OFF, les réglages non grisés, accessibles mais non actifs.

- En ouvrant n'importe quel preset Cube, le bouton Attenuation est à On (valeur par défaut)
- En mettant le bouton des Attenation à Off
- En sauvegardant le projet
- En ouvrant n'importe quel preset Cube (aussi le même)
- Les réglages sont grisés et inaccessibles mais actifs
- On revient à la situation normale en ouvrant n'importe quel preset Cube (2e fois)
- On ouvre le projet sauvegardé avec le bouton des Attenation à Off
- Le bouton est à OFF. Les réglages sont non grisés, accessibles mais ils ne sont pas actifs.
- Pour revenir à la normale ça suffit d'ouvrir n'importe quel preset CUBE.

Pour créer cette situation ça suffit d'ouvrir le projet sauvegardé avec le bouton Attenation Settings à OFF à partir d'une situation où le bouton Attenuation Settings est à ON et les réglages sont non grisés et actifs.

Si on ouvre le projet sauvegardé avec les Attenuation Settings à OFF à partir d'une situation où le bouton Attenuation Settings est à OFF et les réglages sont grisés et non actifs, le comportement est correct : le bouton Attenuation Settings reste à OFF et les réglages restent grisés et non actifs.

**Comment by Normandeau** [comment]
V323
Mode Cube (ou Hybrid)
• En ouvrant n'importe quel preset Cube, le bouton Attenuation est à On (valeur par défaut)
• Passant en mode Stereo ou Binaural
• En mettant le bouton des Attenation à Off
• En ouvrant n'importe quel preset Cube
• Le bouton Attenuation reste à Off, ce qui est la dernière valeur choisie
• En remettant le bouton à On, les valeurs sont accessibles
La situation semble réglée.

**Comment by NicolaGiannini** [comment]
La situation semble réglé aussi de mon côté.

Par rapport aux étapes décrites par Robert, je remarque une différence. 

Mode Cube (ou Hybrid)
• En ouvrant n'importe quel preset Cube, le bouton Attenuation est à On (valeur par défaut)
• Passant en mode Stereo ou Binaural
• En mettant le bouton des Attenation à Off
• En ouvrant n'importe quel preset Cube
• Dans mon cas le bouton Attenuation reste à On (valeur que je pense est enregistrée avec le preset).

**Comment by OKGougou** [comment]
Lorsque vous parlez de n'importe quel preset Cube, est-il question de Projects ou de Speaker Setup ? La valeur du bypass se trouve dans les Projects et l'atténuation est à  ON pour tous les templates de projet. Il est normal que l'atténuation soit automatiquement remise à ON si on ouvre un template de projet.

**Comment by Normandeau** [comment]
Dans mon cas je parlais des Speaker Setups. Je crois que dans son dernier post, Nicola parlait des projets puisque seuls les projets remettent le bouton à On par défaut, comme tu le décrit.. Ce qui était surtout problématique ici, c'était le fait que les réglages étaient inaccessibles selon certaines conditions, mais cela est réglé.
