### ISSUE TITLE
Attenuation Settings à ON: Sous le plancher, le son n'est pas atténué également selon sa position X-Y

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#381]
V322
Si le bouton Attenuation Settings est à ON :

- Si la source dépasse le plafond (en considérant Z dans SpatGRIS, source avec une valeur Z supérieure à 1) les réglages fonctionnent. 
- Si la source est sous le plancher (source avec une valeur Z inférieure à 0) le son n'est pas atténué de façon progressive.

Une fois passé zéro et en descendant, le son est immédiatement atténué. 

Si au contraire les paramètres d'atténuation sont sur OFF et que je déplace une source sous le plancher, le son est toujours présent. 

Dans le manuel on dit :  In Elevation, attenuation starts at the top (Extended Top) and at the bottom (Extended Top and Bottom) of the cube.
Par rapport à ce que dit le manuel, on pourrait s'attendre à ce que le son soit atténué si je déplace une source sous le sol à l'aide de ControlGRIS.

Une question me vient à l'esprit : conceptuellement, voulons-nous que l'atténuation vers le bas commence à Z=0 ou Z=-1 ?

**Comment by NicolaGiannini** [comment]
Je me corrige.

Dans le cas d'une source déplacée sous le plancher, si cette source est au centre pour X et Y (X et Y = 0), l'atténuation fonctionne progressivement. Si je déplace la source de Z=0 à Z=-1 le son est progressivement atténué (comportement correct).

Si au contraire la source est sur le cercle intérieur d'atténuation pour X et Y (par exemple X=0 et Y= -0.60), si je déplace la source de Z=0 à Z=-1 le son n'est pas atténué progressivement. Juste après zéro, le son est immédiatement atténué.

En résumé :
Si la source est au centre par rapport à X et Y, l'atténuation est progressive.
Si la source est sur le cercle intérieur, l'atténuation n'est pas progressive.

Si la source est en position intermédiaire, plus la source est proche du centre, plus l'atténuation verticale vers le bas est progressive. Plus la source est proche du cercle intérieur, moins l'atténuation verticale vers le bas est progressive.

Quant à l'atténuation verticale vers le haut, l'atténuation fonctionne toujours, même si la source est sur le cercle intérieur. Il semble avoir quand même un comportement similaire. Plus la source est proche du centre, plus l'atténuation verticale vers le haut est progressive. Plus la source est proche du cercle intérieur, moins l'atténuation verticale vers le haut est progressive.

**Comment by Normandeau** [comment]
Bonne correction! J'étais en train de la faire...
J'ajoute ceci, avec des valeurs précises.
SpatGRIS Attenuation Settings: -36dB, 1000Hz

**ControlGRIS Extended Top**
• X: 0.00, Y: 0.00, Z: 0.90
Atténuation normale.

• X: 0.60, Y: 0.00, Z: 0.90
On n'entend presque rien. X:0.60 correspond au cercle intérieur.

**ControlGRIS Extended Top and Bottom**
• X: 0.00, Y: 0.00, Z: 0.90
Atténuation normale.

• X: 0.60, Y: 0.00, Z: 0.10
On n'entend presque rien. X:0.60 correspond au cercle intérieur.

**Comment by Normandeau** [comment]
J'ajoute: on peut prendre la valeur de X et la placer dans Y et le résultat est le même.
En Stereo et en Binaural, le résultat est le même.

**Comment by Normandeau** [comment]
V323
J'ai ajouté cette image dans le manuel, suite à la discussion de la semaine dernière, pour bien faire comprendre que les Attenuations Settings suivent la courbe d'une sphère qui prend son origine au point (0.0, 0.0).
Dans cette nouvelle version, les calculs ont l'air de correspondre à ce à quoi on s'attend quand on comprend bien le principe.

![SpatGRIS Attenuation Sphere](https://user-images.githubusercontent.com/8959779/206046590-af43b334-4201-489e-9369-e0c4d10bd855.jpg)

**Comment by NicolaGiannini** [comment]
Très bonne idée pour l’image ! 
Et je confirme que le comportement a l'air de correspondre à ce à quoi on s'attend quand on comprend bien le principe.
