### ISSUE TITLE
Réduction stéréo : modifier l’Audio Output Device peut entraîner un plantage de SpatGRIS si les canaux utilisés par la carte de son précédente ne sont pas présents dans la nouvelle carte.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#383]
V323 
Réduction stéréo : modifier l’Audio Output Device peut entraîner un plantage de SpatGRIS si les canaux utilisés par la carte de son précédente ne sont pas présents dans la nouvelle carte.

Example :

- Je travaille en réduction stéréo dans le Hexa en utilisant la sortie écouteurs 9/10. 
- Je passe à la carte de son interne du Mac (qui a seulement les canaux 1/2). 
- Les menus du Routing deviennent vides.

- ![Schermata 2022-12-07 alle 18 01 47](https://user-images.githubusercontent.com/35705913/206316893-be4c4153-4555-4951-8824-6baf19a4dd20.jpg)

- Je sélectionne le canal 1 (ou 2) dans un de deux menus du Routing. 
- SpatGRIS plante.

Testé en Stereo et Binaural.

Si je modifie le routage stéréo (en passant de 9/10 à 1/2) avant de modifier la carte de son, je n’ai pas de plantage.

**Comment by Normandeau** [comment]
De mon côté, deux choses:
• Si je passe d'une interface à 14 canaux avec la sortie Stereo sur 11-12, aux haut-parleurs du Mac, je ne me rends même pas à l'étape décrite par Nicola: SpatGRIS **gèle** immédiatement dès que je change l'interface (ça **gèle** dans mon cas, ce n'est pas un **plantage**).
• Par contre, comme Nicola le décrit, si je change la sortie Stereo sur 1-2 **avant** de changer l'interface, il n'y a pas de problème.
Autrement dit si les numéros de sorties choisies pour Stereo sont présents dans les deux interfaces, tout va bien.
Si ces numéros sont absents de la seconde interface, ça ne passe pas bien.

Donc question:
Est-ce que c'est normal que SpatGRIS plante ou gèle si les sorties préalablement assignées à Stereo sur une interface donnée ne sont pas présentes sur une seconde interface lorsqu'on passe à celle-ci?
On pourrait penser que c'est une situation rare, mais à la fac on a une RME UFX+ qui est branchée sur les 32 hp du dôme sur les sorties 31 à 63, car elle utilise les sorties MADI qui commencent à 31 (après les 30 sorties standards de l'interface UFX normale).
Si je veux écouter quelque chose sur les hp du mac, par exemple pour éditer un fichier, soient les sorties 1-2, je change d'interface dans SpatGRIS et boum, soit ça plante, soit ça gèle. Embêtant...

**Comment by Normandeau** [comment]
V324
Le problème décrit ici semble réglé avec cette version. Lorsque je passe d'un dôme à 12 canaux avec sorties stéréo assignées à 9-10, aux haut-parleurs du Mac, SpatGRIS assigne automatiquement les sorties stéréo à 1-2.
À confirmer.

**Comment by NicolaGiannini** [comment]
V324
C'est réglé pour moi aussi !
