### ISSUE TITLE
Différence de précision de la localisation entre le MBAP et le VBAP en fonction de la densité du speaker setup

### ISSUE THREAD

**Issue by DavidPiazza** [GRIS-UdeM/SpatGRIS#385]
Pas un problème à proprement parler, plutôt une interrogation, donc à retirer si ce n'est pas à propos : 

Après avoir fait des tests de comparaison, je remarque que dans les cubes denses, le MBAP ne peut pas envoyer de signal à un seul haut-parleur, comme le pourrait le VBAP dans le même speaker setup convertit en dôme. Comme si la source « radiait » toujours un peu. Dans les dômes et les cubes éparses, l'effet est conséquemment beaucoup moins prononcé. Pour démontrer l'effet, j'ai une onde sinusoïdale à 0dBFS qui trace un cercle en mode hybride et je change le mode de la source :

https://user-images.githubusercontent.com/50223477/206541996-2a30a7bf-69b7-413b-ab21-0cd1106add45.mov

Dans un contexte plus réaliste, on peut voir comment l'effet est beaucoup moins présent avec une source au niveau adéquat qui se déplace dans un speaker setup moins dense comme celui du dôme au B-187 : 

https://user-images.githubusercontent.com/50223477/206543658-e01ea0d3-d59f-4789-9250-35d650f52fc0.mov

La chose que je remarque ici c'est que le MBAP offre (visuellement, du moins), pas moins de précision, mais plutôt une transition plus graduelle (ou peut-être seulement plus linéaire?) entre les haut-parleurs.

Est-ce qu'il serait possible, dans le cas du MBAP, d'obtenir un facteur de radiation des sources qui serait à l'échelle de la densité du speaker setup? (je pense à potentiellement tenir compte de la distance moyenne entre les haut-parleurs + la distance moyenne des haut-parleurs par rapport au point 0, 0, 0)

**Comment by Normandeau** [comment]
Réponse écrite après en avoir discuté verbalement.
1. Ne jamais perdre de vue la fonctionnalité première de l'outil qui est de proposer à l'utilisateur un outil de stratégie de spatialisations qui soient cohérent sur le plan perceptif.

Donc méfions-nous des représentations graphiques. Dans la première représentation deux choses à dire. La première c'est que ça ne correspond pas à un dispositif réaliste. Donc pourquoi s'en préoccuper? La seconde c'est qu'il n,y a pas d'analyse perceptive qui l'accompagne. Comment ce déplacement est-il perçu? est-ce que le fait de faire toute une série de fondus entre plusieurs hp est problématique? Quelle est le niveau de fondu-enchaîné entre les hp? est-ce que cela s'approche de la loi de panoramisation?
Ensuite, il faut aussi se méfier de la représentation graphique des VU-mètres. Rappelons pour mémoire qu'une diférence de 1,5 db entre deux hp suffit à a faire passer le son de l'un à l'autre en mode stéréo. Il y a certes ici des différences selon la densité des hp, mais la résolution des VU-mètres ne permet certainement pas d'apprécier justement la pertinence des déplacements à «l'œil»!

2. Comportement du MBAP

Comme déjà mentionné à quelques reprises (#371, #369 entre autres) la valeur de radiation du MBAP est actuellement critique dans le sens contraire par rapport à la situation décrite plus haut. En effet, en faisant tourner une trajectoire sur des dispositifs réels, on observe plutôt, à l'oreille, des trous entre chaque hp. D'où l'ajustement Global Sound Diffusion ajouté au Speaker Setup Edition. Cela permet d'améliorer la fluidité des déplacements dans cet algorithme.
Cela étant dit, le MBAP est certainement un algorithme à améliorer, selon nos expériences de composition.

3. Facteur de radiation

Il est déjà là, il se nomme Global Sound Diffusion.
