### ISSUE TITLE
Lorsque l'on réactive la fenêtre SpatGRIS après l'avoir minimisée, la fenêtre 3D devient noire

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#390]
V327 (et antérieures) 
Lors de la réactivation de la fenêtre SpatGRIS après l'avoir minimisée, la fenêtre 3D devient noire. Pour faire réapparaître le contenu de la fenêtre, il suffit de taper sur la barre en haut de l'interface. 

Voir la vidéo :

https://user-images.githubusercontent.com/35705913/217894129-6870c537-bee9-42ce-a714-f76eb8f74628.mp4

**Comment by Normandeau** [comment]
M2
Pas ce problème sur M2!

**Comment by DavidPiazza** [comment]
Je confirme que le problème ne se présente pas sur M2.

**Comment by Normandeau** [comment]
V328
As-tu toujours ce problème Nicola?

**Comment by NicolaGiannini** [comment]
v328
Ça semble réglé !
