### ISSUE TITLE
Perte de signal à l'Interface audio #389: une synthèse

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#391]
Problème de base: drift audio
Issue #389 

Apparu à partir de la version 3.24 (ainsi qu'avec les version 3.25. et 3.2.6).
Dispositif standard tel que décrit dans la manuel depuis le début de la version 3 de SpatGRIS:
DAW -> BlackHOle -> SpatGRIS -> Interface audio

Symptômes: Distorsion audionumérique et silence au bout d'une certaine durée de jeu ininterrompu. Ce dernier aspect est important, car c'est sur la durée que le problème existe.
Dans la majorité des cas, c'est au bout de 45-50 minutes que cela se produit. Mais on a vu aussi des durées plus courtes.

**Tests divers et variés d'où il ressort que:**

- la version 3.2.1 n'a pas ce problème
Par contre, cette version pose un autre problème qui est celui avec les changements de Fe d'un projet à l'autre (issue #379).
- mise à jour de Juce 7.0.3 a réglé ce problème et SpatGRIS 3.2.4 l'a intégré
- problème de drift audio apparu avec le version 3.2.4.
- mise à jour de Juce 7.0.4 dans SpatGRIS 3.2.6
Le problème n'est pas corrigé, c'est même pire.
- Retour à Juce 7.0.2 pour SpatGRIS 3.2.7
Cela règle le problème de drift audio mais réintroduit le problème de Fe.

-Tests fait avec BlackHole et le Mac
Aucun problème de dérive même sur de très longues périodes.

**Solution temporaire fonctionnelle pour la drift audio**

Périphérique agrégé avec SpatGRIS 3.2.7
Il semble que lorsqu'on utilise un périphérique agrégé dont l'horloge est fixée sur celle de la carte de son et la correction de dérive sur BlackHole, cela règle le problème.
Le PA doit être utilisé par tous: DAW (en sortie) et SpatGRIS (en entrée et en sortie).
On a fait un test supplémentaire avec DANTE, où le réseau a passé le test sans problème pendant plus 70 minutes.

- Le problème de changement de Fe demeure.
- Cela pose aussi un autre problème: le nombre d'entrées et de sorties n'est pas modulable dans un périphérique agrégé. Alors cela nous oblige à avoir des configurations difficilement utilisables, surtout avec BlackHole 128 et une RME UFX+ (94 canaux).
- Enfin cela signifie qu'on perd la flexibilité en passant d'un studio à l'autre, car il faut refaire à chaque fois la numérotation des sorties selon les cartes audio disponibles.

**Solution temporaire fonctionnelle pour la Fe**
- Jeter les préférences de GRIS et d'utilisateur avant d'ouvrir SpatGRIS avec une autre Fe

**Solution non-fonctionnelle**

Faire deux périphériques agrégés ne fonctionne pas. On avait imaginer cela pour inverser l'ordre de BlackHole et de la carte de son pour régler le problème posé par le trop grand nombre d'entrées et de sorties. Mais la synchronisation ne marche pas.

**Conclusion**
D'après l'ensemble des observations et des tests effectués, c'est SpatGRIS/JUCE qui est ici en cause. Quand on les sort de l'équation il n'y a pas de problème. Les expériences ont démontré que ni CoreAudio, ni BlackHole, ni les interfaces audio ne sont en cause.
Donc on est pris dans un catch 22 avec deux solutions bancales...
Fun

**Comment by Normandeau** [comment]
V3.2.5 (JUCE 7.0.3)
Fait un essai avec le périphérique agrégé suivant: Babyface-BlackHole avec horloge source sur Babyface et Correctif de dérive sur BlackHole.
J'utilise seulement BlackHole en entrée dans SpatGRIS et le Périphérique agrégé en sortie. Cette solution est très avantageuse car je n'ai pas besoin de changer les affectations de numéros d'entrées dans SpatGRIS (BlackHole commence à 1) et de sorties (mes speaker setups demeurent identiques car l'interface audio est en premier dans le PA). Cela implique cependant de faire un PA différent pour chaque interface, mais ce n'est pas si pire.

Testé avec Éliane à 48kHz et 44kHz l'un après l'autre (beaucoup de paperasses à faire ces jours...):
- sans gel au passage du changement de Fe
- sans drift audio après deux heures de jeu.

La V325 utilise JUCE 703 qui règle le problème de Fe. Et le périphérique agrégé règle le problème de dérive audio qui a été introduit par cette même version 703 et toujours pas réglé par 704.
Cela me semble un bon compromis pour le moment car cela met de côté les deux problèmes actuels. Peut-être qu'on devrait la publier avec une mise en garde. Parce que rien ne semble bouger depuis pas mal de temps chez JUCE... Ça m'embête de savoir qu'on a publié la dernière version officielle avec un bogue connu.
En attendant de trouver une vraie solution.

**À tester tout le monde.**

PS On devrait se cotiser et payer des droits à Mme Radigue...

**Comment by NicolaGiannini** [comment]
V325
périphérique agrégé : Apogee-BlackHole avec horloge source sur Apogee et Correctif de dérive sur BlackHole.

BlackHole en entrée dans SpatGRIS et le Périphérique agrégé en sortie.

Dans Live j’utilise BlackHole en sortie, comme indiqué dans le paragraphe 9.1.2 ajouté dans le manuel. 

Une heure des sinusoïdes.

J’ai eu un glitch solitaire à : environ à 2 min un autre à 13 min, 25 min, 36 min, 48 min et 60 min.

À chaque fois, il s'agissait d'un seul glitch. Pas de distorsions prolongées, pas de silences.

Utilisation CPU affiché dans les logiciels :
Ableton Live 3%
SpatGRIS 5%

Utilisation CPU affiché dans Activity Monitor 
Ableton Live 46%
Coreaudiod 48%
SpatGRIS 39%

Je testerai aussi le comportement en ce qui concerne le changement de FE.

**Comment by Normandeau** [comment]
Test de Drift Audio: Une synthèse
Testés avec BlackHole et RME (pas de périphérique agrégé, sauf pour 3.2.5).
Test d'une heure chaque fois.

3.1.11 (JUCE 6.1.5, dernière version 6, depuis 3.1.4)
Pas de problèmes

3.1.12 (JUCE 7.0.1, première version 7)
Pas de problèmes

3.1.13 (JUCE 7.0.2: problème avec les changements de Fe)
Pas de problèmes

3.1.14
Pas de problèmes

3.2.1 (Officielle)
Déjà testé: OK

3.2.2
Déjà testé: OK

3.2.3
Déjà testé: OK

3.2.4 (JUCE 7.0.3: cette version règle le problème de Fe))
Déjà testé: problématique
Cette version introduit le problème de dérive audio.

3.2.5 (copie de 3.2.4)
Déjà testé: problématique
Version avec un manuel récent.
Fonctionne bien avec le périphérique agrégé.

3.2.6 (JUCE 7.0.4)
Déjà testé: très problématique

3.2.7 (retour à JUCE 7.0.2)
Déjà testé: OK (mais retour du problème de Fe)

**Comment by NicolaGiannini** [comment]
Test de Drift Audio: ma synthèse
Test d'une heure chaque fois dans mon cas aussi.

V3.1.1 nouveau test : tout ok

V3.1.11 nouveau test : Glitch et spikes de (CPU à 100%) si la fenêtre de SpatGRIS est en deuxième plan. Une fois mise en premier plan, tout est beau.

V 3.2.1 déjà testée, tout ok.

V 3.2.3 nouveau test : tout ok.

3.2.5 déjà testée : ok avec périphérique agrégé. Problématique sans périphérique agrégé.

3.2.6 déjà testée : très problématique.

3.2.7 déjà testée : Ok, mais problème FE.

**Comment by Normandeau** [comment]
Test de changement de Fe et de Drift Audio
Selon la discussion d'hier.

MacBook Pro M2
Ventura 13.3.1
Testés avec BlackHole 0.40 et RME Babyface Pro
Test d'une heure chaque fois.
On teste quelles versions pré JUCE 7.0.2 fonctionnent bien. Tests entre 3.1.11 (JUCE 6) et 3.1.12 (JUCE 7).
La question: est-ce qu'on retourne à JUCE 6.1.5, qui a bien fonctionné de 3.1.4 à 3.1.11.
Ou est-ce qu'on prend la première version 7 de JUCE, la version 7.0.1 qu'on a utilisé seulement dans la version 3.1.12.
Les versions de SpatGRIS avec JUCE 6.1.5 et 7.0.1 sont très stables.

Donc: que gagne-ton à conserver la version 7 de JUCE?
Je pense qu'il est plus que temps qu'on prenne une décision à cet effet.
Avant même de passer à une nouvelle version qui héritera d'un nouveau Open GL.

**Comment by Normandeau** [comment]
Résultats de mes tests.
Une précision sur la méthodologie.
Les changements de Fe se font par le DAW en changeant de projet (de 44 à 48 et vice-versa). Et non pas en effectuant simplement un changement de Fe dans les préférences audio du DAW. Cela semble faire une différence.

3.1.11 (JUCE 6.1.5, dernière version 6, depuis 3.1.4)
Pas de problèmes de Fe, ni de dérive audio à 44,1kHz
Pas de problèmes de Fe, ni de dérive audio à 48kHz

3.1.12 (JUCE 7.0.1, première version 7)
Problème lors du premier changement de Fe. DP était resté ouvert. Changé la version de SpatGRIS de 3.1.11 à 3.1.12 et celui-ci a gelé au premier changement de Fe.
Pas de problèmes de Fe par la suite, pas de problème de dérive audio à 44,1kHz
Pas de problèmes de Fe par la suite, pas de problème de dérive audio à 48kHz

Nicola avait noté le 14 mars dernier:
V3.1.11 (JUCE 6.1.5) nouveau test : Glitch et spikes de (CPU à 100%) si la fenêtre de SpatGRIS est en deuxième plan. Une fois mise en premier plan, tout est beau.

Est-ce qu'on revient à JUCE 7.0.1 alors?

Est-ce que vous pouvez confirmer ces tests?

**Comment by Normandeau** [comment]
Une petite erreur de lecture du test de Nicola.
(J'ai essayé de retrouver le bogue décrit par Mélanie lorsque la fenêtre principale de SpatGRIS passait en arrière-plan, mais je ne le retrouve pas...)

Est-ce qu'on revient à JUCE 7.0.1 alors?

Est-ce que vous pouvez confirmer ces tests?

**Comment by NicolaGiannini** [comment]
Résultats de mes tests : 
3.1.11 (JUCE 6.1.5, dernière version 6, depuis 3.1.4) 
3.1.12 (JUCE 7.0.1, première version 7)

Pour les deux, aucun problème de dérive audio, test de 1h à 48kHz. 
Je n'ai pas non plus trouvé de problème en changeant la fréquence d'échantillonnage, mais dans ce cas je n'ai jamais pu recréer le problème systématiquement, il m'échappe certainement quelque chose, comme je le disais à Robert.

**Comment by Normandeau** [comment]
V328 (JUCE 7.0.1)
Premier test à 48kHz avec notre amie Éliane. Bonne nouvelle, ça ne dérive pas, même après une heure!

**Comment by Normandeau** [comment]
Deuxième test d'une heure à 44, aucun problème.

**Comment by NicolaGiannini** [comment]
Test de 1h à 48kHz. Tout est beau.

**Comment by Normandeau** [comment]
En fait, la version 328 se comporte comme on s'y attendait puisqu'elle est basée sur JUCE 7.0.1 qui n'avait pas le problème de dérive audio.
Donc bye bye les tests d'une heure! Et les périphériques agrégés, du moins en usage normal.
Jusqu'à la prochaine fois...
