### ISSUE TITLE
Les templates des projets CUBE ont comme valeur de défaut 1000Hz pour les attenuation settings. Il faudrait les mettre par défaut à 16000Hz.

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#392]
V327
Les templates des projets CUBE ont comme valeur de défaut 1000Hz pour les attenuation settings. Il faudrait les mettre par défaut à 16000Hz.

**Comment by OKGougou** [comment]
Même chose pour les templates des projets HYBRID ?

**Comment by Normandeau** [comment]
Oui.
C'est pour éviter qu'utilisateur les laissent en place sans s'en rendre compte. À 16k, ça ne fera pas trop de dommage. Mais à 1 K, grrrrrr....

**Comment by Normandeau** [comment]
V328
Corrigé
