### ISSUE TITLE
Expédier un message texte pendant que l'audio joue interrompt l'audio!!!

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#393]
V3.1.13 (JUCE 702)
Expédié un message texte pendant que l'audio joue interrompt l'audio!!! Est-ce normal?
Pendant que je teste notre amie Éliane, si je texte un message, l'audio s'interrompt quand je l'envoie!

**Comment by OKGougou** [comment]
J'imagine que c'est avec l'application Message et non avec le téléphone ?
Non, ce n'est pas normal.

**Comment by Normandeau** [comment]
V328
Pas réussi à reproduire cela.
