### ISSUE TITLE
Enlever Hybrid des Speaker Setups

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#395]
Nous n'avons que deux modes de speaker setup: DOME ou CUBE.
Quand on parle d'hybridité, c'est toujours relié au projet, pas au dispositif.
C'est le projet qui permet d'accéder à l'un ou l'autre des deux modes comportementaux, qui se déploient toujours et exclusivement dans un dôme.
Il n'y a pas de speaker setup hybride.

À l'origine, le mode Hydrid a été incorporé aux speakers setups (version 3.1.0, Octobre 26, 2021). 
Puis nous eu une discussion (issue #322) afin de savoir si c'était plutôt aux projets que celui-ci appartenait. 
Ce à quoi nous avons acquiescé.
Nous l'avons donc incorporé aux projets, mais nous ne l'avons pas enlevé aux speaker setups.

La conséquence de sauvegarder le mode hybride également dans les speaker setup et dans les projets c'est que l'un annule l'autre.
Si j'ouvre un projet hybride et qu'ensuite j'ouvre un speaker setup dôme, le mode hybride est annulé par dôme.
Et l'inverse est aussi vrai: si j'ouvre un speaker setup hybride et qu'ensuite j'ouvre un projet dôme, le mode hydride est annulé.
Cela peut être déroutant pour un utilisateur novice.

Il faut enlever le mode Hybrid des speaker setups.

**Comment by NicolaGiannini** [comment]
Je suis d’accord avec cela ! 
Et cela serait cohérent aussi avec ce que le manuel indique : 

> The hybrid mode uses the DOME algorithm, which means that the speaker setup must be a dome (if not, you will be asked to convert it) within which the sources can be moved according to CUBE behaviours where it's possible to move the sound inside or outside the dome of speakers. In HYBRID mode, the spans keep their usual dome or cube behaviour.

**Comment by Normandeau** [comment]
V328
C'est fait. Reste à tester les différents combinaisons de SS et de P afin de valider que c'est conforme aux attentes.
