### ISSUE TITLE
🐛 SpatGRIS se comporte de différentes manières lorsqu'on essaie de dépasser la valeur de sortie 128

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#397]
SpatGRIS crash systématiquement si j'inscris la valeur «0» dans la colonne Output de la fenêtre Speaker Setup Edition. Je dirais au passage que l'édition d'un dispositif comprenant un grand nombre de haut-parleurs est très pénible et chronophage.
Notamment, lorsque l'on veut changer l'ordre des canaux avec un dispositif en comprenant près de 128, alors qu'il est impossible de rentrer une même valeur deux fois ou de dépasser le chiffre 128 temporairement.

PVI, j'essaie actuellement de faire différentes versions de la future numérotation des haut-parleurs pour le nouveau dôme de la Satosphère, en fonction des contraintes matérielles et des cas d'usage récurrents. Le dispositif comprendra 93.5 canaux et pourrait éventuellement être étendu jusqu'à la limite de 128 canaux de la carte PCIe Dante du serveur audio, sans compter la possibilité d'ajouter d'autres interfaces audio en Dante. On pourrait même aller jusqu'à 256 canaux, si Blackhole le permet éventuellement.

Suggestions d'amélioration :
- Débloquer l'emploi temporaire de valeurs interdites (0, 256+, etc.) et ramener le bouton COMPUTE qui générerait alors un message d'erreur si un numéro de canal est dupliqué ou dépasse la capacité de Blackhole (0 ou 129+ canaux).
- Avoir la possibilité d'annuler une erreur (Cmd+Z) serait aussi bienvenue (feature request); 
- Retarder l'activation de la modification des valeurs par clique-glissement; j'ai souvent modifié une valeur par inadvertance alors que je voulais simplement la copier (feature request).

**Comment by DavidPiazza** [comment]
Bien vu! Je confirme que SpatGRIS plante à tout coup lorsque j'entre "0" comme sortie dans le fenêtre d'édition de speaker setups.

**Comment by Normandeau** [comment]
V325
M2, Ventura
Je confirme.

**Comment by NicolaGiannini** [comment]
V325, Monterey 12.6.1., MacIntel.
Je confirme.

**Comment by DavidPiazza** [comment]
Le bug est présent sous une différente forme dans 3.2.8 : 

Lorsqu'on clique le bouton Add Speaker dans fenêtre d'édition d'un speaker setup qui contient déjà 128 haut-parleurs, SpatGRIS plante. Même chose pour Add Ring.

**Comment by Normandeau** [comment]
V328
Bien vu David, je confirme.
En fait le bogue avec le 0 est résolu.
Le bogue avec le doublon aussi.
Reste donc celui avec des valeurs supérieures à 128.
Bon disons que pour le moment c'est un problème de riches! Qui a besoin vraiment de plus de 128 hp? (oui je sais David à la SAT...). Pour le moment, sortons la version 3.2.8 si elle est fiable par ailleurs. On corrigera le tout et songerons au futur à 256 canaux ainsi qu'aux autres suggestions par la suite.

**Comment by NicolaGiannini** [comment]
V328
Je confirme. J’ajoute qu'il suffit que l'un des haut-parleurs du Speaker Setup ait la valeur 128 pour faire planter SpatGRIS, en ajoutant un nouveau haut-parleur ou un nouveau ring. Par exemple, si dans la configuration Hexa j'ajoute un haut-parleur avec la sortie réglée sur 128 et que je clique ensuite sur le bouton Add Speaker, SpatGRIS se plainte.

**Comment by NicolaGiannini** [comment]
V329
Ça semble réglé. 

Je signale le comportement suivant
De ce que je comprends, SpatGRIS attribue automatiquement une valeur de 128 à chaque valeur introduite qui est supérieure à 128. Cela peut donner lieu au cas suivant. Dans mon Setup, j'ai déjà un haut-parleur attribué à la sortie 128, j'essaie d'ajouter un HP attribué à 129 et j'obtiens le message suivant.  

![Schermata 2023-05-15 alle 13 34 01](https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/139efb3c-e566-4653-8c0f-d178cad16842)

Mais dans tous les cas, il n'y a pas de plantage.

Probablement ce n’est pas si important, à voir peut-être si dans la prochaine version du manuel on pourrait  ajouter : 

Currently, it is not possible to enter an output value greater than 128. If you enter a value greater than 128, it will be automatically converted to 128.

**Comment by Normandeau** [comment]
En complément. 
Si on met un hp à 128 et qu'on essaie d'en ajouter un, il ne se passe rien. Même chose si le dernier des hp est à 126 et qu'on ajoute un ring de 3 hp (donc total 129), aucun message, ni rien.
En fait je viens de comprendre, il y a deux comportements différents:
- si on essaie d'entrer un no supérieur à 128, et que ce chiffre n'est pas utilisé, c'est ramené à 128. Si 128 est utilisé, on reçoit le message d'erreur.
- si on essaie d'ajouter un hp ou un ring et que cela dépasse le numéro 128, il ne se passe rien.

Il est vrai qu'un message unifié sera bienvenu, mais pour l'instant, essayons d'encourager la faculté de déduction des utilisateurs. C'est écrit partout que le nombre de canaux est de 128.
Comme tu dis pour le moment...

Je change donc ceci de Bug à Enhancement.

**Comment by OKGougou** [comment]
En effet, les valeurs sont restreintes entre 1 et 128. Lorsqu'on ajoute un haut-parleur, SpatGris cherche le speaker avec le numéro le plus élevé et ajoute le nouveau haut-parleur après celui-ci. En ce moment, si un haut-parleur a le numéro 128, il est donc impossible d'ajouter un autre haut-parleur, même s'il n'y a que quelques haut-parleurs dans le setup.

Aussi, on a un message d'avertissement équivalent si on entre 0 comme numéro de speaker et que le 1 est déjà pris. Ce message apparaît dès que le numéro du nouveau haut-parleur est déjà pris.

**Comment by Normandeau** [comment]
V3.3.0 (et probablement 3.2.11)
Tous ces problèmes sont résolus, au moins jusqu'à 256... Ça devrait être suffisant!
