### ISSUE TITLE
🐛 Vue 3D : transparence des haut-parleurs inconstante par rapport à l'affichage des numéros selon l'angle de vue ou le numéro du canal de sortie attribué

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#398]
J'ai créé deux versions d'un même dispositif de 94 haut-parleurs, avec une numérotation différente pour chaque. Je remarque que pour un Setup, je ne vois pas les numéros des haut-parleurs cachés derrière un haut-parleur à l'avant-plan dans la vue 3D, alors que c'est le cas lorsque je charge une autre sauvegarde du même dispositif avec une numérotation différente; les haut-parleurs correspondant à un numéro plus près de 1 semblent plus opaques que les haut-parleurs correspondant à un numéro plus élevé.

Les options du menu View sélectionnées sont les mêmes dans tous les cas.

Numéros cachés (opacité des haut-parleurs 3D) :
![Capture d’écran, le 2023-04-25 à 14 31 52](https://user-images.githubusercontent.com/13606544/234371391-201314ae-4eec-4856-9bed-02b89e3a69da.png)

Numéro visibles (transparence des haut-parleurs 3D) :
![Capture d’écran, le 2023-04-25 à 14 23 08](https://user-images.githubusercontent.com/13606544/234371333-d6097e6b-b041-4bfa-bf19-805dd87ffbab.png)

![Capture d’écran, le 2023-04-25 à 14 23 38](https://user-images.githubusercontent.com/13606544/234371665-1d1eab6e-9f53-4a78-a02b-1bc084de043f.png)

![Capture d’écran, le 2023-04-25 à 14 32 51](https://user-images.githubusercontent.com/13606544/234371774-463e9532-be5e-473c-9adb-00b1fc513ef8.png)

**Comment by led78** [comment]
Je ne suis pas certain que cela soit lié à la valeur du chiffre attribué à un haut-parleur...
On voit ici une différence nette entre 1, 2, 3, 4, etc. et 32, 31, 30, 29, etc. Mais les haut-parleurs du dessus, ayant un chiffre plus élevé, sont aussi opaques sous cet angle...
![Capture d’écran, le 2023-04-25 à 14 50 22](https://user-images.githubusercontent.com/13606544/234374655-5f011511-de80-490e-91a2-f79989545d71.png)
Mais pas vus de haut :
![Capture d’écran, le 2023-04-25 à 14 54 37](https://user-images.githubusercontent.com/13606544/234375307-75200d37-d819-4864-b42b-4f67d855363e.png)

**Comment by led78** [comment]
Dans tous les cas, je préfère la transparence :)

**Comment by Normandeau** [comment]
Gaël est entrain de refaire toute l'interface graphique. On va garder ceci pour l'après-refonte. On verra bien si c'est corrigé.

**Comment by Normandeau** [comment]
V328
Impossible de vérifier cela sur un M1-M2. Voir issue #378

**Comment by NicolaGiannini** [comment]
v328
Je pense que la transparence des haut-parleurs est actuellement gérée de la manière suivante. 

Un HP est transparent par rapport aux autres HP d'un numéro inférieur. 

Exemple : le HP 75 est transparent par rapport aux HP 64, 63, etc.

![Schermata 2023-05-13 alle 15 30 53](https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/095cedb9-4a6a-487f-b203-ac5b914b6ee2)


Un HP n'est pas transparent par rapport aux autres HP d'un numéro supérieur

Exemple : le haut-parleur 75 couvre les haut-parleurs 115, 111, 110 et 105.

![Schermata 2023-05-13 alle 15 36 35](https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/ed1d6e38-4f9c-42e2-bf1a-c6f5b5987446)

**Comment by Normandeau** [comment]
V3.3.0 avec Speaker View 0.0.0.1
Mac M2 macOS 13.6
La transparence est remarquable avec Speaker View. Testé avec Dome96 et Cube128.
