### ISSUE TITLE
💬 Discussion : est-ce que la référence à la panoramisation d'amplitude est toujours pertinente pour le MBAP?

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#399]
En employant l'acronyme MBAP, signifiant _Matrix Based Amplitude Panning_ , on inscrit l'algorithme dans la lignée des techniques de spatialisation perceptuelles antérieures (panoramisation stéréo, DBAP, VBAP, LBAP, etc.) Bien que cette association soit dans la suite logique de son développement, sur le plan étymologique, plus j'y pense et plus je réalise qu'on est rendu loin de l'idée originale de l'emploi du terme [«panoramisation», issue du cinéma, qui se rapporte à une spatialisation essentiellement horizontale et fait référence à la vision égocentrique (panorama)](https://fr.wikipedia.org/wiki/Panoramique_(audio)) plus qu'à la diffusion alocentrique que rend possible ce type d'algorithme de spatialisation. Je propose de marquer de façon plus flagrante le changement de paradigme que permet le MBAP en modifiant sa terminologie; on parle toujours de «_Matrix-Based_», mais plus d'«_Amplitude Panning_» au sens classique (horizontal et égocentrique). J'aime bien distinguer les techniques de spatialisation en deux grandes catégories :
1. Spatialisation de surface (2D sphériques) = stéréo; surround; FOA; HOA; VBAP; DBAP (cartésien), ... Donc panoramique = surface de diffusion bidimensionnelle.
2. Spatialisation volumétrique (3D cartésiennes) = LBAP (cas particulier de transition 2D->3D); MBAP (à reformuler); WFS (cas particulier très rare, perception variable selon le dispositif)... Donc volumétrique = espace de diffusion tridimensionnelle.

Voici quelques suggestions pour lancer la discussion :
MBAS (em-bass) : _Matrix-Based Amplitude Spatialisation_ 
VMAS (vee-mass) : _Volumetric Matrix Amplitude Spatialisation_ 
MBVAS (em-bee-vass) : _Matrix-Based Volumetric Amplitude Spatialisation_

Qu'en pensez-vous? Suis-je le seul qui se préoccupe du sens étymologique des expressions? ;)

_Panoramisation : «Le nom de l'effet de déplacement de la source sonore est emprunté au [panoramique](https://fr.wikipedia.org/wiki/Panoramique_(cin%C3%A9ma)) du cinéma, un mouvement horizontal de la caméra sur son axe qui fait passer un objet d'un côté à l'autre.» - Wikipédia_

**Comment by Normandeau** [comment]
Bonne discussion David. D'accord avec la précision étymologique. Pour le moment c'est un peu dommage, l'article des JIM va être publié la semaine prochaine... Cependant pour l'utilisateur, qui ne lit pas les manuels, ce qu'il voit c'est CUBE...
On a une rencontre demain où on déterminera *peut-être) la sortie d'une nouvelle version... À suivre.

Mon choix, très pragmatique:
MBAS (em-bass) : Matrix-Based Amplitude Spatialisation

Pour éviter le V et l'acronyme à 5 chiffres.
