### ISSUE TITLE
Dome, Cube, Hybrid: est-ce que le bon ordre est respecté et nouveau message

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#401]
Algorithmes

Au nombre de 3: Dome, Cube, Hybrid

Sur le plan des haut-parleurs, il n'y en a que deux: Dome ou Cube.
Sur le plan des projets, il y en a trois: Dome, Cube, Hybrid.

Comment la sélection s'opère-t-elle en ce moment?
Dans l'ordre, SS (Speaker Setup) et P (Project)
Tous ces tests ont été faits avec des template SS et des P.

Version 3.2.8.

Dans l'ordre:
1.1. SS Dome + P Dome = Dome
**Ok**
2.1. SS Cube + P Cube = Cube
**Ok**
3.1. SS Dome + P Cube = Cube. Le SS Dome a été transféré en SS Cube, sans message. La forme du SS ne change pas, puisque l'algorithme Cube accepte tous les domes (On peut confirmer cela en ouvrant la fenêtre Speaker Setup Edition).
**Ok**,  sans message. Par contre en ouvrant la fenêtre Speaker Setup Edition et qu'on la referme, sans rien changer, on reçoit ce message.

![Dome à Cube](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/eb6c599b-b0e1-49d3-958a-b3f364a94931)

Qu'est-ce que ça veut dire?
On n'a jamais eu de message lorsqu'on passait d'un Dome à un Cube. Et c'est d'autant plus étrange que ce n'est pas au moment où le passage se fait que ce message arrive, mais seulement après avoir ouvert le Speaker Setup Edition. Le même message apparait au même moment si on transfert tout simplement un Dome en Cube.
**Donc on avait parlé de ce message, mais il ne s'ouvre pas au bon moment.**

4.1. SS Cube + P Dome = Dome. Le SS Cube est converti en Dome après l'approbation du message de conversion.
**Ok**
5.1. SS Dome + P Hybrid = Hybrid.
**Ok**
6.1. SS Cube + P Hybrid = Hybrid. Le SS Cube est converti en Dome après l'approbation du message de conversion.
**Ok**

Dans l'ordre inversé:
1.2. P Dome + SS Dome = Dome
**Ok**
2.2. P Cube + SS Cube = Cube
**Ok**
3.2. P Cube + SS Dome = Dome. Le projet Cube a été transféré en Dome sans message.
Le projet Cube a été transféré en Dome **sans message**. **Est-ce que c'est cela que l'on veut?**
4.2. P Dome + SS Cube = Cube. Le projet Dome a été transféré en Cube sans message.
Le projet Cube a été transféré en Dome **sans message**. **Est-ce que c'est cela que l'on veut?**
5.2. P Hybrid + SS Dome = Dome. Hybrid disparaît de la vue alors que cela devrait être conservé. En sélectionnant Hybrid, on retrouve les attributions sauvées. On veut éviter cela. On veut conserver Hybrid.
**Ok, Hybrid est conservé**.
6.2. P Hybrid + SS Cube = Cube. Hybrid disparaît de la vue puisqu'on vient de passer en Cube. Cela est normal. En sélectionnant Hybrid manuellement, le SS Cube est converti en Dome après l'approbation du message de conversion. On retrouve les attributions sauvées.
**Ok. Cube**. Hybrid disparaît de la vue puisqu'on vient de passer en Cube. Cela est normal. En sélectionnant Hybrid manuellement, le SS Cube est converti en Dome après l'approbation du message de conversion. On retrouve les attributions sauvées.

**Comment by NicolaGiannini** [comment]
Je réponds aux points suivants.

3.1. 

D'après ce que j'ai compris, il se passe ce qui suit dans ce cas.

Situation de départ : SS DOME.

Se je sélectionne CUBE à partir de Algorithm selection, ou que j'ouvre un projet CUBE, le Speaker Setup passe de DOME à CUBE et cela est interprété par SpatGRIS comme un modification au Speaker Setup. Donc le SS devient non sauvegardé. 

Je pense que ça pourrait être correct que SpatGRIS ne demande pas immédiatement si je veux sauvegarder le SS. En effet, sauf si quelque chose m'échappe, c'est comme lorsque j'ouvre un fichier texte et que je fais des modifications, le programme ne me demande pas si je veux sauvegarder à la première modification, mais seulement lorsque je ferme la fenêtre du logiciel, par exemple. 

En revenant à SpatGRIS :
Situation de départ SS DOME + P CUBE. Le SS devient un SS CUBE non sauvegardé. Je peux vérifier cela aussi en ouvrant le menu File, maintenant je peux sauvegarder le SS.  

À ce moment si je ferme SpatGRIS, il me demande si je veux sauvegarder le SS.
Si à la place de fermer SpatGRIS, j'entre dans la Speaker Setup Edition window, je ne change rien et je ferme la fenêtre, SpatGRIS me demande si je veux sauvegarder le SS, car il détecte quand même des modifications non sauvegardées. 

4.2 et 5.2

Dans un souci de clarté, on pourrait ajouter une alerte pour signaler le changement d'algorithme, cela dit je trouve le comportement actuel probablement normal de toute façon. Ce n'est qu'en fermant la fenêtre que le programme me demande si je veux sauvegarder les modifications apportées, qui incluent le changement d'algorithme.

**Comment by OKGougou** [comment]
En effet, le message «Modified Speaker Setup» s'affiche à la fermeture de la fenêtre d'édition des speaker setups si celui-ci n'a pas été enregistré sur disque.

Pour les messages manquants, c'est vraiment un oubli de ma part...
J'avais noté ceci : un message doit être affiché si on charge un projet qui fait changer l'algorithme du speaker setup. Maintenant, suite à cette discussion, est-il nécessaire de demander d'enregistrer le speaker setup nouvellement modifié? Ça me paraît un peu lourd. Il me semble qu'un simple message avec un bouton OK informant l'utilisateur que le changement d'algorithme a eu lieu serait suffisant.

Qu'en pensez-vous?

**Comment by Normandeau** [comment]
Merci de vos commentaires. On va laisser cela comme ça. Le manuel ne sera pas tout à fait à jour. Mais de toute manière il ne l'est plus suite au commentaires de tout le monde. On aura une version rafraichie pour la prochaine version de SpatGRIS.

**Comment by NicolaGiannini** [comment]
V329
Je signale simplement une chose à prendre peut-être éventuellement en compte pour une version future. 

Lorsqu'un changement de projet entraîne une modification de l'algorithme d’un Speaker Setup, SpatGRIS maintenant signale ce changement.

Exemple : SS Dome + P Cube = Message d'avertissement = Cube

Lorsqu'un changement de Speaker Setup entraîne un changement de l'algorithme du projet, ce changement n'est pas signalé. 

Exemple : P Cube + SS Dome  = Dome, sans message d'avertissement.
