### ISSUE TITLE
Player ne replace plus les sorties directes correctement à la lecture de documents anciens

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#402]
V329
Les sorties directes assignées par le Player ne sont pas les bonnes lorsqu'on lit un document Player produit par une version ancienne de SpatGRIS.

Enregistrement d'un fichier 30 pistes à partir d'Icosa (subs sur 6-14-22-30). Cet enregistrement a été fait en septembre 2022 (version 3.1.13 ou 3.1.14, qui datent de septembre 2022).
Joué sur le dispositif Dome24(12-8-4)Subs2 NOTAM. Les Subs sur ce dispositif sont sur 25-26.
Or l'enregistrement joué assigne les sorties directes sur les sorties directes du dispositif d'origine et seulement sur les deux premières (6-14):

![Player Erreur de sorties directes](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/01246a0f-c1e7-4939-99fb-9928a87c6fed)

 et non pas sur celles du dispositif de lecture (25-26).
Testé tous mes anciens documents et ils sont tous interprétés erronément.

Par contre si je fais un nouvel enregistrement avec la version 3.29, tout est correct:
 
![Player Sorties directes Ok](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/c7300de3-daee-40e5-b511-8e78fa8450b3)

Est-ce que vous avez des documents Player anciens afin de valider cela?
Donc question: qu'est-ce qui a changé dans le Player (ou ailleurs) pour entraîner ces erreurs?

**Comment by NicolaGiannini** [comment]
Dans mon cas je n’arrive pas à reproduire l’issue. 
J’ai essayé avec des enregistrements faits avec 3.1.12 (août 22) et les assignations semblent correctes. 

J’ai essayé aussi de récréer la situation décrite par Robert. J’ai fait un enregistrement à partir de la version 3.1.13 (et aussi 3.1.14) en utilisant le Speaker Setup du studio Icosa. Je l’ai ouvert dans V329 avec le Speaker Setup Notam et les assignations me semblent correctes.


![Schermata 2023-05-17 alle 17 52 21](https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/e64d33ea-8ce8-4d74-a39d-50fcbdc8d743)

**Comment by Normandeau** [comment]
Bézarre!
Y aurait-il un comportement différent sur Intel et sur M2?

**Comment by NicolaGiannini** [comment]
Oui c'est bizzarre ! J'ai ressayé maintenant, mais le comportement me semble toujours correct.
