### ISSUE TITLE
⚡️ Faire un build de SpatGRIS avec Blackhole 256ch sous MacOS

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#404]
Je propose que la SAT soit bêta testeur pour un futur build de SpatGRIS sous Blackhole 256ch. 

On risque d'en avoir besoin assez rapidement dans la Satosphère... On aimerait pouvoir intégrer plusieurs Satotems (~50ch) et Audiodices (5x 12ch = 60ch) à l'intérieur de la nouvelle Satosphère (93.5ch), ce qui nous ferait un total possible de 208 canaux! On veut surtout valider la synchronisation des convertisseurs N/A avec Dante et le DAD Core 256 comme horloge.
Notamment grâce au MBAS, les artistes ont envi d'expérimenter avec la spatialisation volumétrique et pour cela, on va avoir besoin de plus de 128 canaux. La demande est forte!

**Comment by Normandeau** [comment]
V3.2.10
C'est fait. À tester.
