### ISSUE TITLE
L'indicateur de crête ne semble pas fonctionner pour les sources

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#405]
V329 (mais aussi les versions antérieures).

L'indicateur de crête ne semble pas fonctionner pour les sources. Dans le manuel, nous disons :

A peak indicator is present for Sources and Speakers. There is a general Reset Meter Clipping in the view menu (Opt- M).

Voir la vidéo: 

https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/5dc0b89b-748c-472b-817b-c36e5b9639e9

**Comment by Normandeau** [comment]
V3.2.10
Ce problème semble réglé.

![Crête mètre 3 2 10](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/197fc7e9-9fb0-4de6-9722-8fc1f71320c1)

**Comment by NicolaGiannini** [comment]
V3.2.10
Dans mon cas, ce problème ne semble pas réglé. Peut-être qu'il s'agit d'une question MacIntel.

**Comment by Normandeau** [comment]
En principe SpatGRIS n'est pas encore optimisé pour les Apple Silicon. Et le graphisme n'est toujours pas optimisé, donc ça ne devrait pas faire de différence.
Je viens de tester avec 319, 321 et 329, et tout fonctionne normalement.

**Comment by NicolaGiannini** [comment]
Je viens de vérifier avec Logic Pro et en effet tout fonctionne bien ! Si j’envoie du signal qui dépasse le zéro dans Logic, l’indicateur fonctionne aussi pour les sources. 

Apparemment c’est un comportement de Ableton Live (10 et 11). Même si les vu-meters dans Live sont en rouge et la valeur affichée dépasse le zéro dans la piste de Live, le signal qui arrive dans la source de SpatGRIS ne fait pas clipper le vu-meter. Les sorties de Live sont peut-être équipées d'une sorte de limiteur.  

Désolé j’aurai dû tester sur un autre DAW avant d’ouvrir l’issue!
