### ISSUE TITLE
3.2.11 : Crash dans le Speaker Setup Edition Window si on retire tous les HP en mode Dôme et que SpatGRIS est en mode Réduction Stéréo

### ISSUE THREAD

**Issue by DavidPiazza** [GRIS-UdeM/SpatGRIS#409]
macOS 13.5.1, M2 Max

Étapes pour reproduire le problème : 

1. Ouvrir un Speaker Setup Template, n'importe lequel;
2. Choisir le mode Dôme et Réduction Stéréo; 
3. Ouvrir le panneau d'édition du Speaker Setup;
4. Retirer les haut-parleurs un à un;

Le problème ne survient pas en mode Cube.

**Comment by Normandeau** [comment]
macOS 13.5.2, M2 Max, SpatGRIS 3.2.11
Je n'arrive pas à reproduire cela.
Ni en partant d'un CUBE transformé en DOME ni en partant d'un DOME ni en partant d'un CUBE.
Au contraire, étonnamment, j'arrive à sauvegarder les Speaker Setup avec aucun hp dedans... ce qui est un peu bizarre!
Bien sûr, dans l'intervalle, en DOME, on reçoit les deux messages d'avertissement suivants (les reçois-tu David?):
- Le premier à 5 hp en général:

![Capture d’écran, le 2023-09-13 à 16 49 07](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/92dc1174-e426-4d1c-a77c-fda0b0f3dbec)

-Et ensuite à 3 hp:

![Capture d’écran, le 2023-09-13 à 16 51 13](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/59b9e2f7-6f1e-4257-9175-aeded9fc43ab)

En CUBE on ne reçoit qu'un seul message:

![Capture d’écran, le 2023-09-13 à 16 59 02](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/ead5fb46-f9fe-4fda-9d55-11aa97460d13)

Bon ce n'est peut-être pas une bonne idée de vider complètement un speaker setup (on peut s'en garder un comme point de départ et le repositionner), mais comme on n'a toujours pas de fonction Reset dans la fenêtre Speaker Setup Edition, si on veut en construite un à partir de 0, on n'a pas tellement le choix de tout effacer d'abord.

**Comment by Normandeau** [comment]
Ok je viens de lire la fin de l'issue: «en mode Réduction Stéréo».
Effectivement ça plante et les messages n'apparaissent pas. Est-ce un signe de quelque chose qui cloche plus profondément? Je laisse Gaël répondre à cela.
En tout état de cause, ce n'est certainement pas une bonne idée de faire cela et qui le voudrait...

**Comment by DavidPiazza** [comment]
> En tout état de cause, ce n'est certainement pas une bonne idée de faire cela et qui le voudrait...

Quand je veux créer un Speaker Setup, et que je veux utiliser le 'Add Ring' pour avoir des anneaux de haut-parleurs avec des numéros de sorties partant de 1, je n'ai pas accès à un bouton du genre « Create a new Speaker Setup ». Je prends donc un template et j'en enlève les haut-parleurs. Qui plus est, l'option de la réduction stéréo est rappelée au démarrage de SpatGRIS, ce qui fait que le problème survient si on s'était mis en réduction stéréo avant de quitter SpatGRIS à la dernière utilisation et qu'on ne se remet pas en « None » avant de travailler.

**Comment by Normandeau** [comment]
Bon point! On fait suivre au chef de l'équipe de développement pour:
- soit corriger ce bogue
- soit ajouter une fonction comme «Create a new Speaker Setup»
- Soit les deux!!!

**Comment by NicolaGiannini** [comment]
MacOS 12.6.8 MacIntel, SpatGRIS 3.2.11
Je confirme le bug. Dans mon cas, j'ai remarqué que cela ne se produit qu'en réduction Stereo et non en réduction Binaural.

**Comment by Normandeau** [comment]
Peut-être qu'une note au manuel suffit! C'est quand même un usage inédit que de vouloir construire un speaker setup en mode stéréo!!! Il me semble qu'on a d'autres chats à fouetter...

**Comment by OKGougou** [comment]
C'est en lien avec les modifications apportées pour avoir l'atténuation du mode Cube en Stéréo.
Commit d4054bb.

Ce sera réparé dans la prochaine version.

**Comment by Normandeau** [comment]
V330 avec Speaker View 0.0.0.1
Mac M2 macOS 13.6
Ce problème semble réglé en mode Dome (cela fonctionne toujours en mode Cube). Je peux tout enlever et tout reconstruire sans problème même en mode stéréo. À confirmer.
Veuillez prendre note qu'on a ajouté dans les Templates:
- Dome0(0)Subs0
- Cube0(0)Subs0
Ces modèles de hp avec 0 haut-parleur sont là pour construire un Speaker Setup à partir de 0. Une solution plus rapide à ajouter un nouveau menu.

**Comment by NicolaGiannini** [comment]
V330 avec Speaker View 0.0.0.1
Macintel MacOS 12.7
Je confirme, ce problème semble réglé en mode Dome. Testé en mode DOME régulier, stéréo et binaural.

**Comment by Normandeau** [comment]
B331 avec Speaker View 0.0.1
Réglé dans ces nouvelles versions également
