### ISSUE TITLE
Speaker View: Double-clic de souris, agaçant

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#411]
Speaker View V 0.0.0.1
Une petite chose agaçante, surtout après des années d'utilisation de SpatGRIS. La fenêtre de Speaker View nécessite toujours deux clics de souris avant d'être active.
Ainsi, si je passe de SpatGRIS à Speaker, je dois d'abord activer Speaker View avec un premier clic de souris et ensuite, au 2e clic de souris, là je peux bouger la fenêtre 3D.
Ce n'est pas le cas en général sur Mac, et ça devient agaçant à la longue (même à la courte...).
Par exemple, si SpatGRIS n'est pas actif et que je pointe la souris sur un des mute de Sources et que je clique, celui-ci sera automatiquement en fonction. Pas besoin de passer par un premier clic de souris sur SpatGRIS.

**Comment by DavidPiazza** [comment]
Je pense qu'en effet, la fenêtre de Speaker View (et, en général, c'est le cas de toutes les fenêtres visibles sur macOS) devrait être actionnable même si celle-ci est hors focus.

**Comment by OKGougou** [comment]
Le «click through» (fenêtre qui reçoit l'input de la souris lorsqu'elle n'a pas le focus) est un comportement par défaut sous Windows et Linux, mais pas sous MacOS. Il faut le forcer, ce que [JUCE fait](https://github.com/search?q=repo%3Ajuce-framework%2FJUCE%20acceptsFirstMouse&type=code), mais pas Godot. Godot se sert du comportement par défaut sous MacOS : pour interagir (avec la souris) avec une application qui n'a pas le focus, il faut d'abord maintenir la touche Command enfoncée.

**Comment by Normandeau** [comment]
Ce n'est pas la première qu'on se fait dire que le comportement du Mac n'est pas le même que sur les autres OS. Mais on travaille sur Mac donc il faut corriger cela.

**Comment by Normandeau** [comment]
D'autant plus que Command-Clic ne règle rien. Bien sûr on peut bouger le setup en utilisant cette combinaison, mais cela ne ramène pas la fenêtre de Speaker View au premier plan pour autant. Il faut toujours cliquer deux fois ensuite pour la ramener.

**Comment by Normandeau** [comment]
V 0.0.1
Vive le Mac!!!
