### ISSUE TITLE
Speaker View: les Spans sont un peu pâlotte!

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#412]
V 0.0.0.1

La représentation des Spans est pas mal pâlotte dans Speaker View!
Pour ne pas dire invisible...

ControlGRIS originel avec des Spans assez larges:

![Capture d’écran, le 2023-10-02 à 12 37 24](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/7d0570bf-cf56-41b6-ac29-cd23d68282d7)

Représentation dans Speaker View:

![Vue dans Speaker View](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/53c3df6a-1bf0-4b62-b95c-8e2d17a46187)

Représentation dans SpatGRIS 3.2.11:

![Capture d’écran, le 2023-10-02 à 12 35 26](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/bad23271-17b3-4792-9328-897c41da8e31)

**Comment by NicolaGiannini** [comment]
Je confirme que les spans pourraient être un peu plus visibles.

**Comment by Normandeau** [comment]
0.0.1
C'est Noël!

![Spans visibles](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/aec360b9-34cc-4c0c-bf4c-91c9766b33b6)
