### ISSUE TITLE
Speaker View: emplacement de la fenêtre, possible qu'elle se souvienne?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#413]
V 1
Gaël: «La première fois que SpatGris lance SpeakerView (au sein d'une même session d'utilisation de SpatGris), la fenêtre apparaît au centre de l'écran, mais elle devrait  conserver dimensions et position si elle est fermée puis rouverte.»
N'y a-t-il pas moyen que la fenêtre de Speaker View se souvienne «toujours» de son dernier emplacement? Comme SpatGRIS ou les DAW? Ou qu'elle se colle à la gauche de SpatGRIS quand on ouvre ce dernier? Bref, quelque chose qui fasse qu'on ne soit pas obligé de la déplacer chaque fois qu'on ouvre une nouvelle session.

**Comment by NicolaGiannini** [comment]
V1
MacIntel MacOs 12.7
D'après les tests que j'ai effectués, la fenêtre ne conserve ni sa position ni sa dimension.

**Comment by DavidPiazza** [comment]
V1
M2 Max, macOS 14

Même chose de mon côté.

**Comment by Normandeau** [comment]
V 0.0.1
Quelle mémoire!!!
