### ISSUE TITLE
Speaker View: un hp sélectionné dans Speaker Edition n'est pas désélectionnable dans la vue 3D

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#414]
V 1
Speaker View: un hp sélectionné dans Speaker Edition n'est pas désélectionnable dans la vue 3D.
Contrairement à SpatGRIS où en cliquant dessus il est désélectionné.
D'ailleurs c'est plus compliqué que cela.
En ouvrant la fenêtre Speaker Edition, on peut certes le désélectionné, mais il en reste toujours un qui est sélectionné, y compris dans SpatGRIS.
Il y a donc toujours un hp orange dans la vue 3D à partir du moment où on fait de l'édition.
La seule façon de se débarrasser de cela est de sauver le setup et de le rappeler.

![Capture d’écran, le 2023-10-03 à 14 56 27](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/acdd8939-0ae3-4554-9176-d6302bbb4503)

**Comment by NicolaGiannini** [comment]
Je confirme. Le même comportement est obtenu si on sélectionne un haut-parleur dans Speakerview on essaye de le désélectionner.

**Comment by Normandeau** [comment]
Pas certain de comprendre: on ne peut pas sélectionner un hp dans SpeakerView.

**Comment by NicolaGiannini** [comment]
Je me réfère à cela : 


https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/f40c677b-5c4d-4f22-9026-4eb01ec3cd40

**Comment by Normandeau** [comment]
V 0.0.1
Les HP sont maintenant désélectionnables dans la vue 3D... mais seulement par là! On ne peut pas désélectionner un hp en cliquant sur le no du HP dans l'onglet Speakers de SpatGRIS. On doit obligatoirement le désélectionner dans la fenêtre 3D. Ce n'est pas bien grave, mais avant on pouvait le faire n'importe où avec le clic-droit de la souris.

![Capture d’écran, le 2023-11-09 à 15 32 21](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/9825c59b-5f20-4f2c-8db3-fecd75d43708)

**Comment by NicolaGiannini** [comment]
V 0.0.1
Dans Speakerview pour désélectionner un HP il faut cliquer une autre fois sur le même HP.

Dans les versions précédentes à SpeakerView, pour désélectionner il fallait faire clic droit, peu importe où.

Dans mon cas dans les versions précédentes à SpeakerView, je n'arrive pas à désélectionner un hp en cliquant sur le no du HP dans l'onglet Speakers de SpatGRIS (testé sur 3.1.9 et 3.2.11).

**Comment by Normandeau** [comment]
Bonne remarque Nicola, Je devais rêver à cela...
