### ISSUE TITLE
Les Spans ne fonctionnent pas bien en mode Hybrid et Cube

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#416]
SV 1
Les Spans ne fonctionnent pas en mode Hybrid et Cube.
Sur le plan visuel d'abord, en mode **Hybrid**, le span d'élévation est on/off seulement et celui d'azimuth ne s'affiche pas.
Sur le plan sonore Elevation Span ne fonctionne pas,  azimuth oui (on voit ici qu'il fonctionne grâce à l'activité des hp):

https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/fd956972-97f0-42b2-874d-1195af17565f

En mode **Cube**, c'est la même chose sauf que le cube dessiné est plus petit qu'en mode hybride:

https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/d7cdee88-bb91-456f-aa68-bf5a29531df0

**Comment by OKGougou** [comment]
Je n'arrive pas à reproduire ce bug.
Est-ce qu'on obtient le même résultat après avoir exécuté «Reset Sources Positions» ?

**Comment by Normandeau** [comment]
Moi non plus!!!!
Testé avec la même session test de DP et le même projet Hybride, tout fonctionne! Je n'ai pas eu besoin de faire aucun reset...
Ça fonctionne!

Par contre, c'est la première fois que je remarque cela, le fond de la chambre (Show Room) est très clair, contrairement aux murs, au plancher et au plafond.
C'est sur un écran 4k haute résolution.
Cela a pour effet de faire disparaître les hp du haut en mode Show Speaker Level.
Possibilité d'ajouter un ajustement de contraste selon l'élan utilisé?

![Show Room très clair](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/9d96f142-0583-43ae-a0df-624ccc3f3ccf)

Et même en enlevant l'option Show Speaker Level, les hp du haut sont presque invisibles:

![Show Room très clair Show Speaker](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/38d3a463-79a3-408e-9ddb-549fa109b2a0)

**Comment by DavidPiazza** [comment]
V1
M2 Max, macOS 14

Les hp sont en effet très clairs; le problème n'est pas trop dérangeant de mon côté, je règle ça en changeant d'angle et il nous est toujours possible d'utiliser SpeakerView sans la vue de la salle.

**Comment by Normandeau** [comment]
C'était corrigé pour moi une fois, mais aujourd'hui, le problème est revenu. Il semble qu'on soit en face d'un problème intermittent.
Comme mentionné hier, le Reset Sources Positions semble régler le problème. À valider.

**Comment by NicolaGiannini** [comment]
SV 1
Macintel MacOs 12.5.1
Je pense qu'il se passe ce qui suit.

Les valeurs du span de la dernière source (par rapport à la valeur source ID) du projet contrôlent le span (s'il est actif) des sources avec les sources ID précédents. Lorsque le span de la dernière source n'est plus actif, le contrôle passe à la source précédente (à condition que le span de cette source soit actif). 
Voir la vidéo.

https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/5fff1e85-f343-4bc0-a8f9-17192ad96c6d



1 Contrôle du span des sources 1 et 2.
2 Contrôle du span de la source 3 : dès que le span est actif, la source 3 contrôle également les sources 1 et 2.
3 Contrôle du span de la source 4 : dès que le span est actif, la source 4 contrôle également les sources 1, 2 et 3.
4 Processus inverse.


"Reset sources positions" dans mon cas ne change pas la situation.
J'ai le même comportement en mode HYBRIDE et CUBE.

**Comment by Normandeau** [comment]
Wow, belle trouvaille Nicola.
Je confirme tout, y compris que ni le Reset Sources Position ni le fait de fermer Speaker View ne corrige la situation.

**Comment by Normandeau** [comment]
Une précision: «… ni le Reset Sources Position ni le fait de fermer Speaker View ne corrige la situation» tant que la session du DAW est active. Évidemment dès qu'on la ferme, alors ces fonctions redeviennes opérantes.

**Comment by Normandeau** [comment]
V 0.0.1
Ça semble être réglé. Confirmation les autres?

**Comment by NicolaGiannini** [comment]
V 0.0.1
Ça semble réglé aussi de mon côté.

**Comment by DavidPiazza** [comment]
De même pour moi.

**Comment by Normandeau** [comment]
Bravo
