### ISSUE TITLE
La sélection d'un haut-parleur dans la Speakerview nécessite un double clic, alors que dans l'ancienne fenêtre 3D, un seul clic suffisait

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#417]
Speakerview 0.0.0.1
La sélection d'un haut-parleur dans la Speakerview nécessite un double clic, alors que dans l'ancienne fenêtre 3D, un seul clic suffisait, probablement je le trouvais plus pratique.

**Comment by DavidPiazza** [comment]
Et le clic droit pour désélectionner les haut-parleurs était bien aussi!

**Comment by Normandeau** [comment]
V 0.0.1
Voir #414
