### ISSUE TITLE
Speakerview, est-il nécessaire que ce soit une application autonome par rapport à SpatGRIS ? 

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#418]
V1

Ce n'est pas vraiment un bogue, mais je pense plutôt à l'ergonomie.
Est-il nécessaire que Speakerview soit une application autonome par rapport à SpatGRIS ? 
Peut-être y a-t-il des raisons techniques pour lesquelles Speakerview doit être une application séparée ?

Le fait d'avoir deux applications distinctes entraîne certaines situations dans l'interaction avec le système.

1) Une fois lancée SpatGRIS, on doit aussi lancer Speakerview. Si ce n'est pas possible d'intégrer Speakerview dans SpatGRIS, elle pourrait être lancée automatiquement ?

2) C'est toujours nécessaire de remettre la fenêtre de Speakerview en premier plan. Entre DAW, SpatGRIS, Speakerview et possiblement d'autres logiciels, ça peut devenir pas facile de retrouver Speakerview. Si ce n'est pas possible d'intégrer Speakerview dans SpatGRIS, ne serait-il pas possible  d'avoir une option pour coller Speakerview à gauche de SpatGRIS, comme c'était le cas auparavant ? Voir aussi issue : https://github.com/GRIS-UdeM/SpatGRIS/issues/411

3) Les commandes pour Speakerview sont maintenant répétées dans SpatGRIS et Speakerview, (sauf les derniers 5 commandes dans Speakerview qui maintenant sont seulement dans cette application).

4) Au niveau de l'installation, je ne sais pas si je donnerais à l'utilisateur-rice la possibilité de ne pas installer Speakerview.

Qu'en pensez-vous ?

**Comment by Normandeau** [comment]
On discutera de tout cela demain à la réunion. Gaël pourra répondre à nos questions à ce sujet.
Et aussi de l'endroit où poster ce genre de questionnement. Je ne pense pas que Github soit le bon endroit et on a GRIS-dev pour cela. À demain.
