### ISSUE TITLE
Menu View: Ajouter Cmd-W sur les fenêtres ouvertes?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#420]

**Comment by Normandeau** [comment]
Menu View
Je constate que certains menus de View sont en mode On/Off et d'autres en monde On seulement. Autrement dit le raccourci clavier appelle la fonction ou la fenêtre, mais l'utiliser à nouveau n'annule pas la commande précédente. Les fonctions ou fenêtres en mode On seulement ne se résolve qu'avec la souris.

On seulement

Show 2D view
Speaker Setup Edition
Show Player View
Tous les menus de la section du bas (en fait, ils n'ont pas de Undo).
On-Off

Show Speaker View
Tous les menus de la partie centrale
On voit donc que seul Show Speaker View n'est pas dans la bonne section car dans les faits, il y a trois groupes de menus:

Haut: On seulement
Central: On/Off
Bas: On seulement
Les On seulement correspondent à l'ouverture des fenêtres: 2D, Setup Edition et Player.
Veut-on les fermer avec le même raccourci?
Si ça fonctionne avec Show Speaker View, pourquoi pas avec les autres?
Pour être plus cohérent, si possible mettre tous les menus en mode On/Off.

**Comment by Normandeau** [comment]
![Capture d’écran, le 2023-10-19 à 08 06 34](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/564e1bd7-2b9b-489c-90e3-b442342b1bbc)

**Comment by NicolaGiannini** [comment]
Robert: 

>  si possible mettre tous les menus en mode On/Off.

Je seconde.

**Comment by OKGougou** [comment]
Pour les menus du haut, je peux très bien les mettre On/Off, comme SpeakerView. Les menus du bas effectuent des actions en un seul coup et ne peuvent pas être On/Off.

**Comment by OKGougou** [comment]
Mais est-ce pertinent de mettre les menus du haut On/Off? Si on se sert de ces menus, c'est pour ouvrir une fenêtre ou la ramener au premier plan si elle déjà ouverte.
Ne serait-ce pas plutôt le menu de SpeakerView qui devrait être On seulement?

**Comment by Normandeau** [comment]
«Si on se sert de ces menus, c'est pour ouvrir une fenêtre ou la ramener au premier plan si elle déjà ouverte.»
Pas toutes:
- Show 2D View: ramène au 1er plan. Pas de √ au menu.
- Speaker Setup Edition: elle est toujours au 1er plan. Pas de √ au menu.
- Show Player View: ramène au 1er plan. Pas de √ au menu.
- Show OSC Monitor: pas de shortcut. On ne peut pas la ramener au 1er plan. Pas de √ au menu.
- Show Speaker View: le raccourci sert à ouvrir et à fermer la fenêtre, qu'elle soit au 1er ou au 2e plan. Si elle est au 2e plan, elle ne vient pas au premier, elle se ferme en arrière-plan. La seule option **qui a un √ au menu** lorsque la fenêtre est ouverte: pourquoi cela?

On a donc plusieurs comportements différents dans cette section.

J'enquête rapidement sur le comportement des DAWs. 
- DP: Les raccourcis servent à ouvrir ou à faire passer au 1er plan les différentes fenêtres ouvertes. Un shortcut universel dans Mac est utilisé pour fermer une fenêtre: Cmd-W. Si un raccourci ouvre une fenêtre dans la fenêtre principale, elle ne peut se fermer qu'en cliquant la case appropriée (comme dans SpatGRIS actuellement) (PS Il y a des milliers de raccourcis dans DP).
- Logic: Les raccourcis servent à ouvrir ou à faire passer au 1er plan les différentes fenêtres ouvertes. Un shortcut universel dans Mac est utilisé pour fermer une fenêtre: Cmd-W, autant pour les fenêtres indépendantes que pour celles qui s'ouvrent dans la fenêtre principale du DAW.
- Reaper: la plupart des raccourcis servent à ouvrir des fenêtres qui restent au 1er plan. Le même raccourci ou Cmd-W sert à fermer la fenêtre. Si la nouvelle fenêtre s'ouvre dans le DAW, c'est le raccourci qui la ferme. Il ne semble pas y avoir de fenêtres qui puissent passer en arrière-plan (ce qui est probablement une bonne idée considérant la quantité effarante de fenêtres potentielles de Reaper...).

Donc nouvelle proposition pour la section du haut, pour être conforme avec les comportements observés ailleurs:
- les raccourcis servent à ouvrir ou à faire passer au 1er plan;
- Cmd-W est ajouté partout pour fermer les fenêtres.
- Pas nécessaire d'ajouter un √ dans ces menus. Dans les DAWs, il y a toujours un menu Window qui dresse la liste des fenêtres ouvertes. Cela se comprend considérant le nombre de fenêtre potentielles. Je ne crois pas que ce soit nécessaire avec SpatGRIS.

**Comment by NicolaGiannini** [comment]
Robert dit : 

> - les raccourcis servent à ouvrir ou à faire passer au 1er plan;
> - Cmd-W est ajouté partout pour fermer les fenêtres.
> - Pas nécessaire d'ajouter un √ dans ces menus. Dans les DAWs, il y a toujours un menu Window qui dresse la liste des fenêtres ouvertes. Cela se comprend considérant le nombre de fenêtre potentielles. Je ne crois pas que ce soit nécessaire avec SpatGRIS.

Je seconde tout cela.

**Comment by NicolaGiannini** [comment]
V 0.0.1

"Show Speaker View" est toujours nécessaire en considérant que maintenant la fênetre s'ouvre avec SpatGRIS et elle est toujours au premier plan ?

Sinon je notais que dans mon cas Cmd-W ne ferme pas les fenêtres

**Comment by DavidPiazza** [comment]
> V 0.0.1
> 
> 
> 
> "Show Speaker View" est toujours nécessaire en considérant que maintenant la fênetre s'ouvre avec SpatGRIS et elle est toujours au premier plan ?
> 
> 
> 
> Sinon je notais que dans mon cas Cmd-W ne ferme pas les fenêtres
> 
> 

Cmd-W devrait définitivement pouvoir fermer la fenêtre. Conséquemment, selon moi, l'option "Show Speaker View" doit rester dans SpatGRIS puisque l'utilisateur devrait avoir le choix d'ouvrir et de fermer Speaker View.

**Comment by NicolaGiannini** [comment]
David dit : 

> l'utilisateur devrait avoir le choix d'ouvrir et de fermer Speaker View

Je suis totalement d'accord. Ignorez mon commentaire précédent.

**Comment by Normandeau** [comment]
V 3.3.1 expérimentale... Sera intégrée à la version 3.3.2.
Cmd-W est maintenant associée à toutes les fenêtres du menu View.
