### ISSUE TITLE
Compilation on Linux fail - MbapAttenuationConfig struct instance name problem

### ISSUE THREAD

**Issue by edumeneses** [GRIS-UdeM/SpatGRIS#422]
When trying to compile SpatGRIS for Linux (Ubuntu 22.04), the compiler complains about the name of the MbapAttenuationConfig instance. Once changing the name of the instance and all its calls, the error gets fixed.

I modified the *sg_AudioStructs.hpp*, *sg_LogicStrucs.cpp*, and *sg_MbapSpatAlgorithm.cpp* files to solve the problem.

**Comment by edumeneses** [comment]
I created PR #423 to fix the issue for Linux (tested on Ubuntu 22.04).

**Comment by led78** [comment]
Is that issue fixed?

**Comment by edumeneses** [comment]
Yes, it is. Thank you. As it seems the issue was fixed without merging #423, please feel free to close the PR.
