### ISSUE TITLE
Show Vbap Spans Complete Sphere: la quadrature du cercle?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#424]
V 0.0.1
ControlGRIS 142 en mode CUBE
SpatGRIS mode Hybrid: Source 1: DOME; Source 2: CUBE. 
Speaker View: Show Vbap Spans Complete Sphere
Voici ce que ça donne à voir.
Est-ce à dire qu'on peut maintenant gérer un dôme sous le plancher?

![Capture d’écran, le 2023-11-09 à 16 04 12](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/767e4305-f0a7-4235-a2fd-58e0fd0ee078)

**Comment by NicolaGiannini** [comment]
V 0.0.1
Je confirme qu'avec ControlGRIS en mode CUBE on peut placer des sources dans un Setup DOME sous le plancher.

**Comment by DavidPiazza** [comment]
En mode Dôme, SpatGRIS interprète correctement les angles d'élévations qui excèdent 90 degrés, sauf que les spans cessent de fonctionner. On peut placer des sources et les haut-parleurs réagissent, mais les Spans ne fonctionnent pas.

En MBAP, les spans fonctionnent. La solution actuelle pour spatialiser dans une sphère de haut-parleurs est d'utiliser des messages OSC envoyant des coordonnées polaires de rayon 1 en mode Cube.

**Comment by NicolaGiannini** [comment]
David dit : 
 

> sauf que les spans cessent de fonctionner.

David, même si tu actives "Speaker View: Show Vbap Spans Complete Sphere" ?

**Comment by DavidPiazza** [comment]
> David, même si tu actives "Speaker View: Show Vbap Spans Complete Sphere" ?

L'option ne fait que changer l'apparence des spans, les haut-parleurs ne suivent pas.

**Comment by Normandeau** [comment]
Bonnes remarques David. Je confirme.
Je mets cela comme un bogue, car ça ne fait pas ce que ça doit faire (ou ne pas faire...)

**Comment by NicolaGiannini** [comment]
V322 et SV002
Les spans en mode DOME ne vont pas sous le sol.

**Comment by Normandeau** [comment]
Effectivement, mais ça on le sait. C'est comme cela que ça ne fonctionne pas... Pour le Full Dome, il faut être mode Cube ou Hybrid. C'est dans le manuel. Un jour peut-être, si jamais quelqu'un en formule le souhait, on mettra un homme là-dessus!
