### ISSUE TITLE
Installer une version antérieure à 3.3.1 efface cette dernière. Normal?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#425]
V 3.3.1 et 3.2.11
La dernière version de SpatGRIS, 3.3.1, est installé dans un dossier distinct qui se nomme GRIS dans le dossier des Applications. Alors contrairement aux versions précédentes qui s'installaient les unes à côté des autres, je n'ai pas ressenti le besoin (dans mon vécu) de renommer 3.3.1 avant l'Installation d'une version antérieure (par exemple en la nommant SpatGRIS331) puisqu'elles ne résident pas dans le même dossier. Mais la version 3.3.1 est écrasée par la version 3.2.11, même si elles ne cohabitent pas dans le même dossier. Sur Mac c'est plutôt étonnant...
Normal?

**Comment by Normandeau** [comment]
L'inverse est vrai aussi. La nouvelle version 331 efface la version installée 3211, même si elles ne sont pas dans la même dossier.

**Comment by NicolaGiannini** [comment]
V 3.3.1 et 3.2.11
Exact, hier j’ai noté la même chose.
Maintenant j'ai 3.2.11 et 3.3.1 ensemble. 

Dans mon cas, la 3.3.1 avait effacé la 3.2.11. 

- Alors j'ai effacé aussi la 3.3.1. 
- J'ai installé la 3.2.11 et je l'ai renommé. 
- J'ai réinstallé la version 3.3.1. 

Tout semble fonctionner.
Pour la 3.3.1 sur GitHub on dit "but it is not advisable to rename anything inside this folder" 

Mais si on ne peut pas renommer la 3.3.1 et qu'on installe une version pré-SpeakerView, probablement on efface la 3.3.1.

**Comment by Normandeau** [comment]
Oui et c'est cela qui est un peu étrange. Comment se fait-il que la version à l'intérieur du dossier soit effacée quand on installe une version qui se place dans le un dossier différent, le dossier Applications?
Parce qu'on fait souvent ce genre de va-et-vient entre les versions. Personnellement je ne laisse pas tout installé. Mais peut-être qu'il faudra le faire à l'avenir. Pour l'utilisateur moyen, c'est comme les autres applications. Tu installes une nouvelle version, elle efface l'ancienne. Certaines te posent la question avant de le faire...

**Comment by Normandeau** [comment]
Après discussion c'est normal... On mettra tout de même une note dans le lLisez-moi de l'installeur et dans le manuel au sujet de la création du menu GRIS dans le dossier Applications.
