### ISSUE TITLE
Avec la fonction Show Speaker Level activée, les sorties directes sont presque invisibles

### ISSUE THREAD

**Issue by NicolaGiannini** [GRIS-UdeM/SpatGRIS#427]
V331
SW 0010
Avec la fonction Show Speaker Level activée, les sorties directes sont presque invisibles, lorsqu'aucun signal audio ne leur est envoyé : 

![Schermata 2023-11-13 alle 2 29 02 PM](https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/6f8fba7c-24ea-4ef5-beb2-22e8020bdae3)

Lors de l'envoi d'un signal audio, les haut-parleurs deviennent visibles : 

![Schermata 2023-11-13 alle 2 29 32 PM](https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/666748c0-c425-4862-82fb-62abc51bd492)

Voici le comportement visuel pré-SW.

Avec la fonction Show Speaker Level activée et lorsqu'aucun signal audio ne leur est envoyé, les sorties directes sont visibles : 

![Schermata 2023-11-13 alle 2 30 35 PM](https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/90d0830c-3d9c-4385-a975-54a54128207f)

Lors de l'envoi d'un signal audio :
![Schermata 2023-11-13 alle 2 31 08 PM](https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/5a37c478-07d6-4572-acc7-51f224f6dc72)

Avec la fonction Show Speaker Level désactivée, le résultat est identique : 

![Schermata 2023-11-13 alle 2 32 27 PM](https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/cb954849-560a-402d-a15b-614fa8660185)

Il peut être utile de différencier la couleur des sorties indépendantes par rapport à celles normales lorsque la fonction Show Speaker Level est active. Cependant, lorsqu'aucun signal audio n'est envoyé, les haut-parleurs devraient être plus visibles. Peut-être pourraient-ils simplement être plus foncés ?

**Comment by Normandeau** [comment]
V 3.3.1 expérimentale... Sera intégrée dans la version 3.3.2.
Des arêtes ont été ajoutées aux hp afin de favoriser les contrastes. Ça fonctionne autant avec Show Speaker Level que sans.
