### ISSUE TITLE
Can’t load SpeakerView window when ASIO driver is selected as the audio device type in SpatGRIS settings. +++ Can’t load the SpeakerView Window when JACK is opened and running in the background. 

### ISSUE THREAD

**Issue by GabrielCaux** [GRIS-UdeM/SpatGRIS#428]
SpatGRIS v3.3.1
Computer information: Asus on Windows 10.  i7-4770 Processor
Graphic card: GeForce RTX 3070 Ti

J’ai téléchargé la nouvelle version de SpatGRIS 3.3.1. Je peux ouvrir le SpeakerView et tout fonctionne, mais quand JACK est ouvert et entrain de runner, alors je ne peux pas ouvrir le SpeakerView dans SpatGRIS. Je reçois l’erreur : Godot Engine is not responding. Impossible alors d’utiliser SpatGRIS sur Windows pour moi avec la nouvelle version pour le moment. It also appears that Speaker View doesn’t load when it’s ASIO driver that is selected in the settings audio device type. JACK uses the ASIO driver. Here is a video to demonstrate the problem:

https://udemontreal-my.sharepoint.com/:v:/g/personal/gabrielle_caux_1_umontreal_ca/EXPt_Q7uUmZJhlGFJxWJycQB-Shavx4Ziqc92ENmfOWa6Q?e=wznHQm&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZyIsInJlZmVycmFsQXBwUGxhdGZvcm0iOiJXZWIiLCJyZWZlcnJhbE1vZGUiOiJ2aWV3In19  

Dans la video: 
0:00: JACK et SpatGRIS sont ouverts sur mon desktop. 
0:03 : Dans SpatGRIS j’appuis sur l’onglet view --> show speaker view.
0:04: la fenêtre du Speaker View s’ouvre, mais ne load pas.
1 :17 : j’appuis sur X, une boite d’erreur apparait : Godot Engine is not responding.
1 :28 : j’appuis sur close the program, ce qui ferme la fenêtre du Speaker View.
1 :34 : je quitte le programme de JACK.
1 :38 : je retourne dans SpatGRIS, j’appuis de nouveau sur Show Speaker View
1 :39 : La fenêtre de Speaker View s’ouvre et load sans problème.

**Comment by GabrielCaux** [comment]
Précision: même quand le programme JACK est fermé, je n'arrive pas à ouvrir le SpeakerView avec ASIO de sélectionné comme audio device type dans SpatGRIS. La fenêtre SpeakerView s'ouvre et load bien lorsque je sélectionne d'autres audio device type comme: Directsound, Windows Audio... Mais JACK ne reconnait pas ces drivers. Maybe I need to download another audio driver, not sure which

**Comment by OKGougou** [comment]
Quelle est la carte son utilisée? Une carte son externe, ou bien celle de l'ordinateur?

**Comment by GabrielCaux** [comment]
C'est la carte son de l'ordinateur. J'ai NVIDIA et Realtek

**Comment by OKGougou** [comment]
Est-ce que la carte son peut autoriser les applications à demander une utilisation exclusive? Je pense qu'il faut désactiver le mode exclusif. Pour le savoir:

- clic droit sur l’icône de son -> Son
- onglet Lecture
- cliquer sur le périphérique de son utilisé et choisir Propriétés
- onglet Avancée -> Mode exclusif
- Désactiver Autoriser les applications à prendre le contrôle

**Comment by GabrielCaux** [comment]
J'ai désactivé le mode exclusif pour toutes les composantes de son, mais la fenêtre speaker view ne load toujours pas

**Comment by OKGougou** [comment]
Je viens de réussir à reproduire le bug.

Il survient seulement (je pense) lorsque QjackCtl utilise ASIO4ALL comme interface.
Godot (engin de jeu vidéo utilisé pour construire SpeakerView) offre une sortie audio, même si SpeakerView ne l'utilise pas. Le taux d’échantillonnage de cette sortie est fixé à 44.1kHz, et il entre apparemment en conflit avec ASIO4ALL.
Il y a une option dans le panneau de configuration de ASIO4ALL qui permet de le re-échantillonnage et qui règle le problème : Always Resample 44.1kHz <=> 48kHz :
![ASIO4ALL](https://github.com/GRIS-UdeM/SpatGRIS/assets/75331877/d11b2a6a-8ed4-45d8-982a-44cbfe9aab7f)

J'ai ajusté la FE à 48kHz par défaut pour SpeakerView et le problème est aussi réglé. (Il n'y a pas moyen de désactiver complètement l'audio (de façon simple et rapide) dans Godot.)

**Comment by OKGougou** [comment]
Bon, après plusieurs tests de différences entre les taux d'échantillonnage SpeakerView/QjackCtl et ASIO4ALL, je n'arrive plus à reproduire le bug, même avec la configuration qui posait problème à l'origine...

Je remarque une chose avec le panneau de configuration de ASIO4ALL: les paramètres changés ne survivent pas à un redémarrage audio par QjackCtl. Il faut les modifier à chaque fois.

**Comment by OKGougou** [comment]
> J'ai ajusté la FE à 48kHz par défaut pour SpeakerView et le problème est aussi réglé. (Il n'y a pas moyen de désactiver complètement l'audio (de façon simple et rapide) dans Godot.)

En fait, je viens de me rendre compte qu'il est possible de désactiver l'audio dans Godot. Ça devrait nous éviter tout ce disgracieux ballet de contre-configuration avec ASIO4ALL. Merci @GabrielCaux.

**Comment by GabrielCaux** [comment]
@OKGougou J'ai essayé d'ouvrir le speakerview avec le 44 to 48Hertz de coché dans ASIO4ALL mais ça ne fonctionne quand même pas pour moi. J'ai une question, est-ce que je dois manuellement désactiver l'audio dans Godot moi-même, ou bien tu veux dire que tu vas faire une version de SpatGris ou l'audio de Godot est désactiver? donc je devrai juste retélécharger SpatGris?

**Comment by OKGougou** [comment]
Ce sera une nouvelle version de SpeakerView (0.0.2) dans laquelle l'audio sera désactivée.

**Comment by Normandeau** [comment]
V 0.0.2
Problème réglé?

**Comment by GabrielCaux** [comment]
Oui, maintenant ça fonctionne avec speakerview 0.0.2  :)

**Comment by Normandeau** [comment]
Wow, belle job team! On commence à prendre soin de la communauté Windows. Excellent.
