### ISSUE TITLE
Unchecking ControlGris plugin during Spatgris download seems to uninstall Controlgris (on Windows)

### ISSUE THREAD

**Issue by GabrielCaux** [GRIS-UdeM/SpatGRIS#429]
Après avoir downloadé la version 3.3.1 de SpatGris, j'ai ouvert un ancien projet. Les plugin ControlGris qui étaient sur mes tracks ne fonctionnent plus (ils n'existent plus, comme s'ils avaient été deletés). Je perds donc les automations et indications qui étaient sauvegardées dans le plugin. Je peux aller chercher un nouveau plugin ControlGris et le glisser sur la track et là ça fonctionne. Donc pour partir de 0 c'est bien, mais je n'ai pas accès à mes anciens paramètres de cette façon.

**Comment by Normandeau** [comment]
Question: est-ce que l'installer Windows installe tout automatiquement: Speaker View, SpatGRIS et ControlGRIS? Ou y a-t-il des options différentes pour chaque logiciel/plugiiciel comme sur Mac?

![Capture d’écran, le 2023-11-25 à 17 07 02](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/df83a8c0-684e-40e9-ac23-2b293b38cac5)

**Comment by GabrielCaux** [comment]
Il y a aussi différentes options pour chaque logiciel pour l'installation sur PC. Je n'avais pas sélectionné le plugin de control gris lors de l'installation puisque je l'avais déjà sur mon ordi, mais je pense qu'il faut quand même le sélectionner pour ne pas l'effacer?

**Comment by Normandeau** [comment]
Normalement c'est plutôt le contraire. Sur Mac en tout cas, je ne réinstalle pas ControlGRIS, lorsqu'il n'y a pas de nouvelles versions. Je crois que l'option activée par défaut, mais en général (mais ça va peut-changer bientôt), ce n'est pas nécessaire car on a eu peu de nouvelles versions de ControlGRIS, en comparaison de celles de SpatGRIS.

**Comment by GabrielCaux** [comment]
Je vais faire plus de tests avec des anciennes version de spatgris

**Comment by GabrielCaux** [comment]
Je ne sais vraiment pas pourquoi ça a réinitialisé tout le plugin puisque je ne l'avais pas sélectionné lors de l'installation justement

**Comment by GabrielCaux** [comment]
J'ai ouvert un vieux projet avec vraiment beaucoup de tracks et le plug-in de controlgris fonctionne et a conservé toutes les automations. Je pense que p-e si l'installation de controlgris n'est pas sélectionné lors de l'installation d'une nouvelle version de spatgris ça désinstalle le plug-in de controlgris sur Windows..

**Comment by GabrielCaux** [comment]
Ok c'est effectivement ça, j'ai testé et il faut absolument que les plugins de Controlgris soient sélectionnés lors de l'installation d'une nouvelle version de Spatgris sur Windows, même s'ils étaient déjà installés auparavant, sinon ça les désinstallent. 

1-J'ai redownloadé la version 3.2.11 (latest) de Spatgris et le controlgris 1.4.2 avec tout de sélectionné. Tout fonctionne à l'ouverture de ma session ableton.
2-J'ai ensuite redownloadé la nouvelle version 3.3.3 de Spatgris et cette fois-ci je n'ai pas sélectionné control gris 1.4.3 lors de l'installation. Pourtant ce plug-in était déjà installé préalablement car j'avais déjà downloadé la version 3.3.3 et le controlgris 1.4.3 auparavant... Un message aparait pour me dire que control gris 1.4.3 sont déjà installés sur ma machine et que ''deselecting these components will not uninstall them''

![deselectingwillnotdeinstall](https://github.com/GRIS-UdeM/SpatGRIS/assets/108013856/2f15053b-983b-4667-9eea-08ed187cf682)

3-Lorsque j'ouvre ma session ableton, le message suivant apparait: ''failed to load the VST3 pluging Controlgris''

![failedtoloadplugin](https://github.com/GRIS-UdeM/SpatGRIS/assets/108013856/7c5b1e25-12c9-4d1f-a9d6-58fe76731567)

4-Le plugin de controlgris n'apparait plus dans ma liste de VST et est grisé dans ma track. 

![plugindoesntexist](https://github.com/GRIS-UdeM/SpatGRIS/assets/108013856/4b23395d-9c57-4a24-a4a8-97c4bcd4af0a)

**Comment by OKGougou** [comment]
De mon côté, cela ne concerne que la version VST3 de ControlGris (sur Windows).
Le format VST3 est récemment passé de fichier DLL à un répertoire (bundle), et une option de l'installateur fait en sorte que le VST3 de ControlGris est effectivement désinstallé si on ne le sélectionne pas à l'installation.
Ce sera corrigé dans la prochaine version.

**Comment by OKGougou** [comment]
À titre informatif :
ControlGris VST3 est un DLL pour les versions CG 1.4.1 et antérieures (installateur de SpatGris 3.2.10).
ControlGris VST3 est un bundle depuis la version 1.4.2 (SpatGris 3.2.11 et versions ultérieures).

L'installateur de SpatGris 3.3.4 ne désinstallera pas ControlGris VST3 s'il n'est pas sélectionné.
Mais, installer ControlGris via SpatGris 3.2.10 (ou toute autre version DLL antérieure) après avoir préalablement installé ControlGris via SpatGris 3.3.4 (bundle) générera une erreur. Il faudra que l'utilisateur efface manuellement ControlGris.vst3 (C:\Program Files\Common Files\VST3\ControlGris.vst3) pour que l'installation fonctionne.

**Comment by Normandeau** [comment]
Information capitale! Doit-on l'inclure dans le Read Me de l'installeur Windows et dans le manuel? Je pense que oui. Si c'est le cas, c'est quoi un DDL?
Direct Download Library?

**Comment by OKGougou** [comment]
Je m’emmêle les pinceaux ce matin... Il n'y a pas de DLL pour les VST3. Ce qui change, c'est que ControlGris n'est plus un fichier, mais un bundle, un peu comme les applications sous MacOS. Je récris mon précédent message:

ControlGris VST3 est un **fichier** pour les versions CG 1.4.1 et antérieures (installateur de SpatGris 3.2.10).
ControlGris VST3 est un bundle depuis la version 1.4.2 (SpatGris 3.2.11 et versions ultérieures).

L'installateur de SpatGris 3.3.4 ne désinstallera pas ControlGris VST3 s'il n'est pas sélectionné.
Mais, installer ControlGris via SpatGris 3.2.10 (ou toute autre version antérieure) après avoir préalablement installé ControlGris via SpatGris 3.3.4 générera une erreur. Il faudra que l'utilisateur efface manuellement ControlGris.vst3 (C:\Program Files\Common Files\VST3\ControlGris.vst3) pour que l'installation fonctionne.

**Comment by GabrielCaux** [comment]
Hello, je viens de tester plusieurs installations/désinstallations... Tout fonctionne comme indiqué dans le dernier commentaire, il faudrait juste ajouter une note au manuel pour dire d'effacer manuellement ControlGris.vst3 (C:\Program Files\Common Files\VST3\ControlGris.vst3), dans le cas ou un utilisateur voudrait installer une ancienne version de Spatgris (3.2.10 et avant) lorsqu'une nouvelle version est déjà installée.

**Comment by GabrielCaux** [comment]
Les tests que j'ai fait plus en détails:

Test01:
1-La version Spatgris 3.3.3 et Control Gris 1.4.3 sont installées sur mon ordinateur. J’installe la nouvelle version Spatgris 3.3.4 et je ne sélectionne pas Control Gris 1.4.3 lors de l’installation.

2- Le plugin Control Gris 1.4.3 ne fût pas désinstallé lors de l’installation. Donc ça fonctionne.

Test02 :
1- J’ai la dernière version de SpatGris 3.3.4 et Control Gris 1.4.3 d’installé sur mon ordinateur et je vais installer une version antérieure (CG 1.4.1 et SG 3.2.10). Je n’ai pas préalablement désinstallé Control Gris 1.4.3.

2- Une erreur est effectivement générée.

Test03 :
1- J’ai la dernière version de SpatGris 3.3.4 et Control Gris 1.4.3 d’installé sur mon ordinateur et je vais installer une version antérieure (CG 1.4.1 et SG 3.2.10). J’ai cette fois-ci désinstallé manuellement ControlGris.vst3 (C:\Program Files\Common Files\VST3\ControlGris.vst3)
2-L’installation fonctionne. 


Test04 :
1- J’ai la version de SpatGris 3.2.10 et ControlGris 1.4.1 installé sur mon ordinateur. Je vais installer la nouvelle version SpatGris 3.3.4 et ControlGris 1.4.3. Tous les plug-ins de ControlGris sont sélectionnés lors de l’installation.

2-L’installation a fonctionnée.

**Comment by GabrielCaux** [comment]
P-e même serait-il possible de rajouter cette indication dans le message d'erreur lorsqu'il apparait? Comme ça même ceux qui n'auraient pas consulter le manuel saurait quoi faire

**Comment by OKGougou** [comment]
Le message d'erreur apparaît lorsqu'on installe une ancienne version sur une version récente. Je ne peux pas modifier une ancienne publication.
Je pense que le meilleur endroit où ajouter l'information est le manuel. Je peux aussi l'ajouter au README.
