### ISSUE TITLE
Save Project window pops up behind SpeakerView window  v.3.3.1

### ISSUE THREAD

**Issue by GabrielCaux** [GRIS-UdeM/SpatGRIS#430]
Quand je cliques sur l'onglet File de SpatGRIS puis que je clique sur ''Save Project'', la fenêtre du Save Project apparait et se place derrière le SpeakerView. Je pense que la fenêtre devrait apparaitre en avant des deux fenêtres.

https://github.com/GRIS-UdeM/SpatGRIS/assets/108013856/0669bda0-606f-4cc3-af92-0d73a8425236

**Comment by Normandeau** [comment]
Deux questions ici.
1. C'est probablement Save Project As dont tu parles n'est-ce pas? 
Parce que Save Project n'ouvre pas de fenêtre (sur Mac en tout cas).
2. Est-ce que l'option Keep Speaker View On Top est activée?
Parce que si c'est le cas, c'est peut-être un comportement normal, la fenêtre Save Project As faisant partie de SpatGRIS, il est peut-être normal qu'elle se place derrière Speaker View, qui est toujours à l'avant-plan avec cette option cochée.

Vérification sur Mac Ventura: le fenêtre Save Project As se place en avant-plan à l'ouverture de celle-ci, même  avec l'option Keep Speaker View On Top activée. Si on clique sur Speaker View, alors elle passe en arrière-plan, mais elle revient à l'avant dès qu'on clique sur celle-ci ou sur SpatGRIS. Ce qui est un comportement normal pour moi.
Comportement différent macOS et Windows?

**Comment by GabrielCaux** [comment]
Je ne vois pas l'option ''Keep Speaker View On Top'' ? C'est ou?

**Comment by Normandeau** [comment]
Ici, Menu View:

![SpatGRIS Windows View Menu New](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/4c786ef3-1e60-413a-b5b9-39d76bc56f22)

**Comment by GabrielCaux** [comment]
Hello, ici c'est réglé avec la version Spatgris 3.3.2.  !

**Comment by Normandeau** [comment]
Perfecto!
