### ISSUE TITLE
Speaker view n’affiche pas correctement les changements effectués dans Speaker setup edition window 

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#435]
Lorsque je modifie la position de haut-parleurs dans Speaker setup edition window (en mode CUBE) alors que Speaker View est ouvert, les modifications graphiques dans la fenêtre Speaker view ne se mettent plus à jour après quelques changements et celle-ci affiche parfois des informations erronées, avant de cesser de répondre. Il faut à chaque fois fermer la fenêtre Speaker view et la réouvrir pour que l’affichage soit à nouveau cohérent avec la configuration réelle.

Pas encore testé sous macOS et Linux

**Comment by OKGougou** [comment]
(J'ai transféré l'issue de SpeakerView ici. On garde les issues de SpeakerView avec celles de SpatGris.)

Quelles versions de SpeakerView et de SpatGris?

Pour SpeakerView 0.0.4, en effet, les arêtes des haut-parleurs ne font pas face au centre quand on déplace un haut-parleur. Mais pas besoin de fermer et ouvrir SpeakerView pour corriger la situation, seulement cacher et montrer les haut-parleurs avec alt+S. (Ce sera corrigé dans une version ultérieure)

De mon côté, SpeakerView ne cesse jamais de répondre aux modifications de Edit Speaker Window.

**Comment by NicolaGiannini** [comment]
V3.3.4 SV004
MacIntel 2,9 GHz Intel Core i7 quad-core avec MacOs 13.6.3
Dans mon cas, tout semble fonctionner comme prévu, à l'exception de ce que Gaël a indiqué : 

>  les arêtes des haut-parleurs ne font pas face au centre quand on déplace un haut-parleur. Mais pas besoin de fermer et ouvrir SpeakerView pour corriger la situation, seulement cacher et montrer les haut-parleurs avec alt+S.

**Comment by NicolaGiannini** [comment]
V335 SV005
Maintenant, les arêtes des haut-parleurs font face au centre quand on déplace un haut-parleur.
