### ISSUE TITLE
Can't route ASIO  audio on windows - can not select different ASIO device for input and output

### ISSUE THREAD

**Issue by trackme518** [GRIS-UdeM/SpatGRIS#436]
Hi,
I have a problem in Windows - I can not select different device for input and another for output. I also can not select output channels as input. Both of which makes it almost impossible to use spatgris on windows without other routing tools.

![asio_same_input_output_device](https://github.com/GRIS-UdeM/SpatGRIS/assets/50262885/336416d0-501d-4e5a-9c99-4279037f915c)

The ASIO device has to be the same for input AND output for some reason. But since I can only select "input" for the input in spatgris I can not stream audio there unless some serious hacking with various routing tools. Normally programs and libraries are coded so that they can only output audio into asio output channels. 

But spatgris is expecting asio "input" channels. 

Can you please make the menu so I can select different asio device for input and different one for output and let me choose if I want to use input or output channels? Alternatively enable at least selecting output channels for input at certain indexes. I for example stream my audio on channels 24-34 (which I would like to recieve as audio sources in spatgris) and output to speakers from spatgris on channels 1-24.

Currently it can not be used without routing software, matrices and loopbacks. It would help a lot if you can figure out how to let the user choose various devices for input / output.

**Comment by led78** [comment]
You have to use a virtual routing software like JACK as ASIO doesn’t support multiple audio devices (unrelated to SpatGRIS). This is standard usage, as explained in the documentation : https://github.com/GRIS-UdeM/SpatGRIS#using-a-virtual-audio-device

**Comment by led78** [comment]
Non issue - standard usage

**Comment by trackme518** [comment]
ok, thanks for clarification
