### ISSUE TITLE
LAWO R3LAY fonctionne comme alternative (payante) à JACK et DVS

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#439]
Simplement pour vous informer qu'il existe une alternative à l'emploi de JACK pour le routage interapplication sous Windows :[ LAWO R3LAY Virtual Patch Bay (VPB)](https://lawo.com/products/r3lay-vpb/). LAWO développe également sa propre interface audio virtuelle, compatible avec RAVENNA/AES67, comme alternative -- à Dante Virtual Soundcard (DVS) -- de sortie multicanal (64 canaux), via le port ethernet d'un ordinateur : [R3LAY Virtual Soundcard (VSC)](https://lawo.com/products/r3lay-vsc/).

**Comment by Acousmachin** [comment]
Il y a aussi VB Matrix (donationware) qui fonctionne parfaitement et Coconut qui supporte 256 canaux : https://vb-audio.com/Matrix/index.htm

**Comment by GabrielCaux** [comment]
J’ai downloadé et installé RELAY VPB virtual patchbay un logiciel qui serait une alternative payante de JACK pour voir comment ça fonctionne. Conclusion : le logiciel RELAY VPB est très facile à utiliser, pour l’instant ça fonctionne sur mon ordi avec Windows, en réduction binaural (seulement 2 sorties) et la carte de son de mon ordinateur. Peut-être un peu plus facile de se mélanger dans l’assignations des numéros de sorties que JACK s’il y en a beaucoup, mais plus facile à utiliser que JACK en général (pas besoin de modifier les fichiers dans les dossiers comme le notepad.ini) et je pense qu’il y a plus de fonctions que JACK par exemple pour faire du mixage et ajouter des effets… Cependant je ne sais pas combien le logiciel RELAY VPB coute$, on dirait qu’il faut leur envoyer un email pour obtenir le prix et une licence.
