### ISSUE TITLE
Les numéros de hp ne sont pas rafraichis lorsqu'on les change dans Speaker Setup Edition

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS#442]
V335
SV 005 Forward
macOS 14.4.1, M2 Max
Lorsqu'on modifie les numéros de sortie d'un speaker setup dans Speaker Setup Edition, après avoir sauvegardé ou sauvegardé sous, les numéros ne sont pas rafraichis dans Speaker View.
Pour qu'ils soient mis à jour, il faut ouvrir un autre speaker setup et ensuite rouvrir le speaker setup modifié pour les voir mis à jour.
Autrement dit il faut fermier et rouvrir le speaker setup modifié pour voir les bonnes valeurs affichées dans Speaker View.

Voir ici. Dans ce dispositif, j'ai changé les numéros 11-12 pour 15-16 et j'ai sauvegardé.
Ce sont toujours les numéros 11-12 qui s'affichent, même après avoir fermé la fenêtre Speaker Setup Edition:

![Capture d’écran, le 2024-05-06 à 09 40 00](https://github.com/GRIS-UdeM/SpatGRIS/assets/8959779/9a6a9753-af2a-4375-8ee6-e44d378100f4)

**Comment by led78** [comment]
Même chose que l’issue #435 ?

**Comment by NicolaGiannini** [comment]
V335
SV 005 Forward
2.9 GHz Intel Core i7 quad-core MacOs 13.6.6 Ventura
Je confirme que lorsqu'on modifie les numéros de sortie d'un speaker setup dans Speaker Setup Edition, après avoir sauvegardé ou sauvegardé sous, les numéros ne sont pas rafraichis dans Speaker View.

Par contre, les valeurs Speakers (celles qui sont en dessous de Sources) dans SpatGRIS semblent se comporter comme prévu.

Dans mon cas, j'ai également remarqué une autre chose dans SpeakerView. La réouverture du template de départ après l'ouverture de sa version modifiée entraîne une erreur d'affichage dans les numéros des haut-parleurs du template.

Étapes pour reproduire l'issue: 
J'ouvre un template (dans ce cas Dome10(-2)subs2)
Je modifie un numéro de sortie (11 pour 31)
Je sauvegarde.
J'ouvre un autre template pour faire afficher les bons numéros, comme indiqué par Robert.
Je réouvre le template modifié: les numéros sont bons. (31 est affiché à la place du 11).
![Screenshot 2024-05-06 alle 13 52 15](https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/bdf3c693-e7c1-4a5a-b7a3-71ea5b200ee2)

Je réouvre le template à partir duquel j'ai fait la modification: les numéros ne sont pas corrects. On dirait que la gauche et la droite sont inversées. Le HP 31 se retrouve à droite et le HP 12 est à gauche.
![Screenshot 2024-05-06 alle 13 52 46](https://github.com/GRIS-UdeM/SpatGRIS/assets/35705913/1b921263-da77-4517-a817-140ce8ad37b1)

**Comment by Normandeau** [comment]
Alt-S (Show Speaker) replace les bons chiffres (en attendant une correction complète)

**Comment by Normandeau** [comment]
V006
Problème de rafraichissement des numéros de hp résolu.
