### ISSUE TITLE
Max crashes when inserting ControlGRIS as a vst~ object

### ISSUE THREAD

**Issue by hectorC** [GRIS-UdeM/SpatGRIS#443]
In Max 8.6.2 (Windows 11) inserting ControlGRIS as either VST or VST3 in a vst~ object causes Max to crash immediately (with or without audio enabled). The plugin loads fine in Reaper.

<img width="602" alt="image" src="https://github.com/GRIS-UdeM/SpatGRIS/assets/4064498/acd38413-ab34-4185-8371-cc9ab549e051">

**Comment by DavidPiazza** [comment]
This is a documented ControlGRIS issue, not a problem that pertains to SpatGRIS.

**Comment by hectorC** [comment]
Thank you for your reply. My apologies, I didn't realize there's a separate repo for ControlGRIS.
