### ISSUE TITLE
💄 Déplacer dans la fenêtre SpeakerViewer la portion du menu View qui ne concerne que Speaker View et ajouter une option Settings

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#444]
![Capture d’écran, le 2024-06-12 à 09 40 05](https://github.com/GRIS-UdeM/SpatGRIS/assets/13606544/ad09460e-2db1-4f02-88bf-3c5c29bbecd8)

Actuellement, tous les paramètres concernant l'affichage de SpeakerView sont dans le menu View de SpatGRIS.

Dans l'optique où l'[on souhaiterait relier une fenêtre Speaker View à une instance de SpatGRIS de façon modulaire](https://github.com/GRIS-UdeM/SpatGRIS/issues/440), à l'instar de la connexion ControlGRIS-SpatGRIS, exposant adresse IP et port de connexion (UDP ou OSC), l'inclusion d'un menu dans SpeakerView permettrait d'y inclure une option Settings qui ouvrirait une fenêtre intégrant les champs respectifs pour ce faire.

**Comment by rochanaf** [comment]
On pourrait exposer les ports UDP dans cette fenêtre de SpeakerView qui s'ouvre avec le raccourci F4 
![image](https://github.com/GRIS-UdeM/SpatGRIS/assets/36674549/c0d1891b-b261-42c5-be59-8b889617acb5)

**Comment by led78** [comment]
Parfait! Mieux vaut respecter la décision de garder les paramètres d'affichage centralisés à l'intérieur du menu View de SpatGRIS et exposer les champs pour modifier le port UDP au menu setting accessible en F4.

**Comment by led78** [comment]
Je vais fermer ce billet.
