### ISSUE TITLE
✨Menu View : ajouter une option permettant de désactiver la fixation de l'angle de la caméra vers l'origine 0 de la représentation graphique de SpeakerView

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS#446]
Il est parfois pénible de construire une configuration de haut-parleurs non concentriques alors que la vue demeure orientée vers le centre. Une option d'affichage dans un menu qui permettrait de désactiver l'ancrage de la caméra vers le centre pour permettre une navigation libre de la caméra dans l'environnement 3D serait la bienvenue.

**Comment by Normandeau** [comment]
C'est fait voir 445
